Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Structure.Terminal.
Require Import Category.Structure.Cartesian.

Generalizable All Variables.

(** * Lawvere theories *)

(* nLab:      https://ncatlab.org/nlab/show/Lawvere+theory
   Wikipedia: https://en.wikipedia.org/wiki/Lawvere_theory

   A Lawvere theory, in the classical sense, is a category with finite
   products whose objects are (in bijection with) the natural numbers,
   with the object [n] the n-fold product of the object [1] — so that
   [0] is the terminal object and products on objects are addition.

   In this library's setoid-based, universe-polymorphic setting we mirror
   the relaxed shape of [Construction/PROP.v]'s [PROP] class: rather than
   asserting [obj law_cat = nat] directly, we supply a naming function
   [law_of_nat : nat -> obj] together with propositional strictness
   equalities on OBJECTS (the sanctioned Type-level use of [=] in this
   library — morphism equality is always [≈]):

     law_zero_terminal : law_of_nat 0 = 1        (the terminal object)
     law_plus_product  : law_of_nat m × law_of_nat n = law_of_nat (m + n)

   These bind the cartesian structure to the additive monoid on ℕ at the
   Leibniz level, and are discharged by [eq_refl] on skeletal base
   instances (where the objects really are the natural numbers).

   Like [PROP], this class does NOT require [law_of_nat] to be bijective
   (or even surjective) on objects.  Omitting bijectivity captures the
   relaxed "Lawvere-theory-like" notion — a cartesian category whose
   object monoid is generated by ℕ under products — which suffices for
   the functorial-semantics development.  A consumer needing reachability
   of all objects states it as an explicit hypothesis
   (Theory/Lawvere/Sets.v does). *)

Class LawvereTheory : Type := {
  law_cat : Category;

  law_terminal : @Terminal law_cat;
  law_cartesian : @Cartesian law_cat;

  (** The canonical object correspondence: every natural number names an
      object of [law_cat], with [0] the terminal object and addition
      reflecting binary products. *)
  law_of_nat : nat → law_cat;

  law_zero_terminal :
    law_of_nat 0%nat = @terminal_obj law_cat law_terminal;

  law_plus_product : ∀ m n : nat,
    (@product_obj law_cat law_cartesian (law_of_nat m) (law_of_nat n))
    = law_of_nat (m + n)%nat
}.

Coercion law_cat : LawvereTheory >-> Category.

(** ** Powers of the generic object

    [law_pow n] is the explicit n-fold product of [law_of_nat 1]
    (right-nested, with the empty product the terminal object), and
    [law_pow_one] is the propositional equality chain showing it agrees
    with [law_of_nat n] — by induction from [law_zero_terminal] and
    [law_plus_product].  Ends in [Defined] so downstream transports can
    compute through the equality. *)

Section LawverePow.

Context {T : LawvereTheory}.

Fixpoint law_pow (n : nat) : law_cat :=
  match n with
  | O => @terminal_obj law_cat law_terminal
  | S k => @product_obj law_cat law_cartesian (law_of_nat 1%nat) (law_pow k)
  end.

Theorem law_pow_one (n : nat) : law_pow n = law_of_nat n.
Proof.
  induction n as [|k IH]; simpl.
  - symmetry; apply law_zero_terminal.
  - rewrite IH. apply (law_plus_product 1%nat k).
Defined.

End LawverePow.

