(** * Probe for the group-action monad and its algebras (issue #464)

    Pins the measured boundaries of the two files #464 adds for Mac Lane
    §VI.2, "Group actions", book p. 141 (PDF p. 150), catalog item
    maclane:VI.2:remark2, with the appended Riehl Exercise 5.5.iv, printed
    p. 208 (PDF p. 228), catalog item riehl:5.5:exiv.  The files are
    Instance/Fun/Action/Monad.v (the monad G × (−) as the monad of the
    free/forgetful adjunction on Instance/Fun/Action.v's M-sets, its
    algebras identified with the M-sets by the comparison functor, and the
    forgetful functor monadic twice, by Beck's theorem and by an explicit
    quasi-inverse) and Instance/Fun/Action/Monad/BG.v (Riehl's Set^BG
    literally: evaluation on [Deloop M, Sets] monadic by Beck's theorem, and
    the functor θ* on algebras that carries its comparison functor onto the
    first file's equivalence).  N1-N20 restate refusals that #464's two
    builders, their two reviews, the fold and the fold's review measured in
    scratch files (LABELS, below); every one is recorded in a target header,
    which cites it by its label here.  The positive controls restate the
    files' claims independently.
    CORRECTION (#1347): N3 now holds at [eq_refl], since Instance/Sets.v
    gives its identity's and composite's properness fields as terms; it is
    a control, and keeps its label.

    THE IMPORT LIST, generated by a script over the [Require] lines.
    Target by target in dependency order: Instance/Fun/Action/Monad.v's
    twenty-five [Require] lines in its own order, and that target; then
    the two lines Instance/Fun/Action/Monad/BG.v adds to those, in its own
    order (Monad/Eilenberg/Moore/Adjunction.v and Instance/Fun/Eval.v),
    and that target.  Twenty-nine lines, all naming [Category] modules.
    Under this list [Print Libraries] in a scratch file loads one hundred
    and twelve [Category] modules, the two targets among them, which is
    the whole dependency closure of Instance/Fun/Action/Monad/BG.v
    (compared by script with the closure of its [Require] lines).  A
    shorter import list is what makes a probe pass for no reason.

    DISCIPLINE.  The instrument was checked both ways: a false statement
    about the targets is refused for that reason (the instrument, below),
    and each of the thirty-four definitions and examples of this file that
    is not a refutation (thirty-two controls and the two helpers
    [p464_ActF_hand] and [p464_SetBG_h]), wrapped in the refutation keyword
    in a copy of this WHOLE file, stops the build at that command with the
    message Rocq prints for a refutation whose command succeeds (thirty-four
    of thirty-four, by a script over the copies, which compares the File
    line of the error with the wrapped line).  Every negative is a
    [Definition] or an [Example], never a [Check], so that an open evar
    cannot satisfy it.  Each negative was stripped of its refutation keyword
    in a copy of this WHOLE file, one at a time, compiled, and its error
    read; each of the twenty-one copies stops inside the stripped command
    (by the File line of its error, compared by a script with the command's
    extent).  The kind recorded is the kind of that error, and each negative
    has positive controls beside it.  Quotations are Rocq 9.1.1's under this
    file's import list, with the error's environment block left out; Rocq
    prints the "cannot unify" parenthetical with the short names in scope,
    and <1> to <3> stand for the universes a stripped copy names after
    itself and a serial number.  The two targets and this file also compile
    on Coq 8.19.2 and 8.20.1, with no warning from any of them, overlaid on
    the prebuilt trees of this library for those versions, whose sources of
    the one hundred and ten other modules this file loads are this tree's
    byte for byte (compared by script); the two targets were compiled there,
    then this file.  Each of the twenty-one stripped copies is refused there
    inside the stripped command, at the File line of the Rocq 9.1.1 refusal,
    and with the Rocq 9.1.1 error up to the serial names of universes
    (compared by a script), with one exception, N17: Coq 8.19.2 prints its
    type mismatch without the parenthetical that names the universe
    inconsistency, and both older versions mark the term [Sets@{o so}]
    (characters 28-39 of its line) where Rocq 9.1.1 marks [Sets] (28-32).
    CORRECTION (#1347): N3 is a control now.  Wrapped in the refutation
    keyword in a copy of this WHOLE file, it stops the build at that
    command with that message, so the definitions and examples that are
    not refutations are thirty-five.  The refutations are twenty, and
    each of the twenty, stripped in a copy of this WHOLE file, stops
    inside its command with the error it printed before #1347 (compared
    by script, universe serial names aside).  Both measurements on Rocq
    9.1.1 only; the older versions were not re-run.

    KINDS.  Twenty-one refutations, counted as the lines that open with the
    refutation keyword: CONVERSION (the instrument, N1-N16, N19, N20) and
    UNIVERSE (N17, N18): nineteen and two.  A CONVERSION refusal is
    [eq_refl] refused with a "cannot unify" parenthetical; a UNIVERSE
    refusal is a type mismatch whose parenthetical, where one is printed, is
    a universe inconsistency.  Each CONVERSION refusal of N1-N20 also has a
    CAUSE, read off the flips below and, where named, off the fields and
    normal forms: STRUCTURAL (the two sides reduce to different terms, or to
    stuck projections of the variable data, and no flip of the tree changes
    that: N1, N2, N4-N16, N19, N20) and STDLIB (the residue is an opaque
    constant of the standard library, which no flip of the tree reaches:
    N3).  The flips, each in a copy of a dependency closure with every [Qed]
    turned into [Defined] and [Transparent Obligations] set:
    (i) #464's first review, Instance/Fun/Action/Monad.v's closure,
    Instance/Sets.v, Structure/Cartesian/Closed.v and Instance/Grp.v keeping
    their [Qed]s and Structure/Limit/Preservation.v's [preserves_colimit],
    which no compared term uses, made opaque: all of N1-N12 are refused
    there (a builder's draft of this file, whose twelve refutations are
    these, compiles there, measured again by the fold);
    (ii) the fold's, Instance/Fun/Action/Monad/BG.v's closure with the final
    targets, Instance/Grp/Free.v also keeping its [Qed]s and
    [preserves_colimit]'s two bullets rewritten into one, since the added
    transparency leaves it one goal: this whole file compiles there, and
    each of the twenty-one refutations, stripped there, prints the error of
    the unchanged tree (by script).  Instance/Grp/Free.v keeps its [Qed]s
    because the second builder kept every file the first had measured,
    although the first found that its flip alone builds; the choice is
    harmless, since copies of the two targets without the imports of
    Instance/Grp.v and Instance/Grp/Free.v and without their six group twins
    compile and load neither file, so no refused or compared term here
    depends on either.  [About] there reports Theory/Functor.v's
    [Compose_obligation_1], Instance/Fun/Eval.v's [Eval_obligation_1],
    Instance/Sets.v's [Sets_obligation_1] and the target's [split_absorb]
    transparent, all four opaque in this tree, and Corelib's
    [subrelation_id_proper] opaque in both.
    A third copy, #464's first review's, changes only Instance/Sets.v's
    [setoid_morphism_id], its properness proof written as fun _ _ H => H:
    there N3 holds at [eq_refl] and every other refutation of this file is
    still refused: N1, N2 and N4-N12 in that copy, with a cut of this file
    (measured again by the fold), and all twenty in that copy extended by
    Instance/Fun/Action/Monad/BG.v and the two further modules of its
    closure, where the whole of this file with N3's refutation keyword
    removed compiles (the fold's review, with this file before N20, and the
    second fold, with this file).
    CORRECTION (#1347): the third copy's change is now the tree's, with
    [setoid_morphism_compose]'s field written as a term too: N3 holds at
    [eq_refl] and is a control.  The refutations are twenty, CONVERSION
    eighteen (the instrument, N1, N2, N4-N16, N19, N20) and UNIVERSE two,
    and every CONVERSION refusal of N1-N20 that remains is STRUCTURAL.
    N3's classification, STDLIB, was right, as the third copy measured;
    the flips (i) and (ii) describe the tree before #1347.

    LABELS.  Builder-1's draft refutations rt_op, rt_unit, rt_respects,
    rt_obj, rt_functor, rt2_functor, rt2_fun, rt2_obj, beck_qi,
    beck_act_strict, monadic_same and hand_is_composite (its report's
    R1-R12) are N1-N12; builder-2's bg_ret_strict, bg_T_is_ActF,
    bg_join_fun, bg_U_is_composite, bg_down_h and bg_F_h (R13-R18) are
    N13-N18.  Here every name carries the prefix p464_.  The first review's
    E5, E6 and E7 are the controls [p464_rt2_eta],
    [p464_rt_respects_isolate] and [p464_rt_respects_eta]; the second
    review's e7c is the control [p464_bg_join_morphism].  N19, the
    instrument and the controls [p464_join_fun], [p464_fun_em_to],
    [p464_tie_carrier] and [p464_tie_alg] are the fold's own; N20 and its
    control [p464_tie_alg_morphism] are the fold's review's (measured again
    by the second fold).  The labels are not constants: each refutation
    carries its own in a comment on the line above it, the instrument's
    reading "The instrument".
    CORRECTION (#1347): N3, builder-1's rt_respects, is a control now
    and keeps its label in the comment on the line above it.

    ** The instrument

    Control: Mac Lane's μ at a triple, in his order
    ([p464_instrument_ctl]).
    The instrument (CONVERSION).  The same with the factors exchanged:
      (cannot unify "join[_] (g1, (g2, x))" and "(mon_op g2 g1, x)")

    ** Instance/Fun/Action/Monad.v: the monad and the two Cat isomorphisms

    Controls: η at a point, μ as a function, and the [to] legs of the two
    Cat isomorphisms, the comparison functor on both routes ([p464_ret],
    [p464_join_fun], [p464_to], [p464_beck_to]).

    ** Instance/Fun/Action/Monad.v: the round trip M-set → algebra → M-set

    Controls: the carrier and the action as a function, at [eq_refl]
    ([p464_rt_setoid], [p464_rt_act]); the [act_respects] field is
    [act_respects A] with its last argument passed through the identity
    map's properness proof, and without that proof it is [act_respects A]
    by eta ([p464_rt_respects_isolate], [p464_rt_respects_eta]).

    N1 (CONVERSION, STRUCTURAL).  The action law of the round trip, a
    composite proof and the symmetry of [t_action]:
      (cannot unify "act_op (fobj[EM_to_MSet M ◯ EM_Comparison (MSet_adj
      M)] A)" and "act_op A")
    N2 (CONVERSION, STRUCTURAL).  The unit law, a composite proof; its
    normal form (the first review's, in a copy that combines flip (i)
    with the third copy's change) is headed by Corelib's
    [CMorphisms.trans_co_eq_inv_arrow_morphism_obligation_1], whose body
    is a transitivity of the variable setoid, where [act_unit A] is a
    projection of the variable action: neutral terms with different
    heads:
      (cannot unify "act_unit (fobj[EM_to_MSet M ◯ EM_Comparison
      (MSet_adj M)] A)" and "act_unit A")
    N3 (CONVERSION, STDLIB).  The properness law: [act_respects A] but for
    Corelib's opaque [subrelation_id_proper] (the controls above, and the
    third copy):
      (cannot unify "act_respects (fobj[EM_to_MSet M ◯ EM_Comparison
      (MSet_adj M)] A)" and "act_respects A")
    CORRECTION (#1347): N3 now holds at [eq_refl], since Instance/Sets.v
    gives its identity's and composite's properness fields as terms; it
    is a control.  The identity map's properness proof is now
    fun _ _ H => H, and the field is [act_respects A] by eta, as the
    controls above read it.
    N4 (CONVERSION, STRUCTURAL).  The whole M-set, whose law fields are
    N1-N3:
      (cannot unify "fobj[EM_to_MSet M ◯ EM_Comparison (MSet_adj M)] A"
      and "A")
    CORRECTION (#1347): of those law fields N3's now converts; N4 is
    still refused, N1's and N2's fields still differing.
    N5 (CONVERSION, STRUCTURAL).  The composite as the identity functor:
      (cannot unify "EM_to_MSet M ◯ EM_Comparison (MSet_adj M)" and
      "Id[MSet M]")

    ** Instance/Fun/Action/Monad.v: the round trip algebra → M-set →
    algebra

    Controls: the carrier, the structure map at each pair, and the
    structure map as the function p ↦ h (fst p, snd p), at [eq_refl]
    ([p464_rt2_carrier], [p464_rt2_pointwise], [p464_rt2_eta]).

    N6 (CONVERSION, STRUCTURAL).  The composite as the identity functor:
      (cannot unify "EM_Comparison (MSet_adj M) ◯ EM_to_MSet M" and
      "Id[EilenbergMoore (ActF M)]")
    N7 (CONVERSION, STRUCTURAL).  The structure map as a function: Coq's
    [prod] has no eta, and the round trip reads h (fst p, snd p) (the
    control [p464_rt2_eta]):
      (cannot unify "λ p : fobj[MSet_Forget M ◯ MSet_Free M] (projT1
      (fobj[EM_Comparison (MSet_adj M) ◯ EM_to_MSet M] x)),
      t_alg[projT2 (fobj[EM_Comparison (MSet_adj M) ◯ EM_to_MSet M] x)]
      p" and "λ p : fobj[MSet_Forget M ◯ MSet_Free M] (projT1
      (fobj[EM_Comparison (MSet_adj M) ◯ EM_to_MSet M] x)), t_alg[`2
      (x)] p")
    N8 (CONVERSION, STRUCTURAL).  The whole algebra, whose structure map
    is N7's:
      (cannot unify "fobj[EM_Comparison (MSet_adj M) ◯ EM_to_MSet M] x"
      and "x")

    ** Instance/Fun/Action/Monad.v: Beck's route against the direct one

    Controls: Beck's quasi-inverse keeps the carrier and acts through η
    ([p464_beck_carrier], [p464_beck_act]).

    N9 (CONVERSION, STRUCTURAL).  Beck's quasi-inverse as [EM_to_MSet],
    whose actions differ (N10):
      (cannot unify "quasi_inverse" and "EM_to_MSet M")
    N10 (CONVERSION, STRUCTURAL).  Its action as h (g, z); it reads
    h (g u, z), and mon_op g mon_unit is stuck for a variable monoid:
      (cannot unify "act (fobj[quasi_inverse] x) g z" and "t_alg[`2 (x)]
      (g, z)")
    N11 (CONVERSION, STRUCTURAL).  The two [Monadic] witnesses as one
    term, whose equivalences have different quasi-inverses (N9):
      (cannot unify "MSet_Forget_Monadic M" and "MSet_Forget_Monadic_direct
      M")

    ** Instance/Fun/Action/Monad.v: the hand-built functor G × (−)

    Controls: the same object and arrow maps as [ActF M] at [eq_refl],
    and ≈ to it with identity components ([p464_hand_obj],
    [p464_hand_map], [p464_hand_equiv]).

    N12 (CONVERSION, STRUCTURAL).  The hand-built functor as [ActF M]; each
    of its proof fields [fmap_respects], [fmap_id] and [fmap_comp] is
    refused alone in flip (i)'s tree (the first review, and again the second
    fold):
      (cannot unify "p464_ActF_hand M" and "ActF M")

    ** Instance/Fun/Action/Monad/BG.v: the two monads

    Controls: the literal unit reads (u u, x); the two monads have the
    same object and arrow maps, the same multiplication at every p and
    the same underlying multiplication function; the [to] leg of
    [BG_EM_iso] is the comparison functor ([p464_bg_ret],
    [p464_bg_T_obj], [p464_bg_T_map], [p464_bg_join_pointwise],
    [p464_bg_join_morphism], [p464_bg_EM_to]).

    N13 (CONVERSION, STRUCTURAL).  The literal unit as Mac Lane's (u, x);
    mon_op mon_unit mon_unit is stuck for a variable monoid:
      (cannot unify "ret[_] x" and "(mon_unit, x)")
    N14 (CONVERSION, STRUCTURAL).  The two functors as one record; each
    of its proof fields [fmap_respects], [fmap_id] and [fmap_comp] is
    refused alone (the second review):
      (cannot unify "U_BG M ◯ F_BG M" and "ActF M")
    N15 (CONVERSION, STRUCTURAL).  The two multiplications as one setoid
    morphism; their functions agree ([p464_bg_join_morphism]), and the
    properness proof of [BGMonad]'s chains M's symmetry and transitivity
    through two [mon_op_respects] steps where [ActMonad]'s takes one (the
    second review's normal forms):
      (cannot unify "@join _ _ (BGMonad M) X" and "@join _ _ (ActMonad M)
      X")

    ** Instance/Fun/Action/Monad/BG.v: evaluation

    Controls: evaluation against [MSet_to] followed by [MSet_Forget], in
    both data fields ([p464_bg_U_obj], [p464_bg_U_map]).

    N16 (CONVERSION, STRUCTURAL).  Evaluation as that composite; its
    [fmap_respects] reads H ttt z where the composite's is a transitivity
    of the variable setoid (the second review's normal forms):
      (cannot unify "U_BG M" and "MSet_Forget M ◯ MSet_to M")

    ** Instance/Fun/Action/Monad/BG.v: the hom level of Set^BG

    Controls: the functor category with its hom level raised to so is a
    category, functors into it are formable, and Instance/Fun/Action.v's
    [MSet_from] lands there ([p464_SetBG_h], [p464_bg_up],
    [p464_bg_from_h]); [MSet_Free] alone ([p464_bg_free]).

    N17 (UNIVERSE).  A functor type out of the raised category into Sets,
    refused by Theory/Functor.v's block h1 <= h2:
      The term "Sets" has type "Category@{so o o}" while it is expected
      to have type "Category@{<1> <2> <3>}" (universe inconsistency:
      Cannot enforce o = <2> because o < so <= <2>).
    N18 (UNIVERSE).  [MSet_from] after [MSet_Free] into the raised
    category, refused by [Compose]'s one hom universe:
      The term "MSet_from M" has type "@Functor@{so o o so so so}
      (MSet@{so so o o o o o o} M) (@Fun@{o o so o so so so} (Deloop@{o
      o} M) Sets@{o so})" while it is expected to have type
      "@Functor@{<1> <2> <2> <3> <2> <2>} ?D ?E" (universe inconsistency:
      Cannot enforce so = o because o < so).

    ** Instance/Fun/Action/Monad/BG.v: the tie

    Controls: the [to] leg of [Fun_EM_iso] is the comparison functor of
    [MSet_adj] after [MSet_to], and θ* after this file's comparison functor
    agrees with it on carriers, on structure maps as functions and in the
    [morphism] field of the structure map, at [eq_refl] ([p464_fun_em_to],
    [p464_tie_carrier], [p464_tie_alg], [p464_tie_alg_morphism]).

    N19 (CONVERSION, STRUCTURAL).  The tie on a whole object; the two
    algebras differ in their proof fields [t_id] and [t_action], and in the
    properness proof of the structure map, whose function agrees
    ([tie_alg_fun]; N20), each refused alone in this tree and in
    flip (ii)'s:
      (cannot unify "fobj[BG_Act_EM M ◯ EM_Comparison (BG_adj M)] P" and
      "fobj[Fun_EM_iso M] P")
    N20 (CONVERSION, STRUCTURAL).  The [proper_morphism] field of the tie's
    structure map, whose [morphism] field agrees (the control above): the
    two structure maps are the counits of different adjunctions, [BG_adj]
    and [MSet_adj] read through [MSet_to]:
      (cannot unify "proper_morphism t_alg[projT2 (fobj[BG_Act_EM M ◯
      EM_Comparison (BG_adj M)] P)]" and "proper_morphism t_alg[projT2
      (fobj[Fun_EM_iso M] P)]")

    ** Closure: a readback, not a refutation

    [Print Assumptions] of [ActMonad], [EM_MSet_iso],
    [MSet_Forget_Monadic], [U_BG_Monadic] and [tie], near the end of this
    file, each print "Closed under the global context".  A [Print
    Assumptions] cannot refuse, so these lines are readbacks and guard
    nothing; the Makefile's print-assumptions gate is where closure is
    kept.  By the same command all one hundred and four constants of the
    two targets are closed under the global context (measured in a
    scratch file, with a positive control: a local axiom is printed).

    NOT PINNED HERE.  (a) [About] readbacks as such: the headers'
    universe censuses, their attributions to first carriers, and the
    forced hom level of Set^BG as a level (N17 and N18 pin the two
    refusals behind it, not the level).  (b) The flips and the third copy
    above, and the field and normal-form readings behind the CAUSEs: made
    in copies of the dependency closure and in scratch files.  (c) The
    closure of the targets under [Print Assumptions]: a measurement of
    the build rather than of a command.  (d) The absences the headers
    record (no general morphisms of monads, no transport of [Monadic]
    along an equivalence, no isomorphism of categories on the nose, the
    converse half of Riehl's theorem not instantiated, no Kleisli
    category of G × (−)): an absence has no command; N4-N6 and N8 pin the
    round trips that an isomorphism on the nose would need.  (e) The
    readings of the books, from their page images.

    CORRECTION (#468).  Of the absences in (d), general morphisms of monads
    now exist: Monad/Morphism.v's [MonadHom] and [Monads C], and
    Monad/Morphism/Algebra.v's θ*.  Instance/Fun/Action/Monad/BG/Morphism.v
    relates this file's second target to them, and
    Test/ProbeMonadMorphism468.v pins that file.  The two targets are
    unchanged, and the other absences stand.

    The guard block at the end names the one hundred and four constants
    of the two targets, so that a rename breaks this file: fifty-eight of
    Instance/Fun/Action/Monad.v and forty-six of Instance/Fun/Action/
    Monad/BG.v.  They are exactly the entries [Print Module] gives for
    each, one hundred and two definitions and the two opaque lemmas
    [split_absorb] and [created_absorb]; neither target declares a
    record or has a [Program] obligation, so there is no [Build_]
    constructor to add.  Each is written fully qualified and with [@],
    so that no short name in scope can stand in for it. *)

Require Import Category.Lib.
Require Import Category.Lib.Setoid.Propositional.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Natural.Transformation.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Monad.
Require Import Category.Theory.Equivalence.
Require Import Category.Monad.Algebra.
Require Import Category.Monad.Eilenberg.Moore.
Require Import Category.Monad.Comparison.
Require Import Category.Monad.Monadicity.Beck.
Require Import Category.Structure.Coequalizer.
Require Import Category.Structure.Coequalizer.Split.
Require Import Category.Structure.Limit.Preservation.
Require Import Category.Structure.Group.
Require Import Category.Construction.Deloop.
Require Import Category.Construction.Deloop.Functors.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Cat.
Require Import Category.Instance.Fun.
Require Import Category.Instance.Fun.Action.
Require Import Category.Instance.Grp.
Require Import Category.Instance.Grp.Free.
Require Import Category.Instance.Fun.Action.Monad.
Require Import Category.Monad.Eilenberg.Moore.Adjunction.
Require Import Category.Instance.Fun.Eval.
Require Import Category.Instance.Fun.Action.Monad.BG.

Generalizable All Variables.

(** ** Instrument: a false statement is refused *)

(* CONTROL: Mac Lane's μ at a triple, in his order. *)
Example p464_instrument_ctl@{o so} (M : MonObject@{o o o})
  (X : SetoidObject@{o o}) (g1 g2 : carrier M) (x : carrier X) :
  (@join _ _ (ActMonad@{o so} M) X) (g1, (g2, x)) = (mon_op g1 g2, x) :=
  eq_refl.

(* The instrument *)
Fail Example p464_instrument@{o so} (M : MonObject@{o o o})
  (X : SetoidObject@{o o}) (g1 g2 : carrier M) (x : carrier X) :
  (@join _ _ (ActMonad@{o so} M) X) (g1, (g2, x)) = (mon_op g2 g1, x) :=
  eq_refl.

(** ** Instance/Fun/Action/Monad.v: the monad and the two Cat isomorphisms *)

(* CONTROL: η at a point and μ as a function, on the nose; the [to] legs
   of the two Cat isomorphisms. *)
Example p464_ret@{o so} (M : MonObject@{o o o}) (X : SetoidObject@{o o})
  (x : carrier X) :
  (@ret _ _ (ActMonad@{o so} M) X) x = (mon_unit, x) := eq_refl.

Example p464_join_fun@{o so} (M : MonObject@{o o o})
  (X : SetoidObject@{o o}) :
  (fun p => (@join _ _ (ActMonad@{o so} M) X) p)
  = (fun p : carrier M * (carrier M * carrier X) =>
       (mon_op (fst p) (fst (snd p)), snd (snd p))) := eq_refl.

Example p464_to@{o so c} (M : MonObject@{o o o}) :
  to (EM_MSet_iso@{o so c} M) = EM_Comparison (MSet_adj@{o so} M) := eq_refl.

Example p464_beck_to@{o so c} (M : MonObject@{o o o}) :
  to (EM_MSet_iso_beck@{o so c} M) = to (EM_MSet_iso@{o so c} M) := eq_refl.

(** ** Instance/Fun/Action/Monad.v: the round trip M-set → algebra → M-set *)

(* CONTROL: the carrier and the action as a function, on the nose. *)
Example p464_rt_setoid@{o so} {M : MonObject@{o o o}}
  (A : MSetoidAction@{o o o o o o o o} M) :
  act_setoid (fobj[EM_to_MSet@{o so} M ◯ EM_Comparison (MSet_adj@{o so} M)] A)
  = act_setoid A := eq_refl.

Example p464_rt_act@{o so} {M : MonObject@{o o o}}
  (A : MSetoidAction@{o o o o o o o o} M) :
  act (fobj[EM_to_MSet@{o so} M ◯ EM_Comparison (MSet_adj@{o so} M)] A)
  = act A := eq_refl.

(* CONTROL (the cause of N3): the [act_respects] field of the round trip
   is [act_respects A] with its last argument passed through the identity
   map's properness proof, and without that proof it is [act_respects A]
   by eta. *)
Example p464_rt_respects_isolate@{o so} {M : MonObject@{o o o}}
  (A : MSetoidAction@{o o o o o o o o} M) :
  act_respects
    (fobj[EM_to_MSet@{o so} M ◯ EM_Comparison (MSet_adj@{o so} M)] A)
  = (fun g g' Hg a a' Ha =>
       act_respects A g g' Hg a a'
         (@proper_morphism _ _ _ _
            (@setoid_morphism_id@{o o o} (act_setoid A)) a a' Ha)) :=
  eq_refl.

Example p464_rt_respects_eta@{o so} {M : MonObject@{o o o}}
  (A : MSetoidAction@{o o o o o o o o} M) :
  (fun g g' Hg a a' Ha => act_respects A g g' Hg a a' Ha) = act_respects A :=
  eq_refl.

(* N1 *)
Fail Example p464_rt_op@{o so} {M : MonObject@{o o o}}
  (A : MSetoidAction@{o o o o o o o o} M) :
  act_op (fobj[EM_to_MSet@{o so} M ◯ EM_Comparison (MSet_adj@{o so} M)] A)
  = act_op A := eq_refl.

(* N2 *)
Fail Example p464_rt_unit@{o so} {M : MonObject@{o o o}}
  (A : MSetoidAction@{o o o o o o o o} M) :
  act_unit (fobj[EM_to_MSet@{o so} M ◯ EM_Comparison (MSet_adj@{o so} M)] A)
  = act_unit A := eq_refl.

(* N3 *)
Example p464_rt_respects@{o so} {M : MonObject@{o o o}}
  (A : MSetoidAction@{o o o o o o o o} M) :
  act_respects
    (fobj[EM_to_MSet@{o so} M ◯ EM_Comparison (MSet_adj@{o so} M)] A)
  = act_respects A := eq_refl.

(* N4 *)
Fail Example p464_rt_obj@{o so} {M : MonObject@{o o o}}
  (A : MSetoidAction@{o o o o o o o o} M) :
  fobj[EM_to_MSet@{o so} M ◯ EM_Comparison (MSet_adj@{o so} M)] A = A :=
  eq_refl.

(* N5 *)
Fail Example p464_rt_functor@{o so} {M : MonObject@{o o o}} :
  EM_to_MSet@{o so} M ◯ EM_Comparison (MSet_adj@{o so} M)
  = Id[MSet@{so so o o o o o o} M] := eq_refl.

(** ** Instance/Fun/Action/Monad.v: the round trip algebra → M-set →
    algebra *)

(* CONTROL: the carrier, the structure map at each pair, and the
   structure map as the function p ↦ h (fst p, snd p), on the nose. *)
Example p464_rt2_carrier@{o so} {M : MonObject@{o o o}}
  (x : @EilenbergMoore@{so so so o} Sets@{o so} (ActF@{o so} M)
         (ActMonad@{o so} M)) :
  `1 (fobj[EM_Comparison (MSet_adj@{o so} M) ◯ EM_to_MSet@{o so} M] x)
  = `1 x := eq_refl.

Example p464_rt2_pointwise@{o so} {M : MonObject@{o o o}}
  (x : @EilenbergMoore@{so so so o} Sets@{o so} (ActF@{o so} M)
         (ActMonad@{o so} M)) (g : carrier M) (a : carrier (`1 x)) :
  t_alg[`2 (fobj[EM_Comparison (MSet_adj@{o so} M) ◯ EM_to_MSet@{o so} M] x)]
    (g, a) = t_alg[`2 x] (g, a) := eq_refl.

Example p464_rt2_eta@{o so} {M : MonObject@{o o o}}
  (x : @EilenbergMoore@{so so so o} Sets@{o so} (ActF@{o so} M)
         (ActMonad@{o so} M)) :
  (fun p => t_alg[`2 (fobj[EM_Comparison (MSet_adj@{o so} M)
                          ◯ EM_to_MSet@{o so} M] x)] p)
  = (fun p => t_alg[`2 x] (fst p, snd p)) := eq_refl.

(* N6 *)
Fail Example p464_rt2_functor@{o so} {M : MonObject@{o o o}} :
  EM_Comparison (MSet_adj@{o so} M) ◯ EM_to_MSet@{o so} M
  = Id[@EilenbergMoore@{so so so o} Sets@{o so} (ActF@{o so} M)
         (ActMonad@{o so} M)] := eq_refl.

(* N7 *)
Fail Example p464_rt2_fun@{o so} {M : MonObject@{o o o}}
  (x : @EilenbergMoore@{so so so o} Sets@{o so} (ActF@{o so} M)
         (ActMonad@{o so} M)) :
  (fun p => t_alg[`2 (fobj[EM_Comparison (MSet_adj@{o so} M)
                          ◯ EM_to_MSet@{o so} M] x)] p)
  = (fun p => t_alg[`2 x] p) := eq_refl.

(* N8 *)
Fail Example p464_rt2_obj@{o so} {M : MonObject@{o o o}}
  (x : @EilenbergMoore@{so so so o} Sets@{o so} (ActF@{o so} M)
         (ActMonad@{o so} M)) :
  fobj[EM_Comparison (MSet_adj@{o so} M) ◯ EM_to_MSet@{o so} M] x = x :=
  eq_refl.

(** ** Instance/Fun/Action/Monad.v: Beck's route against the direct one *)

(* CONTROL: Beck's quasi-inverse keeps the carrier and acts through η. *)
Example p464_beck_carrier@{o so} (M : MonObject@{o o o})
  (x : @EilenbergMoore@{so so so o} Sets@{o so} (ActF@{o so} M)
         (ActMonad@{o so} M)) :
  act_setoid (fobj[@quasi_inverse _ _ _ (MSet_beck_equivalence@{o so} M)] x)
  = `1 x := eq_refl.

Example p464_beck_act@{o so} (M : MonObject@{o o o})
  (x : @EilenbergMoore@{so so so o} Sets@{o so} (ActF@{o so} M)
         (ActMonad@{o so} M)) (g : carrier M) (z : carrier (`1 x)) :
  act (fobj[@quasi_inverse _ _ _ (MSet_beck_equivalence@{o so} M)] x) g z
  = t_alg[`2 x] (mon_op g mon_unit, z) := eq_refl.

(* N9 *)
Fail Example p464_beck_qi@{o so} (M : MonObject@{o o o}) :
  @quasi_inverse _ _ _ (MSet_beck_equivalence@{o so} M) = EM_to_MSet@{o so} M
  := eq_refl.

(* N10 *)
Fail Example p464_beck_act_strict@{o so} (M : MonObject@{o o o})
  (x : @EilenbergMoore@{so so so o} Sets@{o so} (ActF@{o so} M)
         (ActMonad@{o so} M)) (g : carrier M) (z : carrier (`1 x)) :
  act (fobj[@quasi_inverse _ _ _ (MSet_beck_equivalence@{o so} M)] x) g z
  = t_alg[`2 x] (g, z) := eq_refl.

(* N11 *)
Fail Example p464_monadic_same@{o so} (M : MonObject@{o o o}) :
  MSet_Forget_Monadic@{o so} M = MSet_Forget_Monadic_direct@{o so} M :=
  eq_refl.

(** ** Instance/Fun/Action/Monad.v: the hand-built functor G × (−) *)

(* The functor G × (−) built by hand, which the file does not keep. *)
Definition p464_ActF_hand@{o so} (M : MonObject@{o o o}) :
  Sets@{o so} ⟶ Sets@{o so}.
Proof.
  unshelve refine
    (@Build_Functor Sets@{o so} Sets@{o so} (fun X => act_prod M X)
       (fun X Y f => act_prod_map@{o so} M f) _ _ _).
  - intros X Y f f' Hf p. split; [ reflexivity | exact (Hf (snd p)) ].
  - intros X p. split; reflexivity.
  - intros X Y Z f g p. split; reflexivity.
Defined.

(* CONTROL: the same object and arrow maps as [ActF M], and ≈ to it with
   identity components. *)
Example p464_hand_obj@{o so} (M : MonObject@{o o o})
  (X : SetoidObject@{o o}) :
  fobj[p464_ActF_hand@{o so} M] X = fobj[ActF@{o so} M] X := eq_refl.

Example p464_hand_map@{o so} (M : MonObject@{o o o})
  (X Y : SetoidObject@{o o}) (f : X ~{Sets@{o so}}~> Y) :
  fmap[p464_ActF_hand@{o so} M] f = fmap[ActF@{o so} M] f := eq_refl.

Definition p464_hand_equiv@{o so} (M : MonObject@{o o o}) :
  p464_ActF_hand@{o so} M ≈ ActF@{o so} M.
Proof.
  exists (fun X => iso_id). intros X Y f p. split; reflexivity.
Defined.

(* N12 *)
Fail Example p464_hand_is_composite@{o so} (M : MonObject@{o o o}) :
  p464_ActF_hand@{o so} M = ActF@{o so} M := eq_refl.

(** ** Instance/Fun/Action/Monad/BG.v: the two monads *)

(* CONTROL: the literal unit reads (u u, x); the two monads have the same
   object and arrow maps, the same multiplication at every p and the same
   underlying multiplication function; the [to] leg of [BG_EM_iso]. *)
Example p464_bg_ret@{o so} (M : MonObject@{o o o}) (X : SetoidObject@{o o})
  (x : carrier X) :
  (@ret _ _ (BGMonad@{o so} M) X) x = (mon_op mon_unit mon_unit, x) :=
  eq_refl.

Example p464_bg_T_obj@{o so} (M : MonObject@{o o o})
  (X : SetoidObject@{o o}) :
  fobj[U_BG@{o so} M ◯ F_BG@{o so} M] X = fobj[ActF@{o so} M] X := eq_refl.

Example p464_bg_T_map@{o so} (M : MonObject@{o o o})
  (X Y : SetoidObject@{o o}) (f : X ~{Sets@{o so}}~> Y) :
  fmap[U_BG@{o so} M ◯ F_BG@{o so} M] f = fmap[ActF@{o so} M] f := eq_refl.

Example p464_bg_join_pointwise@{o so} (M : MonObject@{o o o})
  (X : SetoidObject@{o o}) (p : carrier M * (carrier M * carrier X)) :
  (@join _ _ (BGMonad@{o so} M) X) p = (@join _ _ (ActMonad@{o so} M) X) p :=
  eq_refl.

Example p464_bg_join_morphism@{o so} (M : MonObject@{o o o})
  (X : SetoidObject@{o o}) :
  @morphism _ _ _ _ (@join _ _ (BGMonad@{o so} M) X)
  = @morphism _ _ _ _ (@join _ _ (ActMonad@{o so} M) X) := eq_refl.

Example p464_bg_EM_to@{o so c} (M : MonObject@{o o o}) :
  to (BG_EM_iso@{o so c} M) = EM_Comparison (BG_adj@{o so} M) := eq_refl.

(* N13 *)
Fail Example p464_bg_ret_strict@{o so} (M : MonObject@{o o o})
  (X : SetoidObject@{o o}) (x : carrier X) :
  (@ret _ _ (BGMonad@{o so} M) X) x = (mon_unit, x) := eq_refl.

(* N14 *)
Fail Example p464_bg_T_is_ActF@{o so} (M : MonObject@{o o o}) :
  U_BG@{o so} M ◯ F_BG@{o so} M = ActF@{o so} M := eq_refl.

(* N15 *)
Fail Example p464_bg_join_fun@{o so} (M : MonObject@{o o o})
  (X : SetoidObject@{o o}) :
  @join _ _ (BGMonad@{o so} M) X = @join _ _ (ActMonad@{o so} M) X :=
  eq_refl.

(** ** Instance/Fun/Action/Monad/BG.v: evaluation *)

(* CONTROL: evaluation against [MSet_to] followed by [MSet_Forget], in
   both data fields. *)
Example p464_bg_U_obj@{o so} (M : MonObject@{o o o}) (P : SetBG@{o so} M) :
  fobj[U_BG@{o so} M] P = fobj[MSet_Forget@{o so} M ◯ MSet_to@{so o} M] P :=
  eq_refl.

Example p464_bg_U_map@{o so} (M : MonObject@{o o o}) (P Q : SetBG@{o so} M)
  (η : P ~{SetBG@{o so} M}~> Q) :
  fmap[U_BG@{o so} M] η = fmap[MSet_Forget@{o so} M ◯ MSet_to@{so o} M] η :=
  eq_refl.

(* N16 *)
Fail Example p464_bg_U_is_composite@{o so} (M : MonObject@{o o o}) :
  U_BG@{o so} M = MSet_Forget@{o so} M ◯ MSet_to@{so o} M := eq_refl.

(** ** Instance/Fun/Action/Monad/BG.v: the hom level of Set^BG *)

(* The functor category of BG.v with its hom level raised from o to so;
   Instance/Fun.v's block allows any hom level at least o. *)
Definition p464_SetBG_h@{o so} (M : MonObject@{o o o}) : Category@{so so so} :=
  @Fun@{o o so o so so so} (Deloop@{o o} M) Sets@{o so}.

(* CONTROL: functors into the raised category are formable, and
   Instance/Fun/Action.v's [MSet_from] lands there; [MSet_Free] alone. *)
Definition p464_bg_up@{o so} (M : MonObject@{o o o}) : Type@{so} :=
  Sets@{o so} ⟶ p464_SetBG_h@{o so} M.

Definition p464_bg_from_h@{o so} (M : MonObject@{o o o}) :
  MSet@{so so o o o o o o} M ⟶ p464_SetBG_h@{o so} M :=
  MSet_from@{so so o so o} M.

Definition p464_bg_free@{o so} (M : MonObject@{o o o}) :
  Sets@{o so} ⟶ MSet@{so so o o o o o o} M := MSet_Free@{o so} M.

(* N17 *)
Fail Definition p464_bg_down_h@{o so} (M : MonObject@{o o o}) : Type@{so} :=
  p464_SetBG_h@{o so} M ⟶ Sets@{o so}.

(* N18 *)
Fail Definition p464_bg_F_h@{o so} (M : MonObject@{o o o}) :
  Sets@{o so} ⟶ p464_SetBG_h@{o so} M :=
  MSet_from@{so so o so o} M ◯ MSet_Free@{o so} M.

(** ** Instance/Fun/Action/Monad/BG.v: the tie *)

(* CONTROL: the [to] leg of [Fun_EM_iso] is the comparison functor of
   [MSet_adj] after [MSet_to], on the nose; θ* after this file's
   comparison functor agrees with it on carriers and on structure maps as
   functions. *)
Example p464_fun_em_to@{o so c} (M : MonObject@{o o o}) :
  to (Fun_EM_iso@{o so c} M)
  = EM_Comparison (MSet_adj@{o so} M) ◯ MSet_to@{so o} M := eq_refl.

Example p464_tie_carrier@{o so c} (M : MonObject@{o o o})
  (P : SetBG@{o so} M) :
  `1 (fobj[BG_Act_EM@{o so} M ◯ EM_Comparison (BG_adj@{o so} M)] P)
  = `1 (fobj[to (Fun_EM_iso@{o so c} M)] P) := eq_refl.

Example p464_tie_alg@{o so c} (M : MonObject@{o o o}) (P : SetBG@{o so} M) :
  (fun p => @t_alg _ _ _ _
     (`2 (fobj[BG_Act_EM@{o so} M ◯ EM_Comparison (BG_adj@{o so} M)] P)) p)
  = (fun p => @t_alg _ _ _ _ (`2 (fobj[to (Fun_EM_iso@{o so c} M)] P)) p) :=
  eq_refl.

(* N19 *)
Fail Example p464_tie_obj@{o so c} (M : MonObject@{o o o})
  (P : SetBG@{o so} M) :
  fobj[BG_Act_EM@{o so} M ◯ EM_Comparison (BG_adj@{o so} M)] P
  = fobj[to (Fun_EM_iso@{o so c} M)] P := eq_refl.

(* CONTROL: the [morphism] field of the tie's structure map, on the nose. *)
Example p464_tie_alg_morphism@{o so c} (M : MonObject@{o o o})
  (P : SetBG@{o so} M) :
  @morphism _ _ _ _
    (@t_alg _ _ _ _
       (`2 (fobj[BG_Act_EM@{o so} M ◯ EM_Comparison (BG_adj@{o so} M)] P)))
  = @morphism _ _ _ _
      (@t_alg _ _ _ _ (`2 (fobj[to (Fun_EM_iso@{o so c} M)] P))) := eq_refl.

(* N20 *)
Fail Example p464_tie_alg_proper@{o so c} (M : MonObject@{o o o})
  (P : SetBG@{o so} M) :
  @proper_morphism _ _ _ _
    (@t_alg _ _ _ _
       (`2 (fobj[BG_Act_EM@{o so} M ◯ EM_Comparison (BG_adj@{o so} M)] P)))
  = @proper_morphism _ _ _ _
      (@t_alg _ _ _ _ (`2 (fobj[to (Fun_EM_iso@{o so c} M)] P))) := eq_refl.

(** ** Closure: a readback, not a refutation *)

Print Assumptions ActMonad.
Print Assumptions EM_MSet_iso.
Print Assumptions MSet_Forget_Monadic.
Print Assumptions U_BG_Monadic.
Print Assumptions tie.

(** ** Guard: the constants of the two targets *)

(* Instance/Fun/Action/Monad.v *)
Check @Category.Instance.Fun.Action.Monad.ActF.
Check @Category.Instance.Fun.Action.Monad.ActF_map.
Check @Category.Instance.Fun.Action.Monad.ActF_obj.
Check @Category.Instance.Fun.Action.Monad.ActMonad.
Check @Category.Instance.Fun.Action.Monad.ActMonad_join.
Check @Category.Instance.Fun.Action.Monad.ActMonad_join_fun.
Check @Category.Instance.Fun.Action.Monad.ActMonad_ret.
Check @Category.Instance.Fun.Action.Monad.ActMonad_ret_fun.
Check @Category.Instance.Fun.Action.Monad.CreatedAct.
Check @Category.Instance.Fun.Action.Monad.CreatedE.
Check @Category.Instance.Fun.Action.Monad.CreatedE_is_coeq.
Check @Category.Instance.Fun.Action.Monad.EM_MSet_iso.
Check @Category.Instance.Fun.Action.Monad.EM_MSet_iso_beck.
Check @Category.Instance.Fun.Action.Monad.EM_MSet_iso_beck_to.
Check @Category.Instance.Fun.Action.Monad.EM_MSet_iso_from.
Check @Category.Instance.Fun.Action.Monad.EM_MSet_iso_to.
Check @Category.Instance.Fun.Action.Monad.EM_act.
Check @Category.Instance.Fun.Action.Monad.EM_act_is_action.
Check @Category.Instance.Fun.Action.Monad.EM_to_MSet.
Check @Category.Instance.Fun.Action.Monad.FreeAct.
Check @Category.Instance.Fun.Action.Monad.Fun_EM_iso.
Check @Category.Instance.Fun.Action.Monad.GAct_Monad.
Check @Category.Instance.Fun.Action.Monad.GAct_Monad_GroupObject.
Check @Category.Instance.Fun.Action.Monad.GAct_Monad_Grp.
Check @Category.Instance.Fun.Action.Monad.GSet_Forget_Monadic.
Check @Category.Instance.Fun.Action.Monad.GSet_Forget_Monadic_GroupObject.
Check @Category.Instance.Fun.Action.Monad.GSet_Forget_Monadic_Grp.
Check @Category.Instance.Fun.Action.Monad.MSet_Forget.
Check @Category.Instance.Fun.Action.Monad.MSet_Forget_Monadic.
Check @Category.Instance.Fun.Action.Monad.MSet_Forget_Monadic_direct.
Check @Category.Instance.Fun.Action.Monad.MSet_Forget_creates.
Check @Category.Instance.Fun.Action.Monad.MSet_Forget_reflects.
Check @Category.Instance.Fun.Action.Monad.MSet_Free.
Check @Category.Instance.Fun.Action.Monad.MSet_adj.
Check @Category.Instance.Fun.Action.Monad.MSet_adj_iso.
Check @Category.Instance.Fun.Action.Monad.MSet_beck_equivalence.
Check @Category.Instance.Fun.Action.Monad.MSet_comparison_equivalence.
Check @Category.Instance.Fun.Action.Monad.MSet_counit_iso.
Check @Category.Instance.Fun.Action.Monad.MSet_extend.
Check @Category.Instance.Fun.Action.Monad.MSet_restrict.
Check @Category.Instance.Fun.Action.Monad.MSet_unit_iso.
Check @Category.Instance.Fun.Action.Monad.Reflected_is_coeq.
Check @Category.Instance.Fun.Action.Monad.act_prod.
Check @Category.Instance.Fun.Action.Monad.act_prod_map.
Check @Category.Instance.Fun.Action.Monad.beck_act.
Check @Category.Instance.Fun.Action.Monad.beck_carrier.
Check @Category.Instance.Fun.Action.Monad.beck_direct_to.
Check @Category.Instance.Fun.Action.Monad.beck_vs_direct.
Check @Category.Instance.Fun.Action.Monad.beck_vs_direct_iso.
Check @Category.Instance.Fun.Action.Monad.comparison_alg_fun.
Check @Category.Instance.Fun.Action.Monad.comparison_alg_is_action.
Check @Category.Instance.Fun.Action.Monad.created_absorb.
Check @Category.Instance.Fun.Action.Monad.created_act.
Check @Category.Instance.Fun.Action.Monad.mset_created_action.
Check @Category.Instance.Fun.Action.Monad.mset_created_arrow.
Check @Category.Instance.Fun.Action.Monad.mset_created_carrier.
Check @Category.Instance.Fun.Action.Monad.mset_created_iso.
Check @Category.Instance.Fun.Action.Monad.split_absorb.

(* Instance/Fun/Action/Monad/BG.v *)
Check @Category.Instance.Fun.Action.Monad.BG.Act_BG_alg.
Check @Category.Instance.Fun.Action.Monad.BG.BGCreatedE.
Check @Category.Instance.Fun.Action.Monad.BG.BGCreatedE_is_coeq.
Check @Category.Instance.Fun.Action.Monad.BG.BGMonad.
Check @Category.Instance.Fun.Action.Monad.BG.BG_Act_EM.
Check @Category.Instance.Fun.Action.Monad.BG.BG_Act_EM_alg.
Check @Category.Instance.Fun.Action.Monad.BG.BG_Act_EM_carrier.
Check @Category.Instance.Fun.Action.Monad.BG.BG_Act_EM_forget_map.
Check @Category.Instance.Fun.Action.Monad.BG.BG_Act_EM_forget_obj.
Check @Category.Instance.Fun.Action.Monad.BG.BG_Act_alg.
Check @Category.Instance.Fun.Action.Monad.BG.BG_EM_iso.
Check @Category.Instance.Fun.Action.Monad.BG.BG_EM_iso_to.
Check @Category.Instance.Fun.Action.Monad.BG.BG_T_ActF.
Check @Category.Instance.Fun.Action.Monad.BG.BG_T_map.
Check @Category.Instance.Fun.Action.Monad.BG.BG_T_obj.
Check @Category.Instance.Fun.Action.Monad.BG.BG_adj.
Check @Category.Instance.Fun.Action.Monad.BG.BG_adj_iso.
Check @Category.Instance.Fun.Action.Monad.BG.BG_beck_equivalence.
Check @Category.Instance.Fun.Action.Monad.BG.BG_extend.
Check @Category.Instance.Fun.Action.Monad.BG.BG_join.
Check @Category.Instance.Fun.Action.Monad.BG.BG_join_ActMonad.
Check @Category.Instance.Fun.Action.Monad.BG.BG_join_fun.
Check @Category.Instance.Fun.Action.Monad.BG.BG_restrict.
Check @Category.Instance.Fun.Action.Monad.BG.BG_ret.
Check @Category.Instance.Fun.Action.Monad.BG.BG_ret_ActMonad.
Check @Category.Instance.Fun.Action.Monad.BG.BG_ret_fun.
Check @Category.Instance.Fun.Action.Monad.BG.F_BG.
Check @Category.Instance.Fun.Action.Monad.BG.GSet_BG_Monadic.
Check @Category.Instance.Fun.Action.Monad.BG.GSet_BG_Monadic_GroupObject.
Check @Category.Instance.Fun.Action.Monad.BG.GSet_BG_Monadic_Grp.
Check @Category.Instance.Fun.Action.Monad.BG.MSet_to_reflects_coeq.
Check @Category.Instance.Fun.Action.Monad.BG.SetBG.
Check @Category.Instance.Fun.Action.Monad.BG.U_BG.
Check @Category.Instance.Fun.Action.Monad.BG.U_BG_Monadic.
Check @Category.Instance.Fun.Action.Monad.BG.U_BG_creates.
Check @Category.Instance.Fun.Action.Monad.BG.U_BG_map.
Check @Category.Instance.Fun.Action.Monad.BG.U_BG_obj.
Check @Category.Instance.Fun.Action.Monad.BG.U_BG_reflects.
Check @Category.Instance.Fun.Action.Monad.BG.bg_created_action.
Check @Category.Instance.Fun.Action.Monad.BG.bg_created_arrow.
Check @Category.Instance.Fun.Action.Monad.BG.bg_created_carrier.
Check @Category.Instance.Fun.Action.Monad.BG.bg_created_iso.
Check @Category.Instance.Fun.Action.Monad.BG.tie.
Check @Category.Instance.Fun.Action.Monad.BG.tie_alg.
Check @Category.Instance.Fun.Action.Monad.BG.tie_alg_fun.
Check @Category.Instance.Fun.Action.Monad.BG.tie_carrier.
