(** * Probe for closure and interior operators (issue #463)

    Pins the measured boundaries of the seven files #463 adds for Mac
    Lane §VI.1 display (3) and §VI.2, book pp. 139 and 141 (PDF pp. 148
    and 150), catalog items maclane:VI.1:remark2 and maclane:VI.2:remark1,
    with the appended Awodey §10.2 (Example 10.4 and the construction
    after it, printed pp. 270-271 of the 2005 pre-print), Seven Sketches
    §1.4.4 (printed pp. 33-35) and Riehl Example 5.1.7 (p. 186) and
    Example 5.2.6 (iv) (p. 190).  The files are Structure/Thin/Monad.v
    (monads and comonads in any thin category),
    Construction/Reflective/Idempotent/Induced.v (the reflection of an
    idempotent monad induces that monad, and the dual at C^op),
    Instance/Proset/Monad.v (monads on a preorder are closure operators,
    their algebras the closed elements), Instance/Proset/Monad/Awodey.v
    (Awodey's t ⊣ i), Instance/Proset/Monad/Interior.v (comonads are
    interior operators, by the reversed order), Instance/Props/Modal.v
    (the modal operator B ⇒ − and the currying monad) and
    Instance/Top/Interior.v (closure and interior on the subsets of a
    space).  N1-N27 restate refusals that #463's two builders, its two
    reviews and its fold measured in scratch files (LABELS, below); every
    one is recorded in a target header.  The positive controls restate
    the files' claims independently.

    THE IMPORT LIST, generated by a script over the [Require] lines.
    Target by target in dependency order, the order named above, the
    [Require] lines each adds to those before it, in its own order, and
    then that target: fifteen lines and Structure/Thin/Monad.v, three and
    Induced.v, eleven and Instance/Proset/Monad.v, none and Awodey.v, four
    and Interior.v, four and Modal.v, five and Instance/Top/Interior.v.
    Then one line for a wall: Instance/Proset/Limit.v, for its
    transparent [op_PreOrder] (N18 and two controls).  Fifty lines,
    forty-four of them naming [Category] modules.  Under this list
    [Print Libraries] in a scratch file loads one hundred and fifty-one
    [Category] modules, the seven targets among them.  A shorter import
    list is what makes a probe pass for no reason.

    DISCIPLINE.  The instrument was checked both ways: a false statement
    about the targets is refused for that reason, and each of the
    sixty-seven definitions (two of them [Program] definitions),
    examples and the one record of this file that is not a refutation,
    wrapped in the refutation keyword in a copy of this
    WHOLE file, stops the build at that command with the message Rocq
    prints for a refutation whose command succeeds (sixty-seven of
    sixty-seven, by a script over the copies, which compares the File
    line of the error with the wrapped line).  Every negative is a
    [Definition] or an [Example], never a [Check], so that an open evar
    cannot satisfy it.  Each negative was stripped of its refutation
    keyword in a copy of this WHOLE file, one at a time, compiled, and
    its error read; each of the twenty-eight copies stops inside the
    stripped command (by the File line of its error, compared by a
    script with the command's extent).  The kind recorded is the kind of
    that error, and each negative has positive controls beside it.
    Quotations are Rocq 9.1.1's under this file's import list, with the
    error's environment block left out; Rocq prints the "cannot unify"
    parenthetical with the short names in scope, and <1> stands for the
    universe a stripped copy names after itself and a serial number.
    The seven targets and this file also compile on Coq 8.19.2 and
    8.20.1, with no warning from any of them, overlaid on the prebuilt
    trees of this library for those versions, whose sources of the one
    hundred and fifty-one modules this file loads are this tree's byte
    for byte (compared by script); twenty-eight files were compiled
    there, these eight, Theory/Monad.v and Instance/Poset.v (which carry
    the CORRECTION (#463) notes) and eighteen modules that depend on
    them.  Each of the twenty-eight stripped copies is refused there
    inside the stripped command with the Rocq 9.1.1 error up to the
    serial names of universes (compared by a script): twenty-five at the
    File line of the Rocq 9.1.1 refusal, and N6, N7 and N8 at the first
    line of the command, their errors naming the universe at the line and
    characters Rocq 9.1.1 marks.  After later edits to Interior.v,
    Instance/Proset/Monad.v, Modal.v, Instance/Top/Interior.v and this
    file, and two more CORRECTION (#463) notes (Instance/Proset/Limit.v
    and Construction/Reflective/FixedPoints.v), the overlay was repeated
    on copies of those trees, byte for byte again (compared by script):
    the eleven files it recompiled compile on both versions with no
    warning.  The stripped copies were not run there again; no
    refutation command of this file changed.

    KINDS.  Twenty-eight refutations, counted as the lines that open with
    the refutation keyword: CONVERSION (the instrument, N1-N5, N9-N16,
    N18-N27), UNIVERSE (N6, N7, N8) and TYPING (N17): twenty-four, three
    and one.  A CONVERSION refusal is [eq_refl] refused with a "cannot
    unify" parenthetical; the UNIVERSE refusals are a closed universe
    list that does not bind a level its body introduces ("is unbound");
    the TYPING refusal is a type mismatch with no parenthetical.  Each
    CONVERSION refusal of N1-N27 also has a CAUSE, read off the normal
    forms and, where one applies, a flip: STRUCTURAL (the two sides
    reduce to different terms, or to a stuck projection of a variable,
    and no flip changes that: N1-N5, N9-N12, N14, N18-N20, N23, N24, N26,
    N27), OPACITY (an in-tree [Qed] or opaque [Program] obligation is the
    whole refusal, and the flip that makes it transparent gives
    [eq_refl]: N22, N25) and STDLIB (the residue is an opaque constant of
    the standard library: N13, N15, N16, N21).

    LABELS.  Builder A's stripped copies StripThinMonadEq, Strip_rt_eq,
    Strip_rt_eq_flip, Strip_iso_record, Strip_iso_idem, Strip_ret,
    Strip_join, Strip_fun, Strip_record, Strip_functor and Strip_tik are
    N1, N2, N3, N4, N5, N9, N10, N11, N12, N13 and N14 (its review's
    RThin1, RMon_rt, RMon_rtflip, RMon_iso, RMon_isoidem, RInd_ret,
    RInd_join, RInd_fun, RAw_rec, RAw_fun and RAw_tik).  Builder B's
    Strip_op_eq, Strip_op_id, Strip_op_cast, OpT_eq, Strip_rt_eq,
    Strip_rt_eq_flip, Strip_flipop_eq, Strip_thin_comonad_eq,
    Strip_curry_is_modal_fobj, Strip_modal_functor_eq,
    Strip_props_is_proset and Strip_props_is_any_proset are N15-N26 in
    that order; its Flip_thin_comonad_ctrl is the control
    [p463_ic_thin_T].  Its review's D_dev_thin_bare is N7, its
    D_dev_thin_t_u, D_dev_thin_t_h and D_dev_thin_plus the controls
    [p463_ic_thin_u], [p463_ic_thin_h] and [p463_ic_thin_plus], and its
    PropsNarrow the control [p463_props_T].  N6, N8 and N27 are the
    fold's own.  The labels are not constants: each refutation carries
    its own in a comment on the line above it, the instrument's reading
    "The instrument".

    ** The instrument

    Control: max 2 0 is 2 ([p463_instrument_ctl]).
    The instrument (CONVERSION).  The same term stated as 0:
      (cannot unify "cl_fun (max_closure 2) 0%nat" and "0%nat")

    ** Structure/Thin/Monad.v

    Controls: [thin_monad]'s unit is the given family, and [thin_comonad]
    is [thin_monad] at C^op on the whole record, at [eq_refl]
    ([p463_thin_ret], [p463_thin_comonad_is_op]); join invertible in any
    thin category ([p463_thin_join_iso]).

    N1 (CONVERSION, STRUCTURAL).  The header's STRENGTHS, a variable
    monad with the same unit and multiplication:
      (cannot unify "thin_monad TC T (@ret _ _ MM) (@join _ _ MM)" and
      "MM")

    ** Instance/Proset/Monad.v: the correspondence

    Controls: closure → monad → closure, and [closure_monad] against
    [thin_monad], on the whole record ([p463_closure_round_trip],
    [p463_closure_monad_is_thin]); monad → closure → monad on objects,
    arrows, unit and multiplication at [eq_refl] and as functors at ≈
    ([p463_rt_fobj], [p463_rt_fmap], [p463_rt_ret], [p463_rt_join],
    [p463_rt_equiv]); the flipped functor's object map
    ([p463_Functor_of_monotone_T], [p463_rt_fobj_T]); the isomorphism as
    a field, with its two directions ([p463_ClosureOperatorIso],
    [p463_iso_monad], [p463_iso_of_monad]); the [to] leg of
    [closure_of_iso] ([p463_iso_to]).

    N2 (CONVERSION, STRUCTURAL).  The header's STRENGTHS:
      (cannot unify "closure_functor (closure_of_monad M)" and "M")
    N3 (CONVERSION, STRUCTURAL).  The same, flipped: the law fields
    written as transparent [I], with no [Qed] anywhere:
      (cannot unify "p463_Functor_of_monotone_T P (cl_fun
      (closure_of_monad M))" and "M")
    N4 (CONVERSION, STRUCTURAL).  The header's WHICH READING: a record
    with the isomorphism as a field does not round-trip:
      (cannot unify "p463_iso_of_monad (Functor_of_monotone P P
      (p463_ci_fun c))" and "c")
    N5 (CONVERSION, STRUCTURAL).  The whole isomorphism of
    [closure_of_iso], whose [from] leg is extensivity at f x:
      (cannot unify "cl_idem (closure_of_iso P f ext idem) x" and "idem
      x")

    ** The thin route, bare and pinned

    Controls: [closure_monad], [interior_comonad] and [modal_monad]
    through [thin_monad] or [thin_comonad] with the thin level pinned to
    u, to h, or left extensible ([p463_cm_thin_u], [p463_cm_thin_h],
    [p463_cm_thin_plus], and likewise [p463_ic_thin_*] and
    [p463_mm_thin_*]).

    N6, N7, N8 (UNIVERSE).  The headers' "refused bare", for
    Instance/Proset/Monad.v, Interior.v and Modal.v: the closed list
    [@{u h}] does not bind the sort level of Structure/Thin.v's [Thin]:
      Universe <1> (File "...", line ..., characters 3-13) is unbound.
    (characters 3-15 for N7, whose term is [@thin_comonad]; the File and
    line are the stripped copy's own, inside the stripped command).

    ** Construction/Reflective/Idempotent/Induced.v

    Controls: the composite is M on objects and on arrows at [eq_refl]
    ([p463_idem_obj], [p463_idem_fmap]); the induced unit is ret at ≈,
    and its dual the extract ([p463_idem_unit], [p463_idem_counit]).

    N9, N10 (CONVERSION, STRUCTURAL).  The header's STRENGTHS: the
    induced unit and multiplication reduce to [id ∘ ret x] and
    [join x ∘ fmap[M] id]:
      (cannot unify "@ret _ _ (@Adjunction_Induced_Monad (Sub C
      (@MLocal_Subcategory C M MM)) C (@idem_reflector C M MM IM) (Incl C
      (@MLocal_Subcategory C M MM)) (@idem_reflective_adj C M MM IM)) x"
      and "@ret _ _ MM x")
    and the same with [@join] in both places.
    N11 (CONVERSION, STRUCTURAL).  The functor equation, refused in the
    law fields alone, stuck projections of a variable M:
      (cannot unify "Incl C MLocal_Subcategory ◯ idem_reflector" and "M")

    ** Instance/Proset/Monad/Awodey.v

    Controls: T = i ∘ t on objects and on arrows, the induced monotone
    map is c's, t (i k) is cl k on first components and ≅ k, and i ◯ t
    ≈ [closure_functor c] ([p463_aw_obj], [p463_aw_fmap], [p463_aw_is_c],
    [p463_aw_tik_fst], [p463_aw_tik_iso], [p463_aw_functor]).

    N12 (CONVERSION, STRUCTURAL).  The whole record read back from the
    induced monad; its proof fields are c's composed with a reflexivity
    by the transitivity of a variable P:
      (cannot unify "closure_of_monad (GaloisFunctor_r P (closed_PreOrder
      c) (closed_galois c) ◯ GaloisFunctor_l P (closed_PreOrder c)
      (closed_galois c))" and "c")
    N13 (CONVERSION, STDLIB).  i ◯ t = [closure_functor c], whose object
    and arrow maps agree; flipped in a copy of the dependency closure,
    the law fields stop on stdlib's opaque
    [CMorphisms.trans_co_eq_inv_arrow_morphism_obligation_1]:
      (cannot unify "GaloisFunctor_r P (closed_PreOrder c) (closed_galois
      c) ◯ GaloisFunctor_l P (closed_PreOrder c) (closed_galois c)" and
      "closure_functor c")
    N14 (CONVERSION, STRUCTURAL).  "tik = k" itself:
      (cannot unify "closed_t c (closed_i c k)" and "k")

    ** Instance/Proset/Monad/Interior.v: the reversed order

    Controls: (Proset P)^op and the reversed order have the same objects
    and homs, and with Instance/Proset/Limit.v's [op_PreOrder] the same
    identity and composition ([p463_op_obj], [p463_op_hom],
    [p463_opT_id], [p463_opT_compose]).

    N15, N16 (CONVERSION, STDLIB).  The header's WHY THE REVERSED ORDER,
    the whole category and its [id] field; stdlib's [flip_PreOrder] is
    opaque ([About] says so):
      (cannot unify "(Proset P)^op" and "Proset (flip_PreOrder P)")
      (cannot unify "@id (Proset P)^op" and "@id (Proset (flip_PreOrder
      P))")
    N17 (TYPING).  An endofunctor of one used as one of the other:
      The term "W" has type "(Proset P)^op ⟶ (Proset P)^op" while it is
      expected to have type "Proset (flip_PreOrder P) ⟶ Proset
      (flip_PreOrder P)".
    N18 (CONVERSION, STRUCTURAL).  With the transparent [op_PreOrder]:
    refused at [compose_respects], whose hypotheses
    Construction/Opposite.v swaps (measured field by field in a fully
    transparent copy of the closure):
      (cannot unify "(Proset P)^op" and "Proset (op_PreOrder P)")

    ** Instance/Proset/Monad/Interior.v: the correspondence

    Controls: interior → comonad → interior on the whole record
    ([p463_int_round_trip]); comonad → interior → comonad on objects,
    arrows, counit and comultiplication at [eq_refl] ([p463_crt_fobj],
    [p463_crt_fmap], [p463_crt_extract], [p463_crt_duplicate]); Riehl's
    route as [thin_monad] on the whole record ([p463_flip_is_thin]);
    [flip_functor W] against the opposite on objects and arrows at
    [eq_refl] and at ≈ ([p463_flipop_fobj], [p463_flipop_fmap],
    [p463_flipop_equiv]); the flip of N22 ([p463_Thin_Opposite_T],
    [p463_ic_thin_T]).

    N19, N20 (CONVERSION, STRUCTURAL).  The header's STRENGTHS, as is and
    flipped (law fields written as transparent [I]):
      (cannot unify "interior_functor (interior_of_comonad W)" and "W")
      (cannot unify "p463_Functor_of_monotone_T P (unflip_mono (cl_fun
      (interior_of_comonad W)))" and "W")
    N21 (CONVERSION, STDLIB).  [flip_functor W] against the opposite; in
    a fully transparent copy of the closure the residue is W's
    [fmap_respects] inside the same stdlib obligation as N13:
      (cannot unify "flip_functor W" and "Proset_op_to P ◯ W^op ◯
      Proset_op_from P")
    N22 (CONVERSION, OPACITY).  [interior_comonad] against
    [thin_comonad]; with [Thin_Opposite] restated transparently it is
    [eq_refl] ([p463_ic_thin_T]):
      (cannot unify "interior_comonad j" and "thin_comonad (λ (x y :
      obj[Proset P]) (_ _ : x ~{ Proset P }~> y), I) (interior_functor j)
      (cl_ext j) (cl_mult j)")

    ** Instance/Props/Modal.v

    Controls: [modal_monad] as [thin_monad] on the whole record with the
    multiplication written as the term f ↦ (b ↦ f b b), and join
    computing ([p463_modal_is_thin], [p463_modal_join]); the currying
    monad's object map is B → p ∧ B, and the two functors are ≈
    ([p463_curry_fobj], [p463_curry_iso]); [Props] and
    [Proset impl_PreOrder] agree on objects, homs, identity and
    composition ([p463_props_obj], [p463_props_hom], [p463_props_id],
    [p463_props_compose]); the flip of N25 and N26, the two [Program
    Definition]s restated verbatim with transparent obligations
    ([P463Flip.p463_props_T], [P463Flip.p463_props_var_T]).

    N23, N24 (CONVERSION, STRUCTURAL).  The header's THE MONAD OF THE
    CURRYING ADJUNCTION; the object maps normalise to different
    [Prop] terms:
      (cannot unify "fobj[curry_functor Props_Closed B] p" and
      "fobj[modal_functor B] p")
      (cannot unify "curry_functor Props_Closed B" and "modal_functor B")
    N25 (CONVERSION, OPACITY).  The header's THE ORDER-LEVEL OPERATOR, at
    [impl_PreOrder]: the [obj], [hom], [id] and [compose] fields agree
    and [homset] does not, and the whole record is [eq_refl] once the
    obligations are transparent ([P463Flip.p463_props_T]):
      (cannot unify "Props" and "Proset impl_PreOrder")
    N26, N27 (CONVERSION, STRUCTURAL).  For a variable P, as the tree
    stands and with the obligations transparent; the objects and homs
    agree ([P463Flip.p463_props_var_T]) and [id] is P's reflexivity:
      (cannot unify "Props" and "Proset P")
      (cannot unify "Props_T" and "Proset_T P")

    ** Instance/Top/Interior.v: readbacks only

    Controls: the coalgebras of the interior comonad are the open subsets
    ([p463_pint_coalg]); {true} in the indiscrete two-point space is not
    one ([p463_true_sub_not_open]); the algebras of the ¬ int ¬ closure
    are the complements of opens ([p463_ncl_algebra]); the converse of the
    footnote-5 algebra half with no hypothesis gives ¬¬(∀ q, ¬¬q → q)
    ([p463_converse_nndne]).  Every statement of that file is a
    proposition about subsets, so it has no conversion boundary to pin.

    ** Closure: a readback, not a refutation

    [Print Assumptions] of twelve headline constants of the targets, near
    the end of this file, each print "Closed under the global context".
    A [Print Assumptions] cannot refuse, so these lines are readbacks and
    guard nothing; the Makefile's print-assumptions gate is where closure
    is kept.  By the same command all two hundred and one
    constants of the seven targets are closed under the global context
    (measured in a scratch file, with a positive control: a local axiom
    is printed).

    NOT PINNED HERE.  (a) [About] readbacks as such: the headers'
    universe censuses (no level of the body alone in any of the two
    hundred and one constants, and the [Set] bounds of the three
    B-side files), the constraints the pinned thin routes add (h <= u,
    u <= h, and the extensible block), and the free level u4 of
    [Adjunction_Comonad], read by [About] in scratch files.  (b) Flips
    made in copies of the dependency closure rather than by restatement
    here: the ones behind N13, N18 and N21.  (c) The closure of the
    targets under [Print Assumptions]: a measurement of the build rather
    than of a command.  (d) The metatheorem Instance/Top/Interior.v cites,
    that intuitionistic higher-order logic does not prove
    ¬¬(∀ q, ¬¬q → q): no command can pin an unprovability.  (e) The
    absences the headers record (no category of closure operators, no
    functoriality in P, no Lawvere-Tierney topology, no proof that
    ¬¬-LEM suffices): an absence has no command.

    The guard block at the end names the two hundred and one
    constants of the seven targets, so that a rename breaks this file:
    fourteen of Structure/Thin/Monad.v, eight of Induced.v, thirty-six of
    Instance/Proset/Monad.v, fourteen of Awodey.v, fifty-three of
    Interior.v, thirty of Modal.v and forty-six of
    Instance/Top/Interior.v.  They are exactly the entries [Print
    Module] gives for each: one hundred and ninety-nine definitions and
    opaque constants, among them the three projections of the one
    record, and the record [ClosureOperator] with its constructor
    [Build_ClosureOperator]; no target has a [Program] obligation.  Each
    is written fully qualified and with [@], so that no short name in
    scope can stand in for it and its implicit arguments are not
    elaborated: without [@], [Check] of Interior.v's [adj_closure] stops
    with a stack overflow (measured). *)

Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Monad.
Require Import Category.Construction.Opposite.
Require Import Category.Functor.Opposite.
Require Import Category.Monad.Algebra.
Require Import Category.Comonad.Core.
Require Import Category.Comonad.Coalgebra.
Require Import Category.Construction.Subcategory.
Require Import Category.Construction.Reflective.
Require Import Category.Construction.Reflective.Idempotent.
Require Import Category.Construction.Reflective.FixedPoints.
Require Import Category.Structure.Thin.
Require Import Category.Structure.Thin.Monad.
Require Import Category.Theory.Natural.Transformation.
Require Import Category.Theory.Adjunction.
Require Import Category.Monad.Comparison.
Require Import Category.Construction.Reflective.Idempotent.Induced.
Require Import Category.Theory.Equivalence.
Require Import Category.Monad.Eilenberg.Moore.
Require Import Category.Instance.Proset.
Require Import Category.Instance.Poset.
Require Import Category.Instance.Proset.Order.
Require Import Category.Instance.Proset.Monotone.
Require Import Category.Instance.Proset.Galois.
Require Import Coq.Classes.Equivalence.
Require Import Coq.Relations.Relation_Definitions.
Require Import Coq.Arith.PeanoNat.
From Coq Require Import Lia.
Require Import Category.Instance.Proset.Monad.
Require Import Category.Instance.Proset.Monad.Awodey.
Require Import Category.Monad.Adjunction.
Require Import Category.Comonad.Duality.
Require Import Coq.Classes.RelationClasses.
Require Import Coq.micromega.Lia.
Require Import Category.Instance.Proset.Monad.Interior.
Require Import Category.Structure.Cartesian.
Require Import Category.Structure.Cartesian.Closed.
Require Import Category.Structure.Cartesian.Closed.Adjunction.
Require Import Category.Instance.Props.
Require Import Category.Instance.Props.Modal.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Sets.Powerset.
Require Import Category.Instance.Powerset.
Require Import Category.Instance.Top.Prop.
Require Import Category.Instance.Top.Cocomplete.
Require Import Category.Instance.Top.Interior.
Require Import Category.Instance.Proset.Limit.

Generalizable All Variables.

Open Scope category_scope.

(** ** Instrument: a false statement is refused *)

(* The instrument *)
Fail Example p463_instrument@{u} : cl_fun (max_closure@{u} 2%nat) 0%nat = 0%nat
  := eq_refl.

(* CONTROL: the same term, correctly stated: max 2 0 is 2. *)
Example p463_instrument_ctl@{u} : cl_fun (max_closure@{u} 2%nat) 0%nat = 2%nat
  := eq_refl.

(** ** Structure/Thin/Monad.v *)

(* CONTROL: the given families on the nose, and the comonad as the monad
   at C^op on the nose. *)
Example p463_thin_ret@{t o h} {C : Category@{o h h}} (TC : Thin@{t o h} C)
  (T : C ⟶ C) (u : ∀ x : C, x ~> T x) (m : ∀ x : C, T (T x) ~> T x)
  (x : C) : @ret C T (thin_monad TC T u m) x = u x := eq_refl.

Example p463_thin_comonad_is_op@{t o h} {C : Category@{o h h}}
  (TC : Thin@{t o h} C) (W : C ⟶ C) (e : ∀ x : C, W x ~> x)
  (d : ∀ x : C, W x ~> W (W x)) :
  thin_comonad TC W e d = thin_monad (Thin_Opposite TC) (W^op) e d
  := eq_refl.

(* CONTROL: join is invertible in any thin category. *)
Definition p463_thin_join_iso@{t o h} {C : Category@{o h h}}
  (TC : Thin@{t o h} C) {M : C ⟶ C} {MM : @Monad C M} (x : C) :
  IsIsomorphism (@join C M MM x) := thin_join_IsIso TC x.

(* N1 *)
Fail Example p463_thin_monad_is_MM@{t o h} {C : Category@{o h h}}
  (TC : Thin@{t o h} C) (T : C ⟶ C) (MM : @Monad C T) :
  thin_monad TC T (@ret C T MM) (@join C T MM) = MM := eq_refl.

(** ** Instance/Proset/Monad.v: the correspondence *)

(* CONTROL: closure → monad → closure on the whole record, and
   [closure_monad] as [thin_monad] on the whole record. *)
Example p463_closure_round_trip@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : ClosureOperator@{u} P) :
  closure_of_monad@{u h} (closure_functor@{u h} c) (MM := closure_monad c)
    = c := eq_refl.

Example p463_closure_monad_is_thin@{u h t} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : ClosureOperator@{u} P) :
  closure_monad@{u h} c
    = @thin_monad@{t u h} (Proset@{u h} P) (fun _ _ _ _ => I)
        (closure_functor@{u h} c) (cl_ext c) (cl_mult c) := eq_refl.

(* CONTROL: monad → closure → monad: the four components on the nose,
   and the functors at ≈. *)
Example p463_rt_fobj@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (M : Proset@{u h} P ⟶ Proset@{u h} P)
  {MM : @Monad (Proset@{u h} P) M} (x : A) :
  fobj[closure_functor (closure_of_monad M (MM := MM))] x = fobj[M] x
  := eq_refl.

Example p463_rt_fmap@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (M : Proset@{u h} P ⟶ Proset@{u h} P)
  {MM : @Monad (Proset@{u h} P) M} (x y : A) (f : R x y) :
  fmap[closure_functor (closure_of_monad M (MM := MM))] f = fmap[M] f
  := eq_refl.

Example p463_rt_ret@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (M : Proset@{u h} P ⟶ Proset@{u h} P)
  {MM : @Monad (Proset@{u h} P) M} (x : A) :
  @ret _ _ (closure_monad (closure_of_monad M (MM := MM))) x = @ret _ M MM x
  := eq_refl.

Example p463_rt_join@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (M : Proset@{u h} P ⟶ Proset@{u h} P)
  {MM : @Monad (Proset@{u h} P) M} (x : A) :
  @join _ _ (closure_monad (closure_of_monad M (MM := MM))) x
    = @join _ M MM x := eq_refl.

Definition p463_rt_equiv@{u h +} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (M : Proset@{u h} P ⟶ Proset@{u h} P)
  {MM : @Monad (Proset@{u h} P) M} :
  closure_functor (closure_of_monad M (MM := MM)) ≈ M :=
  monad_round_trip M.

(* N2 *)
Fail Example p463_rt_eq@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (M : Proset@{u h} P ⟶ Proset@{u h} P)
  {MM : @Monad (Proset@{u h} P) M} :
  closure_functor (closure_of_monad M (MM := MM)) = M := eq_refl.

(* CONTROL: the flip of N2, the functor's law fields written as
   transparent [I]; its object map is M's on the nose. *)
Definition p463_Functor_of_monotone_T@{u h} {A : Type@{u}} {R : relation A}
  (P : PreOrder R) (f : @MonotoneFun@{u u} A R A R) :
  Proset@{u h} P ⟶ Proset@{u h} P :=
  @Build_Functor (Proset@{u h} P) (Proset@{u h} P) (mono_map f)
    (fun x y h => mono_pres f x y h)
    (fun _ _ _ _ _ => I) (fun _ => I) (fun _ _ _ _ _ => I).

Example p463_rt_fobj_T@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (M : Proset@{u h} P ⟶ Proset@{u h} P)
  {MM : @Monad (Proset@{u h} P) M} (x : A) :
  fobj[p463_Functor_of_monotone_T@{u h} P
         (cl_fun (closure_of_monad M (MM := MM)))] x = fobj[M] x
  := eq_refl.

(* N3 *)
Fail Example p463_rt_eq_T@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (M : Proset@{u h} P ⟶ Proset@{u h} P)
  {MM : @Monad (Proset@{u h} P) M} :
  p463_Functor_of_monotone_T@{u h} P (cl_fun (closure_of_monad M (MM := MM)))
    = M := eq_refl.

(* CONTROL: Seven Sketches' isomorphism as the FIELD, the design the
   record does not take, with its two directions. *)
Record p463_ClosureOperatorIso@{u h} {A : Type@{u}} {R : relation A}
  (P : PreOrder R) := {
  p463_ci_fun  : @MonotoneFun@{u u} A R A R;
  p463_ci_ext  : ∀ x, R x (p463_ci_fun x);
  p463_ci_idem : ∀ x, p463_ci_fun (p463_ci_fun x)
                        ≅[Proset@{u h} P] p463_ci_fun x
}.

Arguments p463_ci_fun {A R P} _.
Arguments p463_ci_ext {A R P} _ _.
Arguments p463_ci_idem {A R P} _ _.

Definition p463_iso_monad@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : p463_ClosureOperatorIso@{u h} P) :
  @Monad (Proset@{u h} P) (Functor_of_monotone P P (p463_ci_fun c)) :=
  @Build_Monad (Proset@{u h} P) (Functor_of_monotone P P (p463_ci_fun c))
    (fun x => p463_ci_ext c x) (fun x => to (p463_ci_idem c x))
    (fun _ _ _ => I) (fun _ => I) (fun _ => I) (fun _ => I)
    (fun _ _ _ => I).

Definition p463_iso_of_monad@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (M : Proset@{u h} P ⟶ Proset@{u h} P)
  {MM : @Monad (Proset@{u h} P) M} : p463_ClosureOperatorIso@{u h} P :=
  {| p463_ci_fun  := monotone_of_Functor P P M
   ; p463_ci_ext  := fun x => @ret _ M MM x
   ; p463_ci_idem := fun x =>
       @Build_Isomorphism (Proset@{u h} P) _ _
         (@join _ M MM x) (@ret _ M MM (M x)) I I |}.

(* N4 *)
Fail Example p463_iso_round_trip@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : p463_ClosureOperatorIso@{u h} P) :
  p463_iso_of_monad (Functor_of_monotone P P (p463_ci_fun c))
    (MM := p463_iso_monad c) = c := eq_refl.

(* CONTROL: the [to] leg of [closure_of_iso]'s isomorphism is the given
   one. *)
Example p463_iso_to@{u h} {A : Type@{u}} {R : relation A}
  (P : PreOrder R) (f : @MonotoneFun@{u u} A R A R) (ext : ∀ x, R x (f x))
  (idem : ∀ x, f (f x) ≅[Proset@{u h} P] f x) (x : A) :
  to (cl_idem@{u h} (closure_of_iso P f ext idem) x) = to (idem x)
  := eq_refl.

(* N5 *)
Fail Example p463_iso_whole@{u h} {A : Type@{u}} {R : relation A}
  (P : PreOrder R) (f : @MonotoneFun@{u u} A R A R) (ext : ∀ x, R x (f x))
  (idem : ∀ x, f (f x) ≅[Proset@{u h} P] f x) (x : A) :
  cl_idem@{u h} (closure_of_iso P f ext idem) x = idem x := eq_refl.

(** ** The thin route, bare and pinned: Monad.v, Interior.v, Modal.v *)

(* CONTROL: [closure_monad] through [thin_monad] with the thin level
   pinned to u, to h, or left extensible. *)
Definition p463_cm_thin_u@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : ClosureOperator@{u} P) :
  @Monad (Proset@{u h} P) (closure_functor c) :=
  @thin_monad@{u u h} (Proset@{u h} P) (fun _ _ _ _ => I)
    (closure_functor c) (cl_ext c) (cl_mult c).

Definition p463_cm_thin_h@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : ClosureOperator@{u} P) :
  @Monad (Proset@{u h} P) (closure_functor c) :=
  @thin_monad@{h u h} (Proset@{u h} P) (fun _ _ _ _ => I)
    (closure_functor c) (cl_ext c) (cl_mult c).

Definition p463_cm_thin_plus@{u h +} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : ClosureOperator@{u} P) :
  @Monad (Proset@{u h} P) (closure_functor c) :=
  @thin_monad (Proset@{u h} P) (fun _ _ _ _ => I)
    (closure_functor c) (cl_ext c) (cl_mult c).

(* N6 *)
Fail Definition p463_cm_thin_bare@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : ClosureOperator@{u} P) :
  @Monad (Proset@{u h} P) (closure_functor c) :=
  @thin_monad (Proset@{u h} P) (fun _ _ _ _ => I)
    (closure_functor c) (cl_ext c) (cl_mult c).

(* CONTROL: the same three for [interior_comonad] through
   [thin_comonad]. *)
Definition p463_ic_thin_u@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (j : InteriorOperator@{u} P) :
  @Comonad (Proset@{u h} P) (interior_functor j) :=
  @thin_comonad@{u u h} (Proset@{u h} P) (fun _ _ _ _ => I)
    (interior_functor j) (cl_ext j) (cl_mult j).

Definition p463_ic_thin_h@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (j : InteriorOperator@{u} P) :
  @Comonad (Proset@{u h} P) (interior_functor j) :=
  @thin_comonad@{h u h} (Proset@{u h} P) (fun _ _ _ _ => I)
    (interior_functor j) (cl_ext j) (cl_mult j).

Definition p463_ic_thin_plus@{u h +} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (j : InteriorOperator@{u} P) :
  @Comonad (Proset@{u h} P) (interior_functor j) :=
  @thin_comonad (Proset@{u h} P) (fun _ _ _ _ => I)
    (interior_functor j) (cl_ext j) (cl_mult j).

(* N7 *)
Fail Definition p463_ic_thin_bare@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (j : InteriorOperator@{u} P) :
  @Comonad (Proset@{u h} P) (interior_functor j) :=
  @thin_comonad (Proset@{u h} P) (fun _ _ _ _ => I)
    (interior_functor j) (cl_ext j) (cl_mult j).

(* CONTROL: the same three for [modal_monad] through [thin_monad]. *)
Definition p463_mm_thin_u@{u h} (B : Prop) :
  @Monad Props@{u h} (modal_functor@{u h} B) :=
  @thin_monad@{u u h} Props@{u h} (fun _ _ _ _ => I) (modal_functor@{u h} B)
    (modal_ext B) (modal_mult B).

Definition p463_mm_thin_h@{u h} (B : Prop) :
  @Monad Props@{u h} (modal_functor@{u h} B) :=
  @thin_monad@{h u h} Props@{u h} (fun _ _ _ _ => I) (modal_functor@{u h} B)
    (modal_ext B) (modal_mult B).

Definition p463_mm_thin_plus@{u h +} (B : Prop) :
  @Monad Props@{u h} (modal_functor@{u h} B) :=
  @thin_monad Props@{u h} (fun _ _ _ _ => I) (modal_functor@{u h} B)
    (modal_ext B) (modal_mult B).

(* N8 *)
Fail Definition p463_mm_thin_bare@{u h} (B : Prop) :
  @Monad Props@{u h} (modal_functor@{u h} B) :=
  @thin_monad Props@{u h} (fun _ _ _ _ => I) (modal_functor@{u h} B)
    (modal_ext B) (modal_mult B).

(** ** Construction/Reflective/Idempotent/Induced.v *)

(* CONTROL: the composite is M on objects and on arrows, the induced
   unit is ret at ≈, and the dual at C^op. *)
Example p463_idem_obj@{o h d s | h < s +} {C : Category@{o h h}}
  {M : C ⟶ C} {MM : @Monad C M} {IM : @IdempotentMonad C M MM} (x : C) :
  fobj[Incl C (@MLocal_Subcategory C M MM)
         ◯ @idem_reflector@{o h d h h s} C M MM IM] x = M x := eq_refl.

Example p463_idem_fmap@{o h d s | h < s +} {C : Category@{o h h}}
  {M : C ⟶ C} {MM : @Monad C M} {IM : @IdempotentMonad C M MM} {x y : C}
  (f : x ~> y) :
  fmap[Incl C (@MLocal_Subcategory C M MM)
         ◯ @idem_reflector@{o h d h h s} C M MM IM] f = fmap[M] f := eq_refl.

Definition p463_idem_unit@{o h d s a | h < s +} {C : Category@{o h h}}
  {M : C ⟶ C} {MM : @Monad C M} {IM : @IdempotentMonad C M MM} (x : C) :
  @ret C _ (Adjunction_Induced_Monad
              (@idem_reflective_adj@{o h d a h s} C M MM IM)) x
    ≈ @ret C M MM x := idem_unit_agrees x.

Definition p463_idem_counit@{o h d s a | h < s +} {C : Category@{o h h}}
  {W : C ⟶ C} {H : @Comonad C W} {IH : IdempotentComonad W H} (x : C) :
  @ret (C^op) _ (Adjunction_Induced_Monad
                   (@idem_reflective_adj@{o h d a h s} (C^op) (W^op) H IH)) x
    ≈ @extract C W H x := idem_counit_agrees x.

(* N9 *)
Fail Example p463_idem_ret_refl@{o h d s a | h < s +} {C : Category@{o h h}}
  {M : C ⟶ C} {MM : @Monad C M} {IM : @IdempotentMonad C M MM} (x : C) :
  @ret C _ (Adjunction_Induced_Monad
              (@idem_reflective_adj@{o h d a h s} C M MM IM)) x
    = @ret C M MM x := eq_refl.

(* N10 *)
Fail Example p463_idem_join_refl@{o h d s a | h < s +} {C : Category@{o h h}}
  {M : C ⟶ C} {MM : @Monad C M} {IM : @IdempotentMonad C M MM} (x : C) :
  @join C _ (Adjunction_Induced_Monad
               (@idem_reflective_adj@{o h d a h s} C M MM IM)) x
    = @join C M MM x := eq_refl.

(* N11 *)
Fail Example p463_idem_fun_refl@{o h d s | h < s +} {C : Category@{o h h}}
  {M : C ⟶ C} {MM : @Monad C M} {IM : @IdempotentMonad C M MM} :
  Incl C (@MLocal_Subcategory C M MM)
    ◯ @idem_reflector@{o h d h h s} C M MM IM = M := eq_refl.

(** ** Instance/Proset/Monad/Awodey.v *)

(* CONTROL: T = i ∘ t on objects and on arrows, the induced monotone map
   is c's, and t (i k) agrees with cl k on first components and is
   isomorphic to k. *)
Example p463_aw_obj@{u h +} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : ClosureOperator@{u} P) (x : A) :
  fobj[GaloisFunctor_r@{u u h} P (closed_PreOrder c) (closed_galois c)
       ◯ GaloisFunctor_l@{u u h} P (closed_PreOrder c) (closed_galois c)] x
    = cl_fun c x := eq_refl.

Example p463_aw_fmap@{u h +} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : ClosureOperator@{u} P) (x y : A) (f : R x y) :
  fmap[GaloisFunctor_r@{u u h} P (closed_PreOrder c) (closed_galois c)
       ◯ GaloisFunctor_l@{u u h} P (closed_PreOrder c) (closed_galois c)] f
    = fmap[closure_functor@{u h} c] f := eq_refl.

Example p463_aw_is_c@{u h s a | h < s +} {A : Type@{u}}
  {R : relation A} {P : PreOrder R} (c : ClosureOperator@{u} P) :
  cl_fun (closure_of_monad _
            (MM := Adjunction_Induced_Monad (closed_adj@{u h s a} c)))
    = cl_fun c := eq_refl.

Example p463_aw_tik_fst@{u} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : ClosureOperator@{u} P) (k : ClosedElt c) :
  proj1_sig (closed_t c (closed_i c k)) = cl_fun c (proj1_sig k)
  := eq_refl.

Definition p463_aw_tik_iso@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : ClosureOperator@{u} P) (k : ClosedElt c) :
  closed_t c (closed_i c k) ≅[Proset@{u h} (closed_PreOrder c)] k :=
  closed_tik_iso c k.

Definition p463_aw_functor@{u h +} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : ClosureOperator@{u} P) :
  GaloisFunctor_r@{u u h} P (closed_PreOrder c) (closed_galois c)
    ◯ GaloisFunctor_l@{u u h} P (closed_PreOrder c) (closed_galois c)
    ≈ closure_functor@{u h} c := closed_induced_functor c.

(* N12 *)
Fail Example p463_aw_record@{u h s a | h < s +} {A : Type@{u}}
  {R : relation A} {P : PreOrder R} (c : ClosureOperator@{u} P) :
  closure_of_monad _ (MM := Adjunction_Induced_Monad (closed_adj@{u h s a} c))
    = c := eq_refl.

(* N13 *)
Fail Example p463_aw_functor_eq@{u h +} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : ClosureOperator@{u} P) :
  GaloisFunctor_r@{u u h} P (closed_PreOrder c) (closed_galois c)
    ◯ GaloisFunctor_l@{u u h} P (closed_PreOrder c) (closed_galois c)
    = closure_functor@{u h} c := eq_refl.

(* N14 *)
Fail Example p463_aw_tik@{u} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (c : ClosureOperator@{u} P) (k : ClosedElt c) :
  closed_t c (closed_i c k) = k := eq_refl.

(** ** Instance/Proset/Monad/Interior.v: the reversed order *)

(* CONTROL: (Proset P)^op and the reversed order have the same objects
   and homs; with Instance/Proset/Limit.v's transparent [op_PreOrder]
   the identity and composition agree too. *)
Example p463_op_obj@{u h} {A : Type@{u}} {R : relation A} (P : PreOrder R) :
  obj[(Proset@{u h} P)^op] = obj[Proset@{u h} (flip_PreOrder P)] := eq_refl.

Example p463_op_hom@{u h} {A : Type@{u}} {R : relation A} (P : PreOrder R)
  (x y : A) :
  (x ~{(Proset@{u h} P)^op}~> y) = (x ~{Proset@{u h} (flip_PreOrder P)}~> y)
  := eq_refl.

Example p463_opT_id@{u h} {A : Type@{u}} {R : relation A} (P : PreOrder R) :
  @id ((Proset@{u h} P)^op) = @id (Proset@{u h} (op_PreOrder P)) := eq_refl.

Example p463_opT_compose@{u h} {A : Type@{u}} {R : relation A}
  (P : PreOrder R) :
  @compose ((Proset@{u h} P)^op) = @compose (Proset@{u h} (op_PreOrder P))
  := eq_refl.

(* N15 *)
Fail Example p463_op_eq@{u h} {A : Type@{u}} {R : relation A}
  (P : PreOrder R) :
  ((Proset@{u h} P)^op)%category = Proset@{u h} (flip_PreOrder P)
  := eq_refl.

(* N16 *)
Fail Example p463_op_id@{u h} {A : Type@{u}} {R : relation A}
  (P : PreOrder R) :
  @id ((Proset@{u h} P)^op) = @id (Proset@{u h} (flip_PreOrder P))
  := eq_refl.

(* N17 *)
Fail Definition p463_op_cast@{u h} {A : Type@{u}} {R : relation A}
  (P : PreOrder R) (W : (Proset@{u h} P)^op ⟶ (Proset@{u h} P)^op) :
  Proset@{u h} (flip_PreOrder P) ⟶ Proset@{u h} (flip_PreOrder P) := W.

(* N18 *)
Fail Example p463_opT_eq@{u h} {A : Type@{u}} {R : relation A}
  (P : PreOrder R) :
  ((Proset@{u h} P)^op)%category = Proset@{u h} (op_PreOrder P) := eq_refl.

(** ** Instance/Proset/Monad/Interior.v: the correspondence *)

(* CONTROL: interior → comonad → interior on the whole record; the
   comonad's functor on objects and arrows, and its counit and
   comultiplication; Riehl's route as [thin_monad] on the whole record;
   [flip_functor W] against the opposite on objects and arrows and at
   ≈. *)
Example p463_int_round_trip@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (j : InteriorOperator@{u} P) :
  interior_of_comonad@{u h} (interior_functor@{u h} j)
    (H := interior_comonad j) = j := eq_refl.

Example p463_crt_fobj@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (W : Proset@{u h} P ⟶ Proset@{u h} P)
  {H : @Comonad (Proset@{u h} P) W} (x : A) :
  fobj[interior_functor (interior_of_comonad W (H := H))] x = fobj[W] x
  := eq_refl.

Example p463_crt_fmap@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (W : Proset@{u h} P ⟶ Proset@{u h} P)
  {H : @Comonad (Proset@{u h} P) W} (x y : A) (f : R x y) :
  fmap[interior_functor (interior_of_comonad W (H := H))] f = fmap[W] f
  := eq_refl.

Example p463_crt_extract@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (W : Proset@{u h} P ⟶ Proset@{u h} P)
  {H : @Comonad (Proset@{u h} P) W} (x : A) :
  @extract _ _ (interior_comonad (interior_of_comonad W (H := H))) x
    = @extract _ W H x := eq_refl.

Example p463_crt_duplicate@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (W : Proset@{u h} P ⟶ Proset@{u h} P)
  {H : @Comonad (Proset@{u h} P) W} (x : A) :
  @duplicate _ _ (interior_comonad (interior_of_comonad W (H := H))) x
    = @duplicate _ W H x := eq_refl.

Example p463_flip_is_thin@{u h t} {A : Type@{u}}
  {R : relation A} {P : PreOrder R} (W : Proset@{u h} P ⟶ Proset@{u h} P)
  {H : @Comonad (Proset@{u h} P) W} :
  comonad_flip_monad W (H := H)
    = @thin_monad@{t u h} (Proset@{u h} (flip_PreOrder P))
        (fun _ _ _ _ => I) (flip_functor W)
        (fun x => @extract _ W H x) (fun x => @duplicate _ W H x)
  := eq_refl.

Example p463_flipop_fobj@{u h n | h < n +} {A : Type@{u}}
  {R : relation A}
  {P : PreOrder R} (W : Proset@{u h} P ⟶ Proset@{u h} P) (x : A) :
  fobj[flip_functor W] x
    = fobj[Proset_op_to P ◯ W^op ◯ Proset_op_from P] x := eq_refl.

Example p463_flipop_fmap@{u h n | h < n +} {A : Type@{u}}
  {R : relation A}
  {P : PreOrder R} (W : Proset@{u h} P ⟶ Proset@{u h} P) (x y : A)
  (f : Basics.flip R x y) :
  fmap[flip_functor W] f
    = fmap[Proset_op_to P ◯ W^op ◯ Proset_op_from P] f := eq_refl.

Definition p463_flipop_equiv@{u h m n | h < n, u <= m, h <= m +}
  {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (W : Proset@{u h} P ⟶ Proset@{u h} P) :
  flip_functor W ≈ Proset_op_to P ◯ W^op ◯ Proset_op_from P :=
  flip_functor_is_op W.

(* N19 *)
Fail Example p463_crt_eq@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (W : Proset@{u h} P ⟶ Proset@{u h} P)
  {H : @Comonad (Proset@{u h} P) W} :
  interior_functor (interior_of_comonad W (H := H)) = W := eq_refl.

(* N20 *)
Fail Example p463_crt_eq_T@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (W : Proset@{u h} P ⟶ Proset@{u h} P)
  {H : @Comonad (Proset@{u h} P) W} :
  p463_Functor_of_monotone_T@{u h} P
    (unflip_mono (cl_fun (interior_of_comonad W (H := H)))) = W := eq_refl.

(* N21 *)
Fail Example p463_flipop_eq@{u h} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (W : Proset@{u h} P ⟶ Proset@{u h} P) :
  flip_functor W = Proset_op_to P ◯ W^op ◯ Proset_op_from P := eq_refl.

(* CONTROL: the flip of N22.  Structure/Thin.v's [Thin_Opposite] restated
   with a transparent body; with the tree's own [thin_monad], the whole
   comonad is [eq_refl]. *)
Definition p463_Thin_Opposite_T@{t o h} {C : Category@{o h h}}
  (T : Category.Structure.Thin.Thin@{t o h} C) :
  Category.Structure.Thin.Thin@{t o h} (C^op) :=
  fun x y f g => T y x f g.

Example p463_ic_thin_T@{u h t} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (j : InteriorOperator@{u} P) :
  interior_comonad@{u h} j
    = @thin_monad@{t u h} ((Proset@{u h} P)^op)
        (p463_Thin_Opposite_T@{t u h} (C := Proset@{u h} P)
           (fun _ _ _ _ => I))
        ((interior_functor j)^op) (cl_ext j) (cl_mult j) := eq_refl.

(* N22 *)
Fail Example p463_ic_thin_eq@{u h t} {A : Type@{u}} {R : relation A}
  {P : PreOrder R} (j : InteriorOperator@{u} P) :
  interior_comonad@{u h} j
    = @thin_comonad@{t u h} (Proset@{u h} P) (fun _ _ _ _ => I)
        (interior_functor j) (cl_ext j) (cl_mult j) := eq_refl.

(** ** Instance/Props/Modal.v *)

(* CONTROL: the modal monad as [thin_monad] on the whole record, with its
   multiplication the transparent term, and join computing; the curry
   functor's object map; the two functors at ≈. *)
Example p463_modal_is_thin@{u h t} (B : Prop) :
  modal_monad@{u h} B
    = @thin_monad@{t u h} Props@{u h} (fun _ _ _ _ => I)
        (modal_functor@{u h} B) (modal_ext B) (fun p f b => f b b)
  := eq_refl.

Example p463_modal_join@{u h} (B p : Prop) (f : B → (B → p)) (b : B) :
  @join _ _ (modal_monad@{u h} B) p f b = f b b := eq_refl.

Example p463_curry_fobj@{u h e | h < e +} (B p : Prop) :
  fobj[curry_functor@{u h e} Props_Closed B] p = (B → p /\ B) := eq_refl.

Definition p463_curry_iso@{u h e + | h < e +} (B : Prop) :
  curry_functor@{u h e} Props_Closed B ≈ modal_functor@{u h} B :=
  curry_modal_iso B.

(* N23 *)
Fail Example p463_curry_is_modal_fobj@{u h e | h < e +} (B p : Prop) :
  fobj[curry_functor@{u h e} Props_Closed B] p = fobj[modal_functor@{u h} B] p
  := eq_refl.

(* N24 *)
Fail Example p463_curry_is_modal@{u h e | h < e +} (B : Prop) :
  curry_functor@{u h e} Props_Closed B = modal_functor@{u h} B := eq_refl.

(* CONTROL: at [impl_PreOrder] the objects, homs, identity and
   composition of [Props] and [Proset impl_PreOrder] agree. *)
Example p463_props_obj : obj[Props] = obj[Proset impl_PreOrder] := eq_refl.

Example p463_props_hom (p q : Prop) :
  (p ~{Props}~> q) = (p ~{Proset impl_PreOrder}~> q) := eq_refl.

Example p463_props_id : @id Props = @id (Proset impl_PreOrder) := eq_refl.

Example p463_props_compose :
  @compose Props = @compose (Proset impl_PreOrder) := eq_refl.

(* N25 *)
Fail Example p463_props_is_proset : Props = Proset impl_PreOrder := eq_refl.

(* N26 *)
Fail Example p463_props_is_any_proset (P : PreOrder Basics.impl) :
  Props = Proset P := eq_refl.

(* CONTROL: the flip of N25 and N26.  The two [Program Definition]s
   restated verbatim with their obligations transparent: at
   [impl_PreOrder] the whole records are [eq_refl]; for a variable P the
   objects and homs agree. *)
Module P463Flip.

#[local] Set Transparent Obligations.

Program Definition Props_T : Category := {|
  obj     := Prop;
  hom     := Basics.impl;
  homset  := fun P Q => {| Setoid.equiv := fun f g => True |};
  id      := fun _ x => x;
  compose := fun _ _ _ g f x => g (f x)
|}.

Program Definition Proset_T {A : Type} {R : relation A} (P : PreOrder R) :
  Category := {|
  obj     := A;
  hom     := R;
  homset  := fun A B => {| Setoid.equiv := fun _ _ => True |};
  id      := fun x => @reflexivity A R (@PreOrder_Reflexive A R P) x;
  compose := fun x y z f g =>
    @transitivity A R (@PreOrder_Transitive A R P) x y z g f
|}.

Example p463_props_T : Props_T = Proset_T impl_PreOrder := eq_refl.

Example p463_props_var_T (P : PreOrder Basics.impl) :
  (@obj Props_T, @hom Props_T) = (@obj (Proset_T P), @hom (Proset_T P))
  := eq_refl.

(* N27 *)
Fail Example p463_props_any_T (P : PreOrder Basics.impl) :
  Props_T = Proset_T P := eq_refl.

End P463Flip.

(** ** Instance/Top/Interior.v *)

(* CONTROL: the coalgebras of the interior comonad are the open subsets;
   {true} in the indiscrete two-point space is not one; the algebras of
   the ¬ int ¬ closure are the complements of opens; the converse of the
   footnote-5 algebra half without [lem] gives ¬¬(∀ q, ¬¬q → q). *)
Definition p463_pint_coalg@{o h p} (X : PTop@{o})
  (S : carrier (Powerset_Prop_obj (pt_carrier X))) :
  iffT@{h p}
    (@WCoalgebra (Subsets@{o h} (pt_carrier X))
       (interior_functor (pinterior_op X)) (pinterior_comonad X) S)
    (POpen X S) :=
  pint_coalgebra_iff_open X S.

Definition p463_true_sub_not_open@{o h} :
  @WCoalgebra (Subsets@{o h} (pt_carrier PTwoIndisc@{o}))
    (interior_functor (pinterior_op PTwoIndisc))
    (pinterior_comonad PTwoIndisc) true_sub → False :=
  true_sub_not_coalgebra.

Definition p463_ncl_algebra@{o h p} (X : PTop@{o})
  (S : carrier (Powerset_Prop_obj (pt_carrier X))) :
  iffT@{h p}
    (@TAlgebra (Subsets@{o h} (pt_carrier X))
       (closure_functor (nclosure_op X)) (nclosure_monad X) S)
    (PCoOpen X S) :=
  ncl_talgebra_iff_coopen X S.

Definition p463_converse_nndne@{o h} :
  (∀ (X : PTop@{o}) (S : carrier (Powerset_Prop_obj (pt_carrier X))),
     @TAlgebra (Subsets@{o h} (pt_carrier X))
       (closure_functor (pclosure_op X)) (pclosure_monad X) S →
     PClosedSub X S) →
  ~ ~ (∀ q : Prop, ~ ~ q → q) :=
  pcl_converse_nndne.

(** ** Closure: a readback, not a refutation *)

Print Assumptions closure_of_monad.
Print Assumptions closure_monad.
Print Assumptions monad_closure_iff.
Print Assumptions talgebra_iff_closed.
Print Assumptions thin_IdempotentMonad.
Print Assumptions idem_Monad_agrees.
Print Assumptions closed_adj.
Print Assumptions interior_of_comonad.
Print Assumptions wcoalgebra_iff_open.
Print Assumptions modal_monad.
Print Assumptions pint_coalgebra_iff_open.
Print Assumptions pcl_converse_nndne.

(** ** Guard: the constants of the seven targets *)

(* Structure/Thin/Monad.v: 14 names. *)
Check @Category.Structure.Thin.Monad.thin_IdempotentComonad.
Check @Category.Structure.Thin.Monad.thin_IdempotentMonad.
Check @Category.Structure.Thin.Monad.thin_comonad.
Check @Category.Structure.Thin.Monad.thin_comonad_duplicate.
Check @Category.Structure.Thin.Monad.thin_comonad_extract.
Check @Category.Structure.Thin.Monad.thin_coreflective.
Check @Category.Structure.Thin.Monad.thin_join_IsIso.
Check @Category.Structure.Thin.Monad.thin_monad.
Check @Category.Structure.Thin.Monad.thin_monad_join.
Check @Category.Structure.Thin.Monad.thin_monad_ret.
Check @Category.Structure.Thin.Monad.thin_talgebra_iff.
Check @Category.Structure.Thin.Monad.thin_talgebra_round.
Check @Category.Structure.Thin.Monad.thin_wcoalgebra_iff.
Check @Category.Structure.Thin.Monad.thin_wcoalgebra_round.

(* Construction/Reflective/Idempotent/Induced.v: 8 names. *)
Check @Category.Construction.Reflective.Idempotent.Induced.idem_Comonad_agrees.
Check @Category.Construction.Reflective.Idempotent.Induced.idem_Monad_agrees.
Check @Category.Construction.Reflective.Idempotent.Induced.idem_comult_agrees.
Check @Category.Construction.Reflective.Idempotent.Induced.idem_counit_agrees.
Check @Category.Construction.Reflective.Idempotent.Induced.idem_factorisation_fmap.
Check @Category.Construction.Reflective.Idempotent.Induced.idem_factorisation_obj.
Check @Category.Construction.Reflective.Idempotent.Induced.idem_join_agrees.
Check @Category.Construction.Reflective.Idempotent.Induced.idem_unit_agrees.

(* Instance/Proset/Monad.v: 36 names. *)
Check @Category.Instance.Proset.Monad.Build_ClosureOperator.
Check @Category.Instance.Proset.Monad.ClosureOperator.
Check @Category.Instance.Proset.Monad.cl_ext.
Check @Category.Instance.Proset.Monad.cl_fun.
Check @Category.Instance.Proset.Monad.cl_idem.
Check @Category.Instance.Proset.Monad.cl_mult.
Check @Category.Instance.Proset.Monad.closed_eq.
Check @Category.Instance.Proset.Monad.closed_iff_fixed.
Check @Category.Instance.Proset.Monad.closure_functor.
Check @Category.Instance.Proset.Monad.closure_idem_eq.
Check @Category.Instance.Proset.Monad.closure_monad.
Check @Category.Instance.Proset.Monad.closure_monad_is_thin.
Check @Category.Instance.Proset.Monad.closure_of_iso.
Check @Category.Instance.Proset.Monad.closure_of_iso_to.
Check @Category.Instance.Proset.Monad.closure_of_monad.
Check @Category.Instance.Proset.Monad.closure_round_trip.
Check @Category.Instance.Proset.Monad.max_closed_iff.
Check @Category.Instance.Proset.Monad.max_closure.
Check @Category.Instance.Proset.Monad.max_mono.
Check @Category.Instance.Proset.Monad.max_mult.
Check @Category.Instance.Proset.Monad.mlocal_iff_closed.
Check @Category.Instance.Proset.Monad.monad_closure_iff.
Check @Category.Instance.Proset.Monad.monad_round_trip.
Check @Category.Instance.Proset.Monad.monad_round_trip_fmap.
Check @Category.Instance.Proset.Monad.monad_round_trip_fobj.
Check @Category.Instance.Proset.Monad.monad_round_trip_join.
Check @Category.Instance.Proset.Monad.monad_round_trip_ret.
Check @Category.Instance.Proset.Monad.poset_closure_of_monad.
Check @Category.Instance.Proset.Monad.proset_EM_equivalence.
Check @Category.Instance.Proset.Monad.proset_factorisation_fmap.
Check @Category.Instance.Proset.Monad.proset_factorisation_obj.
Check @Category.Instance.Proset.Monad.proset_fixed_adj.
Check @Category.Instance.Proset.Monad.succ_not_monad.
Check @Category.Instance.Proset.Monad.talgebra_iff_closed.
Check @Category.Instance.Proset.Monad.talgebra_iff_closed_via_idem.
Check @Category.Instance.Proset.Monad.talgebra_round.

(* Instance/Proset/Monad/Awodey.v: 14 names. *)
Check @Category.Instance.Proset.Monad.Awodey.ClosedElt.
Check @Category.Instance.Proset.Monad.Awodey.closed_PreOrder.
Check @Category.Instance.Proset.Monad.Awodey.closed_adj.
Check @Category.Instance.Proset.Monad.Awodey.closed_factorisation_fmap.
Check @Category.Instance.Proset.Monad.Awodey.closed_factorisation_obj.
Check @Category.Instance.Proset.Monad.Awodey.closed_galois.
Check @Category.Instance.Proset.Monad.Awodey.closed_i.
Check @Category.Instance.Proset.Monad.Awodey.closed_induced_functor.
Check @Category.Instance.Proset.Monad.Awodey.closed_induced_is_c.
Check @Category.Instance.Proset.Monad.Awodey.closed_le.
Check @Category.Instance.Proset.Monad.Awodey.closed_t.
Check @Category.Instance.Proset.Monad.Awodey.closed_tik_eq.
Check @Category.Instance.Proset.Monad.Awodey.closed_tik_fst.
Check @Category.Instance.Proset.Monad.Awodey.closed_tik_iso.

(* Instance/Proset/Monad/Interior.v: 53 names. *)
Check @Category.Instance.Proset.Monad.Interior.InteriorOperator.
Check @Category.Instance.Proset.Monad.Interior.adj_closure.
Check @Category.Instance.Proset.Monad.Interior.adj_closure_fun.
Check @Category.Instance.Proset.Monad.Interior.adj_interior.
Check @Category.Instance.Proset.Monad.Interior.adj_interior_fun.
Check @Category.Instance.Proset.Monad.Interior.comonad_flip_join.
Check @Category.Instance.Proset.Monad.Interior.comonad_flip_monad.
Check @Category.Instance.Proset.Monad.Interior.comonad_flip_monad_is_thin.
Check @Category.Instance.Proset.Monad.Interior.comonad_flip_ret.
Check @Category.Instance.Proset.Monad.Interior.comonad_interior_iff.
Check @Category.Instance.Proset.Monad.Interior.comonad_round_trip.
Check @Category.Instance.Proset.Monad.Interior.comonad_round_trip_duplicate.
Check @Category.Instance.Proset.Monad.Interior.comonad_round_trip_extract.
Check @Category.Instance.Proset.Monad.Interior.comonad_round_trip_fmap.
Check @Category.Instance.Proset.Monad.Interior.comonad_round_trip_fobj.
Check @Category.Instance.Proset.Monad.Interior.flip_functor.
Check @Category.Instance.Proset.Monad.Interior.flip_functor_is_op.
Check @Category.Instance.Proset.Monad.Interior.flip_functor_is_op_fmap.
Check @Category.Instance.Proset.Monad.Interior.flip_functor_is_op_fobj.
Check @Category.Instance.Proset.Monad.Interior.flip_mono.
Check @Category.Instance.Proset.Monad.Interior.flip_unflip_mono.
Check @Category.Instance.Proset.Monad.Interior.int_comult.
Check @Category.Instance.Proset.Monad.Interior.int_defl.
Check @Category.Instance.Proset.Monad.Interior.int_idem.
Check @Category.Instance.Proset.Monad.Interior.int_idem_eq.
Check @Category.Instance.Proset.Monad.Interior.int_idem_to.
Check @Category.Instance.Proset.Monad.Interior.int_mono.
Check @Category.Instance.Proset.Monad.Interior.interior_comonad.
Check @Category.Instance.Proset.Monad.Interior.interior_comonad_duplicate.
Check @Category.Instance.Proset.Monad.Interior.interior_comonad_extract.
Check @Category.Instance.Proset.Monad.Interior.interior_functor.
Check @Category.Instance.Proset.Monad.Interior.interior_is_flip_closure.
Check @Category.Instance.Proset.Monad.Interior.interior_of_comonad.
Check @Category.Instance.Proset.Monad.Interior.interior_round_trip.
Check @Category.Instance.Proset.Monad.Interior.min_comult.
Check @Category.Instance.Proset.Monad.Interior.min_interior.
Check @Category.Instance.Proset.Monad.Interior.min_mono.
Check @Category.Instance.Proset.Monad.Interior.min_open_iff.
Check @Category.Instance.Proset.Monad.Interior.min_three_not_open.
Check @Category.Instance.Proset.Monad.Interior.open_eq.
Check @Category.Instance.Proset.Monad.Interior.open_iff_fixed.
Check @Category.Instance.Proset.Monad.Interior.proset_open_coreflective.
Check @Category.Instance.Proset.Monad.Interior.shift_closure_fun.
Check @Category.Instance.Proset.Monad.Interior.shift_closure_is_max.
Check @Category.Instance.Proset.Monad.Interior.shift_interior_fun.
Check @Category.Instance.Proset.Monad.Interior.shift_interior_is_id.
Check @Category.Instance.Proset.Monad.Interior.unflip_flip_mono.
Check @Category.Instance.Proset.Monad.Interior.unflip_mono.
Check @Category.Instance.Proset.Monad.Interior.wcoalgebra_iff_flip_talgebra.
Check @Category.Instance.Proset.Monad.Interior.wcoalgebra_iff_open.
Check @Category.Instance.Proset.Monad.Interior.wcoalgebra_iff_open_via_thin.
Check @Category.Instance.Proset.Monad.Interior.wcoalgebra_round.
Check @Category.Instance.Proset.Monad.Interior.wlocal_iff_open.

(* Instance/Props/Modal.v: 30 names. *)
Check @Category.Instance.Props.Modal.curry_cofunctor.
Check @Category.Instance.Props.Modal.curry_comonad.
Check @Category.Instance.Props.Modal.curry_comonad_fobj.
Check @Category.Instance.Props.Modal.curry_comonad_is_and.
Check @Category.Instance.Props.Modal.curry_functor.
Check @Category.Instance.Props.Modal.curry_modal_closed_iff.
Check @Category.Instance.Props.Modal.curry_modal_fobj_ext.
Check @Category.Instance.Props.Modal.curry_modal_iso.
Check @Category.Instance.Props.Modal.curry_monad.
Check @Category.Instance.Props.Modal.curry_monad_fobj.
Check @Category.Instance.Props.Modal.curry_open_iff_entails.
Check @Category.Instance.Props.Modal.curry_talgebra_iff.
Check @Category.Instance.Props.Modal.curry_wcoalgebra_iff.
Check @Category.Instance.Props.Modal.impl_PreOrder.
Check @Category.Instance.Props.Modal.modal_closure.
Check @Category.Instance.Props.Modal.modal_closure_fobj.
Check @Category.Instance.Props.Modal.modal_closure_join.
Check @Category.Instance.Props.Modal.modal_closure_ret.
Check @Category.Instance.Props.Modal.modal_ext.
Check @Category.Instance.Props.Modal.modal_false_not_closed.
Check @Category.Instance.Props.Modal.modal_functor.
Check @Category.Instance.Props.Modal.modal_idem.
Check @Category.Instance.Props.Modal.modal_idem_ext.
Check @Category.Instance.Props.Modal.modal_monad.
Check @Category.Instance.Props.Modal.modal_monad_is_thin.
Check @Category.Instance.Props.Modal.modal_monad_join.
Check @Category.Instance.Props.Modal.modal_mono.
Check @Category.Instance.Props.Modal.modal_mult.
Check @Category.Instance.Props.Modal.modal_talgebra_iff.
Check @Category.Instance.Props.Modal.modal_talgebra_round.

(* Instance/Top/Interior.v: 46 names. *)
Check @Category.Instance.Top.Interior.PClosedSub.
Check @Category.Instance.Top.Interior.PCoOpen.
Check @Category.Instance.Top.Interior.closed_of_coopen_lem.
Check @Category.Instance.Top.Interior.coopen_of_closed_stable.
Check @Category.Instance.Top.Interior.coopen_stable.
Check @Category.Instance.Top.Interior.ncl.
Check @Category.Instance.Top.Interior.ncl_ext.
Check @Category.Instance.Top.Interior.ncl_mono.
Check @Category.Instance.Top.Interior.ncl_mult.
Check @Category.Instance.Top.Interior.ncl_sub_iff_coopen.
Check @Category.Instance.Top.Interior.ncl_talgebra_iff_coopen.
Check @Category.Instance.Top.Interior.nclosure_monad.
Check @Category.Instance.Top.Interior.nclosure_op.
Check @Category.Instance.Top.Interior.open_of_sub_pint.
Check @Category.Instance.Top.Interior.pcl_closed_of_sub.
Check @Category.Instance.Top.Interior.pcl_closed_of_talgebra.
Check @Category.Instance.Top.Interior.pcl_converse_nndne.
Check @Category.Instance.Top.Interior.pcl_ext.
Check @Category.Instance.Top.Interior.pcl_fun.
Check @Category.Instance.Top.Interior.pcl_mono.
Check @Category.Instance.Top.Interior.pcl_mult.
Check @Category.Instance.Top.Interior.pcl_proper.
Check @Category.Instance.Top.Interior.pcl_sub_of_closed.
Check @Category.Instance.Top.Interior.pcl_talgebra_of_closed.
Check @Category.Instance.Top.Interior.pcl_true_false_dne.
Check @Category.Instance.Top.Interior.pclosure.
Check @Category.Instance.Top.Interior.pclosure_monad.
Check @Category.Instance.Top.Interior.pclosure_ncl_lem.
Check @Category.Instance.Top.Interior.pclosure_op.
Check @Category.Instance.Top.Interior.pcomp.
Check @Category.Instance.Top.Interior.pcomp_proper.
Check @Category.Instance.Top.Interior.pint_coalgebra_iff_open.
Check @Category.Instance.Top.Interior.pint_comult.
Check @Category.Instance.Top.Interior.pint_defl.
Check @Category.Instance.Top.Interior.pint_fun.
Check @Category.Instance.Top.Interior.pint_mono.
Check @Category.Instance.Top.Interior.pint_open.
Check @Category.Instance.Top.Interior.pint_proper.
Check @Category.Instance.Top.Interior.pinterior.
Check @Category.Instance.Top.Interior.pinterior_comonad.
Check @Category.Instance.Top.Interior.pinterior_op.
Check @Category.Instance.Top.Interior.sub_pint_of_open.
Check @Category.Instance.Top.Interior.true_or_sub.
Check @Category.Instance.Top.Interior.true_sub.
Check @Category.Instance.Top.Interior.true_sub_not_coalgebra.
Check @Category.Instance.Top.Interior.true_sub_not_nclosed.
