(** * Probe for the free R-module monad T_R and its algebras (issue #472)

    Pins the measured boundaries of what #472 adds for Mac Lane, §VI.4,
    Exercise 2, book p. 146 (PDF p. 155), catalog item maclane:VI.4:ex2,
    read from the page image ("For any ring R with identity, the forgetful
    functor G: R-Mod→Set … has a left adjoint and so defines a monad
    ⟨T_R, η, μ⟩ in Set", parts (a) to (c)), with the items the issue
    appends: Riehl's Example 5.1.4(iii) (riehl:5.1:example4) and her §5.3
    opening construction, the case R = ℤ (riehl:5.3:construction-ab-
    monadic).  The targets are the hom-set forms of the free-forgetful
    adjunctions #472 adds to Instance/Mod/Free.v and Instance/Ab/Free.v,
    Instance/Mod/FreeMonad.v (T_R, part (a) on formal combinations and
    coefficients, part (b), part (c), monadicity), its satellite
    Instance/Mod/FreeMonad/FinSupp.v (T_R X ≅ the finitely supported
    functions) and Instance/Ab/FreeMonad.v (ℤ[−] and Ab ≅ Set^{ℤ[−]}).
    Their headers cite the refutations and controls here.  Each of the
    ninety-five [Example]s of the targets, all proved by [eq_refl], has a
    control that restates it independently of the constant that states it
    (RESTATEMENTS, below).

    THE IMPORT LIST, generated by a script over the [Require] lines.
    Target by target in dependency order: Instance/Mod/Free.v's fourteen
    [Require] lines in its own order, and that target; the seven lines
    Instance/Mod/FreeMonad.v adds, and that target; the one line the
    satellite adds (Instance/CMon/Biproduct.v), and the satellite;
    Instance/Ab/Free.v, which adds none; Instance/Ab/FreeMonad.v, which
    adds none, and that target.  Twenty-seven lines, twenty-six naming
    [Category] modules and one [Coq.ZArith.ZArith].
    Under them [Print Libraries] in a scratch file loads seventy-four
    [Category] modules, exactly the set a [Require] of the five targets
    alone loads (compared by script), none under [Reals].  A shorter
    import list is what makes a probe pass for no reason.

    DISCIPLINE.  Every negative other than the instrument is an
    [Example], never a [Check], so that an open evar cannot satisfy it.
    Each of the thirty refutation lines (the instrument and R1 to R29) was
    stripped of its refutation keyword in a copy of this WHOLE file, one
    at a time, compiled, and its error read; each copy stops inside the
    stripped command (thirty of thirty, by the File line of its error,
    compared by script with the command's extent).  Each of the one
    hundred and eleven controls, wrapped in the refutation keyword in a
    copy of this WHOLE file, stops the build at that command with the
    message Rocq prints for a refutation whose command succeeds (one
    hundred and eleven of one hundred and eleven, by the same script).
    Quotations are Rocq 9.1.1's under this file's import list, with the
    error's environment block left out; Rocq prints the "cannot unify"
    parenthetical with the short names and notations in scope (TRA, KA,
    ZA and ZKA are the four below).

    KINDS.  Thirty refutations, counted as the lines that open with the
    refutation keyword: NAME-ABSENCE, the instrument (one); and
    CONVERSION, [eq_refl] refused with a "cannot unify" parenthetical,
    every statement being well typed (R1 to R29: twenty-nine).

    CAUSES, MEASURED.  (1) None is the opacity of #472's own proofs:
    every refutation still stops inside its command, and every control is
    still accepted, in a copy of #472's five files and this probe under a
    renamed logical root with all seventy [Qed]s of #472's code turned
    [Defined].  (2) The two [Qed] layers of the universal-arrow
    adjunctions, measured in rebuilt copies of the seventy-four modules
    this file loads, each refutation unguarded in a copy of this whole
    file with every other refutation command removed: with
    Theory/Universal/Arrow.v's [ump_universal_arrows] alone turned
    [Defined], all twenty-nine are still refused; with Instance/Mod/
    Free.v's [free_module_universal] and Instance/Ab/Free.v's
    [free_ab_universal] alone, all twenty-nine; with all three, fifteen
    hold at [eq_refl] (R2 to R11, R14 and R23 to R26: the counits, route
    A's μ and comparison functor, and the free functors' [fmap]) and
    fourteen are still refused.  In that last copy Instance/Ab/Free.v's
    own negatives [counit_does_not_compute] and
    [fmap_generator_does_not_compute] hold as [Example]s too (Free.v's and
    Ab/Free.v's CORRECTION (#472); issue #1353 tracks the shared lemma,
    which is not turned [Defined] here).  (3) Read from the terms, for
    the fourteen: R12 is besides the fold stuck on a variable combination
    ([fv_eval_relabel] is a Leibniz lemma by induction, not a
    conversion); R1 and R22 compare adjunction records whose inverse
    transposes and law proofs differ; R13's sum collected over the
    deduplicated generators is a different term from the combination;
    R15 compares the rebuilt [PropEquiv] field with the module's own; R16,
    R18, R27 and R29 compare rebuilt records with variable ones; R17 and
    R28 compare the fold of the derived structure, a [Fixpoint], with a
    variable algebra's map; R19 and R20 compare composites whose object
    maps already differ from the identity's; R21 is the opacity of
    Theory/Functor.v's [Functor_Setoid_obligation_1] ([About]), whose
    [symmetry] Theory/Equivalence.v's [Equivalence_to_Cat_Iso] uses to
    build [iso_from_to], as #471's probe records for monoids.

    LABELS.  The labels are not constants: each refutation and each
    control carries its label in a comment on the line above it, the
    instrument's reading "The instrument".  The constants are
    [p472_cN_…] and [p472_rN_…] for label CN or RN.

    RESTATEMENTS.  Instance/Mod/Free.v: [free_module_hom_counit] C1,
    [free_module_hom_unit] C2, [free_module_hom_to] C3.
    Instance/Mod/FreeMonad.v: [TR_obj] C9, [TR_carrier] C10, [TR_ret] C11,
    [TR_ret_fun] C12, [TR_join_counit] C13, [TR_join_gen] C14,
    [TR_join_fun] C15, [TR_join_zero] C16, [TR_join_lc] C17,
    [TR_direct_ret] C29, [TR_direct_join] C30, [TR_direct_obj] C31,
    [TR_direct_map] C32, [TR_direct_map_gen] C33,
    [TR_direct_iso_component] C35, [RMod_EM_iso_to] C36,
    [RMod_EM_iso_from] C37, [RMod_K_carrier] C38, [RMod_K_map] C39,
    [RMod_K_alg] C40, [RMod_K_alg_fun] C41, [RMod_K_alg_gen] C42,
    [RMod_K_alg_zero] C43, [RMod_K_alg_plus] C44, [RMod_K_alg_neg] C45,
    [RMod_K_alg_smul] C46, [RMod_K_alg_lc] C47, [EM_to_RModS_carrier] C48,
    [EM_to_RModS_zero] C49, [EM_to_RModS_plus] C50, [EM_to_RModS_neg]
    C51, [EM_to_RModS_smul] C52, [EM_to_RModS_map] C53,
    [EM_to_RModS_prop] C54, [RMod_rt_carrier] C55, [RMod_rt_zero] C56,
    [RMod_rt_plus] C57, [RMod_rt_neg] C58, [RMod_rt_smul] C59,
    [RMod_rt_hom] C60, [TRAlg_rt_carrier] C61, [TRAlg_rt_alg_fun] C62,
    [TRAlg_rt_alg_hom] C64, [RMod_EM_iso_to_from_component] C65,
    [RMod_EM_iso_from_to_component] C66, [RMod_EM_counit_component] C67,
    [RMod_EM_unit_component] C68.  Instance/Mod/FreeMonad/FinSupp.v:
    [TR_coef_Z_true] C22, [TR_coef_Z_false] C23, [TR_coef_Z_join] C24,
    [TR_FinSupp_iso_to] C26, [TR_FinSupp_iso_coef] C27,
    [TR_FinSupp_iso_from] C28.  Instance/Ab/Free.v: [free_ab_hom_counit]
    C70, [free_ab_hom_unit] C71, [free_ab_hom_to] C72.
    Instance/Ab/FreeMonad.v: [ZM_obj] C75, [ZM_carrier] C76, [ZM_ret] C77,
    [ZM_ret_fun] C78, [ZM_join_counit] C79, [ZM_join_gen] C80,
    [ZM_join_fun] C81, [ZM_join_zero] C82, [Ab_EM_iso_to] C84,
    [Ab_EM_iso_from] C85, [Ab_K_carrier] C86, [Ab_K_map] C87, [Ab_K_alg]
    C88, [Ab_K_alg_fun] C89, [Ab_K_alg_gen] C90, [Ab_K_alg_zero] C91,
    [Ab_K_alg_plus] C92, [Ab_K_alg_neg] C93, [EM_to_AbS_carrier] C94,
    [EM_to_AbS_zero] C95, [EM_to_AbS_plus] C96, [EM_to_AbS_neg] C97,
    [EM_to_AbS_map] C98, [EM_to_AbS_prop] C99, [Ab_rt_carrier] C100,
    [Ab_rt_zero] C101, [Ab_rt_plus] C102, [Ab_rt_neg] C103, [Ab_rt_hom]
    C104, [ZMAlg_rt_carrier] C105, [ZMAlg_rt_alg_fun] C106,
    [ZMAlg_rt_alg_hom] C107, [Ab_EM_iso_to_from_component] C108,
    [Ab_EM_iso_from_to_component] C109, [Ab_EM_counit_component] C110,
    [Ab_EM_unit_component] C111.  Ninety-five readbacks, each named once.
    C4, C5, C6, C7, C8, C18, C19, C20, C21, C25, C34, C63, C69, C73, C74
    and C83 restate no readback: they are the twins of refutations, the
    route-A statements that #472 does not build, and the [≈] and Leibniz
    statements beside them.

    THE REFUSALS, with the parenthetical each stripped copy prints.
      The instrument (NAME-ABSENCE): The reference p472_absent_name was
        not found in the current environment.
      R1, the two adjunctions (controls C2, C3): (cannot unify
        "free_module_adjunction_hom R" and "free_module_adjunction R")
      R2, their counits at a variable combination (controls C4, ≈; C1):
        (cannot unify "(@counit (RMod R) Sets (FreeMod R) (RMod_Forget R)
        (free_module_adjunction R) W) t" and "(@counit (RMod R) Sets
        (FreeMod R) (RMod_Forget R) (free_module_adjunction_hom R) W) t")
      R3 to R5, route A's μ at ⟨t⟩, at a variable and at 0 (controls C5,
        U ε F at [eq_refl]; C6, ≈): (cannot unify "join[_] (fv_gen t)"
        and "t"), (cannot unify "join[_] k" and "fv_flatten R k"),
        (cannot unify "join[_] fv_zero" and "fv_zero")
      R6 to R8, route A's comparison functor (controls C7, C8):
        (cannot unify "t_alg[projT2 (fobj[KA R] M)] t" and "fv_eval
        id{Sets} t"), (cannot unify "t_alg[projT2 (fobj[KA R] M)]
        (fv_plus (fv_gen x) (fv_gen y))" and "cmon_plus M x y"), (cannot
        unify "t_alg[projT2 (fobj[KA R] M)] (fv_gen x)" and "x")
      R9 to R11, T_R u at ⟨x⟩, at a variable and at 0 (controls C18, ≈;
        C32, C33): (cannot unify "fmap[FreeModF R] u (fv_gen x)" and
        "fv_gen (u x)"), (cannot unify "fmap[FreeModF R] u t" and
        "fv_relabel R u t"), (cannot unify "fmap[FreeModF R] u fv_zero"
        and "fv_zero")
      R12, Mac Lane's [(T_R t)f]_y (control C21, ≈): (cannot unify
        "fv_coef R Ydec y (fmap[FreeModF R] t f)" and "fv_eval
        (fv_probe_at R Y Ydec y ∘ t) f")
      R13, FinSupp → T_R X → FinSupp's other leg (control C25): (cannot
        unify "from_finsupp R X Xdec (to_finsupp R X Xdec t)" and "t")
      R14, the direct functor's action against T_R's (controls C32, C34):
        (cannot unify "fmap[FreeModF_direct R] u" and "fmap[FreeModF R]
        u")
      R15, the module's [PropEquiv] through the round trip (control C54):
        (cannot unify "cmon_prop (fobj[EM_to_RModS R ◯ RMod_K R] M)" and
        "cmon_prop M")
      R16, the whole module (controls C55 to C60): (cannot unify
        "fobj[EM_to_RModS R ◯ RMod_K R] M" and "M")
      R17, the structure map through the round trip (controls C62, C63):
        (cannot unify "t_alg[projT2 (fobj[RMod_K R ◯ EM_to_RModS R] x)]"
        and "t_alg[`2 (x)]")
      R18, the whole algebra (controls C61, C64): (cannot unify
        "fobj[RMod_K R ◯ EM_to_RModS R] x" and "x")
      R19: (cannot unify "EM_to_RModS R ◯ RMod_K R" and "Id[RMod R]")
      R20: (cannot unify "RMod_K R ◯ EM_to_RModS R" and "Id[TRAlg R]")
      R21, through the bridge (control C69, the other component; C66, the
        direct isomorphism): (cannot unify "cmon_map (projT1 (iso_from_to
        (Equivalence_to_Cat_Iso (RMod_EM_equivalence R))) M)" and
        "id{Sets}")
      R22, the two adjunctions of Instance/Ab/Free.v (controls C71, C72):
        (cannot unify "free_ab_adjunction_hom" and "free_ab_adjunction")
      R23, their counits (controls C73, ≈; C70): (cannot unify "(@counit
        Ab Sets FreeAb Ab_Forget free_ab_adjunction A) t" and "(@counit
        Ab Sets FreeAb Ab_Forget free_ab_adjunction_hom A) t")
      R24, route A's μ for ℤ[−] (control C74): (cannot unify "join[_]
        (fa_gen t)" and "t")
      R25, route A's comparison functor for Ab: (cannot unify
        "t_alg[projT2 (fobj[ZKA] A)] (fa_plus (fa_gen a) (fa_gen b))"
        and "cmon_plus A a b")
      R26, ℤ[u] at a variable sum (control C83, ≈): (cannot unify
        "fmap[FreeAbF] u t" and "fa_relabel u t")
      R27, the whole group (controls C100 to C104): (cannot unify
        "fobj[EM_to_AbS ◯ Ab_K] G" and "G")
      R28, the evaluation through the round trip (control C106): (cannot
        unify "t_alg[projT2 (fobj[Ab_K ◯ EM_to_AbS] x)]" and
        "t_alg[`2 (x)]")
      R29, the whole algebra (controls C105, C107): (cannot unify
        "fobj[Ab_K ◯ EM_to_AbS] x" and "x")

    NOT PINNED HERE.  (a) [About] readbacks as such: the headers'
    universe censuses.  (b) The flips and copies of CAUSES above, and the
    headers' load-bearing [Defined]s: made in scratch copies.  (c) The
    closure of the targets under [Print Assumptions]: the Makefile's
    print-assumptions gate names the same names as the guard below.
    (d) The absences the headers record: an absence has no command.
    (e) The readings of the books, from the page image and the PDF.

    The guard block names the two hundred and thirty-six names, so that
    a rename breaks this file: the six #472 adds to Instance/Mod/Free.v,
    the six it adds to Instance/Ab/Free.v, and the entries [Print Module]
    gives for each new module (one hundred and eleven of
    Instance/Mod/FreeMonad.v; forty-seven of the satellite, its record
    [FinSupp] with constructor and fields among them; sixty-six of
    Instance/Ab/FreeMonad.v).  Each is written fully qualified and with
    [@], so that no short name in scope can stand in for it. *)

Require Import Category.Lib.
Require Import Category.Lib.Setoid.Propositional.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Universal.Arrow.
Require Import Category.Instance.Sets.
Require Import Category.Instance.CMon.
Require Import Category.Instance.Ab.
Require Import Category.Instance.Rng.
Require Import Category.Instance.Mod.
Require Import Category.Theory.Algebra.Rig.
Require Import Coq.ZArith.ZArith.
Require Import Category.Instance.Mod.Free.
Require Import Category.Theory.Monad.
Require Import Category.Theory.Equivalence.
Require Import Category.Monad.Algebra.
Require Import Category.Monad.Eilenberg.Moore.
Require Import Category.Monad.Eilenberg.Moore.Adjunction.
Require Import Category.Monad.Comparison.
Require Import Category.Instance.Cat.
Require Import Category.Instance.Mod.FreeMonad.
Require Import Category.Instance.CMon.Biproduct.
Require Import Category.Instance.Mod.FreeMonad.FinSupp.
Require Import Category.Instance.Ab.Free.
Require Import Category.Instance.Ab.FreeMonad.

Generalizable All Variables.

(* The monad and the comparison functor of the universal-arrow adjunction,
   route A, which #472 does not build: NOTATIONS for terms over in-tree
   constants only, so that nothing below is stated about a local copy. *)
Local Notation TRA R := (Adjunction_Induced_Monad (free_module_adjunction R)).
Local Notation KA R := (EM_Comparison (free_module_adjunction R)).
Local Notation ZA := (Adjunction_Induced_Monad free_ab_adjunction).
Local Notation ZKA := (EM_Comparison free_ab_adjunction).

(* ------------------------------------------------------------------------ *)
(** ** The instrument *)

(* The instrument *)
Fail Check p472_absent_name.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Mod/Free.v: the adjunction in hom-set form *)

(* C1: the counit of the hom-set form is the fold of the identity. *)
Example p472_c1_hom_counit (R : RingObject) (W : RMod R)
  (t : @FVTerm R (RMod_Forget R W)) :
  cmon_map (rm_hom (@counit _ _ _ _ (free_module_adjunction_hom R) W)) t
    = fv_eval (@id Sets (RMod_Forget R W)) t := eq_refl.

(* C2: its unit is the unit of [free_module_adjunction]... *)
Example p472_c2_hom_unit (R : RingObject) (X : Sets) :
  @Category.Theory.Adjunction.unit _ _ _ _ (free_module_adjunction_hom R) X
    = @Category.Theory.Adjunction.unit _ _ _ _ (free_module_adjunction R) X
  := eq_refl.

(* C3: ...and so is its forward transpose. *)
Example p472_c3_hom_to (R : RingObject) (X : Sets) (W : RMod R)
  (g : FreeMod R X ~{RMod R}~> W) :
  to (@adj _ _ _ _ (free_module_adjunction_hom R) X W) g
    = to (@adj _ _ _ _ (free_module_adjunction R) X W) g := eq_refl.

(* R1 *)
Fail Example p472_r1_adjunctions (R : RingObject) :
  free_module_adjunction_hom R = free_module_adjunction R := eq_refl.

(* C4: the two counits agree up to ≈. *)
Definition p472_c4_counits_equiv (R : RingObject) (W : RMod R)
  (t : @FVTerm R (RMod_Forget R W)) :
  cmon_map (rm_hom (@counit _ _ _ _ (free_module_adjunction R) W)) t
    ≈ fv_eval (@id Sets (RMod_Forget R W)) t :=
  free_module_counit_evaluates R W t.

(* R2 *)
Fail Example p472_r2_counits (R : RingObject) (W : RMod R)
  (t : @FVTerm R (RMod_Forget R W)) :
  cmon_map (rm_hom (@counit _ _ _ _ (free_module_adjunction R) W)) t
    = cmon_map (rm_hom (@counit _ _ _ _ (free_module_adjunction_hom R) W)) t
  := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** The monad of the universal-arrow adjunction (route A) *)

(* C5: its μ is U ε F too, at [eq_refl]... *)
Example p472_c5_routeA_join_counit (R : RingObject) (X : Sets) :
  @join _ _ (TRA R) X
    = fmap[RMod_Forget R]
        (@counit _ _ _ _ (free_module_adjunction R) (FreeMod R X))
  := eq_refl.

(* C6: ...and the flattening up to ≈. *)
Definition p472_c6_routeA_join_equiv (R : RingObject) (X : Sets)
  (k : @FVTerm R (RMod_Forget R (FreeModObject X))) :
  @join _ _ (TRA R) X k ≈ fv_flatten R k :=
  free_module_counit_evaluates R (FreeMod R X) k.

(* R3 *)
Fail Example p472_r3_routeA_join_gen (R : RingObject) (X : Sets)
  (t : @FVTerm R X) :
  @join _ _ (TRA R) X (@fv_gen R (RMod_Forget R (FreeModObject X)) t) = t
  := eq_refl.

(* R4 *)
Fail Example p472_r4_routeA_join_fun (R : RingObject) (X : Sets)
  (k : @FVTerm R (RMod_Forget R (FreeModObject X))) :
  @join _ _ (TRA R) X k = fv_flatten R k := eq_refl.

(* R5 *)
Fail Example p472_r5_routeA_join_zero (R : RingObject) (X : Sets) :
  @join _ _ (TRA R) X fv_zero = fv_zero := eq_refl.

(* C7: the structure map of its comparison functor is U ε at [eq_refl]... *)
Example p472_c7_routeA_K_alg (R : RingObject) (M : RMod R) :
  t_alg[projT2 (fobj[KA R] M)]
    = fmap[RMod_Forget R] (@counit _ _ _ _ (free_module_adjunction R) M)
  := eq_refl.

(* C8: ...and the fold up to ≈. *)
Definition p472_c8_routeA_K_alg_equiv (R : RingObject) (M : RMod R)
  (t : @FVTerm R (RMod_Forget R M)) :
  t_alg[projT2 (fobj[KA R] M)] t ≈ fv_eval (@id Sets (RMod_Forget R M)) t :=
  free_module_counit_evaluates R M t.

(* R6 *)
Fail Example p472_r6_routeA_K_alg_fun (R : RingObject) (M : RMod R)
  (t : @FVTerm R (RMod_Forget R M)) :
  t_alg[projT2 (fobj[KA R] M)] t = fv_eval (@id Sets (RMod_Forget R M)) t
  := eq_refl.

(* R7 *)
Fail Example p472_r7_routeA_K_alg_plus (R : RingObject) (M : RMod R)
  (x y : carrier (RMod_Forget R M)) :
  t_alg[projT2 (fobj[KA R] M)] (fv_plus (fv_gen x) (fv_gen y))
    = cmon_plus M x y := eq_refl.

(* R8 *)
Fail Example p472_r8_routeA_K_alg_gen (R : RingObject) (M : RMod R)
  (x : carrier (RMod_Forget R M)) :
  t_alg[projT2 (fobj[KA R] M)] (fv_gen x) = x := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Mod/FreeMonad.v: the monad T_R *)

(* C9: T_R X is the free module's setoid... *)
Example p472_c9_TR_obj (R : RingObject) (X : Sets) :
  fobj[FreeModF R] X = RMod_Forget R (FreeModObject X) := eq_refl.

(* C10: ...whose carrier is the formal combinations. *)
Example p472_c10_TR_carrier (R : RingObject) (X : Sets) :
  carrier (fobj[FreeModF R] X) = @FVTerm R X := eq_refl.

(* C11: η_X is the insertion, as a setoid map... *)
Example p472_c11_TR_ret (R : RingObject) (X : Sets) :
  @ret _ _ (FreeModMonad R) X = fv_insert X := eq_refl.

(* C12: ...and x ↦ ⟨x⟩. *)
Example p472_c12_TR_ret_fun (R : RingObject) (X : Sets) (x : carrier X) :
  @ret _ _ (FreeModMonad R) X x = fv_gen x := eq_refl.

(* C13: μ = U ε F. *)
Example p472_c13_TR_join_counit (R : RingObject) (X : Sets) :
  @join _ _ (FreeModMonad R) X
    = fmap[RMod_Forget R]
        (@counit _ _ _ _ (free_module_adjunction_hom R) (FreeMod R X))
  := eq_refl.

(* C14: μ⟨t⟩ = t. *)
Example p472_c14_TR_join_gen (R : RingObject) (X : Sets) (t : @FVTerm R X) :
  @join _ _ (FreeModMonad R) X
    (@fv_gen R (RMod_Forget R (FreeModObject X)) t) = t := eq_refl.

(* C15: μ is the fold of the identity at a variable combination. *)
Example p472_c15_TR_join_fun (R : RingObject) (X : Sets)
  (k : @FVTerm R (RMod_Forget R (FreeModObject X))) :
  @join _ _ (FreeModMonad R) X k
    = fv_eval (W := FreeModObject X)
        (@id Sets (RMod_Forget R (FreeModObject X))) k := eq_refl.

(* C16: μ 0 = 0. *)
Example p472_c16_TR_join_zero (R : RingObject) (X : Sets) :
  @join _ _ (FreeModMonad R) X fv_zero = fv_zero := eq_refl.

(* C17: μ (r·⟨t⟩ + s·⟨t'⟩) = r·t + s·t'. *)
Example p472_c17_TR_join_lc (R : RingObject) (X : Sets)
  (r s : carrier (rig_setoid (ring_rig R))) (t t' : @FVTerm R X) :
  @join _ _ (FreeModMonad R) X
    (fv_plus (fv_smul r (@fv_gen R (RMod_Forget R (FreeModObject X)) t))
             (fv_smul s (@fv_gen R (RMod_Forget R (FreeModObject X)) t')))
    = fv_plus (fv_smul r t) (fv_smul s t') := eq_refl.

(* C18: T_R u is the relabelling up to ≈. *)
Definition p472_c18_TR_map_equiv (R : RingObject) {X Y : Sets}
  (u : X ~{Sets}~> Y) (t : @FVTerm R X) :
  fmap[FreeModF R] u t ≈ fv_relabel R u t := TR_map_equiv R u t.

(* R9 *)
Fail Example p472_r9_TR_map_gen (R : RingObject) {X Y : Sets}
  (u : X ~{Sets}~> Y) (x : carrier X) :
  fmap[FreeModF R] u (fv_gen x) = fv_gen (u x) := eq_refl.

(* R10 *)
Fail Example p472_r10_TR_map_fun (R : RingObject) {X Y : Sets}
  (u : X ~{Sets}~> Y) (t : @FVTerm R X) :
  fmap[FreeModF R] u t = fv_relabel R u t := eq_refl.

(* R11 *)
Fail Example p472_r11_TR_map_zero (R : RingObject) {X Y : Sets}
  (u : X ~{Sets}~> Y) :
  fmap[FreeModF R] u fv_zero = fv_zero := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Part (a): the list form and the coefficients *)

(* C19: the relabelling of a combination relabels each pair (Leibniz). *)
Definition p472_c19_relabel_lc (R : RingObject) {X Y : Sets}
  (u : X ~{Sets}~> Y) (l : list (fv_pair R X)) :
  fv_relabel R u (fv_lc l) = fv_lc (fv_lc_map R u l) :=
  fv_relabel_lc R u l.

(* C20: the coefficient of x in μ k is the extension of f ↦ f_x at k, a
   Leibniz equation. *)
Definition p472_c20_coef_join (R : RingObject) {X : Sets}
  (Xdec : ∀ x y : carrier X, (x ≈ y) + ((x ≈ y) → False))
  (x : carrier X) (k : @FVTerm R (RMod_Forget R (FreeModObject X))) :
  fv_coef R Xdec x (@join _ _ (FreeModMonad R) X k)
    = fv_eval (W := Ring_RMod R) (fv_coef R Xdec x) k :=
  fv_coef_join R Xdec x k.

(* C21: the coefficient of T_R t, up to ≈. *)
Definition p472_c21_coef_map (R : RingObject) {X Y : Sets}
  (Ydec : ∀ x y : carrier Y, (x ≈ y) + ((x ≈ y) → False))
  (t : X ~{Sets}~> Y) (f : @FVTerm R X) (y : carrier Y) :
  fv_coef R Ydec y (fmap[FreeModF R] t f)
    ≈ fv_eval (fv_probe_at R Y Ydec y ∘ t) f :=
  fv_coef_map R Ydec t f y.

(* R12 *)
Fail Example p472_r12_coef_map (R : RingObject) {X Y : Sets}
  (Ydec : ∀ x y : carrier Y, (x ≈ y) + ((x ≈ y) → False))
  (t : X ~{Sets}~> Y) (f : @FVTerm R X) (y : carrier Y) :
  fv_coef R Ydec y (fmap[FreeModF R] t f)
    = fv_eval (fv_probe_at R Y Ydec y ∘ t) f := eq_refl.

(* C22: the coefficients of 2·e_true + e_false over ℤ... *)
Example p472_c22_coef_Z_true :
  fv_coef Int_Ring two_gens_dec true
    (@fv_plus Int_Ring TwoGens
       (@fv_smul Int_Ring TwoGens 2%Z (@fv_gen Int_Ring TwoGens true))
       (@fv_gen Int_Ring TwoGens false)) = 2%Z := eq_refl.

(* C23: ... *)
Example p472_c23_coef_Z_false :
  fv_coef Int_Ring two_gens_dec false
    (@fv_plus Int_Ring TwoGens
       (@fv_smul Int_Ring TwoGens 2%Z (@fv_gen Int_Ring TwoGens true))
       (@fv_gen Int_Ring TwoGens false)) = 1%Z := eq_refl.

(* C24: ...and of μ (3·⟨e_true + e_false⟩ + ⟨e_true⟩) at true. *)
Example p472_c24_coef_Z_join :
  fv_coef Int_Ring two_gens_dec true
    (@join _ _ (FreeModMonad Int_Ring) TwoGens
       (@fv_plus Int_Ring (RMod_Forget Int_Ring (FreeModObject TwoGens))
          (@fv_smul Int_Ring (RMod_Forget Int_Ring (FreeModObject TwoGens))
             3%Z
             (@fv_gen Int_Ring (RMod_Forget Int_Ring (FreeModObject TwoGens))
                (@fv_plus Int_Ring TwoGens (@fv_gen Int_Ring TwoGens true)
                   (@fv_gen Int_Ring TwoGens false))))
          (@fv_gen Int_Ring (RMod_Forget Int_Ring (FreeModObject TwoGens))
             (@fv_gen Int_Ring TwoGens true)))) = 4%Z := eq_refl.

(* C25: from ∘ to is the identity on combinations up to ≈ ... *)
Definition p472_c25_finsupp_from_to (R : RingObject) (X : Sets)
  (Xdec : ∀ x y : carrier X, (x ≈ y) + ((x ≈ y) → False))
  (t : @FVTerm R X) :
  fv_eq (from_finsupp R X Xdec (to_finsupp R X Xdec t)) t :=
  finsupp_from_to R X Xdec t.

(* C26: T_R X → FinSupp X sends a combination to its coefficients... *)
Example p472_c26_finsupp_iso_to (R : RingObject) (X : Sets)
  (Xdec : ∀ x y : carrier X, (x ≈ y) + ((x ≈ y) → False))
  (t : @FVTerm R X) :
  to (TR_FinSupp_iso R X Xdec) t = to_finsupp R X Xdec t := eq_refl.

(* C27: ...whose value at y is the coefficient of y... *)
Example p472_c27_finsupp_iso_coef (R : RingObject) (X : Sets)
  (Xdec : ∀ x y : carrier X, (x ≈ y) + ((x ≈ y) → False))
  (t : @FVTerm R X) (y : carrier X) :
  fs_fun R X (to (TR_FinSupp_iso R X Xdec) t) y = fv_coef R Xdec y t
  := eq_refl.

(* C28: ...and back, Σ f(y)·e_y over the support, duplicates removed. *)
Example p472_c28_finsupp_iso_from (R : RingObject) (X : Sets)
  (Xdec : ∀ x y : carrier X, (x ≈ y) + ((x ≈ y) → False))
  (f : FinSupp R X) :
  from (TR_FinSupp_iso R X Xdec) f
    = fv_lsum R X (fs_fun R X f) (fs_dedup X Xdec (fs_supp R X f))
  := eq_refl.

(* R13 *)
Fail Example p472_r13_finsupp_from_to (R : RingObject) (X : Sets)
  (Xdec : ∀ x y : carrier X, (x ≈ y) + ((x ≈ y) → False))
  (t : @FVTerm R X) :
  from_finsupp R X Xdec (to_finsupp R X Xdec t) = t := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Part (b): the direct verification *)

(* C29: its unit is T_R's... *)
Example p472_c29_direct_ret (R : RingObject) (X : Sets) :
  @ret _ _ (FreeModMonad_direct R) X = @ret _ _ (FreeModMonad R) X
  := eq_refl.

(* C30: ...and so is its multiplication... *)
Example p472_c30_direct_join (R : RingObject) (X : Sets) :
  @join _ _ (FreeModMonad_direct R) X = @join _ _ (FreeModMonad R) X
  := eq_refl.

(* C31: ...and its endofunctor's objects. *)
Example p472_c31_direct_obj (R : RingObject) (X : Sets) :
  fobj[FreeModF_direct R] X = fobj[FreeModF R] X := eq_refl.

(* C32: its action on arrows IS the relabelling... *)
Example p472_c32_direct_map (R : RingObject) {X Y : Sets}
  (u : X ~{Sets}~> Y) (t : @FVTerm R X) :
  fmap[FreeModF_direct R] u t = fv_relabel R u t := eq_refl.

(* C33: ...which sends ⟨x⟩ to ⟨u x⟩. *)
Example p472_c33_direct_map_gen (R : RingObject) {X Y : Sets}
  (u : X ~{Sets}~> Y) (x : carrier X) :
  fmap[FreeModF_direct R] u (fv_gen x) = fv_gen (u x) := eq_refl.

(* C34: the two endofunctors are naturally isomorphic. *)
Definition p472_c34_direct_iso (R : RingObject) :
  FreeModF_direct R ≈ FreeModF R := FreeModF_direct_iso R.

(* C35: ...with identity components. *)
Example p472_c35_direct_iso_component (R : RingObject) (X : Sets) :
  (to (`1 (FreeModF_direct_iso R) X), from (`1 (FreeModF_direct_iso R) X))
    = (@id Sets (fobj[FreeModF R] X), @id Sets (fobj[FreeModF R] X))
  := eq_refl.

(* R14 *)
Fail Example p472_r14_direct_map_is_TR (R : RingObject) {X Y : Sets}
  (u : X ~{Sets}~> Y) :
  fmap[FreeModF_direct R] u = fmap[FreeModF R] u := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Part (c): the comparison K and R-Mod ≅ Set^{T_R} *)

(* C36: the leg [to] of [RMod_EM_iso] is K... *)
Example p472_c36_iso_to (R : RingObject) :
  to (RMod_EM_iso R) = EM_Comparison (free_module_adjunction_hom R)
  := eq_refl.

(* C37: ...and the leg [from] is [EM_to_RModS]. *)
Example p472_c37_iso_from (R : RingObject) :
  from (RMod_EM_iso R) = EM_to_RModS R := eq_refl.

(* C38: K M has carrier M... *)
Example p472_c38_K_carrier (R : RingObject) (M : RMod R) :
  `1 (fobj[RMod_K R] M) = RMod_Forget R M := eq_refl.

(* C39: ...K f is f... *)
Example p472_c39_K_map (R : RingObject) {M N : RMod R}
  (f : M ~{RMod R}~> N) :
  t_alg_hom[fmap[RMod_K R] f] = fmap[RMod_Forget R] f := eq_refl.

(* C40: ...its structure map is U ε_M... *)
Example p472_c40_K_alg (R : RingObject) (M : RMod R) :
  t_alg[`2 (fobj[RMod_K R] M)]
    = fmap[RMod_Forget R] (@counit _ _ _ _ (free_module_adjunction_hom R) M)
  := eq_refl.

(* C41: ...whose value is the fold of the identity... *)
Example p472_c41_K_alg_fun (R : RingObject) (M : RMod R)
  (t : @FVTerm R (RMod_Forget R M)) :
  t_alg[`2 (fobj[RMod_K R] M)] t = fv_eval (@id Sets (RMod_Forget R M)) t
  := eq_refl.

(* C42: ...so ⟨x⟩ ↦ x... *)
Example p472_c42_K_alg_gen (R : RingObject) (M : RMod R)
  (x : carrier (RMod_Forget R M)) :
  t_alg[`2 (fobj[RMod_K R] M)] (fv_gen x) = x := eq_refl.

(* C43: ...0 ↦ 0... *)
Example p472_c43_K_alg_zero (R : RingObject) (M : RMod R) :
  t_alg[`2 (fobj[RMod_K R] M)] fv_zero = cmon_zero M := eq_refl.

(* C44: ...⟨x⟩ + ⟨y⟩ ↦ x + y... *)
Example p472_c44_K_alg_plus (R : RingObject) (M : RMod R)
  (x y : carrier (RMod_Forget R M)) :
  t_alg[`2 (fobj[RMod_K R] M)] (fv_plus (fv_gen x) (fv_gen y))
    = cmon_plus M x y := eq_refl.

(* C45: ...−⟨x⟩ ↦ −x... *)
Example p472_c45_K_alg_neg (R : RingObject) (M : RMod R)
  (x : carrier (RMod_Forget R M)) :
  t_alg[`2 (fobj[RMod_K R] M)] (fv_neg (fv_gen x)) = ab_neg M x := eq_refl.

(* C46: ...r·⟨x⟩ ↦ r·x... *)
Example p472_c46_K_alg_smul (R : RingObject) (M : RMod R)
  (r : carrier (rig_setoid (ring_rig R))) (x : carrier (RMod_Forget R M)) :
  t_alg[`2 (fobj[RMod_K R] M)] (fv_smul r (fv_gen x)) = rm_smul M r x
  := eq_refl.

(* C47: ...and Σ rᵢ·⟨xᵢ⟩ to the fold of the identity there. *)
Example p472_c47_K_alg_lc (R : RingObject) (M : RMod R)
  (l : list (fv_pair R (RMod_Forget R M))) :
  t_alg[`2 (fobj[RMod_K R] M)] (fv_lc l)
    = fv_eval (@id Sets (RMod_Forget R M)) (fv_lc l) := eq_refl.

(* C48: the module of an algebra has its carrier... *)
Example p472_c48_EM_carrier (R : RingObject) (x : TRAlg R) :
  cmon_setoid (fobj[EM_to_RModS R] x) = `1 x := eq_refl.

(* C49: ...0 = h⟨⟩... *)
Example p472_c49_EM_zero (R : RingObject) (x : TRAlg R) :
  cmon_zero (fobj[EM_to_RModS R] x) = t_alg[`2 x] fv_zero := eq_refl.

(* C50: ...a + b = h(⟨a⟩ + ⟨b⟩)... *)
Example p472_c50_EM_plus (R : RingObject) (x : TRAlg R) (a b : `1 x) :
  cmon_plus (fobj[EM_to_RModS R] x) a b
    = t_alg[`2 x] (fv_plus (fv_gen a) (fv_gen b)) := eq_refl.

(* C51: ...−a = h(−⟨a⟩)... *)
Example p472_c51_EM_neg (R : RingObject) (x : TRAlg R) (a : `1 x) :
  ab_neg (fobj[EM_to_RModS R] x) a = t_alg[`2 x] (fv_neg (fv_gen a))
  := eq_refl.

(* C52: ...r·a = h(r·⟨a⟩)... *)
Example p472_c52_EM_smul (R : RingObject) (x : TRAlg R)
  (r : carrier (rig_setoid (ring_rig R))) (a : `1 x) :
  rm_smul (fobj[EM_to_RModS R] x) r a
    = t_alg[`2 x] (fv_smul r (fv_gen a)) := eq_refl.

(* C53: ...and an algebra map is its own linear map. *)
Example p472_c53_EM_map (R : RingObject) {x y : TRAlg R}
  (f : x ~{TRAlg R}~> y) :
  cmon_map (rm_hom (fmap[EM_to_RModS R] f)) = t_alg_hom[f] := eq_refl.

(* C54: its [Prop] equality compares one-generator combinations. *)
Example p472_c54_EM_prop (R : RingObject) (x : TRAlg R) (a b : `1 x) :
  @pequiv _ _ (cmon_prop (fobj[EM_to_RModS R] x)) a b
    = @fv_eq R (`1 x) (fv_gen a) (fv_gen b) := eq_refl.

(* C55: the module round trip keeps the carrier... *)
Example p472_c55_RMod_rt_carrier (R : RingObject) (M : RMod R) :
  cmon_setoid (fobj[EM_to_RModS R ◯ RMod_K R] M) = cmon_setoid M
  := eq_refl.

(* C56: ...the zero... *)
Example p472_c56_RMod_rt_zero (R : RingObject) (M : RMod R) :
  cmon_zero (fobj[EM_to_RModS R ◯ RMod_K R] M) = cmon_zero M := eq_refl.

(* C57: ...the sum... *)
Example p472_c57_RMod_rt_plus (R : RingObject) (M : RMod R) :
  cmon_plus (fobj[EM_to_RModS R ◯ RMod_K R] M) = cmon_plus M := eq_refl.

(* C58: ...the negation... *)
Example p472_c58_RMod_rt_neg (R : RingObject) (M : RMod R) :
  ab_neg (fobj[EM_to_RModS R ◯ RMod_K R] M) = ab_neg M := eq_refl.

(* C59: ...the action... *)
Example p472_c59_RMod_rt_smul (R : RingObject) (M : RMod R) :
  rm_smul (fobj[EM_to_RModS R ◯ RMod_K R] M) = rm_smul M := eq_refl.

(* C60: ...and the maps. *)
Example p472_c60_RMod_rt_hom (R : RingObject) {M N : RMod R}
  (f : M ~{RMod R}~> N) :
  cmon_map (rm_hom (fmap[EM_to_RModS R ◯ RMod_K R] f))
    = cmon_map (rm_hom f) := eq_refl.

(* R15 *)
Fail Example p472_r15_RMod_rt_prop (R : RingObject) (M : RMod R) :
  cmon_prop (fobj[EM_to_RModS R ◯ RMod_K R] M) = cmon_prop M := eq_refl.

(* R16 *)
Fail Example p472_r16_RMod_rt_obj (R : RingObject) (M : RMod R) :
  fobj[EM_to_RModS R ◯ RMod_K R] M = M := eq_refl.

(* C61: the algebra round trip keeps the carrier... *)
Example p472_c61_TRAlg_rt_carrier (R : RingObject) (x : TRAlg R) :
  `1 (fobj[RMod_K R ◯ EM_to_RModS R] x) = `1 x := eq_refl.

(* C62: ...its structure map is the fold in the derived module... *)
Example p472_c62_TRAlg_rt_alg_fun (R : RingObject) (x : TRAlg R)
  (t : @FVTerm R (`1 x)) :
  t_alg[`2 (fobj[RMod_K R ◯ EM_to_RModS R] x)] t
    = fv_eval (W := tr_alg_rmod R (`2 x))
        (@id Sets (RMod_Forget R (tr_alg_rmod R (`2 x)))) t := eq_refl.

(* C63: ...which is h up to ≈... *)
Definition p472_c63_TRAlg_rt_alg_equiv (R : RingObject) (x : TRAlg R)
  (t : @FVTerm R (`1 x)) :
  tr_alg_eval R (`2 x) t ≈ t_alg[`2 x] t :=
  symmetry (tr_alg_fold R (`2 x) t).

(* C64: ...and the maps come back. *)
Example p472_c64_TRAlg_rt_alg_hom (R : RingObject) {x y : TRAlg R}
  (f : x ~{TRAlg R}~> y) :
  t_alg_hom[fmap[RMod_K R ◯ EM_to_RModS R] f] = t_alg_hom[f] := eq_refl.

(* R17 *)
Fail Example p472_r17_TRAlg_rt_alg (R : RingObject) (x : TRAlg R) :
  t_alg[`2 (fobj[RMod_K R ◯ EM_to_RModS R] x)] = t_alg[`2 x] := eq_refl.

(* R18 *)
Fail Example p472_r18_TRAlg_rt_obj (R : RingObject) (x : TRAlg R) :
  fobj[RMod_K R ◯ EM_to_RModS R] x = x := eq_refl.

(* R19 *)
Fail Example p472_r19_K_functor (R : RingObject) :
  EM_to_RModS R ◯ RMod_K R = Id[RMod R] := eq_refl.

(* R20 *)
Fail Example p472_r20_K_functor_b (R : RingObject) :
  RMod_K R ◯ EM_to_RModS R = Id[TRAlg R] := eq_refl.

(* C65: every component of [iso_to_from] is the identity... *)
Example p472_c65_to_from_component (R : RingObject) (x : TRAlg R) :
  (t_alg_hom[to (`1 (iso_to_from (RMod_EM_iso R)) x)],
   t_alg_hom[from (`1 (iso_to_from (RMod_EM_iso R)) x)])
    = (@id Sets (`1 x), @id Sets (`1 x)) := eq_refl.

(* C66: ...and so is every component of [iso_from_to]. *)
Example p472_c66_from_to_component (R : RingObject) (M : RMod R) :
  (cmon_map (rm_hom (to (`1 (iso_from_to (RMod_EM_iso R)) M))),
   cmon_map (rm_hom (from (`1 (iso_from_to (RMod_EM_iso R)) M))))
    = (@id Sets (RMod_Forget R M), @id Sets (RMod_Forget R M)) := eq_refl.

(* C67: the counit of the equivalence has identity components... *)
Example p472_c67_equiv_counit_component (R : RingObject) (x : TRAlg R) :
  (t_alg_hom[to (`1 (@equivalence_counit _ _ _ (RMod_EM_equivalence R)) x)],
   t_alg_hom[from (`1 (@equivalence_counit _ _ _ (RMod_EM_equivalence R))
                    x)])
    = (@id Sets (`1 x), @id Sets (`1 x)) := eq_refl.

(* C68: ...and so does its unit. *)
Example p472_c68_equiv_unit_component (R : RingObject) (M : RMod R) :
  (cmon_map (rm_hom (to (`1 (@equivalence_unit _ _ _ (RMod_EM_equivalence R))
                           M))),
   cmon_map (rm_hom (from (`1 (@equivalence_unit _ _ _
                                 (RMod_EM_equivalence R)) M))))
    = (@id Sets (RMod_Forget R M), @id Sets (RMod_Forget R M)) := eq_refl.

(* C69: through Theory/Equivalence.v's bridge, the component of
   [iso_to_from] is still the identity... *)
Example p472_c69_bridge_to_from (R : RingObject) (x : TRAlg R) :
  t_alg_hom[to (`1 (iso_to_from
                      (Equivalence_to_Cat_Iso (RMod_EM_equivalence R))) x)]
    = @id Sets (`1 x) := eq_refl.

(* R21 *)
Fail Example p472_r21_bridge_from_to (R : RingObject) (M : RMod R) :
  cmon_map (rm_hom (to (`1 (iso_from_to
                              (Equivalence_to_Cat_Iso (RMod_EM_equivalence R)))
                          M)))
    = @id Sets (RMod_Forget R M) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Ab/Free.v: the adjunction in hom-set form *)

(* C70: the counit of the hom-set form is the fold of the identity... *)
Example p472_c70_ab_hom_counit (A : Ab) (t : FATerm (Ab_Forget A)) :
  cmon_map (@counit _ _ _ _ free_ab_adjunction_hom A) t
    = fa_eval (@id Sets (Ab_Forget A)) t := eq_refl.

(* C71: ...its unit is [free_ab_adjunction]'s... *)
Example p472_c71_ab_hom_unit (X : Sets) :
  @Category.Theory.Adjunction.unit _ _ _ _ free_ab_adjunction_hom X
    = @Category.Theory.Adjunction.unit _ _ _ _ free_ab_adjunction X
  := eq_refl.

(* C72: ...and so is its forward transpose. *)
Example p472_c72_ab_hom_to (X : Sets) (A : Ab) (g : FreeAb X ~{Ab}~> A) :
  to (@adj _ _ _ _ free_ab_adjunction_hom X A) g
    = to (@adj _ _ _ _ free_ab_adjunction X A) g := eq_refl.

(* R22 *)
Fail Example p472_r22_ab_adjunctions :
  free_ab_adjunction_hom = free_ab_adjunction := eq_refl.

(* C73: the two counits agree up to ≈. *)
Definition p472_c73_ab_counits_equiv (A : Ab) (t : FATerm (Ab_Forget A)) :
  cmon_map (@counit _ _ _ _ free_ab_adjunction A) t
    ≈ fa_eval (@id Sets (Ab_Forget A)) t := free_ab_counit_evaluates A t.

(* R23 *)
Fail Example p472_r23_ab_counits (A : Ab) (t : FATerm (Ab_Forget A)) :
  cmon_map (@counit _ _ _ _ free_ab_adjunction A) t
    = cmon_map (@counit _ _ _ _ free_ab_adjunction_hom A) t := eq_refl.

(* C74: route A's μ for ℤ[−] is U ε F at [eq_refl]... *)
Example p472_c74_ab_routeA_join_counit (X : Sets) :
  @join _ _ ZA X
    = fmap[Ab_Forget] (@counit _ _ _ _ free_ab_adjunction (FreeAb X))
  := eq_refl.

(* R24 *)
Fail Example p472_r24_ab_routeA_join_gen (X : Sets) (t : FATerm X) :
  @join _ _ ZA X (@fa_gen (Ab_Forget (FreeAbObject X)) t) = t := eq_refl.

(* R25 *)
Fail Example p472_r25_ab_routeA_K_plus (A : Ab) (a b : carrier (Ab_Forget A)) :
  t_alg[`2 (fobj[ZKA] A)] (fa_plus (fa_gen a) (fa_gen b)) = cmon_plus A a b
  := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Ab/FreeMonad.v: ℤ[−] and Ab ≅ Set^{ℤ[−]} *)

(* C75: ℤ[X] is the free group's setoid... *)
Example p472_c75_ZM_obj (X : Sets) :
  fobj[FreeAbF] X = Ab_Forget (FreeAbObject X) := eq_refl.

(* C76: ...whose carrier is the formal sums. *)
Example p472_c76_ZM_carrier (X : Sets) : carrier (fobj[FreeAbF] X) = FATerm X
  := eq_refl.

(* C77: η_X is the insertion... *)
Example p472_c77_ZM_ret (X : Sets) : @ret _ _ FreeAbMonad X = free_ab_insert X
  := eq_refl.

(* C78: ...x ↦ ⟨x⟩... *)
Example p472_c78_ZM_ret_fun (X : Sets) (x : carrier X) :
  @ret _ _ FreeAbMonad X x = fa_gen x := eq_refl.

(* C79: ...μ = U ε F... *)
Example p472_c79_ZM_join_counit (X : Sets) :
  @join _ _ FreeAbMonad X
    = fmap[Ab_Forget] (@counit _ _ _ _ free_ab_adjunction_hom (FreeAb X))
  := eq_refl.

(* C80: ...μ⟨t⟩ = t... *)
Example p472_c80_ZM_join_gen (X : Sets) (t : FATerm X) :
  @join _ _ FreeAbMonad X (@fa_gen (Ab_Forget (FreeAbObject X)) t) = t
  := eq_refl.

(* C81: ...μ is the fold of the identity... *)
Example p472_c81_ZM_join_fun (X : Sets)
  (k : FATerm (Ab_Forget (FreeAbObject X))) :
  @join _ _ FreeAbMonad X k
    = fa_eval (A := FreeAbObject X) (@id Sets (Ab_Forget (FreeAbObject X))) k
  := eq_refl.

(* C82: ...and μ 0 = 0. *)
Example p472_c82_ZM_join_zero (X : Sets) :
  @join _ _ FreeAbMonad X fa_zero = fa_zero := eq_refl.

(* C83: ℤ[u] is the relabelling up to ≈. *)
Definition p472_c83_ZM_map_equiv {X Y : Sets} (u : X ~{Sets}~> Y)
  (t : FATerm X) : fmap[FreeAbF] u t ≈ fa_relabel u t := ZM_map_equiv u t.

(* R26 *)
Fail Example p472_r26_ZM_map_fun {X Y : Sets} (u : X ~{Sets}~> Y)
  (t : FATerm X) : fmap[FreeAbF] u t = fa_relabel u t := eq_refl.

(* C84: the leg [to] of [Ab_EM_iso] is K... *)
Example p472_c84_ab_iso_to : to Ab_EM_iso = EM_Comparison free_ab_adjunction_hom
  := eq_refl.

(* C85: ...and the leg [from] is [EM_to_AbS]. *)
Example p472_c85_ab_iso_from : from Ab_EM_iso = EM_to_AbS := eq_refl.

(* C86: K G has carrier G... *)
Example p472_c86_ab_K_carrier (G : Ab) : `1 (fobj[Ab_K] G) = Ab_Forget G
  := eq_refl.

(* C87: ...K f is f... *)
Example p472_c87_ab_K_map {G H : Ab} (f : G ~{Ab}~> H) :
  t_alg_hom[fmap[Ab_K] f] = fmap[Ab_Forget] f := eq_refl.

(* C88: ...its structure map is U ε_G... *)
Example p472_c88_ab_K_alg (G : Ab) :
  t_alg[`2 (fobj[Ab_K] G)]
    = fmap[Ab_Forget] (@counit _ _ _ _ free_ab_adjunction_hom G) := eq_refl.

(* C89: ...the evaluation of a formal sum to its actual sum... *)
Example p472_c89_ab_K_alg_fun (G : Ab) (t : FATerm (Ab_Forget G)) :
  t_alg[`2 (fobj[Ab_K] G)] t = fa_eval (@id Sets (Ab_Forget G)) t
  := eq_refl.

(* C90: ...so ⟨x⟩ ↦ x... *)
Example p472_c90_ab_K_alg_gen (G : Ab) (x : carrier (Ab_Forget G)) :
  t_alg[`2 (fobj[Ab_K] G)] (fa_gen x) = x := eq_refl.

(* C91: ...0 ↦ 0... *)
Example p472_c91_ab_K_alg_zero (G : Ab) :
  t_alg[`2 (fobj[Ab_K] G)] fa_zero = cmon_zero G := eq_refl.

(* C92: ...⟨x⟩ + ⟨y⟩ ↦ x + y... *)
Example p472_c92_ab_K_alg_plus (G : Ab) (x y : carrier (Ab_Forget G)) :
  t_alg[`2 (fobj[Ab_K] G)] (fa_plus (fa_gen x) (fa_gen y))
    = cmon_plus G x y := eq_refl.

(* C93: ...and −⟨x⟩ ↦ −x. *)
Example p472_c93_ab_K_alg_neg (G : Ab) (x : carrier (Ab_Forget G)) :
  t_alg[`2 (fobj[Ab_K] G)] (fa_neg (fa_gen x)) = ab_neg G x := eq_refl.

(* C94: the group of an algebra has its carrier... *)
Example p472_c94_ab_EM_carrier (x : ZMAlg) :
  cmon_setoid (fobj[EM_to_AbS] x) = `1 x := eq_refl.

(* C95: ...0 = ev⟨⟩... *)
Example p472_c95_ab_EM_zero (x : ZMAlg) :
  cmon_zero (fobj[EM_to_AbS] x) = t_alg[`2 x] fa_zero := eq_refl.

(* C96: ...a + b = ev(⟨a⟩ + ⟨b⟩)... *)
Example p472_c96_ab_EM_plus (x : ZMAlg) (a b : `1 x) :
  cmon_plus (fobj[EM_to_AbS] x) a b
    = t_alg[`2 x] (fa_plus (fa_gen a) (fa_gen b)) := eq_refl.

(* C97: ...−a = ev(−⟨a⟩)... *)
Example p472_c97_ab_EM_neg (x : ZMAlg) (a : `1 x) :
  ab_neg (fobj[EM_to_AbS] x) a = t_alg[`2 x] (fa_neg (fa_gen a)) := eq_refl.

(* C98: ...and an algebra map is its own homomorphism. *)
Example p472_c98_ab_EM_map {x y : ZMAlg} (f : x ~{ZMAlg}~> y) :
  cmon_map (fmap[EM_to_AbS] f) = t_alg_hom[f] := eq_refl.

(* C99: its [Prop] equality compares one-generator sums. *)
Example p472_c99_ab_EM_prop (x : ZMAlg) (a b : `1 x) :
  @pequiv _ _ (cmon_prop (fobj[EM_to_AbS] x)) a b
    = @fa_eq (`1 x) (fa_gen a) (fa_gen b) := eq_refl.

(* C100: the group round trip keeps the carrier... *)
Example p472_c100_Ab_rt_carrier (G : Ab) :
  cmon_setoid (fobj[EM_to_AbS ◯ Ab_K] G) = cmon_setoid G := eq_refl.

(* C101: ...the zero... *)
Example p472_c101_Ab_rt_zero (G : Ab) :
  cmon_zero (fobj[EM_to_AbS ◯ Ab_K] G) = cmon_zero G := eq_refl.

(* C102: ...the sum... *)
Example p472_c102_Ab_rt_plus (G : Ab) :
  cmon_plus (fobj[EM_to_AbS ◯ Ab_K] G) = cmon_plus G := eq_refl.

(* C103: ...the negation... *)
Example p472_c103_Ab_rt_neg (G : Ab) :
  ab_neg (fobj[EM_to_AbS ◯ Ab_K] G) = ab_neg G := eq_refl.

(* C104: ...and the maps. *)
Example p472_c104_Ab_rt_hom {G H : Ab} (f : G ~{Ab}~> H) :
  cmon_map (fmap[EM_to_AbS ◯ Ab_K] f) = cmon_map f := eq_refl.

(* R27 *)
Fail Example p472_r27_Ab_rt_obj (G : Ab) :
  fobj[EM_to_AbS ◯ Ab_K] G = G := eq_refl.

(* C105: the algebra round trip keeps the carrier... *)
Example p472_c105_ZMAlg_rt_carrier (x : ZMAlg) :
  `1 (fobj[Ab_K ◯ EM_to_AbS] x) = `1 x := eq_refl.

(* C106: ...its evaluation is the fold in the derived group... *)
Example p472_c106_ZMAlg_rt_alg_fun (x : ZMAlg) (t : FATerm (`1 x)) :
  t_alg[`2 (fobj[Ab_K ◯ EM_to_AbS] x)] t
    = fa_eval (A := zm_alg_ab (`2 x))
        (@id Sets (Ab_Forget (zm_alg_ab (`2 x)))) t := eq_refl.

(* C107: ...and the maps come back. *)
Example p472_c107_ZMAlg_rt_alg_hom {x y : ZMAlg} (f : x ~{ZMAlg}~> y) :
  t_alg_hom[fmap[Ab_K ◯ EM_to_AbS] f] = t_alg_hom[f] := eq_refl.

(* R28 *)
Fail Example p472_r28_ZMAlg_rt_alg (x : ZMAlg) :
  t_alg[`2 (fobj[Ab_K ◯ EM_to_AbS] x)] = t_alg[`2 x] := eq_refl.

(* R29 *)
Fail Example p472_r29_ZMAlg_rt_obj (x : ZMAlg) :
  fobj[Ab_K ◯ EM_to_AbS] x = x := eq_refl.

(* C108: every component of [iso_to_from] is the identity... *)
Example p472_c108_ab_to_from_component (x : ZMAlg) :
  (t_alg_hom[to (`1 (iso_to_from Ab_EM_iso) x)],
   t_alg_hom[from (`1 (iso_to_from Ab_EM_iso) x)])
    = (@id Sets (`1 x), @id Sets (`1 x)) := eq_refl.

(* C109: ...and so is every component of [iso_from_to]. *)
Example p472_c109_ab_from_to_component (G : Ab) :
  (cmon_map (to (`1 (iso_from_to Ab_EM_iso) G)),
   cmon_map (from (`1 (iso_from_to Ab_EM_iso) G)))
    = (@id Sets (Ab_Forget G), @id Sets (Ab_Forget G)) := eq_refl.

(* C110: the counit of the equivalence has identity components... *)
Example p472_c110_ab_equiv_counit_component (x : ZMAlg) :
  (t_alg_hom[to (`1 (@equivalence_counit _ _ _ Ab_EM_equivalence) x)],
   t_alg_hom[from (`1 (@equivalence_counit _ _ _ Ab_EM_equivalence) x)])
    = (@id Sets (`1 x), @id Sets (`1 x)) := eq_refl.

(* C111: ...and so does its unit. *)
Example p472_c111_ab_equiv_unit_component (G : Ab) :
  (cmon_map (to (`1 (@equivalence_unit _ _ _ Ab_EM_equivalence) G)),
   cmon_map (from (`1 (@equivalence_unit _ _ _ Ab_EM_equivalence) G)))
    = (@id Sets (Ab_Forget G), @id Sets (Ab_Forget G)) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** The guard: every constant of the targets *)

Check @Category.Instance.Mod.Free.fv_eval_pointwise.
Check @Category.Instance.Mod.Free.free_module_hom_iso.
Check @Category.Instance.Mod.Free.free_module_adjunction_hom.
Check @Category.Instance.Mod.Free.free_module_hom_counit.
Check @Category.Instance.Mod.Free.free_module_hom_unit.
Check @Category.Instance.Mod.Free.free_module_hom_to.
Check @Category.Instance.Ab.Free.fa_eval_pointwise.
Check @Category.Instance.Ab.Free.free_ab_hom_iso.
Check @Category.Instance.Ab.Free.free_ab_adjunction_hom.
Check @Category.Instance.Ab.Free.free_ab_hom_counit.
Check @Category.Instance.Ab.Free.free_ab_hom_unit.
Check @Category.Instance.Ab.Free.free_ab_hom_to.
Check @Category.Instance.Mod.FreeMonad.FreeModF.
Check @Category.Instance.Mod.FreeMonad.FreeModMonad.
Check @Category.Instance.Mod.FreeMonad.fv_relabel.
Check @Category.Instance.Mod.FreeMonad.fv_flatten.
Check @Category.Instance.Mod.FreeMonad.TR_obj.
Check @Category.Instance.Mod.FreeMonad.TR_carrier.
Check @Category.Instance.Mod.FreeMonad.TR_ret.
Check @Category.Instance.Mod.FreeMonad.TR_ret_fun.
Check @Category.Instance.Mod.FreeMonad.TR_join_counit.
Check @Category.Instance.Mod.FreeMonad.TR_join_gen.
Check @Category.Instance.Mod.FreeMonad.TR_join_fun.
Check @Category.Instance.Mod.FreeMonad.TR_join_zero.
Check @Category.Instance.Mod.FreeMonad.TR_join_lc.
Check @Category.Instance.Mod.FreeMonad.TR_map_equiv.
Check @Category.Instance.Mod.FreeMonad.fv_eval_relabel.
Check @Category.Instance.Mod.FreeMonad.fv_eval_flatten.
Check @Category.Instance.Mod.FreeMonad.fv_lc_map.
Check @Category.Instance.Mod.FreeMonad.fv_lc_flat.
Check @Category.Instance.Mod.FreeMonad.fv_lc_inner.
Check @Category.Instance.Mod.FreeMonad.fv_relabel_lc.
Check @Category.Instance.Mod.FreeMonad.TR_map_lc.
Check @Category.Instance.Mod.FreeMonad.TR_ret_lc.
Check @Category.Instance.Mod.FreeMonad.TR_join_lc_flat.
Check @Category.Instance.Mod.FreeMonad.fv_eq_of_eq.
Check @Category.Instance.Mod.FreeMonad.fv_relabel_id.
Check @Category.Instance.Mod.FreeMonad.fv_relabel_comp.
Check @Category.Instance.Mod.FreeMonad.fv_relabel_respects.
Check @Category.Instance.Mod.FreeMonad.fv_flatten_assoc.
Check @Category.Instance.Mod.FreeMonad.fv_flatten_relabel_insert.
Check @Category.Instance.Mod.FreeMonad.fv_flatten_natural.
Check @Category.Instance.Mod.FreeMonad.FreeModF_direct.
Check @Category.Instance.Mod.FreeMonad.FreeModMonad_direct.
Check @Category.Instance.Mod.FreeMonad.TR_direct_ret.
Check @Category.Instance.Mod.FreeMonad.TR_direct_join.
Check @Category.Instance.Mod.FreeMonad.TR_direct_obj.
Check @Category.Instance.Mod.FreeMonad.TR_direct_map.
Check @Category.Instance.Mod.FreeMonad.TR_direct_map_gen.
Check @Category.Instance.Mod.FreeMonad.FreeModF_direct_iso.
Check @Category.Instance.Mod.FreeMonad.TR_direct_iso_component.
Check @Category.Instance.Mod.FreeMonad.TRAlg.
Check @Category.Instance.Mod.FreeMonad.RMod_K.
Check @Category.Instance.Mod.FreeMonad.RMod_K_Forget.
Check @Category.Instance.Mod.FreeMonad.RMod_K_Free.
Check @Category.Instance.Mod.FreeMonad.tr_alg_zero.
Check @Category.Instance.Mod.FreeMonad.tr_alg_plus.
Check @Category.Instance.Mod.FreeMonad.tr_alg_neg.
Check @Category.Instance.Mod.FreeMonad.tr_alg_smul.
Check @Category.Instance.Mod.FreeMonad.tr_alg_eval.
Check @Category.Instance.Mod.FreeMonad.tr_alg_unit.
Check @Category.Instance.Mod.FreeMonad.tr_alg_step.
Check @Category.Instance.Mod.FreeMonad.tr_alg_plus_respects.
Check @Category.Instance.Mod.FreeMonad.tr_alg_neg_respects.
Check @Category.Instance.Mod.FreeMonad.tr_alg_smul_respects.
Check @Category.Instance.Mod.FreeMonad.tr_alg_fold.
Check @Category.Instance.Mod.FreeMonad.tr_alg_eval_respects.
Check @Category.Instance.Mod.FreeMonad.tr_alg_prop.
Check @Category.Instance.Mod.FreeMonad.tr_alg_rmod.
Check @Category.Instance.Mod.FreeMonad.tr_alg_hom_step.
Check @Category.Instance.Mod.FreeMonad.tr_alg_hom_rmod.
Check @Category.Instance.Mod.FreeMonad.EM_to_RModS.
Check @Category.Instance.Mod.FreeMonad.tr_fold_is_alg_eval.
Check @Category.Instance.Mod.FreeMonad.RMod_EM_counit_iso.
Check @Category.Instance.Mod.FreeMonad.RMod_EM_unit_iso.
Check @Category.Instance.Mod.FreeMonad.RMod_EM_equivalence.
Check @Category.Instance.Mod.FreeMonad.RMod_Forget_Monadic.
Check @Category.Instance.Mod.FreeMonad.RMod_EM_iso.
Check @Category.Instance.Mod.FreeMonad.RMod_K_carrier.
Check @Category.Instance.Mod.FreeMonad.RMod_K_map.
Check @Category.Instance.Mod.FreeMonad.RMod_K_alg.
Check @Category.Instance.Mod.FreeMonad.RMod_K_alg_fun.
Check @Category.Instance.Mod.FreeMonad.RMod_K_alg_gen.
Check @Category.Instance.Mod.FreeMonad.RMod_K_alg_zero.
Check @Category.Instance.Mod.FreeMonad.RMod_K_alg_plus.
Check @Category.Instance.Mod.FreeMonad.RMod_K_alg_neg.
Check @Category.Instance.Mod.FreeMonad.RMod_K_alg_smul.
Check @Category.Instance.Mod.FreeMonad.RMod_K_alg_lc.
Check @Category.Instance.Mod.FreeMonad.RMod_EM_iso_to.
Check @Category.Instance.Mod.FreeMonad.RMod_EM_iso_from.
Check @Category.Instance.Mod.FreeMonad.EM_to_RModS_prop.
Check @Category.Instance.Mod.FreeMonad.EM_to_RModS_carrier.
Check @Category.Instance.Mod.FreeMonad.EM_to_RModS_zero.
Check @Category.Instance.Mod.FreeMonad.EM_to_RModS_plus.
Check @Category.Instance.Mod.FreeMonad.EM_to_RModS_neg.
Check @Category.Instance.Mod.FreeMonad.EM_to_RModS_smul.
Check @Category.Instance.Mod.FreeMonad.EM_to_RModS_map.
Check @Category.Instance.Mod.FreeMonad.RMod_rt_carrier.
Check @Category.Instance.Mod.FreeMonad.RMod_rt_zero.
Check @Category.Instance.Mod.FreeMonad.RMod_rt_plus.
Check @Category.Instance.Mod.FreeMonad.RMod_rt_neg.
Check @Category.Instance.Mod.FreeMonad.RMod_rt_smul.
Check @Category.Instance.Mod.FreeMonad.RMod_rt_hom.
Check @Category.Instance.Mod.FreeMonad.TRAlg_rt_carrier.
Check @Category.Instance.Mod.FreeMonad.TRAlg_rt_alg_fun.
Check @Category.Instance.Mod.FreeMonad.TRAlg_rt_alg_hom.
Check @Category.Instance.Mod.FreeMonad.RMod_EM_iso_to_from_component.
Check @Category.Instance.Mod.FreeMonad.RMod_EM_iso_from_to_component.
Check @Category.Instance.Mod.FreeMonad.RMod_EM_counit_component.
Check @Category.Instance.Mod.FreeMonad.RMod_EM_unit_component.
Check @Category.Instance.Mod.FreeMonad.fv_coef.
Check @Category.Instance.Mod.FreeMonad.fv_coef_ret_same.
Check @Category.Instance.Mod.FreeMonad.fv_coef_ret_other.
Check @Category.Instance.Mod.FreeMonad.fv_coef_map.
Check @Category.Instance.Mod.FreeMonad.fv_fibre_sum.
Check @Category.Instance.Mod.FreeMonad.fv_eval_fibre_lc.
Check @Category.Instance.Mod.FreeMonad.fv_coef_map_lc.
Check @Category.Instance.Mod.FreeMonad.fv_coef_join.
Check @Category.Instance.Mod.FreeMonad.fv_lc_weighted.
Check @Category.Instance.Mod.FreeMonad.fv_coef_join_lc.
Check @Category.Instance.Mod.FreeMonad.fv_coef_respects_point.
Check @Category.Instance.Mod.FreeMonad.fv_avoids.
Check @Category.Instance.Mod.FreeMonad.fv_coef_support.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_mem.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_nodup.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_mem_dec.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_mem_respects.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_mem_app_l.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_mem_app_r.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_dedup.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_dedup_mem_back.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_dedup_mem.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_dedup_nodup.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_gens.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_coef_gens_support.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_lsum.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_lsum_ext.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_lsum_zero.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_lsum_plus.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_lsum_neg.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_lsum_smul.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_lsum_ext_in.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_lsum_indicator.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_coef_lsum_out.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_coef_lsum_in.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_coef_lc.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_lc_unique.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_collect.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fv_coef_injective.
Check @Category.Instance.Mod.FreeMonad.FinSupp.FinSupp.
Check @Category.Instance.Mod.FreeMonad.FinSupp.Build_FinSupp.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_fun.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_resp.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_supp.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_vanish.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_eq.
Check @Category.Instance.Mod.FreeMonad.FinSupp.fs_eq_Equivalence.
Check @Category.Instance.Mod.FreeMonad.FinSupp.FinSupp_Setoid.
Check @Category.Instance.Mod.FreeMonad.FinSupp.FinSuppObj.
Check @Category.Instance.Mod.FreeMonad.FinSupp.to_finsupp.
Check @Category.Instance.Mod.FreeMonad.FinSupp.from_finsupp.
Check @Category.Instance.Mod.FreeMonad.FinSupp.finsupp_to_from.
Check @Category.Instance.Mod.FreeMonad.FinSupp.finsupp_from_to.
Check @Category.Instance.Mod.FreeMonad.FinSupp.TR_FinSupp_iso.
Check @Category.Instance.Mod.FreeMonad.FinSupp.TR_FinSupp_iso_to.
Check @Category.Instance.Mod.FreeMonad.FinSupp.TR_FinSupp_iso_from.
Check @Category.Instance.Mod.FreeMonad.FinSupp.TR_FinSupp_iso_coef.
Check @Category.Instance.Mod.FreeMonad.FinSupp.TR_coef_Z_true.
Check @Category.Instance.Mod.FreeMonad.FinSupp.TR_coef_Z_false.
Check @Category.Instance.Mod.FreeMonad.FinSupp.TR_coef_Z_join.
Check @Category.Instance.Ab.FreeMonad.FreeAbF.
Check @Category.Instance.Ab.FreeMonad.FreeAbMonad.
Check @Category.Instance.Ab.FreeMonad.fa_relabel.
Check @Category.Instance.Ab.FreeMonad.fa_flatten.
Check @Category.Instance.Ab.FreeMonad.ZM_obj.
Check @Category.Instance.Ab.FreeMonad.ZM_carrier.
Check @Category.Instance.Ab.FreeMonad.ZM_ret.
Check @Category.Instance.Ab.FreeMonad.ZM_ret_fun.
Check @Category.Instance.Ab.FreeMonad.ZM_join_counit.
Check @Category.Instance.Ab.FreeMonad.ZM_join_gen.
Check @Category.Instance.Ab.FreeMonad.ZM_join_fun.
Check @Category.Instance.Ab.FreeMonad.ZM_join_zero.
Check @Category.Instance.Ab.FreeMonad.ZM_map_equiv.
Check @Category.Instance.Ab.FreeMonad.ZMAlg.
Check @Category.Instance.Ab.FreeMonad.Ab_K.
Check @Category.Instance.Ab.FreeMonad.Ab_K_Forget.
Check @Category.Instance.Ab.FreeMonad.Ab_K_Free.
Check @Category.Instance.Ab.FreeMonad.zm_alg_zero.
Check @Category.Instance.Ab.FreeMonad.zm_alg_plus.
Check @Category.Instance.Ab.FreeMonad.zm_alg_neg.
Check @Category.Instance.Ab.FreeMonad.zm_alg_eval.
Check @Category.Instance.Ab.FreeMonad.zm_alg_unit.
Check @Category.Instance.Ab.FreeMonad.zm_alg_step.
Check @Category.Instance.Ab.FreeMonad.zm_alg_plus_respects.
Check @Category.Instance.Ab.FreeMonad.zm_alg_neg_respects.
Check @Category.Instance.Ab.FreeMonad.zm_alg_fold.
Check @Category.Instance.Ab.FreeMonad.zm_alg_eval_respects.
Check @Category.Instance.Ab.FreeMonad.zm_alg_prop.
Check @Category.Instance.Ab.FreeMonad.zm_alg_ab.
Check @Category.Instance.Ab.FreeMonad.zm_alg_hom_step.
Check @Category.Instance.Ab.FreeMonad.zm_alg_hom_ab.
Check @Category.Instance.Ab.FreeMonad.EM_to_AbS.
Check @Category.Instance.Ab.FreeMonad.zm_fold_is_alg_eval.
Check @Category.Instance.Ab.FreeMonad.Ab_EM_counit_iso.
Check @Category.Instance.Ab.FreeMonad.Ab_EM_unit_iso.
Check @Category.Instance.Ab.FreeMonad.Ab_EM_equivalence.
Check @Category.Instance.Ab.FreeMonad.Ab_Forget_Monadic.
Check @Category.Instance.Ab.FreeMonad.Ab_EM_iso.
Check @Category.Instance.Ab.FreeMonad.Ab_K_carrier.
Check @Category.Instance.Ab.FreeMonad.Ab_K_map.
Check @Category.Instance.Ab.FreeMonad.Ab_K_alg.
Check @Category.Instance.Ab.FreeMonad.Ab_K_alg_fun.
Check @Category.Instance.Ab.FreeMonad.Ab_K_alg_gen.
Check @Category.Instance.Ab.FreeMonad.Ab_K_alg_zero.
Check @Category.Instance.Ab.FreeMonad.Ab_K_alg_plus.
Check @Category.Instance.Ab.FreeMonad.Ab_K_alg_neg.
Check @Category.Instance.Ab.FreeMonad.Ab_EM_iso_to.
Check @Category.Instance.Ab.FreeMonad.Ab_EM_iso_from.
Check @Category.Instance.Ab.FreeMonad.EM_to_AbS_prop.
Check @Category.Instance.Ab.FreeMonad.EM_to_AbS_carrier.
Check @Category.Instance.Ab.FreeMonad.EM_to_AbS_zero.
Check @Category.Instance.Ab.FreeMonad.EM_to_AbS_plus.
Check @Category.Instance.Ab.FreeMonad.EM_to_AbS_neg.
Check @Category.Instance.Ab.FreeMonad.EM_to_AbS_map.
Check @Category.Instance.Ab.FreeMonad.Ab_rt_carrier.
Check @Category.Instance.Ab.FreeMonad.Ab_rt_zero.
Check @Category.Instance.Ab.FreeMonad.Ab_rt_plus.
Check @Category.Instance.Ab.FreeMonad.Ab_rt_neg.
Check @Category.Instance.Ab.FreeMonad.Ab_rt_hom.
Check @Category.Instance.Ab.FreeMonad.ZMAlg_rt_carrier.
Check @Category.Instance.Ab.FreeMonad.ZMAlg_rt_alg_fun.
Check @Category.Instance.Ab.FreeMonad.ZMAlg_rt_alg_hom.
Check @Category.Instance.Ab.FreeMonad.Ab_EM_iso_to_from_component.
Check @Category.Instance.Ab.FreeMonad.Ab_EM_iso_from_to_component.
Check @Category.Instance.Ab.FreeMonad.Ab_EM_counit_component.
Check @Category.Instance.Ab.FreeMonad.Ab_EM_unit_component.
