(** * Probe for the tensor-algebra monad T on Ab (issue #474)

    Pins the measured boundaries of what #474 adds for Mac Lane, §VI.4,
    Exercise 4, book p. 146 (PDF p. 155), catalog item maclane:VI.4:ex4,
    read from the page image ("The adjunction ⟨F, G, φ⟩ : Ab ⇀ Rng with G
    the functor "forget the multiplication in a ring" defines a monad T
    in Ab.  (a) Give a direct description of this monad, like that in the
    text for W, with Xⁿ replaced by the n-fold tensor power and coproduct
    ∐ by the (infinite) direct sum of abelian groups.  (b) Give the
    corresponding description of T-algebras and show that the comparison
    functor from rings to T-algebras is an isomorphism"), with the item
    the issue appends, Riehl's Example 5.5.7(ii) (riehl:5.5:example7,
    printed p. 205, PDF p. 225: "the forgetful functor U : Ring → Ab is
    monadic.  The induced monad on Ab is the free monoid monad TA :=
    ⨁_{n≥0} A^{⊗n}").  The targets are the hom-set form of the free
    ring adjunction that #474 adds to Instance/Rng/Free.v,
    Instance/Ab/TensorPower.v (⨁ₙ A^{⊗n}, as words modulo multilinearity
    and as the coproduct of the tensor powers), Instance/Rng/FreeMonad.v
    (T, the ring of an algebra, Rng ≅ Ab^T, monadicity),
    Instance/Rng/FreeMonad/Words.v (T A ≅ ⨁ₙ A^{⊗n} and η, μ, T f read
    through it, and the monad ⨁ₙ (−)^{⊗n} with T ≅ it as monads) and
    Instance/Rng/FreeMonad/System.v (Mac Lane's systems ⟨A, ν₀, ν₁,
    …⟩).  Their headers cite the refutations and controls here:
    Instance/Rng/Free.v R1 to R3, C1 to C4; Instance/Rng/FreeMonad.v R4
    to R19, C5 to C54; Instance/Ab/TensorPower.v R20, R21, C55 to C61,
    C103, C104; Instance/Rng/FreeMonad/Words.v R22 to R26, C62 to C78,
    C105, C106, C108 to C116; Instance/Rng/FreeMonad/System.v R27 to
    R32, C79 to C102, C107.  Each of the ninety-five [Example]s of the
    targets, all proved by [eq_refl], has a control that restates it
    independently of the constant that states it (RESTATEMENTS, below).

    THE IMPORT LIST, generated by a script over the [Require] lines.
    Target by target in dependency order: Instance/Rng/Free.v's twenty
    [Require] lines in its own order, and that target; the seven lines
    Instance/Ab/TensorPower.v adds, and that target; the seven lines
    Instance/Rng/FreeMonad.v adds, and that target; the three lines
    Instance/Rng/FreeMonad/Words.v adds, and that target; and
    Instance/Rng/FreeMonad/System.v, which adds none.  Forty-two lines,
    forty naming [Category] modules and two the standard library.  Under
    them [Print Libraries] in a scratch file loads one hundred and twelve
    [Category] modules, exactly the set a [Require] of the five targets
    alone loads (compared by script).  A shorter import list is what
    makes a probe pass for no reason.

    DISCIPLINE.  Every negative other than the instrument is an
    [Example], never a [Check], so that an open evar cannot satisfy it.
    Each of the thirty-three refutation lines (the instrument and R1 to
    R32) was stripped of its refutation keyword in a copy of this WHOLE
    file, one at a time, compiled, and its error read; each copy stops
    inside the stripped command (thirty-three of thirty-three, by the
    File line of its error, compared by script with the command's
    extent).  Each of the one hundred and sixteen controls, wrapped in the
    refutation keyword in a copy of this WHOLE file, stops the build at
    that command with the message Rocq prints for a refutation whose
    command succeeds (one hundred and sixteen of one hundred and sixteen,
    by the same script).  The six controls that refute a Leibniz form
    (C103 to C107 and C112) are single commands whose proof is a term, so
    that the wrap checks the proof and not only the statement.
    Quotations are Rocq 9.1.1's under this file's import list, with the
    error's environment block left out; Rocq prints the "cannot unify"
    parenthetical with the short names in scope.

    KINDS.  Thirty-three refutations, counted as the lines that open with
    the refutation keyword: NAME-ABSENCE, the instrument (one); and
    CONVERSION, [eq_refl] refused with a "cannot unify" parenthetical,
    every statement being well typed (R1 to R32: thirty-two).  CAUSES.
    Measured: every refutation still stops inside its command, and every
    control is still accepted, in a copy of the five targets and this
    file under a renamed logical root with all ninety-three [Qed]s of
    #474's code turned [Defined]; so none is the opacity of #474's own
    proofs.  Measured in three copies of this file's 112-file closure,
    rebuilt after each change, with Theory/Universal/Arrow.v's
    [ump_universal_arrows] alone, Instance/Rng/Free.v's
    [free_rng_ab_universal] alone, and both turned [Defined]: with
    either alone all thirty-two are still refused; with both, twelve
    hold, R2, R3, R5 to R13 and R26, the ones that read the counit of
    the universal-arrow adjunction or the free functor's action on
    arrows (issue #1353 tracks the shared lemma; Free.v's header,
    CORRECTION (#474)), and twenty are still refused.  Read from the
    terms, those twenty: the two adjunctions and η as records differ
    in their proof fields (R1, R4); objects come back as rebuilt records
    (R14, R16, R29, R30), and R17, R18 and R31 compare composites whose
    object maps already differ; data are stuck on a variable algebra
    (R15), length (R20, R21), term (R22, R24, R25) or word (R27); from ∘
    to rebrackets (R23, false at Leibniz =, C105); ν₁ of the system
    round trip is the identity while a system's own ν₁ is abstract
    (R28); R19 is the opacity of Theory/Functor.v's
    [Functor_Setoid_obligation_1], from which Theory/Equivalence.v's
    [Equivalence_to_Cat_Iso] builds [iso_from_to] as the symmetry of the
    unit (opaque and transparent respectively, by [About]), measured for
    #470's semigroups and #471's monoids by their audits; and R32 is the
    opacity of three constants of Theory/Functor.v,
    [fun_equiv_comp_assoc], [fun_equiv_id_left] and
    [Functor_Setoid_obligation_1], through which Theory/Isomorphism.v's
    transparent [iso_compose_obligation_2] builds the components of the
    composite [Rng_TSys_iso] by setoid rewrites in [Cat] (read from that
    obligation's term; the four transparencies by [About]).

    LABELS.  The labels are not constants: each refutation and each
    control carries its label in a comment on the line above it, the
    instrument's reading "The instrument".  The constants are
    [p474_cN_…] and [p474_rN_…] for label CN or RN.

    RESTATEMENTS.  Instance/Rng/Free.v: [free_rng_ab_hom_counit] C1,
    [free_rng_ab_hom_unit] C2, [free_rng_ab_hom_to] C3.
    Instance/Rng/FreeMonad.v: [T_obj] C5, [T_carrier] C6, [T_equiv] C7,
    [T_ret] C8, [T_ret_fun] C9, [T_join_counit] C10, [T_join_fun] C11,
    [T_join_gen] C12, [T_join_mul] C13, [T_join_plus] C14, [T_join_one]
    C15, [Rng_EM_iso_to] C21, [Rng_EM_iso_from] C22, [Rng_K_carrier] C23,
    [Rng_K_alg] C24, [Rng_K_alg_fun] C25, [Rng_K_alg_one] C26,
    [Rng_K_alg_gen] C27, [Rng_K_alg_mul] C28, [Rng_K_alg_plus] C29,
    [Rng_K_map] C30, [EM_to_Rng_one] C31, [EM_to_Rng_mul] C32,
    [EM_to_Rng_add] C33, [EM_to_Rng_map] C34, [Rng_rt_setoid] C35,
    [Rng_rt_zero] C36, [Rng_rt_add] C37, [Rng_rt_one] C38, [Rng_rt_mul]
    C39, [Rng_rt_neg] C40, [Rng_rt_hom] C41, [EM_Rng_rt_carrier] C42,
    [EM_Rng_rt_alg_fun] C43, [EM_Rng_rt_alg_hom] C44,
    [Rng_EM_iso_to_from_component] C46, [Rng_EM_iso_from_to_component]
    C47, [Rng_EM_counit_component] C48, [Rng_EM_unit_component] C49,
    [Rng_K_Forget_obj] C51, [Rng_K_Forget_map] C52,
    [EM_to_Rng_Forget_obj] C53, [EM_to_Rng_Forget_map] C54.
    Instance/Ab/TensorPower.v: [tpower_ab_zero] C55, [tpower_ab_succ]
    C56, [tw_iota_gen] C57, [tw_desc_word] C58, [tw_ext_word] C59.
    Instance/Rng/FreeMonad/Words.v: [TWRing_ab] C62, [tw_mul_words] C63,
    [T_TW_ret] C64, [T_TW_to_fun] C65, [T_TW_from_word] C66,
    [T_TW_from_to_gen] C67, [T_TW_from_to_pair] C68, [tw_join_two] C71,
    [T_TW_join_gen] C72, [T_TW_join_pair] C73, [TWF_obj] C76,
    [TWF_map_word] C77, [T_TW_natural_component] C78, [TWMonad_ret] C108,
    [TWMonad_join] C109, [TWMonad_join_word] C110, [TWMonad_join_ret]
    C111, [T_TW_monad_hom_component] C113, [TW_T_monad_hom_component]
    C114, [T_TW_monad_iso_to] C115, [T_TW_monad_iso_from] C116.
    Instance/Rng/FreeMonad/System.v: [alg_system_nu] C79,
    [alg_system_nil] C80, [alg_system_pair] C81, [TSys_EM_iso_to] C82,
    [TSys_EM_iso_from] C83, [TSys_to_EM_alg] C84, [TSys_to_EM_one] C85,
    [TSys_to_EM_pair] C86, [EM_to_TSys_nu] C87, [EM_to_TSys_pair] C88,
    [TSys_rt_ab] C89, [TSys_rt_nil] C90, [TSys_rt_letter] C91,
    [TSys_rt_pair] C92, [TSys_rt_hom] C93, [EM_TSys_rt_carrier] C95,
    [EM_TSys_rt_alg_hom] C96, [TSys_EM_iso_to_from_component] C97,
    [TSys_EM_iso_from_to_component] C98, [Rng_system_nu] C99,
    [Rng_system_nil] C100, [Rng_system_letter] C101, [Rng_system_pair]
    C102.  Ninety-five readbacks, each named once.  C4, C16 to C20, C45,
    C50, C60, C61, C69, C70, C74, C75 and C94 restate no readback: they
    are the twins of refutations, route A's monad and comparison functor
    (C17, C18) among them; C103 to C107 and C112 prove six ≈-stated
    statements false at Leibniz = at an explicit instance, the last the
    associative law of the direct monad [TWMonad].

    THE REFUSALS, with the parenthetical each stripped copy prints.
      The instrument (NAME-ABSENCE): The reference p474_absent_name was
        not found in the current environment.
      R1, the two adjunctions (controls C2, C3, their unit and forward
        transpose): (cannot unify "free_rng_ab_adjunction_hom" and
        "free_rng_ab_adjunction")
      R2, their inverse transposes: (cannot unify
        "(adj[free_rng_ab_adjunction_hom])⁻¹ h" and
        "(adj[free_rng_ab_adjunction])⁻¹ h")
      R3, their counits at a variable expression (control C4, ≈; C1,
        the hom-set counit is the evaluation): (cannot unify "(@counit
        Rng Ab FreeRngAb Rng_Forget_Ab free_rng_ab_adjunction R) t" and
        "(@counit Rng Ab FreeRngAb Rng_Forget_Ab
        free_rng_ab_adjunction_hom R) t")
      R4, η as the whole record (control C8, on carriers): (cannot unify
        "ret[_]" and "free_rng_ab_insert A")
      R5, T f at a generator: (cannot unify "fmap[TF] f (fr_gen a)" and
        "fr_gen (f a)")
      R6, T f at a variable (control C16, ≈): (cannot unify "fmap[TF] f
        t" and "fr_eval (free_rng_ab_insert B ∘ f) t")
      R7 to R10, route A's μ at a generator, at a variable, at a product
        and at 1 (control C19, ≈; C12, C11, C13, C15 on route B): (cannot
        unify "join[_] (fr_gen t)" and "t"), (cannot unify "join[_] t"
        and "fr_eval id{Ab} t"), (cannot unify "join[_] (fr_mul (fr_gen
        s) (fr_gen t))" and "fr_mul s t"), (cannot unify "join[_]
        fr_one" and "fr_one")
      R11 to R13, route A's K R at 1, at a product and at a generator
        (control C20, ≈; C26, C28, C27 on route B): (cannot unify
        "t_alg[projT2 (fobj[p474_c18_KA] R)] fr_one" and "rig_one R"),
        (cannot unify "t_alg[projT2 (fobj[p474_c18_KA] R)] (fr_mul
        (fr_gen a) (fr_gen b))" and "rig_mul R a b"), (cannot unify
        "t_alg[projT2 (fobj[p474_c18_KA] R)] (fr_gen a)" and "a")
      R14, the whole ring through the round trip (controls C35 to C41):
        (cannot unify "fobj[EM_to_Rng ◯ Rng_K] R" and "R")
      R15, the structure map through the round trip at a variable
        (controls C43, C45): (cannot unify "t_alg[projT2 (fobj[Rng_K ◯
        EM_to_Rng] x)] t" and "t_alg[`2 (x)] t")
      R16, the whole algebra (controls C42, C44): (cannot unify
        "fobj[Rng_K ◯ EM_to_Rng] x" and "x")
      R17: (cannot unify "EM_to_Rng ◯ Rng_K" and "Id[Rng]")
      R18: (cannot unify "Rng_K ◯ EM_to_Rng" and "Id[RngAlg]")
      R19, through the bridge (control C50, the other component; C47,
        the direct isomorphism): (cannot unify "rig_map (projT1
        (iso_from_to (Equivalence_to_Cat_Iso Rng_EM_equivalence)) R)" and
        "setoid_morphism_id")
      R20, the copairing after ιₙ (controls C60, ≈; C104): (cannot unify
        "tw_desc A c iota (tw_iota n x)" and "iota n x")
      R21, a word against its pure tensor (controls C61, ≈; C103):
        (cannot unify "tw_word w" and "tw_iota (length w) (tw_pure w)")
      R22, from ∘ to at a variable (controls C67, C68, C69): (cannot
        unify "(T_TW_iso A)⁻¹ (T_TW_iso A t)" and "t")
      R23, at (⟨a⟩·⟨b⟩)·⟨c⟩ (control C105): (cannot unify "(T_TW_iso A)⁻¹
        (T_TW_iso A (fr_mul (fr_mul (fr_gen a) (fr_gen b)) (fr_gen c)))"
        and "fr_mul (fr_mul (fr_gen a) (fr_gen b)) (fr_gen c)")
      R24, to ∘ from at a variable (control C70, Leibniz): (cannot unify
        "T_TW_iso A ((T_TW_iso A)⁻¹ t)" and "t")
      R25, μ read through the isomorphism at a variable (controls C72 to
        C74, C106): (cannot unify "T_TW_iso A (join[_] t)" and "tw_join
        (tw_map (T_TW_iso A) (T_TW_iso (fobj[TF] A) t))")
      R26, T f read through the isomorphism at a generator (control
        C75, ≈): (cannot unify "T_TW_iso B (fmap[TF] f (fr_gen a))" and
        "tw_map f (T_TW_iso A (fr_gen a))")
      R27, ν through the system round trip at a variable word (controls
        C90, C92, C94): (cannot unify "tnu (tsys_str (fobj[EM_to_TSys ◯
        TSys_to_EM] S)) w" and "tnu (tsys_str S) w")
      R28, ν₁ of the round trip against the system's own (control C91):
        (cannot unify "tnu (tsys_str (fobj[EM_to_TSys ◯ TSys_to_EM] S))
        (a :: nil)" and "tnu (tsys_str S) (a :: nil)")
      R29, the whole system (controls C89 to C93): (cannot unify
        "fobj[EM_to_TSys ◯ TSys_to_EM] S" and "S")
      R30, the whole algebra through the systems (controls C95, C96):
        (cannot unify "fobj[TSys_to_EM ◯ EM_to_TSys] x" and "x")
      R31: (cannot unify "EM_to_TSys ◯ TSys_to_EM" and "Id[TSys]")
      R32, a component of the composite [Rng_TSys_iso] at a point
        (controls C47 and C98, the identity components of the two
        isomorphisms it composes): (cannot unify "projT1 (iso_from_to
        Rng_TSys_iso) R a" and "a")

    NOT PINNED HERE.  (a) [About] readbacks as such: the headers'
    universe censuses.  (b) The flips and copies described above, made
    in scratch copies.  (c) The closure of the targets under
    [Print Assumptions]: the Makefile's print-assumptions gate names the
    same two hundred and ninety-six names as the guard below.  (d) The
    absences the headers record: an absence has no command.  (e) The
    readings of the books, from the page image and the PDF.

    The guard block names the two hundred and ninety-six names, so that
    a rename breaks this file: the six #474 adds to Instance/Rng/Free.v,
    sixty of Instance/Ab/TensorPower.v, seventy-four of
    Instance/Rng/FreeMonad.v, eighty-five of Instance/Rng/FreeMonad/
    Words.v and seventy-one of Instance/Rng/FreeMonad/System.v.  They are
    exactly the entries [Print Module] gives for each new module, the
    inductives [TWTerm] and [tw_eq] and the records [TSystem] and
    [TSysObj] with their constructors, fields and schemes among them.
    Each is written fully qualified and with [@], so that no short name
    in scope can stand in for it. *)

Require Import Category.Lib.
Require Import Category.Lib.Setoid.Propositional.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Universal.Arrow.
Require Import Category.Adjunction.Compose.
Require Import Category.Theory.Algebra.Rig.
Require Import Category.Theory.Algebra.Monoid.Hom.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Sets.Cartesian.
Require Import Category.Instance.CMon.
Require Import Category.Instance.Ab.
Require Import Category.Instance.Rng.
Require Import Category.Instance.Ab.Free.
Require Import Category.Instance.Mon.Free.
Require Import Category.Instance.Rng.MonoidRing.
Require Import Category.Instance.Rng.Algebras.Associative.
Require Import Coq.ZArith.ZArith.
Require Import Category.Instance.Rng.Free.
Require Import Category.Structure.Monoidal.
Require Import Category.Structure.Monoidal.Hypergraph.Spider.
Require Import Category.Structure.Limit.Coproduct.
Require Import Category.Instance.CMon.Biproduct.
Require Import Category.Instance.Ab.Tensor.
Require Import Category.Instance.Ab.Monoidal.
Require Import Coq.Lists.List.
Require Import Category.Instance.Ab.TensorPower.
Require Import Category.Theory.Monad.
Require Import Category.Theory.Equivalence.
Require Import Category.Monad.Algebra.
Require Import Category.Monad.Eilenberg.Moore.
Require Import Category.Monad.Eilenberg.Moore.Adjunction.
Require Import Category.Monad.Comparison.
Require Import Category.Instance.Cat.
Require Import Category.Instance.Rng.FreeMonad.
Require Import Category.Theory.Natural.Transformation.
Require Import Category.Monad.Morphism.
Require Import Category.Instance.Rng.Polynomial.
Require Import Category.Instance.Rng.FreeMonad.Words.
Require Import Category.Instance.Rng.FreeMonad.System.

Generalizable All Variables.

(* ------------------------------------------------------------------------ *)
(** ** The instrument *)

(* The instrument *)
Fail Check p474_absent_name.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Rng/Free.v: the adjunction in hom-set form *)

(* C1: the counit of the hom-set form is the evaluation of the identity. *)
Example p474_c1_hom_counit (R : Rng) (t : FRTerm (Rng_Forget_Ab R)) :
  rig_map (@counit _ _ _ _ free_rng_ab_adjunction_hom R) t
    = fr_eval (@id Ab (Rng_Forget_Ab R)) t := eq_refl.

(* C2: its unit is the unit of [free_rng_ab_adjunction]. *)
Example p474_c2_hom_unit (A : Ab) :
  @Category.Theory.Adjunction.unit _ _ _ _ free_rng_ab_adjunction_hom A
    = @Category.Theory.Adjunction.unit _ _ _ _ free_rng_ab_adjunction A
  := eq_refl.

(* C3: so is its forward transpose. *)
Example p474_c3_hom_to (A : Ab) (R : Rng) (g : FreeRngAb A ~{Rng}~> R) :
  to (@adj _ _ _ _ free_rng_ab_adjunction_hom A R) g
    = to (@adj _ _ _ _ free_rng_ab_adjunction A R) g := eq_refl.

(* R1 *)
Fail Example p474_r1_adjunctions :
  free_rng_ab_adjunction_hom = free_rng_ab_adjunction := eq_refl.

(* R2 *)
Fail Example p474_r2_from (A : Ab) (R : Rng)
  (h : A ~{Ab}~> Rng_Forget_Ab R) :
  from (@adj _ _ _ _ free_rng_ab_adjunction_hom A R) h
    = from (@adj _ _ _ _ free_rng_ab_adjunction A R) h := eq_refl.

(* C4: the two counits agree up to ≈. *)
Definition p474_c4_counits_equiv (R : Rng) (t : FRTerm (Rng_Forget_Ab R)) :
  rig_map (@counit _ _ _ _ free_rng_ab_adjunction R) t
    ≈ rig_map (@counit _ _ _ _ free_rng_ab_adjunction_hom R) t :=
  free_rng_ab_counit_evaluates R t.

(* R3 *)
Fail Example p474_r3_counits (R : Rng) (t : FRTerm (Rng_Forget_Ab R)) :
  rig_map (@counit _ _ _ _ free_rng_ab_adjunction R) t
    = rig_map (@counit _ _ _ _ free_rng_ab_adjunction_hom R) t := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Rng/FreeMonad.v: the monad T *)

(* C5: T A is the abelian group of the free ring. *)
Example p474_c5_T_obj (A : Ab) :
  fobj[TF] A = Rng_Forget_Ab (FreeRngAbObject A) := eq_refl.

(* C6: its carrier is the formal ring expressions... *)
Example p474_c6_T_carrier (A : Ab) :
  carrier (cmon_setoid (fobj[TF] A)) = FRTerm A := eq_refl.

(* C7: ...and its ≈ is [fr_eq]. *)
Example p474_c7_T_equiv (A : Ab) (s t : FRTerm A) :
  @equiv _ (is_setoid (cmon_setoid (fobj[TF] A))) s t = fr_eq s t
  := eq_refl.

(* C8: η is the insertion, as a map of carriers. *)
Example p474_c8_T_ret (A : Ab) :
  cmon_map (@ret _ _ TM A) = cmon_map (free_rng_ab_insert A) := eq_refl.

(* C9: η a = ⟨a⟩. *)
Example p474_c9_T_ret_fun (A : Ab) (a : carrier (cmon_setoid A)) :
  cmon_map (@ret _ _ TM A) a = fr_gen a := eq_refl.

(* R4 *)
Fail Example p474_r4_T_ret_record (A : Ab) :
  @ret _ _ TM A = free_rng_ab_insert A := eq_refl.

(* C10: μ = U ε F. *)
Example p474_c10_T_join_counit (A : Ab) :
  @join _ _ TM A
    = fmap[Rng_Forget_Ab]
        (@counit _ _ _ _ free_rng_ab_adjunction_hom (FreeRngAb A))
  := eq_refl.

(* C11: μ evaluates, at a variable expression. *)
Example p474_c11_T_join_fun (A : Ab) (t : FRTerm (fobj[TF] A)) :
  cmon_map (@join _ _ TM A) t = fr_eval (@id Ab (fobj[TF] A)) t := eq_refl.

(* C12: μ⟨t⟩ = t. *)
Example p474_c12_T_join_gen (A : Ab) (t : FRTerm A) :
  cmon_map (@join _ _ TM A) (@fr_gen (fobj[TF] A) t) = t := eq_refl.

(* C13: μ(⟨s⟩·⟨t⟩) = s·t. *)
Example p474_c13_T_join_mul (A : Ab) (s t : FRTerm A) :
  cmon_map (@join _ _ TM A)
    (fr_mul (@fr_gen (fobj[TF] A) s) (@fr_gen (fobj[TF] A) t))
    = fr_mul s t := eq_refl.

(* C14: μ(⟨s⟩ + ⟨t⟩) = s + t. *)
Example p474_c14_T_join_plus (A : Ab) (s t : FRTerm A) :
  cmon_map (@join _ _ TM A)
    (fr_plus (@fr_gen (fobj[TF] A) s) (@fr_gen (fobj[TF] A) t))
    = fr_plus s t := eq_refl.

(* C15: μ 1 = 1. *)
Example p474_c15_T_join_one (A : Ab) :
  cmon_map (@join _ _ TM A) (@fr_one (fobj[TF] A)) = @fr_one A := eq_refl.

(* C16: T f relabels the generators, up to ≈. *)
Definition p474_c16_T_map_equiv {A B : Ab} (f : A ~{Ab}~> B)
  (t : FRTerm A) :
  cmon_map (fmap[TF] f) t ≈ fr_eval (free_rng_ab_insert B ∘[Ab] f) t :=
  T_map_relabel f t.

(* R5 *)
Fail Example p474_r5_T_map_gen {A B : Ab} (f : A ~{Ab}~> B)
  (a : carrier (cmon_setoid A)) :
  cmon_map (fmap[TF] f) (fr_gen a) = fr_gen (cmon_map f a) := eq_refl.

(* R6 *)
Fail Example p474_r6_T_map_var {A B : Ab} (f : A ~{Ab}~> B)
  (t : FRTerm A) :
  cmon_map (fmap[TF] f) t = fr_eval (free_rng_ab_insert B ∘[Ab] f) t
  := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Route A, not taken: the monad of the universal-arrow adjunction *)

(* C17: route A's monad, the literal reading. *)
Definition p474_c17_TA : @Monad Ab (Rng_Forget_Ab ◯ FreeRngAb) :=
  Adjunction_Induced_Monad free_rng_ab_adjunction.

(* C18: route A's comparison functor. *)
Definition p474_c18_KA : Rng ⟶ @EilenbergMoore Ab _ p474_c17_TA :=
  EM_Comparison free_rng_ab_adjunction.

(* C19: route A's μ is the evaluation up to ≈. *)
Definition p474_c19_TA_join_equiv (A : Ab)
  (t : FRTerm (fobj[Rng_Forget_Ab ◯ FreeRngAb] A)) :
  cmon_map (@join _ _ p474_c17_TA A) t
    ≈ fr_eval (@id Ab (fobj[Rng_Forget_Ab ◯ FreeRngAb] A)) t :=
  free_rng_ab_counit_evaluates (FreeRngAb A) t.

(* C20: so is the structure map of route A's K R. *)
Definition p474_c20_KA_alg_equiv (R : Rng) (t : FRTerm (Rng_Forget_Ab R)) :
  cmon_map (t_alg[projT2 (fobj[p474_c18_KA] R)]) t
    ≈ fr_eval (@id Ab (Rng_Forget_Ab R)) t :=
  free_rng_ab_counit_evaluates R t.

(* R7 *)
Fail Example p474_r7_TA_join_gen (A : Ab) (t : FRTerm A) :
  cmon_map (@join _ _ p474_c17_TA A)
    (@fr_gen (fobj[Rng_Forget_Ab ◯ FreeRngAb] A) t) = t := eq_refl.

(* R8 *)
Fail Example p474_r8_TA_join_var (A : Ab)
  (t : FRTerm (fobj[Rng_Forget_Ab ◯ FreeRngAb] A)) :
  cmon_map (@join _ _ p474_c17_TA A) t
    = fr_eval (@id Ab (fobj[Rng_Forget_Ab ◯ FreeRngAb] A)) t := eq_refl.

(* R9 *)
Fail Example p474_r9_TA_join_mul (A : Ab) (s t : FRTerm A) :
  cmon_map (@join _ _ p474_c17_TA A)
    (fr_mul (@fr_gen (fobj[Rng_Forget_Ab ◯ FreeRngAb] A) s)
            (@fr_gen (fobj[Rng_Forget_Ab ◯ FreeRngAb] A) t))
    = fr_mul s t := eq_refl.

(* R10 *)
Fail Example p474_r10_TA_join_one (A : Ab) :
  cmon_map (@join _ _ p474_c17_TA A)
    (@fr_one (fobj[Rng_Forget_Ab ◯ FreeRngAb] A)) = @fr_one A := eq_refl.

(* R11 *)
Fail Example p474_r11_KA_one (R : Rng) :
  cmon_map (t_alg[projT2 (fobj[p474_c18_KA] R)]) (@fr_one (Rng_Forget_Ab R))
    = rig_one R := eq_refl.

(* R12 *)
Fail Example p474_r12_KA_mul (R : Rng) (a b : carrier (rig_setoid R)) :
  cmon_map (t_alg[projT2 (fobj[p474_c18_KA] R)])
    (fr_mul (@fr_gen (Rng_Forget_Ab R) a) (@fr_gen (Rng_Forget_Ab R) b))
    = rig_mul R a b := eq_refl.

(* R13 *)
Fail Example p474_r13_KA_gen (R : Rng) (a : carrier (rig_setoid R)) :
  cmon_map (t_alg[projT2 (fobj[p474_c18_KA] R)]) (@fr_gen (Rng_Forget_Ab R) a)
    = a := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Rng/FreeMonad.v: the comparison and Rng ≅ Ab^T *)

(* C21: the leg [to] of [Rng_EM_iso] is K. *)
Example p474_c21_iso_to :
  to Rng_EM_iso = EM_Comparison free_rng_ab_adjunction_hom := eq_refl.

(* C22: the leg [from]. *)
Example p474_c22_iso_from : from Rng_EM_iso = EM_to_Rng := eq_refl.

(* C23: K R has carrier U R. *)
Example p474_c23_K_carrier (R : Rng) :
  projT1 (fobj[Rng_K] R) = Rng_Forget_Ab R := eq_refl.

(* C24: its structure map is U ε_R. *)
Example p474_c24_K_alg (R : Rng) :
  t_alg[projT2 (fobj[Rng_K] R)]
    = fmap[Rng_Forget_Ab] (@counit _ _ _ _ free_rng_ab_adjunction_hom R)
  := eq_refl.

(* C25: which evaluates in R. *)
Example p474_c25_K_alg_fun (R : Rng) (t : FRTerm (Rng_Forget_Ab R)) :
  cmon_map (t_alg[projT2 (fobj[Rng_K] R)]) t
    = fr_eval (@id Ab (Rng_Forget_Ab R)) t := eq_refl.

(* C26: 1 ↦ 1. *)
Example p474_c26_K_one (R : Rng) :
  cmon_map (t_alg[projT2 (fobj[Rng_K] R)]) (@fr_one (Rng_Forget_Ab R))
    = rig_one R := eq_refl.

(* C27: ⟨a⟩ ↦ a. *)
Example p474_c27_K_gen (R : Rng) (a : carrier (rig_setoid R)) :
  cmon_map (t_alg[projT2 (fobj[Rng_K] R)]) (@fr_gen (Rng_Forget_Ab R) a) = a
  := eq_refl.

(* C28: ⟨a⟩·⟨b⟩ ↦ a·b. *)
Example p474_c28_K_mul (R : Rng) (a b : carrier (rig_setoid R)) :
  cmon_map (t_alg[projT2 (fobj[Rng_K] R)])
    (fr_mul (@fr_gen (Rng_Forget_Ab R) a) (@fr_gen (Rng_Forget_Ab R) b))
    = rig_mul R a b := eq_refl.

(* C29: ⟨a⟩ + ⟨b⟩ ↦ a + b. *)
Example p474_c29_K_plus (R : Rng) (a b : carrier (rig_setoid R)) :
  cmon_map (t_alg[projT2 (fobj[Rng_K] R)])
    (fr_plus (@fr_gen (Rng_Forget_Ab R) a) (@fr_gen (Rng_Forget_Ab R) b))
    = rig_add R a b := eq_refl.

(* C30: K f = U f. *)
Example p474_c30_K_map {R S : Rng} (f : R ~{Rng}~> S) :
  t_alg_hom[fmap[Rng_K] f] = fmap[Rng_Forget_Ab] f := eq_refl.

(* C31: the ring of an algebra: 1 = h 1... *)
Example p474_c31_EM_one (x : RngAlg) :
  rig_one (fobj[EM_to_Rng] x) = cmon_map (t_alg[projT2 x]) fr_one
  := eq_refl.

(* C32: ...a·b = h(⟨a⟩·⟨b⟩)... *)
Example p474_c32_EM_mul (x : RngAlg) (a b : carrier (cmon_setoid (`1 x))) :
  rig_mul (fobj[EM_to_Rng] x) a b
    = cmon_map (t_alg[projT2 x]) (fr_mul (fr_gen a) (fr_gen b)) := eq_refl.

(* C33: ...and A's own +. *)
Example p474_c33_EM_add (x : RngAlg) :
  rig_add (fobj[EM_to_Rng] x) = cmon_plus (`1 x) := eq_refl.

(* C34: an algebra map is its own ring map. *)
Example p474_c34_EM_map {x y : RngAlg} (f : x ~{RngAlg}~> y) :
  rig_map (fmap[EM_to_Rng] f) = cmon_map (t_alg_hom[f]) := eq_refl.

(* C35 to C41: the ring round trip, field by field and on maps. *)
(* C35 *)
Example p474_c35_rt_setoid (R : Rng) :
  rig_setoid (fobj[EM_to_Rng ◯ Rng_K] R) = rig_setoid R := eq_refl.
(* C36 *)
Example p474_c36_rt_zero (R : Rng) :
  rig_zero (fobj[EM_to_Rng ◯ Rng_K] R) = rig_zero R := eq_refl.
(* C37 *)
Example p474_c37_rt_add (R : Rng) :
  rig_add (fobj[EM_to_Rng ◯ Rng_K] R) = rig_add R := eq_refl.
(* C38 *)
Example p474_c38_rt_one (R : Rng) :
  rig_one (fobj[EM_to_Rng ◯ Rng_K] R) = rig_one R := eq_refl.
(* C39 *)
Example p474_c39_rt_mul (R : Rng) (a b : carrier (rig_setoid R)) :
  rig_mul (fobj[EM_to_Rng ◯ Rng_K] R) a b = rig_mul R a b := eq_refl.
(* C40 *)
Example p474_c40_rt_neg (R : Rng) :
  ring_neg (fobj[EM_to_Rng ◯ Rng_K] R) = ring_neg R := eq_refl.
(* C41 *)
Example p474_c41_rt_hom {R S : Rng} (f : R ~{Rng}~> S) :
  rig_map (fmap[EM_to_Rng ◯ Rng_K] f) = rig_map f := eq_refl.

(* R14 *)
Fail Example p474_r14_rt_ring (R : Rng) :
  fobj[EM_to_Rng ◯ Rng_K] R = R := eq_refl.

(* C42: the algebra round trip keeps the group... *)
Example p474_c42_EM_rt_carrier (x : RngAlg) :
  `1 (fobj[Rng_K ◯ EM_to_Rng] x) = `1 x := eq_refl.

(* C43: ...returns the structure map as the evaluation in its ring... *)
Example p474_c43_EM_rt_alg_fun (x : RngAlg) (t : FRTerm (`1 x)) :
  cmon_map (t_alg[projT2 (fobj[Rng_K ◯ EM_to_Rng] x)]) t
    = fr_eval (R := ralg_ring (projT2 x)) (@id Ab (`1 x)) t := eq_refl.

(* C44: ...and keeps the maps. *)
Example p474_c44_EM_rt_alg_hom {x y : RngAlg} (f : x ~{RngAlg}~> y) :
  t_alg_hom[fmap[Rng_K ◯ EM_to_Rng] f] = t_alg_hom[f] := eq_refl.

(* C45: the structure map comes back up to ≈. *)
Definition p474_c45_EM_rt_alg_equiv (x : RngAlg) (t : FRTerm (`1 x)) :
  cmon_map (t_alg[projT2 (fobj[Rng_K ◯ EM_to_Rng] x)]) t
    ≈ cmon_map (t_alg[projT2 x]) t :=
  ralg_fold (projT2 x) t.

(* R15 *)
Fail Example p474_r15_rt_alg_var (x : RngAlg) (t : FRTerm (`1 x)) :
  cmon_map (t_alg[projT2 (fobj[Rng_K ◯ EM_to_Rng] x)]) t
    = cmon_map (t_alg[projT2 x]) t := eq_refl.

(* R16 *)
Fail Example p474_r16_rt_alg (x : RngAlg) :
  fobj[Rng_K ◯ EM_to_Rng] x = x := eq_refl.

(* R17 *)
Fail Example p474_r17_rt_functor_Rng :
  EM_to_Rng ◯ Rng_K = Id[Rng] := eq_refl.

(* R18 *)
Fail Example p474_r18_rt_functor_EM :
  Rng_K ◯ EM_to_Rng = Id[RngAlg] := eq_refl.

(* C46 to C49: every component of the two natural isomorphisms, and of
   the equivalence, is the identity. *)
(* C46 *)
Example p474_c46_to_from_component (x : RngAlg) :
  (t_alg_hom[to (`1 (iso_to_from Rng_EM_iso) x)],
   t_alg_hom[from (`1 (iso_to_from Rng_EM_iso) x)])
    = (@id Ab (`1 x), @id Ab (`1 x)) := eq_refl.
(* C47 *)
Example p474_c47_from_to_component (R : Rng) :
  (rig_map (to (`1 (iso_from_to Rng_EM_iso) R)),
   rig_map (from (`1 (iso_from_to Rng_EM_iso) R)))
    = (@setoid_morphism_id (rig_setoid R),
       @setoid_morphism_id (rig_setoid R)) := eq_refl.
(* C48 *)
Example p474_c48_counit_component (x : RngAlg) :
  (t_alg_hom[to (`1 (@equivalence_counit _ _ _ Rng_EM_equivalence) x)],
   t_alg_hom[from (`1 (@equivalence_counit _ _ _ Rng_EM_equivalence) x)])
    = (@id Ab (`1 x), @id Ab (`1 x)) := eq_refl.
(* C49 *)
Example p474_c49_unit_component (R : Rng) :
  (rig_map (to (`1 (@equivalence_unit _ _ _ Rng_EM_equivalence) R)),
   rig_map (from (`1 (@equivalence_unit _ _ _ Rng_EM_equivalence) R)))
    = (@setoid_morphism_id (rig_setoid R),
       @setoid_morphism_id (rig_setoid R)) := eq_refl.

(* C50: through Theory/Equivalence.v's bridge, the [iso_to_from] component
   is the identity too... *)
Example p474_c50_bridge_to_from (x : RngAlg) :
  t_alg_hom[to (`1 (iso_to_from (Equivalence_to_Cat_Iso Rng_EM_equivalence))
                 x)] = @id Ab (`1 x) := eq_refl.

(* R19 *)
Fail Example p474_r19_bridge_from_to (R : Rng) :
  rig_map (to (`1 (iso_from_to (Equivalence_to_Cat_Iso Rng_EM_equivalence))
                 R)) = @setoid_morphism_id (rig_setoid R) := eq_refl.

(* C51 to C54: the forgetful functors, on objects and on arrows. *)
(* C51 *)
Example p474_c51_K_forget_obj (R : Rng) :
  fobj[RngAlg_Forget] (fobj[Rng_K] R) = fobj[Rng_Forget_Ab] R := eq_refl.
(* C52 *)
Example p474_c52_K_forget_map {R S : Rng} (f : R ~{Rng}~> S) :
  fmap[RngAlg_Forget] (fmap[Rng_K] f) = fmap[Rng_Forget_Ab] f := eq_refl.
(* C53 *)
Example p474_c53_EM_forget_obj (x : RngAlg) :
  fobj[Rng_Forget_Ab] (fobj[EM_to_Rng] x) = fobj[RngAlg_Forget] x := eq_refl.
(* C54 *)
Example p474_c54_EM_forget_map {x y : RngAlg} (f : x ~{RngAlg}~> y) :
  fmap[Rng_Forget_Ab] (fmap[EM_to_Rng] f) = fmap[RngAlg_Forget] f
  := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Ab/TensorPower.v: ⨁ₙ A^{⊗n} *)

(* C55: the tensor powers are Spider.v's [tpower] at Ab: A^{⊗0} = ℤ... *)
Example p474_c55_tpower_zero (A : Ab) : tpower A 0 = ZAb := eq_refl.

(* C56: ...and A^{⊗(n+1)} = A ⊗ A^{⊗n}. *)
Example p474_c56_tpower_succ (A : Ab) (n : nat) :
  tpower A (S n) = AbTensor A (tpower A n) := eq_refl.

(* C57: ι_{n+1}(a ⊗ x) = ⟨a⟩ · ι_n x. *)
Example p474_c57_iota_gen (A : Ab) (n : nat) (a : carrier (cmon_setoid A))
  (x : carrier (tpower A n)) :
  cmon_map (tw_iota (S n)) (@ts_gen A (tpower A n) a x)
    = tw_lmul (a :: nil) (cmon_map (tw_iota n) x) := eq_refl.

(* C58: the copairing computes on words. *)
Example p474_c58_desc_word (A c : Ab)
  (iota : ∀ n : nat, tpower A n ~{Ab}~> c)
  (w : list (carrier (cmon_setoid A))) :
  cmon_map (tw_desc A c iota) (tw_word w)
    = cmon_map (iota (length w)) (tw_pure w) := eq_refl.

(* C59: the extension of a multilinear ν computes on words. *)
Example p474_c59_ext_word (A c : Ab)
  (ν : list (carrier (cmon_setoid A)) → carrier (cmon_setoid c))
  (Hl : ∀ (u v : list (carrier (cmon_setoid A)))
          (a b : carrier (cmon_setoid A)),
          a ≈ b → ν (u ++ a :: v) ≈ ν (u ++ b :: v))
  (Hn : ∀ (u v : list (carrier (cmon_setoid A)))
          (a b : carrier (cmon_setoid A)),
          ν (u ++ cmon_plus A a b :: v)
            ≈ cmon_plus c (ν (u ++ a :: v)) (ν (u ++ b :: v)))
  (w : list (carrier (cmon_setoid A))) :
  cmon_map (tw_ext c ν Hl Hn) (tw_word w) = ν w := eq_refl.

(* C60: the copairing composed with ιₙ, up to ≈. *)
Definition p474_c60_desc_iota_equiv (A c : Ab)
  (iota : ∀ n : nat, tpower A n ~{Ab}~> c) (n : nat)
  (x : carrier (tpower A n)) :
  cmon_map (tw_desc A c iota) (cmon_map (tw_iota n) x) ≈ cmon_map (iota n) x :=
  tw_desc_iota A c n iota x.

(* R20 *)
Fail Example p474_r20_desc_iota (A c : Ab)
  (iota : ∀ n : nat, tpower A n ~{Ab}~> c) (n : nat)
  (x : carrier (tpower A n)) :
  cmon_map (tw_desc A c iota) (cmon_map (tw_iota n) x) = cmon_map (iota n) x
  := eq_refl.

(* C61: a word is the image of its pure tensor, up to ≈. *)
Definition p474_c61_word_iota_equiv (A : Ab)
  (w : list (carrier (cmon_setoid A))) :
  tw_eq A (tw_word w) (cmon_map (tw_iota (length w)) (tw_pure w)) :=
  tw_word_iota A w.

(* R21 *)
Fail Example p474_r21_word_iota (A : Ab)
  (w : list (carrier (cmon_setoid A))) :
  tw_word w = cmon_map (tw_iota (length w)) (tw_pure w) := eq_refl.

(* C103: and false at Leibniz = at the empty word, where ι₀ 1 is the sum
   ⟨⟩ + 0. *)
Definition p474_c103_word_iota_not_leibniz (A : Ab) :
  tw_word (@nil (carrier (cmon_setoid A)))
    ≠ cmon_map (@tw_iota A (length (@nil (carrier (cmon_setoid A)))))
        (tw_pure nil) := fun H => ltac:(discriminate H).

(* C104: [tw_desc_iota] is false at Leibniz = too: at c := ⨁, the family
   ι and n := 0, the copairing returns (⟨⟩ + 0) + 0 for ⟨⟩ + 0. *)
Definition p474_c104_desc_iota_not_leibniz (A : Ab) :
  cmon_map (tw_desc A (TWAb A) (@tw_iota A))
    (cmon_map (@tw_iota A 0) ZAb_one) ≠ cmon_map (@tw_iota A 0) ZAb_one
  := fun H => ltac:(discriminate H).

(* ------------------------------------------------------------------------ *)
(** ** Instance/Rng/FreeMonad/Words.v: T A ≅ ⨁ₙ A^{⊗n} *)

(* C62: the ring's abelian group is the words'. *)
Example p474_c62_TWRing_ab (A : AbObject) :
  Rng_Forget_Ab (TWRing A) = TWAb A := eq_refl.

(* C63: ⟨u⟩·⟨v⟩ = ⟨u v⟩. *)
Example p474_c63_mul_words (A : AbObject)
  (u v : list (carrier (cmon_setoid A))) :
  tw_mul (tw_word u) (tw_word v) = tw_word (u ++ v) := eq_refl.

(* C64: η a goes to the one-letter word. *)
Example p474_c64_TW_ret (A : Ab) (a : carrier (cmon_setoid A)) :
  cmon_map (to (T_TW_iso A)) (cmon_map (@ret _ _ TM A) a) = tw_word (a :: nil)
  := eq_refl.

(* C65: [to] is the shared extension of the insertion. *)
Example p474_c65_TW_to (A : Ab) (t : FRTerm A) :
  cmon_map (to (T_TW_iso A)) t = fr_eval (@tw_insert A) t := eq_refl.

(* C66: [from] sends a word to the product of its letters. *)
Example p474_c66_TW_from (A : Ab) (w : list (carrier (cmon_setoid A))) :
  cmon_map (from (T_TW_iso A)) (tw_word w) = fr_word w := eq_refl.

(* C67: from ∘ to at a generator... *)
Example p474_c67_TW_from_to_gen (A : Ab) (a : carrier (cmon_setoid A)) :
  cmon_map (from (T_TW_iso A)) (cmon_map (to (T_TW_iso A)) (fr_gen a))
    = fr_gen a := eq_refl.

(* C68: ...and at a product of two. *)
Example p474_c68_TW_from_to_pair (A : Ab) (a b : carrier (cmon_setoid A)) :
  cmon_map (from (T_TW_iso A))
    (cmon_map (to (T_TW_iso A)) (fr_mul (fr_gen a) (fr_gen b)))
    = fr_mul (fr_gen a) (fr_gen b) := eq_refl.

(* C69: from ∘ to up to ≈. *)
Definition p474_c69_TW_from_to_equiv (A : Ab) (t : FRTerm A) :
  cmon_map (from (T_TW_iso A)) (cmon_map (to (T_TW_iso A)) t) ≈ t :=
  iso_from_to (T_TW_iso A) t.

(* R22 *)
Fail Example p474_r22_TW_from_to_var (A : Ab) (t : FRTerm A) :
  cmon_map (from (T_TW_iso A)) (cmon_map (to (T_TW_iso A)) t) = t
  := eq_refl.

(* R23 *)
Fail Example p474_r23_TW_from_to_rebracket (A : Ab)
  (a b c : carrier (cmon_setoid A)) :
  cmon_map (from (T_TW_iso A))
    (cmon_map (to (T_TW_iso A))
       (fr_mul (fr_mul (fr_gen a) (fr_gen b)) (fr_gen c)))
    = fr_mul (fr_mul (fr_gen a) (fr_gen b)) (fr_gen c) := eq_refl.

(* C105: and false at Leibniz =: from ∘ to rebrackets to the right. *)
Definition p474_c105_from_to_not_leibniz (A : Ab)
  (a b c : carrier (cmon_setoid A)) :
  cmon_map (from (T_TW_iso A))
    (cmon_map (to (T_TW_iso A))
       (fr_mul (fr_mul (fr_gen a) (fr_gen b)) (fr_gen c)))
    ≠ fr_mul (fr_mul (fr_gen a) (fr_gen b)) (fr_gen c)
  := fun H => ltac:(injection H; intros _ H1; discriminate H1).

(* C70: to ∘ from is the identity on terms as a Leibniz lemma. *)
Definition p474_c70_TW_to_from_lemma (A : Ab) (t : TWTerm A) :
  rig_map (@tw_to_rng A) (tw_to_fr t) = t := tw_to_from A t.

(* R24 *)
Fail Example p474_r24_TW_to_from_var (A : Ab) (t : TWTerm A) :
  cmon_map (to (T_TW_iso A)) (cmon_map (from (T_TW_iso A)) t) = t
  := eq_refl.

(* C71: μ of a word of two words is their juxtaposition. *)
Example p474_c71_join_two (A : Ab) (u v : list (carrier (cmon_setoid A))) :
  tw_join (@tw_word (TWAb A) (tw_word u :: tw_word v :: nil))
    = tw_word (u ++ v) := eq_refl.

(* C72: μ read through the isomorphism, at a generator of T T A... *)
Example p474_c72_TW_join_gen (A : Ab) (s : FRTerm A) :
  cmon_map (to (T_TW_iso A))
    (cmon_map (@join _ _ TM A) (@fr_gen (fobj[TF] A) s))
  = tw_join (tw_map (to (T_TW_iso A))
       (cmon_map (to (T_TW_iso (fobj[TF] A))) (@fr_gen (fobj[TF] A) s)))
  := eq_refl.

(* C73: ...and at a product of two. *)
Example p474_c73_TW_join_pair (A : Ab) (s t : FRTerm A) :
  cmon_map (to (T_TW_iso A))
    (cmon_map (@join _ _ TM A)
       (fr_mul (@fr_gen (fobj[TF] A) s) (@fr_gen (fobj[TF] A) t)))
  = tw_join (tw_map (to (T_TW_iso A))
       (cmon_map (to (T_TW_iso (fobj[TF] A)))
          (fr_mul (@fr_gen (fobj[TF] A) s) (@fr_gen (fobj[TF] A) t))))
  := eq_refl.

(* C74: and up to ≈ at a variable. *)
Definition p474_c74_TW_join_equiv (A : Ab) (t : FRTerm (fobj[TF] A)) :
  tw_eq A (cmon_map (to (T_TW_iso A)) (cmon_map (@join _ _ TM A) t))
          (tw_join (tw_map (to (T_TW_iso A))
                      (cmon_map (to (T_TW_iso (fobj[TF] A))) t))) :=
  T_TW_join t.

(* R25 *)
Fail Example p474_r25_TW_join_var (A : Ab) (t : FRTerm (fobj[TF] A)) :
  cmon_map (to (T_TW_iso A)) (cmon_map (@join _ _ TM A) t)
  = tw_join (tw_map (to (T_TW_iso A)) (cmon_map (to (T_TW_iso (fobj[TF] A))) t))
  := eq_refl.

(* C106: and false at Leibniz =: at ⟨⟨x⟩ + ⟨y⟩⟩ · 0 the left side is 0 + 0
   and the right side 0. *)
Definition p474_c106_join_not_leibniz (A : Ab)
  (x y : carrier (cmon_setoid A)) :
  cmon_map (to (T_TW_iso A))
    (cmon_map (@join _ _ TM A)
       (fr_mul (@fr_gen (fobj[TF] A) (fr_plus (fr_gen x) (fr_gen y)))
               fr_zero))
  ≠ tw_join (tw_map (to (T_TW_iso A))
       (cmon_map (to (T_TW_iso (fobj[TF] A)))
          (fr_mul (@fr_gen (fobj[TF] A) (fr_plus (fr_gen x) (fr_gen y)))
                  fr_zero)))
  := fun H => ltac:(discriminate H).

(* C75: T f read through the isomorphism, up to ≈. *)
Definition p474_c75_TW_map_equiv {A B : Ab} (f : A ~{Ab}~> B)
  (t : FRTerm A) :
  tw_eq B (cmon_map (to (T_TW_iso B)) (cmon_map (fmap[TF] f) t))
          (tw_map f (cmon_map (to (T_TW_iso A)) t)) :=
  T_TW_map f t.

(* R26 *)
Fail Example p474_r26_TW_map_gen {A B : Ab} (f : A ~{Ab}~> B)
  (a : carrier (cmon_setoid A)) :
  cmon_map (to (T_TW_iso B)) (cmon_map (fmap[TF] f) (fr_gen a))
  = tw_map f (cmon_map (to (T_TW_iso A)) (fr_gen a)) := eq_refl.

(* C76: the functor ⨁ₙ (−)^{⊗n} on objects... *)
Example p474_c76_TWF_obj (A : Ab) : fobj[TWF] A = TWAb A := eq_refl.

(* C77: ...and on arrows, letterwise, on the nose. *)
Example p474_c77_TWF_map_word {A B : Ab} (f : A ~{Ab}~> B)
  (w : list (carrier (cmon_setoid A))) :
  cmon_map (fmap[TWF] f) (tw_word w) = tw_word (map (cmon_map f) w)
  := eq_refl.

(* C78: the components of T ≈ TWF are the isomorphisms of (a). *)
Example p474_c78_natural_component (A : Ab) :
  `1 T_TW_natural A = T_TW_iso A := eq_refl.

(* C108: the direct monad's η IS the insertion of one-letter words, as the
   whole record... *)
Example p474_c108_TWMonad_ret (A : Ab) :
  @ret _ _ TWMonad A = @tw_insert A := eq_refl.

(* C109: ...its μ IS juxtaposition, at a variable... *)
Example p474_c109_TWMonad_join (A : Ab) (t : TWTerm (TWAb A)) :
  cmon_map (@join _ _ TWMonad A) t = tw_join t := eq_refl.

(* C110: ...on a word of words the product of the inner words... *)
Example p474_c110_TWMonad_join_word (A : Ab) (ws : list (TWTerm A)) :
  cmon_map (@join _ _ TWMonad A) (@tw_word (TWAb A) ws) = tw_prod ws
  := eq_refl.

(* C111: ...and μ ∘ η T = 1 on the nose, at a variable. *)
Example p474_c111_TWMonad_join_ret (A : Ab) (t : TWTerm A) :
  cmon_map (@join _ _ TWMonad A)
    (cmon_map (@ret _ _ TWMonad (fobj[TWF] A)) t) = t := eq_refl.

(* C112: its associative law is false at Leibniz =: at the word
   ⟨⟨⟨x⟩ + ⟨y⟩⟩, 0⟩ of T T T A, μ ∘ T μ gives 0 + 0 and μ ∘ μ T gives 0. *)
Definition p474_c112_TWMonad_assoc_not_leibniz (A : Ab)
  (x y : carrier (cmon_setoid A)) :
  cmon_map (@join _ _ TWMonad A)
    (cmon_map (fmap[TWF] (@join _ _ TWMonad A))
       (@tw_word (TWAb (TWAb A))
          (@tw_word (TWAb A)
             (@tw_plus A (tw_word (x :: nil)) (tw_word (y :: nil)) :: nil)
           :: @tw_zero (TWAb A) :: nil)))
  ≠ cmon_map (@join _ _ TWMonad A)
      (cmon_map (@join _ _ TWMonad (fobj[TWF] A))
         (@tw_word (TWAb (TWAb A))
            (@tw_word (TWAb A)
               (@tw_plus A (tw_word (x :: nil)) (tw_word (y :: nil)) :: nil)
             :: @tw_zero (TWAb A) :: nil)))
  := fun H => ltac:(discriminate H).

(* C113: the morphism of monads T → TWMonad has the components of (a)... *)
Example p474_c113_monad_hom_component (A : Ab) :
  transform[mh_transform T_TW_monad_hom] A = to (T_TW_iso A) := eq_refl.

(* C114: ...the morphism back has their inverses... *)
Example p474_c114_monad_hom_back_component (A : Ab) :
  transform[mh_transform TW_T_monad_hom] A = from (T_TW_iso A) := eq_refl.

(* C115: ...and the two are the legs of T ≅ TWMonad in [Monads Ab]. *)
Example p474_c115_monad_iso_to : to T_TW_monad_iso = T_TW_monad_hom
  := eq_refl.

(* C116 *)
Example p474_c116_monad_iso_from : from T_TW_monad_iso = TW_T_monad_hom
  := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Rng/FreeMonad/System.v: the systems ⟨A, ν₀, ν₁, …⟩ *)

(* C79: ν of an algebra's system is the structure map on the word... *)
Example p474_c79_alg_nu (A : Ab) (α : @TAlgebra Ab TF TM A)
  (w : list (carrier (cmon_setoid A))) :
  tnu (alg_system α) w = cmon_map (t_alg[α]) (fr_word w) := eq_refl.

(* C80: ...ν₀ the unit of its ring... *)
Example p474_c80_alg_nil (A : Ab) (α : @TAlgebra Ab TF TM A) :
  tnu (alg_system α) nil = ralg_one α := eq_refl.

(* C81: ...and ν₂ its product. *)
Example p474_c81_alg_pair (A : Ab) (α : @TAlgebra Ab TF TM A)
  (a b : carrier (cmon_setoid A)) :
  tnu (alg_system α) (a :: b :: nil) = ralg_mul α a b := eq_refl.

(* C107: [fr_eval_id_word_concat] is false at Leibniz =: at the word of
   words ⟨⟨a⟩, ⟨⟩⟩ one side is ⟨a⟩·1 and the other ⟨a⟩. *)
Definition p474_c107_word_concat_not_leibniz (A : Ab)
  (a : carrier (cmon_setoid A)) :
  fr_eval (@id Ab (fobj[TF] A))
    (@fr_word (fobj[TF] A) (map fr_word ((a :: nil) :: nil :: nil)))
    ≠ fr_word (concat ((a :: nil) :: nil :: nil))
  := fun H => ltac:(discriminate H).

(* C82: the leg [to] of [TSys_EM_iso]... *)
Example p474_c82_sys_iso_to : to TSys_EM_iso = TSys_to_EM := eq_refl.

(* C83: ...and the leg [from]. *)
Example p474_c83_sys_iso_from : from TSys_EM_iso = EM_to_TSys := eq_refl.

(* C84: a system's algebra evaluates in the system's ring... *)
Example p474_c84_sys_alg (S : TSys) (t : FRTerm (tsys_ab S)) :
  cmon_map (t_alg[projT2 (fobj[TSys_to_EM] S)]) t
    = fr_eval (R := sys_ring (tsys_str S)) (@id Ab (tsys_ab S)) t := eq_refl.

(* C85: ...1 ↦ ν⟨⟩... *)
Example p474_c85_sys_alg_one (S : TSys) :
  cmon_map (t_alg[projT2 (fobj[TSys_to_EM] S)]) fr_one = tnu (tsys_str S) nil
  := eq_refl.

(* C86: ...and ⟨a⟩·⟨b⟩ ↦ ν⟨a b⟩. *)
Example p474_c86_sys_alg_pair (S : TSys)
  (a b : carrier (cmon_setoid (tsys_ab S))) :
  cmon_map (t_alg[projT2 (fobj[TSys_to_EM] S)]) (fr_mul (fr_gen a) (fr_gen b))
    = tnu (tsys_str S) (a :: b :: nil) := eq_refl.

(* C87: ν of an algebra's system, through the functor. *)
Example p474_c87_EM_sys_nu (x : RngAlg)
  (w : list (carrier (cmon_setoid (`1 x)))) :
  tnu (tsys_str (fobj[EM_to_TSys] x)) w = cmon_map (t_alg[projT2 x]) (fr_word w)
  := eq_refl.

(* C88: ν₂ of an algebra's system is the product of its ring. *)
Example p474_c88_EM_sys_pair (x : RngAlg)
  (a b : carrier (cmon_setoid (`1 x))) :
  tnu (tsys_str (fobj[EM_to_TSys] x)) (a :: b :: nil)
    = rig_mul (fobj[EM_to_Rng] x) a b := eq_refl.

(* C89 to C93: the system round trip keeps the group, ν₀, ν₂ and the maps,
   and returns ν₁ as the identity. *)
(* C89 *)
Example p474_c89_sys_rt_ab (S : TSys) :
  tsys_ab (fobj[EM_to_TSys ◯ TSys_to_EM] S) = tsys_ab S := eq_refl.
(* C90 *)
Example p474_c90_sys_rt_nil (S : TSys) :
  tnu (tsys_str (fobj[EM_to_TSys ◯ TSys_to_EM] S)) nil = tnu (tsys_str S) nil
  := eq_refl.
(* C91 *)
Example p474_c91_sys_rt_letter (S : TSys)
  (a : carrier (cmon_setoid (tsys_ab S))) :
  tnu (tsys_str (fobj[EM_to_TSys ◯ TSys_to_EM] S)) (a :: nil) = a := eq_refl.
(* C92 *)
Example p474_c92_sys_rt_pair (S : TSys)
  (a b : carrier (cmon_setoid (tsys_ab S))) :
  tnu (tsys_str (fobj[EM_to_TSys ◯ TSys_to_EM] S)) (a :: b :: nil)
    = tnu (tsys_str S) (a :: b :: nil) := eq_refl.
(* C93 *)
Example p474_c93_sys_rt_hom {S S' : TSys} (f : S ~{TSys}~> S') :
  `1 (fmap[EM_to_TSys ◯ TSys_to_EM] f) = `1 f := eq_refl.

(* C94: ν through the round trip, up to ≈. *)
Definition p474_c94_sys_rt_nu_equiv (S : TSys)
  (w : list (carrier (cmon_setoid (tsys_ab S)))) :
  tnu (tsys_str (fobj[EM_to_TSys ◯ TSys_to_EM] S)) w ≈ tnu (tsys_str S) w :=
  TSys_rt_nu S w.

(* R27 *)
Fail Example p474_r27_sys_rt_nu_var (S : TSys)
  (w : list (carrier (cmon_setoid (tsys_ab S)))) :
  tnu (tsys_str (fobj[EM_to_TSys ◯ TSys_to_EM] S)) w = tnu (tsys_str S) w
  := eq_refl.

(* R28 *)
Fail Example p474_r28_sys_rt_letter_own (S : TSys)
  (a : carrier (cmon_setoid (tsys_ab S))) :
  tnu (tsys_str (fobj[EM_to_TSys ◯ TSys_to_EM] S)) (a :: nil)
    = tnu (tsys_str S) (a :: nil) := eq_refl.

(* R29 *)
Fail Example p474_r29_sys_rt_whole (S : TSys) :
  fobj[EM_to_TSys ◯ TSys_to_EM] S = S := eq_refl.

(* C95: the algebra round trip through the systems keeps the group... *)
Example p474_c95_EM_sys_rt_carrier (x : RngAlg) :
  `1 (fobj[TSys_to_EM ◯ EM_to_TSys] x) = `1 x := eq_refl.

(* C96: ...and the maps. *)
Example p474_c96_EM_sys_rt_hom {x y : RngAlg} (f : x ~{RngAlg}~> y) :
  t_alg_hom[fmap[TSys_to_EM ◯ EM_to_TSys] f] = t_alg_hom[f] := eq_refl.

(* R30 *)
Fail Example p474_r30_EM_sys_rt_whole (x : RngAlg) :
  fobj[TSys_to_EM ◯ EM_to_TSys] x = x := eq_refl.

(* R31 *)
Fail Example p474_r31_sys_rt_functor :
  EM_to_TSys ◯ TSys_to_EM = Id[TSys] := eq_refl.

(* C97, C98: every component of the two natural isomorphisms is the
   identity. *)
(* C97 *)
Example p474_c97_sys_to_from_component (x : RngAlg) :
  (t_alg_hom[to (`1 (iso_to_from TSys_EM_iso) x)],
   t_alg_hom[from (`1 (iso_to_from TSys_EM_iso) x)])
    = (@id Ab (`1 x), @id Ab (`1 x)) := eq_refl.
(* C98 *)
Example p474_c98_sys_from_to_component (S : TSys) :
  (`1 (to (`1 (iso_from_to TSys_EM_iso) S)),
   `1 (from (`1 (iso_from_to TSys_EM_iso) S)))
    = (@id Ab (tsys_ab S), @id Ab (tsys_ab S)) := eq_refl.

(* R32 *)
Fail Example p474_r32_rng_sys_component (R : Rng)
  (a : carrier (rig_setoid R)) :
  rig_map (to (`1 (iso_from_to Rng_TSys_iso) R)) a = a := eq_refl.

(* C99 to C102: the system of a ring R. *)
(* C99 *)
Example p474_c99_rng_system_nu (R : Rng) (w : list (carrier (rig_setoid R))) :
  tnu (tsys_str (fobj[EM_to_TSys ◯ Rng_K] R)) w
    = fr_eval (@id Ab (Rng_Forget_Ab R)) (@fr_word (Rng_Forget_Ab R) w)
  := eq_refl.
(* C100 *)
Example p474_c100_rng_system_nil (R : Rng) :
  tnu (tsys_str (fobj[EM_to_TSys ◯ Rng_K] R)) nil = rig_one R := eq_refl.
(* C101 *)
Example p474_c101_rng_system_letter (R : Rng) (a : carrier (rig_setoid R)) :
  tnu (tsys_str (fobj[EM_to_TSys ◯ Rng_K] R)) (a :: nil) = a := eq_refl.
(* C102 *)
Example p474_c102_rng_system_pair (R : Rng) (a b : carrier (rig_setoid R)) :
  tnu (tsys_str (fobj[EM_to_TSys ◯ Rng_K] R)) (a :: b :: nil)
    = rig_mul R a b := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** The guard: every constant of the targets *)

Check @Category.Instance.Rng.Free.fr_eval_pointwise.
Check @Category.Instance.Rng.Free.free_rng_ab_hom_iso.
Check @Category.Instance.Rng.Free.free_rng_ab_adjunction_hom.
Check @Category.Instance.Rng.Free.free_rng_ab_hom_counit.
Check @Category.Instance.Rng.Free.free_rng_ab_hom_unit.
Check @Category.Instance.Rng.Free.free_rng_ab_hom_to.
Check @Category.Instance.Ab.TensorPower.TWTerm.
Check @Category.Instance.Ab.TensorPower.tw_word.
Check @Category.Instance.Ab.TensorPower.tw_zero.
Check @Category.Instance.Ab.TensorPower.tw_plus.
Check @Category.Instance.Ab.TensorPower.tw_neg.
Check @Category.Instance.Ab.TensorPower.TWTerm_rect.
Check @Category.Instance.Ab.TensorPower.TWTerm_ind.
Check @Category.Instance.Ab.TensorPower.TWTerm_rec.
Check @Category.Instance.Ab.TensorPower.TWTerm_sind.
Check @Category.Instance.Ab.TensorPower.tw_eq.
Check @Category.Instance.Ab.TensorPower.twe_letter.
Check @Category.Instance.Ab.TensorPower.twe_lin.
Check @Category.Instance.Ab.TensorPower.twe_plus.
Check @Category.Instance.Ab.TensorPower.twe_neg.
Check @Category.Instance.Ab.TensorPower.twe_assoc.
Check @Category.Instance.Ab.TensorPower.twe_comm.
Check @Category.Instance.Ab.TensorPower.twe_zero_l.
Check @Category.Instance.Ab.TensorPower.twe_neg_l.
Check @Category.Instance.Ab.TensorPower.twe_sym.
Check @Category.Instance.Ab.TensorPower.twe_trans.
Check @Category.Instance.Ab.TensorPower.tw_eq_ind.
Check @Category.Instance.Ab.TensorPower.tw_eq_sind.
Check @Category.Instance.Ab.TensorPower.tw_refl.
Check @Category.Instance.Ab.TensorPower.tw_eq_Equivalence.
Check @Category.Instance.Ab.TensorPower.tw_Setoid.
Check @Category.Instance.Ab.TensorPower.TWAb.
Check @Category.Instance.Ab.TensorPower.tw_eq_of_eq.
Check @Category.Instance.Ab.TensorPower.tw_lmul.
Check @Category.Instance.Ab.TensorPower.tw_lmul_app.
Check @Category.Instance.Ab.TensorPower.tw_lmul_nil.
Check @Category.Instance.Ab.TensorPower.tw_lmul_respects_r.
Check @Category.Instance.Ab.TensorPower.tw_neg_plus.
Check @Category.Instance.Ab.TensorPower.tw_neg_zero.
Check @Category.Instance.Ab.TensorPower.tw_zero_zero.
Check @Category.Instance.Ab.TensorPower.tw_lmul_letter.
Check @Category.Instance.Ab.TensorPower.tw_lmul_lin.
Check @Category.Instance.Ab.TensorPower.tw_ext_fun.
Check @Category.Instance.Ab.TensorPower.tw_ext_respects.
Check @Category.Instance.Ab.TensorPower.tw_ext.
Check @Category.Instance.Ab.TensorPower.tw_ext_word.
Check @Category.Instance.Ab.TensorPower.tpower_ab_zero.
Check @Category.Instance.Ab.TensorPower.tpower_ab_succ.
Check @Category.Instance.Ab.TensorPower.tw_pure.
Check @Category.Instance.Ab.TensorPower.tw_iota0.
Check @Category.Instance.Ab.TensorPower.tw_lmul1_bilin.
Check @Category.Instance.Ab.TensorPower.tw_iota.
Check @Category.Instance.Ab.TensorPower.tw_iota_gen.
Check @Category.Instance.Ab.TensorPower.tw_word_iota.
Check @Category.Instance.Ab.TensorPower.ts_gen_hom.
Check @Category.Instance.Ab.TensorPower.tw_shift.
Check @Category.Instance.Ab.TensorPower.tw_desc_fun.
Check @Category.Instance.Ab.TensorPower.tw_desc_letter.
Check @Category.Instance.Ab.TensorPower.tw_desc_lin.
Check @Category.Instance.Ab.TensorPower.tw_desc_respects.
Check @Category.Instance.Ab.TensorPower.tw_desc.
Check @Category.Instance.Ab.TensorPower.tw_desc_lmul.
Check @Category.Instance.Ab.TensorPower.tw_desc_iota.
Check @Category.Instance.Ab.TensorPower.tw_desc_unique.
Check @Category.Instance.Ab.TensorPower.TW_is_tensor_coproduct.
Check @Category.Instance.Ab.TensorPower.tw_desc_word.
Check @Category.Instance.Rng.FreeMonad.TF.
Check @Category.Instance.Rng.FreeMonad.TM.
Check @Category.Instance.Rng.FreeMonad.T_obj.
Check @Category.Instance.Rng.FreeMonad.T_carrier.
Check @Category.Instance.Rng.FreeMonad.T_equiv.
Check @Category.Instance.Rng.FreeMonad.T_ret.
Check @Category.Instance.Rng.FreeMonad.T_ret_fun.
Check @Category.Instance.Rng.FreeMonad.T_join_counit.
Check @Category.Instance.Rng.FreeMonad.T_join_fun.
Check @Category.Instance.Rng.FreeMonad.T_join_gen.
Check @Category.Instance.Rng.FreeMonad.T_join_mul.
Check @Category.Instance.Rng.FreeMonad.T_join_plus.
Check @Category.Instance.Rng.FreeMonad.T_join_one.
Check @Category.Instance.Rng.FreeMonad.T_map_relabel.
Check @Category.Instance.Rng.FreeMonad.RngAlg.
Check @Category.Instance.Rng.FreeMonad.ralg_unit.
Check @Category.Instance.Rng.FreeMonad.ralg_action.
Check @Category.Instance.Rng.FreeMonad.ralg_one.
Check @Category.Instance.Rng.FreeMonad.ralg_mul.
Check @Category.Instance.Rng.FreeMonad.ralg_mul_eval.
Check @Category.Instance.Rng.FreeMonad.ralg_mul_respects.
Check @Category.Instance.Rng.FreeMonad.ralg_mul_assoc.
Check @Category.Instance.Rng.FreeMonad.ralg_one_l.
Check @Category.Instance.Rng.FreeMonad.ralg_one_r.
Check @Category.Instance.Rng.FreeMonad.ralg_distr_l.
Check @Category.Instance.Rng.FreeMonad.ralg_distr_r.
Check @Category.Instance.Rng.FreeMonad.ralg_mul_zero_l.
Check @Category.Instance.Rng.FreeMonad.ralg_mul_zero_r.
Check @Category.Instance.Rng.FreeMonad.ralg_rig.
Check @Category.Instance.Rng.FreeMonad.ralg_ring.
Check @Category.Instance.Rng.FreeMonad.ralg_fold.
Check @Category.Instance.Rng.FreeMonad.EM_rng_map.
Check @Category.Instance.Rng.FreeMonad.EM_to_Rng.
Check @Category.Instance.Rng.FreeMonad.Rng_K.
Check @Category.Instance.Rng.FreeMonad.Rng_EM_counit_iso.
Check @Category.Instance.Rng.FreeMonad.Rng_EM_unit_iso.
Check @Category.Instance.Rng.FreeMonad.Rng_EM_equivalence.
Check @Category.Instance.Rng.FreeMonad.Rng_Forget_Ab_Monadic.
Check @Category.Instance.Rng.FreeMonad.Rng_EM_iso.
Check @Category.Instance.Rng.FreeMonad.RngAlg_Forget.
Check @Category.Instance.Rng.FreeMonad.Rng_K_Forget.
Check @Category.Instance.Rng.FreeMonad.EM_to_Rng_Forget.
Check @Category.Instance.Rng.FreeMonad.Rng_K_Forget_obj.
Check @Category.Instance.Rng.FreeMonad.Rng_K_Forget_map.
Check @Category.Instance.Rng.FreeMonad.EM_to_Rng_Forget_obj.
Check @Category.Instance.Rng.FreeMonad.EM_to_Rng_Forget_map.
Check @Category.Instance.Rng.FreeMonad.Rng_EM_iso_to.
Check @Category.Instance.Rng.FreeMonad.Rng_EM_iso_from.
Check @Category.Instance.Rng.FreeMonad.Rng_K_carrier.
Check @Category.Instance.Rng.FreeMonad.Rng_K_alg.
Check @Category.Instance.Rng.FreeMonad.Rng_K_alg_fun.
Check @Category.Instance.Rng.FreeMonad.Rng_K_alg_one.
Check @Category.Instance.Rng.FreeMonad.Rng_K_alg_gen.
Check @Category.Instance.Rng.FreeMonad.Rng_K_alg_mul.
Check @Category.Instance.Rng.FreeMonad.Rng_K_alg_plus.
Check @Category.Instance.Rng.FreeMonad.Rng_K_map.
Check @Category.Instance.Rng.FreeMonad.EM_to_Rng_one.
Check @Category.Instance.Rng.FreeMonad.EM_to_Rng_mul.
Check @Category.Instance.Rng.FreeMonad.EM_to_Rng_add.
Check @Category.Instance.Rng.FreeMonad.EM_to_Rng_map.
Check @Category.Instance.Rng.FreeMonad.Rng_rt_setoid.
Check @Category.Instance.Rng.FreeMonad.Rng_rt_zero.
Check @Category.Instance.Rng.FreeMonad.Rng_rt_add.
Check @Category.Instance.Rng.FreeMonad.Rng_rt_one.
Check @Category.Instance.Rng.FreeMonad.Rng_rt_mul.
Check @Category.Instance.Rng.FreeMonad.Rng_rt_neg.
Check @Category.Instance.Rng.FreeMonad.Rng_rt_hom.
Check @Category.Instance.Rng.FreeMonad.EM_Rng_rt_carrier.
Check @Category.Instance.Rng.FreeMonad.EM_Rng_rt_alg_fun.
Check @Category.Instance.Rng.FreeMonad.EM_Rng_rt_alg_hom.
Check @Category.Instance.Rng.FreeMonad.Rng_EM_iso_to_from_component.
Check @Category.Instance.Rng.FreeMonad.Rng_EM_iso_from_to_component.
Check @Category.Instance.Rng.FreeMonad.Rng_EM_counit_component.
Check @Category.Instance.Rng.FreeMonad.Rng_EM_unit_component.
Check @Category.Instance.Rng.FreeMonad.Words.tw_mul.
Check @Category.Instance.Rng.FreeMonad.Words.tw_mul_respects_l.
Check @Category.Instance.Rng.FreeMonad.Words.tw_mul_respects_r.
Check @Category.Instance.Rng.FreeMonad.Words.tw_mul_lmul.
Check @Category.Instance.Rng.FreeMonad.Words.tw_mul_assoc.
Check @Category.Instance.Rng.FreeMonad.Words.tw_mul_one_l.
Check @Category.Instance.Rng.FreeMonad.Words.tw_mul_one_r.
Check @Category.Instance.Rng.FreeMonad.Words.tw_mul_distr_l.
Check @Category.Instance.Rng.FreeMonad.Words.tw_mul_zero_r.
Check @Category.Instance.Rng.FreeMonad.Words.TWRing.
Check @Category.Instance.Rng.FreeMonad.Words.TWRing_ab.
Check @Category.Instance.Rng.FreeMonad.Words.tw_mul_words.
Check @Category.Instance.Rng.FreeMonad.Words.fr_word.
Check @Category.Instance.Rng.FreeMonad.Words.fr_word_cons.
Check @Category.Instance.Rng.FreeMonad.Words.fr_word_letter.
Check @Category.Instance.Rng.FreeMonad.Words.fr_word_lin.
Check @Category.Instance.Rng.FreeMonad.Words.fr_word_app.
Check @Category.Instance.Rng.FreeMonad.Words.tw_word_zero.
Check @Category.Instance.Rng.FreeMonad.Words.tw_insert.
Check @Category.Instance.Rng.FreeMonad.Words.tw_to_rng.
Check @Category.Instance.Rng.FreeMonad.Words.tw_to_fr.
Check @Category.Instance.Rng.FreeMonad.Words.tw_to_fr_respects.
Check @Category.Instance.Rng.FreeMonad.Words.tw_from.
Check @Category.Instance.Rng.FreeMonad.Words.fr_eval_word.
Check @Category.Instance.Rng.FreeMonad.Words.tw_to_from.
Check @Category.Instance.Rng.FreeMonad.Words.tw_to_fr_lmul.
Check @Category.Instance.Rng.FreeMonad.Words.tw_to_fr_mul.
Check @Category.Instance.Rng.FreeMonad.Words.tw_from_to.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_iso.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_ret.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_to_fun.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_from_word.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_to_word.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_from_to_gen.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_from_to_pair.
Check @Category.Instance.Rng.FreeMonad.Words.tw_map.
Check @Category.Instance.Rng.FreeMonad.Words.tw_map_lmul.
Check @Category.Instance.Rng.FreeMonad.Words.tw_map_mul.
Check @Category.Instance.Rng.FreeMonad.Words.tw_to_relabel.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_map.
Check @Category.Instance.Rng.FreeMonad.Words.tw_prod.
Check @Category.Instance.Rng.FreeMonad.Words.tw_join.
Check @Category.Instance.Rng.FreeMonad.Words.tw_join_two.
Check @Category.Instance.Rng.FreeMonad.Words.tw_prod_cons.
Check @Category.Instance.Rng.FreeMonad.Words.tw_prod_app.
Check @Category.Instance.Rng.FreeMonad.Words.tw_join_lmul.
Check @Category.Instance.Rng.FreeMonad.Words.tw_join_mul.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_join.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_join_gen.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_join_pair.
Check @Category.Instance.Rng.FreeMonad.Words.tw_map_respects.
Check @Category.Instance.Rng.FreeMonad.Words.tw_map_hom.
Check @Category.Instance.Rng.FreeMonad.Words.tw_word_pointwise.
Check @Category.Instance.Rng.FreeMonad.Words.tw_map_id.
Check @Category.Instance.Rng.FreeMonad.Words.tw_map_comp.
Check @Category.Instance.Rng.FreeMonad.Words.TWF.
Check @Category.Instance.Rng.FreeMonad.Words.TWF_obj.
Check @Category.Instance.Rng.FreeMonad.Words.TWF_map_word.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_natural.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_natural_component.
Check @Category.Instance.Rng.FreeMonad.Words.tw_prod_letter.
Check @Category.Instance.Rng.FreeMonad.Words.tw_prod_lin.
Check @Category.Instance.Rng.FreeMonad.Words.tw_join_respects.
Check @Category.Instance.Rng.FreeMonad.Words.tw_join_hom.
Check @Category.Instance.Rng.FreeMonad.Words.tw_prod_letters.
Check @Category.Instance.Rng.FreeMonad.Words.tw_join_letters.
Check @Category.Instance.Rng.FreeMonad.Words.tw_prod_map.
Check @Category.Instance.Rng.FreeMonad.Words.tw_join_natural.
Check @Category.Instance.Rng.FreeMonad.Words.tw_join_prod.
Check @Category.Instance.Rng.FreeMonad.Words.TWMonad.
Check @Category.Instance.Rng.FreeMonad.Words.TWMonad_ret.
Check @Category.Instance.Rng.FreeMonad.Words.TWMonad_join.
Check @Category.Instance.Rng.FreeMonad.Words.TWMonad_join_word.
Check @Category.Instance.Rng.FreeMonad.Words.TWMonad_join_ret.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_transform.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_monad_hom.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_monad_hom_component.
Check @Category.Instance.Rng.FreeMonad.Words.TW_T_natural.
Check @Category.Instance.Rng.FreeMonad.Words.TW_T_transform.
Check @Category.Instance.Rng.FreeMonad.Words.tw_to_fr_prod.
Check @Category.Instance.Rng.FreeMonad.Words.TW_T_monad_hom.
Check @Category.Instance.Rng.FreeMonad.Words.TW_T_monad_hom_component.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_monad_iso.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_monad_iso_to.
Check @Category.Instance.Rng.FreeMonad.Words.T_TW_monad_iso_from.
Check @Category.Instance.Rng.FreeMonad.System.TSystem.
Check @Category.Instance.Rng.FreeMonad.System.Build_TSystem.
Check @Category.Instance.Rng.FreeMonad.System.tnu.
Check @Category.Instance.Rng.FreeMonad.System.tnu_letter.
Check @Category.Instance.Rng.FreeMonad.System.tnu_lin.
Check @Category.Instance.Rng.FreeMonad.System.tnu_unit.
Check @Category.Instance.Rng.FreeMonad.System.tnu_assoc.
Check @Category.Instance.Rng.FreeMonad.System.tsys_sum.
Check @Category.Instance.Rng.FreeMonad.System.tsys_nu_hom.
Check @Category.Instance.Rng.FreeMonad.System.tsys_nu_hom_pure.
Check @Category.Instance.Rng.FreeMonad.System.TSystemHom.
Check @Category.Instance.Rng.FreeMonad.System.fr_eval_word_map.
Check @Category.Instance.Rng.FreeMonad.System.fr_eval_id_word_concat.
Check @Category.Instance.Rng.FreeMonad.System.alg_nu.
Check @Category.Instance.Rng.FreeMonad.System.alg_system.
Check @Category.Instance.Rng.FreeMonad.System.alg_system_nu.
Check @Category.Instance.Rng.FreeMonad.System.alg_system_nil.
Check @Category.Instance.Rng.FreeMonad.System.alg_system_pair.
Check @Category.Instance.Rng.FreeMonad.System.alg_hom_TSystemHom.
Check @Category.Instance.Rng.FreeMonad.System.sys_one.
Check @Category.Instance.Rng.FreeMonad.System.sys_mul.
Check @Category.Instance.Rng.FreeMonad.System.sys_mul_respects.
Check @Category.Instance.Rng.FreeMonad.System.sys_nu_pair.
Check @Category.Instance.Rng.FreeMonad.System.sys_mul_assoc.
Check @Category.Instance.Rng.FreeMonad.System.sys_one_l.
Check @Category.Instance.Rng.FreeMonad.System.sys_one_r.
Check @Category.Instance.Rng.FreeMonad.System.sys_distr_l.
Check @Category.Instance.Rng.FreeMonad.System.sys_distr_r.
Check @Category.Instance.Rng.FreeMonad.System.sys_mul_zero_l.
Check @Category.Instance.Rng.FreeMonad.System.sys_mul_zero_r.
Check @Category.Instance.Rng.FreeMonad.System.sys_ring.
Check @Category.Instance.Rng.FreeMonad.System.sys_nu_is_product.
Check @Category.Instance.Rng.FreeMonad.System.sys_ring_map.
Check @Category.Instance.Rng.FreeMonad.System.TSysObj.
Check @Category.Instance.Rng.FreeMonad.System.Build_TSysObj.
Check @Category.Instance.Rng.FreeMonad.System.tsys_ab.
Check @Category.Instance.Rng.FreeMonad.System.tsys_str.
Check @Category.Instance.Rng.FreeMonad.System.TSysHom.
Check @Category.Instance.Rng.FreeMonad.System.TSysHom_Setoid.
Check @Category.Instance.Rng.FreeMonad.System.map_cmon_id.
Check @Category.Instance.Rng.FreeMonad.System.TSys_id.
Check @Category.Instance.Rng.FreeMonad.System.TSys_compose.
Check @Category.Instance.Rng.FreeMonad.System.TSys.
Check @Category.Instance.Rng.FreeMonad.System.TSys_to_Rng.
Check @Category.Instance.Rng.FreeMonad.System.TSys_to_EM.
Check @Category.Instance.Rng.FreeMonad.System.EM_to_TSys.
Check @Category.Instance.Rng.FreeMonad.System.TSys_EM_counit_iso.
Check @Category.Instance.Rng.FreeMonad.System.TSys_EM_unit_iso.
Check @Category.Instance.Rng.FreeMonad.System.TSys_EM_iso.
Check @Category.Instance.Rng.FreeMonad.System.Rng_TSys_iso.
Check @Category.Instance.Rng.FreeMonad.System.TSys_EM_iso_to.
Check @Category.Instance.Rng.FreeMonad.System.TSys_EM_iso_from.
Check @Category.Instance.Rng.FreeMonad.System.TSys_to_EM_alg.
Check @Category.Instance.Rng.FreeMonad.System.TSys_to_EM_one.
Check @Category.Instance.Rng.FreeMonad.System.TSys_to_EM_pair.
Check @Category.Instance.Rng.FreeMonad.System.EM_to_TSys_nu.
Check @Category.Instance.Rng.FreeMonad.System.EM_to_TSys_pair.
Check @Category.Instance.Rng.FreeMonad.System.TSys_rt_ab.
Check @Category.Instance.Rng.FreeMonad.System.TSys_rt_nil.
Check @Category.Instance.Rng.FreeMonad.System.TSys_rt_letter.
Check @Category.Instance.Rng.FreeMonad.System.TSys_rt_pair.
Check @Category.Instance.Rng.FreeMonad.System.TSys_rt_hom.
Check @Category.Instance.Rng.FreeMonad.System.TSys_rt_nu.
Check @Category.Instance.Rng.FreeMonad.System.EM_TSys_rt_carrier.
Check @Category.Instance.Rng.FreeMonad.System.EM_TSys_rt_alg_hom.
Check @Category.Instance.Rng.FreeMonad.System.TSys_EM_iso_to_from_component.
Check @Category.Instance.Rng.FreeMonad.System.TSys_EM_iso_from_to_component.
Check @Category.Instance.Rng.FreeMonad.System.Rng_system_nu.
Check @Category.Instance.Rng.FreeMonad.System.Rng_system_nil.
Check @Category.Instance.Rng.FreeMonad.System.Rng_system_letter.
Check @Category.Instance.Rng.FreeMonad.System.Rng_system_pair.
