(** * Probe for the Kleisli comparison functor (issue #475)

    Pins the measured boundaries of what #475 adds for Mac Lane, §VI.5,
    "Free Algebras for a Monad", book pp. 147-148 (PDF pp. 156-157),
    catalog items maclane:VI.5:construction1, maclane:VI.5:thm2 and
    maclane:VI.5:ex1 to maclane:VI.5:ex3, read from the page images (the
    restriction of an adjunction to a full subcategory B containing every
    F x "defines in X the same monad as did the first"; Theorem 2, "there
    is a unique functor L : X_T → A with GL = G_T and LF_T = F"; the
    exercises: L, its uniqueness and its image FX, the equivalence
    X_T → FX, and an example where it is not an isomorphism), with the
    item the issue appends, Riehl's Lemma 5.2.14 (riehl:5.2:lem14,
    printed p. 194, PDF p. 214: "The canonical functor K : C_T → C^T from
    the Kleisli category to the Eilenberg–Moore category is full and
    faithful and its image consists of the free T-algebras").  The
    targets are Monad/Kleisli/Comparison.v (construction 1, Theorem 2,
    Exercises 1 and 2, Riehl's lemma and the biconditional) and
    Monad/Kleisli/Comparison/Examples.v (Exercise 3, and the
    biconditional's premise witnessed).  Their headers cite the
    refutations and controls here: Monad/Kleisli/Comparison.v R1 to R13,
    C1 to C34 and C36 to C42; Examples.v C35.  Each of the thirty-one
    [Example]s of the targets has a control that restates it
    independently of the constant that states it (RESTATEMENTS, below).

    THE IMPORT LIST, generated by a script over the [Require] lines.
    Target by target in dependency order: Monad/Kleisli/Comparison.v's
    twenty-five [Require] lines in its own order, and that target; the
    four lines Monad/Kleisli/Comparison/Examples.v adds, and that target.
    Thirty-one lines, all naming [Category] modules.  Under them
    [Print Libraries] in a scratch file loads fifty-six [Category]
    modules, exactly the set a [Require] of the two targets alone loads
    (compared by script).  A shorter import list is what makes a probe
    pass for no reason.

    DISCIPLINE.  Every negative other than the instrument is an
    [Example], never a [Check], so that an open evar cannot satisfy it.
    Each of the fourteen refutation lines (the instrument and R1 to R13)
    was stripped of its refutation keyword in a copy of this WHOLE file,
    one at a time, compiled, and its error read; each copy stops inside
    the stripped command (fourteen of fourteen, by the File line of its
    error, compared by script with the command's extent).  Each of the
    forty-two controls, wrapped in the refutation keyword in a copy of
    this WHOLE file, stops the build at that command with the message
    Rocq prints for a refutation whose command succeeds (forty-two of
    forty-two, by the same script).  Quotations are Rocq 9.1.1's under
    this file's import list and its local notations, with the error's
    environment block left out; Rocq prints the "cannot unify"
    parenthetical with the short names in scope.

    KINDS.  Fourteen refutations, counted as the lines that open with the
    refutation keyword: NAME-ABSENCE, the instrument (one); CONVERSION,
    [eq_refl] refused with a "cannot unify" parenthetical, every
    statement being well typed (R1, R3 to R6, R8 to R10, R12: nine); and
    TYPING (R2, R7, R11, R13: four), the statement itself refused because
    its two sides have different types (R2, R7), or a term because its
    type is not the one ascribed to it (R11, R13).  CAUSES.  Measured:
    every refutation still stops inside its command, and every control is
    still accepted, in a copy of the two targets and this file under a
    renamed logical root with all forty-eight [Qed]s of #475's code
    turned [Defined]; so none is the opacity of #475's own proofs.  Read
    from the terms: R4 to R6 compare expressions in the transposition of
    the adjunction, a section variable, that agree only by its laws; R9
    and R10 compare ret with id ∘ ret and μ with μ ∘ T id in a variable
    category, R12 μ ∘ T id with μ, and R8 the two Kleisli categories
    built on them; R1 and R3 compare records whose data agree (C1, C2,
    C5, C6) and whose proof fields differ; R2 and R7 compare terms of
    different types, the monad records over the two composite functors,
    and K with L at the Eilenberg–Moore resolution over the two Kleisli
    categories; R11 ascribes C^T to [EM_Comparison] at the Kleisli
    adjunction, whose codomain is the algebras of the monad that
    adjunction induces, and R13 ascribes the source C_T to L at the
    Kleisli resolution, whose source is the Kleisli category of that
    induced monad.

    LABELS.  The labels are not constants: each refutation and each
    control carries its label in a comment on the line above it, the
    instrument's reading "The instrument".  The constants are
    [p475_cN_…] and [p475_rN_…] for label CN or RN.

    RESTATEMENTS.  Monad/Kleisli/Comparison.v: [Restricted_monad_obj] C1,
    [Restricted_monad_map] C2, [Restricted_Monad_agrees_iso] C4,
    [Restricted_unit_agrees] C5, [Restricted_join_agrees] C6,
    [Restricted_Monad_iso_to] C8, [Restricted_Monad_iso_from] C9,
    [Kleisli_Comparison_obj] C10, [Kleisli_Comparison_map] C11,
    [Kleisli_Comparison_Forget_iso] C14,
    [Kleisli_Comparison_Forget_strict_obj] C15,
    [Kleisli_Comparison_Free_iso] C17,
    [Kleisli_Comparison_Free_strict_obj] C18,
    [Restricted_Left_Image_obj] C19, [Restricted_Left_Image_map] C20,
    [Kleisli_Comparison_Image_is_ImageTo_obj] C21,
    [Kleisli_Comparison_Image_is_ImageTo_map] C22,
    [Kleisli_Comparison_Image_incl_obj] C23,
    [Kleisli_Comparison_Image_incl_map] C24,
    [Kleisli_Comparison_Image_surjective_obj] C25, [Kleisli_EM_obj] C26,
    [Kleisli_EM_obj_free] C27, [Kleisli_EM_map] C28,
    [Kleisli_EM_Forget_map] C29, [Kleisli_EM_is_transpose] C30,
    [Kleisli_EM_is_comparison_obj] C31, [Kleisli_EM_is_comparison_map]
    C32, [EM_Comparison_Kleisli_obj] C36, [EM_Comparison_Kleisli_map]
    C37, [EM_Comparison_Kleisli_alg] C39.
    Monad/Kleisli/Comparison/Examples.v: [kleisli_point_monad_obj] C35,
    at [Sets] with its levels left to Rocq.  Thirty-one readbacks, each
    named once.  C3, C7, C12, C13, C16, C33, C34, C38, C40 and C41
    restate no readback: they are the twins of refutations, C3, C7, C12
    and C40 by the targets' own constants ([Restricted_Monad_agrees],
    [Restricted_Monad_iso], [Kleisli_Comparison_map_counit],
    [EM_Comparison_Kleisli_alg_join]), C13 and C16 the object halves of
    the triangles whose arrow halves R5 and R6 refuse, C33 and C34 the
    identities and composites of R9 and R10 at ≈, and C38 and C41 the
    types of the terms R11 and R13 refuse at other types.  C42 restates
    none either: it applies [Kleisli_Comparison_unique_of_strict] at
    L0 := L to the strict triangles L comes with, the coherence at
    [eq_refl], so that its hypotheses are shown satisfiable.

    THE REFUSALS, with the parenthetical each stripped copy prints.
      The instrument (NAME-ABSENCE): The reference p475_absent_name was
        not found in the current environment.
      R1, G_B F_B against G F as functor records (controls C1, C2; C3,
        ≈): (cannot unify "Restricted_Right G S ◯ Restricted_Left S full
        mem" and "G ◯ F")
      R2, the two monad records (TYPING; controls C5, C6): The term
        "Adjunction_Induced_Monad Adj" has type "Monad (G ◯ F)" while it
        is expected to have type "Monad (Restricted_Right G S ◯
        Restricted_Left S full mem)"
      R3, the two objects of [Monads X] (controls C7 to C9): (cannot
        unify "(Restricted_Right G S ◯ Restricted_Left S full mem;
        Adjunction_Induced_Monad (Restricted_Adjunction Adj S full mem))"
        and "(G ◯ F; Adjunction_Induced_Monad Adj)")
      R4, L f against ε ∘ F f (controls C11; C12, ≈): (cannot unify
        "fmap[Kleisli_Comparison Adj] f" and "counit ∘ fmap[F] f")
      R5, the arrow half of G L = G_T (controls C13 to C15): (cannot
        unify "fmap[G ◯ Kleisli_Comparison Adj] f" and
        "fmap[Kleisli_Forget] f")
      R6, the arrow half of L F_T = F (controls C16 to C18): (cannot
        unify "fmap[Kleisli_Comparison Adj ◯ Kleisli_Free] f" and
        "fmap[F] f")
      R7, K against L at the Eilenberg–Moore resolution (TYPING;
        controls C31, C32): The term "Kleisli_Comparison (EM_Adjunction
        T)" has type "KI ⟶ EilenbergMoore T" while it is expected to have
        type "KT ⟶ EilenbergMoore T"
      R8, their two source categories: (cannot unify "KT" and "KI")
      R9, the identities of the two (control C33, ≈): (cannot unify
        "id{KT}" and "id{KI}")
      R10, the composites of the two (control C34, ≈): (cannot unify
        "@compose (@Kleisli C T H) x y z f g" and "@compose (@Kleisli C
        (@Compose C (@EilenbergMoore C T H) C (@EM_Forget C T H)
        (@EM_Free C T H)) (@Adjunction_Induced_Monad (@EilenbergMoore C T
        H) C (@EM_Free C T H) (@EM_Forget C T H) (@EM_Adjunction C T H)))
        x y z f g")
      R11, [EM_Comparison] at the Kleisli adjunction typed into C^T
        (TYPING; controls C36 to C38): The term "EM_Comparison
        Kleisli_Adjunction" has type "KT ⟶ EilenbergMoore (Kleisli_Forget
        ◯ Kleisli_Free)" while it is expected to have type "KT ⟶
        EilenbergMoore T"
      R12, its structure map against μ (controls C39; C40, ≈): (cannot
        unify "t_alg[projT2 (fobj[EM_Comparison Kleisli_Adjunction] c)]"
        and "join[_]")
      R13, L at the Kleisli resolution of T typed as an endofunctor of
        C_T (TYPING; control C41): The term "Kleisli_Comparison
        Kleisli_Adjunction" has type "Kleisli ⟶ KT" while it is expected
        to have type "KT ⟶ KT"
    KT and KI are this file's local notations for the Kleisli categories
    of (T, η, μ) and of the monad [EM_Adjunction] induces; the bare
    Kleisli of R13 is the Kleisli category of the monad
    [Kleisli_Adjunction] induces.

    NOT PINNED HERE.  (a) [About] readbacks as such: the headers'
    universe censuses.  (b) The flips and copies described above, made
    in scratch copies.  (c) The closure of the targets under
    [Print Assumptions]: the Makefile's print-assumptions gate names the
    same one hundred and twenty-nine names as the guard below.  (d) The
    absences the headers record: an absence has no command.  (e) The
    readings of the books, from the page images and the PDF.  (f) The
    negations of Examples.v, which are theorems of that file, proved
    without an axiom, and not refusals.

    The guard block names the one hundred and twenty-nine names, so that
    a rename breaks this file: one hundred and ten of
    Monad/Kleisli/Comparison.v and nineteen of Examples.v.  They are
    exactly the entries [Print Module] gives for each new module, the
    twenty-six [Program] obligations among them.  Each is written fully
    qualified and with [@], so that no short name in scope can stand in
    for it. *)

Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Natural.Transformation.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Monad.
Require Import Category.Theory.Equivalence.
Require Import Category.Theory.Equivalence.FullFaithful.
Require Import Category.Theory.Equivalence.Adjoint.
Require Import Category.Theory.Equivalence.Strict.
Require Import Category.Theory.Skeleton.
Require Import Category.Construction.Quotient.
Require Import Category.Construction.Subcategory.
Require Import Category.Instance.Sets.
Require Import Category.Instance.StrictCat.
Require Import Category.Adjunction.Map.
Require Import Category.Adjunction.LeftInverse.
Require Import Category.Monad.Algebra.
Require Import Category.Monad.Eilenberg.Moore.
Require Import Category.Monad.Eilenberg.Moore.Adjunction.
Require Import Category.Monad.Comparison.
Require Import Category.Monad.Morphism.
Require Import Category.Monad.Kleisli.
Require Import Category.Monad.Kleisli.Adjunction.
Require Import Category.Monad.Kleisli.Comparison.
Require Import Category.Theory.Skeleton.Separation.
Require Import Category.Structure.Terminal.
Require Import Category.Structure.Initial.
Require Import Category.Instance.One.
Require Import Category.Monad.Kleisli.Comparison.Examples.

Generalizable All Variables.

(* ------------------------------------------------------------------------ *)
(** ** The instrument *)

(* The instrument *)
Fail Check p475_absent_name.

(* ------------------------------------------------------------------------ *)
(** ** Construction 1: the restricted adjunction and its monad *)

Section Restrict.

Context {X A : Category} {F : X ⟶ A} {G : A ⟶ X} (Adj : F ⊣ G).
Context (S : Subcategory A) (full : Full A S).
Context (mem : ∀ x : X, sobj A S (F x)).

(* C1: G_B F_B and G F agree on objects. *)
Example p475_c1_monad_obj (x : X) :
  fobj[Restricted_Right G S ◯ Restricted_Left S full mem] x = fobj[G ◯ F] x
  := eq_refl.

(* C2: ... and on arrows. *)
Example p475_c2_monad_map (x y : X) (f : x ~> y) :
  fmap[Restricted_Right G S ◯ Restricted_Left S full mem] f = fmap[G ◯ F] f
  := eq_refl.

(* R1 *)
Fail Example p475_r1_functors :
  Restricted_Right G S ◯ Restricted_Left S full mem = G ◯ F := eq_refl.

(* C3: the two composites are naturally isomorphic. *)
Definition p475_c3_functors_equiv :
  Restricted_Right G S ◯ Restricted_Left S full mem ≈ G ◯ F :=
  Restricted_Monad_agrees S full mem.

(* C4: ... by the identity at every object. *)
Example p475_c4_functors_equiv_iso (x : X) :
  `1 (Restricted_Monad_agrees S full mem) x = iso_id := eq_refl.

(* C5: η of the restricted monad is η. *)
Example p475_c5_unit (x : X) :
  @ret X (Restricted_Right G S ◯ Restricted_Left S full mem)
       (Adjunction_Induced_Monad (Restricted_Adjunction Adj S full mem)) x
    = @ret X (G ◯ F) (Adjunction_Induced_Monad Adj) x := eq_refl.

(* C6: μ of the restricted monad is μ. *)
Example p475_c6_join (x : X) :
  @join X (Restricted_Right G S ◯ Restricted_Left S full mem)
        (Adjunction_Induced_Monad (Restricted_Adjunction Adj S full mem)) x
    = @join X (G ◯ F) (Adjunction_Induced_Monad Adj) x := eq_refl.

(* R2 *)
Fail Example p475_r2_monad_records :
  Adjunction_Induced_Monad (Restricted_Adjunction Adj S full mem)
    = Adjunction_Induced_Monad Adj := eq_refl.

(* R3 *)
Fail Example p475_r3_monads_objects :
  ((Restricted_Right G S ◯ Restricted_Left S full mem;
    Adjunction_Induced_Monad (Restricted_Adjunction Adj S full mem))
     : Monads X)
    = (G ◯ F; Adjunction_Induced_Monad Adj) := eq_refl.

(* C7: the two monads are isomorphic in [Monads X]... *)
Definition p475_c7_monads_iso :
  ((Restricted_Right G S ◯ Restricted_Left S full mem;
    Adjunction_Induced_Monad (Restricted_Adjunction Adj S full mem))
     : Monads X)
    ≅ (G ◯ F; Adjunction_Induced_Monad Adj) :=
  Restricted_Monad_iso Adj S full mem.

(* C8: ... with the identity as every component of [to]... *)
Example p475_c8_monads_iso_to (x : X) :
  transform[mh_transform (to (Restricted_Monad_iso Adj S full mem))] x = id
  := eq_refl.

(* C9: ... and of [from]. *)
Example p475_c9_monads_iso_from (x : X) :
  transform[mh_transform (from (Restricted_Monad_iso Adj S full mem))] x
    = id := eq_refl.

End Restrict.

(* ------------------------------------------------------------------------ *)
(** ** Theorem 2: L by transposition, and its two triangles *)

Section Comparison.

Context {X A : Category} {F : X ⟶ A} {G : A ⟶ X} (Adj : F ⊣ G).

Notation T := (Adjunction_Induced_Monad Adj).
Notation XT := (@Kleisli X (G ◯ F) T).

(* C10: L x = F x. *)
Example p475_c10_obj (x : X) : fobj[Kleisli_Comparison Adj] x = F x
  := eq_refl.

(* C11: L f is the transpose of f. *)
Example p475_c11_map (x y : X) (f : x ~{XT}~> y) :
  fmap[Kleisli_Comparison Adj] f = from (@adj _ _ _ _ Adj x (F y)) f
  := eq_refl.

(* R4 *)
Fail Example p475_r4_map_counit (x y : X) (f : x ~{XT}~> y) :
  fmap[Kleisli_Comparison Adj] f = @counit _ _ _ _ Adj (F y) ∘ fmap[F] f
  := eq_refl.

(* C12: L f = ε ∘ F f up to ≈. *)
Definition p475_c12_map_counit (x y : X) (f : x ~{XT}~> y) :
  fmap[Kleisli_Comparison Adj] f ≈ @counit _ _ _ _ Adj (F y) ∘ fmap[F] f :=
  Kleisli_Comparison_map_counit Adj x y f.

(* C13: G L = G_T on objects. *)
Example p475_c13_forget_obj (x : X) :
  fobj[G ◯ Kleisli_Comparison Adj] x = fobj[@Kleisli_Forget X (G ◯ F) T] x
  := eq_refl.

(* R5 *)
Fail Example p475_r5_forget_map (x y : X) (f : x ~{XT}~> y) :
  fmap[G ◯ Kleisli_Comparison Adj] f = fmap[@Kleisli_Forget X (G ◯ F) T] f
  := eq_refl.

(* C14: G L ≈ G_T with the identity at every object. *)
Example p475_c14_forget_iso (x : X) :
  `1 (Kleisli_Comparison_Forget Adj) x = iso_id := eq_refl.

(* C15: G L = G_T strictly, with eq_refl at every object. *)
Example p475_c15_forget_strict_obj (x : X) :
  `1 (Kleisli_Comparison_Forget_strict Adj) x = eq_refl := eq_refl.

(* C16: L F_T = F on objects. *)
Example p475_c16_free_obj (x : X) :
  fobj[Kleisli_Comparison Adj ◯ @Kleisli_Free X (G ◯ F) T] x = fobj[F] x
  := eq_refl.

(* R6 *)
Fail Example p475_r6_free_map (x y : X) (f : x ~> y) :
  fmap[Kleisli_Comparison Adj ◯ @Kleisli_Free X (G ◯ F) T] f = fmap[F] f
  := eq_refl.

(* C17: L F_T ≈ F with the identity at every object. *)
Example p475_c17_free_iso (x : X) :
  `1 (Kleisli_Comparison_Free Adj) x = iso_id := eq_refl.

(* C18: L F_T = F strictly, with eq_refl at every object. *)
Example p475_c18_free_strict_obj (x : X) :
  `1 (Kleisli_Comparison_Free_strict Adj) x = eq_refl := eq_refl.

End Comparison.

(* ------------------------------------------------------------------------ *)
(** ** Exercise 1's image and Exercise 2 at FX *)

Section Image.

Context {X A : Category} {F : X ⟶ A} {G : A ⟶ X} (Adj : F ⊣ G).

Notation T := (Adjunction_Induced_Monad Adj).
Notation XT := (@Kleisli X (G ◯ F) T).

(* C19: F_B at B = FX is [ImageTo] on objects... *)
Example p475_c19_restricted_image_obj (x : X) :
  fobj[Restricted_Left (@LaliImageSub X A F) image_full
         (fun x => (x; eq_refl))] x
    = fobj[@ImageTo X A F] x := eq_refl.

(* C20: ... and on arrows. *)
Example p475_c20_restricted_image_map (x y : X) (f : x ~> y) :
  fmap[Restricted_Left (@LaliImageSub X A F) image_full
         (fun x => (x; eq_refl))] f
    = fmap[@ImageTo X A F] f := eq_refl.

(* C21: L' is [ImageTo] of L on objects... *)
Example p475_c21_image_is_imageto_obj (x : X) :
  fobj[Kleisli_Comparison_Image Adj] x
    = fobj[@ImageTo XT A (Kleisli_Comparison Adj)] x := eq_refl.

(* C22: ... and on arrows. *)
Example p475_c22_image_is_imageto_map (x y : X) (f : x ~{XT}~> y) :
  fmap[Kleisli_Comparison_Image Adj] f
    = fmap[@ImageTo XT A (Kleisli_Comparison Adj)] f := eq_refl.

(* C23: L = Incl ◯ L' on objects... *)
Example p475_c23_incl_obj (x : X) :
  fobj[Incl A (@LaliImageSub X A F) ◯ Kleisli_Comparison_Image Adj] x
    = fobj[Kleisli_Comparison Adj] x := eq_refl.

(* C24: ... and on arrows. *)
Example p475_c24_incl_map (x y : X) (f : x ~{XT}~> y) :
  fmap[Incl A (@LaliImageSub X A F) ◯ Kleisli_Comparison_Image Adj] f
    = fmap[Kleisli_Comparison Adj] f := eq_refl.

(* C25: the chosen preimage of (a; (x; e)) is x. *)
Example p475_c25_surjective_obj (y : Sub A (@LaliImageSub X A F)) :
  `1 (Kleisli_Comparison_Image_surjective Adj y) = `1 (`2 y).
Proof. destruct y as [a [x e]]; reflexivity. Qed.

End Image.

(* ------------------------------------------------------------------------ *)
(** ** Riehl, Lemma 5.2.14: K : C_T ⟶ C^T *)

Section Riehl.

Context {C : Category} (T : C ⟶ C) `{H : @Monad C T}.

Notation KT := (@Kleisli C T H).
Notation KI := (@Kleisli C (EM_Forget T ◯ EM_Free T)
                  (Adjunction_Induced_Monad (EM_Adjunction T))).

(* C26: K c = (T c, μ_c). *)
Example p475_c26_em_obj (c : C) :
  fobj[@Kleisli_EM C T H] c = (T c; {| t_alg := @join C T H c |}) := eq_refl.

(* C27: K c is the free algebra on c. *)
Example p475_c27_em_obj_free (c : C) :
  fobj[@Kleisli_EM C T H] c = fobj[EM_Free T] c := eq_refl.

(* C28: K f has underlying arrow μ ∘ T f. *)
Example p475_c28_em_map (x y : C) (f : x ~{KT}~> y) :
  t_alg_hom[fmap[@Kleisli_EM C T H] f] = join ∘ fmap[T] f := eq_refl.

(* C29: U^T K = U_T on arrows. *)
Example p475_c29_em_forget_map (x y : C) (f : x ~{KT}~> y) :
  fmap[EM_Forget T ◯ @Kleisli_EM C T H] f = fmap[@Kleisli_Forget C T H] f
  := eq_refl.

(* C30: K f is the transpose of f under F^T ⊣ U^T. *)
Example p475_c30_em_transpose (x y : C) (f : x ~{KT}~> y) :
  fmap[@Kleisli_EM C T H] f
    = from (@adj _ _ _ _ (EM_Adjunction T) x (EM_Free T y)) f := eq_refl.

(* C31: K and L at the Eilenberg-Moore resolution agree on objects... *)
Example p475_c31_em_is_l_obj (c : C) :
  fobj[@Kleisli_EM C T H] c = fobj[Kleisli_Comparison (EM_Adjunction T)] c
  := eq_refl.

(* C32: ... and on arrows. *)
Example p475_c32_em_is_l_map (x y : C) (f : x ~{KT}~> y) :
  fmap[@Kleisli_EM C T H] f = fmap[Kleisli_Comparison (EM_Adjunction T)] f
  := eq_refl.

(* R7 *)
Fail Example p475_r7_em_is_l :
  @Kleisli_EM C T H = Kleisli_Comparison (EM_Adjunction T) := eq_refl.

(* R8 *)
Fail Example p475_r8_kleisli_categories : KT = KI := eq_refl.

(* R9 *)
Fail Example p475_r9_kleisli_ids (c : C) : @id KT c = @id KI c := eq_refl.

(* C33: the two identities agree up to ≈. *)
Example p475_c33_kleisli_ids_equiv (c : C) : @id KT c ≈ @id KI c.
Proof. simpl. symmetry. exact (@EM_unit_agrees C T H c). Qed.

(* R10 *)
Fail Example p475_r10_kleisli_compose (x y z : C)
  (f : y ~> T z) (g : x ~> T y) :
  @compose KT x y z f g = @compose KI x y z f g := eq_refl.

(* C34: the two composites agree up to ≈. *)
Example p475_c34_kleisli_compose_equiv (x y z : C)
  (f : y ~> T z) (g : x ~> T y) :
  @compose KT x y z f g ≈ @compose KI x y z f g.
Proof. simpl. rewrite fmap_id, id_right. reflexivity. Qed.

End Riehl.

(* ------------------------------------------------------------------------ *)
(** ** Exercise 3: the one-point monad *)

(* C35: T S is the one-point set. *)
Example p475_c35_point_monad_obj (S : Sets) :
  fobj[PointAt (@terminal_obj Sets Sets_Terminal) ◯ Erase Sets] S
    = @terminal_obj Sets _ := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Riehl's K as her proof builds it, and L at the Kleisli resolution *)

Section RiehlEMComparison.

Context {C : Category} (T : C ⟶ C) `{H : @Monad C T}.

Notation KT := (@Kleisli C T H).

(* C36: EM_Comparison at the Kleisli adjunction forgets to K's functor on
   objects... *)
Example p475_c36_riehl_k_obj (c : C) :
  fobj[EM_Forget _ ◯ EM_Comparison (@Kleisli_Adjunction C T H)] c
    = fobj[EM_Forget T ◯ @Kleisli_EM C T H] c := eq_refl.

(* C37: ... and on arrows. *)
Example p475_c37_riehl_k_map (x y : C) (f : x ~{KT}~> y) :
  fmap[EM_Forget _ ◯ EM_Comparison (@Kleisli_Adjunction C T H)] f
    = fmap[EM_Forget T ◯ @Kleisli_EM C T H] f := eq_refl.

(* R11 *)
Fail Example p475_r11_riehl_k_codomain : KT ⟶ EilenbergMoore T :=
  EM_Comparison (@Kleisli_Adjunction C T H).

(* C38: its codomain is the algebras of the monad the Kleisli adjunction
   induces. *)
Example p475_c38_riehl_k_codomain :
  KT ⟶ @EilenbergMoore C (@Kleisli_Forget C T H ◯ @Kleisli_Free C T H)
         (Adjunction_Induced_Monad (@Kleisli_Adjunction C T H)) :=
  EM_Comparison (@Kleisli_Adjunction C T H).

(* C39: its structure map at c is μ ∘ T id. *)
Example p475_c39_riehl_k_alg (c : C) :
  t_alg[`2 (fobj[EM_Comparison (@Kleisli_Adjunction C T H)] c)]
    = @join C T H c ∘ fmap[T] (@id C (T c)) := eq_refl.

(* R12 *)
Fail Example p475_r12_riehl_k_alg_join (c : C) :
  t_alg[`2 (fobj[EM_Comparison (@Kleisli_Adjunction C T H)] c)]
    = @join C T H c := eq_refl.

(* C40: the structure map is μ up to ≈. *)
Definition p475_c40_riehl_k_alg_join (c : C) :
  t_alg[`2 (fobj[EM_Comparison (@Kleisli_Adjunction C T H)] c)]
    ≈ @join C T H c := EM_Comparison_Kleisli_alg_join T c.

(* R13 *)
Fail Example p475_r13_l_at_kleisli : KT ⟶ KT :=
  Kleisli_Comparison (@Kleisli_Adjunction C T H).

(* C41: L at the Kleisli resolution of T goes out of the Kleisli category of
   the monad that resolution induces. *)
Example p475_c41_l_at_kleisli :
  @Kleisli C (@Kleisli_Forget C T H ◯ @Kleisli_Free C T H)
      (Adjunction_Induced_Monad (@Kleisli_Adjunction C T H)) ⟶ KT :=
  Kleisli_Comparison (@Kleisli_Adjunction C T H).

End RiehlEMComparison.

(* ------------------------------------------------------------------------ *)
(** ** Uniqueness from the strict triangles *)

Section UniqueStrict.

Context {X A : Category} {F : X ⟶ A} {G : A ⟶ X} (Adj : F ⊣ G).

(* C42: the strict triangles L delivers satisfy the hypotheses of
   [Kleisli_Comparison_unique_of_strict] at L0 := L, coh at eq_refl. *)
Definition p475_c42_unique_of_strict_at_l :
  @equiv _ (@Functor_StrictEq_Setoid _ A) (Kleisli_Comparison Adj)
    (Kleisli_Comparison Adj) :=
  Kleisli_Comparison_unique_of_strict Adj (Kleisli_Comparison Adj)
    (Kleisli_Comparison_Free_strict Adj)
    (Kleisli_Comparison_Forget_strict Adj) (fun x => eq_refl).

End UniqueStrict.

(* ------------------------------------------------------------------------ *)
(** ** Guard: every constant of the two targets, by name *)

Check @Category.Monad.Kleisli.Comparison.Restricted_Left_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Restricted_Left_obligation_2.
Check @Category.Monad.Kleisli.Comparison.Restricted_Left_obligation_3.
Check @Category.Monad.Kleisli.Comparison.Restricted_Left.
Check @Category.Monad.Kleisli.Comparison.Restricted_Right.
Check @Category.Monad.Kleisli.Comparison.Restricted_adj_iso_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Restricted_adj_iso_obligation_2.
Check @Category.Monad.Kleisli.Comparison.Restricted_adj_iso_obligation_3.
Check @Category.Monad.Kleisli.Comparison.Restricted_adj_iso_obligation_4.
Check @Category.Monad.Kleisli.Comparison.Restricted_adj_iso.
Check @Category.Monad.Kleisli.Comparison.Restricted_Adjunction.
Check @Category.Monad.Kleisli.Comparison.Restricted_monad_obj.
Check @Category.Monad.Kleisli.Comparison.Restricted_monad_map.
Check @Category.Monad.Kleisli.Comparison.Restricted_unit_agrees.
Check @Category.Monad.Kleisli.Comparison.Restricted_join_agrees.
Check @Category.Monad.Kleisli.Comparison.Restricted_Monad_agrees.
Check @Category.Monad.Kleisli.Comparison.Restricted_Monad_agrees_iso.
Check @Category.Monad.Kleisli.Comparison.Restricted_Monad_to.
Check @Category.Monad.Kleisli.Comparison.Restricted_Monad_from.
Check @Category.Monad.Kleisli.Comparison.Restricted_Monad_iso.
Check @Category.Monad.Kleisli.Comparison.Restricted_Monad_iso_to.
Check @Category.Monad.Kleisli.Comparison.Restricted_Monad_iso_from.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_fmap_id.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_fmap_comp.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_obligation_2.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_obligation_3.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_obj.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_map.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_map_counit.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Forget.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Forget_iso.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Free.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Free_iso.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Forget_strict.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Forget_strict_obj.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Free_strict.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Free_strict_obj.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Full_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Full.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Faithful_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Faithful.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_unique_map.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_unique.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_unique_strict.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_unique_of_strict.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Squares_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Squares_obligation_2.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Squares.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Squares_unit.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Map.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Squares_of.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Squares_of_unit.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_unique_via_map.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Restrict_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Restrict_obligation_2.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Restrict_obligation_3.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Restrict.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Restrict_Full_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Restrict_Full.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Restrict_Faithful_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Restrict_Faithful.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Restrict_ESO.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Restrict_Equivalence.
Check @Category.Monad.Kleisli.Comparison.Restricted_Left_Image_obj.
Check @Category.Monad.Kleisli.Comparison.Restricted_Left_Image_map.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_is_ImageTo_obj.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_is_ImageTo_map.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_incl_obj.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_incl_map.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_surjective.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_surjective_obj.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_pick.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_Equivalence.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_AdjointEquivalence.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_injective.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_inv_left.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_inv_right_obj.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_inv_right.
Check @Category.Monad.Kleisli.Comparison.Kleisli_Comparison_Image_StrictIso.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_obligation_2.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_obligation_3.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_obj.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_obj_free.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_map.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_Forget_map.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_is_transpose.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_Full_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_Full.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_Faithful_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_Faithful.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_Image.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_Image_Full_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_Image_Full.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_Image_Faithful_obligation_1.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_Image_Faithful.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_Image_surjective.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_Image_Equivalence.
Check @Category.Monad.Kleisli.Comparison.EveryAlgebraFree.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_equivalence_iff.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_is_comparison_obj.
Check @Category.Monad.Kleisli.Comparison.Kleisli_EM_is_comparison_map.
Check @Category.Monad.Kleisli.Comparison.EM_Comparison_Kleisli_obj.
Check @Category.Monad.Kleisli.Comparison.EM_Comparison_Kleisli_map.
Check @Category.Monad.Kleisli.Comparison.EM_Comparison_Kleisli_alg.
Check @Category.Monad.Kleisli.Comparison.EM_Comparison_Kleisli_alg_join.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_FX.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_FX_full.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_FX_skeletal.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_adj.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_monad_obj.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_empty.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_one.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_distinct.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_F_not_injective.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_L_not_injective.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_surjective.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_equivalence.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_not_skeletal.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_not_iso.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_FX_pick.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_FX_equivalence.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_FX_not_iso.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_every_algebra_free.
Check @Category.Monad.Kleisli.Comparison.Examples.kleisli_point_K_equivalence.
