(** * Probe for morphisms of monads and θ* (issue #468)

    Pins the measured boundaries of the six files #468 adds for Mac Lane,
    §VI.2, Exercise 3, book p. 142 (PDF p. 151), catalog item
    maclane:VI.2:ex3, read from the page image: "(a) For monads
    ⟨T, η, μ⟩ and ⟨T', η', μ'⟩ on X, define a morphism θ of monads as a
    suitable natural transformation θ : T ⇝ T', and construct the category
    of all monads in X.  (b) From θ construct a functor θ* : X^{T'} → X^T
    such that G^T ∘ θ* = G^{T'} and a natural transformation
    F^T ⇝ θ* ∘ F^{T'}."  The files are Monad/Morphism.v (part (a):
    [MonadHom] and the category [Monads C]), Monad/Morphism/Algebra.v
    (part (b): θ*, its readbacks and its functoriality in θ),
    Monad/Morphism/Monoid.v (Mac Lane's own reading of "the category of
    all monads" as Mon_{X^X}, pp. 138 and 171), Monad/Morphism/
    Transformer.v (the transformer laws of Monad/Transformer.v as a
    morphism of monads), and the two bridges Instance/Fun/Action/Monad/BG/
    Morphism.v (#464's two monads) and Instance/SupLat/Free/Morphism.v
    (#466's).  Their headers cite the refutations and controls here:
    Morphism.v R6 and R18; Algebra.v R1 to R5 with R2a, R2b and R2c;
    Monoid.v R7 to R9; Transformer.v R10 and R11; the #464 bridge R12 to
    R14; the #466 bridge R15 to R17.  Each of the fifty-two [Example]s of
    the six targets, all proved by [eq_refl], has a control that restates
    it at the same generality and independently of the constant that
    states it (RESTATEMENTS, below).
    CORRECTION (#1347): R12, R14, R15 and R16 now hold at [eq_refl],
    since Instance/Sets.v gives its identity's and composite's properness
    fields as terms; they are controls, and keep their labels.

    THE IMPORT LIST, generated by a script over the [Require] lines.
    Target by target in dependency order: Monad/Morphism.v's six
    [Require] lines in its own order, and that target; the six lines
    Monad/Morphism/Algebra.v adds (Theory/Isomorphism.v, Monad/Algebra.v,
    Monad/Eilenberg/Moore.v, Monad/Eilenberg/Moore/Adjunction.v,
    Construction/Opposite.v and Instance/Cat.v), and that target; the
    seven lines Monad/Morphism/Monoid.v adds (Functor/Bifunctor.v,
    Structure/Monoidal.v, Structure/Monoidal/Compose.v,
    Theory/Algebra/Monoid.v, Theory/Algebra/Monoid/Hom.v,
    Theory/Equivalence.v and Theory/Equivalence/FullFaithful.v), and that
    target; the one line Monad/Morphism/Transformer.v adds
    (Monad/Transformer.v), and that target; the four lines the #464
    bridge adds (Construction/Deloop.v, Instance/Sets.v,
    Instance/Fun/Action/Monad.v and Instance/Fun/Action/Monad/BG.v), and
    that target; the four lines the #466 bridge adds
    (Instance/Sets/Powerset.v, Instance/Sets/Powerset/Monad.v,
    Instance/SupLat.v and Instance/SupLat/Free.v), and that target.
    Thirty-four lines, all naming [Category] modules.  Under them
    [Print Libraries] in a scratch file loads one hundred and thirty-five
    [Category] modules, exactly the union of the six targets' dependency
    closures (compared by script with the closure of their [Require]
    lines).  Two more lines, Monad/Monoid.v and
    Theory/Algebra/Monoid/Product.v, are loaded at the end of this file,
    after every other command, the guard block included, for control C40
    alone, which measures a route the targets do not take; with them the
    count is one hundred and thirty-seven.
    CORRECTION (#1348): the targets take that route now, Monad/Morphism/Monoid.v
    requiring both modules, so the 34 import lines alone load the one hundred
    and thirty-seven, and the two lines at the end load no further module; they
    still bring the two modules' names into scope for C40.
    A shorter import list is what
    makes a probe pass for no reason.

    NAMES.  The probe binds a second and a third monad as T2, M2 and T3,
    M3, further objects of [Monads C] as N2 and N3, and a second morphism
    as θ2, where the headers write T', M', T'', M'', N', N'' and θ'; the
    quotations are as Rocq prints them under the probe's names.

    DISCIPLINE.  Every negative is an [Example] or a [Definition], never a
    [Check], so that an open evar cannot satisfy it.  Each of the
    twenty-one refutation lines was stripped of its refutation keyword in
    a copy of this WHOLE file, one at a time, compiled, and its error
    read; each copy stops inside the stripped command (twenty-one of
    twenty-one, by the File line of its error, compared by script with
    the command's extent).  Each of the sixty-three controls, wrapped in
    the refutation keyword in a copy of this WHOLE file, stops the build
    at that command with the message Rocq prints for a refutation whose
    command succeeds (sixty-three of sixty-three, by the same script).
    Quotations are Rocq 9.1.1's under this file's import list, with the
    error's environment block left out; Rocq prints the "cannot unify"
    parenthetical with the short names in scope.  The six targets and this
    file also compile on Coq 8.19.2 and 8.20.1, with no warning from any of
    them, overlaid on copies of the dependency closure whose one hundred and
    thirty-seven sources are this tree's byte for byte (compared by [cmp]).
    Each of the twenty-one stripped copies is refused there inside the
    stripped command with the Rocq 9.1.1 error, environment block included
    (compared by script), and every wrapped control reports there that its
    command succeeded (sixty-three of sixty-three on each version).
    CORRECTION (#1347): R12, R14, R15 and R16 are controls now.  Each,
    wrapped in the refutation keyword in a copy of this WHOLE file, stops
    the build at that command with that message, so the controls are
    sixty-seven.  The refutation lines are seventeen, and each, stripped
    in a copy of this WHOLE file, stops inside its command with the error
    it printed before #1347 (compared by script, universe serial names
    aside).  Both measurements on Rocq 9.1.1 only; the older versions were
    not re-run.

    KINDS.  Twenty-one refutations, counted as the lines that open with
    the refutation keyword: TYPING, a statement that is itself ill-typed
    (R1: one); and CONVERSION, [eq_refl] refused with a "cannot unify"
    parenthetical, every statement being well typed (the other twenty).
    Each CONVERSION refusal also has a CAUSE.  STRUCTURAL: the two sides
    reduce to different terms, or to stuck projections of variable data,
    and no measured flip of the tree changes that (R2 to R11 with R2a,
    R2b and R2c, R13, R17 and R18; every flip kept the [Qed]s of
    Instance/Sets.v and three other files, so for R13 and R17, which
    pass through Instance/Sets.v's opaque
    [setoid_morphism_compose_respects], the label is argued from the
    terms, not measured further).  STDLIB OPACITY: the residue is an opaque
    constant of the standard library, which no flip of the tree reaches
    (R12, R14, R15 and R16, of the kind of Test/ProbeGroupAction464.v's
    N3 and Test/ProbeSupLat466.v's F1).
    CORRECTION (#1347): R12, R14, R15 and R16 now hold at [eq_refl] and
    are controls, so the refutations are seventeen, R1 TYPING and sixteen
    CONVERSION, every one of these STRUCTURAL.  Their classification,
    STDLIB OPACITY, was right: TERMS, below, is now the tree, and the N3
    and the F1 named above hold too.

    THE FLIPS.  Measured on the builders' drafts of the six files by
    #468's two builders and, again, by their two reviewers, each in
    copies of their own.  For R2 to R6: a copy of the twenty-seven-file
    closure of Monad/Morphism.v and Monad/Morphism/Algebra.v with every
    [Qed] turned into [Defined] and [Transparent Obligations] set,
    Instance/Sets.v keeping its [Qed]s, where that change is itself
    refused with "Universe ... is unbound"; there the obligations of
    [EM_Forget], [EilenbergMoore] and [nat_id] report "is transparent",
    which in the tree report "is opaque", and each of R2 to R6 with R2a,
    R2b and R2c stands with the text of the tree.  R18 was measured the
    same way by #468's fold, in the first reviewer's copy, where
    Theory/Natural/Transformation.v's [nat_compose_obligation_1] reports
    "is transparent" (and "is opaque" in the tree): it stands there with
    the text of the tree.  For R7 to R17, four copies of the 135-module
    closure.  FLIP: every [Qed] turned into [Defined] and [Transparent
    Obligations] set, but in Instance/Sets.v, Structure/Cartesian/
    Closed.v, Instance/Grp.v and Instance/Grp/Free.v (#464's
    accommodations); the instrument is that [Compose_Monoidal_obligation_1],
    [MonoidHom_id], [mh_join_nat], [lift_natural], [Powerset_Prop_map_id],
    [SL_induced_join_equiv] and [nat_compose_obligation_1] report "is
    transparent" there and "is opaque" in the tree.  TERMS: no [Qed]
    changed, and Instance/Sets.v's [setoid_morphism_id] and
    [setoid_morphism_compose] given their properness fields as the terms
    fun _ _ H => H and fun a b H => proper_morphism g _ _
    (proper_morphism f a b H) (the change #466 measured for its F1); the
    fields they replace are built from the CMorphisms lemmas
    [Reflexive_partial_app_morphism], [proper_proper_proxy],
    [subrelation_id_proper] and [subrelation_refl], opaque in the tree
    and in every copy.  FLIP+TERMS: both changes.  And TERMS with one of
    the two fields alone, each way.  In each copy every refutation was
    tested alone.  The STRUCTURAL ones stand in all four copies with the
    texts of the tree; the STDLIB OPACITY ones stand in the tree, in FLIP
    and in TERMS with either field alone, and HOLD at [eq_refl] in TERMS
    and in FLIP+TERMS: each compares h ∘ id in Sets with h.  R13 and R17
    compare whole algebras; in FLIP+TERMS, where carriers and structure
    maps convert, the unit law [t_id] and the action law [t_action] are
    each refused alone, for #464's monads and for #466's.  The fold then
    turned four [Qed]s of Monad/Morphism/Algebra.v into [Defined]
    ([mh_EM_forget], [mh_EM_respects], [mh_EM_id], [mh_EM_compose]) and
    added constants to Monad/Morphism.v, Algebra.v and the #466 bridge,
    so #468's Stage-2 verifier measured the causes again on the fold's
    final versions of the six files, in its own copies of the second
    reviewer's FLIP, TERMS and FLIP+TERMS trees with those files
    installed ([Qed] turned into [Defined] in the two flipped trees) and
    each tree rebuilt.  The instrument: [nat_compose_obligation_1],
    [EM_Forget_obligation_1], [Compose_Monoidal_obligation_1],
    [mh_join_nat], [lift_natural], [SL_induced_join_equiv] and
    [Powerset_Prop_map_id] report "is transparent" in FLIP and in
    FLIP+TERMS and "is opaque" in the tree.  Each refutation was tested
    alone, the other twenty removed, in each tree.  In FLIP all twenty-one
    are refused, R18 among them, each with the text of the tree; in TERMS
    and in FLIP+TERMS exactly R12, R14, R15 and R16 hold at [eq_refl],
    and the other seventeen are refused with the texts of the tree.
    #468's second fold compiled the twenty-one isolated copies again
    against each of the verifier's three trees, and the instrument, and
    read the same results; its own edits to the six files changed
    comments only.
    CORRECTION (#1347): TERMS is now the tree.  In it R12, R14, R15 and
    R16 hold at [eq_refl] and the other seventeen are refused with the
    texts they printed before #1347, as these copies found; "stand in the
    tree" above describes the tree before #1347.

    LABELS.  The labels are not constants: each refutation and each control
    carries its label in a comment on the line above it.  The first
    builder's draft keeps C1 to C18 and R1 to R6 with R2a, R2b and R2c; the
    second builder's keeps C19 to C36 and R7 to R17.  The fold adds C37 and
    R18 (the first review's finding on the composition law of
    [Monads_Forget]), C38 and C39 (the second review's pins of the two
    [exact] bridges), C40 (the second review's measurement of the route
    through Monad/Monoid.v), C41 to C44 (the identity isomorphisms of the
    four constants it made [Defined]) and C45 (the inverse morphism it added
    to the #466 bridge).  The second fold adds C46 to C62, the seventeen
    readbacks of the targets that #468's Stage-2 verifier found with no
    control, adapted from the verifier's restatements to this file's names
    and binders, and C63, [mh_EM_alg] at a variable morphism, which C15, C16
    and C32 state only at particular ones; and it widens C41 to C44, which
    had restated the leg [to] alone, to both legs.  C1 is
    [p468_c1_hcompose], C2 [p468_c2_equiv], C3 [p468_c3_id_components], C4
    [p468_c4_fun_id], C5 [p468_c5_book_type], C6 [p468_c6_free_type], C7
    [p468_c7_forget_obj], C8 [p468_c8_forget_obj_fun], C9
    [p468_c9_forget_map], C10 [p468_c10_fobj_field], C11
    [p468_c11_fmap_field], C12 [p468_c12_strict_obj], C13
    [p468_c13_free_forget], C14 [p468_c14_id_carrier], C15
    [p468_c15_id_alg], C16 [p468_c16_comp_alg], C17 [p468_c17_comp_hom], C18
    [p468_c18_transpose_arrow], C19 [p468_c19_bimap], C20
    [p468_c20_hom_mu_type], C21 [p468_c21_mon_id_left], C22
    [p468_c22_mon_id_right], C23 [p468_c23_mon_comp], C24
    [p468_c24_monad_round], C25 [p468_c25_monoid_round], C26
    [p468_c26_trans_round], C27 [p468_c27_hom_round], C28
    [p468_c28_bg_carrier], C29 [p468_c29_bg_alg_fun], C30 [p468_c30_bg_hom],
    C31 [p468_c31_bg_orig_alg], C32 [p468_c32_bg_alg_compose], C33
    [p468_c33_actbg_alg_fun], C34 [p468_c34_sl_alg_fun], C35
    [p468_c35_sl_parts], C36 [p468_c36_sl_map], C37 [p468_c37_forget_comp],
    C38 [p468_c38_hom_mu_term], C39 [p468_c39_mh_join_term], C40
    [p468_c40_monoid_route], C41 [p468_c41_forget_iso], C42
    [p468_c42_id_iso], C43 [p468_c43_comp_iso], C44 [p468_c44_respects_iso],
    C45 [p468_c45_sl_inv_component], C46 [p468_c46_mforget_obj], C47
    [p468_c47_mforget_map], C48 [p468_c48_em_obj], C49 [p468_c49_em_map],
    C50 [p468_c50_monoid_mu], C51 [p468_c51_monoid_eta], C52
    [p468_c52_hom_eta_type], C53 [p468_c53_mh_transform], C54
    [p468_c54_mon_obj], C55 [p468_c55_mon_map], C56 [p468_c56_trans_lift],
    C57 [p468_c57_hom_lift], C58 [p468_c58_bg_component], C59
    [p468_c59_bg_inv_component], C60 [p468_c60_actbg_carrier], C61
    [p468_c61_sl_component], C62 [p468_c62_sl_carrier] and C63
    [p468_c63_alg].  R1 is [p468_r1_issue_direction], R2
    [p468_r2_forget_eq], R2a [p468_r2a_fmap_respects], R2b
    [p468_r2b_fmap_id], R2c [p468_r2c_fmap_comp], R3 [p468_r3_id_obj], R4
    [p468_r4_comp_obj], R5 [p468_r5_transpose], R6 [p468_r6_forget_id], R7
    [p468_r7_mon_id], R8 [p468_r8_monad_round], R9 [p468_r9_monoid_round],
    R10 [p468_r10_trans_round], R11 [p468_r11_hom_round], R12
    [p468_r12_bg_alg], R13 [p468_r13_bg_obj], R14 [p468_r14_actbg_alg], R15
    [p468_r15_sl_alg], R16 [p468_r16_sl_sup], R17 [p468_r17_sl_obj] and R18
    [p468_r18_forget_comp].
    CORRECTION (#1347): R12, R14, R15 and R16 are controls now and keep
    these labels and names.

    RESTATEMENTS.  A control restates a readback when the two are the same
    statement under this file's names, the control perhaps pairing it with
    another, or agree once the functors and categories they name are
    unfolded, over the same variables.  Monad/Morphism.v: [mh_join_hcompose]
    C1, [mh_id_component] C3, [mh_compose_component] and
    [Monads_Forget_comp_component] C37, [Monads_equiv_is_Fun_equiv] C2,
    [Monads_Forget_obj] C46 and [Monads_Forget_map] C47.
    Monad/Morphism/Algebra.v: [mh_EM_carrier] and [mh_EM_forget_obj] C7,
    [mh_EM_forget_obj_fun] C8, [mh_EM_hom] and [mh_EM_forget_map] C9,
    [mh_EM_alg] C63, [mh_EM_forget_iso_id] C41, [mh_EM_free_forget] C13,
    [mh_EM_id_iso_id] C42, [mh_EM_compose_iso_id] C43,
    [mh_EM_respects_iso_id] C44, [Monads_EM_obj] C48 and [Monads_EM_map]
    C49.  Monad/Morphism/Monoid.v: [monad_monoid_mu] C50, [monad_monoid_eta]
    C51, [monoid_monad_ret] and [monoid_monad_join] C24,
    [monad_monoid_mu_round] and [monad_monoid_eta_round] C25,
    [mh_bimap_component] C19, [mh_join_is_hom_mu] C20, [mh_ret_is_hom_eta]
    C52, [monoidhom_mh_transform] C53, [Monads_Mon_obj] C54 and
    [Monads_Mon_map] C55.  Monad/Morphism/Transformer.v:
    [transformer_hom_lift] C56, [hom_transformer_lift] C57,
    [transformer_round_trip] C26 and [hom_round_trip] C27.  The #464 bridge:
    [BG_theta_component] C58, [BG_theta_inv_component] C59,
    [BG_theta_EM_carrier] C28, [BG_theta_EM_alg_fun] C29, [BG_theta_EM_hom]
    C30, [Act_BG_EM_carrier] C60 and [Act_BG_EM_alg_fun] C33.  The #466
    bridge: [SL_theta_component] C61, [SL_theta_alg_fun] (at the algebra of
    a variable object) and [SL_EM_theta_alg_fun] C34,
    [SL_theta_inv_component] C45, [SL_EM_theta_carrier] C62,
    [SL_factor_set], [SL_factor_le] and [SL_factor_sup_fun] C35, and
    [SL_factor_map] C36.  Fifty-two readbacks, each named once.

    ** Part (a): Monad/Morphism.v

    Controls, at [eq_refl]: the right factor of [mh_join] is
    [nat_hcompose θ θ] at x (C1); the ≈ of [Monads C] is the ≈ of [C, C]
    on [mh_transform] (C2); the identity of [Monads C] has components [id]
    (C3), the identity of [C, C] components [fmap[T] id] (C4);
    [Monads_Forget] is the first projection on objects and [mh_transform]
    on arrows (C46, C47); its composition law holds at each component
    (C37).
    R6 (CONVERSION, STRUCTURAL).  [Monads_Forget] on an identity, against
    the identity of [C, C], at a component:
      (cannot unify "fmap[Monads_Forget C] id{Monads C} x" and
      "id{[C, C]} x")
    R18 (CONVERSION, STRUCTURAL).  The composition law of
    [Monads_Forget] between whole transformations, whose naturality
    proofs differ:
      (cannot unify "fmap[Monads_Forget C] (φ ∘ θ)" and
      "fmap[Monads_Forget C] φ ∘ fmap[Monads_Forget C] θ")

    ** Part (b): the direction

    Controls: the page's direction F^T ⇝ θ* ∘ F^{T'} is a well-formed
    type (C5), and [mh_EM_free θ] inhabits it (C6).
    R1 (TYPING).  The issue body's direction, "F^{T'} ⇒ θ* ∘ Fᵀ":
      The term "EM_Free T" has type "C ⟶ EilenbergMoore T" while it is
      expected to have type "C ⟶ EilenbergMoore T2" (cannot unify
      "EilenbergMoore T" and "EilenbergMoore T2").

    ** Part (b): G^T ∘ θ* = G^{T'}

    Controls, at [eq_refl]: G^T ∘ θ* against G^{T'} on objects (C7), as a
    function of the object (C8) and on arrows (C9); the two data fields of
    the two functors, as record fields (C10, C11); the object equation of
    [mh_EM_forget_strict] IS [eq_refl] (C12); both legs of the isomorphism
    of [mh_EM_forget] at an algebra are [id] (C41).
    R2 (CONVERSION, STRUCTURAL).  The functor equation G^T ∘ θ* = G^{T'}:
      (cannot unify "EM_Forget T ◯ mh_EM θ" and "EM_Forget T2")
    R2a, R2b, R2c (CONVERSION, STRUCTURAL).  Its three proof fields, one
    at a time:
      (cannot unify "@fmap_respects _ _ (@EM_Forget C T M ◯ @mh_EM C T T2
      M M2 θ)" and "@fmap_respects _ _ (@EM_Forget C T2 M2)")
      (cannot unify "@fmap_id _ _ (EM_Forget T ◯ mh_EM θ)" and
      "@fmap_id _ _ (EM_Forget T2)")
      (cannot unify "@fmap_comp _ _ (EM_Forget T ◯ mh_EM θ)" and
      "@fmap_comp _ _ (EM_Forget T2)")

    ** Part (b): F^T ⇝ θ* ∘ F^{T'}

    Controls: each component of F^T ⇝ θ* ∘ F^{T'} is θ_x under G^T
    (C13); the underlying arrow of the transpose of η'_x is
    (μ'_x ∘ θ_{T'x}) ∘ T(η'_x) (C18).
    R5 (CONVERSION, STRUCTURAL).  That transpose against θ_x:
      (cannot unify "t_alg_hom[EM_extend T ret[_]]" and
      "mh_transform θ x")

    ** Part (b): functoriality in θ

    Controls: θ* writes a structure map h' as h' ∘ θ_a (C63); (id)*
    keeps the carrier (C14) and writes h ∘ id (C15); (φ ∘ θ)* writes
    h ∘ (φ ∘ θ) (C16) and keeps underlying arrows as θ* ◯ φ* does (C17);
    both legs of the isomorphisms of (id)* ≈ Id, of (φ ∘ θ)* ≈ θ* ◯ φ*
    and of θ* ≈ θ2* have underlying arrow [id] (C42, C43, C44);
    [Monads_EM] sends a monad to its Eilenberg–Moore category and a
    morphism θ to θ* (C48, C49).
    R3 (CONVERSION, STRUCTURAL).  (id)* on an object, against the object:
      (cannot unify "fobj[mh_EM (mh_id M)] X" and "X")
    R4 (CONVERSION, STRUCTURAL).  (φ ∘ θ)* on an object, against
    θ* ◯ φ*:
      (cannot unify "fobj[mh_EM (mh_compose φ θ)] X" and
      "fobj[mh_EM θ ◯ mh_EM φ] X")

    ** Monad/Morphism/Monoid.v

    Controls, at [eq_refl]: the tensor of [Compose_Monoidal] on (θ, θ) is
    θ_{T2 x} ∘ T(θ_x) at x (C19); the type of [mh_join] is the type of
    the multiplication square of a monoid homomorphism (C20), and the
    type of [mh_ret] that of the unit triangle (C52); the square of
    [mh_monoidhom θ] IS [mh_join θ] and the [mh_join] of
    [monoidhom_mh θ H] IS the square of H, as proof terms (C38, C39);
    [monoidhom_mh θ H] has the transformation θ itself (C53);
    [Monads_Mon] on objects and on arrows (C54, C55); [Monads_Mon] on an
    identity has components [id] (C21); the identity of [Mon [C, C]] has
    components fmap[T] id (C22); [Monads_Mon] on a composite has the
    components of the composite of the images (C23).
    R7 (CONVERSION, STRUCTURAL).  The identity law, at a component:
      (cannot unify "projT1 (fmap[Monads_Mon C] id{Monads C}) x" and
      "projT1 id{Mon ([C, C])} x")
    Controls: μ and η of monad_monoid M are [join] and [ret] at x (C50,
    C51); the unit and multiplication of monoid_monad (monad_monoid M)
    are M's (C24); μ and η of monad_monoid (monoid_monad N) are N's at x
    (C25).
    R8 (CONVERSION, STRUCTURAL).  The monad round trip, whole:
      (cannot unify "monoid_monad (monad_monoid M)" and "M")
    R9 (CONVERSION, STRUCTURAL).  The monoid round trip, whole:
      (cannot unify "monad_monoid (monoid_monad N)" and "N")
    Control, at the end of this file under its two extra lines: the route
    through Monad/Monoid.v's [Monoid_Monad] and
    Theory/Algebra/Monoid/Product.v's conversions has μ and η equal to
    [monad_monoid]'s, and its round trip keeps [ret] (C40).  Its binder
    alone ends its universe list with [+]: [Monoid_Monad] has four universes
    on Rocq 9.1.1 and twenty-six on Coq 8.19.2 ([About] on each), and 8.19
    and 8.20 refuse an instance of four ("Universe instance length is 4 but
    should be 26"), so no fixed instance serves the three versions.
    CORRECTION (#1348): the route is taken.  [monad_monoid] and
    [monoid_monad] are now that composite, so C40 holds by unfolding
    [monad_monoid], and #1348 rewrote [Monoid_Monad] so that it has four
    universes on Coq 8.19.2, Coq 8.20.1 and Rocq 9.1.1 alike ([About] on
    each); Monad/Morphism/Monoid.v names them with a fixed binder.

    ** Monad/Morphism/Transformer.v

    Controls: the components of transformer_hom L are L's lift (C56), and
    the lift of hom_transformer θ has the components of θ (C57); the lift
    of hom_transformer (transformer_hom L) is L's (C26); the components of
    transformer_hom (hom_transformer θ) are θ's (C27).
    R10 (CONVERSION, STRUCTURAL).
      (cannot unify "hom_transformer (transformer_hom L)" and "L")
    R11 (CONVERSION, STRUCTURAL).
      (cannot unify "transformer_hom (hom_transformer θ)" and "θ")

    ** Instance/Fun/Action/Monad/BG/Morphism.v

    Controls: [BG_theta M] and [BG_theta_inv M] have identity components
    (C58, C59); θ* keeps the carrier (C28), the structure map as a
    function (C29) and the underlying arrows (C30); BG.v's [BG_Act_EM]
    keeps the structure map as a setoid morphism (C31, BG.v's
    [BG_Act_EM_alg]); θ*'s structure map IS h ∘ id in Sets (C32).
    R12 (CONVERSION, STDLIB OPACITY).  BG.v's [BG_Act_EM_alg] restated
    for θ*:
      (cannot unify "t_alg[projT2 (fobj[mh_EM (BG_theta M)] x)]" and
      "t_alg[`2 (x)]")
    CORRECTION (#1347): R12 now holds at [eq_refl], since Instance/Sets.v
    gives its identity's and composite's properness fields as terms; it is
    a control.
    R13 (CONVERSION, STRUCTURAL).  θ* against [BG_Act_EM], whole object:
      (cannot unify "fobj[mh_EM (BG_theta M)] x" and
      "fobj[BG_Act_EM M] x")
    Controls: [Act_BG_EM] keeps the carrier (C60), and against BG.v's
    [Act_BG_alg] the structure map as a function (C33).
    R14 (CONVERSION, STDLIB OPACITY).  The same as setoid morphisms:
      (cannot unify "t_alg[projT2 (fobj[Act_BG_EM M] x)]" and
      "t_alg[Act_BG_alg M `1 (x) `2 (x)]")
    CORRECTION (#1347): R14 likewise now holds at [eq_refl] and is a
    control.

    ** Instance/SupLat/Free/Morphism.v

    Controls: [SL_theta] and [SL_theta_inv] have identity components
    (C61, C45); θ* keeps the carrier (C62); θ*'s structure map against
    [SL_induced_repack]'s, as functions (C34).
    R15 (CONVERSION, STDLIB OPACITY).  The same as setoid morphisms:
      (cannot unify "t_alg[projT2 (fobj[SL_EM_theta] x)]" and
      "t_alg[SL_induced_repack `2 (x)]")
    CORRECTION (#1347): R15 now holds at [eq_refl], since Instance/Sets.v
    gives its identity's and composite's properness fields as terms; it is
    a control.
    Controls: the factorization through θ* agrees with
    [EM_induced_to_SupLat] in the carrier, the order and the supremum as
    a function (C35) and in the underlying map of arrows (C36).
    R16 (CONVERSION, STDLIB OPACITY).  The supremum as a setoid morphism:
      (cannot unify "sl_sup (fobj[EM_to_SupLat ◯ SL_EM_theta] x)" and
      "sl_sup (fobj[EM_induced_to_SupLat] x)")
    CORRECTION (#1347): R16 likewise now holds at [eq_refl] and is a
    control.
    R17 (CONVERSION, STRUCTURAL).  The two semilattices, whole:
      (cannot unify "fobj[EM_to_SupLat ◯ SL_EM_theta] x" and
      "fobj[EM_induced_to_SupLat] x")

    NOT PINNED HERE.  (a) [About] readbacks as such: the headers' universe
    censuses and their attributions to first carriers and caps (among
    them [Set < o] to Instance/Sets/Powerset.v's
    [Powerset_Prop_truth_equiv]), the unchanged blocks of the four
    constants the fold made [Defined], and the levels at which
    Theory/Equivalence.v's [Equivalence_to_Cat_Iso] reads
    [Monads_Mon_Equivalence].  (b) The flips and copies above, and the
    field and normal-form readings behind the CAUSEs: made in copies of
    the dependency closure and in scratch files.  (c) The closure of the
    targets under [Print Assumptions]: a measurement of the build rather
    than of a command; the Makefile's print-assumptions gate names all
    ninety-seven names below.  (d) The absences the headers record (no
    Kleisli functor induced by θ, no comonad morphisms, no 2-category of
    monads, no converse of θ*, no isomorphism of categories on the nose
    between [Monads C] and [Mon [C, C]], no pointed endofunctor on
    [Monads C], BG.v and Free.v not rewired onto θ*, no isomorphism in
    Cat of the Eilenberg–Moore categories of [BG_theta_iso] or of
    [SL_theta_iso], and Monad/Transformer.v's [MonadTransformerLaws]
    inside a comment): an absence has no command.  (e) The
    dependency-closure counts and [Require] costs the headers give,
    measured by script over coqdep's output.  (f) The readings of the
    book and of nLab, from the page images and the fetched pages.

    The guard block, which only control C40 and its two [Require] lines
    follow, names the ninety-seven names of the six targets, so that a
    rename breaks this file: sixteen constants of Monad/Morphism.v with
    its record [MonadHom] and that record's constructor
    [Build_MonadHom], twenty-five of Monad/Morphism/Algebra.v,
    twenty-one of Monad/Morphism/Monoid.v, seven of
    Monad/Morphism/Transformer.v, twelve of the #464 bridge and fourteen
    of the #466 bridge.  They are exactly the entries [Print Module] gives
    for each, with the constructor added; the .glob files' [def], [prf],
    [proj] and [rec] entries agree, and no target has a [Program]
    obligation.  Each is written fully qualified and with [@], so that no
    short name in scope can stand in for it. *)

Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Natural.Transformation.
Require Import Category.Theory.Monad.
Require Import Category.Instance.Fun.
Require Import Category.Monad.Morphism.
Require Import Category.Theory.Isomorphism.
Require Import Category.Monad.Algebra.
Require Import Category.Monad.Eilenberg.Moore.
Require Import Category.Monad.Eilenberg.Moore.Adjunction.
Require Import Category.Construction.Opposite.
Require Import Category.Instance.Cat.
Require Import Category.Monad.Morphism.Algebra.
Require Import Category.Functor.Bifunctor.
Require Import Category.Structure.Monoidal.
Require Import Category.Structure.Monoidal.Compose.
Require Import Category.Theory.Algebra.Monoid.
Require Import Category.Theory.Algebra.Monoid.Hom.
Require Import Category.Theory.Equivalence.
Require Import Category.Theory.Equivalence.FullFaithful.
Require Import Category.Monad.Morphism.Monoid.
Require Import Category.Monad.Transformer.
Require Import Category.Monad.Morphism.Transformer.
Require Import Category.Construction.Deloop.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Fun.Action.Monad.
Require Import Category.Instance.Fun.Action.Monad.BG.
Require Import Category.Instance.Fun.Action.Monad.BG.Morphism.
Require Import Category.Instance.Sets.Powerset.
Require Import Category.Instance.Sets.Powerset.Monad.
Require Import Category.Instance.SupLat.
Require Import Category.Instance.SupLat.Free.
Require Import Category.Instance.SupLat.Free.Morphism.

Generalizable All Variables.

(* ------------------------------------------------------------------------ *)
(** ** Part (a): Monad/Morphism.v *)

(* C1: the right factor of [mh_join] is [nat_hcompose θ θ] at x. *)
Example p468_c1_hcompose@{o h s | h < s +} {C : Category@{o h h}}
  {T T2 : C ⟶ C} {M : @Monad C T} {M2 : @Monad C T2}
  (θ : MonadHom@{o h} M M2) (x : C) :
  transform[nat_hcompose@{s o o o h} (mh_transform θ) (mh_transform θ)] x
    = mh_transform θ (T2 x) ∘ fmap[T] (mh_transform θ x) := eq_refl.

(* C2: the ≈ of [Monads C] is the ≈ of [C, C] on [mh_transform]. *)
Example p468_c2_equiv@{o h m1 m2 u |
  h < u, o <= m1, h <= m1, o <= m2, h <= m2 +}
  (C : Category@{o h h}) (N N2 : Monads@{o h m1 m2} C)
  (θ φ : N ~{Monads@{o h m1 m2} C}~> N2) :
  @equiv _ (@homset (Monads@{o h m1 m2} C) N N2) θ φ
    = @equiv _ (@homset (@Fun@{o h o h m1 m2 u} C C) (projT1 N) (projT1 N2))
        (mh_transform θ) (mh_transform φ) := eq_refl.

(* C3: the identity of [Monads C] has components [id]. *)
Example p468_c3_id_components@{o h m1 m2 |
  o <= m1, h <= m1, o <= m2, h <= m2 +}
  (C : Category@{o h h}) (N : Monads@{o h m1 m2} C) (x : C) :
  mh_transform (@id (Monads@{o h m1 m2} C) N) x = id := eq_refl.

(* C4: the identity of [C, C] has components [fmap[T] id]. *)
Example p468_c4_fun_id@{o h m1 m2 u |
  h < u, o <= m1, h <= m1, o <= m2, h <= m2 +}
  (C : Category@{o h h}) (T : C ⟶ C) (x : C) :
  transform[@id (@Fun@{o h o h m1 m2 u} C C) T] x = fmap[T] id := eq_refl.

(* C46: [Monads_Forget] is the first projection on objects. *)
Example p468_c46_mforget_obj@{o h m1 m2 u |
  h < u, o <= m1, h <= m1, o <= m2, h <= m2 +} (C : Category@{o h h})
  (N : Monads@{o h m1 m2} C) :
  fobj[Monads_Forget@{o h m1 m2 u} C] N = projT1 N := eq_refl.

(* C47: and [mh_transform] on arrows. *)
Example p468_c47_mforget_map@{o h m1 m2 u |
  h < u, o <= m1, h <= m1, o <= m2, h <= m2 +} (C : Category@{o h h})
  (N N2 : Monads@{o h m1 m2} C) (θ : N ~{Monads@{o h m1 m2} C}~> N2) :
  fmap[Monads_Forget@{o h m1 m2 u} C] θ = mh_transform θ := eq_refl.

(* R6 *)
Fail Example p468_r6_forget_id@{o h m1 m2 u |
  h < u, o <= m1, h <= m1, o <= m2, h <= m2 +}
  (C : Category@{o h h}) (N : Monads@{o h m1 m2} C) (x : C) :
  transform[fmap[Monads_Forget@{o h m1 m2 u} C]
              (@id (Monads@{o h m1 m2} C) N)] x
    = transform[@id (@Fun@{o h o h m1 m2 u} C C) (projT1 N)] x := eq_refl.

(* C37: the composition law of [Monads_Forget] at a component. *)
Example p468_c37_forget_comp@{o h m1 m2 u |
  h < u, o <= m1, h <= m1, o <= m2, h <= m2 +}
  (C : Category@{o h h}) (N N2 N3 : Monads@{o h m1 m2} C)
  (φ : N2 ~{Monads@{o h m1 m2} C}~> N3)
  (θ : N ~{Monads@{o h m1 m2} C}~> N2) (x : C) :
  transform[fmap[Monads_Forget@{o h m1 m2 u} C] (φ ∘ θ)] x
    = transform[fmap[Monads_Forget@{o h m1 m2 u} C] φ
                ∘ fmap[Monads_Forget@{o h m1 m2 u} C] θ] x := eq_refl.

(* R18 *)
Fail Example p468_r18_forget_comp@{o h m1 m2 u |
  h < u, o <= m1, h <= m1, o <= m2, h <= m2 +}
  (C : Category@{o h h}) (N N2 N3 : Monads@{o h m1 m2} C)
  (φ : N2 ~{Monads@{o h m1 m2} C}~> N3)
  (θ : N ~{Monads@{o h m1 m2} C}~> N2) :
  fmap[Monads_Forget@{o h m1 m2 u} C] (φ ∘ θ)
    = fmap[Monads_Forget@{o h m1 m2 u} C] φ
      ∘ fmap[Monads_Forget@{o h m1 m2 u} C] θ := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Part (b): the direction of F^T ⇝ θ* ∘ F^{T'} *)

(* C5: the page's direction is a well-formed type. *)
Definition p468_c5_book_type@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) :=
  @EM_Free@{o h s e} C T M ⟹ mh_EM@{o h e s} θ ◯ @EM_Free@{o h s e} C T2 M2.

(* C6: [mh_EM_free θ] inhabits it. *)
Definition p468_c6_free_type@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) :
  p468_c5_book_type@{o h e s} θ := mh_EM_free@{o h e s} θ.

(* R1 *)
Fail Definition p468_r1_issue_direction@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) :=
  @EM_Free@{o h s e} C T2 M2 ⟹ mh_EM@{o h e s} θ ◯ @EM_Free@{o h s e} C T M.

(* ------------------------------------------------------------------------ *)
(** ** Part (b): G^T ∘ θ* = G^{T'} *)

(* C7: on objects. *)
Example p468_c7_forget_obj@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2)
  (X : @EilenbergMoore@{e o s h} C T2 M2) :
  fobj[@EM_Forget@{o h s e} C T M ◯ mh_EM@{o h e s} θ] X
    = fobj[@EM_Forget@{o h s e} C T2 M2] X := eq_refl.

(* C8: on objects, as a function. *)
Example p468_c8_forget_obj_fun@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) :
  (fun X => fobj[@EM_Forget@{o h s e} C T M ◯ mh_EM@{o h e s} θ] X)
    = (fun X => fobj[@EM_Forget@{o h s e} C T2 M2] X) := eq_refl.

(* C9: on arrows. *)
Example p468_c9_forget_map@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2)
  (X Y : @EilenbergMoore@{e o s h} C T2 M2) (f : X ~> Y) :
  fmap[@EM_Forget@{o h s e} C T M ◯ mh_EM@{o h e s} θ] f
    = fmap[@EM_Forget@{o h s e} C T2 M2] f := eq_refl.

(* C10: the [fobj] fields of the two functors. *)
Example p468_c10_fobj_field@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) :
  @fobj _ _ (@EM_Forget@{o h s e} C T M ◯ mh_EM@{o h e s} θ)
    = @fobj _ _ (@EM_Forget@{o h s e} C T2 M2) := eq_refl.

(* C11: the [fmap] fields of the two functors. *)
Example p468_c11_fmap_field@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) :
  @fmap _ _ (@EM_Forget@{o h s e} C T M ◯ mh_EM@{o h e s} θ)
    = @fmap _ _ (@EM_Forget@{o h s e} C T2 M2) := eq_refl.

(* C12: the object equation of [mh_EM_forget_strict] IS [eq_refl]. *)
Example p468_c12_strict_obj@{o h e s a b |
  h < s, o <= e, h <= e, o <= a, h <= a, e <= a, h <= b, e <= b +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2)
  (X : @EilenbergMoore@{e o s h} C T2 M2) :
  projT1 (mh_EM_forget_strict@{o h e s a b} θ) X = eq_refl := eq_refl.

(* C41: both legs of the isomorphisms of [mh_EM_forget] are identities. *)
Example p468_c41_forget_iso@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2)
  (X : @EilenbergMoore@{e o s h} C T2 M2) :
  (to (projT1 (mh_EM_forget@{o h e s} θ) X),
   from (projT1 (mh_EM_forget@{o h e s} θ) X))
    = (@id C (`1 X), @id C (`1 X)) := eq_refl.

(* R2 *)
Fail Example p468_r2_forget_eq@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) :
  @EM_Forget@{o h s e} C T M ◯ mh_EM@{o h e s} θ
    = @EM_Forget@{o h s e} C T2 M2 := eq_refl.

(* R2a *)
Fail Example p468_r2a_fmap_respects@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) :
  @fmap_respects _ _ (@EM_Forget@{o h s e} C T M ◯ mh_EM@{o h e s} θ)
    = @fmap_respects _ _ (@EM_Forget@{o h s e} C T2 M2) := eq_refl.

(* R2b *)
Fail Example p468_r2b_fmap_id@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) :
  @fmap_id _ _ (@EM_Forget@{o h s e} C T M ◯ mh_EM@{o h e s} θ)
    = @fmap_id _ _ (@EM_Forget@{o h s e} C T2 M2) := eq_refl.

(* R2c *)
Fail Example p468_r2c_fmap_comp@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) :
  @fmap_comp _ _ (@EM_Forget@{o h s e} C T M ◯ mh_EM@{o h e s} θ)
    = @fmap_comp _ _ (@EM_Forget@{o h s e} C T2 M2) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Part (b): F^T ⇝ θ* ∘ F^{T'} *)

(* C13: each component is θ_x under G^T. *)
Example p468_c13_free_forget@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) (x : C) :
  t_alg_hom[transform[mh_EM_free@{o h e s} θ] x] = mh_transform θ x
  := eq_refl.

(* C18: the underlying arrow of the transpose of η'_x. *)
Example p468_c18_transpose_arrow@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) (x : C) :
  t_alg_hom[@EM_extend@{o h e s} C T M x
                 (fobj[mh_EM@{o h e s} θ ◯ @EM_Free@{o h s e} C T2 M2] x)
                 (@ret C T2 M2 x)]
    = (@join C T2 M2 x ∘ mh_transform θ (T2 x)) ∘ fmap[T] (@ret C T2 M2 x)
  := eq_refl.

(* R5 *)
Fail Example p468_r5_transpose@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) (x : C) :
  t_alg_hom[@EM_extend@{o h e s} C T M x
                 (fobj[mh_EM@{o h e s} θ ◯ @EM_Free@{o h s e} C T2 M2] x)
                 (@ret C T2 M2 x)]
    = mh_transform θ x := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Part (b): functoriality in θ *)

(* C63: θ* writes the structure map h' as h' ∘ θ_a. *)
Example p468_c63_alg@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2)
  (X : @EilenbergMoore@{e o s h} C T2 M2) :
  @t_alg _ _ _ _ (`2 (fobj[mh_EM@{o h e s} θ] X))
    = @t_alg _ _ _ _ (`2 X) ∘ mh_transform θ (`1 X) := eq_refl.

(* C14: (id)* keeps the carrier. *)
Example p468_c14_id_carrier@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T : C ⟶ C} {M : @Monad C T}
  (X : @EilenbergMoore@{e o s h} C T M) :
  `1 (fobj[mh_EM@{o h e s} (mh_id M)] X) = `1 X := eq_refl.

(* C15: (id)* writes h ∘ id. *)
Example p468_c15_id_alg@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T : C ⟶ C} {M : @Monad C T}
  (X : @EilenbergMoore@{e o s h} C T M) :
  @t_alg _ _ _ _ (`2 (fobj[mh_EM@{o h e s} (mh_id M)] X))
    = @t_alg _ _ _ _ (`2 X) ∘ id := eq_refl.

(* R3 *)
Fail Example p468_r3_id_obj@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T : C ⟶ C} {M : @Monad C T}
  (X : @EilenbergMoore@{e o s h} C T M) :
  fobj[mh_EM@{o h e s} (mh_id M)] X = X := eq_refl.

(* C16: (φ ∘ θ)* writes h ∘ (φ ∘ θ). *)
Example p468_c16_comp_alg@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 T3 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} {M3 : @Monad C T3}
  (φ : MonadHom@{o h} M2 M3) (θ : MonadHom@{o h} M M2)
  (X : @EilenbergMoore@{e o s h} C T3 M3) :
  @t_alg _ _ _ _ (`2 (fobj[mh_EM@{o h e s} (mh_compose φ θ)] X))
    = @t_alg _ _ _ _ (`2 X) ∘ (mh_transform φ (`1 X) ∘ mh_transform θ (`1 X))
  := eq_refl.

(* C17: (φ ∘ θ)* and θ* ◯ φ* keep the same underlying arrows. *)
Example p468_c17_comp_hom@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 T3 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} {M3 : @Monad C T3}
  (φ : MonadHom@{o h} M2 M3) (θ : MonadHom@{o h} M M2)
  (X Y : @EilenbergMoore@{e o s h} C T3 M3) (f : X ~> Y) :
  t_alg_hom[fmap[mh_EM@{o h e s} (mh_compose φ θ)] f]
    = t_alg_hom[fmap[mh_EM@{o h e s} θ ◯ mh_EM@{o h e s} φ] f] := eq_refl.

(* R4 *)
Fail Example p468_r4_comp_obj@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 T3 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} {M3 : @Monad C T3}
  (φ : MonadHom@{o h} M2 M3) (θ : MonadHom@{o h} M M2)
  (X : @EilenbergMoore@{e o s h} C T3 M3) :
  fobj[mh_EM@{o h e s} (mh_compose φ θ)] X
    = fobj[mh_EM@{o h e s} θ ◯ mh_EM@{o h e s} φ] X := eq_refl.

(* C42: both legs of the isomorphism of (id)* ≈ Id have underlying arrow
   [id]. *)
Example p468_c42_id_iso@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T : C ⟶ C} {M : @Monad C T}
  (X : @EilenbergMoore@{e o s h} C T M) :
  (t_alg_hom[to (projT1 (@mh_EM_id@{o h e s} C T M) X)],
   t_alg_hom[from (projT1 (@mh_EM_id@{o h e s} C T M) X)])
    = (@id C (`1 X), @id C (`1 X)) := eq_refl.

(* C43: so have those of (φ ∘ θ)* ≈ θ* ◯ φ*. *)
Example p468_c43_comp_iso@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 T3 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} {M3 : @Monad C T3}
  (φ : MonadHom@{o h} M2 M3) (θ : MonadHom@{o h} M M2)
  (X : @EilenbergMoore@{e o s h} C T3 M3) :
  (t_alg_hom[to (projT1 (mh_EM_compose@{o h e s} φ θ) X)],
   t_alg_hom[from (projT1 (mh_EM_compose@{o h e s} φ θ) X)])
    = (@id C (`1 X), @id C (`1 X)) := eq_refl.

(* C44: and those of θ* ≈ θ2*, for θ ≈ θ2. *)
Example p468_c44_respects_iso@{o h e s | h < s, o <= e, h <= e +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ θ2 : MonadHom@{o h} M M2)
  (E : ∀ x, mh_transform θ x ≈ mh_transform θ2 x)
  (X : @EilenbergMoore@{e o s h} C T2 M2) :
  (t_alg_hom[to (projT1 (mh_EM_respects@{o h e s} θ θ2 E) X)],
   t_alg_hom[from (projT1 (mh_EM_respects@{o h e s} θ θ2 E) X)])
    = (@id C (`1 X), @id C (`1 X)) := eq_refl.

(* C48: [Monads_EM] sends a monad to its Eilenberg–Moore category. *)
Example p468_c48_em_obj@{o h m1 m2 e s u |
  h < s, h < u, e < u, o <= m1, h <= m1, o <= m2, h <= m2, m2 <= e,
  o <= e, h <= e +} (C : Category@{o h h}) (N : Monads@{o h m1 m2} C) :
  fobj[Monads_EM@{o h m1 m2 e s u} C] N
    = @EilenbergMoore@{e o s h} C (projT1 N) (projT2 N) := eq_refl.

(* C49: and a morphism θ to θ*. *)
Example p468_c49_em_map@{o h m1 m2 e s u |
  h < s, h < u, e < u, o <= m1, h <= m1, o <= m2, h <= m2, m2 <= e,
  o <= e, h <= e +} (C : Category@{o h h}) (N N2 : Monads@{o h m1 m2} C)
  (θ : N2 ~{Monads@{o h m1 m2} C}~> N) :
  fmap[Monads_EM@{o h m1 m2 e s u} C] θ = mh_EM@{o h e s} θ := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Monad/Morphism/Monoid.v *)

(* C19: the tensor of [Compose_Monoidal] on (θ, θ), at x. *)
Example p468_c19_bimap@{o h f s | h < s, o <= f, h <= f +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) (x : C) :
  transform[@bimap _ _ _ (@tensor _ (@Compose_Monoidal@{s f o h} C))
              _ _ _ _ (mh_transform θ) (mh_transform θ)] x
    = mh_transform θ (T2 x) ∘ fmap[T] (mh_transform θ x) := eq_refl.

(* C20: the type of [mh_join] is the multiplication square's. *)
Example p468_c20_hom_mu_type@{o h f s q |
  h < s, o <= f, h <= f, o < q, h < q +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) :
  @eq Type@{q}
    (∀ x : C, mh_transform θ x ∘ @join C T M x
                ≈ @join C T2 M2 x
                    ∘ (mh_transform θ (T2 x) ∘ fmap[T] (mh_transform θ x)))
    (@compose (@Fun@{o h o h f f s} C C) _ _ _
       (mh_transform θ) (@mu _ _ _ (monad_monoid@{o h f s} M))
     ≈ @compose (@Fun@{o h o h f f s} C C) _ _ _
         (@mu _ _ _ (monad_monoid@{o h f s} M2))
         (@bimap _ _ _ (@tensor _ (@Compose_Monoidal@{s f o h} C))
            _ _ _ _ (mh_transform θ) (mh_transform θ)))
  := eq_refl.

(* C52: the type of [mh_ret] is the unit triangle's. *)
Example p468_c52_hom_eta_type@{o h f s q |
  h < s, o <= f, h <= f, o < q, h < q +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) :
  @eq Type@{q} (∀ x : C, mh_transform θ x ∘ @ret C T M x ≈ @ret C T2 M2 x)
  (@compose (@Fun@{o h o h f f s} C C) _ _ _
       (mh_transform θ) (@eta _ _ _ (monad_monoid@{o h f s} M))
     ≈ @eta _ _ _ (monad_monoid@{o h f s} M2)) := eq_refl.

(* C38: the square of [mh_monoidhom θ] at x IS [mh_join θ] at x. *)
Example p468_c38_hom_mu_term@{o h f s | h < s, o <= f, h <= f +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : MonadHom@{o h} M M2) (x : C) :
  @hom_mu _ _ _ _ _ _ _ (mh_monoidhom@{o h f s} θ) x = @mh_join _ _ _ _ _ θ x
  := eq_refl.

(* C39: the [mh_join] of [monoidhom_mh θ H] IS the square of H. *)
Example p468_c39_mh_join_term@{o h f s | h < s, o <= f, h <= f +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : T ⟹ T2)
  (H : @MonoidHom (@Fun@{o h o h f f s} C C) (@Compose_Monoidal@{s f o h} C)
         T T2 (monad_monoid@{o h f s} M) (monad_monoid@{o h f s} M2) θ)
  (x : C) :
  @mh_join _ _ _ _ _ (monoidhom_mh@{o h f s} θ H) x
    = @hom_mu _ _ _ _ _ _ _ H x := eq_refl.

(* C53: [monoidhom_mh θ H] has the transformation θ itself. *)
Example p468_c53_mh_transform@{o h f s | h < s, o <= f, h <= f +}
  {C : Category@{o h h}} {T T2 : C ⟶ C}
  {M : @Monad C T} {M2 : @Monad C T2} (θ : T ⟹ T2)
  (H : @MonoidHom (@Fun@{o h o h f f s} C C) (@Compose_Monoidal@{s f o h} C)
         T T2 (monad_monoid@{o h f s} M) (monad_monoid@{o h f s} M2) θ) :
  mh_transform (monoidhom_mh@{o h f s} θ H) = θ := eq_refl.

(* C54: [Monads_Mon] on objects. *)
Example p468_c54_mon_obj@{o h m1 m2 f s mo t |
  h < s, f < t, o <= m1, h <= m1, o <= m2, h <= m2, m2 <= f,
  o <= f, h <= f, f <= mo +}
  (C : Category@{o h h}) (N : Monads@{o h m1 m2} C) :
  fobj[Monads_Mon@{o h m1 m2 f s mo t} C] N
    = (projT1 N; monad_monoid@{o h f s} (projT2 N)) := eq_refl.

(* C55: [Monads_Mon] on arrows. *)
Example p468_c55_mon_map@{o h m1 m2 f s mo t |
  h < s, f < t, o <= m1, h <= m1, o <= m2, h <= m2, m2 <= f,
  o <= f, h <= f, f <= mo +}
  (C : Category@{o h h}) (N N2 : Monads@{o h m1 m2} C)
  (θ : N ~{Monads@{o h m1 m2} C}~> N2) :
  fmap[Monads_Mon@{o h m1 m2 f s mo t} C] θ
    = (mh_transform θ; mh_monoidhom@{o h f s} θ) := eq_refl.

(* C21: [Monads_Mon] on an identity has components [id]. *)
Example p468_c21_mon_id_left@{o h m1 f s mo t |
  h < s, f < t, o <= m1, h <= m1, o <= f, h <= f, f <= mo +}
  (C : Category@{o h h}) (N : Monads@{o h m1 f} C) (x : C) :
  transform[projT1 (fmap[Monads_Mon@{o h m1 f f s mo t} C]
                       (@id (Monads@{o h m1 f} C) N))] x
    = @id C (projT1 N x) := eq_refl.

(* C22: the identity of [Mon [C, C]] has components fmap[T] id. *)
Example p468_c22_mon_id_right@{o h m1 f s mo t |
  h < s, f < t, o <= m1, h <= m1, o <= f, h <= f, f <= mo +}
  (C : Category@{o h h}) (N : Monads@{o h m1 f} C) (x : C) :
  transform[projT1 (@id (@Mon@{f f mo t} (@Fun@{o h o h f f s} C C)
                          (@Compose_Monoidal@{s f o h} C))
                       (fobj[Monads_Mon@{o h m1 f f s mo t} C] N))] x
    = fmap[projT1 N] (@id C x) := eq_refl.

(* R7 *)
Fail Example p468_r7_mon_id@{o h m1 f s mo t |
  h < s, f < t, o <= m1, h <= m1, o <= f, h <= f, f <= mo +}
  (C : Category@{o h h}) (N : Monads@{o h m1 f} C) (x : C) :
  transform[projT1 (fmap[Monads_Mon@{o h m1 f f s mo t} C]
                       (@id (Monads@{o h m1 f} C) N))] x
    = transform[projT1 (@id (@Mon@{f f mo t} (@Fun@{o h o h f f s} C C)
                               (@Compose_Monoidal@{s f o h} C))
                          (fobj[Monads_Mon@{o h m1 f f s mo t} C] N))] x
  := eq_refl.

(* C23: [Monads_Mon] on a composite, at a component. *)
Example p468_c23_mon_comp@{o h m1 f s mo t |
  h < s, f < t, o <= m1, h <= m1, o <= f, h <= f, f <= mo +}
  (C : Category@{o h h}) (N N2 N3 : Monads@{o h m1 f} C)
  (φ : N2 ~{Monads@{o h m1 f} C}~> N3) (θ : N ~{Monads@{o h m1 f} C}~> N2)
  (x : C) :
  transform[projT1 (fmap[Monads_Mon@{o h m1 f f s mo t} C] (φ ∘ θ))] x
    = transform[projT1 (fmap[Monads_Mon@{o h m1 f f s mo t} C] φ
                        ∘ fmap[Monads_Mon@{o h m1 f f s mo t} C] θ)] x
  := eq_refl.

(* C50: μ of [monad_monoid M] is [join], at x. *)
Example p468_c50_monoid_mu@{o h f s | h < s, o <= f, h <= f +}
  {C : Category@{o h h}} {T : C ⟶ C} (M : @Monad C T) (x : C) :
  transform[@mu _ _ _ (monad_monoid@{o h f s} M)] x = @join C T M x
  := eq_refl.

(* C51: η of [monad_monoid M] is [ret], at x. *)
Example p468_c51_monoid_eta@{o h f s | h < s, o <= f, h <= f +}
  {C : Category@{o h h}} {T : C ⟶ C} (M : @Monad C T) (x : C) :
  transform[@eta _ _ _ (monad_monoid@{o h f s} M)] x = @ret C T M x
  := eq_refl.

(* C24: the unit and multiplication of the monad round trip are M's. *)
Example p468_c24_monad_round@{o h f s | h < s, o <= f, h <= f +}
  {C : Category@{o h h}} {T : C ⟶ C} (M : @Monad C T) (x : C) :
  (@ret C T (monoid_monad@{o h f s} (monad_monoid@{o h f s} M)) x,
   @join C T (monoid_monad@{o h f s} (monad_monoid@{o h f s} M)) x)
    = (@ret C T M x, @join C T M x) := eq_refl.

(* R8 *)
Fail Example p468_r8_monad_round@{o h f s | h < s, o <= f, h <= f +}
  {C : Category@{o h h}} {T : C ⟶ C} (M : @Monad C T) :
  monoid_monad@{o h f s} (monad_monoid@{o h f s} M) = M := eq_refl.

(* C25: μ and η of the monoid round trip are N's, at x. *)
Example p468_c25_monoid_round@{o h f s | h < s, o <= f, h <= f +}
  {C : Category@{o h h}} {T : C ⟶ C}
  (N : @Monoid (@Fun@{o h o h f f s} C C) (@Compose_Monoidal@{s f o h} C) T)
  (x : C) :
  (transform[@mu _ _ _ (monad_monoid@{o h f s} (monoid_monad@{o h f s} N))] x,
   transform[@eta _ _ _ (monad_monoid@{o h f s} (monoid_monad@{o h f s} N))] x)
    = (transform[@mu _ _ _ N] x, transform[@eta _ _ _ N] x) := eq_refl.

(* R9 *)
Fail Example p468_r9_monoid_round@{o h f s | h < s, o <= f, h <= f +}
  {C : Category@{o h h}} {T : C ⟶ C}
  (N : @Monoid (@Fun@{o h o h f f s} C C) (@Compose_Monoidal@{s f o h} C) T) :
  monad_monoid@{o h f s} (monoid_monad@{o h f s} N) = N := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Monad/Morphism/Transformer.v *)

(* C56: the components of [transformer_hom L] are L's lift. *)
Example p468_c56_trans_lift@{o h | +} {C : Category@{o h h}} {M : C ⟶ C}
  {HM : @Monad C M} {T : (C ⟶ C) → (C ⟶ C)} {HT : @Monad C (T M)}
  (L : @MonadTransformer C M HM T HT) (x : C) :
  mh_transform (transformer_hom@{o h} L) x = @lift C M HM T HT L x
  := eq_refl.

(* C57: the lift of [hom_transformer θ] has the components of θ. *)
Example p468_c57_hom_lift@{o h | +} {C : Category@{o h h}} {M : C ⟶ C}
  {HM : @Monad C M} {T : (C ⟶ C) → (C ⟶ C)} {HT : @Monad C (T M)}
  (θ : MonadHom@{o h} HM HT) (x : C) :
  @lift C M HM T HT (hom_transformer@{o h} θ) x = mh_transform θ x
  := eq_refl.

(* C26: the lift of the transformer round trip is L's. *)
Example p468_c26_trans_round@{o h | +} {C : Category@{o h h}}
  {M : C ⟶ C} {HM : @Monad C M} {T : (C ⟶ C) → (C ⟶ C)}
  {HT : @Monad C (T M)} (L : @MonadTransformer C M HM T HT) (x : C) :
  @lift C M HM T HT (hom_transformer@{o h} (transformer_hom@{o h} L)) x
    = @lift C M HM T HT L x := eq_refl.

(* R10 *)
Fail Example p468_r10_trans_round@{o h | +} {C : Category@{o h h}}
  {M : C ⟶ C} {HM : @Monad C M} {T : (C ⟶ C) → (C ⟶ C)}
  {HT : @Monad C (T M)} (L : @MonadTransformer C M HM T HT) :
  hom_transformer@{o h} (transformer_hom@{o h} L) = L := eq_refl.

(* C27: the components of the hom round trip are θ's. *)
Example p468_c27_hom_round@{o h | +} {C : Category@{o h h}}
  {M : C ⟶ C} {HM : @Monad C M} {T : (C ⟶ C) → (C ⟶ C)}
  {HT : @Monad C (T M)} (θ : MonadHom@{o h} HM HT) (x : C) :
  mh_transform (transformer_hom@{o h} (hom_transformer@{o h} θ)) x
    = mh_transform θ x := eq_refl.

(* R11 *)
Fail Example p468_r11_hom_round@{o h | +} {C : Category@{o h h}}
  {M : C ⟶ C} {HM : @Monad C M} {T : (C ⟶ C) → (C ⟶ C)}
  {HT : @Monad C (T M)} (θ : MonadHom@{o h} HM HT) :
  transformer_hom@{o h} (hom_transformer@{o h} θ) = θ := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Fun/Action/Monad/BG/Morphism.v *)

(* C58: [BG_theta M] has identity components. *)
Example p468_c58_bg_component@{o so | o < so +} (M : MonObject@{o o o})
  (X : SetoidObject@{o o}) :
  mh_transform (BG_theta@{o so} M) X = @id Sets@{o so} (act_prod M X)
  := eq_refl.

(* C59: so has [BG_theta_inv M]. *)
Example p468_c59_bg_inv_component@{o so | o < so +} (M : MonObject@{o o o})
  (X : SetoidObject@{o o}) :
  mh_transform (BG_theta_inv@{o so} M) X = @id Sets@{o so} (act_prod M X)
  := eq_refl.

(* C28: θ* keeps the carrier. *)
Example p468_c28_bg_carrier@{o so | o < so +} (M : MonObject@{o o o})
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (U_BG@{o so} M ◯ F_BG@{o so} M) (BGMonad@{o so} M)) :
  `1 (fobj[mh_EM@{so o so so} (BG_theta@{o so} M)] x) = `1 x := eq_refl.

(* C29: θ* keeps the structure map as a function. *)
Example p468_c29_bg_alg_fun@{o so | o < so +} (M : MonObject@{o o o})
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (U_BG@{o so} M ◯ F_BG@{o so} M) (BGMonad@{o so} M)) :
  (fun p => @t_alg _ _ _ _
              (`2 (fobj[mh_EM@{so o so so} (BG_theta@{o so} M)] x)) p)
    = (fun p => @t_alg _ _ _ _ (`2 x) p) := eq_refl.

(* C30: θ* keeps underlying arrows. *)
Example p468_c30_bg_hom@{o so | o < so +} (M : MonObject@{o o o})
  (x y : @EilenbergMoore@{so so so o} Sets@{o so}
           (U_BG@{o so} M ◯ F_BG@{o so} M) (BGMonad@{o so} M))
  (f : x ~> y) :
  t_alg_hom[fmap[mh_EM@{so o so so} (BG_theta@{o so} M)] f]
    = t_alg_hom[f] := eq_refl.

(* C31: BG.v's [BG_Act_EM] keeps the structure map as a setoid morphism. *)
Example p468_c31_bg_orig_alg@{o so | o < so +} (M : MonObject@{o o o})
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (U_BG@{o so} M ◯ F_BG@{o so} M) (BGMonad@{o so} M)) :
  @t_alg _ _ _ _ (`2 (fobj[BG_Act_EM@{o so} M] x)) = @t_alg _ _ _ _ (`2 x)
  := eq_refl.

(* C32: θ*'s structure map IS h ∘ id in Sets. *)
Example p468_c32_bg_alg_compose@{o so | o < so +} (M : MonObject@{o o o})
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (U_BG@{o so} M ◯ F_BG@{o so} M) (BGMonad@{o so} M)) :
  @t_alg _ _ _ _ (`2 (fobj[mh_EM@{so o so so} (BG_theta@{o so} M)] x))
    = @compose Sets@{o so} _ _ _ (@t_alg _ _ _ _ (`2 x))
        (@id Sets@{o so} (act_prod M (`1 x))) := eq_refl.

(* R12 *)
Example p468_r12_bg_alg@{o so | o < so +} (M : MonObject@{o o o})
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (U_BG@{o so} M ◯ F_BG@{o so} M) (BGMonad@{o so} M)) :
  @t_alg _ _ _ _ (`2 (fobj[mh_EM@{so o so so} (BG_theta@{o so} M)] x))
    = @t_alg _ _ _ _ (`2 x) := eq_refl.

(* R13 *)
Fail Example p468_r13_bg_obj@{o so | o < so +} (M : MonObject@{o o o})
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (U_BG@{o so} M ◯ F_BG@{o so} M) (BGMonad@{o so} M)) :
  fobj[mh_EM@{so o so so} (BG_theta@{o so} M)] x = fobj[BG_Act_EM@{o so} M] x
  := eq_refl.

(* C33: [Act_BG_EM] against BG.v's [Act_BG_alg], as functions. *)
Example p468_c33_actbg_alg_fun@{o so | o < so +} (M : MonObject@{o o o})
  (x : @EilenbergMoore@{so so so o} Sets@{o so} (ActF@{o so} M)
         (ActMonad@{o so} M)) :
  (fun p => @t_alg _ _ _ _ (`2 (fobj[Act_BG_EM@{o so} M] x)) p)
    = (fun p => @t_alg _ _ _ _ (Act_BG_alg@{o so} M (`1 x) (`2 x)) p)
  := eq_refl.

(* C60: [Act_BG_EM] keeps the carrier. *)
Example p468_c60_actbg_carrier@{o so | o < so +} (M : MonObject@{o o o})
  (x : @EilenbergMoore@{so so so o} Sets@{o so} (ActF@{o so} M)
         (ActMonad@{o so} M)) :
  `1 (fobj[Act_BG_EM@{o so} M] x) = `1 x := eq_refl.

(* R14 *)
Example p468_r14_actbg_alg@{o so | o < so +} (M : MonObject@{o o o})
  (x : @EilenbergMoore@{so so so o} Sets@{o so} (ActF@{o so} M)
         (ActMonad@{o so} M)) :
  @t_alg _ _ _ _ (`2 (fobj[Act_BG_EM@{o so} M] x))
    = @t_alg _ _ _ _ (Act_BG_alg@{o so} M (`1 x) (`2 x)) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/SupLat/Free/Morphism.v *)

(* C61: [SL_theta] has identity components. *)
Example p468_c61_sl_component@{o so | Set < o, o < so +}
  (X : SetoidObject@{o o}) :
  mh_transform SL_theta@{o so} X
    = @id Sets@{o so} (fobj[Powerset_Prop@{o so}] X) := eq_refl.

(* C45: [SL_theta_inv] has identity components. *)
Example p468_c45_sl_inv_component@{o so | Set < o, o < so +}
  (X : SetoidObject@{o o}) :
  mh_transform SL_theta_inv@{o so} X
    = @id Sets@{o so} (fobj[Powerset_Prop@{o so}] X) := eq_refl.

(* C34: θ*'s structure map against [SL_induced_repack]'s, as functions. *)
Example p468_c34_sl_alg_fun@{o so | Set < o, o < so +}
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (SL_Forget@{o so} ◯ SL_Free@{o so}) SL_induced@{o so}) :
  (fun S => @t_alg _ _ _ _ (`2 (fobj[SL_EM_theta@{o so}] x)) S)
    = (fun S => @t_alg _ _ _ _ (SL_induced_repack@{o so} (`2 x)) S)
  := eq_refl.

(* R15 *)
Example p468_r15_sl_alg@{o so | Set < o, o < so +}
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (SL_Forget@{o so} ◯ SL_Free@{o so}) SL_induced@{o so}) :
  @t_alg _ _ _ _ (`2 (fobj[SL_EM_theta@{o so}] x))
    = @t_alg _ _ _ _ (SL_induced_repack@{o so} (`2 x)) := eq_refl.

(* C62: θ* keeps the carrier. *)
Example p468_c62_sl_carrier@{o so | Set < o, o < so +}
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (SL_Forget@{o so} ◯ SL_Free@{o so}) SL_induced@{o so}) :
  `1 (fobj[SL_EM_theta@{o so}] x) = `1 x := eq_refl.

(* C35: the carrier, the order and the supremum as a function. *)
Example p468_c35_sl_parts@{o so | Set < o, o < so +}
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (SL_Forget@{o so} ◯ SL_Free@{o so}) SL_induced@{o so}) :
  (sl_set (fobj[EM_to_SupLat@{o so} ◯ SL_EM_theta@{o so}] x),
   sl_le (fobj[EM_to_SupLat@{o so} ◯ SL_EM_theta@{o so}] x),
   fun S => sl_sup (fobj[EM_to_SupLat@{o so} ◯ SL_EM_theta@{o so}] x) S)
    = (sl_set (fobj[EM_induced_to_SupLat@{o so}] x),
       sl_le (fobj[EM_induced_to_SupLat@{o so}] x),
       fun S => sl_sup (fobj[EM_induced_to_SupLat@{o so}] x) S) := eq_refl.

(* C36: the underlying map of arrows. *)
Example p468_c36_sl_map@{o so | Set < o, o < so +}
  (x y : @EilenbergMoore@{so so so o} Sets@{o so}
           (SL_Forget@{o so} ◯ SL_Free@{o so}) SL_induced@{o so})
  (f : x ~> y) :
  slh_map (fmap[EM_to_SupLat@{o so} ◯ SL_EM_theta@{o so}] f)
    = slh_map (fmap[EM_induced_to_SupLat@{o so}] f) := eq_refl.

(* R16 *)
Example p468_r16_sl_sup@{o so | Set < o, o < so +}
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (SL_Forget@{o so} ◯ SL_Free@{o so}) SL_induced@{o so}) :
  sl_sup (fobj[EM_to_SupLat@{o so} ◯ SL_EM_theta@{o so}] x)
    = sl_sup (fobj[EM_induced_to_SupLat@{o so}] x) := eq_refl.

(* R17 *)
Fail Example p468_r17_sl_obj@{o so | Set < o, o < so +}
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (SL_Forget@{o so} ◯ SL_Free@{o so}) SL_induced@{o so}) :
  fobj[EM_to_SupLat@{o so} ◯ SL_EM_theta@{o so}] x
    = fobj[EM_induced_to_SupLat@{o so}] x := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Guard: every constant of the six targets, by its full name *)

Check @Category.Monad.Morphism.MonadHom.
Check @Category.Monad.Morphism.Build_MonadHom.
Check @Category.Monad.Morphism.mh_transform.
Check @Category.Monad.Morphism.mh_ret.
Check @Category.Monad.Morphism.mh_join.
Check @Category.Monad.Morphism.mh_join_hcompose.
Check @Category.Monad.Morphism.mh_join_nat.
Check @Category.Monad.Morphism.mh_id.
Check @Category.Monad.Morphism.mh_id_component.
Check @Category.Monad.Morphism.mh_compose.
Check @Category.Monad.Morphism.mh_compose_component.
Check @Category.Monad.Morphism.Monads.
Check @Category.Monad.Morphism.Monads_equiv_is_Fun_equiv.
Check @Category.Monad.Morphism.Monads_Forget.
Check @Category.Monad.Morphism.Monads_Forget_obj.
Check @Category.Monad.Morphism.Monads_Forget_map.
Check @Category.Monad.Morphism.Monads_Forget_comp_component.
Check @Category.Monad.Morphism.Monads_Forget_Faithful.
Check @Category.Monad.Morphism.Algebra.mh_algebra.
Check @Category.Monad.Morphism.Algebra.mh_EM.
Check @Category.Monad.Morphism.Algebra.mh_EM_carrier.
Check @Category.Monad.Morphism.Algebra.mh_EM_alg.
Check @Category.Monad.Morphism.Algebra.mh_EM_hom.
Check @Category.Monad.Morphism.Algebra.mh_EM_forget_obj.
Check @Category.Monad.Morphism.Algebra.mh_EM_forget_obj_fun.
Check @Category.Monad.Morphism.Algebra.mh_EM_forget_map.
Check @Category.Monad.Morphism.Algebra.mh_EM_forget.
Check @Category.Monad.Morphism.Algebra.mh_EM_forget_iso_id.
Check @Category.Monad.Morphism.Algebra.mh_EM_forget_strict.
Check @Category.Monad.Morphism.Algebra.mh_free_component.
Check @Category.Monad.Morphism.Algebra.mh_EM_free.
Check @Category.Monad.Morphism.Algebra.mh_EM_free_forget.
Check @Category.Monad.Morphism.Algebra.mh_EM_free_transpose.
Check @Category.Monad.Morphism.Algebra.talg_same.
Check @Category.Monad.Morphism.Algebra.mh_EM_respects.
Check @Category.Monad.Morphism.Algebra.mh_EM_id.
Check @Category.Monad.Morphism.Algebra.mh_EM_compose.
Check @Category.Monad.Morphism.Algebra.mh_EM_respects_iso_id.
Check @Category.Monad.Morphism.Algebra.mh_EM_id_iso_id.
Check @Category.Monad.Morphism.Algebra.mh_EM_compose_iso_id.
Check @Category.Monad.Morphism.Algebra.Monads_EM.
Check @Category.Monad.Morphism.Algebra.Monads_EM_obj.
Check @Category.Monad.Morphism.Algebra.Monads_EM_map.
Check @Category.Monad.Morphism.Monoid.monad_monoid.
Check @Category.Monad.Morphism.Monoid.monad_monoid_mu.
Check @Category.Monad.Morphism.Monoid.monad_monoid_eta.
Check @Category.Monad.Morphism.Monoid.monoid_monad.
Check @Category.Monad.Morphism.Monoid.monoid_monad_ret.
Check @Category.Monad.Morphism.Monoid.monoid_monad_join.
Check @Category.Monad.Morphism.Monoid.monad_monoid_mu_round.
Check @Category.Monad.Morphism.Monoid.monad_monoid_eta_round.
Check @Category.Monad.Morphism.Monoid.mh_bimap_component.
Check @Category.Monad.Morphism.Monoid.mh_join_is_hom_mu.
Check @Category.Monad.Morphism.Monoid.mh_ret_is_hom_eta.
Check @Category.Monad.Morphism.Monoid.mh_monoidhom.
Check @Category.Monad.Morphism.Monoid.monoidhom_mh.
Check @Category.Monad.Morphism.Monoid.monoidhom_mh_transform.
Check @Category.Monad.Morphism.Monoid.Monads_Mon.
Check @Category.Monad.Morphism.Monoid.Monads_Mon_obj.
Check @Category.Monad.Morphism.Monoid.Monads_Mon_map.
Check @Category.Monad.Morphism.Monoid.Monads_Mon_Faithful.
Check @Category.Monad.Morphism.Monoid.Monads_Mon_Full.
Check @Category.Monad.Morphism.Monoid.Monads_Mon_ESO.
Check @Category.Monad.Morphism.Monoid.Monads_Mon_Equivalence.
Check @Category.Monad.Morphism.Transformer.lift_natural.
Check @Category.Monad.Morphism.Transformer.transformer_hom.
Check @Category.Monad.Morphism.Transformer.transformer_hom_lift.
Check @Category.Monad.Morphism.Transformer.hom_transformer.
Check @Category.Monad.Morphism.Transformer.hom_transformer_lift.
Check @Category.Monad.Morphism.Transformer.transformer_round_trip.
Check @Category.Monad.Morphism.Transformer.hom_round_trip.
Check @Category.Instance.Fun.Action.Monad.BG.Morphism.BG_theta.
Check @Category.Instance.Fun.Action.Monad.BG.Morphism.BG_theta_component.
Check @Category.Instance.Fun.Action.Monad.BG.Morphism.BG_theta_inv.
Check @Category.Instance.Fun.Action.Monad.BG.Morphism.BG_theta_inv_component.
Check @Category.Instance.Fun.Action.Monad.BG.Morphism.BG_theta_iso.
Check @Category.Instance.Fun.Action.Monad.BG.Morphism.BG_theta_EM_carrier.
Check @Category.Instance.Fun.Action.Monad.BG.Morphism.BG_theta_EM_alg_fun.
Check @Category.Instance.Fun.Action.Monad.BG.Morphism.BG_theta_EM_hom.
Check @Category.Instance.Fun.Action.Monad.BG.Morphism.BG_theta_EM.
Check @Category.Instance.Fun.Action.Monad.BG.Morphism.Act_BG_EM.
Check @Category.Instance.Fun.Action.Monad.BG.Morphism.Act_BG_EM_carrier.
Check @Category.Instance.Fun.Action.Monad.BG.Morphism.Act_BG_EM_alg_fun.
Check @Category.Instance.SupLat.Free.Morphism.SL_theta.
Check @Category.Instance.SupLat.Free.Morphism.SL_theta_component.
Check @Category.Instance.SupLat.Free.Morphism.SL_theta_alg_fun.
Check @Category.Instance.SupLat.Free.Morphism.SL_theta_inv.
Check @Category.Instance.SupLat.Free.Morphism.SL_theta_inv_component.
Check @Category.Instance.SupLat.Free.Morphism.SL_theta_iso.
Check @Category.Instance.SupLat.Free.Morphism.SL_EM_theta.
Check @Category.Instance.SupLat.Free.Morphism.SL_EM_theta_carrier.
Check @Category.Instance.SupLat.Free.Morphism.SL_EM_theta_alg_fun.
Check @Category.Instance.SupLat.Free.Morphism.SL_factor_set.
Check @Category.Instance.SupLat.Free.Morphism.SL_factor_le.
Check @Category.Instance.SupLat.Free.Morphism.SL_factor_sup_fun.
Check @Category.Instance.SupLat.Free.Morphism.SL_factor_map.
Check @Category.Instance.SupLat.Free.Morphism.SL_factor.

(* ------------------------------------------------------------------------ *)
(** ** The route through Monad/Monoid.v, measured and not taken *)

(* CORRECTION (#1348): taken since #1348; C40 now restates [monad_monoid]'s
   own body. *)

(* Loaded here, after every other command, so that the two modules below
   change the environment of this control alone. *)
Require Import Category.Monad.Monoid.
Require Import Category.Theory.Algebra.Monoid.Product.

(* C40: that route's μ and η are [monad_monoid]'s, and its round trip
   keeps [ret]. *)
Example p468_c40_monoid_route@{o h f s + | h < s, o <= f, h <= f +}
  {C : Category@{o h h}} {T : C ⟶ C} (M : @Monad C T) (x : C) :
  (transform[@mu _ _ _
     (@Monoid_of_MonoidObject _ (@Compose_Monoidal@{s f o h} C) T
        (snd (@Monoid_Monad C T) M))] x,
   transform[@eta _ _ _
     (@Monoid_of_MonoidObject _ (@Compose_Monoidal@{s f o h} C) T
        (snd (@Monoid_Monad C T) M))] x,
   @ret C T (fst (@Monoid_Monad C T)
     (@MonoidObject_of_Monoid _ (@Compose_Monoidal@{s f o h} C) T
        (@Monoid_of_MonoidObject _ (@Compose_Monoidal@{s f o h} C) T
           (snd (@Monoid_Monad C T) M)))) x)
    = (transform[@mu _ _ _ (monad_monoid@{o h f s} M)] x,
       transform[@eta _ _ _ (monad_monoid@{o h f s} M)] x,
       @ret C T M x) := eq_refl.
