(** * Probe for the monad R ⊗ (−) on Ab and its modules (issue #465)

    Pins the measured boundaries of the three files #465 adds for Mac
    Lane §VI.2, "Modules", book p. 142 (PDF p. 151), catalog item
    maclane:VI.2:remark3, with the appended items from Riehl, "Category
    Theory in Context", 2nd ed.: Example 5.2.6(ii), printed p. 189 (PDF
    p. 209), Example 5.5.7(i), printed p. 205 (PDF p. 225), and Corollary
    5.6.10, printed p. 212 (PDF p. 232).  The files are
    Instance/Mod/TensorMonad.v (the monad R ⊗ (−) as the monad of the
    extension-of-scalars adjunction, its algebras identified with the left
    R-modules by the canonical comparison functor, and the forgetful
    functor monadic twice, by an explicit quasi-inverse and by Beck's
    theorem), Instance/Mod/Colimit/Creation.v (Riehl's Corollary 5.6.10
    proved directly: U : R-Mod ⟶ Ab creates every colimit that Ab has)
    and Instance/Mod/TensorMonad/Cocontinuous.v (the tensor–hom adjunction
    and the other premises of her monadic proof of it).  The first file's
    header cites the refutations N0-N15 and N0Z, N12a-N12d and N13Z here;
    the other two cite C0-C8, C5Z, C6Z, C7a-C7c and C8a.  The positive
    controls restate the files' claims independently.

    THE IMPORT LIST, generated by a script over the [Require] lines.
    Target by target: Instance/Mod/TensorMonad.v's twenty-six [Require]
    lines in its own order, and that target; then the nine lines
    Instance/Mod/Colimit/Creation.v adds to those, in its own order, and
    that target; then the five lines Instance/Mod/TensorMonad/Cocontinuous.v
    adds, in its own order, and that target.  Forty-three lines.  Under
    this list [Print Libraries] in a scratch file loads ninety-five
    [Category] modules, the three targets among them, which is exactly
    the union of the three targets' dependency closures (compared by
    script with the closure of their [Require] lines).  A shorter import
    list is what makes a probe pass for no reason.

    DISCIPLINE.  Three instruments: N0 and N0Z are false statements about
    the monad's multiplication, refused for that reason, and C0 wraps a
    true readback in two refutation keywords, so that the inner one
    reports that its command succeeded.  Each of the thirty-eight
    definitions and examples of this file that is not a refutation
    (thirty-seven controls and the helper [p465_tm_bilin]), wrapped in the
    refutation keyword in a copy of this WHOLE file, stops the build at
    that command with the message Rocq prints for a refutation whose
    command succeeds (thirty-eight of thirty-eight, by a script over the
    copies, which compares the File line of the error with the command's
    extent).  Every negative is a [Definition] or an [Example], never a
    [Check], so that an open evar cannot satisfy it.  Each of the
    thirty-seven refutation lines was stripped of one refutation keyword
    in a copy of this WHOLE file, one at a time, compiled, and its error
    read; each copy stops inside the stripped command (by the File line of
    its error, compared by the same script with the command's extent).
    The kind recorded is the kind of that error.  Quotations are Rocq
    9.1.1's under this file's import list, with the error's environment
    block left out; Rocq prints the "cannot unify" parenthetical with the
    short names in scope.  The three targets and this file also compile on
    Coq 8.19.2 and 8.20.1, overlaid on copies of the dependency closure
    whose ninety-five sources are this tree's byte for byte (compared by
    [cmp]); there every stripped copy is refused inside the stripped
    command, on the line Rocq 9.1.1 reports, with the Rocq 9.1.1 text,
    except that Coq 8.19.2 names C8's and C8a's two universes by number
    (Cannot enforce P.4648 = P.4649 because P.4649 < P.4648, in the copy
    compiled as P) where Coq 8.20.1 and Rocq 9.1.1 print the binder's
    names; and every wrapped control reports that its command succeeded
    (compared by the same script).  No target and not this file prints a
    warning on either older version.

    KINDS.  Thirty-seven refutation lines: the instrument C0; CONVERSION,
    [eq_refl] refused with a "cannot unify" parenthetical (N0, N0Z,
    N1-N15, N12a-N12d, N13Z, C1-C7, C5Z, C6Z, C7a-C7c: thirty-four);
    UNIVERSE, a universe binder that declares one universe of the ring
    strictly below another refused with "Universe inconsistency" and the
    equation it forbids (C8, C8a).  Each CONVERSION refusal but the two
    instruments also has a CAUSE, read off the flips below and off the
    fields and normal forms the targets' headers record: STRUCTURAL (the
    two sides reduce to different terms, or to stuck projections of the
    variable data, and no flip of the tree changes that: all but N12d) and
    OPACITY (the two sides differ only in opaque proofs, and the flip makes
    them convertible: N12d).  The flips, each in a copy of a dependency
    closure with every [Qed] turned into [Defined], [Transparent
    Obligations] set and [abstract] made [transparent_abstract], with
    Structure/Cartesian/Closed.v keeping its [Qed]s, Structure/Limit/
    Preservation.v's [preserves_colimit], which no compared term uses,
    given bullets that tolerate the goals the added transparency closes,
    and the targets' universe annotations dropped: (i) #465's first
    builder's, the first target's closure with Instance/Sets.v also
    keeping its [Qed]s, where the builder's draft of N0-N15 is refused;
    (ii) the first review's, Instance/Sets.v flipped too once
    [setoid_morphism_compose_respects] and its one use are given explicit
    universes, where N0-N15, N0Z and N12a-N12c are refused and N12d's
    statement holds; (iii) the second review's, (ii) extended to both
    other targets' closure, where C1-C7 and C7a-C7c are refused; (iv) the
    fold's, (iii) with the final targets and Instance/Ab/ModFunctor.v,
    re-run on this final file by the second fold, where this whole file
    compiles once C8 and C8a, whose universe binders do not survive the
    dropped annotations, are removed and N12d's refutation keyword with
    them, N12d's statement holding there, and each of the thirty-four
    other refutation lines, stripped there, stops inside the stripped
    command with the text it prints in the unchanged tree (by script).
    In (iv), [Print Opaque Dependencies] on sixteen constants of the three
    targets and their donors lists thirteen constants, all of them
    Corelib's lemmas of generalized rewriting, where the unchanged tree
    lists two hundred and thirty-one.
    CORRECTION (#1347): two hundred and twenty-eight since #1347, whose
    properness fields as terms take Corelib's [subrelation_id_proper],
    [proper_proper_proxy] and [CMorphisms.compose_proper_obligation_1] out of
    the census.

    LABELS.  The first builder's draft refutations (its N0-N15) keep their
    labels.  N0Z and N12a-N12d, the controls [p465_ctl_join_Z],
    [p465_ctl_beck_act_Z] and [p465_ctl_n12_record], [p465_ctl_n12_maps],
    [p465_ctl_n12_left], [p465_ctl_n12_right], and the helper
    [p465_tm_bilin] are the first review's measurements (its rv_n00z, its
    rv_c13z and its N12 records), restated by the fold.  The second
    builder's draft refutations N0-N8 are C0-C8 here, renamed so that no
    label names two refusals; C7a-C7c are the second review's rv_n7a-c,
    and the controls [p465c_ctl_to_Z], [p465c_ctl_from_Z],
    [p465c_ctl_reflect_group], [p465c_ctl_reflect_mediator] and
    [p465c_ctl_lift_module] its rv_c9, rv_c10, rv_c6, rv_c7 and rv_c3.
    N13Z, C5Z and C6Z, the present C8 with C8a, and the control
    [p465c_ctl_ring_open] are the third review's (its B1, T1 and T2, and
    its t2_apart and t3_open), restated by the second fold.
    The labels are not constants: each refutation carries its own in a
    comment on the line above it.

    ** The instruments

    Controls: Mac Lane's μ at a triple, in his order, and over ℤ,
    μ (3 ⊗ (4 ⊗ a)) = 12 ⊗ a ([p465_ctl_join], [p465_ctl_join_Z]).
    N0 (CONVERSION).  The same with the two scalars exchanged:
      (cannot unify "join[_] (ts_gen r1 (ts_gen r2 a0))" and "ts_gen
      (rig_mul R r2 r1) a0")
    N0Z (CONVERSION).  Over ℤ with 13 for 12:
      (cannot unify "join[_] (ts_gen 3%Z (ts_gen 4%Z a0))" and "ts_gen
      13%Z a0")

    ** Instance/Mod/TensorMonad.v: the module round trip

    Controls: the group and the action as a function, at [eq_refl]
    ([p465_ctl_rt_ab], [p465_ctl_rt_smul]).

    N1 (CONVERSION, STRUCTURAL).  The whole module:
      (cannot unify "fobj[EM_to_RMod R ◯ EM_Comparison (zext_adjunction
      R)] M" and "M")
    N2-N6 (CONVERSION, STRUCTURAL).  Its law fields [rm_smul_respects],
    [rm_smul_distr_l], [rm_smul_distr_r], [rm_smul_assoc] and
    [rm_smul_one], one each, all five with the text
      (cannot unify "<field> (fobj[EM_to_RMod R ◯ EM_Comparison
      (zext_adjunction R)] M)" and "<field> M")

    ** Instance/Mod/TensorMonad.v: the algebra round trip

    Controls: the carrier, the structure map at each generator r ⊗ m at
    [eq_refl], and the structure map at every formal sum up to ≈
    ([p465_ctl_rt2_carrier], [p465_ctl_rt2_gen], [p465_ctl_rt2_equiv]).

    N7 (CONVERSION, STRUCTURAL).  The structure map as a function:
      (cannot unify "λ s : fobj[RMod_Forget_Ab R ◯ ZExt R] (projT1
      (fobj[EM_Comparison (zext_adjunction R) ◯ EM_to_RMod R] X)),
      t_alg[projT2 (fobj[EM_Comparison (zext_adjunction R) ◯ EM_to_RMod
      R] X)] s" and "λ s : fobj[RMod_Forget_Ab R ◯ ZExt R] (projT1
      (fobj[EM_Comparison (zext_adjunction R) ◯ EM_to_RMod R] X)),
      t_alg[`2 (X)] s")
    N8 (CONVERSION, STRUCTURAL).  The same at a variable formal sum:
      (cannot unify "t_alg[projT2 (fobj[EM_Comparison (zext_adjunction R)
      ◯ EM_to_RMod R] X)] s" and "t_alg[`2 (X)] s")
    N9 (CONVERSION, STRUCTURAL).  The whole algebra:
      (cannot unify "fobj[EM_Comparison (zext_adjunction R) ◯ EM_to_RMod
      R] X" and "X")

    ** Instance/Mod/TensorMonad.v: the composites

    N10 (CONVERSION, STRUCTURAL).
      (cannot unify "EM_to_RMod R ◯ EM_Comparison (zext_adjunction R)" and
      "Id[RMod R]")
    N11 (CONVERSION, STRUCTURAL).
      (cannot unify "EM_Comparison (zext_adjunction R) ◯ EM_to_RMod R" and
      "Id[EilenbergMoore (TensorF R)]")

    ** Instance/Mod/TensorMonad.v: T f against 1 ⊗ f

    Controls: at each generator at [eq_refl], and at every formal sum up
    to ≈ ([p465_ctl_fmap_gen], [p465_ctl_fmap_equiv]); and, for N12's
    cause, Instance/Ab/Tensor.v's [tensor_map] at 1 ⊗ f IS the mediator of
    the record [p465_tm_bilin] writes out with that definition's own three
    proof terms, the two records have one map, and each side of N12 IS the
    stuck mediator of its own record at the variable sum
    ([p465_ctl_n12_record], [p465_ctl_n12_maps], [p465_ctl_n12_left],
    [p465_ctl_n12_right]).

    N12 (CONVERSION, STRUCTURAL).  At a variable formal sum:
      (cannot unify "fmap[TensorF R] f s" and "tensor_map cmon_hom_id f
      s")
    N12a (CONVERSION, STRUCTURAL).  The two [Bilinear] records:
      (cannot unify "zext_map_bilin R f" and "p465_tm_bilin R f")
    N12b, N12c (CONVERSION, STRUCTURAL).  Their fields [bilin_respects]
    and [bilin_add_l], one each, refused in flip (ii) too:
      (cannot unify "<field> (zext_map_bilin R f)" and "<field>
      (p465_tm_bilin R f)")
    N12d (CONVERSION, OPACITY).  Their field [bilin_add_r], with the same
    text; its statement holds in flips (ii) and (iv).

    ** Instance/Mod/TensorMonad.v: Beck's route

    Controls: Beck's quasi-inverse acts through η, and over ℤ at the
    scalar 3 it IS h (3 ⊗ m); the two [Monadic] witnesses inhabit one type
    ([p465_ctl_beck_act], [p465_ctl_beck_act_Z],
    [p465_ctl_monadic_type]).

    N13 (CONVERSION, STRUCTURAL).  The action as h (r ⊗ m):
      (cannot unify "rm_smul (fobj[quasi_inverse] X) r m" and "t_alg[`2
      (X)] (ts_gen r m)")
    N13Z (CONVERSION, STRUCTURAL).  The same over ℤ at a variable integer
    z, where the ℤ control holds at the scalar 3:
      (cannot unify "rm_smul (fobj[quasi_inverse] X) z m" and "t_alg[`2
      (X)] (ts_gen z m)")
    N14 (CONVERSION, STRUCTURAL).
      (cannot unify "quasi_inverse" and "EM_to_RMod R")
    N15 (CONVERSION, STRUCTURAL).
      (cannot unify "RMod_Forget_Ab_Monadic_beck R" and
      "RMod_Forget_Ab_Monadic R")

    ** Instance/Mod/Colimit/Creation.v

    C0 (the instrument).  Stripped of one keyword, it reports that its
    command succeeded.
    Controls: the created module's group and insertions at [eq_refl], and
    its action on an inserted element up to ≈ ([p465c_ctl_obj],
    [p465c_ctl_legs], [p465c_ctl_leg_smul]).
    C1 (CONVERSION, STRUCTURAL).  That action at [eq_refl]:
      (cannot unify "rm_smul (ColimMod N HN) r (cone_leg N i m)" and
      "cone_leg N i (rm_smul (fobj[K] i) r m)")
    Controls: the module reflected from a cocone M of modules has M's
    group, and its mediators' group maps ARE the Ab mediators
    ([p465c_ctl_reflect_group], [p465c_ctl_reflect_mediator]).
    C2 (CONVERSION, STRUCTURAL).  That module as M itself:
      (cannot unify "ColimMod (FCone (RMod_Forget_Ab R)^op M) HM" and
      "vertex_obj[M]")
    Control: two colimit witnesses of one cocone act alike up to ≈
    ([p465c_ctl_two_witnesses]).
    C3 (CONVERSION, STRUCTURAL).  Their modules as one term:
      (cannot unify "ColimMod N HN" and "ColimMod N HN'")
    Controls: the lift through [creates_colimit_lift] has the given nadir
    as its group and IS [ColimMod] of the colimit read in the opposite
    category; at a terminal shape the action is K(!)(r · m) at [eq_refl]
    and K 1's own up to ≈ ([p465c_ctl_lift_apex],
    [p465c_ctl_lift_module], [p465c_ctl_terminal_smul],
    [p465c_ctl_terminal_own]).
    C4 (CONVERSION, STRUCTURAL).  That action as K 1's own at [eq_refl]:
      (cannot unify "rm_smul vertex_obj[rmod_terminal_colimit T K] r m"
      and "rm_smul (fobj[K] 1) r m")

    ** Instance/Mod/TensorMonad/Cocontinuous.v

    Controls: each transpose at a generator with the unit at [eq_refl],
    without it up to ≈, and without it over ℤ at the scalar 3 at
    [eq_refl] ([p465c_ctl_to], [p465c_ctl_to_gen], [p465c_ctl_to_Z],
    [p465c_ctl_from], [p465c_ctl_from_gen], [p465c_ctl_from_Z]).
    C5 (CONVERSION, STRUCTURAL).
      (cannot unify "adj[TensorF_left_adjoint R] φ a r" and "φ (ts_gen r
      a)")
    C6 (CONVERSION, STRUCTURAL).
      (cannot unify "(adj[TensorF_left_adjoint R])⁻¹ ψ (ts_gen r a)" and
      "ψ a r")
    C5Z, C6Z (CONVERSION, STRUCTURAL).  The same two over ℤ at a variable
    integer z, where the ℤ controls hold at the scalar 3:
      (cannot unify "adj[TensorF_left_adjoint Int_Ring] φ a z" and "φ
      (ts_gen z a)")
      (cannot unify "(adj[TensorF_left_adjoint Int_Ring])⁻¹ ψ (ts_gen z
      a)" and "ψ a z")
    Controls: U^T ◯ K against U on objects and arrows at [eq_refl], and as
    functors up to ≈ ([p465c_ctl_cmp_obj], [p465c_ctl_cmp_map],
    [p465c_ctl_cmp]).
    C7 (CONVERSION, STRUCTURAL).  The two functor records:
      (cannot unify "EM_Forget (TensorF R) ◯ EM_Comparison (zext_adjunction
      R)" and "RMod_Forget_Ab R")
    C7a-C7c (CONVERSION, STRUCTURAL).  Their fields [fmap_respects],
    [fmap_id] and [fmap_comp], one each; [fmap_id] and [fmap_comp] with
    the text
      (cannot unify "@<field> _ _ (EM_Forget (TensorF R) ◯ EM_Comparison
      (zext_adjunction R))" and "@<field> _ _ (RMod_Forget_Ab R)")
    and [fmap_respects] with the same text but for the composite printed
    with its implicit arguments.
    Controls: the tensor–hom adjunction at [RingObject@{c c c}], and at
    [RingObject@{a c p}] under an extensible binder, where elaboration
    adds a = c and a = p ([p465c_ctl_ring_ccc], [p465c_ctl_ring_open]).
    C8 (UNIVERSE).  The same at [RingObject@{a c p}] with c < a declared:
      Universe inconsistency. Cannot enforce a = c because c < a.
    C8a (UNIVERSE).  The same with p < a declared:
      Universe inconsistency. Cannot enforce a = p because p < a.
    The binders are extensible and differ from the control's only in the
    one declared constraint, so either refutation breaks if the equation
    it names ever leaves the adjunction.  A closed constraint list would
    not: it must also declare the standard library's universe caps the
    donors carry, and so it is refused at [RingObject@{c c c}] too, where
    the adjunction exists (the third review's measurement).

    ** Closure: a readback, not a refutation

    [Print Assumptions] of [TensorMonad], [EM_RMod_iso], the two
    [Monadic] witnesses, [RMod_Forget_Ab_creates_colimits] and the two
    cocontinuity constants, near the end of this file, each print "Closed
    under the global context".  A [Print Assumptions] cannot refuse, so
    these lines are readbacks and guard nothing; the Makefile's
    print-assumptions gate is where closure is kept, and it names all
    ninety-four constants of the three targets.

    NOT PINNED HERE.  (a) [About] readbacks as such: the headers'
    universe censuses, their attributions to first carriers and caps, and
    which donor levels are load-bearing pins (C8 and C8a pin one wall,
    not the censuses).  (b) The flips above, the opaque-dependency censuses
    and the field and normal-form readings behind the CAUSEs: made in
    copies of the dependency closure and in scratch files.  (c) The
    closure of the targets under [Print Assumptions]: a measurement of
    the build rather than of a command.  (d) The absences the headers
    record (no Kleisli category of R ⊗ (−), no isomorphism of categories
    on the nose, no general morphisms of monads, Riehl's Theorem 5.6.5(ii)
    and so her monadic route not in the tree, no tensor–hom adjunction at
    a general ring, no cocompleteness of Ab): an absence has no command;
    N1, N9-N11 and C2, C3 pin the round trips and lifts that the stronger
    readings would need, and C8 and C8a the universe wall.  (e) The readings of
    the books, from their page images.

    CORRECTION (#468).  Of the absences in (d), general morphisms of monads
    now exist: Monad/Morphism.v's [MonadHom] and [Monads C], and
    Monad/Morphism/Algebra.v's θ*, pinned by Test/ProbeMonadMorphism468.v.
    Nothing relates [TensorMonad] to them; the three targets are unchanged,
    and the other absences stand.

    The guard block at the end names the ninety-four constants of the
    three targets, so that a rename breaks this file: fifty of
    Instance/Mod/TensorMonad.v, thirty of Instance/Mod/Colimit/Creation.v
    and fourteen of Instance/Mod/TensorMonad/Cocontinuous.v.  They are
    exactly the entries [Print Module] gives for each (the .glob files'
    [def] and [prf] entries agree); no target declares a record or has a
    [Program] obligation, so there is no [Build_] constructor to add.
    Each is written fully qualified and with [@], so that no short name
    in scope can stand in for it. *)

Require Import Category.Lib.
Require Import Category.Lib.Setoid.Propositional.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Natural.Transformation.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Monad.
Require Import Category.Theory.Equivalence.
Require Import Category.Monad.Algebra.
Require Import Category.Monad.Eilenberg.Moore.
Require Import Category.Monad.Comparison.
Require Import Category.Monad.Monadicity.Beck.
Require Import Category.Structure.Coequalizer.
Require Import Category.Structure.Coequalizer.Split.
Require Import Category.Structure.Limit.Preservation.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Cat.
Require Import Category.Instance.CMon.
Require Import Category.Instance.Ab.
Require Import Category.Instance.Ab.Tensor.
Require Import Category.Instance.Rng.
Require Import Category.Instance.Mod.
Require Import Category.Instance.Mod.BaseChange.
Require Import Category.Theory.Algebra.Rig.
Require Import Coq.ZArith.ZArith.
Require Import Category.Instance.Mod.TensorMonad.
Require Import Category.Construction.Opposite.
Require Import Category.Functor.Opposite.
Require Import Category.Structure.Cone.
Require Import Category.Structure.Limit.
Require Import Category.Structure.Limit.Creation.
Require Import Category.Structure.Limit.Initial.
Require Import Category.Structure.Terminal.
Require Import Category.Structure.AbCategory.
Require Import Category.Instance.Ab.ModFunctor.
Require Import Category.Instance.Mod.Colimit.Creation.
Require Import Category.Adjunction.Compose.
Require Import Category.Adjunction.Continuity.
Require Import Category.Adjunction.Additive.
Require Import Category.Monad.Eilenberg.Moore.Adjunction.
Require Import Category.Instance.Mod.Coextension.
Require Import Category.Instance.Mod.TensorMonad.Cocontinuous.

Generalizable All Variables.

(** ** The instruments *)

(* CONTROL: Mac Lane's μ at a triple, in his order. *)
Example p465_ctl_join@{a c p o x} (R : RingObject@{a c p})
  (A : obj[Ab@{o c}]) (r1 r2 : carrier (rig_setoid (ring_rig R)))
  (a0 : carrier A) :
  cmon_map (@join _ _ (TensorMonad@{a c p o x} R) A)
    (@ts_gen (ring_ab R) (AbTensor (ring_ab R) A) r1
       (@ts_gen (ring_ab R) A r2 a0))
  = @ts_gen (ring_ab R) A (rig_mul (ring_rig R) r1 r2) a0
  := eq_refl.

(* N0 *)
Fail Example p465_N0_instrument@{a c p o x} (R : RingObject@{a c p})
  (A : obj[Ab@{o c}]) (r1 r2 : carrier (rig_setoid (ring_rig R)))
  (a0 : carrier A) :
  cmon_map (@join _ _ (TensorMonad@{a c p o x} R) A)
    (@ts_gen (ring_ab R) (AbTensor (ring_ab R) A) r1
       (@ts_gen (ring_ab R) A r2 a0))
  = @ts_gen (ring_ab R) A (rig_mul (ring_rig R) r2 r1) a0
  := eq_refl.

(* CONTROL: over ℤ, μ (3 ⊗ (4 ⊗ a)) = 12 ⊗ a. *)
Example p465_ctl_join_Z@{o x} (a0 : Z) :
  cmon_map (@join _ _ (TensorMonad@{Set Set Set o x} Int_Ring)
              (ring_ab Int_Ring))
    (@ts_gen (ring_ab Int_Ring)
       (AbTensor (ring_ab Int_Ring) (ring_ab Int_Ring))
       3%Z (@ts_gen (ring_ab Int_Ring) (ring_ab Int_Ring) 4%Z a0))
  = @ts_gen (ring_ab Int_Ring) (ring_ab Int_Ring) 12%Z a0 := eq_refl.

(* N0Z *)
Fail Example p465_N0Z_instrument@{o x} (a0 : Z) :
  cmon_map (@join _ _ (TensorMonad@{Set Set Set o x} Int_Ring)
              (ring_ab Int_Ring))
    (@ts_gen (ring_ab Int_Ring)
       (AbTensor (ring_ab Int_Ring) (ring_ab Int_Ring))
       3%Z (@ts_gen (ring_ab Int_Ring) (ring_ab Int_Ring) 4%Z a0))
  = @ts_gen (ring_ab Int_Ring) (ring_ab Int_Ring) 13%Z a0 := eq_refl.

(** ** Instance/Mod/TensorMonad.v: the module round trip *)

(* CONTROL: the round trip on its group and on its action. *)
Example p465_ctl_rt_ab@{a c p o x} (R : RingObject@{a c p})
  (M : obj[RMod@{o x a p c} R]) :
  rm_ab (fobj[EM_to_RMod@{a c p o x} R
        ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R)] M)
  = rm_ab M
  := eq_refl.

Example p465_ctl_rt_smul@{a c p o x} (R : RingObject@{a c p})
  (M : obj[RMod@{o x a p c} R]) :
  rm_smul (fobj[EM_to_RMod@{a c p o x} R
        ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R)] M)
  = rm_smul M
  := eq_refl.

(* N1 *)
Fail Example p465_N1_rt_obj@{a c p o x} (R : RingObject@{a c p})
  (M : obj[RMod@{o x a p c} R]) :
  fobj[EM_to_RMod@{a c p o x} R
        ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R)] M
  = M
  := eq_refl.

(* N2 *)
Fail Example p465_N2_rt_respects@{a c p o x} (R : RingObject@{a c p})
  (M : obj[RMod@{o x a p c} R]) :
  rm_smul_respects
    (fobj[EM_to_RMod@{a c p o x} R
          ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R)] M)
  = rm_smul_respects M
  := eq_refl.

(* N3 *)
Fail Example p465_N3_rt_distr_l@{a c p o x} (R : RingObject@{a c p})
  (M : obj[RMod@{o x a p c} R]) :
  rm_smul_distr_l
    (fobj[EM_to_RMod@{a c p o x} R
          ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R)] M)
  = rm_smul_distr_l M
  := eq_refl.

(* N4 *)
Fail Example p465_N4_rt_distr_r@{a c p o x} (R : RingObject@{a c p})
  (M : obj[RMod@{o x a p c} R]) :
  rm_smul_distr_r
    (fobj[EM_to_RMod@{a c p o x} R
          ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R)] M)
  = rm_smul_distr_r M
  := eq_refl.

(* N5 *)
Fail Example p465_N5_rt_assoc@{a c p o x} (R : RingObject@{a c p})
  (M : obj[RMod@{o x a p c} R]) :
  rm_smul_assoc
    (fobj[EM_to_RMod@{a c p o x} R
          ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R)] M)
  = rm_smul_assoc M
  := eq_refl.

(* N6 *)
Fail Example p465_N6_rt_one@{a c p o x} (R : RingObject@{a c p})
  (M : obj[RMod@{o x a p c} R]) :
  rm_smul_one
    (fobj[EM_to_RMod@{a c p o x} R
          ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R)] M)
  = rm_smul_one M
  := eq_refl.

(** ** Instance/Mod/TensorMonad.v: the algebra round trip *)

(* CONTROL: the round trip on its carrier, its structure map on each
   generator r ⊗ m, and at every formal sum up to ≈. *)
Example p465_ctl_rt2_carrier@{a c p o x} (R : RingObject@{a c p})
  (X : @EilenbergMoore@{o o x c} Ab@{o c} (TensorF@{a c p o x} R)
         (TensorMonad@{a c p o x} R)) :
  `1 (fobj[EM_Comparison (zext_adjunction@{a c p o o x a a} R)
        ◯ EM_to_RMod@{a c p o x} R] X)
  = `1 X
  := eq_refl.

Example p465_ctl_rt2_gen@{a c p o x} (R : RingObject@{a c p})
  (X : @EilenbergMoore@{o o x c} Ab@{o c} (TensorF@{a c p o x} R)
         (TensorMonad@{a c p o x} R))
  (r : carrier (rig_setoid (ring_rig R))) (m : carrier (`1 X)) :
  cmon_map (t_alg[`2 (fobj[EM_Comparison (zext_adjunction@{a c p o o x a a} R)
          ◯ EM_to_RMod@{a c p o x} R] X)])
    (@ts_gen (ring_ab R) (`1 X) r m)
  = cmon_map (t_alg[`2 X]) (@ts_gen (ring_ab R) (`1 X) r m)
  := eq_refl.

Example p465_ctl_rt2_equiv@{a c p o x} (R : RingObject@{a c p})
  (X : @EilenbergMoore@{o o x c} Ab@{o c} (TensorF@{a c p o x} R)
         (TensorMonad@{a c p o x} R))
  (s : carrier (AbTensor (ring_ab R) (`1 X))) :
  cmon_map (t_alg[`2 (fobj[EM_Comparison (zext_adjunction@{a c p o o x a a} R)
          ◯ EM_to_RMod@{a c p o x} R] X)]) s
  ≈ cmon_map (t_alg[`2 X]) s :=
  ltac:(refine (tensor_hom_ext _ _ _ s); intros r m; reflexivity).

(* N7 *)
Fail Example p465_N7_rt2_fun@{a c p o x} (R : RingObject@{a c p})
  (X : @EilenbergMoore@{o o x c} Ab@{o c} (TensorF@{a c p o x} R)
         (TensorMonad@{a c p o x} R)) :
  (fun s =>
     cmon_map
       (t_alg[`2 (fobj[EM_Comparison (zext_adjunction@{a c p o o x a a} R)
                      ◯ EM_to_RMod@{a c p o x} R] X)]) s)
  = (fun s => cmon_map (t_alg[`2 X]) s)
  := eq_refl.

(* N8 *)
Fail Example p465_N8_rt2_sum@{a c p o x} (R : RingObject@{a c p})
  (X : @EilenbergMoore@{o o x c} Ab@{o c} (TensorF@{a c p o x} R)
         (TensorMonad@{a c p o x} R))
  (s : carrier (AbTensor (ring_ab R) (`1 X))) :
  cmon_map (t_alg[`2 (fobj[EM_Comparison (zext_adjunction@{a c p o o x a a} R)
          ◯ EM_to_RMod@{a c p o x} R] X)]) s
  = cmon_map (t_alg[`2 X]) s
  := eq_refl.

(* N9 *)
Fail Example p465_N9_rt2_obj@{a c p o x} (R : RingObject@{a c p})
  (X : @EilenbergMoore@{o o x c} Ab@{o c} (TensorF@{a c p o x} R)
         (TensorMonad@{a c p o x} R)) :
  fobj[EM_Comparison (zext_adjunction@{a c p o o x a a} R)
        ◯ EM_to_RMod@{a c p o x} R] X
  = X
  := eq_refl.

(** ** Instance/Mod/TensorMonad.v: the composites as identity functors *)

(* N10 *)
Fail Example p465_N10_rt_functor@{a c p o x} (R : RingObject@{a c p}) :
  EM_to_RMod@{a c p o x} R
    ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R)
  = Id[RMod@{o x a p c} R]
  := eq_refl.

(* N11 *)
Fail Example p465_N11_rt2_functor@{a c p o x} (R : RingObject@{a c p}) :
  EM_Comparison (zext_adjunction@{a c p o o x a a} R)
    ◯ EM_to_RMod@{a c p o x} R
  = Id[@EilenbergMoore@{o o x c} Ab@{o c} (TensorF@{a c p o x} R)
         (TensorMonad@{a c p o x} R)]
  := eq_refl.

(** ** Instance/Mod/TensorMonad.v: T f against the bifunctor's 1 ⊗ f *)

(* CONTROL: T f and 1 ⊗ f on a generator, and at every formal sum up
   to ≈. *)
Example p465_ctl_fmap_gen@{a c p o x} (R : RingObject@{a c p})
  (A B : obj[Ab@{o c}]) (f : A ~{Ab@{o c}}~> B)
  (s : carrier (rig_setoid (ring_rig R))) (a0 : carrier A) :
  cmon_map (fmap[TensorF@{a c p o x} R] f) (@ts_gen (ring_ab R) A s a0)
  = cmon_map (tensor_map (@cmon_hom_id (ring_ab R)) f)
      (@ts_gen (ring_ab R) A s a0)
  := eq_refl.

Example p465_ctl_fmap_equiv@{a c p o x} (R : RingObject@{a c p})
  (A B : obj[Ab@{o c}]) (f : A ~{Ab@{o c}}~> B)
  (s : carrier (AbTensor (ring_ab R) A)) :
  cmon_map (fmap[TensorF@{a c p o x} R] f) s
  ≈ cmon_map (tensor_map (@cmon_hom_id (ring_ab R)) f) s :=
  ltac:(refine (tensor_hom_ext _ _ _ s); intros r a0; reflexivity).

(* N12 *)
Fail Example p465_N12_fmap_sum@{a c p o x} (R : RingObject@{a c p})
  (A B : obj[Ab@{o c}]) (f : A ~{Ab@{o c}}~> B)
  (s : carrier (AbTensor (ring_ab R) A)) :
  cmon_map (fmap[TensorF@{a c p o x} R] f) s
  = cmon_map (tensor_map (@cmon_hom_id (ring_ab R)) f) s
  := eq_refl.

(* The [Bilinear] record under Instance/Ab/Tensor.v's [tensor_map] at
   1 ⊗ f, written out with that definition's own three proof terms, so
   that N12's two records can be compared field by field. *)
Definition p465_tm_bilin@{a c p o} (R : RingObject@{a c p})
  {A B : obj[Ab@{o c}]} (f : A ~{Ab@{o c}}~> B) :
  Bilinear@{c c c c c c c c c c c c c} (ring_ab R) A
    (AbTensor (ring_ab R) B) :=
  @Build_Bilinear@{c c c c c c c c c c c c c} (ring_ab R) A
    (AbTensor (ring_ab R) B)
    (fun g h => @ts_gen (ring_ab R) B
                  (cmon_map (@cmon_hom_id (ring_ab R)) g) (cmon_map f h))
    (Category.Instance.Ab.Tensor.tensor_map_obligation_1@{c c c}
       _ _ _ _ (@cmon_hom_id (ring_ab R)) f)
    (Category.Instance.Ab.Tensor.tensor_map_obligation_2@{c c c}
       _ _ _ _ (@cmon_hom_id (ring_ab R)) f)
    (Category.Instance.Ab.Tensor.tensor_map_obligation_3@{c c c}
       _ _ _ _ (@cmon_hom_id (ring_ab R)) f).

(* CONTROL (the cause of N12): [tensor_map] at 1 ⊗ f IS the mediator of
   that record; the two records' maps are one; and each side of N12 is
   the stuck mediator of its own record at the variable sum. *)
Example p465_ctl_n12_record@{a c p o x} (R : RingObject@{a c p})
  (A B : obj[Ab@{o c}]) (f : A ~{Ab@{o c}}~> B) :
  tensor_map (@cmon_hom_id (ring_ab R)) f
  = tensor_ump@{c c c c c c c c c} (p465_tm_bilin R f) := eq_refl.

Example p465_ctl_n12_maps@{a c p o x} (R : RingObject@{a c p})
  (A B : obj[Ab@{o c}]) (f : A ~{Ab@{o c}}~> B) :
  bilin_map (zext_map_bilin R f) = bilin_map (p465_tm_bilin R f)
  := eq_refl.

Example p465_ctl_n12_left@{a c p o x} (R : RingObject@{a c p})
  (A B : obj[Ab@{o c}]) (f : A ~{Ab@{o c}}~> B)
  (s : carrier (AbTensor (ring_ab R) A)) :
  cmon_map (fmap[TensorF@{a c p o x} R] f) s
  = @tensor_med_fun _ _ _ (zext_map_bilin R f) s := eq_refl.

Example p465_ctl_n12_right@{a c p o x} (R : RingObject@{a c p})
  (A B : obj[Ab@{o c}]) (f : A ~{Ab@{o c}}~> B)
  (s : carrier (AbTensor (ring_ab R) A)) :
  cmon_map (tensor_map (@cmon_hom_id (ring_ab R)) f) s
  = @tensor_med_fun _ _ _ (p465_tm_bilin R f) s := eq_refl.

(* N12a *)
Fail Example p465_N12a_records@{a c p o x} (R : RingObject@{a c p})
  (A B : obj[Ab@{o c}]) (f : A ~{Ab@{o c}}~> B) :
  zext_map_bilin R f = p465_tm_bilin R f := eq_refl.

(* N12b *)
Fail Example p465_N12b_respects@{a c p o x} (R : RingObject@{a c p})
  (A B : obj[Ab@{o c}]) (f : A ~{Ab@{o c}}~> B) :
  bilin_respects (zext_map_bilin R f) = bilin_respects (p465_tm_bilin R f)
  := eq_refl.

(* N12c *)
Fail Example p465_N12c_add_l@{a c p o x} (R : RingObject@{a c p})
  (A B : obj[Ab@{o c}]) (f : A ~{Ab@{o c}}~> B) :
  bilin_add_l (zext_map_bilin R f) = bilin_add_l (p465_tm_bilin R f)
  := eq_refl.

(* N12d *)
Fail Example p465_N12d_add_r@{a c p o x} (R : RingObject@{a c p})
  (A B : obj[Ab@{o c}]) (f : A ~{Ab@{o c}}~> B) :
  bilin_add_r (zext_map_bilin R f) = bilin_add_r (p465_tm_bilin R f)
  := eq_refl.

(** ** Instance/Mod/TensorMonad.v: Beck's route *)

(* CONTROL: Beck's quasi-inverse acts through η; over ℤ at the scalar 3
   it IS h (3 ⊗ m). *)
Example p465_ctl_beck_act@{a c p o x} (R : RingObject@{a c p})
  (X : @EilenbergMoore@{o o x c} Ab@{o c} (TensorF@{a c p o x} R)
         (TensorMonad@{a c p o x} R))
  (r : carrier (rig_setoid (ring_rig R))) (m : carrier (`1 X)) :
  rm_smul
    (fobj[@quasi_inverse _ _ _ (RMod_beck_equivalence@{a c p o x} R)] X)
    r m
  = cmon_map (t_alg[`2 X])
      (@ts_gen (ring_ab R) (`1 X)
         (rig_mul (ring_rig R) r (rig_one (ring_rig R))) m)
  := eq_refl.

Example p465_ctl_beck_act_Z@{o x}
  (X : @EilenbergMoore@{o o x Set} Ab@{o Set}
         (TensorF@{Set Set Set o x} Int_Ring)
         (TensorMonad@{Set Set Set o x} Int_Ring))
  (m : carrier (`1 X)) :
  rm_smul
    (fobj[@quasi_inverse _ _ _
            (RMod_beck_equivalence@{Set Set Set o x} Int_Ring)] X) 3%Z m
  = cmon_map (t_alg[`2 X]) (@ts_gen (ring_ab Int_Ring) (`1 X) 3%Z m)
  := eq_refl.

(* N13Z *)
Fail Example p465_N13Z_beck_act_var@{o x}
  (X : @EilenbergMoore@{o o x Set} Ab@{o Set}
         (TensorF@{Set Set Set o x} Int_Ring)
         (TensorMonad@{Set Set Set o x} Int_Ring))
  (z : Z) (m : carrier (`1 X)) :
  rm_smul
    (fobj[@quasi_inverse _ _ _
            (RMod_beck_equivalence@{Set Set Set o x} Int_Ring)] X) z m
  = cmon_map (t_alg[`2 X]) (@ts_gen (ring_ab Int_Ring) (`1 X) z m)
  := eq_refl.

(* N13 *)
Fail Example p465_N13_beck_act_strict@{a c p o x} (R : RingObject@{a c p})
  (X : @EilenbergMoore@{o o x c} Ab@{o c} (TensorF@{a c p o x} R)
         (TensorMonad@{a c p o x} R))
  (r : carrier (rig_setoid (ring_rig R))) (m : carrier (`1 X)) :
  rm_smul
    (fobj[@quasi_inverse _ _ _ (RMod_beck_equivalence@{a c p o x} R)] X)
    r m
  = cmon_map (t_alg[`2 X]) (@ts_gen (ring_ab R) (`1 X) r m)
  := eq_refl.

(* N14 *)
Fail Example p465_N14_beck_qi@{a c p o x} (R : RingObject@{a c p}) :
  @quasi_inverse _ _ _ (RMod_beck_equivalence@{a c p o x} R)
  = EM_to_RMod@{a c p o x} R
  := eq_refl.

(* CONTROL: the two witnesses inhabit one type. *)
Example p465_ctl_monadic_type@{a c p o x} (R : RingObject@{a c p}) :
  @Monadic@{o x o o o c o a} (RMod@{o x a p c} R) Ab@{o c}
    (RMod_Forget_Ab@{x o o a p c} R)
  * @Monadic@{o x o o o c o a} (RMod@{o x a p c} R) Ab@{o c}
      (RMod_Forget_Ab@{x o o a p c} R)
  := (RMod_Forget_Ab_Monadic_beck@{a c p o x} R,
      RMod_Forget_Ab_Monadic@{a c p o x} R).

(* N15 *)
Fail Example p465_N15_monadic_same@{a c p o x} (R : RingObject@{a c p}) :
  RMod_Forget_Ab_Monadic_beck@{a c p o x} R
  = RMod_Forget_Ab_Monadic@{a c p o x} R
  := eq_refl.

(** ** Instance/Mod/Colimit/Creation.v *)

(* C0 *)
Fail Fail Example p465c_C0_instrument@{a c p o x j l l0}
  {R : RingObject@{a c p}}
  {J : Category@{j c c}} {K : J ⟶ RMod@{o x a p c} R}
  (N : Cone ((RMod_Forget_Ab@{x o o a p c} R)^op ◯ K^op))
  (HN : IsLimitCone@{l l0 j c o} N) :
  rm_ab (ColimMod N HN) = vertex_obj[N] := eq_refl.

(* CONTROL: the created module's group and insertions, and the action on
   an inserted element up to ≈. *)
Example p465c_ctl_obj@{a c p o x j l l0} {R : RingObject@{a c p}}
  {J : Category@{j c c}} {K : J ⟶ RMod@{o x a p c} R}
  (N : Cone ((RMod_Forget_Ab@{x o o a p c} R)^op ◯ K^op))
  (HN : IsLimitCone@{l l0 j c o} N) :
  rm_ab (ColimMod N HN) = vertex_obj[N] := eq_refl.

Example p465c_ctl_legs@{a c p o x j l l0} {R : RingObject@{a c p}}
  {J : Category@{j c c}} {K : J ⟶ RMod@{o x a p c} R}
  (N : Cone ((RMod_Forget_Ab@{x o o a p c} R)^op ◯ K^op))
  (HN : IsLimitCone@{l l0 j c o} N) (i : J) :
  rm_hom (mcol_hom N HN i) = cone_leg N i := eq_refl.

Example p465c_ctl_leg_smul@{a c p o x j l l0} {R : RingObject@{a c p}}
  {J : Category@{j c c}} {K : J ⟶ RMod@{o x a p c} R}
  (N : Cone ((RMod_Forget_Ab@{x o o a p c} R)^op ◯ K^op))
  (HN : IsLimitCone@{l l0 j c o} N)
  (r : carrier (rig_setoid (ring_rig R)))
  (i : J) (m : carrier (rm_ab (K i))) :
  rm_smul (ColimMod N HN) r (cmon_map (cone_leg N i) m)
  ≈ cmon_map (cone_leg N i) (rm_smul (K i) r m) :=
  mcol_smul_triangle N HN r i m.

(* C1 *)
Fail Example p465c_C1_leg_smul@{a c p o x j l l0} {R : RingObject@{a c p}}
  {J : Category@{j c c}} {K : J ⟶ RMod@{o x a p c} R}
  (N : Cone ((RMod_Forget_Ab@{x o o a p c} R)^op ◯ K^op))
  (HN : IsLimitCone@{l l0 j c o} N)
  (r : carrier (rig_setoid (ring_rig R)))
  (i : J) (m : carrier (rm_ab (K i))) :
  rm_smul (ColimMod N HN) r (cmon_map (cone_leg N i) m)
  = cmon_map (cone_leg N i) (rm_smul (K i) r m) := eq_refl.

(* CONTROL: the module reflected from a cocone M of modules has M's
   group, and its mediators compute to the Ab ones. *)
Example p465c_ctl_reflect_group@{a c p o x j l l0} {R : RingObject@{a c p}}
  {J : Category@{j c c}} {K : J ⟶ RMod@{o x a p c} R}
  (M : Cone (K^op))
  (HM : IsLimitCone@{l l0 j c o}
          (FCone ((RMod_Forget_Ab@{x o o a p c} R)^op) M)) :
  rm_ab (ColimMod (FCone ((RMod_Forget_Ab@{x o o a p c} R)^op) M) HM)
  = rm_ab (vertex_obj[M]) := eq_refl.

Example p465c_ctl_reflect_mediator@{a c p o x j l l0}
  {R : RingObject@{a c p}}
  {J : Category@{j c c}} {K : J ⟶ RMod@{o x a p c} R}
  (M : Cone (K^op))
  (HM : IsLimitCone@{l l0 j c o}
          (FCone ((RMod_Forget_Ab@{x o o a p c} R)^op) M))
  (P : Cone (K^op)) :
  rm_hom (unique_obj (mcol_reflect M HM P))
  = unique_obj (HM (FCone ((RMod_Forget_Ab@{x o o a p c} R)^op) P))
  := eq_refl.

(* C2 *)
Fail Example p465c_C2_reflect_is_self@{a c p o x j l l0}
  {R : RingObject@{a c p}}
  {J : Category@{j c c}} {K : J ⟶ RMod@{o x a p c} R}
  (M : Cone (K^op))
  (HM : IsLimitCone@{l l0 j c o}
          (FCone ((RMod_Forget_Ab@{x o o a p c} R)^op) M)) :
  ColimMod (FCone ((RMod_Forget_Ab@{x o o a p c} R)^op) M) HM
  = vertex_obj[M] := eq_refl.

(* CONTROL: two colimit witnesses of one cocone act alike up to ≈. *)
Example p465c_ctl_two_witnesses@{a c p o x j l l0} {R : RingObject@{a c p}}
  {J : Category@{j c c}} {K : J ⟶ RMod@{o x a p c} R}
  (N : Cone ((RMod_Forget_Ab@{x o o a p c} R)^op ◯ K^op))
  (HN HN' : IsLimitCone@{l l0 j c o} N)
  (r : carrier (rig_setoid (ring_rig R)))
  (b : carrier (@vertex_obj _ _ _ N)) :
  mcol_smul N HN' r b ≈ mcol_smul N HN r b :=
  mcol_smul_unique N HN (mcol_smul_map N HN')
    (fun i r' m => mcol_smul_triangle N HN' r' i m) r b.

(* C3 *)
Fail Example p465c_C3_two_witnesses@{a c p o x j l l0}
  {R : RingObject@{a c p}}
  {J : Category@{j c c}} {K : J ⟶ RMod@{o x a p c} R}
  (N : Cone ((RMod_Forget_Ab@{x o o a p c} R)^op ◯ K^op))
  (HN HN' : IsLimitCone@{l l0 j c o} N) :
  ColimMod N HN = ColimMod N HN' := eq_refl.

(* CONTROL: the lift read back through [creates_colimit_lift] has the
   given nadir as its group and IS [ColimMod] of the colimit read in the
   opposite category. *)
Example p465c_ctl_lift_apex@{a c p o x j l l0} {R : RingObject@{a c p}}
  {J : Category@{j c c}} (K : J ⟶ RMod@{o x a p c} R)
  (L : Colimit (RMod_Forget_Ab@{x o o a p c} R ◯ K)) :
  rm_ab (vertex_obj[creates_colimit_lift
           (RMod_Forget_Ab_CreatesColimit@{a c p o x j l l0} K) L])
  = vertex_obj[L] := eq_refl.

Example p465c_ctl_lift_module@{a c p o x j l l0} {R : RingObject@{a c p}}
  {J : Category@{j c c}} (K : J ⟶ RMod@{o x a p c} R)
  (L : Colimit (RMod_Forget_Ab@{x o o a p c} R ◯ K)) :
  vertex_obj[creates_colimit_lift
     (RMod_Forget_Ab_CreatesColimit@{a c p o x j l l0} K) L]
  = ColimMod (cone_op_comp (@limit_cone _ _ _ L))
      (islimitcone_op_comp (limit_limitcone L)) := eq_refl.

(* CONTROL: at a shape with a terminal object the created action is
   K(!)(r · m) on the nose and K 1's own up to ≈. *)
Example p465c_ctl_terminal_smul@{a c p o x j l l0} {R : RingObject@{a c p}}
  {J : Category@{j c c}} (T : @Terminal J) (K : J ⟶ RMod@{o x a p c} R)
  (r : carrier (rig_setoid (ring_rig R)))
  (m : carrier (rm_ab (K (@terminal_obj J T)))) :
  rm_smul (vertex_obj[@limit_cone _ _ _
             (rmod_terminal_colimit@{a c p o x j l l0} T K)]) r m
  = cmon_map (rm_hom (fmap[K] (@one J T (@terminal_obj J T))))
      (rm_smul (K (@terminal_obj J T)) r m) := eq_refl.

Example p465c_ctl_terminal_own@{a c p o x j l l0} {R : RingObject@{a c p}}
  {J : Category@{j c c}} (T : @Terminal J) (K : J ⟶ RMod@{o x a p c} R)
  (r : carrier (rig_setoid (ring_rig R)))
  (m : carrier (rm_ab (K (@terminal_obj J T)))) :
  rm_smul (vertex_obj[@limit_cone _ _ _
             (rmod_terminal_colimit@{a c p o x j l l0} T K)]) r m
  ≈ rm_smul (K (@terminal_obj J T)) r m :=
  rmod_terminal_smul_own T K r m.

(* C4 *)
Fail Example p465c_C4_terminal_own@{a c p o x j l l0}
  {R : RingObject@{a c p}}
  {J : Category@{j c c}} (T : @Terminal J) (K : J ⟶ RMod@{o x a p c} R)
  (r : carrier (rig_setoid (ring_rig R)))
  (m : carrier (rm_ab (K (@terminal_obj J T)))) :
  rm_smul (vertex_obj[@limit_cone _ _ _
             (rmod_terminal_colimit@{a c p o x j l l0} T K)]) r m
  = rm_smul (K (@terminal_obj J T)) r m := eq_refl.

(** ** Instance/Mod/TensorMonad/Cocontinuous.v *)

(* CONTROL: the transpose at a generator with the unit, on the nose; without
   it, up to ≈; and over ℤ at the scalar 3 without it, on the nose. *)
Example p465c_ctl_to@{c o x} (R : RingObject@{c c c})
  (A B : obj[Ab@{o c}])
  (φ : fobj[TensorF@{c c c o x} R] A ~{Ab@{o c}}~> B)
  (a : carrier (cmon_setoid A)) (r : carrier (rig_setoid (ring_rig R))) :
  @cmon_map (ab_cmon (ring_ab R)) (ab_cmon B)
    (cmon_map (to (@adj _ _ _ _ (TensorF_left_adjoint@{c o x} R) A B) φ) a)
    r
  = cmon_map φ (@ts_gen (ring_ab R) A
                  (rig_mul (ring_rig R) r (rig_one (ring_rig R))) a)
  := eq_refl.

Example p465c_ctl_to_gen@{c o x} (R : RingObject@{c c c})
  (A B : obj[Ab@{o c}])
  (φ : fobj[TensorF@{c c c o x} R] A ~{Ab@{o c}}~> B)
  (a : carrier (cmon_setoid A)) (r : carrier (rig_setoid (ring_rig R))) :
  @cmon_map (ab_cmon (ring_ab R)) (ab_cmon B)
    (cmon_map (to (@adj _ _ _ _ (TensorF_left_adjoint@{c o x} R) A B) φ) a)
    r
  ≈ cmon_map φ (@ts_gen (ring_ab R) A r a) :=
  tensor_hom_to_gen R A B φ a r.

Example p465c_ctl_to_Z@{o x} (A B : obj[Ab@{o Set}])
  (φ : fobj[TensorF@{Set Set Set o x} Int_Ring] A ~{Ab@{o Set}}~> B)
  (a : carrier (cmon_setoid A)) :
  @cmon_map (ab_cmon (ring_ab Int_Ring)) (ab_cmon B)
    (cmon_map (to (@adj _ _ _ _
       (TensorF_left_adjoint@{Set o x} Int_Ring) A B) φ) a) 3%Z
  = cmon_map φ (@ts_gen (ring_ab Int_Ring) A 3%Z a) := eq_refl.

(* C5Z *)
Fail Example p465c_C5Z_to_var@{o x} (A B : obj[Ab@{o Set}])
  (φ : fobj[TensorF@{Set Set Set o x} Int_Ring] A ~{Ab@{o Set}}~> B)
  (a : carrier (cmon_setoid A)) (z : Z) :
  @cmon_map (ab_cmon (ring_ab Int_Ring)) (ab_cmon B)
    (cmon_map (to (@adj _ _ _ _
       (TensorF_left_adjoint@{Set o x} Int_Ring) A B) φ) a) z
  = cmon_map φ (@ts_gen (ring_ab Int_Ring) A z a) := eq_refl.

(* C5 *)
Fail Example p465c_C5_to@{c o x} (R : RingObject@{c c c})
  (A B : obj[Ab@{o c}])
  (φ : fobj[TensorF@{c c c o x} R] A ~{Ab@{o c}}~> B)
  (a : carrier (cmon_setoid A)) (r : carrier (rig_setoid (ring_rig R))) :
  @cmon_map (ab_cmon (ring_ab R)) (ab_cmon B)
    (cmon_map (to (@adj _ _ _ _ (TensorF_left_adjoint@{c o x} R) A B) φ) a)
    r
  = cmon_map φ (@ts_gen (ring_ab R) A r a) := eq_refl.

(* CONTROL: the inverse transpose, the same three ways. *)
Example p465c_ctl_from@{c o x} (R : RingObject@{c c c})
  (A B : obj[Ab@{o c}])
  (ψ : A ~{Ab@{o c}}~>
         fobj[RMod_Forget_Ab@{x o o c c c} R ◯ Coextension@{c c c o x} R] B)
  (a : carrier (cmon_setoid A)) (r : carrier (rig_setoid (ring_rig R))) :
  cmon_map (from (@adj _ _ _ _ (TensorF_left_adjoint@{c o x} R) A B) ψ)
    (@ts_gen (ring_ab R) A r a)
  = @cmon_map (ab_cmon (ring_ab R)) (ab_cmon B) (cmon_map ψ a)
      (rig_mul (ring_rig R) (rig_one (ring_rig R)) r) := eq_refl.

Example p465c_ctl_from_gen@{c o x} (R : RingObject@{c c c})
  (A B : obj[Ab@{o c}])
  (ψ : A ~{Ab@{o c}}~>
         fobj[RMod_Forget_Ab@{x o o c c c} R ◯ Coextension@{c c c o x} R] B)
  (a : carrier (cmon_setoid A)) (r : carrier (rig_setoid (ring_rig R))) :
  cmon_map (from (@adj _ _ _ _ (TensorF_left_adjoint@{c o x} R) A B) ψ)
    (@ts_gen (ring_ab R) A r a)
  ≈ @cmon_map (ab_cmon (ring_ab R)) (ab_cmon B) (cmon_map ψ a) r :=
  tensor_hom_from_gen R A B ψ a r.

Example p465c_ctl_from_Z@{o x} (A B : obj[Ab@{o Set}])
  (ψ : A ~{Ab@{o Set}}~>
     fobj[RMod_Forget_Ab@{x o o Set Set Set} Int_Ring
          ◯ Coextension@{Set Set Set o x} Int_Ring] B)
  (a : carrier (cmon_setoid A)) :
  cmon_map (from (@adj _ _ _ _
     (TensorF_left_adjoint@{Set o x} Int_Ring) A B) ψ)
    (@ts_gen (ring_ab Int_Ring) A 3%Z a)
  = @cmon_map (ab_cmon (ring_ab Int_Ring)) (ab_cmon B) (cmon_map ψ a) 3%Z
  := eq_refl.

(* C6Z *)
Fail Example p465c_C6Z_from_var@{o x} (A B : obj[Ab@{o Set}])
  (ψ : A ~{Ab@{o Set}}~>
     fobj[RMod_Forget_Ab@{x o o Set Set Set} Int_Ring
          ◯ Coextension@{Set Set Set o x} Int_Ring] B)
  (a : carrier (cmon_setoid A)) (z : Z) :
  cmon_map (from (@adj _ _ _ _
     (TensorF_left_adjoint@{Set o x} Int_Ring) A B) ψ)
    (@ts_gen (ring_ab Int_Ring) A z a)
  = @cmon_map (ab_cmon (ring_ab Int_Ring)) (ab_cmon B) (cmon_map ψ a) z
  := eq_refl.

(* C6 *)
Fail Example p465c_C6_from@{c o x} (R : RingObject@{c c c})
  (A B : obj[Ab@{o c}])
  (ψ : A ~{Ab@{o c}}~>
         fobj[RMod_Forget_Ab@{x o o c c c} R ◯ Coextension@{c c c o x} R] B)
  (a : carrier (cmon_setoid A)) (r : carrier (rig_setoid (ring_rig R))) :
  cmon_map (from (@adj _ _ _ _ (TensorF_left_adjoint@{c o x} R) A B) ψ)
    (@ts_gen (ring_ab R) A r a)
  = @cmon_map (ab_cmon (ring_ab R)) (ab_cmon B) (cmon_map ψ a) r
  := eq_refl.

(* CONTROL: U^T ◯ K against U on objects and arrows on the nose, and as
   functors up to ≈. *)
Example p465c_ctl_cmp_obj@{a c p o x} (R : RingObject@{a c p})
  (M : obj[RMod@{o x a p c} R]) :
  fobj[EM_Forget (TensorF@{a c p o x} R)
         ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R)] M
  = fobj[RMod_Forget_Ab@{x o o a p c} R] M := eq_refl.

Example p465c_ctl_cmp_map@{a c p o x} (R : RingObject@{a c p})
  (M N : obj[RMod@{o x a p c} R]) (f : M ~{RMod@{o x a p c} R}~> N) :
  fmap[EM_Forget (TensorF@{a c p o x} R)
         ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R)] f
  = fmap[RMod_Forget_Ab@{x o o a p c} R] f := eq_refl.

Example p465c_ctl_cmp@{a c p o x} (R : RingObject@{a c p}) :
  EM_Forget (TensorF@{a c p o x} R)
    ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R)
  ≈ RMod_Forget_Ab@{x o o a p c} R :=
  rmod_forget_comparison R.

(* C7 *)
Fail Example p465c_C7_forget_record@{a c p o x} (R : RingObject@{a c p}) :
  EM_Forget (TensorF@{a c p o x} R)
    ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R)
  = RMod_Forget_Ab@{x o o a p c} R := eq_refl.

(* C7a *)
Fail Example p465c_C7a_fmap_respects@{a c p o x} (R : RingObject@{a c p}) :
  @fmap_respects _ _ (EM_Forget (TensorF@{a c p o x} R)
    ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R))
  = @fmap_respects _ _ (RMod_Forget_Ab@{x o o a p c} R) := eq_refl.

(* C7b *)
Fail Example p465c_C7b_fmap_id@{a c p o x} (R : RingObject@{a c p}) :
  @fmap_id _ _ (EM_Forget (TensorF@{a c p o x} R)
    ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R))
  = @fmap_id _ _ (RMod_Forget_Ab@{x o o a p c} R) := eq_refl.

(* C7c *)
Fail Example p465c_C7c_fmap_comp@{a c p o x} (R : RingObject@{a c p}) :
  @fmap_comp _ _ (EM_Forget (TensorF@{a c p o x} R)
    ◯ EM_Comparison (zext_adjunction@{a c p o o x a a} R))
  = @fmap_comp _ _ (RMod_Forget_Ab@{x o o a p c} R) := eq_refl.

(* CONTROL: the tensor–hom adjunction at [RingObject@{c c c}]. *)
Definition p465c_ctl_ring_ccc@{c o x} (R : RingObject@{c c c}) :
  @Adjunction@{o c c o c c c c x c o} Ab@{o c} Ab@{o c}
    (TensorF@{c c c o x} R)
    (RMod_Forget_Ab@{x o o c c c} R ◯ Coextension@{c c c o x} R) :=
  Adjunction_Compose (zext_adjunction@{c c c o o x c c} R)
    (coex_adjunction@{c c c o x c} R).

(* CONTROL (for C8 and C8a): at [RingObject@{a c p}] under an extensible
   binder the same composite is accepted, elaboration adding a = c and
   a = p. *)
Definition p465c_ctl_ring_open@{a c p o x | Set < o, c < o, c < x +}
  (R : RingObject@{a c p}) :
  @Adjunction@{o c c o c c c c x c o} Ab@{o c} Ab@{o c}
    (TensorF@{a c p o x} R)
    (RMod_Forget_Ab@{x o o a p c} R ◯ Coextension@{a c p o x} R) :=
  Adjunction_Compose (zext_adjunction@{a c p o o x a a} R)
    (coex_adjunction@{a c p o x c} R).

(* C8 *)
Fail Definition p465c_C8_carrier_below@{a c p o x |
    Set < o, c < o, c < x, c < a +}
  (R : RingObject@{a c p}) :
  @Adjunction@{o c c o c c c c x c o} Ab@{o c} Ab@{o c}
    (TensorF@{a c p o x} R)
    (RMod_Forget_Ab@{x o o a p c} R ◯ Coextension@{a c p o x} R) :=
  Adjunction_Compose (zext_adjunction@{a c p o o x a a} R)
    (coex_adjunction@{a c p o x c} R).

(* C8a *)
Fail Definition p465c_C8a_proof_below@{a c p o x |
    Set < o, c < o, c < x, p < a +}
  (R : RingObject@{a c p}) :
  @Adjunction@{o c c o c c c c x c o} Ab@{o c} Ab@{o c}
    (TensorF@{a c p o x} R)
    (RMod_Forget_Ab@{x o o a p c} R ◯ Coextension@{a c p o x} R) :=
  Adjunction_Compose (zext_adjunction@{a c p o o x a a} R)
    (coex_adjunction@{a c p o x c} R).

(** ** Closure: a readback, not a refutation *)

Print Assumptions TensorMonad.
Print Assumptions EM_RMod_iso.
Print Assumptions RMod_Forget_Ab_Monadic.
Print Assumptions RMod_Forget_Ab_Monadic_beck.
Print Assumptions RMod_Forget_Ab_creates_colimits.
Print Assumptions TensorF_cocontinuous.
Print Assumptions TensorF2_cocontinuous.

(** ** Guard: the constants of the three targets *)

(* Instance/Mod/TensorMonad.v *)
Check @Category.Instance.Mod.TensorMonad.TensorF.
Check @Category.Instance.Mod.TensorMonad.TensorMonad.
Check @Category.Instance.Mod.TensorMonad.TensorF_obj.
Check @Category.Instance.Mod.TensorMonad.TensorF_map.
Check @Category.Instance.Mod.TensorMonad.TensorMonad_ret.
Check @Category.Instance.Mod.TensorMonad.TensorMonad_join.
Check @Category.Instance.Mod.TensorMonad.TensorMonad_join_counit.
Check @Category.Instance.Mod.TensorMonad.TensorMonad_join_gen.
Check @Category.Instance.Mod.TensorMonad.TensorMonad_join_Z.
Check @Category.Instance.Mod.TensorMonad.em_smul.
Check @Category.Instance.Mod.TensorMonad.em_smul_respects.
Check @Category.Instance.Mod.TensorMonad.em_smul_distr_l.
Check @Category.Instance.Mod.TensorMonad.em_smul_distr_r.
Check @Category.Instance.Mod.TensorMonad.em_smul_assoc.
Check @Category.Instance.Mod.TensorMonad.em_smul_one.
Check @Category.Instance.Mod.TensorMonad.EM_mod.
Check @Category.Instance.Mod.TensorMonad.EM_mod_hom.
Check @Category.Instance.Mod.TensorMonad.EM_to_RMod.
Check @Category.Instance.Mod.TensorMonad.EM_mod_smul.
Check @Category.Instance.Mod.TensorMonad.RMod_counit_iso.
Check @Category.Instance.Mod.TensorMonad.RMod_unit_iso.
Check @Category.Instance.Mod.TensorMonad.RMod_comparison_equivalence.
Check @Category.Instance.Mod.TensorMonad.RMod_Forget_Ab_Monadic.
Check @Category.Instance.Mod.TensorMonad.EM_RMod_iso.
Check @Category.Instance.Mod.TensorMonad.EM_RMod_iso_to.
Check @Category.Instance.Mod.TensorMonad.EM_RMod_iso_from.
Check @Category.Instance.Mod.TensorMonad.comparison_alg_is_smul.
Check @Category.Instance.Mod.TensorMonad.comparison_alg_counit.
Check @Category.Instance.Mod.TensorMonad.rmod_split_absorb.
Check @Category.Instance.Mod.TensorMonad.rmod_created_smul.
Check @Category.Instance.Mod.TensorMonad.rmod_created_absorb.
Check @Category.Instance.Mod.TensorMonad.RModCreated.
Check @Category.Instance.Mod.TensorMonad.RModCreatedE.
Check @Category.Instance.Mod.TensorMonad.RModCreatedE_is_coeq.
Check @Category.Instance.Mod.TensorMonad.RModReflected_is_coeq.
Check @Category.Instance.Mod.TensorMonad.RMod_Forget_Ab_creates_split.
Check @Category.Instance.Mod.TensorMonad.rmod_created_carrier.
Check @Category.Instance.Mod.TensorMonad.rmod_created_action.
Check @Category.Instance.Mod.TensorMonad.rmod_created_arrow.
Check @Category.Instance.Mod.TensorMonad.rmod_created_iso.
Check @Category.Instance.Mod.TensorMonad.RMod_Forget_Ab_reflects.
Check @Category.Instance.Mod.TensorMonad.RMod_beck_equivalence.
Check @Category.Instance.Mod.TensorMonad.RMod_Forget_Ab_Monadic_beck.
Check @Category.Instance.Mod.TensorMonad.EM_RMod_iso_beck.
Check @Category.Instance.Mod.TensorMonad.EM_RMod_iso_beck_to.
Check @Category.Instance.Mod.TensorMonad.rmod_beck_direct_to.
Check @Category.Instance.Mod.TensorMonad.rmod_beck_carrier.
Check @Category.Instance.Mod.TensorMonad.rmod_beck_act.
Check @Category.Instance.Mod.TensorMonad.rmod_beck_vs_direct_iso.
Check @Category.Instance.Mod.TensorMonad.rmod_beck_vs_direct.

(* Instance/Mod/Colimit/Creation.v *)
Check @Category.Instance.Mod.Colimit.Creation.mcol_ext.
Check @Category.Instance.Mod.Colimit.Creation.mcol_smul_cone.
Check @Category.Instance.Mod.Colimit.Creation.mcol_smul_map.
Check @Category.Instance.Mod.Colimit.Creation.mcol_smul_triangle.
Check @Category.Instance.Mod.Colimit.Creation.mcol_smul.
Check @Category.Instance.Mod.Colimit.Creation.mcol_smul_respects.
Check @Category.Instance.Mod.Colimit.Creation.mcol_smul_distr_l.
Check @Category.Instance.Mod.Colimit.Creation.mcol_smul_distr_r.
Check @Category.Instance.Mod.Colimit.Creation.mcol_smul_assoc.
Check @Category.Instance.Mod.Colimit.Creation.mcol_smul_one.
Check @Category.Instance.Mod.Colimit.Creation.ColimMod.
Check @Category.Instance.Mod.Colimit.Creation.mcol_hom.
Check @Category.Instance.Mod.Colimit.Creation.mcol_cone.
Check @Category.Instance.Mod.Colimit.Creation.mcol_reflect.
Check @Category.Instance.Mod.Colimit.Creation.mcol_strict_lift.
Check @Category.Instance.Mod.Colimit.Creation.RMod_Forget_Ab_StrictlyCreatesColimit.
Check @Category.Instance.Mod.Colimit.Creation.RMod_Forget_Ab_CreatesColimit.
Check @Category.Instance.Mod.Colimit.Creation.RMod_Forget_Ab_creates_colimits.
Check @Category.Instance.Mod.Colimit.Creation.mcol_over_obj.
Check @Category.Instance.Mod.Colimit.Creation.mcol_over_legs.
Check @Category.Instance.Mod.Colimit.Creation.mcol_smul_is_mediator.
Check @Category.Instance.Mod.Colimit.Creation.mcol_lift_apex.
Check @Category.Instance.Mod.Colimit.Creation.mcol_lift_legs.
Check @Category.Instance.Mod.Colimit.Creation.mcol_lift_module.
Check @Category.Instance.Mod.Colimit.Creation.mcol_reflect_mediator.
Check @Category.Instance.Mod.Colimit.Creation.mcol_smul_unique.
Check @Category.Instance.Mod.Colimit.Creation.rmod_terminal_colimit.
Check @Category.Instance.Mod.Colimit.Creation.rmod_terminal_group.
Check @Category.Instance.Mod.Colimit.Creation.rmod_terminal_smul.
Check @Category.Instance.Mod.Colimit.Creation.rmod_terminal_smul_own.

(* Instance/Mod/TensorMonad/Cocontinuous.v *)
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.TensorF_left_adjoint.
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.TensorF_right_adjoint_obj.
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.tensor_hom_to.
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.tensor_hom_to_gen.
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.tensor_hom_from.
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.tensor_hom_from_gen.
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.TensorF2_left_adjoint.
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.TensorF_cocontinuous.
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.TensorF2_cocontinuous.
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.TensorF_preserves_colimits.
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.TensorF2_preserves_colimits.
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.rmod_forget_comparison_obj.
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.rmod_forget_comparison_map.
Check @Category.Instance.Mod.TensorMonad.Cocontinuous.rmod_forget_comparison.
