(** * Probe for the monoid monad W₀ and its algebras (issue #471)

    Pins the measured boundaries of what #471 adds for Mac Lane, §VI.4,
    Exercise 1, book p. 146 (PDF p. 155), catalog item maclane:VI.4:ex1,
    read from the page image ("Let W₀ be the monad in Set defined by the
    forgetful functor Mon→Set.  Show that a W₀-algebra is a set M with a
    string ν₀, ν₁, … of n-ary operations νₙ, where ν₀ : * → M is the unit
    of the monoid M and νₙ is the n-fold product"), with the items the
    issue appends: Awodey's Example 10.7 and Exercise 10.6.6
    (awodey:10.3:example7, awodey:10:ex6) and Riehl's Examples 5.1.4(ii),
    5.1.5(ii), 5.2.6(iii) and 5.2.11(ii) (riehl:5.1:example4,
    riehl:5.1:example5, riehl:5.2:example6, riehl:5.2:example11).  The
    targets are the hom-set form of the free monoid adjunction that #471
    adds to Instance/Mon/Free.v, Instance/Mon/Word.v (W₀, an algebra as a
    monoid, Mon ≅ Set^{W₀}, monadicity, the forgetful functors, the
    Kleisli category), Instance/Mon/Word/System.v (Mac Lane's ν₀, ν₁, …)
    and Instance/CMon/Free.v (the free commutative monoid and its monad).
    Their headers cite the refutations and controls here: Instance/Mon/
    Free.v R1, R2, C1 to C3; Instance/Mon/Word.v R3 to R14, C5 to C57;
    Instance/Mon/Word/System.v R15 to R21, C58 to C83; Instance/CMon/
    Free.v R22 to R26, C84 to C108.  Each of the ninety-six [Example]s of
    the targets, all proved by [eq_refl], has a control that restates it
    independently of the constant that states it (RESTATEMENTS, below).

    THE IMPORT LIST, generated by a script over the [Require] lines.
    Target by target in dependency order: Instance/Mon/Free.v's eleven
    [Require] lines in its own order, and that target; the nine lines
    Instance/Mon/Word.v adds, and that target; the one line
    Instance/Mon/Word/System.v adds, and that target; the three lines
    Instance/CMon/Free.v adds, and that target.  Twenty-eight lines, all
    naming [Category] modules.  Under them [Print Libraries] in a scratch
    file loads sixty-four [Category] modules, exactly the set a [Require]
    of the four targets alone loads (compared by script).  A shorter
    import list is what makes a probe pass for no reason.

    DISCIPLINE.  Every negative other than the instrument is an
    [Example], never a [Check], so that an open evar cannot satisfy it.
    Each of the twenty-seven refutation lines (the instrument and R1 to
    R26) was stripped of its refutation keyword in a copy of this WHOLE
    file, one at a time, compiled, and its error read; each copy stops
    inside the stripped command (twenty-seven of twenty-seven, by the File
    line of its error, compared by script with the command's extent).
    Each of the one hundred and eight controls, wrapped in the refutation
    keyword in a copy of this WHOLE file, stops the build at that command
    with the message Rocq prints for a refutation whose command succeeds
    (one hundred and eight of one hundred and eight, by the same script).
    Quotations are Rocq 9.1.1's under this file's import list, with the
    error's environment block left out; Rocq prints the "cannot unify"
    parenthetical with the short names in scope.

    KINDS.  Twenty-seven refutations, counted as the lines that open with
    the refutation keyword: NAME-ABSENCE, the instrument (one); and
    CONVERSION, [eq_refl] refused with a "cannot unify" parenthetical,
    every statement being well typed (R1 to R26: twenty-six).  CAUSES.
    Measured: every refutation still stops inside its command, and every
    control is still accepted, in a copy of the five #471 files under a
    renamed logical root with all fifty-nine [Qed]s of #471's code turned
    [Defined]; so none is the opacity of #471's own proofs.  Measured by
    #471's scout in a rebuilt copy of Instance/Mon/Free.v's closure: with
    both [Qed] constants that block the universal-arrow counit turned
    [Defined] (Theory/Universal/Arrow.v's [ump_universal_arrows] and
    Free.v's [free_mon_universal], its header's CORRECTION (#471)), that
    counit and the free functor at a one-letter word compute, which are
    R2 and R5 (issue #1353 tracks the shared lemma).  Read from the
    terms: the free functor at a variable word is stuck besides, on
    Free.v's [Fixpoint] (its NEGATIVE 2), behind R4 and R14; the two
    adjunctions differ in their inverse transposes and law proofs (R1);
    data are stuck on a variable list (R3), monoid (R6, R7), algebra
    (R9), length (R15, R16, R17) or arity (R21), and on a variable
    commutative monoid (R22); objects come back as rebuilt records or
    pairs (R8, R10, R18, R19, R23, R24), and R11, R12, R20, R25 and R26
    compare composites whose object maps already differ; R13 is the
    opacity of Theory/Functor.v's [Functor_Setoid_obligation_1], from
    which Theory/Equivalence.v's [Equivalence_to_Cat_Iso] builds
    [iso_from_to] (opaque by [About]).  With that obligation made
    transparent the same component holds at [eq_refl]: measured for
    #470's semigroups by #470's audit, and for these monoids by #471's
    audit, which rebuilt Word.v's closure with it [Defined], and by
    #471's review, which swapped in a transparent symmetry.

    LABELS.  The labels are not constants: each refutation and each
    control carries its label in a comment on the line above it, the
    instrument's reading "The instrument".  The constants are
    [p471_cN_…] and [p471_rN_…] for label CN or RN.

    RESTATEMENTS.  Instance/Mon/Free.v: [free_mon_hom_counit] C1,
    [free_mon_hom_unit] C2, [free_mon_hom_to] C3.  Instance/Mon/Word.v:
    [W0_obj] C5, [W0_carrier] C6, [W0_ret] C7, [W0_ret_fun] C8,
    [W0_join_counit] C9, [W0_join_fun] C10, [W0_join_literal] C11,
    [W0_join_nil] C12, [W0_sum_iso_to] C13, [W0_sum_iso_from] C14,
    [alg_monoid_carrier] C18, [alg_monoid_mul] C19, [alg_monoid_one] C20,
    [Mon_EM_iso_to] C21, [Mon_EM_iso_from] C22, [Mon_K_carrier] C23,
    [Mon_K_alg] C24, [Mon_K_alg_fun] C25, [Mon_K_nu0] C26, [Mon_K_nu1]
    C27, [Mon_K_nu2] C29, [Mon_K_map] C30, [EM_to_Mon_carrier] C31,
    [EM_to_Mon_mul] C32, [EM_to_Mon_one] C33, [EM_to_Mon_map] C34,
    [Mon_rt_carrier] C35, [Mon_rt_one] C36, [Mon_rt_hom] C37,
    [Mon_rt_mul_fun] C38, [EM_rt_carrier] C40, [EM_rt_alg_fun] C41,
    [EM_rt_alg_hom] C43, [Mon_EM_iso_to_from_component] C44,
    [Mon_EM_iso_from_to_component] C45, [Mon_EM_counit_component] C46,
    [Mon_EM_unit_component] C47, [Mon_K_Forget_obj] C49,
    [Mon_K_Forget_map] C50, [EM_to_Mon_Forget_obj] C51,
    [EM_to_Mon_Forget_map] C52, [W0Kl_hom] C53, [W0Kl_homset] C54,
    [W0Kl_id_fun] C55, [W0Kl_hom_iso_to] C56.  Instance/Mon/Word/
    System.v: [nu0_list_nil] C58, [nu0_list_letter] C59, [nu0_list_pair]
    C60, [alg_NAry0_zero] C61, [alg_NAry0_at] C62, [alg_nu0_is_unit] C63,
    [alg_nu2_is_mul] C64, [NAry0_alg_map] C65, [NAry0_rt_zero] C66,
    [NAry0_rt_pos_pair] C67, [W0Sys_EM_iso_to] C69, [W0Sys_EM_iso_from]
    C70, [W0Sys_to_EM_alg] C71, [EM_to_W0Sys_zero] C72, [EM_to_W0Sys_nu]
    C73, [W0Sys_rt_set] C74, [W0Sys_rt_zero] C75, [W0Sys_rt_hom] C76,
    [EM_W0Sys_rt_carrier] C77, [EM_W0Sys_rt_alg_hom] C78,
    [W0Sys_EM_iso_to_from_component] C79,
    [W0Sys_EM_iso_from_to_component] C80, [Mon_system_zero] C81,
    [Mon_system_pair] C82.  Instance/CMon/Free.v: [FreeCMon_carrier] C84,
    [FreeCMon_plus] C85, [FreeCMon_zero] C86, [Bag_obj] C87, [Bag_map]
    C88, [Bag_ret] C89, [Bag_join_counit] C90, [Bag_join] C91,
    [CMon_EM_iso_to] C92, [CMon_EM_iso_from] C93, [CMon_K_alg_fun] C94,
    [CMon_K_zero] C95, [CMon_K_map] C96, [EM_to_CMon_plus] C97,
    [EM_to_CMon_zero] C98, [CMon_rt_carrier] C99, [CMon_rt_zero] C100,
    [CMon_rt_hom] C101, [CMon_rt_plus_fun] C102, [EM_CMon_rt_carrier]
    C104, [EM_CMon_rt_alg_hom] C105, [CMon_EM_iso_to_from_component]
    C106, [CMon_EM_iso_from_to_component] C107, [balg_prop_is] C108.
    Ninety-six readbacks, each named once.  C4, C15, C16, C17, C28, C39,
    C42, C48, C57, C68, C83 and C103 restate no readback: they are the
    twins of refutations.

    THE REFUSALS, with the parenthetical each stripped copy prints.
      The instrument (NAME-ABSENCE): The reference p471_absent_name was
        not found in the current environment.
      R1, the two adjunctions (controls C2, C3, their unit and forward
        transpose): (cannot unify "free_mon_sets_adjunction_hom" and
        "free_mon_sets_adjunction")
      R2, their counits at a variable word (control C4, ≈; C1, the
        hom-set counit is the fold): (cannot unify "@mon_fun … (@counit
        MonS Sets FreeMonSets UMonS free_mon_sets_adjunction L) l" and
        "@mon_fun … (@counit MonS Sets FreeMonSets UMonS
        free_mon_sets_adjunction_hom L) l")
      R3, word → tuple → word at a variable word (controls C15, a
        literal word; C16, Leibniz): (cannot unify "tup0sum_to_list
        (list_to_tup0sum l)" and "l")
      R4, W₀ f at a variable word (control C17, ≈): (cannot unify
        "fmap[W0F] f l" and "wmap f l")
      R5, at a one-letter word: (cannot unify "fmap[W0F] f (a :: nil)%list"
        and "(f a :: nil)%list")
      R6, ν₁ of K M (controls C27, x · 1; C28, ≈): (cannot unify
        "t_alg[projT2 (fobj[Mon_K] M)] (x :: nil)%list" and "x")
      R7, the multiplication through the round trip (controls C38, C39):
        (cannot unify "mon_mul (fobj[EM_to_Mon ◯ Mon_K] M)" and
        "mon_mul M")
      R8, the whole monoid (controls C35 to C37): (cannot unify
        "fobj[EM_to_Mon ◯ Mon_K] M" and "M")
      R9, the algebra's structure map through the round trip (controls
        C41, C42): (cannot unify "t_alg[projT2 (fobj[Mon_K ◯ EM_to_Mon]
        x)]" and "t_alg[`2 (x)]")
      R10, the whole algebra (controls C40, C43): (cannot unify
        "fobj[Mon_K ◯ EM_to_Mon] x" and "x")
      R11: (cannot unify "EM_to_Mon ◯ Mon_K" and "Id[MonS]")
      R12: (cannot unify "Mon_K ◯ EM_to_Mon" and "Id[W0Alg]")
      R13, through the bridge (control C48, the other component; C45,
        the direct isomorphism): (cannot unify "mon_fun (projT1
        (iso_from_to (Equivalence_to_Cat_Iso Mon_EM_equivalence)) M)" and
        "λ a : mon_ob (fobj[(Equivalence_to_Cat_Iso
        Mon_EM_equivalence)⁻¹ ∘ Equivalence_to_Cat_Iso
        Mon_EM_equivalence] M), a")
      R14, the Kleisli composite (control C57, ≈): (cannot unify
        "(g ∘ f) a" and "wconcat (wmap g (f a))")
      R15, family → algebra → family at a variable arity (controls C67,
        at a pair; C68, ≈): (cannot unify "nu (nu_pos (alg_NAry0
        (NAry0_alg ν Hu Ha))) n t" and "nu (nu_pos ν) n t")
      R16, the whole positive family: (cannot unify "nu_pos (alg_NAry0
        (NAry0_alg ν Hu Ha))" and "nu_pos ν")
      R17, a system's family through the round trip (control C75, ν₀):
        (cannot unify "ws0_nu (fobj[EM_to_W0Sys ◯ W0Sys_to_EM] A)" and
        "ws0_nu A")
      R18, the whole system (controls C74 to C76): (cannot unify
        "fobj[EM_to_W0Sys ◯ W0Sys_to_EM] A" and "A")
      R19, the whole algebra through the systems (controls C77, C78):
        (cannot unify "fobj[W0Sys_to_EM ◯ EM_to_W0Sys] x" and "x")
      R20: (cannot unify "EM_to_W0Sys ◯ W0Sys_to_EM" and "Id[W0Sys]")
      R21, νₙ of K M at a variable n (controls C81, C82, C83): (cannot
        unify "nu0 (ws0_nu (fobj[EM_to_W0Sys ◯ Mon_K] M)) n t" and
        "free_mon_extend (λ s : mon_ob M, s) (tup0_to_list n t)")
      R22, the sum through the round trip (controls C102, C103): (cannot
        unify "cmon_plus (fobj[EM_to_CMon ◯ CMon_K] M)" and
        "cmon_plus M")
      R23, the whole commutative monoid (controls C99 to C101): (cannot
        unify "fobj[EM_to_CMon ◯ CMon_K] M" and "M")
      R24, the whole algebra (controls C104, C105): (cannot unify
        "fobj[CMon_K ◯ EM_to_CMon] x" and "x")
      R25: (cannot unify "EM_to_CMon ◯ CMon_K" and "Id[CMon]")
      R26: (cannot unify "CMon_K ◯ EM_to_CMon" and "Id[BagAlg]")

    NOT PINNED HERE.  (a) [About] readbacks as such: the headers'
    universe censuses.  (b) The flips and copies the headers describe
    (each [Defined] closed [Qed] alone; every [Qed] turned [Defined]):
    made in scratch copies.  (c) The closure of the targets under
    [Print Assumptions]: the Makefile's print-assumptions gate names the
    same two hundred and fifty names as the guard below.  (d) The
    absences the headers record: an absence has no command.  (e) The
    readings of the books, from the page image and the PDFs.

    The guard block names the two hundred and fifty names, so that a
    rename breaks this file: the six #471 adds to Instance/Mon/Free.v,
    one hundred and three of Instance/Mon/Word.v, sixty-three of
    Instance/Mon/Word/System.v and seventy-eight of Instance/CMon/Free.v.
    They are exactly the entries [Print Module] gives for each new
    module, the records [NAry0] and [W0System] and the inductive [perm_eq]
    with their constructors, fields and schemes among them.  Each is
    written fully qualified and with [@], so that no short name in scope
    can stand in for it. *)

Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Universal.Arrow.
Require Import Category.Structure.Monoidal.
Require Import Category.Theory.Algebra.Monoid.
Require Import Category.Theory.Algebra.Monoid.Hom.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Mon.Coproduct.
Require Import Category.Instance.Mon.Free.
Require Import Category.Theory.Monad.
Require Import Category.Theory.Equivalence.
Require Import Category.Monad.Algebra.
Require Import Category.Monad.Eilenberg.Moore.
Require Import Category.Monad.Eilenberg.Moore.Adjunction.
Require Import Category.Monad.Comparison.
Require Import Category.Monad.Kleisli.
Require Import Category.Instance.Cat.
Require Import Category.Instance.Smgrp.
Require Import Category.Instance.Mon.Word.
Require Import Category.Instance.Smgrp.Word.
Require Import Category.Instance.Mon.Word.System.
Require Import Category.Lib.Setoid.Propositional.
Require Import Category.Instance.Sets.Propositional.
Require Import Category.Instance.CMon.
Require Import Category.Instance.CMon.Free.

Generalizable All Variables.

Local Notation MonS := (@Mon Sets Sets_Product_Monoidal).
Local Notation UMonS := (@Mon_Forget Sets Sets_Product_Monoidal).

(* ------------------------------------------------------------------------ *)
(** ** The instrument *)

(* The instrument *)
Fail Check p471_absent_name.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Mon/Free.v: the adjunction in hom-set form *)

(* C1: the counit of the hom-set form is the fold of the identity. *)
Example p471_c1_hom_counit (L : MonS) (l : list (mon_ob L)) :
  mon_fun (@counit _ _ _ _ free_mon_sets_adjunction_hom L) l
    = free_mon_extend (fun x => x) l := eq_refl.

(* C2: its unit is the unit of [free_mon_sets_adjunction]. *)
Example p471_c2_hom_unit (X : Sets) :
  @Category.Theory.Adjunction.unit _ _ _ _ free_mon_sets_adjunction_hom X
    = @Category.Theory.Adjunction.unit _ _ _ _ free_mon_sets_adjunction X
  := eq_refl.

(* C3: so is its forward transpose. *)
Example p471_c3_hom_to (X : Sets) (L : MonS)
  (g : FreeMonSets X ~{MonS}~> L) :
  to (@adj _ _ _ _ free_mon_sets_adjunction_hom X L) g
    = to (@adj _ _ _ _ free_mon_sets_adjunction X L) g := eq_refl.

(* R1 *)
Fail Example p471_r1_adjunctions :
  free_mon_sets_adjunction_hom = free_mon_sets_adjunction := eq_refl.

(* C4: the two counits agree up to ≈. *)
Definition p471_c4_counits_equiv (L : MonS) (l : list (mon_ob L)) :
  mon_fun (@counit _ _ _ _ free_mon_sets_adjunction L) l
    ≈ mon_fun (@counit _ _ _ _ free_mon_sets_adjunction_hom L) l :=
  free_mon_counit_evaluates L l.

(* R2 *)
Fail Example p471_r2_counits (L : MonS) (l : list (mon_ob L)) :
  mon_fun (@counit _ _ _ _ free_mon_sets_adjunction L) l
    = mon_fun (@counit _ _ _ _ free_mon_sets_adjunction_hom L) l := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Mon/Word.v: the monad W₀ *)

(* C5: W₀ X is the setoid of words. *)
Example p471_c5_W0_obj (X : Sets) : fobj[W0F] X = WordObj X := eq_refl.

(* C6: its carrier is list X. *)
Example p471_c6_W0_carrier (X : Sets) :
  carrier (fobj[W0F] X) = list (carrier X) := eq_refl.

(* C7: η_X is the insertion, as a setoid map. *)
Example p471_c7_W0_ret (X : Sets) : @ret _ _ W0 X = free_mon_insert X
  := eq_refl.

(* C8: η_X a = ⟨a⟩. *)
Example p471_c8_W0_ret_fun (X : Sets) (a : X) :
  @ret _ _ W0 X a = Datatypes.cons a Datatypes.nil := eq_refl.

(* C9: μ = U ε F. *)
Example p471_c9_W0_join_counit (X : Sets) :
  @join _ _ W0 X
    = fmap[UMonS]
        (@counit _ _ _ _ free_mon_sets_adjunction_hom (FreeMonSets X))
  := eq_refl.

(* C10: μ is the concatenation, the fold of the free monoid's product. *)
Example p471_c10_W0_join_fun (X : Sets) (ww : list (list X)) :
  @join _ _ W0 X ww = free_mon_extend (L := FreeMonSetsObject X)
                        (fun w => w) ww := eq_refl.

(* C11: μ⟨⟨a b⟩⟨c⟩⟩ = ⟨a b c⟩. *)
Example p471_c11_W0_join_literal (X : Sets) (a b c : X) :
  @join _ _ W0 X
    (Datatypes.cons (Datatypes.cons a (Datatypes.cons b Datatypes.nil))
       (Datatypes.cons (Datatypes.cons c Datatypes.nil) Datatypes.nil))
    = Datatypes.cons a (Datatypes.cons b (Datatypes.cons c Datatypes.nil))
  := eq_refl.

(* C12: μ⟨⟩ = ⟨⟩. *)
Example p471_c12_W0_join_nil (X : Sets) :
  @join _ _ W0 X Datatypes.nil = @Datatypes.nil X := eq_refl.

(* C13: W₀ X → ∐ Xⁿ sends a word to its length and its tuple. *)
Example p471_c13_sum_to (X : Sets) (l : list X) :
  to (W0_sum_iso X) l = existT _ (length l) (list_to_tup0 l) := eq_refl.

(* C14: and back. *)
Example p471_c14_sum_from (X : Sets) (n : nat) (t : Tup0 X n) :
  from (W0_sum_iso X) (existT _ n t) = tup0_to_list n t := eq_refl.

(* C15: on a literal word the round trip holds on the nose... *)
Example p471_c15_sum_rt_literal (X : Sets) (a b : X) :
  tup0sum_to_list (list_to_tup0sum (word2 a b)) = word2 a b := eq_refl.

(* C16: ...and at a variable word as a Leibniz lemma. *)
Definition p471_c16_sum_rt_lemma (X : Sets) (l : list X) :
  tup0_to_list (length l) (list_to_tup0 l) = l :=
  tup0_to_list_list_to_tup0 l.

(* R3 *)
Fail Example p471_r3_sum_rt_variable (X : Sets) (l : list X) :
  tup0sum_to_list (list_to_tup0sum l) = l := eq_refl.

(* C17: W₀ f is the letterwise map up to ≈. *)
Definition p471_c17_W0_map_equiv {X Y : Sets} (f : X ~{Sets}~> Y)
  (l : list X) : fmap[W0F] f l ≈ wmap f l := W0_map f l.

(* R4 *)
Fail Example p471_r4_W0_map_variable {X Y : Sets} (f : X ~{Sets}~> Y)
  (l : list X) : fmap[W0F] f l = wmap f l := eq_refl.

(* R5 *)
Fail Example p471_r5_W0_map_letter {X Y : Sets} (f : X ~{Sets}~> Y)
  (a : X) :
  fmap[W0F] f (Datatypes.cons a Datatypes.nil)
    = Datatypes.cons (f a) Datatypes.nil := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Mon/Word.v: an algebra is a monoid (Awodey Ex. 10.6.6) *)

(* C18: the monoid of an algebra has its carrier... *)
Example p471_c18_alg_monoid_carrier {S : Sets} (α : @TAlgebra Sets W0F W0 S) :
  mon_ob (alg_monoid α) = S := eq_refl.

(* C19: ...the multiplication x · y = α⟨x y⟩... *)
Example p471_c19_alg_monoid_mul {S : Sets} (α : @TAlgebra Sets W0F W0 S)
  (a b : S) :
  mon_mul (alg_monoid α) a b
    = t_alg[α] (Datatypes.cons a (Datatypes.cons b Datatypes.nil))
  := eq_refl.

(* C20: ...and the unit α⟨⟩. *)
Example p471_c20_alg_monoid_one {S : Sets} (α : @TAlgebra Sets W0F W0 S) :
  mon_one (alg_monoid α) = t_alg[α] Datatypes.nil := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Mon/Word.v: the comparison K and EM ≅ Mon *)

(* C21: the leg [to] of [Mon_EM_iso] is K. *)
Example p471_c21_iso_to :
  to Mon_EM_iso = EM_Comparison free_mon_sets_adjunction_hom := eq_refl.

(* C22: the leg [from]. *)
Example p471_c22_iso_from : from Mon_EM_iso = EM_to_Mon := eq_refl.

(* C23: K M has carrier M. *)
Example p471_c23_K_carrier (M : MonS) : `1 (fobj[Mon_K] M) = mon_ob M
  := eq_refl.

(* C24: its structure map is U ε_M. *)
Example p471_c24_K_alg (M : MonS) :
  t_alg[`2 (fobj[Mon_K] M)]
    = fmap[UMonS] (@counit _ _ _ _ free_mon_sets_adjunction_hom M)
  := eq_refl.

(* C25: whose value is the fold of the identity. *)
Example p471_c25_K_alg_fun (M : MonS) (l : list (mon_ob M)) :
  t_alg[`2 (fobj[Mon_K] M)] l = free_mon_extend (fun x => x) l := eq_refl.

(* C26: ν₀ is the unit of M. *)
Example p471_c26_K_nu0 (M : MonS) :
  t_alg[`2 (fobj[Mon_K] M)] Datatypes.nil = mon_one M := eq_refl.

(* C27: ν₁ x = x · 1. *)
Example p471_c27_K_nu1 (M : MonS) (x : mon_ob M) :
  t_alg[`2 (fobj[Mon_K] M)] (Datatypes.cons x Datatypes.nil)
    = mon_mul M x (mon_one M) := eq_refl.

(* C28: ν₁ x ≈ x. *)
Definition p471_c28_K_nu1_equiv (M : MonS) (x : mon_ob M) :
  t_alg[`2 (fobj[Mon_K] M)] (Datatypes.cons x Datatypes.nil) ≈ x :=
  mon_one_r M x.

(* R6 *)
Fail Example p471_r6_K_nu1 (M : MonS) (x : mon_ob M) :
  t_alg[`2 (fobj[Mon_K] M)] (Datatypes.cons x Datatypes.nil) = x
  := eq_refl.

(* C29: ν₂(x, y) = x · (y · 1). *)
Example p471_c29_K_nu2 (M : MonS) (x y : mon_ob M) :
  t_alg[`2 (fobj[Mon_K] M)] (Datatypes.cons x (Datatypes.cons y Datatypes.nil))
    = mon_mul M x (mon_mul M y (mon_one M)) := eq_refl.

(* C30: K f has underlying map f. *)
Example p471_c30_K_map {M N : MonS} (f : M ~{MonS}~> N) :
  t_alg_hom[fmap[Mon_K] f] = `1 f := eq_refl.

(* C31: the monoid of an algebra, through the functor: the carrier... *)
Example p471_c31_EM_carrier (x : W0Alg) :
  mon_ob (fobj[EM_to_Mon] x) = `1 x := eq_refl.

(* C32: ...the multiplication... *)
Example p471_c32_EM_mul (x : W0Alg) (a b : `1 x) :
  mon_mul (fobj[EM_to_Mon] x) a b
    = t_alg[`2 x] (Datatypes.cons a (Datatypes.cons b Datatypes.nil))
  := eq_refl.

(* C33: ...the unit... *)
Example p471_c33_EM_one (x : W0Alg) :
  mon_one (fobj[EM_to_Mon] x) = t_alg[`2 x] Datatypes.nil := eq_refl.

(* C34: ...and the map of a morphism. *)
Example p471_c34_EM_map {x y : W0Alg} (f : x ~{W0Alg}~> y) :
  `1 (fmap[EM_to_Mon] f) = t_alg_hom[f] := eq_refl.

(* C35: the monoid round trip keeps the carrier... *)
Example p471_c35_Mon_rt_carrier (M : MonS) :
  mon_ob (fobj[EM_to_Mon ◯ Mon_K] M) = mon_ob M := eq_refl.

(* C36: ...the unit... *)
Example p471_c36_Mon_rt_one (M : MonS) :
  mon_one (fobj[EM_to_Mon ◯ Mon_K] M) = mon_one M := eq_refl.

(* C37: ...and the map of a morphism. *)
Example p471_c37_Mon_rt_hom {M N : MonS} (f : M ~{MonS}~> N) :
  mon_fun (fmap[EM_to_Mon ◯ Mon_K] f) = mon_fun f := eq_refl.

(* C38: the multiplication comes back as x · (y · 1)... *)
Example p471_c38_Mon_rt_mul_fun (M : MonS) (a b : mon_ob M) :
  mon_mul (fobj[EM_to_Mon ◯ Mon_K] M) a b
    = mon_mul M a (mon_mul M b (mon_one M)) := eq_refl.

(* C39: ...so at ≈. *)
Definition p471_c39_Mon_rt_mul_equiv (M : MonS) (a b : mon_ob M) :
  mon_mul (fobj[EM_to_Mon ◯ Mon_K] M) a b ≈ mon_mul M a b :=
  Mon_rt_mul M a b.

(* R7 *)
Fail Example p471_r7_Mon_rt_mul (M : MonS) :
  mon_mul (fobj[EM_to_Mon ◯ Mon_K] M) = mon_mul M := eq_refl.

(* R8 *)
Fail Example p471_r8_Mon_rt_obj (M : MonS) :
  fobj[EM_to_Mon ◯ Mon_K] M = M := eq_refl.

(* C40: the algebra round trip keeps the carrier... *)
Example p471_c40_EM_rt_carrier (x : W0Alg) :
  `1 (fobj[Mon_K ◯ EM_to_Mon] x) = `1 x := eq_refl.

(* C41: ...its structure map is the fold of the derived monoid... *)
Example p471_c41_EM_rt_alg_fun (x : W0Alg) (l : list (`1 x)) :
  t_alg[`2 (fobj[Mon_K ◯ EM_to_Mon] x)] l
    = free_mon_extend (L := alg_monoid (`2 x)) (fun s => s) l := eq_refl.

(* C42: ...which is α at ≈ ... *)
Definition p471_c42_EM_rt_alg_equiv (x : W0Alg) (l : list (`1 x)) :
  t_alg[`2 (fobj[Mon_K ◯ EM_to_Mon] x)] l ≈ t_alg[`2 x] l :=
  alg_fold (`2 x) l.

(* C43: ...and the map of a morphism comes back. *)
Example p471_c43_EM_rt_alg_hom {x y : W0Alg} (f : x ~{W0Alg}~> y) :
  t_alg_hom[fmap[Mon_K ◯ EM_to_Mon] f] = t_alg_hom[f] := eq_refl.

(* R9 *)
Fail Example p471_r9_EM_rt_alg (x : W0Alg) :
  t_alg[`2 (fobj[Mon_K ◯ EM_to_Mon] x)] = t_alg[`2 x] := eq_refl.

(* R10 *)
Fail Example p471_r10_EM_rt_obj (x : W0Alg) :
  fobj[Mon_K ◯ EM_to_Mon] x = x := eq_refl.

(* R11 *)
Fail Example p471_r11_K_functor : EM_to_Mon ◯ Mon_K = Id[MonS] := eq_refl.

(* R12 *)
Fail Example p471_r12_K_functor_b : Mon_K ◯ EM_to_Mon = Id[W0Alg] := eq_refl.

(* C44: every component of [iso_to_from] is the identity... *)
Example p471_c44_to_from_component (x : W0Alg) :
  (t_alg_hom[to (`1 (iso_to_from Mon_EM_iso) x)],
   t_alg_hom[from (`1 (iso_to_from Mon_EM_iso) x)])
    = (@setoid_morphism_id (`1 x), @setoid_morphism_id (`1 x)) := eq_refl.

(* C45: ...and so is every component of [iso_from_to]... *)
Example p471_c45_from_to_component (M : MonS) :
  (mon_fun (to (`1 (iso_from_to Mon_EM_iso) M)),
   mon_fun (from (`1 (iso_from_to Mon_EM_iso) M)))
    = ((fun a : mon_ob M => a), (fun a : mon_ob M => a)) := eq_refl.

(* C46: ...of the equivalence's counit... *)
Example p471_c46_counit_component (x : W0Alg) :
  (t_alg_hom[to (`1 (@equivalence_counit _ _ _ Mon_EM_equivalence) x)],
   t_alg_hom[from (`1 (@equivalence_counit _ _ _ Mon_EM_equivalence) x)])
    = (@setoid_morphism_id (`1 x), @setoid_morphism_id (`1 x)) := eq_refl.

(* C47: ...and of its unit. *)
Example p471_c47_unit_component (M : MonS) :
  (mon_fun (to (`1 (@equivalence_unit _ _ _ Mon_EM_equivalence) M)),
   mon_fun (from (`1 (@equivalence_unit _ _ _ Mon_EM_equivalence) M)))
    = ((fun a : mon_ob M => a), (fun a : mon_ob M => a)) := eq_refl.

(* C48: Theory/Equivalence.v's bridge [Equivalence_to_Cat_Iso], applied
   to the equivalence, has the identity as the component of its
   [iso_to_from]... *)
Example p471_c48_bridge_to_from (x : W0Alg) :
  t_alg_hom[to (`1 (iso_to_from (Equivalence_to_Cat_Iso Mon_EM_equivalence))
                  x)]
    = @setoid_morphism_id (`1 x) := eq_refl.

(* R13 *)
Fail Example p471_r13_bridge_from_to (M : MonS) :
  mon_fun (to (`1 (iso_from_to (Equivalence_to_Cat_Iso Mon_EM_equivalence))
                 M))
    = (fun a => a) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Mon/Word.v: the forgetful functors (Awodey §10.3) *)

(* C49: U^{W₀} K M = U M... *)
Example p471_c49_K_forget_obj (M : MonS) :
  fobj[W0_Forget] (fobj[Mon_K] M) = fobj[UMonS] M := eq_refl.

(* C50: ...and on arrows. *)
Example p471_c50_K_forget_map {M N : MonS} (f : M ~{MonS}~> N) :
  fmap[W0_Forget] (fmap[Mon_K] f) = fmap[UMonS] f := eq_refl.

(* C51: U (the monoid of x) = U^{W₀} x... *)
Example p471_c51_EM_forget_obj (x : W0Alg) :
  fobj[UMonS] (fobj[EM_to_Mon] x) = fobj[W0_Forget] x := eq_refl.

(* C52: ...and on arrows. *)
Example p471_c52_EM_forget_map {x y : W0Alg} (f : x ~{W0Alg}~> y) :
  fmap[UMonS] (fmap[EM_to_Mon] f) = fmap[W0_Forget] f := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Mon/Word.v: the Kleisli category (Riehl Ex. 5.2.11(ii)) *)

(* C53: a Kleisli arrow A ⇝ B is a setoid map A → W₀ B... *)
Example p471_c53_Kl_hom (A B : Sets) :
  @hom W0Kl A B = (A ~{Sets}~> WordObj B) := eq_refl.

(* C54: ...compared as such. *)
Example p471_c54_Kl_homset (A B : Sets) :
  @homset W0Kl A B = @homset Sets A (WordObj B) := eq_refl.

(* C55: the identity sends a to ⟨a⟩. *)
Example p471_c55_Kl_id (A : Sets) (a : A) :
  (@id W0Kl A) a = Datatypes.cons a Datatypes.nil := eq_refl.

(* C56: the hom-set isomorphism sends f to a ↦ (length, tuple) of f a. *)
Example p471_c56_Kl_hom_iso_to (A B : Sets) (f : A ~{W0Kl}~> B) (a : A) :
  to (W0Kl_hom_iso A B) f a = existT _ (length (f a)) (list_to_tup0 (f a))
  := eq_refl.

(* C57: composition is concatenated mapping, up to ≈. *)
Definition p471_c57_Kl_compose_equiv {A B C : Sets}
  (g : B ~{W0Kl}~> C) (f : A ~{W0Kl}~> B) (a : A) :
  (g ∘[W0Kl] f) a ≈ wconcat (wmap g (f a)) := W0Kl_compose g f a.

(* R14 *)
Fail Example p471_r14_Kl_compose {A B C : Sets}
  (g : B ~{W0Kl}~> C) (f : A ~{W0Kl}~> B) (a : A) :
  (g ∘[W0Kl] f) a = wconcat (wmap g (f a)) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Mon/Word/System.v: the families ν₀, ν₁, … *)

(* C58: ν read on the empty word is ν₀... *)
Example p471_c58_nu0_nil {X : SetoidObject} (ν : NAry0 X) :
  nu0_list ν Datatypes.nil = nu_zero ν := eq_refl.

(* C59: ...on a letter ν₁... *)
Example p471_c59_nu0_letter {X : SetoidObject} (ν : NAry0 X) (x : X) :
  nu0_list ν (Datatypes.cons x Datatypes.nil) = nu (nu_pos ν) 0 x
  := eq_refl.

(* C60: ...and on a pair ν₂. *)
Example p471_c60_nu0_pair {X : SetoidObject} (ν : NAry0 X) (x y : X) :
  nu0_list ν (Datatypes.cons x (Datatypes.cons y Datatypes.nil))
    = nu (nu_pos ν) 1 (x, y) := eq_refl.

(* C61: an algebra's ν₀ is α⟨⟩... *)
Example p471_c61_alg_zero {X : Sets} (α : @TAlgebra Sets W0F W0 X) :
  nu_zero (alg_NAry0 α) = t_alg[α] Datatypes.nil := eq_refl.

(* C62: ...and its ν_{n+1} is α on S^{n+1}. *)
Example p471_c62_alg_at {X : Sets} (α : @TAlgebra Sets W0F W0 X) (n : nat)
  (t : Tup X n) :
  nu (nu_pos (alg_NAry0 α)) n t = t_alg[α] (tup_to_list n t) := eq_refl.

(* C63: ν₀ is the unit of the monoid of the algebra... *)
Example p471_c63_alg_nu0_unit {X : Sets} (α : @TAlgebra Sets W0F W0 X) :
  nu_zero (alg_NAry0 α) = mon_one (alg_monoid α) := eq_refl.

(* C64: ...and ν₂ its multiplication. *)
Example p471_c64_alg_nu2_mul {X : Sets} (α : @TAlgebra Sets W0F W0 X)
  (a b : X) :
  nu (nu_pos (alg_NAry0 α)) 1 (a, b) = mon_mul (alg_monoid α) a b
  := eq_refl.

(* C65: a family's algebra has the copairing as structure map. *)
Example p471_c65_NAry0_alg_map {X : Sets} (ν : NAry0 X)
  (Hu : nu_unit (nu_pos ν)) (Ha : nu0_assoc ν) (l : list X) :
  t_alg[NAry0_alg ν Hu Ha] l = nu0_list ν l := eq_refl.

(* C66: family → algebra → family keeps ν₀... *)
Example p471_c66_rt_zero {X : Sets} (ν : NAry0 X)
  (Hu : nu_unit (nu_pos ν)) (Ha : nu0_assoc ν) :
  nu_zero (alg_NAry0 (NAry0_alg ν Hu Ha)) = nu_zero ν := eq_refl.

(* C67: ...and ν₂ at a literal pair... *)
Example p471_c67_rt_pair {X : Sets} (ν : NAry0 X)
  (Hu : nu_unit (nu_pos ν)) (Ha : nu0_assoc ν) (a b : X) :
  nu (nu_pos (alg_NAry0 (NAry0_alg ν Hu Ha))) 1 (a, b)
    = nu (nu_pos ν) 1 (a, b) := eq_refl.

(* C68: ...and ν_{n+1} at ≈. *)
Definition p471_c68_rt_pos_equiv {X : Sets} (ν : NAry0 X)
  (Hu : nu_unit (nu_pos ν)) (Ha : nu0_assoc ν) (n : nat) (t : Tup X n) :
  nu (nu_pos (alg_NAry0 (NAry0_alg ν Hu Ha))) n t ≈ nu (nu_pos ν) n t :=
  NAry0_rt_pos ν Hu Ha n t.

(* R15 *)
Fail Example p471_r15_rt_pos_at {X : Sets} (ν : NAry0 X)
  (Hu : nu_unit (nu_pos ν)) (Ha : nu0_assoc ν) (n : nat) (t : Tup X n) :
  nu (nu_pos (alg_NAry0 (NAry0_alg ν Hu Ha))) n t = nu (nu_pos ν) n t
  := eq_refl.

(* R16 *)
Fail Example p471_r16_rt_pos {X : Sets} (ν : NAry0 X)
  (Hu : nu_unit (nu_pos ν)) (Ha : nu0_assoc ν) :
  nu_pos (alg_NAry0 (NAry0_alg ν Hu Ha)) = nu_pos ν := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Mon/Word/System.v: the systems as a category *)

(* C69: the leg [to] of [W0Sys_EM_iso]. *)
Example p471_c69_sys_iso_to : to W0Sys_EM_iso = W0Sys_to_EM := eq_refl.

(* C70: the leg [from]. *)
Example p471_c70_sys_iso_from : from W0Sys_EM_iso = EM_to_W0Sys := eq_refl.

(* C71: a system's structure map is the copairing of its family. *)
Example p471_c71_sys_to_em_alg (A : W0Sys) (l : list (ws0_set A)) :
  t_alg[`2 (fobj[W0Sys_to_EM] A)] l = nu0_list (ws0_nu A) l := eq_refl.

(* C72: an algebra's ν₀ is α⟨⟩... *)
Example p471_c72_em_to_sys_zero (x : W0Alg) :
  nu_zero (ws0_nu (fobj[EM_to_W0Sys] x)) = t_alg[`2 x] Datatypes.nil
  := eq_refl.

(* C73: ...and its ν_{n+1} is α on S^{n+1}. *)
Example p471_c73_em_to_sys_nu (x : W0Alg) (n : nat) (t : Tup (`1 x) n) :
  nu (nu_pos (ws0_nu (fobj[EM_to_W0Sys] x))) n t
    = t_alg[`2 x] (tup_to_list n t) := eq_refl.

(* C74: the system round trip keeps the set... *)
Example p471_c74_sys_rt_set (A : W0Sys) :
  ws0_set (fobj[EM_to_W0Sys ◯ W0Sys_to_EM] A) = ws0_set A := eq_refl.

(* C75: ...ν₀... *)
Example p471_c75_sys_rt_zero (A : W0Sys) :
  nu_zero (ws0_nu (fobj[EM_to_W0Sys ◯ W0Sys_to_EM] A)) = nu_zero (ws0_nu A)
  := eq_refl.

(* C76: ...and the map of a morphism. *)
Example p471_c76_sys_rt_hom {A B : W0Sys} (f : A ~{W0Sys}~> B) :
  `1 (fmap[EM_to_W0Sys ◯ W0Sys_to_EM] f) = `1 f := eq_refl.

(* R17 *)
Fail Example p471_r17_sys_rt_nu (A : W0Sys) :
  ws0_nu (fobj[EM_to_W0Sys ◯ W0Sys_to_EM] A) = ws0_nu A := eq_refl.

(* R18 *)
Fail Example p471_r18_sys_rt_obj (A : W0Sys) :
  fobj[EM_to_W0Sys ◯ W0Sys_to_EM] A = A := eq_refl.

(* C77: the algebra round trip through the systems keeps the carrier... *)
Example p471_c77_em_sys_rt_carrier (x : W0Alg) :
  `1 (fobj[W0Sys_to_EM ◯ EM_to_W0Sys] x) = `1 x := eq_refl.

(* C78: ...and the map of a morphism. *)
Example p471_c78_em_sys_rt_alg_hom {x y : W0Alg} (f : x ~{W0Alg}~> y) :
  t_alg_hom[fmap[W0Sys_to_EM ◯ EM_to_W0Sys] f] = t_alg_hom[f] := eq_refl.

(* R19 *)
Fail Example p471_r19_em_sys_rt_obj (x : W0Alg) :
  fobj[W0Sys_to_EM ◯ EM_to_W0Sys] x = x := eq_refl.

(* R20 *)
Fail Example p471_r20_sys_functor :
  EM_to_W0Sys ◯ W0Sys_to_EM = Id[W0Sys] := eq_refl.

(* C79: the components of [iso_to_from] are identities... *)
Example p471_c79_sys_to_from_component (x : W0Alg) :
  (t_alg_hom[to (`1 (iso_to_from W0Sys_EM_iso) x)],
   t_alg_hom[from (`1 (iso_to_from W0Sys_EM_iso) x)])
    = (@setoid_morphism_id (`1 x), @setoid_morphism_id (`1 x)) := eq_refl.

(* C80: ...and so are those of [iso_from_to]. *)
Example p471_c80_sys_from_to_component (A : W0Sys) :
  (`1 (to (`1 (iso_from_to W0Sys_EM_iso) A)),
   `1 (from (`1 (iso_from_to W0Sys_EM_iso) A)))
    = (@setoid_morphism_id (ws0_set A), @setoid_morphism_id (ws0_set A))
  := eq_refl.

(* C81: the system of a monoid M has ν₀ the unit... *)
Example p471_c81_mon_system_zero (M : MonS) :
  nu_zero (ws0_nu (fobj[EM_to_W0Sys ◯ Mon_K] M)) = mon_one M := eq_refl.

(* C82: ...and ν₂(x, y) = x · (y · 1)... *)
Example p471_c82_mon_system_pair (M : MonS) (x y : mon_ob M) :
  nu (nu_pos (ws0_nu (fobj[EM_to_W0Sys ◯ Mon_K] M))) 1 (x, y)
    = mon_mul M x (mon_mul M y (mon_one M)) := eq_refl.

(* C83: ...and νₙ the n-fold product, at each n by cases. *)
Definition p471_c83_mon_system_nu (M : MonS) (n : nat)
  (t : Tup0 (mon_ob M) n) :
  nu0 (ws0_nu (fobj[EM_to_W0Sys ◯ Mon_K] M)) n t
    ≈ free_mon_extend (L := M) (fun s => s) (tup0_to_list n t) :=
  Mon_system_nu M n t.

(* R21 *)
Fail Example p471_r21_mon_system_nu (M : MonS) (n : nat)
  (t : Tup0 (mon_ob M) n) :
  nu0 (ws0_nu (fobj[EM_to_W0Sys ◯ Mon_K] M)) n t
    = free_mon_extend (L := M) (fun s => s) (tup0_to_list n t) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/CMon/Free.v: the free commutative monoid and its monad *)

(* C84: the carrier of the free commutative monoid is the setoid of
   multisets... *)
Example p471_c84_cmon_carrier (X : Sets) :
  cmon_setoid (FreeCMonObject X) = BagObj X := eq_refl.

(* C85: ...its sum is concatenation... *)
Example p471_c85_cmon_plus (X : Sets) (l m : list X) :
  cmon_plus (FreeCMonObject X) l m = wapp l m := eq_refl.

(* C86: ...and its zero the empty multiset. *)
Example p471_c86_cmon_zero (X : Sets) :
  cmon_zero (FreeCMonObject X) = @Datatypes.nil X := eq_refl.

(* C87: the monad on objects is the setoid of multisets... *)
Example p471_c87_bag_obj (X : Sets) : fobj[BagF] X = BagObj X := eq_refl.

(* C88: ...on arrows the letterwise map, at a variable multiset... *)
Example p471_c88_bag_map {X Y : Sets} (f : X ~{Sets}~> Y) (l : list X) :
  fmap[BagF] f l = wmap f l := eq_refl.

(* C89: ...its unit the insertion... *)
Example p471_c89_bag_ret (X : Sets) : @ret _ _ BagMonad X = bag_insert X
  := eq_refl.

(* C90: ...its multiplication U ε F... *)
Example p471_c90_bag_join_counit (X : Sets) :
  @join _ _ BagMonad X
    = fmap[CMon_Forget] (@counit _ _ _ _ FreeCMon_adj (FreeCMon X))
  := eq_refl.

(* C91: ...the union of a multiset of multisets. *)
Example p471_c91_bag_join (X : Sets) (ll : list (list X)) :
  @join _ _ BagMonad X ll = cfold (L := FreeCMonObject X) (fun l => l) ll
  := eq_refl.

(* C92: the legs of [CMon_EM_iso]... *)
Example p471_c92_cmon_iso_to : to CMon_EM_iso = CMon_K := eq_refl.

(* C93: ... *)
Example p471_c93_cmon_iso_from : from CMon_EM_iso = EM_to_CMon := eq_refl.

(* C94: K M's structure map is the fold of the identity... *)
Example p471_c94_cmon_K_alg_fun (M : CMon) (l : list (cmon_setoid M)) :
  t_alg[`2 (fobj[CMon_K] M)] l = cfold (L := M) (fun x => x) l := eq_refl.

(* C95: ...with the zero on the empty multiset... *)
Example p471_c95_cmon_K_zero (M : CMon) :
  t_alg[`2 (fobj[CMon_K] M)] Datatypes.nil = cmon_zero M := eq_refl.

(* C96: ...and K f is f. *)
Example p471_c96_cmon_K_map {M N : CMon} (f : M ~{CMon}~> N) :
  t_alg_hom[fmap[CMon_K] f] = cmon_map f := eq_refl.

(* C97: the commutative monoid of an algebra: a + b = α⟨a b⟩... *)
Example p471_c97_em_cmon_plus (x : BagAlg) (a b : `1 x) :
  cmon_plus (fobj[EM_to_CMon] x) a b
    = t_alg[`2 x] (Datatypes.cons a (Datatypes.cons b Datatypes.nil))
  := eq_refl.

(* C98: ...and 0 = α⟨⟩. *)
Example p471_c98_em_cmon_zero (x : BagAlg) :
  cmon_zero (fobj[EM_to_CMon] x) = t_alg[`2 x] Datatypes.nil := eq_refl.

(* C99: the round trip keeps the carrier... *)
Example p471_c99_cmon_rt_carrier (M : CMon) :
  cmon_setoid (fobj[EM_to_CMon ◯ CMon_K] M) = cmon_setoid M := eq_refl.

(* C100: ...the zero... *)
Example p471_c100_cmon_rt_zero (M : CMon) :
  cmon_zero (fobj[EM_to_CMon ◯ CMon_K] M) = cmon_zero M := eq_refl.

(* C101: ...and the maps... *)
Example p471_c101_cmon_rt_hom {M N : CMon} (f : M ~{CMon}~> N) :
  cmon_map (fmap[EM_to_CMon ◯ CMon_K] f) = cmon_map f := eq_refl.

(* C102: ...and the sum comes back as a + (b + 0)... *)
Example p471_c102_cmon_rt_plus_fun (M : CMon) (a b : cmon_setoid M) :
  cmon_plus (fobj[EM_to_CMon ◯ CMon_K] M) a b
    = cmon_plus M a (cmon_plus M b (cmon_zero M)) := eq_refl.

(* C103: ...so at ≈. *)
Definition p471_c103_cmon_rt_plus_equiv (M : CMon) (a b : cmon_setoid M) :
  cmon_plus (fobj[EM_to_CMon ◯ CMon_K] M) a b ≈ cmon_plus M a b :=
  cmon_plus_respects M a a (reflexivity a) _ _ (cmon_plus_zero_r M b).

(* R22 *)
Fail Example p471_r22_cmon_rt_plus (M : CMon) :
  cmon_plus (fobj[EM_to_CMon ◯ CMon_K] M) = cmon_plus M := eq_refl.

(* R23 *)
Fail Example p471_r23_cmon_rt_obj (M : CMon) :
  fobj[EM_to_CMon ◯ CMon_K] M = M := eq_refl.

(* C104: the algebra round trip keeps the carrier... *)
Example p471_c104_em_cmon_rt_carrier (x : BagAlg) :
  `1 (fobj[CMon_K ◯ EM_to_CMon] x) = `1 x := eq_refl.

(* C105: ...and the maps. *)
Example p471_c105_em_cmon_rt_alg_hom {x y : BagAlg} (f : x ~{BagAlg}~> y) :
  t_alg_hom[fmap[CMon_K ◯ EM_to_CMon] f] = t_alg_hom[f] := eq_refl.

(* R24 *)
Fail Example p471_r24_em_cmon_rt_obj (x : BagAlg) :
  fobj[CMon_K ◯ EM_to_CMon] x = x := eq_refl.

(* R25 *)
Fail Example p471_r25_cmon_functor : EM_to_CMon ◯ CMon_K = Id[CMon]
  := eq_refl.

(* R26 *)
Fail Example p471_r26_cmon_functor_b : CMon_K ◯ EM_to_CMon = Id[BagAlg]
  := eq_refl.

(* C106: the components of [iso_to_from] are identities... *)
Example p471_c106_cmon_to_from_component (x : BagAlg) :
  (t_alg_hom[to (`1 (iso_to_from CMon_EM_iso) x)],
   t_alg_hom[from (`1 (iso_to_from CMon_EM_iso) x)])
    = (@setoid_morphism_id (`1 x), @setoid_morphism_id (`1 x)) := eq_refl.

(* C107: ...and so are those of [iso_from_to]. *)
Example p471_c107_cmon_from_to_component (M : CMon) :
  (cmon_map (to (`1 (iso_from_to CMon_EM_iso) M)),
   cmon_map (from (`1 (iso_from_to CMon_EM_iso) M)))
    = (@setoid_morphism_id (cmon_setoid M),
       @setoid_morphism_id (cmon_setoid M)) := eq_refl.

(* C108: the Prop mirror of an algebra's carrier compares one-letter
   multisets. *)
Example p471_c108_balg_prop (x : BagAlg) (a b : `1 x) :
  @pequiv _ _ (cmon_prop (fobj[EM_to_CMon] x)) a b
    = perm_eq (Datatypes.cons a Datatypes.nil)
        (Datatypes.cons b Datatypes.nil) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** The guard: every constant of the targets *)

Check @Category.Instance.Mon.Free.free_mon_extend_pointwise.
Check @Category.Instance.Mon.Free.free_mon_hom_iso.
Check @Category.Instance.Mon.Free.free_mon_sets_adjunction_hom.
Check @Category.Instance.Mon.Free.free_mon_hom_counit.
Check @Category.Instance.Mon.Free.free_mon_hom_unit.
Check @Category.Instance.Mon.Free.free_mon_hom_to.
Check @Category.Instance.Mon.Word.Tup0.
Check @Category.Instance.Mon.Word.tup_to_list.
Check @Category.Instance.Mon.Word.tup0_to_list.
Check @Category.Instance.Mon.Word.list_to_tup.
Check @Category.Instance.Mon.Word.list_to_tup0.
Check @Category.Instance.Mon.Word.tup_to_list_list_to_tup.
Check @Category.Instance.Mon.Word.tup0_to_list_list_to_tup0.
Check @Category.Instance.Mon.Word.tup_to_list_respects.
Check @Category.Instance.Mon.Word.list_to_tup_respects.
Check @Category.Instance.Mon.Word.list_to_tup_tup_to_list.
Check @Category.Instance.Mon.Word.tup0_eq.
Check @Category.Instance.Mon.Word.tup0_eq_refl.
Check @Category.Instance.Mon.Word.tup0_eq_sym.
Check @Category.Instance.Mon.Word.tup0_eq_trans.
Check @Category.Instance.Mon.Word.Tup0Sum.
Check @Category.Instance.Mon.Word.Tup0Sum_Setoid.
Check @Category.Instance.Mon.Word.Tup0SumObj.
Check @Category.Instance.Mon.Word.list_to_tup0sum.
Check @Category.Instance.Mon.Word.tup0sum_to_list.
Check @Category.Instance.Mon.Word.list_to_tup0sum_respects.
Check @Category.Instance.Mon.Word.tup0sum_to_list_respects.
Check @Category.Instance.Mon.Word.tup0sum_list_tup0sum.
Check @Category.Instance.Mon.Word.word0.
Check @Category.Instance.Mon.Word.word1.
Check @Category.Instance.Mon.Word.word2.
Check @Category.Instance.Mon.Word.word_eq_wapp_nil_r.
Check @Category.Instance.Mon.Word.W0F.
Check @Category.Instance.Mon.Word.W0.
Check @Category.Instance.Mon.Word.wconcat.
Check @Category.Instance.Mon.Word.W0_obj.
Check @Category.Instance.Mon.Word.W0_carrier.
Check @Category.Instance.Mon.Word.W0_ret.
Check @Category.Instance.Mon.Word.W0_ret_fun.
Check @Category.Instance.Mon.Word.W0_join_counit.
Check @Category.Instance.Mon.Word.W0_join_fun.
Check @Category.Instance.Mon.Word.W0_join_literal.
Check @Category.Instance.Mon.Word.W0_join_nil.
Check @Category.Instance.Mon.Word.W0_map.
Check @Category.Instance.Mon.Word.W0_sum_iso.
Check @Category.Instance.Mon.Word.W0_sum_iso_to.
Check @Category.Instance.Mon.Word.W0_sum_iso_from.
Check @Category.Instance.Mon.Word.alg_unit.
Check @Category.Instance.Mon.Word.alg_action.
Check @Category.Instance.Mon.Word.alg_mul.
Check @Category.Instance.Mon.Word.alg_one.
Check @Category.Instance.Mon.Word.alg_mul_respects.
Check @Category.Instance.Mon.Word.alg_mul_assoc.
Check @Category.Instance.Mon.Word.alg_one_l.
Check @Category.Instance.Mon.Word.alg_one_r.
Check @Category.Instance.Mon.Word.alg_monoid.
Check @Category.Instance.Mon.Word.alg_fold.
Check @Category.Instance.Mon.Word.alg_monoid_unique.
Check @Category.Instance.Mon.Word.W0Alg.
Check @Category.Instance.Mon.Word.EM_mon_map.
Check @Category.Instance.Mon.Word.EM_to_Mon.
Check @Category.Instance.Mon.Word.Mon_K.
Check @Category.Instance.Mon.Word.Mon_EM_counit_iso.
Check @Category.Instance.Mon.Word.Mon_EM_unit_iso.
Check @Category.Instance.Mon.Word.Mon_EM_equivalence.
Check @Category.Instance.Mon.Word.Mon_Forget_Monadic.
Check @Category.Instance.Mon.Word.Mon_EM_iso.
Check @Category.Instance.Mon.Word.W0_Forget.
Check @Category.Instance.Mon.Word.Mon_K_Forget.
Check @Category.Instance.Mon.Word.EM_to_Mon_Forget.
Check @Category.Instance.Mon.Word.Mon_K_Forget_obj.
Check @Category.Instance.Mon.Word.Mon_K_Forget_map.
Check @Category.Instance.Mon.Word.EM_to_Mon_Forget_obj.
Check @Category.Instance.Mon.Word.EM_to_Mon_Forget_map.
Check @Category.Instance.Mon.Word.W0Kl.
Check @Category.Instance.Mon.Word.W0Kl_hom.
Check @Category.Instance.Mon.Word.W0Kl_homset.
Check @Category.Instance.Mon.Word.W0Kl_id_fun.
Check @Category.Instance.Mon.Word.W0Kl_compose.
Check @Category.Instance.Mon.Word.W0Kl_hom_iso.
Check @Category.Instance.Mon.Word.W0Kl_hom_iso_to.
Check @Category.Instance.Mon.Word.Mon_EM_iso_to.
Check @Category.Instance.Mon.Word.Mon_EM_iso_from.
Check @Category.Instance.Mon.Word.alg_monoid_carrier.
Check @Category.Instance.Mon.Word.alg_monoid_mul.
Check @Category.Instance.Mon.Word.alg_monoid_one.
Check @Category.Instance.Mon.Word.Mon_K_carrier.
Check @Category.Instance.Mon.Word.Mon_K_alg.
Check @Category.Instance.Mon.Word.Mon_K_alg_fun.
Check @Category.Instance.Mon.Word.Mon_K_nu0.
Check @Category.Instance.Mon.Word.Mon_K_nu1.
Check @Category.Instance.Mon.Word.Mon_K_nu2.
Check @Category.Instance.Mon.Word.Mon_K_map.
Check @Category.Instance.Mon.Word.EM_to_Mon_carrier.
Check @Category.Instance.Mon.Word.EM_to_Mon_mul.
Check @Category.Instance.Mon.Word.EM_to_Mon_one.
Check @Category.Instance.Mon.Word.EM_to_Mon_map.
Check @Category.Instance.Mon.Word.Mon_rt_carrier.
Check @Category.Instance.Mon.Word.Mon_rt_one.
Check @Category.Instance.Mon.Word.Mon_rt_mul_fun.
Check @Category.Instance.Mon.Word.Mon_rt_mul.
Check @Category.Instance.Mon.Word.Mon_rt_hom.
Check @Category.Instance.Mon.Word.EM_rt_carrier.
Check @Category.Instance.Mon.Word.EM_rt_alg_fun.
Check @Category.Instance.Mon.Word.EM_rt_alg_hom.
Check @Category.Instance.Mon.Word.Mon_EM_iso_to_from_component.
Check @Category.Instance.Mon.Word.Mon_EM_iso_from_to_component.
Check @Category.Instance.Mon.Word.Mon_EM_counit_component.
Check @Category.Instance.Mon.Word.Mon_EM_unit_component.
Check @Category.Instance.Mon.Word.System.NAry0.
Check @Category.Instance.Mon.Word.System.Build_NAry0.
Check @Category.Instance.Mon.Word.System.nu_zero.
Check @Category.Instance.Mon.Word.System.nu_pos.
Check @Category.Instance.Mon.Word.System.nu0.
Check @Category.Instance.Mon.Word.System.nu0_list.
Check @Category.Instance.Mon.Word.System.nu0_list_nil.
Check @Category.Instance.Mon.Word.System.nu0_list_letter.
Check @Category.Instance.Mon.Word.System.nu0_list_pair.
Check @Category.Instance.Mon.Word.System.nu0_list_respects.
Check @Category.Instance.Mon.Word.System.NAry0_hom.
Check @Category.Instance.Mon.Word.System.nu0_list_tup_to_list.
Check @Category.Instance.Mon.Word.System.tmap_tup_to_list.
Check @Category.Instance.Mon.Word.System.nu0_assoc.
Check @Category.Instance.Mon.Word.System.alg_NAry0.
Check @Category.Instance.Mon.Word.System.alg_NAry0_zero.
Check @Category.Instance.Mon.Word.System.alg_NAry0_at.
Check @Category.Instance.Mon.Word.System.alg_nu0_is_unit.
Check @Category.Instance.Mon.Word.System.alg_nu2_is_mul.
Check @Category.Instance.Mon.Word.System.alg_nu0_list.
Check @Category.Instance.Mon.Word.System.alg_NAry0_unit.
Check @Category.Instance.Mon.Word.System.alg_NAry0_assoc.
Check @Category.Instance.Mon.Word.System.alg_nu_is_fold.
Check @Category.Instance.Mon.Word.System.NAry0_alg.
Check @Category.Instance.Mon.Word.System.NAry0_alg_map.
Check @Category.Instance.Mon.Word.System.NAry0_rt_zero.
Check @Category.Instance.Mon.Word.System.NAry0_rt_pos_pair.
Check @Category.Instance.Mon.Word.System.NAry0_rt_pos.
Check @Category.Instance.Mon.Word.System.alg_round_trip0.
Check @Category.Instance.Mon.Word.System.alg_hom_NAry0_hom.
Check @Category.Instance.Mon.Word.System.NAry0_hom_alg_hom.
Check @Category.Instance.Mon.Word.System.W0System.
Check @Category.Instance.Mon.Word.System.Build_W0System.
Check @Category.Instance.Mon.Word.System.ws0_set.
Check @Category.Instance.Mon.Word.System.ws0_nu.
Check @Category.Instance.Mon.Word.System.ws0_unit.
Check @Category.Instance.Mon.Word.System.ws0_assoc.
Check @Category.Instance.Mon.Word.System.W0SystemHom.
Check @Category.Instance.Mon.Word.System.W0SystemHom_Setoid.
Check @Category.Instance.Mon.Word.System.W0System_id.
Check @Category.Instance.Mon.Word.System.W0System_compose.
Check @Category.Instance.Mon.Word.System.W0Sys.
Check @Category.Instance.Mon.Word.System.W0Sys_to_EM.
Check @Category.Instance.Mon.Word.System.EM_to_W0Sys.
Check @Category.Instance.Mon.Word.System.W0Sys_EM_counit_iso.
Check @Category.Instance.Mon.Word.System.W0Sys_EM_unit_iso.
Check @Category.Instance.Mon.Word.System.W0Sys_EM_iso.
Check @Category.Instance.Mon.Word.System.Mon_W0Sys_iso.
Check @Category.Instance.Mon.Word.System.W0Sys_EM_iso_to.
Check @Category.Instance.Mon.Word.System.W0Sys_EM_iso_from.
Check @Category.Instance.Mon.Word.System.W0Sys_to_EM_alg.
Check @Category.Instance.Mon.Word.System.EM_to_W0Sys_zero.
Check @Category.Instance.Mon.Word.System.EM_to_W0Sys_nu.
Check @Category.Instance.Mon.Word.System.W0Sys_rt_set.
Check @Category.Instance.Mon.Word.System.W0Sys_rt_zero.
Check @Category.Instance.Mon.Word.System.W0Sys_rt_hom.
Check @Category.Instance.Mon.Word.System.EM_W0Sys_rt_carrier.
Check @Category.Instance.Mon.Word.System.EM_W0Sys_rt_alg_hom.
Check @Category.Instance.Mon.Word.System.W0Sys_EM_iso_to_from_component.
Check @Category.Instance.Mon.Word.System.W0Sys_EM_iso_from_to_component.
Check @Category.Instance.Mon.Word.System.Mon_system_zero.
Check @Category.Instance.Mon.Word.System.Mon_system_pair.
Check @Category.Instance.Mon.Word.System.Mon_system_nu.
Check @Category.Instance.CMon.Free.perm_eq.
Check @Category.Instance.CMon.Free.pe_nil.
Check @Category.Instance.CMon.Free.pe_skip.
Check @Category.Instance.CMon.Free.pe_swap.
Check @Category.Instance.CMon.Free.pe_transitive.
Check @Category.Instance.CMon.Free.perm_eq_ind.
Check @Category.Instance.CMon.Free.perm_eq_sind.
Check @Category.Instance.CMon.Free.perm_eq_refl.
Check @Category.Instance.CMon.Free.perm_eq_sym.
Check @Category.Instance.CMon.Free.Bag_Setoid.
Check @Category.Instance.CMon.Free.BagObj.
Check @Category.Instance.CMon.Free.perm_eq_app_l.
Check @Category.Instance.CMon.Free.perm_eq_app_r.
Check @Category.Instance.CMon.Free.perm_eq_middle.
Check @Category.Instance.CMon.Free.perm_eq_app_comm.
Check @Category.Instance.CMon.Free.perm_eq_wmap.
Check @Category.Instance.CMon.Free.wmap_wapp.
Check @Category.Instance.CMon.Free.wmap_id.
Check @Category.Instance.CMon.Free.FreeCMonObject.
Check @Category.Instance.CMon.Free.FreeCMon_carrier.
Check @Category.Instance.CMon.Free.FreeCMon_plus.
Check @Category.Instance.CMon.Free.FreeCMon_zero.
Check @Category.Instance.CMon.Free.bag_insert.
Check @Category.Instance.CMon.Free.cfold.
Check @Category.Instance.CMon.Free.cfold_respects.
Check @Category.Instance.CMon.Free.cfold_app.
Check @Category.Instance.CMon.Free.cfold_hom.
Check @Category.Instance.CMon.Free.cfold_unique.
Check @Category.Instance.CMon.Free.FreeCMon_map.
Check @Category.Instance.CMon.Free.FreeCMon.
Check @Category.Instance.CMon.Free.FreeCMon_adj_iso.
Check @Category.Instance.CMon.Free.FreeCMon_adj.
Check @Category.Instance.CMon.Free.BagF.
Check @Category.Instance.CMon.Free.BagMonad.
Check @Category.Instance.CMon.Free.bconcat.
Check @Category.Instance.CMon.Free.Bag_obj.
Check @Category.Instance.CMon.Free.Bag_map.
Check @Category.Instance.CMon.Free.Bag_ret.
Check @Category.Instance.CMon.Free.Bag_join_counit.
Check @Category.Instance.CMon.Free.Bag_join.
Check @Category.Instance.CMon.Free.BagAlg.
Check @Category.Instance.CMon.Free.balg_unit.
Check @Category.Instance.CMon.Free.balg_action.
Check @Category.Instance.CMon.Free.balg_plus.
Check @Category.Instance.CMon.Free.balg_zero.
Check @Category.Instance.CMon.Free.balg_resp.
Check @Category.Instance.CMon.Free.balg_comm.
Check @Category.Instance.CMon.Free.balg_assoc.
Check @Category.Instance.CMon.Free.balg_zero_l.
Check @Category.Instance.CMon.Free.balg_prop.
Check @Category.Instance.CMon.Free.balg_cmon.
Check @Category.Instance.CMon.Free.balg_fold.
Check @Category.Instance.CMon.Free.EM_cmon_map.
Check @Category.Instance.CMon.Free.EM_to_CMon.
Check @Category.Instance.CMon.Free.CMon_K.
Check @Category.Instance.CMon.Free.CMon_EM_counit_iso.
Check @Category.Instance.CMon.Free.CMon_EM_unit_iso.
Check @Category.Instance.CMon.Free.CMon_EM_equivalence.
Check @Category.Instance.CMon.Free.CMon_Forget_Monadic.
Check @Category.Instance.CMon.Free.CMon_EM_iso.
Check @Category.Instance.CMon.Free.CMon_K_Forget.
Check @Category.Instance.CMon.Free.EM_to_CMon_Forget.
Check @Category.Instance.CMon.Free.CMon_EM_iso_to.
Check @Category.Instance.CMon.Free.CMon_EM_iso_from.
Check @Category.Instance.CMon.Free.CMon_K_alg_fun.
Check @Category.Instance.CMon.Free.CMon_K_zero.
Check @Category.Instance.CMon.Free.CMon_K_map.
Check @Category.Instance.CMon.Free.EM_to_CMon_plus.
Check @Category.Instance.CMon.Free.EM_to_CMon_zero.
Check @Category.Instance.CMon.Free.CMon_rt_carrier.
Check @Category.Instance.CMon.Free.CMon_rt_zero.
Check @Category.Instance.CMon.Free.CMon_rt_plus_fun.
Check @Category.Instance.CMon.Free.CMon_rt_hom.
Check @Category.Instance.CMon.Free.EM_CMon_rt_carrier.
Check @Category.Instance.CMon.Free.EM_CMon_rt_alg_hom.
Check @Category.Instance.CMon.Free.CMon_EM_iso_to_from_component.
Check @Category.Instance.CMon.Free.CMon_EM_iso_from_to_component.
Check @Category.Instance.CMon.Free.balg_prop_is.
