(** * Probe for words, free semigroups and the word monad (issue #470)

    Pins the measured boundaries of the three files #470 adds for Mac
    Lane, §VI.4, "Words and Free Semigroups", book pp. 144-146 (PDF
    pp. 153-155), catalog items maclane:VI.4:construction1,
    maclane:VI.4:prop1, maclane:VI.4:prop2, maclane:VI.4:cor1 and
    maclane:VI.4:remark1, read from the page images: the free semigroup
    WX = ∐ Xⁿ (n = 1, 2, …) of words under juxtaposition and the
    adjunction ⟨F, G, η, ε⟩ : Set ⇀ Smgrp, "ε_S(⟨s1⟩ … ⟨sn⟩) = s1 … sn
    (product in S)"; Proposition 1, the monad W with η_X x = ⟨x⟩ and μ_X
    removing "the outer pointy brackets"; Proposition 2, "the W-algebras
    have the form ⟨S, ν1, ν2, …⟩"; the Corollary, "ν1 = 1, ν2 … associative
    … and for all n ≥ 2, ν_{n+1} = νn(ν2 × 1)"; and the remark that the
    comparison K : Smgrp → Set^W "is an isomorphism".  The files are
    Theory/Algebra/Semigroup.v (internal semigroups and [Smgrp C]),
    Instance/Smgrp.v (words, the free semigroup and the adjunction) and
    Instance/Smgrp/Word.v (W, Propositions 1 and 2, the Corollary and K).
    Their headers cite the refutations and controls here:
    Theory/Algebra/Semigroup.v C1 and C2; Instance/Smgrp.v R1, R4, R5,
    C3 to C6, C11 to C17, C68 and C69; Instance/Smgrp/Word.v R2, R3, R6
    to R21, C19 to C31 and C33 to C67.  Each of the fifty-six [Example]s
    of the three targets, all proved by [eq_refl], has a control that
    restates it at the same generality and independently of the constant
    that states it (RESTATEMENTS, below).

    THE IMPORT LIST, generated by a script over the [Require] lines.
    Target by target in dependency order: Theory/Algebra/Semigroup.v's
    eight [Require] lines in its own order, and that target; the three
    lines Instance/Smgrp.v adds (Theory/Adjunction.v, Theory/Universal/
    Arrow.v and Instance/Sets.v), and that target; the six lines
    Instance/Smgrp/Word.v adds (Theory/Monad.v, Theory/Equivalence.v,
    Monad/Algebra.v, Monad/Eilenberg/Moore.v, Monad/Comparison.v and
    Instance/Cat.v), and that target.  Twenty lines, all naming
    [Category] modules.  Under them [Print Libraries] in a scratch file
    loads thirty-nine [Category] modules, exactly the set a [Require] of
    the three targets alone loads (compared by script).  A shorter import
    list is what makes a probe pass for no reason.

    DISCIPLINE.  Every negative other than the instrument is an
    [Example], never a [Check], so that an open evar cannot satisfy it.
    Each of the twenty-two refutation lines (the instrument and R1 to
    R21) was stripped of its refutation keyword in a copy of this WHOLE
    file, one at a time, compiled, and its error read; each copy stops
    inside the stripped command (twenty-two of twenty-two, by the File
    line of its error, compared by script with the command's extent).
    Each of the sixty-nine controls, wrapped in the refutation keyword in
    a copy of this WHOLE file, stops the build at that command with the
    message Rocq prints for a refutation whose command succeeds
    (sixty-nine of sixty-nine, by the same script).  Quotations are
    Rocq 9.1.1's under this file's import list, with the error's
    environment block left out; Rocq prints the "cannot unify"
    parenthetical with the short names in scope.  The three targets and
    this file also compile on Coq 8.19.2 and 8.20.1, with no warning from
    them, overlaid on copies of the dependency closure whose forty
    sources are this tree's byte for byte (compared by [cmp]); there too
    every refutation is refused and every control accepted.

    KINDS.  Twenty-two refutations, counted as the lines that open with
    the refutation keyword: NAME-ABSENCE, the instrument (one); and
    CONVERSION, [eq_refl] refused with a "cannot unify" parenthetical,
    every statement being well typed (R1 to R21: twenty-one).  R10 is
    well typed because a hom type of [WSys] depends on the set and the
    family alone, which come back at [eq_refl] (C37, C38).  The CAUSES
    are read from the terms, not from a flip of the dependency closure,
    but for R21's, which is measured: sigT has no η (R2, behind R7, R10,
    R11, R14 and R17, each of which compares a variable sigT pair, an
    object, a morphism or a word, with its rebuilt pair); prod has no η
    (R3, behind R16, and through it R15); a proof comes back rebuilt (R6,
    the law fields of the two monads; R9, the proof of (2), behind R8,
    whose record has η); data are stuck on a variable (R1, on the length
    n; R4, R5, R13 and R18, on a variable semigroup, map or algebra); R12,
    R19 and R20 compare composites whose object maps already differ (R8,
    R14, R17); and R21 is the opacity of Theory/Functor.v's
    [Functor_Setoid_obligation_1], from which Theory/Equivalence.v's
    [Equivalence_to_Cat_Iso] builds [iso_from_to] (opaque by [About]).
    That cause is measured, not argued, by the #470 audit: in a scratch
    file under this file's import list, the bridge's [iso_from_to] is the
    [symmetry] of the equivalence's unit at [eq_refl]; with that symmetry
    replaced by a transparent swap of the components, R21's statement
    holds at [eq_refl]; and R21 itself is still refused there, so the
    CONVERSION refusal is caused by that one opaque constant of the
    dependency closure (for Instance/SupLat.v's equivalence the same
    component holds in #466's flip, where that obligation is
    transparent).  Measured too: every refutation, R21 included, still
    stops inside its command, with the instrument, in a copy of the three
    targets with their forty-one [Qed]s turned [Defined] and [Transparent
    Obligations] set, under which this whole file otherwise compiles and
    [About] reports transparent what the tree has opaque; so none is the
    opacity of the three targets.

    LABELS.  The labels are not constants: each refutation and each
    control carries its label in a comment on the line above it, the
    instrument's reading "The instrument".  C1 and C2 pin
    Theory/Algebra/Semigroup.v; C3 to C18, C68 and C69 with R1 to R5
    Instance/Smgrp.v (R2 and R3 with C8 to C10 the absence of η for sigT
    and prod, cited by Instance/Smgrp/Word.v; C68 and C69, the universal
    arrow, numbered after the rest and placed beside C11); C19 to C28
    with R6 Proposition 1; C29 to C32 with R7 Proposition 2; C33 to C44
    with R8 to R12 its category; C45 with R13 the Corollary; C46 to C67
    with R14 to R21 the comparison K.  The constants are [p470_cN_…] and
    [p470_rN_…] for label CN or RN.

    RESTATEMENTS.  Theory/Algebra/Semigroup.v: [Mon_Smgrp_Forget_obj] C1,
    [Mon_Smgrp_Forget_map] C2.  Instance/Smgrp.v: [FreeSg_carrier] C3,
    [FreeSg_mul] C4, [FreeSg_mul_literal] C5, [sg_insert_universal_obj]
    C11, [sg_insert_UA_obj] C68, [sg_insert_UA_arrow] C69, [Sg_adj_unit]
    C12, [Sg_adj_counit_letter] C13, [Sg_adj_counit] C14,
    [Sg_adj_counit_literal] C15.  Instance/Smgrp/Word.v: [W_obj] C19,
    [W_carrier] C20, [W_map] C21, [W_ret] C22, [W_ret_fun] C23,
    [W_join_counit] C24, [W_join_fun] C25, [W_join_literal] C26,
    [WordMonad_direct_ret] C27, [WordMonad_direct_join] C28,
    [alg_NAry_at] C29, [NAry_round_trip] C30, [WSys_EM_iso_to] C33,
    [WSys_EM_iso_from] C34, [WSys_to_EM_alg] C35, [EM_to_WSys_nu] C36,
    [WSys_rt_set] C37, [WSys_rt_nu] C38, [WSys_rt_unit] C39,
    [WSys_rt_hom] C40, [EM_WSys_rt_carrier] C41, [EM_WSys_rt_alg_hom]
    C42, [WSys_EM_iso_to_from_component] C43,
    [WSys_EM_iso_from_to_component] C44, [Smgrp_EM_iso_to] C46,
    [Smgrp_EM_iso_from] C47, [Sg_K_carrier] C48, [Sg_K_alg] C49,
    [Sg_K_alg_fun] C50, [Sg_K_nu1] C51, [Sg_K_nu2] C52, [Sg_K_nu_succ]
    C53, [Sg_K_map] C54, [Sg_K_system_nu] C55, [Sg_K_system_nu2] C56,
    [Smgrp_EM_rt_carrier] C57, [Smgrp_EM_rt_mul] C58, [Smgrp_EM_rt_hom]
    C59, [EM_Smgrp_rt_carrier] C60, [EM_Smgrp_rt_alg_hom] C61,
    [Smgrp_EM_iso_to_from_component] C62,
    [Smgrp_EM_iso_from_to_component] C63, [Smgrp_EM_counit_component]
    C64, [Smgrp_EM_unit_component] C65.  Fifty-six readbacks, each named
    once.  C6 to C10, C16 to C18, C31, C32, C45, C66 and C67 restate no
    readback: they are the twins of refutations.

    THE REFUSALS, with the parenthetical each stripped copy prints.
      The instrument (NAME-ABSENCE): The reference p470_absent_name was
        not found in the current environment.
      R1, juxtaposition at variable words (control C6, literal words; C7,
        ≈): (cannot unify "pwapp (pwapp w v) u" and
        "pwapp w (pwapp v u)")
      R2, a variable word against its rebuilt pair (control C9, a
        literal pair; C8, a setoid against its rebuilt record):
        (cannot unify "p" and "(`1 (p); `2 (p))")
      R3, a variable pair (control C10, a literal pair):
        (cannot unify "λ p : X ∧ X, (fst p, snd p)" and "λ p : X ∧ X, p")
      R4, (1) bracketed to the right (control C16, ≈):
        (cannot unify "projT1 counit (2%nat; (s1, (s2, s3)))" and
        "sg_mul S s1 (sg_mul S s2 s3)")
      R5, a semigroup map out of F X at a variable word (control C17, a
        letter; C18, ≈): (cannot unify "sg_fun g w" and
        "pwfold (λ y : X, sg_fun g (letter y)) w")
      R6, the two monads (controls C27, C28): (cannot unify
        "WordMonad_direct" and "WordMonad")
      R7, the rebuilt structure map (control C31, at (n; t); C32, ≈):
        (cannot unify "t_alg[NAry_alg (alg_NAry α) (alg_NAry_unit α)
        (alg_NAry_assoc α)]" and "t_alg[α]")
      R8, the whole system (controls C37 to C39): (cannot unify
        "fobj[EM_to_WSys ◯ WSys_to_EM] A" and "A")
      R9, its proof of (2): (cannot unify "ws_assoc (fobj[EM_to_WSys ◯
        WSys_to_EM] A)" and "ws_assoc A")
      R10, a whole morphism (control C40): (cannot unify
        "fmap[EM_to_WSys ◯ WSys_to_EM] f" and "f")
      R11, the whole algebra (control C41): (cannot unify
        "fobj[WSys_to_EM ◯ EM_to_WSys] x" and "x")
      R12: (cannot unify "EM_to_WSys ◯ WSys_to_EM" and "Id[WSys]")
      R13, ν3 in an arbitrary algebra (control C45, ≈; C53, in K S):
        (cannot unify "nu (alg_NAry α) 2 (a, (b, c))" and
        "nu2 (alg_NAry α) (nu2 (alg_NAry α) a b) c")
      R14, the semigroup round trip (controls C57 to C59): (cannot unify
        "fobj[EM_to_Smgrp ◯ Sg_K] A" and "A")
      R15, at a pair: (cannot unify "fobj[EM_to_Smgrp ◯ Sg_K] (X; σ)" and
        "(X; σ)")
      R16, its uncurried multiplication (control C66, at (a, b)):
        (cannot unify "λ p : X ∧ X, smu[projT2 (fobj[EM_to_Smgrp ◯ Sg_K]
        (X; σ))] p" and "λ p : X ∧ X, smu[σ] p")
      R17, the algebra round trip (controls C60, C61): (cannot unify
        "fobj[Sg_K ◯ EM_to_Smgrp] x" and "x")
      R18, its structure map: (cannot unify "t_alg[projT2 (fobj[Sg_K ◯
        EM_to_Smgrp] x)]" and "t_alg[`2 (x)]")
      R19: (cannot unify "EM_to_Smgrp ◯ Sg_K" and "Id[SmgrpSets]")
      R20: (cannot unify "Sg_K ◯ EM_to_Smgrp" and "Id[WordAlg]")
      R21, through the bridge (control C67, the other component; C63,
        the direct isomorphism): (cannot unify "sg_fun (projT1
        (iso_from_to (Equivalence_to_Cat_Iso Smgrp_EM_equivalence)) A)"
        and "λ a : sg_ob (fobj[(Equivalence_to_Cat_Iso
        Smgrp_EM_equivalence)⁻¹ ∘ Equivalence_to_Cat_Iso
        Smgrp_EM_equivalence] A), a")

    NOT PINNED HERE.  (a) [About] readbacks as such: the headers'
    universe censuses.  (b) The flips and copies the headers describe
    (each [Defined] closed [Qed] alone; every [Qed] turned [Defined]; the
    three targets compiled against a built tree of master 687ac356, before
    #1347): made in scratch copies.  (c) The closure of the targets under
    [Print Assumptions]: the Makefile's print-assumptions gate names the
    same one hundred and ninety-eight names as the guard below.  (d) The
    absences the headers record: an absence has no command.  (e) The
    dependency-closure counts.  (f) The readings of the book, from the
    page images.

    The guard block names the one hundred and ninety-eight names of the
    three targets, so that a rename breaks this file: thirty of
    Theory/Algebra/Semigroup.v (its twelve [Program] obligations among
    them), sixty-three of Instance/Smgrp.v and one hundred and five of
    Instance/Smgrp/Word.v.  They are exactly the entries [Print Module]
    gives for each, the four records [Semigroup], [SemigroupHom], [NAry]
    and [WSystem] with their constructors among them.  Each is written
    fully qualified and with [@], so that no short name in scope can stand
    in for it. *)

Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Functor.Bifunctor.
Require Import Category.Structure.Monoidal.
Require Import Category.Theory.Algebra.Monoid.
Require Import Category.Theory.Algebra.Monoid.Hom.
Require Import Category.Theory.Algebra.Semigroup.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Universal.Arrow.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Smgrp.
Require Import Category.Theory.Monad.
Require Import Category.Theory.Equivalence.
Require Import Category.Monad.Algebra.
Require Import Category.Monad.Eilenberg.Moore.
Require Import Category.Monad.Comparison.
Require Import Category.Instance.Cat.
Require Import Category.Instance.Smgrp.Word.

Generalizable All Variables.

(* ------------------------------------------------------------------------ *)
(** ** The instrument *)

(* The instrument *)
Fail Check p470_absent_name.

(* ------------------------------------------------------------------------ *)
(** ** Theory/Algebra/Semigroup.v *)

(* C1: forgetting the unit, then the multiplication, forgets both. *)
Example p470_c1_mon_smgrp_obj {C : Category} `{M : @Monoidal C}
  (X : Mon C) : fobj[Smgrp_Forget] (fobj[Mon_Smgrp] X) = `1 X := eq_refl.

(* C2: and on arrows. *)
Example p470_c2_mon_smgrp_map {C : Category} `{M : @Monoidal C}
  {X Y : Mon C} (f : X ~> Y) :
  fmap[Smgrp_Forget] (fmap[Mon_Smgrp] f) = `1 f := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Smgrp.v: words and juxtaposition *)

(* C3: the carrier of F X is W X. *)
Example p470_c3_free_carrier@{o so} (X : SetoidObject@{o o}) :
  `1 (FreeSg@{o so} X) = PWordObj@{o} X := eq_refl.

(* C4: its multiplication is juxtaposition. *)
Example p470_c4_free_mul@{o so} (X : SetoidObject@{o o}) (w v : PWord@{o} X) :
  sg_mul (FreeSg@{o so} X) w v = pwapp w v := eq_refl.

(* C5: (⟨x1⟩⟨x2⟩)(⟨y1⟩) = ⟨x1⟩⟨x2⟩⟨y1⟩. *)
Example p470_c5_free_mul_literal@{o so} (X : SetoidObject@{o o})
  (x1 x2 y1 : X) :
  sg_mul (FreeSg@{o so} X) (existT (fun n => Tup X n) 1%nat (x1, x2))
    (letter y1)
    = existT (fun n => Tup X n) 2%nat (x1, (x2, y1)) := eq_refl.

(* C6: juxtaposition is associative on the nose on literal words. *)
Example p470_c6_assoc_literal@{o} (X : SetoidObject@{o o}) (a b c : X) :
  pwapp (pwapp (letter a) (letter b)) (letter c)
    = pwapp (letter a) (pwapp (letter b) (letter c)) := eq_refl.

(* C7: and up to ≈ at variable words. *)
Definition p470_c7_assoc_equiv@{o} (X : SetoidObject@{o o})
  (w v u : PWord@{o} X) :
  pwapp (pwapp w v) u ≈ pwapp w (pwapp v u) := pwapp_assoc w v u.

(* R1 *)
Fail Example p470_r1_assoc_variable@{o} (X : SetoidObject@{o o})
  (w v u : PWord@{o} X) :
  pwapp (pwapp w v) u = pwapp w (pwapp v u) := eq_refl.

(* C8: a setoid, a record with primitive projections, converts with its
   rebuilt record. *)
Example p470_c8_setoid_eta@{o} (X : SetoidObject@{o o}) :
  X = {| carrier := carrier X; is_setoid := is_setoid X |} := eq_refl.

(* C9: a literal word converts with its rebuilt pair. *)
Example p470_c9_sigT_literal@{o} (X : SetoidObject@{o o}) (n : nat)
  (t : Tup@{o} X n) :
  existT (fun k => Tup X k) (projT1 (existT (fun k => Tup X k) n t))
    (projT2 (existT (fun k => Tup X k) n t))
    = existT (fun k => Tup X k) n t := eq_refl.

(* R2 *)
Fail Example p470_r2_sigT_eta@{o} (X : SetoidObject@{o o})
  (p : PWord@{o} X) :
  p = existT (fun k => Tup X k) (projT1 p) (projT2 p) := eq_refl.

(* C10: a literal pair converts with its rebuilt pair. *)
Example p470_c10_prod_literal@{o} (X : SetoidObject@{o o}) (a b : X) :
  (fst (a, b), snd (a, b)) = (a, b) := eq_refl.

(* R3 *)
Fail Example p470_r3_prod_eta@{o} (X : SetoidObject@{o o}) :
  (fun p : prod X X => (fst p, snd p)) = (fun p : prod X X => p) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Smgrp.v: the adjunction Set ⇀ Smgrp *)

(* C11: the factorization of h through η_X is the extension of h. *)
Example p470_c11_universal_obj@{o so} (X : SetoidObject@{o o})
  (A : SmgrpSets@{o so}) (h : X ~{Sets@{o so}}~> fobj[Sg_Forget@{o so}] A) :
  unique_obj (sg_insert_universal@{o so} X A h) = sg_extend@{o so} h
  := eq_refl.

(* C68: η_X as Theory/Universal/Arrow.v's universal arrow from X to G has
   F X as its universal object... *)
Example p470_c68_ua_obj@{o so +} (X : SetoidObject@{o o}) :
  @arrow_obj Sets@{o so} SmgrpSets@{o so} X Sg_Forget@{o so}
    (sg_insert_UA X) = FreeSg@{o so} X := eq_refl.

(* C69: ...and the insertion x ↦ ⟨x⟩ as its arrow. *)
Example p470_c69_ua_arrow@{o so +} (X : SetoidObject@{o o}) :
  @arrow Sets@{o so} SmgrpSets@{o so} X Sg_Forget@{o so}
    (sg_insert_UA X) = sg_insert@{o so} X := eq_refl.

(* C12: the unit of the adjunction is the insertion x ↦ ⟨x⟩. *)
Example p470_c12_unit@{o so} (X : SetoidObject@{o o}) :
  @unit _ _ _ _ Sg_adj@{o so} X = sg_insert@{o so} X := eq_refl.

(* C13: ε_S sends each generator ⟨s⟩ to s. *)
Example p470_c13_counit_letter@{o so} (S : SmgrpSets@{o so})
  (s : sg_ob S) :
  `1 (@counit _ _ _ _ Sg_adj@{o so} S) (letter s) = s := eq_refl.

(* C14: (1), ε_S(⟨s1⟩⋯⟨sn⟩) = s1⋯sn, bracketed to the left. *)
Example p470_c14_counit@{o so} (S : SmgrpSets@{o so})
  (w : PWord@{o} (sg_ob S)) :
  `1 (@counit _ _ _ _ Sg_adj@{o so} S) w = tfold1 (fun s => s) (`1 w) (`2 w)
  := eq_refl.

(* C15: at a literal word of three letters. *)
Example p470_c15_counit_literal@{o so} (S : SmgrpSets@{o so})
  (s1 s2 s3 : sg_ob S) :
  `1 (@counit _ _ _ _ Sg_adj@{o so} S)
    (existT (fun n => Tup (sg_ob S) n) 2%nat (s1, (s2, s3)))
  = sg_mul S (sg_mul S s1 s2) s3 := eq_refl.

(* C16: the right bracketing, up to ≈. *)
Definition p470_c16_counit_right_equiv@{o so} (S : SmgrpSets@{o so})
  (s1 s2 s3 : sg_ob S) :
  `1 (@counit _ _ _ _ Sg_adj@{o so} S)
    (existT (fun n => Tup (sg_ob S) n) 2%nat (s1, (s2, s3)))
  ≈ sg_mul S s1 (sg_mul S s2 s3) := sg_mul_assoc S s1 s2 s3.

(* R4 *)
Fail Example p470_r4_counit_right@{o so} (S : SmgrpSets@{o so})
  (s1 s2 s3 : sg_ob S) :
  `1 (@counit _ _ _ _ Sg_adj@{o so} S)
    (existT (fun n => Tup (sg_ob S) n) 2%nat (s1, (s2, s3)))
  = sg_mul S s1 (sg_mul S s2 s3) := eq_refl.

(* C17: a semigroup map out of F X is the fold of its values on the
   letters, on the nose at a one-letter word. *)
Example p470_c17_unique_letter@{o so} (X : SetoidObject@{o o})
  (A : SmgrpSets@{o so}) (g : FreeSg@{o so} X ~{SmgrpSets@{o so}}~> A)
  (x : X) :
  sg_fun g (letter x) = pwfold (fun y => sg_fun g (letter y)) (letter x)
  := eq_refl.

(* C18: and up to ≈ at a variable word. *)
Definition p470_c18_unique_equiv@{o so} (X : SetoidObject@{o o})
  (A : SmgrpSets@{o so}) (g : FreeSg@{o so} X ~{SmgrpSets@{o so}}~> A)
  (w : PWord@{o} X) :
  sg_fun g w ≈ pwfold (fun y => sg_fun g (letter y)) w :=
  sg_extend_unique g w.

(* R5 *)
Fail Example p470_r5_unique_variable@{o so} (X : SetoidObject@{o o})
  (A : SmgrpSets@{o so}) (g : FreeSg@{o so} X ~{SmgrpSets@{o so}}~> A)
  (w : PWord@{o} X) :
  sg_fun g w = pwfold (fun y => sg_fun g (letter y)) w := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Smgrp/Word.v: Proposition 1 *)

(* C19: W X is the setoid of words. *)
Example p470_c19_W_obj@{o so} (X : SetoidObject@{o o}) :
  fobj[Sg_Forget@{o so} ◯ Sg_Free@{o so}] X = PWordObj@{o} X := eq_refl.

(* C20: its carrier is ∐_{n≥1} X^n. *)
Example p470_c20_W_carrier@{o so} (X : SetoidObject@{o o}) :
  carrier (fobj[WordF@{o so}] X) = sigT (fun n : nat => Tup@{o} X n)
  := eq_refl.

(* C21: W f acts letterwise. *)
Example p470_c21_W_map@{o so} {X Y : SetoidObject@{o o}}
  (f : X ~{Sets@{o so}}~> Y) (w : PWord@{o} X) :
  fmap[WordF@{o so}] f w = existT _ (`1 w) (tmap f (`1 w) (`2 w)) := eq_refl.

(* C22: η_X is the insertion, as a setoid map. *)
Example p470_c22_W_ret@{o so} (X : SetoidObject@{o o}) :
  @ret _ _ WordMonad@{o so} X = sg_insert@{o so} X := eq_refl.

(* C23: η_X x = ⟨x⟩. *)
Example p470_c23_W_ret_fun@{o so} (X : SetoidObject@{o o}) (x : X) :
  @ret _ _ WordMonad@{o so} X x = existT (fun n => Tup X n) O x := eq_refl.

(* C24: μ = G ε F. *)
Example p470_c24_W_join_counit@{o so} (X : SetoidObject@{o o}) :
  @join _ _ WordMonad@{o so} X
    = fmap[Sg_Forget@{o so}]
        (@counit _ _ _ _ Sg_adj@{o so} (fobj[Sg_Free@{o so}] X))
  := eq_refl.

(* C25: μ is the concatenation of a word of words. *)
Example p470_c25_W_join_fun@{o so} (X : SetoidObject@{o o})
  (ww : PWord@{o} (PWordObj@{o} X)) :
  @join _ _ WordMonad@{o so} X ww
    = tfold1 (A := FreeSg@{o so} X) (fun w => w) (`1 ww) (`2 ww)
  := eq_refl.

(* C26: μ⟨⟨x11⟩⟨x12⟩⟩⟨⟨x21⟩⟩ = ⟨x11⟩⟨x12⟩⟨x21⟩. *)
Example p470_c26_W_join_literal@{o so} (X : SetoidObject@{o o})
  (x11 x12 x21 : X) :
  @join _ _ WordMonad@{o so} X
    (existT (fun n => Tup (PWordObj X) n) 1%nat
       (existT (fun n => Tup X n) 1%nat (x11, x12), letter x21))
  = existT (fun n => Tup X n) 2%nat (x11, (x12, x21)) := eq_refl.

(* C27: the direct monad's unit is W's. *)
Example p470_c27_direct_ret@{o so} (X : SetoidObject@{o o}) :
  @ret _ _ WordMonad_direct@{o so} X = @ret _ _ WordMonad@{o so} X
  := eq_refl.

(* C28: and so is its multiplication. *)
Example p470_c28_direct_join@{o so} (X : SetoidObject@{o o}) :
  @join _ _ WordMonad_direct@{o so} X = @join _ _ WordMonad@{o so} X
  := eq_refl.

(* R6 *)
Fail Example p470_r6_monads_eq@{o so} :
  WordMonad_direct@{o so} = WordMonad@{o so} := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Smgrp/Word.v: Proposition 2 *)

(* C29: ν_n of an algebra is h at (n; t). *)
Example p470_c29_alg_NAry_at@{o so} {X : SetoidObject@{o o}}
  (α : @TAlgebra Sets@{o so} WordF@{o so} WordMonad@{o so} X) (n : nat)
  (t : Tup@{o} X n) :
  nu (alg_NAry α) n t = t_alg[α] (existT _ n t) := eq_refl.

(* C30: family → algebra → family is the family itself. *)
Example p470_c30_NAry_round_trip@{o so} {X : SetoidObject@{o o}}
  (ν : NAry@{o} X) (Hu : nu_unit ν) (Ha : nu_assoc@{o so} ν) :
  alg_NAry (NAry_alg@{o so} ν Hu Ha) = ν := eq_refl.

(* C31: algebra → family → algebra keeps h at each (n; t). *)
Example p470_c31_alg_rt_at@{o so} {X : SetoidObject@{o o}}
  (α : @TAlgebra Sets@{o so} WordF@{o so} WordMonad@{o so} X) (n : nat)
  (t : Tup@{o} X n) :
  t_alg[NAry_alg@{o so} (alg_NAry α) (alg_NAry_unit α) (alg_NAry_assoc α)]
    (existT _ n t) = t_alg[α] (existT _ n t) := eq_refl.

(* C32: and h itself up to ≈. *)
Definition p470_c32_alg_rt_equiv@{o so} {X : SetoidObject@{o o}}
  (α : @TAlgebra Sets@{o so} WordF@{o so} WordMonad@{o so} X) :
  t_alg[NAry_alg@{o so} (alg_NAry α) (alg_NAry_unit α) (alg_NAry_assoc α)]
    ≈ t_alg[α] := alg_round_trip α.

(* R7 *)
Fail Example p470_r7_alg_rt_map@{o so} {X : SetoidObject@{o o}}
  (α : @TAlgebra Sets@{o so} WordF@{o so} WordMonad@{o so} X) :
  t_alg[NAry_alg@{o so} (alg_NAry α) (alg_NAry_unit α) (alg_NAry_assoc α)]
    = t_alg[α] := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Smgrp/Word.v: Proposition 2 as a category *)

(* C33: the leg [to] of [WSys_EM_iso]. *)
Example p470_c33_wsys_iso_to@{o so c} :
  to WSys_EM_iso@{o so c} = WSys_to_EM@{o so} := eq_refl.

(* C34: the leg [from]. *)
Example p470_c34_wsys_iso_from@{o so c} :
  from WSys_EM_iso@{o so c} = EM_to_WSys@{o so} := eq_refl.

(* C35: a system's structure map is the copairing of its family. *)
Example p470_c35_wsys_to_em_alg@{o so} (A : WSys@{o so})
  (p : PWord@{o} (ws_set A)) :
  t_alg[`2 (fobj[WSys_to_EM@{o so}] A)] p = nu (ws_nu A) (`1 p) (`2 p)
  := eq_refl.

(* C36: an algebra's ν_n is h on S^n. *)
Example p470_c36_em_to_wsys_nu@{o so} (x : WordAlg@{o so}) (n : nat)
  (t : Tup@{o} (`1 x) n) :
  nu (ws_nu (fobj[EM_to_WSys@{o so}] x)) n t = t_alg[`2 x] (existT _ n t)
  := eq_refl.

(* C37: the system round trip keeps the set... *)
Example p470_c37_wsys_rt_set@{o so} (A : WSys@{o so}) :
  ws_set (fobj[EM_to_WSys@{o so} ◯ WSys_to_EM@{o so}] A) = ws_set A
  := eq_refl.

(* C38: ...the family of operations... *)
Example p470_c38_wsys_rt_nu@{o so} (A : WSys@{o so}) :
  ws_nu (fobj[EM_to_WSys@{o so} ◯ WSys_to_EM@{o so}] A) = ws_nu A
  := eq_refl.

(* C39: ...and the proof of ν1 = 1. *)
Example p470_c39_wsys_rt_unit@{o so} (A : WSys@{o so}) :
  ws_unit (fobj[EM_to_WSys@{o so} ◯ WSys_to_EM@{o so}] A) = ws_unit A
  := eq_refl.

(* C40: it keeps the map of a morphism. *)
Example p470_c40_wsys_rt_hom@{o so} {A B : WSys@{o so}}
  (f : A ~{WSys@{o so}}~> B) :
  `1 (fmap[EM_to_WSys@{o so} ◯ WSys_to_EM@{o so}] f) = `1 f := eq_refl.

(* C41: the algebra round trip keeps the carrier... *)
Example p470_c41_em_wsys_rt_carrier@{o so} (x : WordAlg@{o so}) :
  `1 (fobj[WSys_to_EM@{o so} ◯ EM_to_WSys@{o so}] x) = `1 x := eq_refl.

(* C42: ...and the map of a morphism. *)
Example p470_c42_em_wsys_rt_alg_hom@{o so} {x y : WordAlg@{o so}}
  (f : x ~{WordAlg@{o so}}~> y) :
  t_alg_hom[fmap[WSys_to_EM@{o so} ◯ EM_to_WSys@{o so}] f] = t_alg_hom[f]
  := eq_refl.

(* C43: the components of [iso_to_from] are identities. *)
Example p470_c43_wsys_to_from_component@{o so c} (x : WordAlg@{o so}) :
  (t_alg_hom[to (`1 (iso_to_from WSys_EM_iso@{o so c}) x)],
   t_alg_hom[from (`1 (iso_to_from WSys_EM_iso@{o so c}) x)])
    = (@setoid_morphism_id@{o o o} (`1 x),
       @setoid_morphism_id@{o o o} (`1 x)) := eq_refl.

(* C44: so are those of [iso_from_to]. *)
Example p470_c44_wsys_from_to_component@{o so c} (A : WSys@{o so}) :
  (`1 (to (`1 (iso_from_to WSys_EM_iso@{o so c}) A)),
   `1 (from (`1 (iso_from_to WSys_EM_iso@{o so c}) A)))
    = (@setoid_morphism_id@{o o o} (ws_set A),
       @setoid_morphism_id@{o o o} (ws_set A)) := eq_refl.

(* R8 *)
Fail Example p470_r8_wsys_rt_obj@{o so} (A : WSys@{o so}) :
  fobj[EM_to_WSys@{o so} ◯ WSys_to_EM@{o so}] A = A := eq_refl.

(* R9 *)
Fail Example p470_r9_wsys_rt_assoc@{o so} (A : WSys@{o so}) :
  ws_assoc (fobj[EM_to_WSys@{o so} ◯ WSys_to_EM@{o so}] A) = ws_assoc A
  := eq_refl.

(* R10 *)
Fail Example p470_r10_wsys_rt_hom@{o so} {A B : WSys@{o so}}
  (f : A ~{WSys@{o so}}~> B) :
  fmap[EM_to_WSys@{o so} ◯ WSys_to_EM@{o so}] f = f := eq_refl.

(* R11 *)
Fail Example p470_r11_em_wsys_rt_obj@{o so} (x : WordAlg@{o so}) :
  fobj[WSys_to_EM@{o so} ◯ EM_to_WSys@{o so}] x = x := eq_refl.

(* R12 *)
Fail Example p470_r12_wsys_functor@{o so} :
  EM_to_WSys@{o so} ◯ WSys_to_EM@{o so} = Id[WSys@{o so}] := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Smgrp/Word.v: the Corollary *)

(* C45: in any algebra ν3 is the iterate of ν2, up to ≈. *)
Definition p470_c45_alg_nu3_equiv@{o so} {X : SetoidObject@{o o}}
  (α : @TAlgebra Sets@{o so} WordF@{o so} WordMonad@{o so} X) (a b c : X) :
  nu (alg_NAry α) 2%nat (a, (b, c))
    ≈ nu2 (alg_NAry α) (nu2 (alg_NAry α) a b) c :=
  snd (cor_forward (alg_NAry α) (alg_NAry_unit α) (alg_NAry_assoc α))
    O a b c.

(* R13 *)
Fail Example p470_r13_alg_nu3@{o so} {X : SetoidObject@{o o}}
  (α : @TAlgebra Sets@{o so} WordF@{o so} WordMonad@{o so} X) (a b c : X) :
  nu (alg_NAry α) 2%nat (a, (b, c))
    = nu2 (alg_NAry α) (nu2 (alg_NAry α) a b) c := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Smgrp/Word.v: the comparison K *)

(* C46: the leg [to] of [Smgrp_EM_iso] is K. *)
Example p470_c46_iso_to@{o so c} :
  to Smgrp_EM_iso@{o so c} = EM_Comparison Sg_adj@{o so} := eq_refl.

(* C47: the leg [from]. *)
Example p470_c47_iso_from@{o so c} :
  from Smgrp_EM_iso@{o so c} = EM_to_Smgrp@{o so} := eq_refl.

(* C48: K ⟨S, ν⟩ has carrier S. *)
Example p470_c48_K_carrier@{o so} (A : SmgrpSets@{o so}) :
  `1 (fobj[Sg_K@{o so}] A) = `1 A := eq_refl.

(* C49: its structure map is G ε_S. *)
Example p470_c49_K_alg@{o so} (A : SmgrpSets@{o so}) :
  t_alg[`2 (fobj[Sg_K@{o so}] A)]
    = fmap[Sg_Forget@{o so}] (@counit _ _ _ _ Sg_adj@{o so} A) := eq_refl.

(* C50: its value is the product of the letters, bracketed to the left. *)
Example p470_c50_K_alg_fun@{o so} (A : SmgrpSets@{o so})
  (p : PWord@{o} (sg_ob A)) :
  t_alg[`2 (fobj[Sg_K@{o so}] A)] p = tfold1 (fun s => s) (`1 p) (`2 p)
  := eq_refl.

(* C51: ν1 = 1. *)
Example p470_c51_K_nu1@{o so} (A : SmgrpSets@{o so}) (x : sg_ob A) :
  t_alg[`2 (fobj[Sg_K@{o so}] A)] (existT (fun n => Tup (sg_ob A) n) O x)
    = x := eq_refl.

(* C52: ν2 = ν. *)
Example p470_c52_K_nu2@{o so} (A : SmgrpSets@{o so}) (a b : sg_ob A) :
  t_alg[`2 (fobj[Sg_K@{o so}] A)] (existT _ 1%nat (a, b))
    = @smu _ _ _ (`2 A) (a, b) := eq_refl.

(* C53: ν_{m+3}(x, y, t) = ν_{m+2}(xy, t). *)
Example p470_c53_K_nu_succ@{o so} (A : SmgrpSets@{o so}) (m : nat)
  (x y : sg_ob A) (t : Tup@{o} (sg_ob A) m) :
  t_alg[`2 (fobj[Sg_K@{o so}] A)] (existT _ (S (S m)) (x, (y, t)))
    = t_alg[`2 (fobj[Sg_K@{o so}] A)]
        (existT _ (S m) (sg_mul A x y, t)) := eq_refl.

(* C54: K f has underlying map f. *)
Example p470_c54_K_map@{o so} {A B : SmgrpSets@{o so}}
  (f : A ~{SmgrpSets@{o so}}~> B) :
  t_alg_hom[fmap[Sg_K@{o so}] f] = `1 f := eq_refl.

(* C55: K ⟨S, ν⟩ as a system: νn is the left-bracketed product. *)
Example p470_c55_K_system_nu@{o so} (A : SmgrpSets@{o so}) (n : nat)
  (t : Tup@{o} (sg_ob A) n) :
  nu (ws_nu (fobj[EM_to_WSys@{o so}] (fobj[Sg_K@{o so}] A))) n t
    = tfold1 (fun s => s) n t := eq_refl.

(* C56: ...and ν2 is the multiplication. *)
Example p470_c56_K_system_nu2@{o so} (A : SmgrpSets@{o so})
  (a b : sg_ob A) :
  nu (ws_nu (fobj[EM_to_WSys@{o so}] (fobj[Sg_K@{o so}] A))) 1%nat (a, b)
    = sg_mul A a b := eq_refl.

(* C57: the semigroup round trip keeps the carrier... *)
Example p470_c57_sg_rt_carrier@{o so} (A : SmgrpSets@{o so}) :
  `1 (fobj[EM_to_Smgrp@{o so} ◯ Sg_K@{o so}] A) = `1 A := eq_refl.

(* C58: ...the curried multiplication... *)
Example p470_c58_sg_rt_mul@{o so} (A : SmgrpSets@{o so}) :
  sg_mul (fobj[EM_to_Smgrp@{o so} ◯ Sg_K@{o so}] A) = sg_mul A := eq_refl.

(* C59: ...and the map of a morphism. *)
Example p470_c59_sg_rt_hom@{o so} {A B : SmgrpSets@{o so}}
  (f : A ~{SmgrpSets@{o so}}~> B) :
  (fun a => `1 (fmap[EM_to_Smgrp@{o so} ◯ Sg_K@{o so}] f) a)
    = (fun a => `1 f a) := eq_refl.

(* C60: the algebra round trip keeps the carrier... *)
Example p470_c60_em_rt_carrier@{o so} (x : WordAlg@{o so}) :
  `1 (fobj[Sg_K@{o so} ◯ EM_to_Smgrp@{o so}] x) = `1 x := eq_refl.

(* C61: ...and the map of a morphism. *)
Example p470_c61_em_rt_alg_hom@{o so} {x y : WordAlg@{o so}}
  (f : x ~{WordAlg@{o so}}~> y) :
  t_alg_hom[fmap[Sg_K@{o so} ◯ EM_to_Smgrp@{o so}] f] = t_alg_hom[f]
  := eq_refl.

(* C62: the components of [iso_to_from] are identities. *)
Example p470_c62_iso_to_from_component@{o so c} (x : WordAlg@{o so}) :
  (t_alg_hom[to (`1 (iso_to_from Smgrp_EM_iso@{o so c}) x)],
   t_alg_hom[from (`1 (iso_to_from Smgrp_EM_iso@{o so c}) x)])
    = (@setoid_morphism_id@{o o o} (`1 x),
       @setoid_morphism_id@{o o o} (`1 x)) := eq_refl.

(* C63: so are those of [iso_from_to], as functions. *)
Example p470_c63_iso_from_to_component@{o so c} (A : SmgrpSets@{o so}) :
  (sg_fun (to (`1 (iso_from_to Smgrp_EM_iso@{o so c}) A)),
   sg_fun (from (`1 (iso_from_to Smgrp_EM_iso@{o so c}) A)))
    = ((fun a : sg_ob A => a), (fun a : sg_ob A => a)) := eq_refl.

(* C64: and those of the equivalence's counit. *)
Example p470_c64_counit_component@{o so} (x : WordAlg@{o so}) :
  (t_alg_hom[to (`1 (@equivalence_counit _ _ _
                       Smgrp_EM_equivalence@{o so}) x)],
   t_alg_hom[from (`1 (@equivalence_counit _ _ _
                         Smgrp_EM_equivalence@{o so}) x)])
    = (@setoid_morphism_id@{o o o} (`1 x),
       @setoid_morphism_id@{o o o} (`1 x)) := eq_refl.

(* C65: and of its unit. *)
Example p470_c65_unit_component@{o so} (A : SmgrpSets@{o so}) :
  (sg_fun (to (`1 (@equivalence_unit _ _ _ Smgrp_EM_equivalence@{o so}) A)),
   sg_fun (from (`1 (@equivalence_unit _ _ _
                        Smgrp_EM_equivalence@{o so}) A)))
    = ((fun a : sg_ob A => a), (fun a : sg_ob A => a)) := eq_refl.

(* C66: at an object written as a pair, the uncurried multiplication comes
   back at each literal pair (a, b). *)
Example p470_c66_sg_rt_smu_at@{o so} (X : SetoidObject@{o o})
  (σ : @Semigroup Sets@{o so} Sets_Product_Monoidal@{so o} X) (a b : X) :
  @smu _ _ _ (`2 (fobj[EM_to_Smgrp@{o so} ◯ Sg_K@{o so}] (existT _ X σ)))
    (a, b) = @smu _ _ _ σ (a, b) := eq_refl.

(* R14 *)
Fail Example p470_r14_sg_rt_obj@{o so} (A : SmgrpSets@{o so}) :
  fobj[EM_to_Smgrp@{o so} ◯ Sg_K@{o so}] A = A := eq_refl.

(* R15 *)
Fail Example p470_r15_sg_rt_pair@{o so} (X : SetoidObject@{o o})
  (σ : @Semigroup Sets@{o so} Sets_Product_Monoidal@{so o} X) :
  fobj[EM_to_Smgrp@{o so} ◯ Sg_K@{o so}] (existT _ X σ) = existT _ X σ
  := eq_refl.

(* R16 *)
Fail Example p470_r16_sg_rt_smu@{o so} (X : SetoidObject@{o o})
  (σ : @Semigroup Sets@{o so} Sets_Product_Monoidal@{so o} X) :
  (fun p : prod X X =>
     @smu _ _ _ (`2 (fobj[EM_to_Smgrp@{o so} ◯ Sg_K@{o so}] (existT _ X σ)))
       p)
  = (fun p : prod X X => @smu _ _ _ σ p) := eq_refl.

(* R17 *)
Fail Example p470_r17_em_rt_obj@{o so} (x : WordAlg@{o so}) :
  fobj[Sg_K@{o so} ◯ EM_to_Smgrp@{o so}] x = x := eq_refl.

(* R18 *)
Fail Example p470_r18_em_rt_alg@{o so} (x : WordAlg@{o so}) :
  t_alg[`2 (fobj[Sg_K@{o so} ◯ EM_to_Smgrp@{o so}] x)] = t_alg[`2 x]
  := eq_refl.

(* R19 *)
Fail Example p470_r19_K_functor@{o so} :
  EM_to_Smgrp@{o so} ◯ Sg_K@{o so} = Id[SmgrpSets@{o so}] := eq_refl.

(* R20 *)
Fail Example p470_r20_K_functor_b@{o so} :
  Sg_K@{o so} ◯ EM_to_Smgrp@{o so} = Id[WordAlg@{o so}] := eq_refl.

(* C67: Theory/Equivalence.v's bridge [Equivalence_to_Cat_Iso], applied
   to the equivalence, has the identity as the component of its
   [iso_to_from]... *)
Example p470_c67_bridge_to_from@{o so +} (x : WordAlg@{o so}) :
  t_alg_hom[to (`1 (iso_to_from
                      (Equivalence_to_Cat_Iso Smgrp_EM_equivalence@{o so}))
                    x)]
    = @setoid_morphism_id@{o o o} (`1 x) := eq_refl.

(* R21 *)
Fail Example p470_r21_bridge_from_to@{o so +} (A : SmgrpSets@{o so}) :
  sg_fun (to (`1 (iso_from_to
                    (Equivalence_to_Cat_Iso Smgrp_EM_equivalence@{o so}))
                  A))
    = (fun a => a) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** The guard: every constant of the three targets *)

Check @Category.Theory.Algebra.Semigroup.Semigroup.
Check @Category.Theory.Algebra.Semigroup.smu.
Check @Category.Theory.Algebra.Semigroup.smu_assoc.
Check @Category.Theory.Algebra.Semigroup.SemigroupHom.
Check @Category.Theory.Algebra.Semigroup.shom_mu.
Check @Category.Theory.Algebra.Semigroup.SemigroupHom_id.
Check @Category.Theory.Algebra.Semigroup.SemigroupHom_comp.
Check @Category.Theory.Algebra.Semigroup.SemigroupHom_equiv.
Check @Category.Theory.Algebra.Semigroup.Smgrp_obligation_1.
Check @Category.Theory.Algebra.Semigroup.Smgrp_obligation_2.
Check @Category.Theory.Algebra.Semigroup.Smgrp_obligation_3.
Check @Category.Theory.Algebra.Semigroup.Smgrp_obligation_4.
Check @Category.Theory.Algebra.Semigroup.Smgrp_obligation_5.
Check @Category.Theory.Algebra.Semigroup.Smgrp_obligation_6.
Check @Category.Theory.Algebra.Semigroup.Smgrp.
Check @Category.Theory.Algebra.Semigroup.Smgrp_Forget_obligation_1.
Check @Category.Theory.Algebra.Semigroup.Smgrp_Forget_obligation_2.
Check @Category.Theory.Algebra.Semigroup.Smgrp_Forget_obligation_3.
Check @Category.Theory.Algebra.Semigroup.Smgrp_Forget.
Check @Category.Theory.Algebra.Semigroup.Smgrp_Forget_Faithful.
Check @Category.Theory.Algebra.Semigroup.Monoid_Semigroup.
Check @Category.Theory.Algebra.Semigroup.MonoidHom_SemigroupHom.
Check @Category.Theory.Algebra.Semigroup.Mon_Smgrp_obligation_1.
Check @Category.Theory.Algebra.Semigroup.Mon_Smgrp_obligation_2.
Check @Category.Theory.Algebra.Semigroup.Mon_Smgrp_obligation_3.
Check @Category.Theory.Algebra.Semigroup.Mon_Smgrp.
Check @Category.Theory.Algebra.Semigroup.Mon_Smgrp_Forget_obj.
Check @Category.Theory.Algebra.Semigroup.Mon_Smgrp_Forget_map.
Check @Category.Theory.Algebra.Semigroup.Build_Semigroup.
Check @Category.Theory.Algebra.Semigroup.Build_SemigroupHom.
Check @Category.Instance.Smgrp.SmgrpSets.
Check @Category.Instance.Smgrp.Sg_Forget.
Check @Category.Instance.Smgrp.sg_ob.
Check @Category.Instance.Smgrp.sg_mul.
Check @Category.Instance.Smgrp.sg_mul_respects.
Check @Category.Instance.Smgrp.sg_mul_assoc.
Check @Category.Instance.Smgrp.sg_fun.
Check @Category.Instance.Smgrp.sg_fun_respects.
Check @Category.Instance.Smgrp.sg_fun_mul.
Check @Category.Instance.Smgrp.mk_sg_obj.
Check @Category.Instance.Smgrp.mk_sg_hom.
Check @Category.Instance.Smgrp.Tup.
Check @Category.Instance.Smgrp.tup_eq.
Check @Category.Instance.Smgrp.tup_eq_refl.
Check @Category.Instance.Smgrp.tup_eq_sym.
Check @Category.Instance.Smgrp.tup_eq_trans.
Check @Category.Instance.Smgrp.PWord.
Check @Category.Instance.Smgrp.pword_eq.
Check @Category.Instance.Smgrp.pword_eq_Equivalence.
Check @Category.Instance.Smgrp.PWord_Setoid.
Check @Category.Instance.Smgrp.PWordObj.
Check @Category.Instance.Smgrp.letter.
Check @Category.Instance.Smgrp.tapp.
Check @Category.Instance.Smgrp.pwapp.
Check @Category.Instance.Smgrp.tapp_respects.
Check @Category.Instance.Smgrp.pwapp_respects.
Check @Category.Instance.Smgrp.tapp_assoc.
Check @Category.Instance.Smgrp.pwapp_assoc.
Check @Category.Instance.Smgrp.FreeSg.
Check @Category.Instance.Smgrp.FreeSg_carrier.
Check @Category.Instance.Smgrp.FreeSg_mul.
Check @Category.Instance.Smgrp.FreeSg_mul_literal.
Check @Category.Instance.Smgrp.tmap.
Check @Category.Instance.Smgrp.pwmap.
Check @Category.Instance.Smgrp.tmap_respects.
Check @Category.Instance.Smgrp.tmap_tapp.
Check @Category.Instance.Smgrp.tmap_id.
Check @Category.Instance.Smgrp.tmap_comp.
Check @Category.Instance.Smgrp.FreeSg_map.
Check @Category.Instance.Smgrp.Sg_Free.
Check @Category.Instance.Smgrp.sg_insert.
Check @Category.Instance.Smgrp.tfoldl.
Check @Category.Instance.Smgrp.tfold1.
Check @Category.Instance.Smgrp.pwfold.
Check @Category.Instance.Smgrp.tfoldl_respects.
Check @Category.Instance.Smgrp.tfold1_respects.
Check @Category.Instance.Smgrp.tfoldl_tapp.
Check @Category.Instance.Smgrp.tfold1_tapp.
Check @Category.Instance.Smgrp.tfoldl_mul.
Check @Category.Instance.Smgrp.pwfold_pwapp.
Check @Category.Instance.Smgrp.sg_extend.
Check @Category.Instance.Smgrp.sg_extend_unique.
Check @Category.Instance.Smgrp.sg_insert_universal.
Check @Category.Instance.Smgrp.sg_insert_universal_obj.
Check @Category.Instance.Smgrp.sg_insert_UA.
Check @Category.Instance.Smgrp.sg_insert_UA_obj.
Check @Category.Instance.Smgrp.sg_insert_UA_arrow.
Check @Category.Instance.Smgrp.Sg_adj_iso.
Check @Category.Instance.Smgrp.Sg_adj.
Check @Category.Instance.Smgrp.Sg_adj_unit.
Check @Category.Instance.Smgrp.Sg_adj_counit_letter.
Check @Category.Instance.Smgrp.Sg_adj_counit.
Check @Category.Instance.Smgrp.Sg_adj_counit_literal.
Check @Category.Instance.Smgrp.Word.WordF.
Check @Category.Instance.Smgrp.Word.WordMonad.
Check @Category.Instance.Smgrp.Word.pwconcat.
Check @Category.Instance.Smgrp.Word.W_obj.
Check @Category.Instance.Smgrp.Word.W_carrier.
Check @Category.Instance.Smgrp.Word.W_map.
Check @Category.Instance.Smgrp.Word.W_ret.
Check @Category.Instance.Smgrp.Word.W_ret_fun.
Check @Category.Instance.Smgrp.Word.W_join_counit.
Check @Category.Instance.Smgrp.Word.W_join_fun.
Check @Category.Instance.Smgrp.Word.W_join_literal.
Check @Category.Instance.Smgrp.Word.tfoldl_acc_respects.
Check @Category.Instance.Smgrp.Word.tfoldl_hom.
Check @Category.Instance.Smgrp.Word.tfold1_hom.
Check @Category.Instance.Smgrp.Word.tfoldl_tmap.
Check @Category.Instance.Smgrp.Word.tfold1_tmap.
Check @Category.Instance.Smgrp.Word.tfoldl_letters.
Check @Category.Instance.Smgrp.Word.pwconcat_hom.
Check @Category.Instance.Smgrp.Word.pwconcat_map.
Check @Category.Instance.Smgrp.Word.WordMonad_direct.
Check @Category.Instance.Smgrp.Word.WordMonad_direct_ret.
Check @Category.Instance.Smgrp.Word.WordMonad_direct_join.
Check @Category.Instance.Smgrp.Word.WordAlg.
Check @Category.Instance.Smgrp.Word.NAry.
Check @Category.Instance.Smgrp.Word.nu.
Check @Category.Instance.Smgrp.Word.nu_respects.
Check @Category.Instance.Smgrp.Word.nu_sharp.
Check @Category.Instance.Smgrp.Word.nu_unit.
Check @Category.Instance.Smgrp.Word.nu_assoc.
Check @Category.Instance.Smgrp.Word.alg_NAry.
Check @Category.Instance.Smgrp.Word.alg_NAry_at.
Check @Category.Instance.Smgrp.Word.alg_NAry_unit.
Check @Category.Instance.Smgrp.Word.alg_NAry_assoc.
Check @Category.Instance.Smgrp.Word.NAry_alg.
Check @Category.Instance.Smgrp.Word.NAry_round_trip.
Check @Category.Instance.Smgrp.Word.alg_round_trip.
Check @Category.Instance.Smgrp.Word.NAry_hom.
Check @Category.Instance.Smgrp.Word.alg_hom_NAry_hom.
Check @Category.Instance.Smgrp.Word.NAry_hom_alg_hom.
Check @Category.Instance.Smgrp.Word.WSystem.
Check @Category.Instance.Smgrp.Word.ws_set.
Check @Category.Instance.Smgrp.Word.ws_nu.
Check @Category.Instance.Smgrp.Word.ws_unit.
Check @Category.Instance.Smgrp.Word.ws_assoc.
Check @Category.Instance.Smgrp.Word.WSystemHom.
Check @Category.Instance.Smgrp.Word.WSystemHom_Setoid.
Check @Category.Instance.Smgrp.Word.WSystem_id.
Check @Category.Instance.Smgrp.Word.WSystem_compose.
Check @Category.Instance.Smgrp.Word.WSys.
Check @Category.Instance.Smgrp.Word.WSys_to_EM.
Check @Category.Instance.Smgrp.Word.EM_to_WSys.
Check @Category.Instance.Smgrp.Word.WSys_EM_counit_iso.
Check @Category.Instance.Smgrp.Word.WSys_EM_unit_iso.
Check @Category.Instance.Smgrp.Word.WSys_EM_iso.
Check @Category.Instance.Smgrp.Word.nu2.
Check @Category.Instance.Smgrp.Word.cor_conditions.
Check @Category.Instance.Smgrp.Word.nu2_respects.
Check @Category.Instance.Smgrp.Word.cor_forward.
Check @Category.Instance.Smgrp.Word.nu2_sg.
Check @Category.Instance.Smgrp.Word.cor_iterate.
Check @Category.Instance.Smgrp.Word.cor_backward.
Check @Category.Instance.Smgrp.Word.NAry_corollary.
Check @Category.Instance.Smgrp.Word.Sg_K.
Check @Category.Instance.Smgrp.Word.EM_sg.
Check @Category.Instance.Smgrp.Word.EM_sg_map.
Check @Category.Instance.Smgrp.Word.EM_to_Smgrp.
Check @Category.Instance.Smgrp.Word.Smgrp_EM_counit_iso.
Check @Category.Instance.Smgrp.Word.Smgrp_EM_unit_iso.
Check @Category.Instance.Smgrp.Word.Smgrp_EM_equivalence.
Check @Category.Instance.Smgrp.Word.Sg_Forget_Monadic.
Check @Category.Instance.Smgrp.Word.Smgrp_EM_iso.
Check @Category.Instance.Smgrp.Word.Smgrp_EM_iso_to.
Check @Category.Instance.Smgrp.Word.Smgrp_EM_iso_from.
Check @Category.Instance.Smgrp.Word.WSys_EM_iso_to.
Check @Category.Instance.Smgrp.Word.WSys_EM_iso_from.
Check @Category.Instance.Smgrp.Word.Sg_K_carrier.
Check @Category.Instance.Smgrp.Word.Sg_K_alg.
Check @Category.Instance.Smgrp.Word.Sg_K_alg_fun.
Check @Category.Instance.Smgrp.Word.Sg_K_nu1.
Check @Category.Instance.Smgrp.Word.Sg_K_nu2.
Check @Category.Instance.Smgrp.Word.Sg_K_nu_succ.
Check @Category.Instance.Smgrp.Word.Sg_K_map.
Check @Category.Instance.Smgrp.Word.Sg_K_system_nu.
Check @Category.Instance.Smgrp.Word.Sg_K_system_nu2.
Check @Category.Instance.Smgrp.Word.WSys_to_EM_alg.
Check @Category.Instance.Smgrp.Word.EM_to_WSys_nu.
Check @Category.Instance.Smgrp.Word.Smgrp_EM_rt_carrier.
Check @Category.Instance.Smgrp.Word.Smgrp_EM_rt_mul.
Check @Category.Instance.Smgrp.Word.Smgrp_EM_rt_hom.
Check @Category.Instance.Smgrp.Word.EM_Smgrp_rt_carrier.
Check @Category.Instance.Smgrp.Word.EM_Smgrp_rt_alg_hom.
Check @Category.Instance.Smgrp.Word.WSys_rt_set.
Check @Category.Instance.Smgrp.Word.WSys_rt_nu.
Check @Category.Instance.Smgrp.Word.WSys_rt_unit.
Check @Category.Instance.Smgrp.Word.WSys_rt_hom.
Check @Category.Instance.Smgrp.Word.EM_WSys_rt_carrier.
Check @Category.Instance.Smgrp.Word.EM_WSys_rt_alg_hom.
Check @Category.Instance.Smgrp.Word.Smgrp_EM_iso_to_from_component.
Check @Category.Instance.Smgrp.Word.Smgrp_EM_iso_from_to_component.
Check @Category.Instance.Smgrp.Word.Smgrp_EM_counit_component.
Check @Category.Instance.Smgrp.Word.Smgrp_EM_unit_component.
Check @Category.Instance.Smgrp.Word.WSys_EM_iso_to_from_component.
Check @Category.Instance.Smgrp.Word.WSys_EM_iso_from_to_component.
Check @Category.Instance.Smgrp.Word.Build_NAry.
Check @Category.Instance.Smgrp.Word.Build_WSystem.
