(** * Probe for the power-set monad and complete semilattices (issue #466)

    Pins the measured boundaries of the five files #466 adds for Mac Lane
    §VI.2, Exercise 1, "Complete semi-lattices (E. Manes; thesis)", book
    p. 142 (PDF p. 151), catalog item maclane:VI.2:ex1, with the appended
    items from Awodey, "Category Theory", Example 10.5, printed p. 271, and
    Exercise 10.6.5, printed p. 291, and from Riehl, "Category Theory in
    Context", 2nd ed., Example 5.1.5(i), printed p. 185.  The files are
    Instance/Sets/Powerset/Monad.v (part (a): the covariant power-set monad
    on #227's endofunctor), Instance/SupLat.v (parts (b), (c) and (d): the
    complete semilattices and their identification with the algebras),
    Instance/SupLat/Free.v (the free complete semilattice, the monad of that
    adjunction against the monad of part (a), and the monadicity of the
    forgetful functor), Instance/SupLat/Examples.v (P X, Prop = P 1 and the
    two-point theorem) and Instance/Sets/Powerset/Monad/Riehl.v (Riehl's
    route to the naturality of the union).  The first file's header cites
    the refutations M1-M7 here, the second's N1-N10 with N4b, N5b and
    N8b, the third's F1-F6 with F2b, F5b and F6b, and the fourth's E1,
    E1b, E2, E3 and E3b; the fifth states nothing that is refused.  The
    positive controls restate the files' claims independently.

    THE IMPORT LIST, generated by a script over the [Require] lines.
    Target by target in dependency order: Instance/Sets/Powerset/Monad.v's
    seven [Require] lines in its own order, and that target; then the six
    lines Instance/SupLat.v adds, and that target; the two lines
    Instance/SupLat/Free.v adds (Theory/Adjunction.v and
    Monad/Comparison.v), and that target; the one line
    Instance/SupLat/Examples.v adds (Monad/Eilenberg/Moore/Adjunction.v),
    and that target; the two lines Instance/Sets/Powerset/Monad/Riehl.v
    adds (Instance/Proset/Limit.v and Instance/Powerset.v), and that
    target.  Twenty-three lines, all naming [Category] modules.  Under this
    list [Print Libraries] in a scratch file loads one hundred [Category]
    modules, the five targets among them, which is exactly the union of
    the five targets' dependency closures (compared by script with the
    closure of their [Require] lines).  A shorter import list is what
    makes a probe pass for no reason.

    DISCIPLINE.  The instrument was checked both ways: a false statement
    about the targets is refused for that reason (the instrument, below),
    and each of the forty-eight definitions and examples of this file that
    is not a refutation (forty-four controls and the four helpers
    [p466_L_TAlgebra], [p466_TAlgebra_L], [p466_sup_respects] and
    [p466_varA_alg]), wrapped in the refutation keyword in a copy of this
    WHOLE file, stops the build at that command with the message Rocq
    prints for a refutation whose command succeeds (forty-eight of
    forty-eight, by a script over the copies, which compares the File line
    of the error with the command's extent); so does the helper record
    [p466_SupLatObjectL], wrapped the same way.  Every negative is a
    [Definition] or an [Example], never a [Check], so that an open evar
    cannot satisfy it.  Each of the thirty-five refutation lines was
    stripped of its refutation keyword in a copy of this WHOLE file, one at
    a time, compiled, and its error read; each copy stops inside the
    stripped command (by the File line of its error, compared by the same
    script with the command's extent).  The kind recorded is the kind of
    that error.  Quotations are Rocq 9.1.1's under this file's import list,
    with the error's environment block left out; Rocq prints the "cannot
    unify" parenthetical with the short names in scope.  The five targets
    and this file also compile on Coq 8.19.2 and 8.20.1, with no warning
    from any of them, overlaid on copies of the dependency closure whose
    one hundred sources are this tree's byte for byte (compared by [cmp]);
    this file prints the same thirteen closure readbacks there.  Each of
    the thirty-five stripped copies is refused there inside the stripped
    command, at the File line of the Rocq 9.1.1 refusal, and with the Rocq
    9.1.1 error, environment block included (compared by script), with one
    exception, M2: Coq 8.19.2 prints its type mismatch without the
    parenthetical that names the universe inconsistency.  Every wrapped
    definition, example and record reports there that its command
    succeeded (forty-nine of forty-nine on each version).

    KINDS.  Thirty-five refutations, counted as the lines that open with
    the refutation keyword: CONVERSION, [eq_refl] refused with a "cannot
    unify" parenthetical (the instrument, M1, M3-M7, N1-N5, N4b, N5b, N7,
    N8, N8b, N9, F1-F3, F2b, F5, F5b, F6, F6b, E1, E1b, E2, E3, E3b:
    thirty-one); TYPING, a statement that is itself ill-typed (N6, F4:
    two); and UNIVERSE, a type mismatch whose parenthetical, where one is
    printed, is a universe inconsistency (M2, and N10, a sort refusal:
    two).  Each CONVERSION refusal but
    the instrument also has a CAUSE: STRUCTURAL (the two sides reduce to
    different terms, or to stuck projections of the variable data, and no
    flip of the tree changes that: all but F1) and STDLIB OPACITY (the
    residue is an opaque constant of the standard library, which no flip of
    the tree reaches: F1, of the kind of Test/ProbeGroupAction464.v's N3).
    The flip: a copy of the one-hundred-module closure with every [Qed]
    turned into [Defined], [Transparent Obligations] set and [abstract]
    made [transparent_abstract], with exceptions in five files.  Three
    [Defined]s are refused and those [Qed]s are kept: Instance/Sets.v's
    [setoid_morphism_compose_respects] ("Universe … is unbound", as #466's
    builders found) and Riehl.v's [join_natural_via_image] and
    [join_natural_via_LAPC] ("Universes … are unbound"), whose proofs'
    universes would enter the constants.  Structure/Cartesian/Closed.v
    keeps its [Qed]s, since a rewrite in it finds no subterm once more is
    transparent, and adds [Unset Transparent Obligations.]; and
    Structure/Limit/Preservation.v's [preserves_colimit] has its two
    bullets written as [all:] steps, since the added transparency closes a
    goal; these two are #465's accommodations, copied from its flip.
    Construction/Elements.v keeps two [abstract cat] steps as they are.
    [About] there reports
    Theory/Functor.v's [Compose_obligation_1],
    Monad/Eilenberg/Moore.v's [EilenbergMoore_obligation_1], Instance/Sets/
    Powerset.v's [Powerset_Prop_map_id] and the targets' [talg_antisym],
    [Powerset_union_natural] and [SL_induced_join_equiv] transparent, all
    opaque in this tree, and Corelib's [subrelation_id_proper] and
    [subrelation_refl] opaque in both.  [Print Opaque Dependencies] on the
    eighteen compared constructions ([Powerset_union_pred],
    [Powerset_union], [Powerset_Monad], [Powerset_Prop_pair], [SupLat],
    [SupLat_TAlgebra], [TAlgebra_SupLat], [EM_to_SupLat], [SupLat_to_EM],
    [FreeSL], [SL_Free], [SL_Forget], [SL_adj], [SL_induced],
    [EM_induced_to_SupLat], [Prop_to_P1], [P1_to_Prop] and the comparison
    functor of [SL_adj]) lists seventy-six constants in this tree and
    sixteen in the flip: fifteen of Corelib and the one [Qed] kept in
    Instance/Sets.v, none of Riehl.v, Structure/Cartesian/Closed.v or
    Construction/Elements.v.  This whole file compiles in the flip, and
    each of the thirty-five refutation lines, stripped there, stops inside
    the stripped command
    with the error of the unchanged tree, environment block included (by
    script).  Two further copies change no [Qed] and only
    Instance/Sets.v's two properness fields.  In the first, both are
    written as terms, [setoid_morphism_id]'s as fun _ _ H => H and
    [setoid_morphism_compose]'s as
    fun a b H => proper_morphism g _ _ (proper_morphism f a b H): there
    this whole file with F1's refutation keyword removed compiles, so F1's
    statement holds, and each of the other thirty-four, stripped there,
    stops inside the stripped command with the error of the unchanged tree.
    In the second, the compose field alone is so written, and F1 is still
    refused, inside its command.  #466's builders and their reviewers made
    the same measurements on the drafts of the files, with the same
    results.

    LABELS.  The first builder's draft refutations keep their labels: the
    instrument, M1, M2, N1-N10, N4b, N5b and N8b (N1-N6 are the first
    scout's measurements, N7 and N8 the second scout's variant-L controls,
    N9 and N10 the first scout's variant A and Type-valued order).  M3-M7
    are the first review's R1-R5, restated by the fold, with the controls
    [p466_assoc_ctl], [p466_unit_image_ctl], [p466_unit_singleton_ctl] and
    [p466_ret_natural_ctl].  The second builder's draft refutations keep
    theirs: F1-F4 with F2b (the induced monad), F5, F5b, F6 and F6b (the
    comparison round trips) and E1, E1b and E2 (the examples).  The
    controls [p466_ind_functor_component], [p466_chain_carrier] and
    [p466_riehl_lapc] are the fold's, and E3 and E3b, with the control
    [p466_freealg_carrier], the second verification's measurement, pinned
    by the fold's second pass.  The labels are not constants: each
    refutation carries its own in a comment on the line above it, the
    instrument's reading "The instrument".

    ** The instrument

    Control: the pair {x, y} is commutative up to ≈
    ([p466_instrument_ctl]).
    The instrument (CONVERSION).  The same at [eq_refl]:
      (cannot unify "Powerset_Prop_pair x y" and "Powerset_Prop_pair y x")

    ** Instance/Sets/Powerset/Monad.v: the laws

    Controls: η is #227's singleton transformation and μ the union, at
    [eq_refl] ([p466_ret], [p466_join]); each law and naturality square
    below at ≈, by the file's lemma or #227's field ([p466_assoc_ctl],
    [p466_unit_image_ctl], [p466_unit_singleton_ctl],
    [p466_ret_natural_ctl], [p466_join_natural_ctl]).
    M3 (CONVERSION, STRUCTURAL).  Associativity, μ ∘ Pμ against μ ∘ μP:
      (cannot unify "Powerset_union_pred (Powerset_Prop_image Powerset_union
      SSS)" and "Powerset_union_pred (Powerset_union_pred SSS)")
    M4 (CONVERSION, STRUCTURAL).  μ ∘ Pη against the identity:
      (cannot unify "Powerset_union_pred (Powerset_Prop_image
      Powerset_Prop_singleton_map S)" and "S")
    M5 (CONVERSION, STRUCTURAL).  μ ∘ ηP against the identity:
      (cannot unify "Powerset_union_pred (Powerset_Prop_singleton_pred S)" and
      "S")
    M6 (CONVERSION, STRUCTURAL).  The naturality of η at one point:
      (cannot unify "ret[_] (f x)" and "fmap[Powerset_Prop] f (ret[_] x)")
    M1 (CONVERSION, STRUCTURAL).  The naturality of μ at one set of
    subsets:
      (cannot unify "join[_] (fmap[Powerset_Prop] (fmap[Powerset_Prop] f) SS)"
      and "fmap[Powerset_Prop] f (join[_] SS)")
    M7 (CONVERSION, STRUCTURAL).  The same as a function of the point:
      (cannot unify "λ y : Y, join[_] (fmap[Powerset_Prop] (fmap[Powerset_Prop]
      f) SS) y" and "λ y : Y, fmap[Powerset_Prop] f (join[_] SS) y")

    ** Instance/Sets/Powerset/Monad.v: the proof-relevant carrier

    Control: [@Monad Sets Powerset_Prop] is formable
    ([p466_prop_statement]).
    M2 (UNIVERSE).  The same over #227's proof-relevant [Powerset]:
      The term "Powerset" has type "Sets@{o so} ⟶ Sets@{so sso}" while it
      is expected to have type "Sets@{o so} ⟶ Sets@{o so}" (universe
      inconsistency: Cannot enforce so = o because o < so).
    Coq 8.19.2 prints the same without the parenthetical.

    ** Instance/SupLat.v: semilattice to algebra to semilattice

    Controls: the carrier and the sup at [eq_refl], the order logically,
    and both fields of the morphism round trip at [eq_refl]
    ([p466_rt_set], [p466_rt_sup], [p466_rt_le_iff], [p466_rt_hom_map],
    [p466_rt_hom_sup]).
    N1 (CONVERSION, STRUCTURAL).  The whole semilattice:
      (cannot unify "fobj[EM_to_SupLat ◯ SupLat_to_EM] A" and "A")
    N2 (CONVERSION, STRUCTURAL).  Its order field, rebuilt as a squash:
      (cannot unify "sl_le (fobj[EM_to_SupLat ◯ SupLat_to_EM] A)" and "sl_le A")
    N5b (CONVERSION, STRUCTURAL).  The composite as the identity functor:
      (cannot unify "EM_to_SupLat ◯ SupLat_to_EM" and "Id[SupLat]")
    N6 (TYPING).  The morphism round trip, whose two ends differ:
      The term "f" has type "SupLatHom A B" while it is expected to have
      type "fobj[EM_to_SupLat ◯ SupLat_to_EM] A ~{ SupLat }~>
      fobj[EM_to_SupLat ◯ SupLat_to_EM] B".

    ** Instance/SupLat.v: algebra to semilattice to algebra

    Controls: the carrier and the structure map at a variable object, the
    structure map at a named algebra, and the morphism maps, at [eq_refl]
    ([p466_rt2_carrier], [p466_rt2_alg], [p466_alg_rt_data],
    [p466_rt2_hom]).
    N3 (CONVERSION, STRUCTURAL).  The whole object, a [sigT] pair:
      (cannot unify "fobj[SupLat_to_EM ◯ EM_to_SupLat] x" and "x")
    N4, N4b (CONVERSION, STRUCTURAL).  The proof fields [t_id] and
    [t_action] of the rebuilt algebra, one each, with the text
      (cannot unify "@<field> _ _ _ _ (@projT2 obj[Sets] (λ a : obj[Sets],
      @TAlgebra Sets Powerset_Prop Powerset_Monad a) (fobj[SupLat_to_EM ◯
      EM_to_SupLat] x))" and "@<field> _ _ _ _ `2 (x)")
    N5 (CONVERSION, STRUCTURAL).  The composite as the identity functor:
      (cannot unify "SupLat_to_EM ◯ EM_to_SupLat" and "Id[EilenbergMoore
      Powerset_Prop]")
    N7 (CONVERSION, STRUCTURAL).  The algebra round trip at a named α:
      (cannot unify "SupLat_TAlgebra (TAlgebra_SupLat α)" and "α")

    ** Variant L, measured and not adopted

    Controls: with the two algebra laws of the sup as redundant fields
    ([p466_SupLatObjectL]), the algebra round trip holds at [eq_refl] on a
    whole algebra and on an object written (X; α), and the semilattice
    round trip keeps the carrier ([p466_L_alg_rt], [p466_L_obj_rt],
    [p466_L_set_rt]).
    N8 (CONVERSION, STRUCTURAL).  At a variable object, [sigT] again:
      (cannot unify "(`1 (x); p466_L_TAlgebra (p466_TAlgebra_L `2 (x)))" and
      "x")
    N8b (CONVERSION, STRUCTURAL).  Its semilattice round trip's order:
      (cannot unify "p466_sll_le (p466_TAlgebra_L (p466_L_TAlgebra A))" and
      "p466_sll_le A")

    ** Variant A: the sup as a bare function

    Control: the rebuilt map and the sup agree as functions
    ([p466_varA_fun]).
    N9 (CONVERSION, STRUCTURAL).  As setoid maps:
      (cannot unify "p466_varA_alg A" and "sl_sup A")

    ** A Type-valued order

    Control: with the Prop-valued order, sup {x} ≤ x follows from a
    squashed membership ([p466_proporder_unit]).
    N10 (UNIVERSE, a sort refusal).  With an order valued in [Type@{o}]:
      The term "le z x" has type "Type" while it is expected to have type
      "Prop" (universe inconsistency: Cannot enforce o <= Prop).

    ** Instance/SupLat/Free.v: the monad of the adjunction

    Controls: the object and arrow maps of the composite and the unit as
    functions, the unit as the identity composed with #227's singleton
    map, and the join as ⋃ ∘ P id, at [eq_refl]; the unit, the join and
    the functor at ≈, the last with the identity isomorphism as its
    component at [eq_refl] ([p466_ind_obj_fun], [p466_ind_map_fun],
    [p466_ind_ret_fun], [p466_ind_ret_compose], [p466_ind_join_fun_ctl],
    [p466_ind_ret_equiv], [p466_ind_join_equiv], [p466_ind_functor_equiv],
    [p466_ind_functor_component]).
    F1 (CONVERSION, STDLIB OPACITY).  The whole unit, which holds in the
    copy with Instance/Sets.v's two properness fields written as terms:
      (cannot unify "@ret _ _ SL_induced X" and "@ret _ _ Powerset_Monad X")
    F2 (CONVERSION, STRUCTURAL).  The join as a function:
      (cannot unify "fun SS : carrier (@fobj _ _ (@Compose Sets SupLat Sets
      SL_Forget SL_Free) (@fobj _ _ (@Compose Sets SupLat Sets SL_Forget
      SL_Free) X)) => @morphism _ _ _ _ (@join _ _ SL_induced X) SS" and "fun SS
      : carrier (@fobj _ _ (@Compose Sets SupLat Sets SL_Forget SL_Free) (@fobj
      _ _ (@Compose Sets SupLat Sets SL_Forget SL_Free) X)) => @morphism _ _ _ _
      (@join _ _ Powerset_Monad X) SS")
    F2b (CONVERSION, STRUCTURAL).  The join at one set of subsets:
      (cannot unify "@morphism _ _ _ _ (@join _ _ SL_induced X) SS" and
      "@morphism _ _ _ _ (@join _ _ Powerset_Monad X) SS")
    F3 (CONVERSION, STRUCTURAL).  The composite functor as [Powerset_Prop]:
      (cannot unify "SL_Forget ◯ SL_Free" and "Powerset_Prop")
    F4 (TYPING).  [Powerset_Monad] as a monad on the composite:
      The term "Powerset_Monad" has type "Monad Powerset_Prop" while it is
      expected to have type "Monad (SL_Forget ◯ SL_Free)".

    ** Instance/SupLat/Free.v: the comparison round trips

    Controls: the identity components of the comparison at a variable
    object, and the carrier of the semilattice round trip, at [eq_refl]
    ([p466_cmp_counit_component], [p466_cmp_unit_component],
    [p466_cmp_carrier]).
    F5, F5b (CONVERSION, STRUCTURAL).  The two composites as the identity
    functors:
      (cannot unify "EM_Comparison SL_adj ◯ EM_induced_to_SupLat" and
      "Id[EilenbergMoore (SL_Forget ◯ SL_Free)]")
      (cannot unify "EM_induced_to_SupLat ◯ EM_Comparison SL_adj" and
      "Id[SupLat]")
    F6, F6b (CONVERSION, STRUCTURAL).  The two whole-object round trips:
      (cannot unify "fobj[EM_induced_to_SupLat ◯ EM_Comparison SL_adj] A" and
      "A")
      (cannot unify "fobj[EM_Comparison SL_adj ◯ EM_induced_to_SupLat] x" and
      "x")

    ** Instance/SupLat/Examples.v

    Controls: (b) at the free algebra has the carrier and the sup of
    [FreeSL X] at [eq_refl] and its order logically, by Instance/SupLat.v's
    [sl_talg_le_iff] at [FreeSL X]; (c) at P X has the free algebra's
    carrier at [eq_refl], its structure map being Instance/SupLat/
    Examples.v's [FreeSL_alg]; the P 1 round trip at the point ttt and the
    Prop round trip at [eq_refl]; the two-point theorem at its stated type;
    the chain's carrier is Instance/Sets.v's [bool_setoid_object]
    ([p466_freesl_em_set], [p466_freesl_em_sup], [p466_freesl_em_le_iff],
    [p466_freealg_carrier], [p466_prop_p1_rt_at], [p466_p1_prop_rt],
    [p466_two_points], [p466_chain_carrier]).
    E1 (CONVERSION, STRUCTURAL).  (b) at the free algebra as [FreeSL X]:
      (cannot unify "fobj[EM_to_SupLat] (fobj[EM_Free Powerset_Prop] X)" and
      "FreeSL X")
    E1b (CONVERSION, STRUCTURAL).  Its order field:
      (cannot unify "sl_le (fobj[EM_to_SupLat] (fobj[EM_Free Powerset_Prop] X))"
      and "sl_le (FreeSL X)")
    E3 (CONVERSION, STRUCTURAL).  (c) at P X against the free algebra, as
    a whole algebra, whose proof fields [t_id] and [t_action] differ (each
    refused at [eq_refl] in a scratch copy of this whole file):
      (cannot unify "projT2 (fobj[SupLat_to_EM] (FreeSL X))" and
      "projT2 (fobj[EM_Free Powerset_Prop] X)")
    E3b (CONVERSION, STRUCTURAL).  The same as a whole object of the
    Eilenberg–Moore category:
      (cannot unify "fobj[SupLat_to_EM] (FreeSL X)" and
      "fobj[EM_Free Powerset_Prop] X")
    E2 (CONVERSION, STRUCTURAL).  The P 1 round trip on a whole subset:
      (cannot unify "slh_map Prop_to_P1 (slh_map P1_to_Prop T)" and "T")

    ** Instance/Sets/Powerset/Monad/Riehl.v

    Control: the route through the direct image as a left adjoint proves
    the statement of [Powerset_Monad]'s naturality field as stated
    ([p466_riehl_lapc]).  Nothing in the file is refused.

    ** Closure: readbacks, not refutations

    [Print Assumptions] of [Powerset_Monad], [SupLat_EM_iso],
    [SupLat_EM_equivalence], [talg_PropEquiv], [sl_PropEquiv], [SL_adj],
    [SL_Forget_Monadic], [SL_induced], [suplat_two_points_WLEM],
    [bool_SupLat_WLEM], [bool_SupLat], [Prop_P1_iso] and
    [join_natural_routes_agree], near the end of this file, each print
    "Closed under the global context".  A [Print Assumptions] cannot
    refuse, so these lines are readbacks and guard nothing; the Makefile's
    print-assumptions gate is where closure is kept, and it names all one
    hundred and fifty-two constants of the five targets.

    NOT PINNED HERE.  (a) [About] readbacks as such: the headers' universe
    censuses and their attributions to first carriers and caps, the
    measured cost of a [relation]-typed order (Instance/SupLat.v) and of
    [IsLUB] at level o (Riehl.v).  (b) The flips and copies above, the
    opaque-dependency census and the field and normal-form readings behind
    the CAUSEs: made in copies of the dependency closure and in scratch
    files.  (c) The closure of the targets under [Print Assumptions]: a
    measurement of the build rather than of a command.  (d) The absences
    the headers record (no identity of categories on the nose, no Kleisli
    category of the monad, no morphisms of monads, Beck's route to
    monadicity not taken, no meets, no chain beyond 0 < 1): an absence has
    no command; N1, N3, N5, N5b, F5, F5b, F6 and F6b pin the round trips
    that an identity of categories would need.  (e) The dependency-closure
    counts the headers give, measured by script over the [Require] lines.
    (f) The readings of the books, from their page images.

    The guard block at the end names the one hundred and fifty-two
    constants of the five targets, so that a rename breaks this file:
    eighteen of Instance/Sets/Powerset/Monad.v, seventy-three of
    Instance/SupLat.v, twenty-six of Instance/SupLat/Free.v, twenty-nine of
    Instance/SupLat/Examples.v and six of Instance/Sets/Powerset/Monad/
    Riehl.v.  They are exactly the entries [Print Module] gives for each;
    the .glob files' [def], [prf], [proj] and [rec] entries agree, with
    Instance/SupLat.v's two record constructors [Build_SupLatObject] and
    [Build_SupLatHom] added, and no target has a [Program] obligation.
    Each is written fully qualified and with [@], so that no short name in
    scope can stand in for it. *)

Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Natural.Transformation.
Require Import Category.Theory.Monad.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Sets.Powerset.
Require Import Category.Instance.Sets.Powerset.Monad.
Require Import Category.Lib.Setoid.Propositional.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Equivalence.
Require Import Category.Monad.Algebra.
Require Import Category.Monad.Eilenberg.Moore.
Require Import Category.Instance.Cat.
Require Import Category.Instance.SupLat.
Require Import Category.Theory.Adjunction.
Require Import Category.Monad.Comparison.
Require Import Category.Instance.SupLat.Free.
Require Import Category.Monad.Eilenberg.Moore.Adjunction.
Require Import Category.Instance.SupLat.Examples.
Require Import Category.Instance.Proset.Limit.
Require Import Category.Instance.Powerset.
Require Import Category.Instance.Sets.Powerset.Monad.Riehl.

Generalizable All Variables.

(* ------------------------------------------------------------------------ *)
(** ** The instrument *)

(* Control: the pair is commutative up to ≈. *)
Example p466_instrument_ctl@{o} {X : SetoidObject@{o o}} (x y : carrier X) :
  Powerset_Prop_pair@{o} x y ≈ Powerset_Prop_pair@{o} y x :=
  Powerset_Prop_pair_comm@{o} x y.

(* The instrument *)
Fail Example p466_instrument@{o} {X : SetoidObject@{o o}} (x y : carrier X) :
  Powerset_Prop_pair@{o} x y = Powerset_Prop_pair@{o} y x := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Sets/Powerset/Monad.v: the data *)

(* Controls: η is #227's singleton transformation and μ is the union. *)
Example p466_ret@{o so} (X : SetoidObject@{o o}) :
  @ret _ _ Powerset_Monad@{o so} X
    = transform[Powerset_Prop_Singleton@{o so}] X := eq_refl.

Example p466_join@{o so} (X : SetoidObject@{o o}) :
  @join _ _ Powerset_Monad@{o so} X = @Powerset_union@{o} X := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Sets/Powerset/Monad.v: the laws, at ≈ and not at eq_refl *)

(* Control: associativity at ≈. *)
Example p466_assoc_ctl@{o} {X : SetoidObject@{o o}}
  (SSS : carrier (Powerset_Prop_obj@{o}
                    (Powerset_Prop_obj@{o} (Powerset_Prop_obj@{o} X)))) :
  Powerset_union_pred@{o} (Powerset_Prop_image@{o} Powerset_union@{o} SSS)
    ≈ Powerset_union_pred@{o} (Powerset_union_pred@{o} SSS) :=
  Powerset_union_assoc@{o} SSS.

(* M3 *)
Fail Example p466_assoc_eq@{o} {X : SetoidObject@{o o}}
  (SSS : carrier (Powerset_Prop_obj@{o}
                    (Powerset_Prop_obj@{o} (Powerset_Prop_obj@{o} X)))) :
  Powerset_union_pred@{o} (Powerset_Prop_image@{o} Powerset_union@{o} SSS)
    = Powerset_union_pred@{o} (Powerset_union_pred@{o} SSS) := eq_refl.

(* Control: μ ∘ Pη ≈ id. *)
Example p466_unit_image_ctl@{o} {X : SetoidObject@{o o}}
  (S : carrier (Powerset_Prop_obj@{o} X)) :
  Powerset_union_pred@{o}
    (Powerset_Prop_image@{o} (@Powerset_Prop_singleton_map@{o} X) S) ≈ S :=
  Powerset_union_image_singleton@{o} S.

(* M4 *)
Fail Example p466_unit_image_eq@{o} {X : SetoidObject@{o o}}
  (S : carrier (Powerset_Prop_obj@{o} X)) :
  Powerset_union_pred@{o}
    (Powerset_Prop_image@{o} (@Powerset_Prop_singleton_map@{o} X) S) = S
  := eq_refl.

(* Control: μ ∘ ηP ≈ id. *)
Example p466_unit_singleton_ctl@{o} {X : SetoidObject@{o o}}
  (S : carrier (Powerset_Prop_obj@{o} X)) :
  Powerset_union_pred@{o} (Powerset_Prop_singleton_pred@{o} S) ≈ S :=
  Powerset_union_singleton@{o} S.

(* M5 *)
Fail Example p466_unit_singleton_eq@{o} {X : SetoidObject@{o o}}
  (S : carrier (Powerset_Prop_obj@{o} X)) :
  Powerset_union_pred@{o} (Powerset_Prop_singleton_pred@{o} S) = S
  := eq_refl.

(* Control: the naturality of η at a point, at ≈ (#227's field). *)
Example p466_ret_natural_ctl@{o so} {X Y : SetoidObject@{o o}}
  (f : X ~{Sets@{o so}}~> Y) (x : carrier X) :
  @ret _ _ Powerset_Monad@{o so} Y (f x)
    ≈ fmap[Powerset_Prop@{o so}] f (@ret _ _ Powerset_Monad@{o so} X x) :=
  @naturality_sym _ _ _ _ Powerset_Prop_Singleton@{o so} X Y f x.

(* M6 *)
Fail Example p466_ret_natural_eq@{o so} {X Y : SetoidObject@{o o}}
  (f : X ~{Sets@{o so}}~> Y) (x : carrier X) :
  @ret _ _ Powerset_Monad@{o so} Y (f x)
    = fmap[Powerset_Prop@{o so}] f (@ret _ _ Powerset_Monad@{o so} X x)
  := eq_refl.

(* Control: the naturality of μ at ≈. *)
Example p466_join_natural_ctl@{o so} {X Y : SetoidObject@{o o}}
  (f : X ~{Sets@{o so}}~> Y)
  (SS : carrier (Powerset_Prop_obj@{o} (Powerset_Prop_obj@{o} X))) :
  @join _ _ Powerset_Monad@{o so} Y
      (fmap[Powerset_Prop@{o so}] (fmap[Powerset_Prop@{o so}] f) SS)
    ≈ fmap[Powerset_Prop@{o so}] f (@join _ _ Powerset_Monad@{o so} X SS)
  := Powerset_union_natural@{o} f SS.

(* M1 *)
Fail Example p466_join_natural_eq@{o so} {X Y : SetoidObject@{o o}}
  (f : X ~{Sets@{o so}}~> Y)
  (SS : carrier (Powerset_Prop_obj@{o} (Powerset_Prop_obj@{o} X))) :
  @join _ _ Powerset_Monad@{o so} Y
      (fmap[Powerset_Prop@{o so}] (fmap[Powerset_Prop@{o so}] f) SS)
    = fmap[Powerset_Prop@{o so}] f (@join _ _ Powerset_Monad@{o so} X SS)
  := eq_refl.

(* M7 *)
Fail Example p466_join_natural_fun@{o so} {X Y : SetoidObject@{o o}}
  (f : X ~{Sets@{o so}}~> Y)
  (SS : carrier (Powerset_Prop_obj@{o} (Powerset_Prop_obj@{o} X))) :
  (fun y => @join _ _ Powerset_Monad@{o so} Y
      (fmap[Powerset_Prop@{o so}] (fmap[Powerset_Prop@{o so}] f) SS) y)
    = (fun y => fmap[Powerset_Prop@{o so}] f
                  (@join _ _ Powerset_Monad@{o so} X SS) y)
  := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Sets/Powerset/Monad.v: the proof-relevant carrier *)

(* Control: the Prop-valued carrier's monad statement is formable. *)
Definition p466_prop_statement@{so o} : Type@{so} :=
  @Monad Sets@{o so} Powerset_Prop@{o so}.

(* M2 *)
Fail Definition p466_relevant_statement@{o so sso} : Type@{sso} :=
  @Monad Sets@{o so} Powerset@{o so sso}.

(* ------------------------------------------------------------------------ *)
(** ** Instance/SupLat.v: the round trip semilattice → algebra → semilattice *)

(* Controls: the carrier and the sup, at [eq_refl]; the order, logically. *)
Example p466_rt_set@{o so} (A : SupLatObject@{o}) :
  sl_set (fobj[EM_to_SupLat@{o so} ◯ SupLat_to_EM@{o so}] A) = sl_set A
  := eq_refl.

Example p466_rt_sup@{o so} (A : SupLatObject@{o}) :
  sl_sup (fobj[EM_to_SupLat@{o so} ◯ SupLat_to_EM@{o so}] A) = sl_sup A
  := eq_refl.

Example p466_rt_le_iff@{o so} (A : SupLatObject@{o})
  (x y : carrier (sl_set A)) :
  iff (sl_le (fobj[EM_to_SupLat@{o so} ◯ SupLat_to_EM@{o so}] A) x y)
      (sl_le A x y) := sl_talg_le_iff@{o so} A x y.

(* N1 *)
Fail Example p466_rt_obj@{o so} (A : SupLatObject@{o}) :
  fobj[EM_to_SupLat@{o so} ◯ SupLat_to_EM@{o so}] A = A := eq_refl.

(* N2 *)
Fail Example p466_rt_le@{o so} (A : SupLatObject@{o}) :
  sl_le (fobj[EM_to_SupLat@{o so} ◯ SupLat_to_EM@{o so}] A) = sl_le A
  := eq_refl.

(* N5b *)
Fail Example p466_rt_functor@{o so} :
  EM_to_SupLat@{o so} ◯ SupLat_to_EM@{o so} = Id[SupLat@{o so}] := eq_refl.

(* Controls: both fields of the hom round trip, at [eq_refl]. *)
Example p466_rt_hom_map@{o so} (A B : SupLatObject@{o})
  (f : SupLatHom@{o} A B) :
  slh_map (fmap[EM_to_SupLat@{o so} ◯ SupLat_to_EM@{o so}] f) = slh_map f
  := eq_refl.

Example p466_rt_hom_sup@{o so} (A B : SupLatObject@{o})
  (f : SupLatHom@{o} A B) :
  slh_sup (fmap[EM_to_SupLat@{o so} ◯ SupLat_to_EM@{o so}] f) = slh_sup f
  := eq_refl.

(* N6 *)
Fail Example p466_rt_hom@{o so} (A B : SupLatObject@{o})
  (f : SupLatHom@{o} A B) :
  fmap[EM_to_SupLat@{o so} ◯ SupLat_to_EM@{o so}] f = f := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/SupLat.v: the round trip algebra → semilattice → algebra *)

(* Controls: the carrier and the structure map, at [eq_refl], at a
   variable object and at a named algebra. *)
Example p466_rt2_carrier@{o so}
  (x : @EilenbergMoore@{so so so o} Sets@{o so} Powerset_Prop@{o so}
         Powerset_Monad@{o so}) :
  projT1 (fobj[SupLat_to_EM@{o so} ◯ EM_to_SupLat@{o so}] x) = projT1 x
  := eq_refl.

Example p466_rt2_alg@{o so}
  (x : @EilenbergMoore@{so so so o} Sets@{o so} Powerset_Prop@{o so}
         Powerset_Monad@{o so}) :
  t_alg[projT2 (fobj[SupLat_to_EM@{o so} ◯ EM_to_SupLat@{o so}] x)]
    = t_alg[projT2 x] := eq_refl.

Example p466_alg_rt_data@{o so} {X : SetoidObject@{o o}}
  (α : @TAlgebra Sets@{o so} Powerset_Prop@{o so} Powerset_Monad@{o so} X) :
  t_alg[SupLat_TAlgebra@{o so} (TAlgebra_SupLat@{o so} α)] = t_alg[α]
  := eq_refl.

Example p466_rt2_hom@{o so}
  (x y : @EilenbergMoore@{so so so o} Sets@{o so} Powerset_Prop@{o so}
           Powerset_Monad@{o so}) (f : x ~> y) :
  t_alg_hom[fmap[SupLat_to_EM@{o so} ◯ EM_to_SupLat@{o so}] f]
    = t_alg_hom[f] := eq_refl.

(* N3 *)
Fail Example p466_rt2_obj@{o so}
  (x : @EilenbergMoore@{so so so o} Sets@{o so} Powerset_Prop@{o so}
         Powerset_Monad@{o so}) :
  fobj[SupLat_to_EM@{o so} ◯ EM_to_SupLat@{o so}] x = x := eq_refl.

(* N4 *)
Fail Example p466_rt2_t_id@{o so}
  (x : @EilenbergMoore@{so so so o} Sets@{o so} Powerset_Prop@{o so}
         Powerset_Monad@{o so}) :
  @t_id _ _ _ _ (projT2 (fobj[SupLat_to_EM@{o so} ◯ EM_to_SupLat@{o so}] x))
    = @t_id _ _ _ _ (projT2 x) := eq_refl.

(* N4b *)
Fail Example p466_rt2_t_action@{o so}
  (x : @EilenbergMoore@{so so so o} Sets@{o so} Powerset_Prop@{o so}
         Powerset_Monad@{o so}) :
  @t_action _ _ _ _
      (projT2 (fobj[SupLat_to_EM@{o so} ◯ EM_to_SupLat@{o so}] x))
    = @t_action _ _ _ _ (projT2 x) := eq_refl.

(* N5 *)
Fail Example p466_rt2_functor@{o so} :
  SupLat_to_EM@{o so} ◯ EM_to_SupLat@{o so}
    = Id[@EilenbergMoore@{so so so o} Sets@{o so} Powerset_Prop@{o so}
           Powerset_Monad@{o so}] := eq_refl.

(* N7 *)
Fail Example p466_alg_rt@{o so} {X : SetoidObject@{o o}}
  (α : @TAlgebra Sets@{o so} Powerset_Prop@{o so} Powerset_Monad@{o so} X) :
  SupLat_TAlgebra@{o so} (TAlgebra_SupLat@{o so} α) = α := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Variant L: two redundant law fields (scout B's t5) *)

(* The order-first record with the two algebra laws of the sup added as
   fields; not adopted, since the record is then no longer Mac Lane's
   definition. *)
Record p466_SupLatObjectL@{o} := {
  p466_sll_set : SetoidObject@{o o};
  p466_sll_le : carrier p466_sll_set → carrier p466_sll_set → Prop;
  p466_sll_le_refl x : p466_sll_le x x;
  p466_sll_le_trans x y z :
    p466_sll_le x y → p466_sll_le y z → p466_sll_le x z;
  p466_sll_le_respects x x' y y' :
    @equiv _ (is_setoid p466_sll_set) x x' →
    @equiv _ (is_setoid p466_sll_set) y y' →
    p466_sll_le x y → p466_sll_le x' y';
  p466_sll_antisym x y :
    p466_sll_le x y → p466_sll_le y x →
    @equiv _ (is_setoid p466_sll_set) x y;
  p466_sll_sup :
    SetoidMorphism@{o o o} (Powerset_Prop_obj@{o} p466_sll_set) p466_sll_set;
  p466_sll_sup_ub (S : carrier (Powerset_Prop_obj@{o} p466_sll_set)) x :
    S x → p466_sll_le x (p466_sll_sup S);
  p466_sll_sup_least (S : carrier (Powerset_Prop_obj@{o} p466_sll_set)) y :
    (∀ x, S x → p466_sll_le x y) → p466_sll_le (p466_sll_sup S) y;
  p466_sll_unit x :
    @equiv _ (is_setoid p466_sll_set)
      (p466_sll_sup (Powerset_Prop_singleton_pred@{o} x)) x;
  p466_sll_assoc
    (SS : carrier (Powerset_Prop_obj@{o}
                     (Powerset_Prop_obj@{o} p466_sll_set))) :
    @equiv _ (is_setoid p466_sll_set)
      (p466_sll_sup (Powerset_Prop_image@{o} p466_sll_sup SS))
      (p466_sll_sup (Powerset_union_pred@{o} SS))
}.

Definition p466_L_TAlgebra@{o so} (A : p466_SupLatObjectL@{o}) :
  @TAlgebra Sets@{o so} Powerset_Prop@{o so} Powerset_Monad@{o so}
    (p466_sll_set A) :=
  @Build_TAlgebra Sets@{o so} Powerset_Prop@{o so} Powerset_Monad@{o so}
    (p466_sll_set A) (p466_sll_sup A) (p466_sll_unit A) (p466_sll_assoc A).

Definition p466_TAlgebra_L@{o so} {X : SetoidObject@{o o}}
  (α : @TAlgebra Sets@{o so} Powerset_Prop@{o so} Powerset_Monad@{o so} X) :
  p466_SupLatObjectL@{o} :=
  @Build_p466_SupLatObjectL@{o} X (talg_le@{o so} α)
    (talg_le_refl@{o so} α) (talg_le_trans@{o so} α)
    (talg_le_respects@{o so} α) (talg_antisym@{o so} α)
    t_alg[α] (talg_sup_ub@{o so} α) (talg_sup_least@{o so} α)
    (@t_id _ _ _ _ α) (@t_action _ _ _ _ α).

(* Controls: variant L's algebra round trip holds on the whole algebra,
   and on the whole EM object written (X; α). *)
Example p466_L_alg_rt@{o so} {X : SetoidObject@{o o}}
  (α : @TAlgebra Sets@{o so} Powerset_Prop@{o so} Powerset_Monad@{o so} X) :
  p466_L_TAlgebra@{o so} (p466_TAlgebra_L@{o so} α) = α := eq_refl.

Example p466_L_obj_rt@{o so} {X : SetoidObject@{o o}}
  (α : @TAlgebra Sets@{o so} Powerset_Prop@{o so} Powerset_Monad@{o so} X) :
  existT (fun Y => @TAlgebra Sets@{o so} Powerset_Prop@{o so}
                     Powerset_Monad@{o so} Y)
    X (p466_L_TAlgebra@{o so} (p466_TAlgebra_L@{o so} α))
  = existT _ X α := eq_refl.

(* N8 *)
Fail Example p466_L_var_rt@{o so}
  (x : @EilenbergMoore@{so so so o} Sets@{o so} Powerset_Prop@{o so}
         Powerset_Monad@{o so}) :
  existT (fun Y => @TAlgebra Sets@{o so} Powerset_Prop@{o so}
                     Powerset_Monad@{o so} Y)
    (projT1 x) (p466_L_TAlgebra@{o so} (p466_TAlgebra_L@{o so} (projT2 x)))
  = x := eq_refl.

(* Control: variant L's semilattice round trip keeps the carrier. *)
Example p466_L_set_rt@{o so} (A : p466_SupLatObjectL@{o}) :
  p466_sll_set (p466_TAlgebra_L@{o so} (p466_L_TAlgebra@{o so} A))
    = p466_sll_set A := eq_refl.

(* N8b *)
Fail Example p466_L_le_rt@{o so} (A : p466_SupLatObjectL@{o}) :
  p466_sll_le (p466_TAlgebra_L@{o so} (p466_L_TAlgebra@{o so} A))
    = p466_sll_le A := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Variant A: the sup as a bare function *)

(* The properness of a sup, derived from the order.  Transparent, so that
   the comparison below is not stopped by opacity. *)
Definition p466_sup_respects@{o} (A : SupLatObject@{o})
  (S T : carrier (Powerset_Prop_obj@{o} (sl_set A))) (E : S ≈ T) :
  @equiv _ (is_setoid (sl_set A)) (sl_sup A S) (sl_sup A T).
Proof.
  apply sl_antisym; apply sl_sup_least; intros x Hx; apply sl_sup_ub.
  - exact (proj1 (E x) Hx).
  - exact (proj2 (E x) Hx).
Defined.

Definition p466_varA_alg@{o} (A : SupLatObject@{o}) :
  SetoidMorphism@{o o o} (Powerset_Prop_obj@{o} (sl_set A)) (sl_set A) :=
  @Build_SetoidMorphism@{o o o} _ _ _ _ (fun S => sl_sup A S)
    (p466_sup_respects@{o} A).

(* Control: the functions agree. *)
Example p466_varA_fun@{o} (A : SupLatObject@{o}) :
  (fun S => p466_varA_alg@{o} A S) = (fun S => sl_sup A S) := eq_refl.

(* N9 *)
Fail Example p466_varA_whole@{o} (A : SupLatObject@{o}) :
  p466_varA_alg@{o} A = sl_sup A := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** A Type-valued order *)

(* Control: with a Prop-valued order the unit law's inequality is formable
   (the order of [TAlgebra_SupLat], by [talg_sup_least]'s shape). *)
Example p466_proporder_unit@{o} (A : SupLatObject@{o})
  (x : carrier (sl_set A)) :
  ∀ z, Powerset_Prop_singleton_pred@{o} x z → sl_le A z x :=
  fun z Hz => Hz (sl_le A z x)
    (fun e => sl_le_respects A x z x x e (reflexivity x) (sl_le_refl A x)).

Section TypeOrder.
Universe o.
Constraint Set < o.
Context (X : SetoidObject@{o o}) (le : carrier X → carrier X → Type@{o}).
Context (le_respects : ∀ x x' y y', @equiv _ (is_setoid X) x x' →
          @equiv _ (is_setoid X) y y' → le x y → le x' y').
Context (le_refl : ∀ x, le x x).

(* N10 *)
Fail Definition p466_typeorder_unit (x : carrier X) :
  ∀ z, Powerset_Prop_singleton_pred@{o} x z → le z x :=
  fun z Hz => Hz (le z x)
    (fun e => le_respects x z x x e (reflexivity x) (le_refl x)).

End TypeOrder.

(* ------------------------------------------------------------------------ *)
(** ** Instance/SupLat/Free.v: the induced monad against [Powerset_Monad] *)

(* Controls: the object and arrow maps of the composite, as functions. *)
Example p466_ind_obj_fun@{o so} :
  (fun X => fobj[SL_Forget@{o so} ◯ SL_Free@{o so}] X)
    = (fun X => fobj[Powerset_Prop@{o so}] X) := eq_refl.

Example p466_ind_map_fun@{o so} (X Y : SetoidObject@{o o}) :
  (fun f : X ~{Sets@{o so}}~> Y =>
     fmap[SL_Forget@{o so} ◯ SL_Free@{o so}] f)
    = (fun f => fmap[Powerset_Prop@{o so}] f) := eq_refl.

(* Control: the unit as a function. *)
Example p466_ind_ret_fun@{o so} (X : SetoidObject@{o o}) :
  (fun x => @ret _ _ SL_induced@{o so} X x)
    = (fun x => @ret _ _ Powerset_Monad@{o so} X x) := eq_refl.

(* Control: the induced unit IS the identity composed with #227's
   singleton map. *)
Example p466_ind_ret_compose@{o so} (X : SetoidObject@{o o}) :
  @ret _ _ SL_induced@{o so} X
    = @setoid_morphism_compose@{o o o} _ _ _
        (@setoid_morphism_id@{o o o} (Powerset_Prop_obj@{o} X))
        (@Powerset_Prop_singleton_map@{o} X) := eq_refl.

(* F1 *)
Fail Example p466_ind_ret_whole@{o so} (X : SetoidObject@{o o}) :
  @ret _ _ SL_induced@{o so} X = @ret _ _ Powerset_Monad@{o so} X
  := eq_refl.

(* Control: the unit at ≈. *)
Example p466_ind_ret_equiv@{o so} (X : SetoidObject@{o o}) :
  @ret _ _ SL_induced@{o so} X ≈ @ret _ _ Powerset_Monad@{o so} X :=
  SL_induced_ret_equiv@{o so} X.

(* Control: the induced join is ⋃ ∘ P id. *)
Example p466_ind_join_fun_ctl@{o so} (X : SetoidObject@{o o}) :
  (fun SS => @join _ _ SL_induced@{o so} X SS)
    = (fun SS => Powerset_union_pred@{o}
                   (Powerset_Prop_image@{o}
                      (@setoid_morphism_id@{o o o} (Powerset_Prop_obj@{o} X))
                      SS)) := eq_refl.

(* F2 *)
Fail Example p466_ind_join_fun@{o so} (X : SetoidObject@{o o}) :
  (fun SS => @join _ _ SL_induced@{o so} X SS)
    = (fun SS => @join _ _ Powerset_Monad@{o so} X SS) := eq_refl.

(* F2b *)
Fail Example p466_ind_join_at@{o so} (X : SetoidObject@{o o})
  (SS : carrier (Powerset_Prop_obj@{o} (Powerset_Prop_obj@{o} X))) :
  @join _ _ SL_induced@{o so} X SS = @join _ _ Powerset_Monad@{o so} X SS
  := eq_refl.

(* Control: the join at ≈. *)
Example p466_ind_join_equiv@{o so} (X : SetoidObject@{o o}) :
  @join _ _ SL_induced@{o so} X ≈ @join _ _ Powerset_Monad@{o so} X :=
  SL_induced_join_equiv@{o so} X.

(* F3 *)
Fail Example p466_ind_functor@{o so} :
  SL_Forget@{o so} ◯ SL_Free@{o so} = Powerset_Prop@{o so} := eq_refl.

(* Controls: the functor at ≈, with the identity isomorphism as its
   component. *)
Example p466_ind_functor_equiv@{o so} :
  SL_Forget@{o so} ◯ SL_Free@{o so} ≈ Powerset_Prop@{o so} :=
  SL_induced_functor_equiv@{o so}.

Example p466_ind_functor_component@{o so} (X : SetoidObject@{o o}) :
  projT1 SL_induced_functor_equiv@{o so} X
    = @iso_id Sets@{o so} (fobj[Powerset_Prop@{o so}] X) := eq_refl.

(* F4 *)
Fail Definition p466_ind_monad@{o so} :
  @Monad Sets@{o so} (SL_Forget@{o so} ◯ SL_Free@{o so}) :=
  Powerset_Monad@{o so}.

(* ------------------------------------------------------------------------ *)
(** ** Instance/SupLat/Free.v: the comparison round trips *)

(* Controls: identity components at a variable object, and the carrier. *)
Example p466_cmp_counit_component@{o so}
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (SL_Forget@{o so} ◯ SL_Free@{o so}) SL_induced@{o so}) :
  t_alg_hom[to (projT1 (@equivalence_counit _ _ _
                           SL_comparison_equivalence@{o so}) x)]
    = @setoid_morphism_id@{o o o} (projT1 x) := eq_refl.

Example p466_cmp_unit_component@{o so} (A : SupLatObject@{o}) :
  slh_map (to (projT1 (@equivalence_unit _ _ _
                         SL_comparison_equivalence@{o so}) A))
    = @setoid_morphism_id@{o o o} (sl_set A) := eq_refl.

Example p466_cmp_carrier@{o so} (A : SupLatObject@{o}) :
  sl_set (fobj[EM_induced_to_SupLat@{o so} ◯ EM_Comparison SL_adj@{o so}] A)
  = sl_set A := eq_refl.

(* F5 *)
Fail Example p466_cmp_composite@{o so} :
  EM_Comparison SL_adj@{o so} ◯ EM_induced_to_SupLat@{o so}
  = Id[@EilenbergMoore@{so so so o} Sets@{o so}
         (SL_Forget@{o so} ◯ SL_Free@{o so}) SL_induced@{o so}] := eq_refl.

(* F5b *)
Fail Example p466_cmp_composite_b@{o so} :
  EM_induced_to_SupLat@{o so} ◯ EM_Comparison SL_adj@{o so}
  = Id[SupLat@{o so}] := eq_refl.

(* F6 *)
Fail Example p466_cmp_obj@{o so} (A : SupLatObject@{o}) :
  fobj[EM_induced_to_SupLat@{o so} ◯ EM_Comparison SL_adj@{o so}] A = A
  := eq_refl.

(* F6b *)
Fail Example p466_cmp_obj_b@{o so}
  (x : @EilenbergMoore@{so so so o} Sets@{o so}
         (SL_Forget@{o so} ◯ SL_Free@{o so}) SL_induced@{o so}) :
  fobj[EM_Comparison SL_adj@{o so} ◯ EM_induced_to_SupLat@{o so}] x = x
  := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/SupLat/Examples.v: P X and P 1 *)

(* Controls: (b) at the free algebra has the carrier and the sup of
   [FreeSL X], and its order is inclusion logically. *)
Example p466_freesl_em_set@{o so} (X : SetoidObject@{o o}) :
  sl_set (fobj[EM_to_SupLat@{o so}]
            (fobj[@EM_Free Sets@{o so} Powerset_Prop@{o so}
                    Powerset_Monad@{o so}] X))
  = sl_set (FreeSL@{o} X) := eq_refl.

Example p466_freesl_em_sup@{o so} (X : SetoidObject@{o o}) :
  sl_sup (fobj[EM_to_SupLat@{o so}]
            (fobj[@EM_Free Sets@{o so} Powerset_Prop@{o so}
                    Powerset_Monad@{o so}] X))
  = sl_sup (FreeSL@{o} X) := eq_refl.

Example p466_freesl_em_le_iff@{o so} (X : SetoidObject@{o o})
  (S T : carrier (Powerset_Prop_obj@{o} X)) :
  iff (sl_le (fobj[EM_to_SupLat@{o so}]
                (fobj[@EM_Free Sets@{o so} Powerset_Prop@{o so}
                        Powerset_Monad@{o so}] X)) S T)
      (sl_le (FreeSL@{o} X) S T) :=
  sl_talg_le_iff@{o so} (FreeSL@{o} X) S T.

(* E1 *)
Fail Example p466_freesl_em_obj@{o so} (X : SetoidObject@{o o}) :
  fobj[EM_to_SupLat@{o so}]
    (fobj[@EM_Free Sets@{o so} Powerset_Prop@{o so} Powerset_Monad@{o so}] X)
  = FreeSL@{o} X := eq_refl.

(* E1b *)
Fail Example p466_freesl_em_le@{o so} (X : SetoidObject@{o o}) :
  sl_le (fobj[EM_to_SupLat@{o so}]
           (fobj[@EM_Free Sets@{o so} Powerset_Prop@{o so}
                   Powerset_Monad@{o so}] X))
  = sl_le (FreeSL@{o} X) := eq_refl.

(* Control: (c) at P X has the free algebra's carrier at [eq_refl]; its
   structure map is Instance/SupLat/Examples.v's [FreeSL_alg]. *)
Example p466_freealg_carrier@{o so} (X : SetoidObject@{o o}) :
  projT1 (fobj[SupLat_to_EM@{o so}] (FreeSL@{o} X))
    = projT1 (fobj[@EM_Free Sets@{o so} Powerset_Prop@{o so}
                    Powerset_Monad@{o so}] X) := eq_refl.

(* E3 *)
Fail Example p466_freealg_whole@{o so} (X : SetoidObject@{o o}) :
  projT2 (fobj[SupLat_to_EM@{o so}] (FreeSL@{o} X))
    = projT2 (fobj[@EM_Free Sets@{o so} Powerset_Prop@{o so}
                    Powerset_Monad@{o so}] X) := eq_refl.

(* E3b *)
Fail Example p466_freealg_obj@{o so} (X : SetoidObject@{o o}) :
  fobj[SupLat_to_EM@{o so}] (FreeSL@{o} X)
    = fobj[@EM_Free Sets@{o so} Powerset_Prop@{o so} Powerset_Monad@{o so}] X
  := eq_refl.

(* Controls: the P 1 round trip at the point, and the Prop round trip. *)
Example p466_prop_p1_rt_at@{o}
  (T : carrier (Powerset_Prop_obj@{o} unit_setoid_object@{o o})) :
  slh_map Prop_to_P1@{o} (slh_map P1_to_Prop@{o} T) ttt = T ttt := eq_refl.

Example p466_p1_prop_rt@{o} (Q : Prop) :
  slh_map P1_to_Prop@{o} (slh_map Prop_to_P1@{o} Q) = Q := eq_refl.

(* E2 *)
Fail Example p466_prop_p1_rt@{o}
  (T : carrier (Powerset_Prop_obj@{o} unit_setoid_object@{o o})) :
  slh_map Prop_to_P1@{o} (slh_map P1_to_Prop@{o} T) = T := eq_refl.

(* Control: the two-point theorem at its stated type. *)
Definition p466_two_points@{o} (A : SupLatObject@{o})
  (bot top : carrier (sl_set A)) (Hle : sl_le A bot top)
  (Hne : @equiv _ (is_setoid (sl_set A)) top bot → False)
  (Hdec : ∀ x y, @equiv _ (is_setoid (sl_set A)) x y
                 + (@equiv _ (is_setoid (sl_set A)) x y → False)) :
  ∀ Q : Prop, (~ Q) + (~ ~ Q) :=
  suplat_two_points_WLEM@{o} A bot top Hle Hne Hdec.

(* Control: the chain's carrier is Instance/Sets.v's two-element setoid. *)
Example p466_chain_carrier@{o}
  (wlem : ∀ Q : Prop, (~ Q) + (~ ~ Q)) :
  sl_set (bool_SupLat@{o} wlem) = bool_setoid_object@{o o} := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Sets/Powerset/Monad/Riehl.v: the routes prove the field *)

(* Control: Riehl's route through the left adjoint proves the statement of
   [Powerset_Monad]'s naturality field, as stated. *)
Definition p466_riehl_lapc@{o so} {X Y : SetoidObject@{o o}}
  (f : X ~{Sets@{o so}}~> Y) : Powerset_join_natural_statement@{o so} f :=
  fun SS => join_natural_via_LAPC f SS.

(* ------------------------------------------------------------------------ *)
(** ** Closure: readbacks, not refutations *)

Print Assumptions Powerset_Monad.
Print Assumptions SupLat_EM_iso.
Print Assumptions SupLat_EM_equivalence.
Print Assumptions talg_PropEquiv.
Print Assumptions sl_PropEquiv.
Print Assumptions SL_adj.
Print Assumptions SL_Forget_Monadic.
Print Assumptions SL_induced.
Print Assumptions suplat_two_points_WLEM.
Print Assumptions bool_SupLat_WLEM.
Print Assumptions bool_SupLat.
Print Assumptions Prop_P1_iso.
Print Assumptions join_natural_routes_agree.

(* ------------------------------------------------------------------------ *)
(** ** Guard: every constant of the five targets, by its full name *)

Check @Category.Instance.Sets.Powerset.Monad.Powerset_union_pred.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_union_respects.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_union.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_union_assoc.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_union_image_singleton.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_union_singleton.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_union_natural.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_Monad.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_Monad_obj.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_Monad_map.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_Monad_ret.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_Monad_ret_map.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_Monad_ret_at.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_Monad_join.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_Monad_join_at.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_Monad_map_at.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_Monad_ret_member.
Check @Category.Instance.Sets.Powerset.Monad.Powerset_Monad_statement.
Check @Category.Instance.SupLat.Powerset_Prop_pair.
Check @Category.Instance.SupLat.Powerset_Prop_pair_respects.
Check @Category.Instance.SupLat.Powerset_Prop_pair_comm.
Check @Category.Instance.SupLat.Powerset_Prop_singleton_sub.
Check @Category.Instance.SupLat.Powerset_union_pair_sub.
Check @Category.Instance.SupLat.Powerset_Prop_least_family.
Check @Category.Instance.SupLat.SupLatObject.
Check @Category.Instance.SupLat.Build_SupLatObject.
Check @Category.Instance.SupLat.sl_set.
Check @Category.Instance.SupLat.sl_le.
Check @Category.Instance.SupLat.sl_le_refl.
Check @Category.Instance.SupLat.sl_le_trans.
Check @Category.Instance.SupLat.sl_le_respects.
Check @Category.Instance.SupLat.sl_antisym.
Check @Category.Instance.SupLat.sl_sup.
Check @Category.Instance.SupLat.sl_sup_ub.
Check @Category.Instance.SupLat.sl_sup_least.
Check @Category.Instance.SupLat.SupLatHom.
Check @Category.Instance.SupLat.Build_SupLatHom.
Check @Category.Instance.SupLat.slh_map.
Check @Category.Instance.SupLat.slh_sup.
Check @Category.Instance.SupLat.SupLatHom_Setoid.
Check @Category.Instance.SupLat.SupLat_id.
Check @Category.Instance.SupLat.SupLat_compose.
Check @Category.Instance.SupLat.SupLat.
Check @Category.Instance.SupLat.sl_sup_pair_le.
Check @Category.Instance.SupLat.SupLatHom_monotone.
Check @Category.Instance.SupLat.sl_PropEquiv.
Check @Category.Instance.SupLat.SupLat_TAlgebra.
Check @Category.Instance.SupLat.talg_singleton.
Check @Category.Instance.SupLat.talg_unsquash.
Check @Category.Instance.SupLat.talg_pair.
Check @Category.Instance.SupLat.talg_mono.
Check @Category.Instance.SupLat.talg_le.
Check @Category.Instance.SupLat.talg_le_iff.
Check @Category.Instance.SupLat.talg_le_refl.
Check @Category.Instance.SupLat.talg_sup_ub.
Check @Category.Instance.SupLat.talg_sup_least.
Check @Category.Instance.SupLat.talg_le_trans.
Check @Category.Instance.SupLat.talg_le_respects.
Check @Category.Instance.SupLat.talg_antisym.
Check @Category.Instance.SupLat.TAlgebra_SupLat.
Check @Category.Instance.SupLat.talg_PropEquiv.
Check @Category.Instance.SupLat.sl_talg_le_iff.
Check @Category.Instance.SupLat.EM_to_SupLat.
Check @Category.Instance.SupLat.SupLat_to_EM.
Check @Category.Instance.SupLat.SupLat_EM_counit_iso.
Check @Category.Instance.SupLat.SupLat_EM_unit_iso.
Check @Category.Instance.SupLat.SupLat_EM_equivalence.
Check @Category.Instance.SupLat.SupLat_EM_iso.
Check @Category.Instance.SupLat.SupLat_EM_iso_to.
Check @Category.Instance.SupLat.SupLat_EM_iso_from.
Check @Category.Instance.SupLat.EM_to_SupLat_carrier.
Check @Category.Instance.SupLat.EM_to_SupLat_sup.
Check @Category.Instance.SupLat.EM_to_SupLat_le.
Check @Category.Instance.SupLat.SupLat_to_EM_carrier.
Check @Category.Instance.SupLat.SupLat_to_EM_alg.
Check @Category.Instance.SupLat.EM_to_SupLat_map.
Check @Category.Instance.SupLat.SupLat_to_EM_map.
Check @Category.Instance.SupLat.SupLat_EM_rt_carrier.
Check @Category.Instance.SupLat.SupLat_EM_rt_alg.
Check @Category.Instance.SupLat.SupLat_EM_rt_set.
Check @Category.Instance.SupLat.SupLat_EM_rt_sup.
Check @Category.Instance.SupLat.SupLat_EM_rt_hom.
Check @Category.Instance.SupLat.SupLat_EM_rt_alg_hom.
Check @Category.Instance.SupLat.SupLat_EM_counit_component.
Check @Category.Instance.SupLat.SupLat_EM_unit_component.
Check @Category.Instance.SupLat.SupLat_EM_counit_component_from.
Check @Category.Instance.SupLat.SupLat_EM_unit_component_from.
Check @Category.Instance.SupLat.SupLat_EM_iso_to_from_component.
Check @Category.Instance.SupLat.SupLat_EM_iso_from_to_component.
Check @Category.Instance.SupLat.SupLat_EM_iso_to_from_component_from.
Check @Category.Instance.SupLat.SupLat_EM_iso_from_to_component_from.
Check @Category.Instance.SupLat.Free.FreeSL.
Check @Category.Instance.SupLat.Free.SL_Free.
Check @Category.Instance.SupLat.Free.SL_Forget.
Check @Category.Instance.SupLat.Free.SL_extend.
Check @Category.Instance.SupLat.Free.SL_restrict.
Check @Category.Instance.SupLat.Free.SL_adj_iso.
Check @Category.Instance.SupLat.Free.SL_adj.
Check @Category.Instance.SupLat.Free.SL_induced.
Check @Category.Instance.SupLat.Free.SL_induced_obj.
Check @Category.Instance.SupLat.Free.SL_induced_map.
Check @Category.Instance.SupLat.Free.SL_induced_ret_fun.
Check @Category.Instance.SupLat.Free.SL_induced_join_fun.
Check @Category.Instance.SupLat.Free.SL_induced_ret_equiv.
Check @Category.Instance.SupLat.Free.SL_induced_join_equiv.
Check @Category.Instance.SupLat.Free.SL_induced_functor_equiv.
Check @Category.Instance.SupLat.Free.SL_induced_functor_component.
Check @Category.Instance.SupLat.Free.SL_induced_repack.
Check @Category.Instance.SupLat.Free.EM_induced_to_SupLat.
Check @Category.Instance.SupLat.Free.SL_comparison_counit_iso.
Check @Category.Instance.SupLat.Free.SL_comparison_unit_iso.
Check @Category.Instance.SupLat.Free.SL_comparison_equivalence.
Check @Category.Instance.SupLat.Free.SL_Forget_Monadic.
Check @Category.Instance.SupLat.Free.SL_comparison_counit_component.
Check @Category.Instance.SupLat.Free.SL_comparison_counit_component_from.
Check @Category.Instance.SupLat.Free.SL_comparison_unit_component.
Check @Category.Instance.SupLat.Free.SL_comparison_unit_component_from.
Check @Category.Instance.SupLat.Examples.FreeSL_set.
Check @Category.Instance.SupLat.Examples.FreeSL_le.
Check @Category.Instance.SupLat.Examples.FreeSL_sup.
Check @Category.Instance.SupLat.Examples.FreeSL_alg.
Check @Category.Instance.SupLat.Examples.FreeSL_talg_le_iff.
Check @Category.Instance.SupLat.Examples.FreeSL_extend_singleton.
Check @Category.Instance.SupLat.Examples.FreeSL_extend_unique.
Check @Category.Instance.SupLat.Examples.Prop_sup.
Check @Category.Instance.SupLat.Examples.Prop_SupLat.
Check @Category.Instance.SupLat.Examples.Prop_SupLat_le.
Check @Category.Instance.SupLat.Examples.Prop_SupLat_sup.
Check @Category.Instance.SupLat.Examples.Prop_SupLat_nontrivial.
Check @Category.Instance.SupLat.Examples.Prop_to_P1_pred.
Check @Category.Instance.SupLat.Examples.Prop_to_P1.
Check @Category.Instance.SupLat.Examples.P1_to_Prop.
Check @Category.Instance.SupLat.Examples.Prop_P1_iso.
Check @Category.Instance.SupLat.Examples.Prop_to_P1_at.
Check @Category.Instance.SupLat.Examples.Prop_P1_round_trip.
Check @Category.Instance.SupLat.Examples.two_points_probe.
Check @Category.Instance.SupLat.Examples.suplat_two_points_WLEM.
Check @Category.Instance.SupLat.Examples.Prop_SupLat_decidable_WLEM.
Check @Category.Instance.SupLat.Examples.bool_chain_le.
Check @Category.Instance.SupLat.Examples.bool_chain_SupLat.
Check @Category.Instance.SupLat.Examples.bool_SupLat_WLEM.
Check @Category.Instance.SupLat.Examples.bool_chain_sup_fun.
Check @Category.Instance.SupLat.Examples.bool_chain_sup_true.
Check @Category.Instance.SupLat.Examples.bool_chain_sup_false.
Check @Category.Instance.SupLat.Examples.bool_chain_sup.
Check @Category.Instance.SupLat.Examples.bool_SupLat.
Check @Category.Instance.Sets.Powerset.Monad.Riehl.Powerset_union_IsLUB.
Check @Category.Instance.Sets.Powerset.Monad.Riehl.Powerset_union_family.
Check @Category.Instance.Sets.Powerset.Monad.Riehl.join_natural_via_image.
Check @Category.Instance.Sets.Powerset.Monad.Riehl.join_natural_via_LAPC.
Check @Category.Instance.Sets.Powerset.Monad.Riehl.Powerset_join_natural_statement.
Check @Category.Instance.Sets.Powerset.Monad.Riehl.join_natural_routes_agree.
