(** * Probe for the identity monad and the non-monadic discrete adjunctions
      (issue #469)

    Pins the measured boundaries of the five files #469 adds for Mac
    Lane, §VI.3, book p. 144 (PDF p. 153), catalog item
    maclane:VI.3:remark1, read from the page image: the adjunction
    ⟨D, G, η, …⟩ : Set ⇀ Top "defines on Set the monad I = ⟨I, 1, 1⟩
    which is the identity (identity functor, identity as unit and as
    multiplication).  The I-algebras in Set are just the sets, so the
    comparison functor Top → Top^I = Set is in this case the given
    forgetful functor G", "not an isomorphism, and not even an
    equivalence"; and for the appended box, Awodey, §10.3, printed p. 278
    (PDF p. 287), catalog item awodey:10.3:example-pos-not-monadic, read
    from the page image: "An example of a right adjoint that is not
    monadic is the forgetful functor from posets, U : Pos → Sets.  Its
    left adjoint F is the discrete poset functor.  For any set X,
    therefore, one has as the unit the identity function X = UF(X)."  The
    files are Monad/Identity.v ([IdMonad] on any category),
    Instance/Top/Monadicity.v (Mac Lane's example over the Prop-valued
    [PTopCat]), Instance/Top/Monadicity/TypeValued.v (non-monadicity over
    the Type-valued [Top]), Instance/Sets/Propositional/Full.v (the full
    reflective subcategory [PropSets] of propositional setoids) and
    Instance/Pos/Monadicity.v (Awodey's example, over [PropSets] and over
    [Sets]).  Their headers cite the refutations and controls here:
    Monad/Identity.v C55; Instance/Top/Monadicity.v R1 to R3 with R1a to
    R1c and R2a to R2c, R13, R14, R15, C1 to C4, C17, C20, C36 and C39;
    Instance/Sets/Propositional/Full.v R7, R12 and R19 to R21;
    Instance/Pos/Monadicity.v R1 (as Instance/Top/Monadicity.v's
    header reads it), R4 to R12, R16 to R21, C44, C49, C52 and C53.
    Each of the forty-five [Example]s of the five targets, all proved by
    [eq_refl], has a control that restates it at the same generality and
    independently of the constant that states it (RESTATEMENTS, below).

    THE IMPORT LIST, generated by a script over the [Require] lines.
    Target by target in dependency order: Monad/Identity.v's nine
    [Require] lines in its own order, and that target; the thirteen lines
    Instance/Top/Monadicity.v adds (Theory/Natural/Transformation.v,
    Theory/Adjunction.v, Theory/Equivalence/FullFaithful.v,
    Structure/Limit/Preservation.v, Monad/Comparison.v, Monad/Morphism.v,
    Monad/Morphism/Algebra.v, Monad/Monadicity/BeckObjects.v,
    Instance/Cat.v, Instance/Sets.v, Instance/Top/Prop.v,
    Instance/Top/Complete.v and Instance/Top/Cocomplete.v), and that
    target; the two lines Instance/Top/Monadicity/TypeValued.v adds
    (Instance/Top.v and Instance/Top/Forgetful.v), and that target; the
    four lines Instance/Sets/Propositional/Full.v adds
    (Lib/Setoid/Propositional.v, Construction/Subcategory.v,
    Construction/Reflective.v and Instance/Sets/Propositional.v), and
    that target; the three lines Instance/Pos/Monadicity.v adds
    (Construction/Reflective/Monadic.v, Instance/Pos.v and
    Instance/Proset/Monotone.v), and that target.  Thirty-six lines,
    all naming [Category] modules.  Under them [Print Libraries] in a
    scratch file loads one hundred and thirty [Category] modules,
    exactly the union of the five targets' dependency closures (compared
    by script with the closure of each target's own [Require]).  Four
    more lines are loaded at the end of this file, after every other
    command, the guard block included: Instance/Sets/Classifier/
    OneLevel.v for controls C53 and C54, and Instance/Adjoints.v,
    Adjunction/Compose.v and Monad/Monadicity/Examples.v for control
    C55; with them the count is one hundred and forty.  A shorter import
    list is what makes a probe pass for no reason.

    NAMES.  Two short names are shadowed under this list, and the
    commands here write the intended constant in full.  [unit] and
    [counit] resolve to Adjunction/Natural/Transformation.v's, which
    Instance/Top.v and Construction/Reflective/Monadic.v bring, so C12,
    C13, C24 and C43 write Category.Theory.Adjunction.unit and .counit.
    [Full] resolves to Construction/Subcategory.v's, so the targets write
    Functor.Full, and no command here names either.

    DISCIPLINE.  Every negative is an [Example] or a [Definition], never a
    [Check], so that an open evar cannot satisfy it.  Each of the
    twenty-seven refutation lines was stripped of its refutation keyword
    in a copy of this WHOLE file, one at a time, compiled, and its error
    read; each copy stops inside the stripped command (twenty-seven of
    twenty-seven, by the File line of its error, compared by script with
    the command's extent).  Each of the fifty-five controls, wrapped in
    the refutation keyword in a copy of this WHOLE file, stops the build
    at that command with the message Rocq prints for a refutation whose
    command succeeds (fifty-five of fifty-five, by the same script).
    Quotations are Rocq 9.1.1's under this file's import list, with the
    error's environment block left out; Rocq prints the "cannot unify"
    parenthetical with the short names in scope.  The five targets and
    this file also compile on Coq 8.19.2 and 8.20.1, with no warning from
    this file, overlaid on copies of the dependency closure whose one
    hundred and forty sources are this tree's byte for byte (compared by
    [cmp]).  Each of the twenty-seven stripped copies is refused there
    inside the stripped command with the Rocq 9.1.1 error, environment
    block included (compared by script), and every wrapped control reports
    there that its command succeeded (fifty-five of fifty-five on each
    version).

    KINDS.  Twenty-seven refutations, counted as the lines that open with
    the refutation keyword: TYPING, a statement that is itself ill-typed
    (R6: one); ELIMINATION, a term refused by the sort discipline (R10:
    one); and CONVERSION, [eq_refl] refused with a "cannot unify"
    parenthetical, every statement being well typed (the other
    twenty-five).  Each CONVERSION refusal also has a CAUSE.  STRUCTURAL:
    the two sides differ in their data, or one side is stuck on variable
    data, and no measured flip of the tree changes that (R4, R5, R7, R8,
    R9, R11, R12, R13, R20 and R21: ten).  STRUCTURAL PAST THE STANDARD
    LIBRARY: the data converts, and the proof fields normalize, in the
    flip, to terms headed by or containing the standard library's opaque
    [CMorphisms.trans_co_eq_inv_arrow_morphism_obligation_1], which the
    [rewrite] inside [Compose]'s obligations leaves; unfolded by hand, its
    body is the variable setoid's transitivity after a reflexivity, which
    R13 refuses against its argument and C36 accepts at the Leibniz
    setoid of [bool] (R1, R1a, R1b, R1c, R2, R2a, R2b, R2c, R3, R14, R17,
    R18 and R19: thirteen; the normal form was read for R1a, R1b, R2a,
    R2b, the unit law behind R14, the join properness field behind R17
    and the functor laws behind R18 and R19, and is argued from the
    terms for the rest).  STDLIB OPACITY: the
    residue is built from opaque constants of the standard library, which
    no flip of the tree reaches (R15: one, of the kind of
    Test/ProbeMonadMorphism468.v's R12; the step that would make it hold,
    Instance/Sets.v's properness fields given as terms, is argued here,
    not measured).  OPACITY: refused in the tree and accepted in the flip
    (R16: one).

    THE FLIPS.  The copy: the dependency closure of the targets' drafts
    with [Transparent Obligations] set and every [Qed] turned into
    [Defined], obligations included, but in Instance/Sets.v,
    Instance/Discrete/Reconstruct.v, Structure/Limit/Preservation.v and
    Structure/Cartesian/Closed.v, the four files Instance/Top/
    Monadicity.v's header names with its reasons; Instance/Sets.v's hom
    setoid equivalence and [setoid_morphism_compose_respects] made
    transparent there.  The instrument: [About] reports the obligations
    of [Compose], [Id], [PForget], [PDisc], [EM_Forget], [Incl] and
    [Pos_Forget] "transparent" in the copy and "opaque" in the tree.  The
    two Pos files there have no universe annotations, so the twenty-seven
    strip copies of this file were compiled there with every universe
    annotation removed, and, in the six copies of the commands that follow
    R16 (R17, R4, R11, R5, R6 and R10), with R16 blanked, since it is
    accepted there.  Twenty-six are refused there inside the stripped
    command, each with the text of the tree; R16 is accepted.  For R16,
    three further copies of the copy each make one group of obligations
    opaque again and rebuild what depends on it: [Compose]'s
    (Theory/Functor.v), [Incl]'s (Construction/Subcategory.v) and
    [Pos_Forget]'s (Instance/Pos.v).  R16 is refused in each, with the
    text of the tree; [About] on [Compose_obligation_1] to
    [Compose_obligation_3], [Incl_obligation_1] and
    [Pos_Forget_obligation_1] reports each group "opaque" in exactly its
    own copy.

    LABELS.  The labels are not constants: each refutation and each
    control carries its label in a comment on the line above it, and the
    labels are stable identifiers that the five files' headers and
    docs/INDEX.md cite.  C1 to C22 and R1 to R3 (with R1a, R1b, R1c, R2a,
    R2b and R2c) pin the Top files; C23 to C35 and R4 to R12 the Pos and
    PropSets files; C36 and R13 the hand-unfolded residue behind R1 to
    R3; C37 and C38 the stronger readbacks [PDiscMonad_fields] and
    [PDiscK_alg]; C39 with R14 and R15 two further boundaries of the Top
    comparison; C40 to C51 the remaining readbacks of the two Pos files;
    R16 to R19 the opacity and structural boundaries of the Pos
    constructions (the truncation monad, its factoring, [PosDisc]);
    R20, R21 and C52 the absence of η for [sigT], cited by both Pos
    files; C53 and C54 the principle under Instance/Sets/Classifier/
    OneLevel.v's names; and C55 the monad Id ⊣ Id induces, cited by
    Monad/Identity.v.  C1 is [p469_c1_fobj_field], C2
    [p469_c2_fmap_field], C3 [p469_c3_forget_fobj_field], C4
    [p469_c4_forget_fmap_field], C5 [p469_c5_id_fobj], C6
    [p469_c6_id_fmap], C7 [p469_c7_id_ret], C8 [p469_c8_id_join], C9
    [p469_c9_em_unit_legs], C10 [p469_c10_T_fobj], C11
    [p469_c11_T_fmap], C12 [p469_c12_unit], C13 [p469_c13_counit], C14
    [p469_c14_ret], C15 [p469_c15_join], C16 [p469_c16_hom_components],
    C17 [p469_c17_iso_components], C18 [p469_c18_forget_obj], C19
    [p469_c19_forget_map], C20 [p469_c20_strict_obj], C21
    [p469_c21_KI_forget], C22 [p469_c22_KI_alg], C23
    [p469_c23_incl_fobj], C24 [p469_c24_trunc_unit], C25
    [p469_c25_factor_obj], C26 [p469_c26_TPosP_setoid], C27
    [p469_c27_MPosP_ret], C28 [p469_c28_to_Id_component], C29
    [p469_c29_TPos_fobj], C30 [p469_c30_TPos_carrier], C31
    [p469_c31_MPos_ret], C32 [p469_c32_PosDisc_obj], C33
    [p469_c33_TPos_equiv], C34 [p469_c34_TPosP_pequiv], C35
    [p469_c35_pair_setoid], C36 [p469_c36_unfolded_bool], C37
    [p469_c37_monad_fields], C38 [p469_c38_K_alg], C39
    [p469_c39_K_free_parts], C40 [p469_c40_incl_fmap], C41
    [p469_c41_lift_obj], C42 [p469_c42_lift_map], C43
    [p469_c43_trunc_counit], C44 [p469_c44_factor_map], C45
    [p469_c45_TPosP_fmap], C46 [p469_c46_MPosP_join], C47
    [p469_c47_Id_to_component], C48 [p469_c48_disc_le], C49
    [p469_c49_PosDisc_map], C50 [p469_c50_TPos_fmap], C51
    [p469_c51_MPos_join], C52 [p469_c52_setoid_eta], C53
    [p469_c53_untr_iem_unfold], C54 [p469_c54_iem_routes] and C55
    [p469_c55_IdId_monad].  R1 is [p469_r1_functor_eq], R1a
    [p469_r1a_fmap_respects], R1b [p469_r1b_fmap_id], R1c
    [p469_r1c_fmap_comp], R2 [p469_r2_forget_eq], R2a
    [p469_r2a_fmap_respects], R2b [p469_r2b_fmap_id], R2c
    [p469_r2c_fmap_comp], R3 [p469_r3_monad_eq], R4 [p469_r4_TPos_obj],
    R5 [p469_r5_TPos_eq], R6 [p469_r6_MPos_ret], R7 [p469_r7_pair_obj],
    R8 [p469_r8_TPosP_eq], R9 [p469_r9_monads_eq], R10
    [p469_r10_naive_elim], R11 [p469_r11_TPos_equiv], R12
    [p469_r12_pequiv], R13 [p469_r13_unfolded_variable], R14
    [p469_r14_K_free_obj], R15 [p469_r15_KI_alg_setoid], R16
    [p469_r16_TPos_trunc_eq], R17 [p469_r17_trunc_monads_eq], R18
    [p469_r18_factor_eq], R19 [p469_r19_PosDisc_eq], R20
    [p469_r20_variable_obj] and R21 [p469_r21_sigT_eta].

    RESTATEMENTS.  A control restates a readback when the two are the same
    statement under this file's names, the control perhaps pairing it with
    another, or agree once the functors and categories they name are
    unfolded, over the same variables.  Monad/Identity.v: [IdMonad_fobj]
    C5, [IdMonad_fmap] C6, [IdMonad_ret] C7, [IdMonad_join] C8 and
    [IdMonad_EM_unit_iso_id] C9.  Instance/Top/Monadicity.v:
    [PDiscT_fobj] C10, [PDiscT_fmap] C11, [PDiscT_fields] C1 and C2,
    [PDisc_PForget_unit] C12, [PDisc_PForget_counit] C13,
    [PDiscMonad_ret] C14, [PDiscMonad_join] C15, [PDiscMonad_fields] C37,
    [disc_id_hom_component] and [id_disc_hom_component] C16,
    [PDiscK_forget_obj] C18, [PDiscK_forget_map] C19, [PDiscK_alg] C38,
    [PDiscKI_forget_obj] and [PDiscKI_forget_map] C21 and [PDiscKI_alg]
    C22.  Instance/Sets/Propositional/Full.v: [PropSets_Incl_fobj] C23,
    [PropSets_Incl_fmap] C40, [PropSets_lift_obj] C41,
    [PropSets_lift_map] C42, [PropSets_trunc_unit] C24 and
    [PropSets_trunc_counit] C43.  Instance/Pos/Monadicity.v:
    [Pos_Forget_factor_obj] C25, [Pos_Forget_factor_map] C44,
    [TPosP_setoid] C26, [TPosP_fmap] C45, [TPosP_pequiv] C34,
    [MPosP_ret] C27, [MPosP_join] C46, [MPosP_to_Id_component] C28,
    [Id_to_MPosP_component] C47, [PosDiscObj_le] C48, [PosDisc_obj] C32,
    [PosDisc_map] C49, [TPos_fobj] C29, [TPos_fmap] C50, [TPos_carrier]
    C30, [TPos_equiv] C33, [MPos_ret] C31 and [MPos_join] C51.
    Forty-five readbacks, each named once.  C3, C4, C17, C20, C35, C36,
    C39, C52, C53, C54 and C55 restate no readback: they are the twins of
    refusals, or read the computational content of a constant closed by
    [Defined], or measure a route the targets do not take.

    ** Monad/Identity.v

    Controls, at [eq_refl]: [IdMonad C] is the identity on objects and
    arrows, with unit and multiplication [id] (C5 to C8); both legs of the
    unit isomorphism of [IdMonad_EM_equivalence] at an algebra are [id]
    (C9).  At the end of this file, under its three extra lines for it:
    the monad Id ⊣ Id induces has unit and multiplication [id] (C55).

    ** Instance/Top/Monadicity.v: the induced monad

    Controls, at [eq_refl]: the [fobj] and [fmap] fields of
    PDiscT = PForget ◯ PDisc and of Id[Sets] (C1, C2); PDiscT on objects
    and arrows (C10, C11); the unit of [PDisc_PForget] is [id] and its
    counit the identity on points (C12, C13); the unit and multiplication
    of the induced monad are [id] (C14, C15), as functions too (C37).
    R1 (CONVERSION, STRUCTURAL PAST THE STANDARD LIBRARY).  The functor
    equation:
      (cannot unify "PDiscT" and "Id[Sets]")
    R1a, R1b, R1c (the same).  Its three proof fields, one at a time:
      (cannot unify "@fmap_respects _ _ PDiscT" and
      "@fmap_respects _ _ Id[Sets]")
      (cannot unify "@fmap_id _ _ PDiscT" and "@fmap_id _ _ Id[Sets]")
      (cannot unify "@fmap_comp _ _ PDiscT" and
      "@fmap_comp _ _ Id[Sets]")
    Control: the standard library's obligation body, transitivity after a
    reflexivity, converts with its argument at the Leibniz setoid of
    [bool] (C36).
    R13 (CONVERSION, STRUCTURAL).  The same at a variable setoid of
    [Sets]:
      (cannot unify "λ (x y : obj[Sets]) (x0 y0 : x ~{ Sets }~> y)
      (X : ∀ x1 : x, x0 x1 ≈ y0 x1) (x2 : x), transitivity (X x2)
      (reflexivity (y0 x2))" and "λ (x y : obj[Sets])
      (x0 y0 : x ~{ Sets }~> y) (X : ∀ x1 : x, x0 x1 ≈ y0 x1) (x2 : x),
      X x2")

    ** Instance/Top/Monadicity.v: the isomorphism in [Monads Sets]

    Controls, at [eq_refl]: both morphisms of monads, and both legs of
    [disc_id_iso], have identity components (C16, C17).
    R3 (CONVERSION, STRUCTURAL PAST THE STANDARD LIBRARY).  The two
    monads as equal objects of [Monads Sets]:
      (cannot unify "(PDiscT; PDiscMonad)" and "(Id[Sets]; IdMonad Sets)")

    ** Instance/Top/Monadicity.v: the comparison functor

    Controls, at [eq_refl]: the [fobj] and [fmap] fields of
    EM_Forget ◯ PDiscK and of PForget (C3, C4); K X has carrier PForget X
    (C18) and K f underlying arrow PForget f (C19); the object equation of
    [PDiscK_forget_strict] IS [eq_refl] (C20); the structure map of K X is
    the identity setoid morphism itself (C38).
    R2 (CONVERSION, STRUCTURAL PAST THE STANDARD LIBRARY).  The book's
    "the comparison functor is the given forgetful functor G", Leibniz:
      (cannot unify "EM_Forget PDiscT ◯ PDiscK" and "PForget")
    R2a, R2b, R2c (the same).  Its three proof fields, one at a time:
      (cannot unify "@fmap_respects _ _ (@EM_Forget Sets PDiscT
      PDiscMonad ◯ PDiscK)" and "@fmap_respects _ _ PForget")
      (cannot unify "@fmap_id _ _ (EM_Forget PDiscT ◯ PDiscK)" and
      "@fmap_id _ _ PForget")
      (cannot unify "@fmap_comp _ _ (EM_Forget PDiscT ◯ PDiscK)" and
      "@fmap_comp _ _ PForget")

    ** Instance/Top/Monadicity.v: Set^I = Set

    Control: K X and EM_Free (PForget X) have one carrier and one
    structure map (C39).
    R14 (CONVERSION, STRUCTURAL PAST THE STANDARD LIBRARY).  The two
    algebras, whole, so [PDiscK_free] is ≈ and no more:
      (cannot unify "fobj[PDiscK] X" and "fobj[EM_Free PDiscT ◯ PForget]
      X")
    Controls: KI after the forgetful functor is PForget on objects and
    arrows (C21), and the structure map of KI X is the identity function
    (C22).
    R15 (CONVERSION, STDLIB OPACITY).  That structure map as a setoid
    morphism, so [PDiscKI_alg] is pointwise and no more:
      (cannot unify "t_alg[projT2 (fobj[PDiscKI] X)]" and
      "setoid_morphism_id")

    ** Instance/Sets/Propositional/Full.v

    Controls, at [eq_refl]: the inclusion is the first projection on
    objects and arrows (C23, C40); [PropSets_lift F P] keeps F's objects
    and arrows in its first components (C41, C42); the unit and the
    counit of the reflection are identity functions (C24, C43).

    ** Instance/Pos/Monadicity.v: [Pos_Forget] through [PropSets]

    Controls, at [eq_refl]: PropSets_Incl ◯ PosPForget is Pos_Forget on
    objects (C25) and, on first projections, on arrows (C44).
    R18 (CONVERSION, STRUCTURAL PAST THE STANDARD LIBRARY).  The functor
    equation, so [Pos_Forget_factor] is ≈ and no more:
      (cannot unify "PropSets_Incl ◯ PosPForget" and "Pos_Forget")

    ** Instance/Pos/Monadicity.v: over [PropSets]

    Controls, at [eq_refl]: TPosP keeps the setoid of an object (C26) and
    the function of an arrow (C45); its [PropEquiv] witness is recomputed
    as the two-way order (C34); at a pair (S; P) the first components
    agree (C35); the unit and multiplication are identity functions (C27,
    C46), and so are the components of both morphisms of monads (C28,
    C47).
    R7 (CONVERSION, STRUCTURAL).  "X = UF(X)" at a pair (S; P):
      (cannot unify "fobj[TPosP] (S; P)" and "(S; P)")
    R12 (CONVERSION, STRUCTURAL).  Its cause, the recomputed witness:
      (cannot unify "@pequiv _ _ (@projT2 obj[Sets] (λ x : obj[Sets],
      sobj _ PropSets_sub x) (fobj[TPosP] X)) x y" and
      "@pequiv _ _ `2 (X) x y")
    R20 (CONVERSION, STRUCTURAL).  The same at a variable object:
      (cannot unify "fobj[TPosP] X" and "X")
    R8 (CONVERSION, STRUCTURAL).  The functor equation:
      (cannot unify "TPosP" and "Id[PropSets]")
    R9 (CONVERSION, STRUCTURAL).  The two monads as equal objects of
    [Monads PropSets]:
      (cannot unify "(TPosP; MPosP)" and "(Id[PropSets]; IdMonad
      PropSets)")
    Control: a [SetoidObject], a record with primitive projections,
    converts with its rebuilt record (C52).
    R21 (CONVERSION, STRUCTURAL).  A variable of [PropSets], a [sigT],
    against its rebuilt pair: [sigT] has no η:
      (cannot unify "X" and "(`1 (X); `2 (X))")

    ** Instance/Pos/Monadicity.v: over [Sets]

    Controls, at [eq_refl]: the discrete order is the truncated ≈ (C48);
    [PosDisc] is [PosDiscP] after the reflector on objects and arrows
    (C32, C49).
    R19 (CONVERSION, STRUCTURAL PAST THE STANDARD LIBRARY).  As functors:
      (cannot unify "PosDisc" and "PosDiscP ◯ PropSets_trunc")
    Controls: TPos is the reflection's functor on objects and arrows (C29,
    C50).
    R16 (CONVERSION, OPACITY).  As functors:
      (cannot unify "TPos" and "PropSets_Incl ◯ PropSets_trunc")
    R17 (CONVERSION, STRUCTURAL PAST THE STANDARD LIBRARY).  (TPos; MPos)
    and the monad of the reflection as equal objects of [Monads Sets]:
      (cannot unify "(TPos; MPos)" and "(PropSets_Incl ◯ PropSets_trunc;
      Adjunction_Induced_Monad PropSets_trunc_Incl)")
    Controls: TPos keeps the carrier (C30), and its ≈ is the truncation
    of S's (C33).
    R4 (CONVERSION, STRUCTURAL).  "X = UF(X)" as setoids:
      (cannot unify "fobj[TPos] S" and "S")
    R11 (CONVERSION, STRUCTURAL).  Its cause:
      (cannot unify "@equiv _ (is_setoid (@fobj _ _ TPos S)) x y" and
      "@equiv _ (is_setoid S) x y")
    R5 (CONVERSION, STRUCTURAL).  The functor equation:
      (cannot unify "TPos" and "Id[Sets]")
    Controls: the unit and multiplication are identity functions (C31,
    C51).
    R6 (TYPING).  The unit against [id], ill-typed because fobj[TPos] S
    does not convert with S (R4):
      The term "id{?Category}" has type "?x ~{ ?Category }~> ?x" while it
      is expected to have type "S ~{ Sets }~> fobj[TPos] S".
    R10 (ELIMINATION).  The naive elimination of the truncation, the one
    step [SetsTruncElim] supplies and the key step of the normal-form
    argument in Instance/Pos/Monadicity.v's header:
      Incorrect elimination of "H" in the inductive type "inhabited": the
      return type has sort "Type" while it should be SProp or Prop.
    At the end of this file, under its extra line for them: OneLevel.v's
    [Untruncate@{c}] and [IEM@{c}] are the written-out hypotheses of
    [choice_of_untr] and [choice_of_IEM] (C53), and under [IEM@{c}] the
    induced monad is the identity monad both by [MPos_IEM_Id_iso] and
    through [untruncate_of_IEM] and [choice_of_untr] (C54).

    NOT PINNED HERE.  (a) [About] readbacks as such: the headers'
    universe censuses and their attributions to first carriers and caps.
    (b) The flips and copies above, and the normal-form readings behind
    the CAUSEs: made in copies of the dependency closure and in scratch
    files.  (c) The closure of the targets under [Print Assumptions]: a
    measurement of the build rather than of a command; the Makefile's
    print-assumptions gate names all one hundred and seventy-two names
    below.  (d) The absences the headers record (no initiality of
    [IdMonad] in [Monads C], no isomorphism in Instance/StrictCat.v, no
    left adjoint of the Type-valued [Top_Forget], no Eilenberg-Moore
    equivalence for [MPos], no comparison-functor readbacks for the two
    Pos adjunctions): an absence has no command.  (e) The
    dependency-closure counts and [Require] costs the headers give,
    measured by script.  (f) The readings of the books, from the page
    images.  (g) Metatheory: that ∀ A, inhabited A → A has no axiom-free
    proof is an argument, whose key step R10 pins; its consistency, by
    the standard library's [constructive_indefinite_description], was
    compiled in a scratch file, since no constant of the tree may carry
    an axiom.

    The guard block, which only controls C53 to C55 and their four
    [Require] lines follow, names the one hundred and seventy-two names of
    the five targets, so that a rename breaks this file: eleven constants
    of Monad/Identity.v, forty-four of Instance/Top/Monadicity.v, three of
    Instance/Top/Monadicity/TypeValued.v, twenty-nine of
    Instance/Sets/Propositional/Full.v and eighty-five of
    Instance/Pos/Monadicity.v.  They are exactly the entries [Print
    Module] gives for each, among them the twelve [Program] obligations
    of [PropSets_trunc_iso], [posdiscP_iso] and [posdisc_iso]; no target
    declares a record, so there is no constructor to add.  Each is written
    fully qualified and with [@], so that no short name in scope can stand
    in for it. *)

Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Monad.
Require Import Category.Theory.Equivalence.
Require Import Category.Monad.Algebra.
Require Import Category.Monad.Eilenberg.Moore.
Require Import Category.Monad.Eilenberg.Moore.Adjunction.
Require Import Category.Monad.Identity.
Require Import Category.Theory.Natural.Transformation.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Equivalence.FullFaithful.
Require Import Category.Structure.Limit.Preservation.
Require Import Category.Monad.Comparison.
Require Import Category.Monad.Morphism.
Require Import Category.Monad.Morphism.Algebra.
Require Import Category.Monad.Monadicity.BeckObjects.
Require Import Category.Instance.Cat.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Top.Prop.
Require Import Category.Instance.Top.Complete.
Require Import Category.Instance.Top.Cocomplete.
Require Import Category.Instance.Top.Monadicity.
Require Import Category.Instance.Top.
Require Import Category.Instance.Top.Forgetful.
Require Import Category.Instance.Top.Monadicity.TypeValued.
Require Import Category.Lib.Setoid.Propositional.
Require Import Category.Construction.Subcategory.
Require Import Category.Construction.Reflective.
Require Import Category.Instance.Sets.Propositional.
Require Import Category.Instance.Sets.Propositional.Full.
Require Import Category.Construction.Reflective.Monadic.
Require Import Category.Instance.Pos.
Require Import Category.Instance.Proset.Monotone.
Require Import Category.Instance.Pos.Monadicity.

Generalizable All Variables.

(* ------------------------------------------------------------------------ *)
(** ** Monad/Identity.v *)

(* C5: the functor of [IdMonad C] is the identity on objects. *)
Example p469_c5_id_fobj@{o h | +} (C : Category@{o h h}) (x : C) :
  @fobj C C Id[C] x = x := eq_refl.

(* C6: and on arrows. *)
Example p469_c6_id_fmap@{o h | +} (C : Category@{o h h}) (x y : C)
  (f : x ~> y) : @fmap C C Id[C] x y f = f := eq_refl.

(* C7: its unit is [id]. *)
Example p469_c7_id_ret@{o h | +} (C : Category@{o h h}) (x : C) :
  @ret C Id[C] (IdMonad@{o h} C) x = @id C x := eq_refl.

(* C8: its multiplication is [id]. *)
Example p469_c8_id_join@{o h | +} (C : Category@{o h h}) (x : C) :
  @join C Id[C] (IdMonad@{o h} C) x = @id C x := eq_refl.

(* C9: both legs of the unit isomorphism at an algebra are [id]. *)
Example p469_c9_em_unit_legs@{o h s e | h < s, o <= e, h <= e +}
  (C : Category@{o h h})
  (X : @EilenbergMoore@{e o s h} C Id[C] (IdMonad@{o h} C)) :
  (@t_alg_hom _ _ _ _ _ _ _ (to (IdMonad_EM_unit_iso@{o h s e} C X)),
   @t_alg_hom _ _ _ _ _ _ _ (from (IdMonad_EM_unit_iso@{o h s e} C X)))
    = (@id C (`1 X), @id C (`1 X)) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Top/Monadicity.v: the induced monad *)

(* C1: the [fobj] fields of PDiscT and Id[Sets]. *)
Example p469_c1_fobj_field@{o so s | o < so, o < s +} :
  @fobj _ _ PDiscT@{o so s} = @fobj _ _ Id[Sets@{o so}] := eq_refl.

(* C2: their [fmap] fields. *)
Example p469_c2_fmap_field@{o so s | o < so, o < s +} :
  @fmap _ _ PDiscT@{o so s} = @fmap _ _ Id[Sets@{o so}] := eq_refl.

(* C10: PForget ◯ PDisc is the identity on objects. *)
Example p469_c10_T_fobj@{o so s | o < so, o < s +} (x : Sets@{o so}) :
  fobj[PForget@{o so} ◯ PDisc@{o so}] x = x := eq_refl.

(* C11: and on arrows. *)
Example p469_c11_T_fmap@{o so s | o < so, o < s +} (x y : Sets@{o so})
  (f : x ~> y) : fmap[PForget@{o so} ◯ PDisc@{o so}] f = f := eq_refl.

(* C12: the unit of the adjunction is the identity arrow. *)
Example p469_c12_unit@{o so u u0 | o < so, o < u +} (x : Sets@{o so}) :
  @Category.Theory.Adjunction.unit _ _ _ _ PDisc_PForget@{o so u u0} x
    = @id Sets@{o so} x := eq_refl.

(* C13: the counit at a space is the identity on its points. *)
Example p469_c13_counit@{o so u u0 | o < so, o < u +}
  (X : PTopCat@{o so}) :
  pmap (@Category.Theory.Adjunction.counit _ _ _ _
          PDisc_PForget@{o so u u0} X) = setoid_morphism_id := eq_refl.

(* C14: the unit of the induced monad is [id]. *)
Example p469_c14_ret@{o so s u u0 | o < so, o < s, o < u +}
  (x : Sets@{o so}) :
  @ret _ _ (@Adjunction_Induced_Monad _ _ _ _ PDisc_PForget@{o so u u0}) x
    = @id Sets@{o so} x := eq_refl.

(* C15: its multiplication is [id]. *)
Example p469_c15_join@{o so s u u0 | o < so, o < s, o < u +}
  (x : Sets@{o so}) :
  @join _ _ (@Adjunction_Induced_Monad _ _ _ _ PDisc_PForget@{o so u u0}) x
    = @id Sets@{o so} x := eq_refl.

(* C37: its unit and multiplication, as functions, are those of the
   identity monad. *)
Example p469_c37_monad_fields@{o so s u u0 | o < so, o < s, o < u +} :
  (@ret _ _ (@Adjunction_Induced_Monad _ _ _ _ PDisc_PForget@{o so u u0}),
   @join _ _ (@Adjunction_Induced_Monad _ _ _ _ PDisc_PForget@{o so u u0}))
    = ((fun x : Sets@{o so} => @id Sets@{o so} x),
       (fun x : Sets@{o so} => @id Sets@{o so} x)) := eq_refl.

(* R1 *)
Fail Example p469_r1_functor_eq@{o so s | o < so, o < s +} :
  PDiscT@{o so s} = Id[Sets@{o so}] := eq_refl.

(* R1a *)
Fail Example p469_r1a_fmap_respects@{o so s | o < so, o < s +} :
  @fmap_respects _ _ PDiscT@{o so s} = @fmap_respects _ _ Id[Sets@{o so}]
  := eq_refl.

(* R1b *)
Fail Example p469_r1b_fmap_id@{o so s | o < so, o < s +} :
  @fmap_id _ _ PDiscT@{o so s} = @fmap_id _ _ Id[Sets@{o so}] := eq_refl.

(* R1c *)
Fail Example p469_r1c_fmap_comp@{o so s | o < so, o < s +} :
  @fmap_comp _ _ PDiscT@{o so s} = @fmap_comp _ _ Id[Sets@{o so}]
  := eq_refl.

(* C36: at the Leibniz setoid of [bool], the body of the standard
   library's obligation behind R1a, transitivity after a reflexivity,
   converts with its argument. *)
Example p469_c36_unfolded_bool@{o so | o < so +} :
  (fun (x0 y0 : bool_setoid_object@{o o} ~{Sets@{o so}}~>
                  bool_setoid_object@{o o})
       (X : ∀ x1 : bool, x0 x1 ≈ y0 x1) (x2 : bool) =>
     @transitivity _ _ _ (x0 x2) (y0 x2) (y0 x2) (X x2)
       (@reflexivity _ _ _ (y0 x2)))
  = (fun (x0 y0 : bool_setoid_object@{o o} ~{Sets@{o so}}~>
                    bool_setoid_object@{o o})
         (X : ∀ x1 : bool, x0 x1 ≈ y0 x1) (x2 : bool) => X x2) := eq_refl.

(* R13 *)
Fail Example p469_r13_unfolded_variable@{o so | o < so +} :
  (fun (x y : Sets@{o so}) (x0 y0 : x ~> y) (X : ∀ x1 : x, x0 x1 ≈ y0 x1)
       (x2 : x) =>
     @transitivity _ _ _ (x0 x2) (y0 x2) (y0 x2) (X x2)
       (@reflexivity _ _ _ (y0 x2)))
  = (fun (x y : Sets@{o so}) (x0 y0 : x ~> y) (X : ∀ x1 : x, x0 x1 ≈ y0 x1)
         (x2 : x) => X x2) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Top/Monadicity.v: the isomorphism in [Monads Sets] *)

(* C16: both morphisms of monads have identity components. *)
Example p469_c16_hom_components@{o so s u u0 | o < so, o < s, o < u +}
  (x : Sets@{o so}) :
  (transform[mh_transform disc_id_hom@{o so s u u0}] x,
   transform[mh_transform id_disc_hom@{o so s u u0}] x)
    = (@id Sets@{o so} x, @id Sets@{o so} x) := eq_refl.

(* C17: so have the two legs of the isomorphism. *)
Example p469_c17_iso_components@{o so s u u0 m1 m2 |
  o < so, o < s, o < u, so <= m1, o <= m1, so <= m2, o <= m2 +}
  (x : Sets@{o so}) :
  (transform[mh_transform (to disc_id_iso@{o so s u u0 m1 m2})] x,
   transform[mh_transform (from disc_id_iso@{o so s u u0 m1 m2})] x)
    = (@id Sets@{o so} x, @id Sets@{o so} x) := eq_refl.

(* R3 *)
Fail Example p469_r3_monad_eq@{o so s u u0 | o < so, o < s, o < u +} :
  existT (fun T : Sets@{o so} ⟶ Sets@{o so} => @Monad Sets@{o so} T)
    PDiscT@{o so s} PDiscMonad@{o so s u u0}
  = existT (fun T : Sets@{o so} ⟶ Sets@{o so} => @Monad Sets@{o so} T)
    Id[Sets@{o so}] (IdMonad@{so o} Sets@{o so}) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Top/Monadicity.v: the comparison functor *)

(* C3: the [fobj] fields of EM_Forget ◯ K and PForget. *)
Example p469_c3_forget_fobj_field@{o so s u u0 e |
  o < so, o < s, o < u, so <= e +} :
  @fobj _ _ (EM_Forget _ ◯ PDiscK@{o so s u u0 e}) = @fobj _ _ PForget@{o so}
  := eq_refl.

(* C4: their [fmap] fields. *)
Example p469_c4_forget_fmap_field@{o so s u u0 e |
  o < so, o < s, o < u, so <= e +} :
  @fmap _ _ (EM_Forget _ ◯ PDiscK@{o so s u u0 e}) = @fmap _ _ PForget@{o so}
  := eq_refl.

(* C18: the carrier of K X is PForget X. *)
Example p469_c18_forget_obj@{o so s u u0 e |
  o < so, o < s, o < u, so <= e +} (X : PTopCat@{o so}) :
  `1 (fobj[EM_Comparison PDisc_PForget@{o so u u0}] X) = fobj[PForget@{o so}] X
  := eq_refl.

(* C19: the underlying arrow of K f is PForget f. *)
Example p469_c19_forget_map@{o so s u u0 e |
  o < so, o < s, o < u, so <= e +} (X Y : PTopCat@{o so}) (f : X ~> Y) :
  t_alg_hom[fmap[EM_Comparison PDisc_PForget@{o so u u0}] f]
    = fmap[PForget@{o so}] f := eq_refl.

(* C20: the object equation of [PDiscK_forget_strict] IS [eq_refl]. *)
Example p469_c20_strict_obj@{o so s u u0 e a b |
  o < so, o < s, o < u, so <= e, o < b, so <= a, o <= a +}
  (X : PTopCat@{o so}) :
  `1 PDiscK_forget_strict@{o so s u u0 e a b} X = eq_refl := eq_refl.

(* C38: the structure map of K X is the identity setoid morphism. *)
Example p469_c38_K_alg@{o so s u u0 e | o < so, o < s, o < u, so <= e +}
  (X : PTopCat@{o so}) :
  t_alg[`2 (fobj[EM_Comparison PDisc_PForget@{o so u u0}] X)]
    = @setoid_morphism_id (pt_carrier X) := eq_refl.

(* R2 *)
Fail Example p469_r2_forget_eq@{o so s u u0 e |
  o < so, o < s, o < u, so <= e +} :
  EM_Forget _ ◯ PDiscK@{o so s u u0 e} = PForget@{o so} := eq_refl.

(* R2a *)
Fail Example p469_r2a_fmap_respects@{o so s u u0 e |
  o < so, o < s, o < u, so <= e +} :
  @fmap_respects _ _ (EM_Forget _ ◯ PDiscK@{o so s u u0 e})
    = @fmap_respects _ _ PForget@{o so} := eq_refl.

(* R2b *)
Fail Example p469_r2b_fmap_id@{o so s u u0 e |
  o < so, o < s, o < u, so <= e +} :
  @fmap_id _ _ (EM_Forget _ ◯ PDiscK@{o so s u u0 e})
    = @fmap_id _ _ PForget@{o so} := eq_refl.

(* R2c *)
Fail Example p469_r2c_fmap_comp@{o so s u u0 e |
  o < so, o < s, o < u, so <= e +} :
  @fmap_comp _ _ (EM_Forget _ ◯ PDiscK@{o so s u u0 e})
    = @fmap_comp _ _ PForget@{o so} := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Top/Monadicity.v: Set^I = Set *)

(* C39: K X and EM_Free (PForget X) have one carrier and one structure
   map. *)
Example p469_c39_K_free_parts@{o so s u u0 e |
  o < so, o < s, o < u, so <= e +} (X : PTopCat@{o so}) :
  (`1 (fobj[PDiscK@{o so s u u0 e}] X),
   t_alg[`2 (fobj[PDiscK@{o so s u u0 e}] X)])
    = (`1 (fobj[@EM_Free@{so o s e} Sets@{o so} PDiscT@{o so s}
                 PDiscMonad@{o so s u u0} ◯ PForget@{o so}] X),
       t_alg[`2 (fobj[@EM_Free@{so o s e} Sets@{o so} PDiscT@{o so s}
                       PDiscMonad@{o so s u u0} ◯ PForget@{o so}] X)])
  := eq_refl.

(* R14 *)
Fail Example p469_r14_K_free_obj@{o so s u u0 e |
  o < so, o < s, o < u, so <= e +} (X : PTopCat@{o so}) :
  fobj[PDiscK@{o so s u u0 e}] X
    = fobj[@EM_Free@{so o s e} Sets@{o so} PDiscT@{o so s}
             PDiscMonad@{o so s u u0} ◯ PForget@{o so}] X := eq_refl.

(* C21: KI after the forgetful functor is PForget on objects and arrows. *)
Example p469_c21_KI_forget@{o so s u u0 e |
  o < so, o < s, o < u, so <= e +} (X Y : PTopCat@{o so}) (f : X ~> Y) :
  (`1 (fobj[PDiscKI@{o so s u u0 e}] X),
   t_alg_hom[fmap[PDiscKI@{o so s u u0 e}] f])
    = (fobj[PForget@{o so}] X, fmap[PForget@{o so}] f) := eq_refl.

(* C22: the structure map of KI X is the identity function. *)
Example p469_c22_KI_alg@{o so s u u0 e | o < so, o < s, o < u, so <= e +}
  (X : PTopCat@{o so}) (x : X) :
  t_alg[`2 (fobj[mh_EM@{so o e s} id_disc_hom@{o so s u u0}
                   ◯ EM_Comparison PDisc_PForget@{o so u u0}] X)] x = x
  := eq_refl.

(* R15 *)
Fail Example p469_r15_KI_alg_setoid@{o so s u u0 e |
  o < so, o < s, o < u, so <= e +} (X : PTopCat@{o so}) :
  t_alg[`2 (fobj[PDiscKI@{o so s u u0 e}] X)] = setoid_morphism_id
  := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Sets/Propositional/Full.v *)

(* C23: the inclusion is the first projection on objects. *)
Example p469_c23_incl_fobj@{o so | o < so +} (X : PropSets@{o so}) :
  fobj[PropSets_Incl@{o so}] X = projT1 X := eq_refl.

(* C40: and on arrows. *)
Example p469_c40_incl_fmap@{o so | o < so +} (X Y : PropSets@{o so})
  (f : X ~{PropSets@{o so}}~> Y) :
  fmap[Incl@{so o so o so so} Sets@{o so} PropSets_sub@{o so}] f = `1 f
  := eq_refl.

(* C41: [PropSets_lift F P] keeps F's object in its first component. *)
Example p469_c41_lift_obj@{co o so | o < so +}
  {C : Category@{co o o}} (F : C ⟶ Sets@{o so})
  (P : ∀ c : C, PropEquivObj@{so o o} (F c)) (c : C) :
  projT1 (fobj[PropSets_lift@{co o o so} F P] c) = fobj[F] c := eq_refl.

(* C42: and F's arrow. *)
Example p469_c42_lift_map@{co o so | o < so +}
  {C : Category@{co o o}} (F : C ⟶ Sets@{o so})
  (P : ∀ c : C, PropEquivObj@{so o o} (F c)) (x y : C) (f : x ~> y) :
  projT1 (fmap[PropSets_lift@{co o o so} F P] f) = fmap[F] f := eq_refl.

(* C24: the unit of the reflection is the identity function. *)
Example p469_c24_trunc_unit@{o so a | o < so +} (S : Sets@{o so}) :
  @Sets.morphism _ _ _ _
    (@Category.Theory.Adjunction.unit _ _ _ _
       PropSets_trunc_Incl@{o so a} S) = (fun x : carrier S => x)
  := eq_refl.

(* C43: so is its counit. *)
Example p469_c43_trunc_counit@{o so a | o < so +} (X : PropSets@{o so}) :
  @Sets.morphism _ _ _ _
    (projT1 (@Category.Theory.Adjunction.counit _ _ _ _
               PropSets_trunc_Incl@{o so a} X))
    = (fun x : carrier (projT1 X) => x) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Pos/Monadicity.v: [Pos_Forget] through [PropSets] *)

(* C25: PropSets_Incl ◯ PosPForget is Pos_Forget on objects. *)
Example p469_c25_factor_obj@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (P : Pos@{po p0 p1 p2 p3 c}) :
  fobj[PropSets_Incl@{c so} ◯ PosPForget@{c so po p0 p1 p2 p3}] P
    = fobj[Pos_Forget@{po so p0 p2 p1 p3 c}] P := eq_refl.

(* C44: and on arrows, read on first projections. *)
Example p469_c44_factor_map@{c so po p0 p1 p2 p3 |
  c < so, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +}
  (P Q : Pos@{po p0 p1 p2 p3 c}) (f : P ~{Pos@{po p0 p1 p2 p3 c}}~> Q) :
  projT1 (fmap[PosPForget@{c so po p0 p1 p2 p3}] f)
    = fmap[Pos_Forget@{po so p0 p2 p1 p3 c}] f := eq_refl.

(* R18 *)
Fail Example p469_r18_factor_eq@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} :
  PropSets_Incl@{c so} ◯ PosPForget@{c so po p0 p1 p2 p3}
    = Pos_Forget@{po so p0 p2 p1 p3 c} := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Pos/Monadicity.v: over [PropSets] *)

(* C26: the monad keeps the setoid of an object. *)
Example p469_c26_TPosP_setoid@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (X : PropSets@{c so}) :
  projT1 (fobj[TPosP@{c so po p0 p1 p2 p3 s}] X) = projT1 X := eq_refl.

(* C45: and the function of an arrow. *)
Example p469_c45_TPosP_fmap@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (X Y : PropSets@{c so})
  (f : X ~{PropSets@{c so}}~> Y) :
  projT1 (fmap[PosPForget@{c so po p0 p1 p2 p3}
               ◯ PosDiscP@{c so po p0 p1 p2 p3}] f) = projT1 f := eq_refl.

(* C34: its [PropEquiv] witness is recomputed as the two-way order. *)
Example p469_c34_TPosP_pequiv@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (X : PropSets@{c so}) (x y : carrier (projT1 X)) :
  @pequiv _ _ (projT2 (fobj[TPosP@{c so po p0 p1 p2 p3 s}] X)) x y
    = (@pequiv _ _ (projT2 X) x y /\ @pequiv _ _ (projT2 X) y x)
  := eq_refl.

(* C35: at a pair (S; P) the first components agree. *)
Example p469_c35_pair_setoid@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (S : Sets@{c so}) (P : PropEquivObj@{so c c} S) :
  projT1 (fobj[TPosP@{c so po p0 p1 p2 p3 s}]
            (existT _ S P : PropSets@{c so})) = S := eq_refl.

(* C27: the unit is the identity function. *)
Example p469_c27_MPosP_ret@{c so po p0 p1 p2 p3 s a |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (X : PropSets@{c so}) :
  projT1 (@ret _ _ MPosP@{c so po p0 p1 p2 p3 s a} X) = id := eq_refl.

(* C46: so is the multiplication. *)
Example p469_c46_MPosP_join@{c so po p0 p1 p2 p3 s a |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (X : PropSets@{c so}) :
  projT1 (@join _ _ (Adjunction_Induced_Monad
                       PosDiscP_PosPForget@{c so po p0 p1 p2 p3 a}) X)
    = id := eq_refl.

(* C28: the morphism of monads to the identity monad has identity
   components. *)
Example p469_c28_to_Id_component@{c so po p0 p1 p2 p3 s a |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (X : PropSets@{c so}) :
  projT1 (transform[mh_transform MPosP_to_Id@{c so po p0 p1 p2 p3 s a}] X)
    = id := eq_refl.

(* C47: so has the one back. *)
Example p469_c47_Id_to_component@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (X : PropSets@{c so}) :
  projT1 (transform[id_to_TPosP@{c so po p0 p1 p2 p3 s}] X) = id
  := eq_refl.

(* R7 *)
Fail Example p469_r7_pair_obj@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (S : Sets@{c so}) (P : PropEquivObj@{so c c} S) :
  fobj[TPosP@{c so po p0 p1 p2 p3 s}] (existT _ S P : PropSets@{c so})
    = (existT _ S P : PropSets@{c so}) := eq_refl.

(* R12 *)
Fail Example p469_r12_pequiv@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (X : PropSets@{c so}) (x y : carrier (projT1 X)) :
  @pequiv _ _ (projT2 (fobj[TPosP@{c so po p0 p1 p2 p3 s}] X)) x y
    = @pequiv _ _ (projT2 X) x y := eq_refl.

(* R20 *)
Fail Example p469_r20_variable_obj@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (X : PropSets@{c so}) :
  fobj[TPosP@{c so po p0 p1 p2 p3 s}] X = X := eq_refl.

(* R8 *)
Fail Example p469_r8_TPosP_eq@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} :
  TPosP@{c so po p0 p1 p2 p3 s} = Id[PropSets@{c so}] := eq_refl.

(* R9 *)
Fail Example p469_r9_monads_eq@{c so po p0 p1 p2 p3 s a m1 m2 |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1, so <= m1, c <= m1, so <= m2, c <= m2 +} :
  @eq (obj[Monads@{so c m1 m2} PropSets@{c so}])
    (existT _ TPosP@{c so po p0 p1 p2 p3 s} MPosP@{c so po p0 p1 p2 p3 s a})
    (existT _ Id[PropSets@{c so}] (IdMonad@{so c} PropSets@{c so}))
  := eq_refl.

(* C52: a [SetoidObject], a record with primitive projections, converts
   with its rebuilt record. *)
Example p469_c52_setoid_eta@{c | +} (S : SetoidObject@{c c}) :
  {| carrier := carrier S; is_setoid := is_setoid S |} = S := eq_refl.

(* R21 *)
Fail Example p469_r21_sigT_eta@{c so | c < so +} (X : PropSets@{c so}) :
  X = (existT _ (projT1 X) (projT2 X) : PropSets@{c so}) := eq_refl.

(* ------------------------------------------------------------------------ *)
(** ** Instance/Pos/Monadicity.v: over [Sets] *)

(* C48: the discrete order is the truncated ≈. *)
Example p469_c48_disc_le@{c so p0 p1 p2 p3 |
  c < so, Set < p2, p2 <= p0, p3 <= p1, c <= p0, c <= p1 +}
  (S : Sets@{c so}) (x y : carrier S) :
  pos_le (PosDiscPObj@{c so p0 p1 p2 p3} (PropSets_trunc@{c so} S)) x y
    = inhabited (x ≈ y) := eq_refl.

(* C32: [PosDisc] is [PosDiscP] after the reflector on objects. *)
Example p469_c32_PosDisc_obj@{c so po p0 p1 p2 p3 |
  c < so, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (S : Sets@{c so}) :
  fobj[PosDisc@{c so po p0 p1 p2 p3}] S
    = fobj[PosDiscP@{c so po p0 p1 p2 p3}] (fobj[PropSets_trunc@{c so}] S)
  := eq_refl.

(* C49: and on arrows. *)
Example p469_c49_PosDisc_map@{c so po p0 p1 p2 p3 |
  c < so, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (S T : Sets@{c so}) (f : S ~{Sets@{c so}}~> T) :
  fmap[PosDisc@{c so po p0 p1 p2 p3}] f
    = PosDiscP_fmap@{c so p0 p1 p2 p3} (fmap[PropSets_trunc@{c so}] f)
  := eq_refl.

(* R19 *)
Fail Example p469_r19_PosDisc_eq@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} :
  PosDisc@{c so po p0 p1 p2 p3}
    = PosDiscP@{c so po p0 p1 p2 p3} ◯ PropSets_trunc@{c so} := eq_refl.

(* C29: the monad's functor is the reflection's on objects. *)
Example p469_c29_TPos_fobj@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (S : Sets@{c so}) :
  fobj[TPos@{c so po p0 p1 p2 p3 s}] S
    = fobj[PropSets_Incl@{c so} ◯ PropSets_trunc@{c so}] S := eq_refl.

(* C50: and on arrows. *)
Example p469_c50_TPos_fmap@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (S T : Sets@{c so}) (f : S ~{Sets@{c so}}~> T) :
  fmap[Pos_Forget@{po so p0 p2 p1 p3 c} ◯ PosDisc@{c so po p0 p1 p2 p3}] f
    = fmap[PropSets_Incl@{c so} ◯ PropSets_trunc@{c so}] f := eq_refl.

(* R16 *)
Fail Example p469_r16_TPos_trunc_eq@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} :
  TPos@{c so po p0 p1 p2 p3 s} = PropSets_Incl@{c so} ◯ PropSets_trunc@{c so}
  := eq_refl.

(* R17 *)
Fail Example p469_r17_trunc_monads_eq@{c so po p0 p1 p2 p3 s a r m1 m2 |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1, so <= m1, c <= m1, so <= m2, c <= m2 +} :
  @eq (obj[Monads@{so c m1 m2} Sets@{c so}])
    (existT _ TPos@{c so po p0 p1 p2 p3 s} MPos@{c so po p0 p1 p2 p3 s a})
    (existT _ (PropSets_Incl@{c so} ◯ PropSets_trunc@{c so})
       (Adjunction_Induced_Monad PropSets_trunc_Incl@{c so r})) := eq_refl.

(* C30: the monad keeps the carrier. *)
Example p469_c30_TPos_carrier@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (S : Sets@{c so}) :
  carrier (fobj[TPos@{c so po p0 p1 p2 p3 s}] S) = carrier S := eq_refl.

(* C33: its ≈ is the truncation of S's. *)
Example p469_c33_TPos_equiv@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (S : Sets@{c so}) (x y : carrier S) :
  @equiv _ (is_setoid (fobj[TPos@{c so po p0 p1 p2 p3 s}] S)) x y
    = inhabited (x ≈ y) := eq_refl.

(* R4 *)
Fail Example p469_r4_TPos_obj@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (S : Sets@{c so}) :
  fobj[TPos@{c so po p0 p1 p2 p3 s}] S = S := eq_refl.

(* R11 *)
Fail Example p469_r11_TPos_equiv@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (S : Sets@{c so}) (x y : carrier S) :
  @equiv _ (is_setoid (fobj[TPos@{c so po p0 p1 p2 p3 s}] S)) x y
    = (x ≈ y) := eq_refl.

(* R5 *)
Fail Example p469_r5_TPos_eq@{c so po p0 p1 p2 p3 s |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} :
  TPos@{c so po p0 p1 p2 p3 s} = Id[Sets@{c so}] := eq_refl.

(* C31: the unit is the identity function. *)
Example p469_c31_MPos_ret@{c so po p0 p1 p2 p3 s a |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (S : Sets@{c so}) :
  @Sets.morphism _ _ _ _ (@ret _ _ MPos@{c so po p0 p1 p2 p3 s a} S)
    = (fun x : carrier S => x) := eq_refl.

(* C51: so is the multiplication. *)
Example p469_c51_MPos_join@{c so po p0 p1 p2 p3 s a |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (S : Sets@{c so}) :
  @Sets.morphism _ _ _ _
    (@join _ _ (Adjunction_Induced_Monad
                  PosDisc_Pos_Forget@{c so po p0 p1 p2 p3 a}) S)
    = (fun x : carrier S => x) := eq_refl.

(* R6 *)
Fail Example p469_r6_MPos_ret@{c so po p0 p1 p2 p3 s a |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1,
  c <= p0, c <= p1 +} (S : Sets@{c so}) :
  @ret _ _ MPos@{c so po p0 p1 p2 p3 s a} S = id := eq_refl.

(* R10 *)
Fail Definition p469_r10_naive_elim@{c so | c < so +} :
  SetsTruncElim@{c so} :=
  fun S x y H => match H with inhabits h => h end.

(* ------------------------------------------------------------------------ *)
(** ** The guard: every constant of the five targets *)

Check @Category.Monad.Identity.IdMonad.
Check @Category.Monad.Identity.IdMonad_fobj.
Check @Category.Monad.Identity.IdMonad_fmap.
Check @Category.Monad.Identity.IdMonad_ret.
Check @Category.Monad.Identity.IdMonad_join.
Check @Category.Monad.Identity.IdMonad_alg_id.
Check @Category.Monad.Identity.IdMonad_EM_counit.
Check @Category.Monad.Identity.IdMonad_EM_unit_iso.
Check @Category.Monad.Identity.IdMonad_EM_unit_iso_id.
Check @Category.Monad.Identity.IdMonad_EM_unit.
Check @Category.Monad.Identity.IdMonad_EM_equivalence.
Check @Category.Instance.Top.Monadicity.PDiscT.
Check @Category.Instance.Top.Monadicity.PDiscMonad.
Check @Category.Instance.Top.Monadicity.PDiscT_fobj.
Check @Category.Instance.Top.Monadicity.PDiscT_fmap.
Check @Category.Instance.Top.Monadicity.PDisc_PForget_unit.
Check @Category.Instance.Top.Monadicity.PDisc_PForget_counit.
Check @Category.Instance.Top.Monadicity.PDiscMonad_ret.
Check @Category.Instance.Top.Monadicity.PDiscMonad_join.
Check @Category.Instance.Top.Monadicity.PDiscT_fields.
Check @Category.Instance.Top.Monadicity.PDiscMonad_fields.
Check @Category.Instance.Top.Monadicity.disc_to_id.
Check @Category.Instance.Top.Monadicity.id_to_disc.
Check @Category.Instance.Top.Monadicity.disc_id_hom.
Check @Category.Instance.Top.Monadicity.id_disc_hom.
Check @Category.Instance.Top.Monadicity.disc_id_hom_component.
Check @Category.Instance.Top.Monadicity.id_disc_hom_component.
Check @Category.Instance.Top.Monadicity.disc_id_iso.
Check @Category.Instance.Top.Monadicity.PDiscK.
Check @Category.Instance.Top.Monadicity.PDiscK_forget_obj.
Check @Category.Instance.Top.Monadicity.PDiscK_forget_map.
Check @Category.Instance.Top.Monadicity.PDiscK_alg.
Check @Category.Instance.Top.Monadicity.PDiscK_forget_strict.
Check @Category.Instance.Top.Monadicity.PDiscK_forget.
Check @Category.Instance.Top.Monadicity.PDiscMonad_alg_id.
Check @Category.Instance.Top.Monadicity.EM_PDisc_counit.
Check @Category.Instance.Top.Monadicity.EM_PDisc_unit_iso.
Check @Category.Instance.Top.Monadicity.EM_PDisc_unit.
Check @Category.Instance.Top.Monadicity.EM_PDisc_equivalence.
Check @Category.Instance.Top.Monadicity.PDiscK_free_iso.
Check @Category.Instance.Top.Monadicity.PDiscK_free.
Check @Category.Instance.Top.Monadicity.PDiscKI.
Check @Category.Instance.Top.Monadicity.PDiscKI_forget_obj.
Check @Category.Instance.Top.Monadicity.PDiscKI_forget_map.
Check @Category.Instance.Top.Monadicity.PDiscKI_alg.
Check @Category.Instance.Top.Monadicity.pbool_to_indisc.
Check @Category.Instance.Top.Monadicity.no_pindisc_to_bool.
Check @Category.Instance.Top.Monadicity.PForget_not_Full.
Check @Category.Instance.Top.Monadicity.PForget_not_ReflectsIsos.
Check @Category.Instance.Top.Monadicity.PDiscK_not_Full.
Check @Category.Instance.Top.Monadicity.PDiscK_not_Equivalence.
Check @Category.Instance.Top.Monadicity.PDiscKI_not_Full.
Check @Category.Instance.Top.Monadicity.PDiscKI_not_Equivalence.
Check @Category.Instance.Top.Monadicity.PDiscK_not_Cat_iso.
Check @Category.Instance.Top.Monadicity.PForget_not_Monadic.
Check @Category.Instance.Top.Monadicity.TypeValued.top_bool_to_indisc.
Check @Category.Instance.Top.Monadicity.TypeValued.no_top_indisc_to_bool.
Check @Category.Instance.Top.Monadicity.TypeValued.Top_Forget_not_Monadic.
Check @Category.Instance.Sets.Propositional.Full.PropSets_sub.
Check @Category.Instance.Sets.Propositional.Full.PropSets.
Check @Category.Instance.Sets.Propositional.Full.PropSets_Incl.
Check @Category.Instance.Sets.Propositional.Full.PropSets_Incl_fobj.
Check @Category.Instance.Sets.Propositional.Full.PropSets_Incl_fmap.
Check @Category.Instance.Sets.Propositional.Full.PropSets_Full.
Check @Category.Instance.Sets.Propositional.Full.PropSets_Incl_Full.
Check @Category.Instance.Sets.Propositional.Full.PropSets_Incl_Faithful.
Check @Category.Instance.Sets.Propositional.Full.PropSets_LocallyPropositional.
Check @Category.Instance.Sets.Propositional.Full.PropSets_lift.
Check @Category.Instance.Sets.Propositional.Full.PropSets_lift_obj.
Check @Category.Instance.Sets.Propositional.Full.PropSets_lift_map.
Check @Category.Instance.Sets.Propositional.Full.PropSets_lift_Incl.
Check @Category.Instance.Sets.Propositional.Full.trunc_equivalence.
Check @Category.Instance.Sets.Propositional.Full.trunc_setoid.
Check @Category.Instance.Sets.Propositional.Full.trunc_PropEquiv.
Check @Category.Instance.Sets.Propositional.Full.PropSets_trunc_obj.
Check @Category.Instance.Sets.Propositional.Full.PropSets_trunc.
Check @Category.Instance.Sets.Propositional.Full.trunc_transpose.
Check @Category.Instance.Sets.Propositional.Full.trunc_extend.
Check @Category.Instance.Sets.Propositional.Full.PropSets_trunc_iso_obligation_1.
Check @Category.Instance.Sets.Propositional.Full.PropSets_trunc_iso_obligation_2.
Check @Category.Instance.Sets.Propositional.Full.PropSets_trunc_iso_obligation_3.
Check @Category.Instance.Sets.Propositional.Full.PropSets_trunc_iso_obligation_4.
Check @Category.Instance.Sets.Propositional.Full.PropSets_trunc_iso.
Check @Category.Instance.Sets.Propositional.Full.PropSets_trunc_Incl.
Check @Category.Instance.Sets.Propositional.Full.PropSets_trunc_unit.
Check @Category.Instance.Sets.Propositional.Full.PropSets_trunc_counit.
Check @Category.Instance.Sets.Propositional.Full.PropSets_Reflective.
Check @Category.Instance.Pos.Monadicity.pos_PropEquiv.
Check @Category.Instance.Pos.Monadicity.PosPForget.
Check @Category.Instance.Pos.Monadicity.Pos_Forget_factor_obj.
Check @Category.Instance.Pos.Monadicity.Pos_Forget_factor_map.
Check @Category.Instance.Pos.Monadicity.Pos_Forget_factor.
Check @Category.Instance.Pos.Monadicity.PosDiscPObj.
Check @Category.Instance.Pos.Monadicity.PosDiscP_fmap.
Check @Category.Instance.Pos.Monadicity.PosDiscP.
Check @Category.Instance.Pos.Monadicity.posdiscP_from.
Check @Category.Instance.Pos.Monadicity.posdiscP_to.
Check @Category.Instance.Pos.Monadicity.posdiscP_iso_obligation_1.
Check @Category.Instance.Pos.Monadicity.posdiscP_iso_obligation_2.
Check @Category.Instance.Pos.Monadicity.posdiscP_iso_obligation_3.
Check @Category.Instance.Pos.Monadicity.posdiscP_iso_obligation_4.
Check @Category.Instance.Pos.Monadicity.posdiscP_iso.
Check @Category.Instance.Pos.Monadicity.PosDiscP_PosPForget.
Check @Category.Instance.Pos.Monadicity.TPosP.
Check @Category.Instance.Pos.Monadicity.MPosP.
Check @Category.Instance.Pos.Monadicity.TPosP_setoid.
Check @Category.Instance.Pos.Monadicity.TPosP_fmap.
Check @Category.Instance.Pos.Monadicity.TPosP_pequiv.
Check @Category.Instance.Pos.Monadicity.MPosP_ret.
Check @Category.Instance.Pos.Monadicity.MPosP_join.
Check @Category.Instance.Pos.Monadicity.TPosP_to_id.
Check @Category.Instance.Pos.Monadicity.id_to_TPosP.
Check @Category.Instance.Pos.Monadicity.MPosP_to_Id.
Check @Category.Instance.Pos.Monadicity.Id_to_MPosP.
Check @Category.Instance.Pos.Monadicity.MPosP_to_Id_component.
Check @Category.Instance.Pos.Monadicity.Id_to_MPosP_component.
Check @Category.Instance.Pos.Monadicity.MPosP_Id_iso.
Check @Category.Instance.Pos.Monadicity.PropSets_EM_Id_equivalence.
Check @Category.Instance.Pos.Monadicity.PosDiscObj.
Check @Category.Instance.Pos.Monadicity.PosDiscObj_le.
Check @Category.Instance.Pos.Monadicity.PosDisc.
Check @Category.Instance.Pos.Monadicity.PosDisc_obj.
Check @Category.Instance.Pos.Monadicity.PosDisc_map.
Check @Category.Instance.Pos.Monadicity.posdisc_from.
Check @Category.Instance.Pos.Monadicity.posdisc_to.
Check @Category.Instance.Pos.Monadicity.posdisc_iso_obligation_1.
Check @Category.Instance.Pos.Monadicity.posdisc_iso_obligation_2.
Check @Category.Instance.Pos.Monadicity.posdisc_iso_obligation_3.
Check @Category.Instance.Pos.Monadicity.posdisc_iso_obligation_4.
Check @Category.Instance.Pos.Monadicity.posdisc_iso.
Check @Category.Instance.Pos.Monadicity.PosDisc_Pos_Forget.
Check @Category.Instance.Pos.Monadicity.TPos.
Check @Category.Instance.Pos.Monadicity.MPos.
Check @Category.Instance.Pos.Monadicity.TPos_fobj.
Check @Category.Instance.Pos.Monadicity.TPos_fmap.
Check @Category.Instance.Pos.Monadicity.TPos_carrier.
Check @Category.Instance.Pos.Monadicity.TPos_equiv.
Check @Category.Instance.Pos.Monadicity.MPos_ret.
Check @Category.Instance.Pos.Monadicity.MPos_join.
Check @Category.Instance.Pos.Monadicity.TPos_to_trunc.
Check @Category.Instance.Pos.Monadicity.trunc_to_TPos.
Check @Category.Instance.Pos.Monadicity.MPos_to_trunc.
Check @Category.Instance.Pos.Monadicity.trunc_to_MPos.
Check @Category.Instance.Pos.Monadicity.MPos_trunc_iso.
Check @Category.Instance.Pos.Monadicity.id_to_TPos.
Check @Category.Instance.Pos.Monadicity.Id_to_MPos.
Check @Category.Instance.Pos.Monadicity.SetsTruncElim.
Check @Category.Instance.Pos.Monadicity.MPos_to_Id_trunc.
Check @Category.Instance.Pos.Monadicity.TPos_to_id.
Check @Category.Instance.Pos.Monadicity.MPos_to_Id.
Check @Category.Instance.Pos.Monadicity.MPos_Id_iso.
Check @Category.Instance.Pos.Monadicity.choice_setoid.
Check @Category.Instance.Pos.Monadicity.trunc_choice.
Check @Category.Instance.Pos.Monadicity.choice_trunc.
Check @Category.Instance.Pos.Monadicity.MPos_Id_iff.
Check @Category.Instance.Pos.Monadicity.all_PropEquiv_trunc.
Check @Category.Instance.Pos.Monadicity.trunc_all_PropEquiv.
Check @Category.Instance.Pos.Monadicity.any_adj_to_Id_trunc.
Check @Category.Instance.Pos.Monadicity.untr_of_choice.
Check @Category.Instance.Pos.Monadicity.choice_of_untr.
Check @Category.Instance.Pos.Monadicity.choice_of_IEM.
Check @Category.Instance.Pos.Monadicity.MPos_IEM_Id_iso.
Check @Category.Instance.Pos.Monadicity.bool_le_antisym.
Check @Category.Instance.Pos.Monadicity.BoolDiscPos.
Check @Category.Instance.Pos.Monadicity.BoolChainPos.
Check @Category.Instance.Pos.Monadicity.bool_disc_to_chain.
Check @Category.Instance.Pos.Monadicity.no_bool_chain_to_disc.
Check @Category.Instance.Pos.Monadicity.Pos_Forget_not_Full.
Check @Category.Instance.Pos.Monadicity.Pos_Forget_not_ReflectsIsos.
Check @Category.Instance.Pos.Monadicity.Pos_Forget_not_Monadic.
Check @Category.Instance.Pos.Monadicity.PosPForget_not_Monadic.
Check @Category.Instance.Pos.Monadicity.PropSets_Incl_Monadic.

(* ------------------------------------------------------------------------ *)
(** ** The tree's other names for the principle, measured at the end *)

(* Loaded here, after every other command, the guard block included, so
   that the modules below change the environment of C53 and C54 alone. *)
Require Import Category.Instance.Sets.Classifier.OneLevel.

(* C53: Instance/Sets/Classifier/OneLevel.v's [Untruncate] and [IEM] are
   the hypotheses of [choice_of_untr] and [choice_of_IEM], written out. *)
Example p469_c53_untr_iem_unfold@{c t | c < t +} :
  @eq Type@{t} Untruncate@{c}
    (∀ P : Type@{c}, (∀ Q : Prop, (P → Q) → Q) → P)
  /\ @eq Type@{t} IEM@{c} (∀ P : Type@{c}, P + (P → False))
  := conj eq_refl eq_refl.

(* C54: under OneLevel.v's [IEM] the induced monad over [Sets] is the
   identity monad, by [MPos_IEM_Id_iso] and by the route through
   [untruncate_of_IEM] and [choice_of_untr]. *)
Definition p469_c54_iem_routes@{c so po p0 p1 p2 p3 s a m1 m2 |
  c < so, c < s, c < po, Set < p2, p1 <= po, p2 <= p0, p3 <= p1, c <= p0,
  c <= p1, so <= m1, c <= m1, so <= m2, c <= m2 +} (E : IEM@{c}) :=
  (MPos_IEM_Id_iso@{c so po p0 p1 p2 p3 s a m1 m2} E,
   MPos_Id_iso@{c so po p0 p1 p2 p3 s a m1 m2}
     (choice_trunc@{c so}
        (choice_of_untr@{c} (untruncate_of_IEM@{c} E)))).

(* ------------------------------------------------------------------------ *)
(** ** The monad of Id ⊣ Id, measured at the end *)

Require Import Category.Instance.Adjoints.
Require Import Category.Adjunction.Compose.
Require Import Category.Monad.Monadicity.Examples.

(* C55: the monad Id ⊣ Id induces has unit and multiplication [id]. *)
Example p469_c55_IdId_monad@{o h s a | h < s +} (C : Category@{o h h})
  (x : C) :
  (@ret _ _ (@Adjunction_Induced_Monad@{o h o h s a s} _ _ _ _
               (@Adjunction_Id@{s a o h} C)) x,
   @join _ _ (@Adjunction_Induced_Monad@{o h o h s a s} _ _ _ _
                (@Adjunction_Id@{s a o h} C)) x)
    = (@id C x, @id C x) := eq_refl.
