(** * Probe for absolute coequalizers and absolute (co)limits (issue #477)

    Pins the measured boundaries of what #477 adds for Mac Lane, §VI.6,
    book p. 149 (PDF p. 158), item maclane:VI.6:def2, read from the page
    image ("An arrow e is called an absolute coequalizer of ∂₀ and ∂₁ in
    C if for any functor T: C → X (to any category X whatever) the
    resulting fork ... still has Te a coequalizer"; "absolute colimits
    (or absolute limits) of any other type"), with the item the issue
    appends, Riehl's Exercise 3.4.vi(iii) (riehl:3.4:def-absolute,
    printed p. 109, PDF p. 129: "Co/limits with this property are called
    absolute co/limits").  The targets are Construction/Lift.v (the
    universe lift), Structure/Coequalizer.v (its last section, the
    conversions at any diagram of parallel-pair shape),
    Structure/Limit/Absolute.v (the cone-level predicates and their
    closure theory), Structure/Coequalizer/Absolute.v (the elementary
    predicate and its agreement with the cocone-level one) and
    Structure/Limit/Constant.v (the two apex bridges #477 adds there).
    Donors named by controls or refusals: Structure/Coequalizer/Split.v,
    whose two preservation theorems #477 re-annotated (C17, C18, C20);
    Structure/Limit/Preservation.v ([IsLimitCone], R7) and
    Functor/Opposite.v ([Opposite_Functor], R8), two carriers of the
    cone-level hom cap; Theory/Functor.v ([Compose], R3, R9); Functor/
    Hom.v (the Yoneda embedding, C46, C47, R11); and Adjunction/Diagonal/
    Limit.v ([HasColimitsOfShape], C31).

    THE IMPORT LIST, generated by a script over the [Require] lines.
    Target by target in dependency order: Construction/Lift.v's three
    [Require] lines and that target; the ten lines Structure/Limit/
    Absolute.v adds, and that target; the three lines Structure/
    Coequalizer.v adds, and that module; the one line Structure/
    Coequalizer/Absolute.v adds, and that target; the fourteen lines
    Structure/Limit/Constant.v adds, and that module: thirty-six lines.
    Then the two modules of the Yoneda boundary, Functor/Hom.v and
    Instance/Sets.v.  Thirty-eight lines, all naming [Category] modules.
    Under them [Print Libraries] in a scratch file loads one hundred and
    thirteen [Category] modules, exactly the set a [Require] of the five
    targets alone loads, the two modules among them (compared by
    script), and no module under [Reals].  A shorter import list is what
    makes a probe pass for no reason.
    CORRECTION (#480): Structure/Coequalizer/Absolute.v now also
    requires Structure/Coequalizer/Contractible.v, so it adds two lines
    and the list has thirty-nine, which load one hundred and fourteen
    [Category] modules, again exactly the set a [Require] of the five
    targets alone loads; the strip and wrap checks below were run again
    under the longer list, twelve of twelve and forty-eight of
    forty-eight, each refusal printing the parenthetical quoted below.

    DISCIPLINE.  Every negative other than the instrument is an
    [Example] or a [Definition], never a [Check], so that an open evar
    cannot satisfy it.  Each of the twelve refutation lines (the
    instrument and R1 to R11) was stripped of its refutation keyword in a
    copy of this WHOLE file, one at a time, compiled, and its error read;
    each copy stops inside the stripped command (twelve of twelve, by the
    File line of its error, compared by script with the command's
    extent).  Each of the forty-eight controls, wrapped in the refutation
    keyword in a copy of this WHOLE file, stops the build at that command
    with the message Rocq prints for a refutation whose command succeeds
    (forty-eight of forty-eight, by the same script).  Quotations are
    Rocq 9.1.1's under this file's import list, with the error's
    environment block left out; Rocq prints the "cannot unify"
    parenthetical with the short names in scope.

    KINDS.  Twelve refutations, counted as the lines that open with the
    refutation keyword: NAME-ABSENCE, the instrument (one); CONVERSION,
    [eq_refl] refused with a "cannot unify" parenthetical, every
    statement being well typed (R1, R2, R5: three); and UNIVERSE, the
    term refused with "universe inconsistency" between levels this file
    declares (R3, R4, R6, R7, R8, R9, R10, R11: eight).  CAUSES, read
    from the terms: R1 compares the record [Id ◯ K] with a variable
    functor [K], whose data agree (C1, C2); R2 compares two predicates of
    which one quantifies over functors out of C and the other out of
    C^op, related by maps that are mutually inverse on the nose (C4, C5);
    R5 compares [fmap[T] (e ∘ f)] with [fmap[T] e ∘ fmap[T] f] for a
    variable functor [T], equal at ≈ (C15).  None names a constant whose
    proof #477 closes with [Qed].  R3 is [Compose] (Theory/Functor.v),
    whose three categories share one hom-and-proof level, while the
    functor type itself is formable across hom levels (C10).  R4 and R6
    read a hypothesis at a target level above C's own with the lemmas
    that consume C's own (C11, C19): they pin those lemmas' signatures,
    not what the predicates yield, since their statements are accepted
    through the lift (C22, C23, C26, C27; C24, C25 for the colimit
    twins).  R7 is [IsLimitCone] (Structure/Limit/Preservation.v), whose
    bare binders give a shape and its ambient one hom level, over cones
    that are themselves formable (C43); the same definition with its
    binders written out is accepted there (C40, C41, C44).  R8 is
    [Opposite_Functor] (Functor/Opposite.v), the first carrier of
    [Cocone]; with its binders written out it is accepted, and so are
    the cones over it (C42, C45).  R9 is [Compose] again, at the lift,
    which is why [Lift_after] is built directly (C37); with the objects
    lifted alone the composite is formable (C38).  R10 is [Functor]
    itself, whose [fmap_respects] bounds a source's hom level by its
    target's, so there is no way back from a lift of the hom level, the
    way in being formable (C39).  R11 is the cone-level hom cap at the
    Yoneda embedding of a category whose objects lie strictly above its
    hom-sets, the embedding itself being formable (C47); strictly below,
    an absolute colimit is preserved by it (C46).

    INSTANCES.  C11, R4, C22 to C25, C12, C17, R6, C26, C27, C37, R9, C38,
    C39 and R10 name the universe instance of [AbsoluteLimitCone],
    [AbsoluteColimitCocone], [AbsoluteCoequalizer] or [LiftCat]
    explicitly: a universe boundary is a statement about a particular
    instance, and the levels are the ones this file declares in its
    sections.  C40 to C42 write their binders out, which is what they
    are for.

    LABELS.  The labels are not constants: each refutation and each
    control carries its label in a comment on the line above it, the
    instrument's reading "The instrument".  The constants are
    [p477_cN_…] and [p477_rN_…] for label CN or RN.  The numbers follow
    the order in which the controls were written, not the file's.

    RESTATEMENTS.  Construction/Lift.v: [Lift_in_fobj] C33,
    [Lift_in_fmap] C34, [Lift_after_fobj] C35, [Lift_after_fmap] C36.
    Structure/Limit/Absolute.v: [FCone_Id_apex] C1, [FCone_Id_leg] C2,
    [AbsoluteColimitCocone_of_op_op] C4, [AbsoluteColimitCocone_op_of_op]
    C5.  Structure/Coequalizer/Absolute.v: [image_cofork_inj_ParX] C13,
    [image_cofork_inj_ParY] C14, [image_colimit_coequalizer_desc] C16.
    Eleven readbacks, each named once, each at [eq_refl]; C32 adds a
    twelfth that no file states, that [image_colimit_coequalizer] IS
    Structure/Coequalizer.v's [parallel_colimit_coequalizer] at
    [T ◯ APair f g].  The other controls restate no readback: C3, C10,
    C11, C15, C19, C22 to C27, C37 to C39, C43 to C47 are the twins of
    refutations, and C40 to C42 the annotated definitions C44 and C45
    use; C6 and C7 show the predicates applying to a bundled [Limit] and
    [Colimit] through the coercion [limit_cone]; C8 and C9 type the apex
    bridges by Structure/Limit/Constant.v's [AbsoluteLimit] and
    [AbsoluteColimit]; C12 keeps the target level of preservation free;
    C17 and C18 accept a split fork's absoluteness, and Split.v's
    preservation, at a target with strictly larger hom-sets, which the
    two Split.v theorems refused before #477 wrote their binders out
    ("Cannot enforce xh = ch because ch < xh", measured on the earlier
    signatures); C20 is Mac Lane's Lemma, Split.v's own; C21 carries a
    split fork to Constant.v's [AbsoluteColimit] through the cone-level
    predicate, and C48 a split fork of C^op to an absolute limit cone in
    C; C28 to C31 read Structure/Coequalizer.v's conversions at
    [APair f g] with the types of [is_coequalizer_cocone_ump] (as an
    [IsColimitCocone]) and [coequalizer_is_coequalizer], at an image
    diagram [U ◯ APair f g] as an elementary coequalizer of the image
    pair, and at Adjunction/Diagonal/Limit.v's [HasColimitsOfShape].

    THE REFUSALS, with the parenthetical each stripped copy prints.
      The instrument (NAME-ABSENCE): The reference p477_absent_name was
        not found in the current environment.
      R1, [Id ◯ K] against [K] (controls C1, C2; C3): (cannot unify
        "Id[C] ◯ K" and "K")
      R2, the colimit predicate against the opposite limit predicate
        (controls C4, C5): (cannot unify "AbsoluteColimitCocone N" and
        "AbsoluteLimitCone N")
      R3, [F ◯ K] with C's homs strictly below D's (control C10):
        (universe inconsistency: Cannot enforce dh = ch because ch < dh)
      R4, the [Id] reading from a target object level above C's
        (controls C11, C12, C22 to C25): (universe inconsistency: Cannot
        enforce do = co because co < do)
      R5, the image cocone's [ParX] injection against the split
        composite (controls C13; C15, ≈): (cannot unify "cocone_inj
        (FCocone T (cofork_cocone f g e H)) ParX" and "fmap[T] e ∘
        fmap[T] f")
      R6, the [Id] reading of the elementary predicate from a target hom
        level above C's, at C's own object level (controls C19, C26,
        C27): (universe inconsistency: Cannot enforce xh = ch because
        ch < xh)
      R7, [IsLimitCone] over a shape with strictly smaller hom-sets
        (controls C43, C44): (universe inconsistency: Cannot enforce
        ch = jh because jh < ch)
      R8, [Opposite_Functor] across the same levels (control C45):
        (universe inconsistency: Cannot enforce ch = jh because jh < ch)
      R9, [Lift_in X ◯ T] into a lift with strictly larger hom-sets
        (controls C37, C38): (universe inconsistency: Cannot enforce
        xh = yh because xh < yh)
      R10, the functor type from a lift of the hom level back to C
        (control C39): (universe inconsistency: Cannot enforce ch = …
        because ch < xh <= …), the elided level being one Rocq names
      R11, the Yoneda embedding of a category whose objects lie strictly
        above its hom-sets, as a target of the cone-level predicate
        (controls C46, C47): (universe inconsistency: Cannot enforce
        … = ch because ch < co <= …), the elided level being one Rocq
        names

    NOT PINNED HERE.  (a) [About] readbacks as such: the headers'
    universe censuses.  (b) The pre-#477 signatures of Split.v's
    theorems, measured in a scratch file and no longer in the tree.
    (c) The closure of the targets under [Print Assumptions]: the
    Makefile's print-assumptions gate names the same sixty-five names as
    the guard below.  (d) The absences the headers record: an absence has
    no command.  (e) The readings of the books, from the page image and
    the PDF.  (f) The non-vacuity refutations of
    Structure/Limit/Absolute.v, which are theorems of that file, proved
    without an axiom, and not refusals.  (g) [U ◯ APair f g] against
    [APair (fmap[U] f) (fmap[U] g)], refused at [eq_refl] by
    Test/ProbeComponents462.v and not repeated here.  (h) [Compose] with
    its binders written out over three hom levels, which compiles with
    the same two obligation proofs: measured in a scratch file by the
    review of #477, and not restated here as a second [Program] functor.

    The guard block names the sixty-five constants #477 adds, so that a
    rename breaks this file: seven of Construction/Lift.v, six of
    Structure/Coequalizer.v, three of Structure/Limit/Preservation.v, one
    of Structure/Limit/Comparison.v, thirty-two of Structure/Limit/
    Absolute.v, fourteen of Structure/Coequalizer/Absolute.v and two of
    Structure/Limit/Constant.v; for the three new modules exactly the
    entries [Print Module] gives (none has a [Program] obligation).  Each
    is written fully qualified and with [@], so that no short name in
    scope can stand in for it.
    CORRECTION (#480): [Print Module] of Structure/Coequalizer/
    Absolute.v now gives fifteen entries, the fifteenth #480's
    [contractible_coequalizer_absolute], which Test/
    ProbeContractible480.v's guard names. *)

Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Functor.
Require Import Category.Construction.Lift.
Require Import Category.Theory.Isomorphism.
Require Import Category.Construction.Opposite.
Require Import Category.Functor.Opposite.
Require Import Category.Structure.Cone.
Require Import Category.Structure.Limit.
Require Import Category.Structure.Limit.Preservation.
Require Import Category.Structure.Limit.Comparison.
Require Import Category.Functor.Diagonal.
Require Import Category.Instance.Zero.
Require Import Category.Instance.Two.
Require Import Category.Structure.Limit.Absolute.
Require Import Category.Theory.Morphisms.
Require Import Category.Structure.Equalizer.
Require Import Category.Instance.Parallel.
Require Import Category.Structure.Coequalizer.
Require Import Category.Structure.Coequalizer.Split.
Require Import Category.Structure.Coequalizer.Contractible.
Require Import Category.Structure.Coequalizer.Absolute.
Require Import Category.Theory.Natural.Transformation.
Require Import Category.Theory.Adjunction.
Require Import Category.Instance.Fun.
Require Import Category.Structure.Cone.Const.
Require Import Category.Structure.Cartesian.
Require Import Category.Structure.Terminal.
Require Import Category.Structure.Limit.Unique.
Require Import Category.Structure.Limit.Components.
Require Import Category.Structure.Groupoid.Connected.
Require Import Category.Theory.Connected.Components.
Require Import Category.Adjunction.Diagonal.Limit.
Require Import Category.Instance.One.
Require Import Category.Instance.Two.Discrete.
Require Import Category.Instance.Coq.
Require Import Category.Structure.Limit.Constant.
Require Import Category.Functor.Hom.
Require Import Category.Instance.Sets.

Generalizable All Variables.

(* ------------------------------------------------------------------------ *)
(** ** The instrument *)

(* The instrument *)
Fail Check p477_absent_name.

(* ------------------------------------------------------------------------ *)
(** ** The cone-level predicates: Structure/Limit/Absolute.v *)

Section Cones.

Context {J C : Category} {K : J ⟶ C}.

(* C1: the image of a cone under [Id] has the cone's apex ... *)
Example p477_c1_id_apex (N : Cone K) :
  vertex_obj[FCone Id N] = vertex_obj[N] := eq_refl.

(* C2: ... and its legs. *)
Example p477_c2_id_leg (N : Cone K) (x : J) :
  cone_leg (FCone Id N) x = cone_leg N x := eq_refl.

(* R1 *)
Fail Example p477_r1_id_comp : Id ◯ K = K := eq_refl.

(* C3: so only the competing cone is repackaged, and absolute is
   limiting. *)
Definition p477_c3_is_limit (N : Cone K) (A : AbsoluteLimitCone N) :
  IsLimitCone N := fun M => A C Id (cone_id_comp M).

(* C4: the duality maps are mutually inverse on the nose ... *)
Example p477_c4_of_op_op (N : Cocone K) (A : AbsoluteColimitCocone N) :
  AbsoluteColimitCocone_of_op (AbsoluteColimitCocone_op A) = A := eq_refl.

(* C5: ... both ways. *)
Example p477_c5_op_of_op (N : Cocone K)
  (A : @AbsoluteLimitCone (J^op) (C^op) (K^op) N) :
  AbsoluteColimitCocone_op (AbsoluteColimitCocone_of_op A) = A := eq_refl.

(* R2 *)
Fail Example p477_r2_dual_same (N : Cocone K) :
  AbsoluteColimitCocone N = @AbsoluteLimitCone (J^op) (C^op) (K^op) N
  := eq_refl.

(* C6: the limit predicate applies to a bundled limit ... *)
Definition p477_c6_bundled_limit (L : Limit K) (A : AbsoluteLimitCone L) :
  IsLimitCone L := AbsoluteLimitCone_IsLimitCone A.

(* C7: ... and the colimit predicate to a bundled colimit. *)
Definition p477_c7_bundled_colimit (L : Colimit K)
  (A : AbsoluteColimitCocone L) : IsColimitCocone L :=
  AbsoluteColimitCocone_IsColimitCocone A.

(* C8: the apex reading lands in Structure/Limit/Constant.v's
   [AbsoluteLimit] ... *)
Definition p477_c8_apex (N : Cone K) (A : AbsoluteLimitCone N) :
  AbsoluteLimit K vertex_obj[N] := AbsoluteLimitCone_apex A.

(* C9: ... and its colimit twin in [AbsoluteColimit]. *)
Definition p477_c9_coapex (N : Cocone K) (A : AbsoluteColimitCocone N) :
  AbsoluteColimit K vertex_obj[N] := AbsoluteColimitCocone_apex A.

End Cones.

(* ------------------------------------------------------------------------ *)
(** ** Universes of the cone-level predicates *)

Section ComposeUniverse.

Universes jo co ch do dh.
Constraint ch < dh.

Context (Ju : Category@{jo ch ch}) (Cu : Category@{co ch ch})
  (Du : Category@{do dh dh}) (Ku : Ju ⟶ Cu) (Fu : Cu ⟶ Du).

(* C10: a functor into a category with strictly larger hom-sets. *)
Definition p477_c10_functor_type : Type := Cu ⟶ Du.

(* R3 *)
Fail Definition p477_r3_compose : Ju ⟶ Du := Fu ◯ Ku.

End ComposeUniverse.

Section IdInstance.

Universes jo co ch do.
Constraint co < do.

Context (Ju : Category@{jo ch ch}) (Cu : Category@{co ch ch})
  (Ku : Ju ⟶ Cu) (N : Cone Ku) (Nc : Cocone Ku).

(* C11: "take F := Id" at the instance whose target is C's own level. *)
Definition p477_c11_id_instance
  (A : AbsoluteLimitCone@{jo co ch co _ _ _ _} N) : IsLimitCone N :=
  AbsoluteLimitCone_IsLimitCone A.

(* R4 *)
Fail Definition p477_r4_id_instance
  (A : AbsoluteLimitCone@{jo co ch do _ _ _ _} N) : IsLimitCone N :=
  AbsoluteLimitCone_IsLimitCone A.

(* C22: R4's statement is a theorem through the lift ... *)
Definition p477_c22_up_instance
  (A : AbsoluteLimitCone@{jo co ch do _ _ _ _} N) : IsLimitCone N :=
  AbsoluteLimitCone_IsLimitCone_up A.

(* C23: ... and through the downward closure to the [Id] instance. *)
Definition p477_c23_down_instance
  (A : AbsoluteLimitCone@{jo co ch do _ _ _ _} N) : IsLimitCone N :=
  AbsoluteLimitCone_IsLimitCone (AbsoluteLimitCone_down A).

(* C24: the colimit twins, the lift ... *)
Definition p477_c24_coup_instance
  (A : AbsoluteColimitCocone@{jo co ch do _ _ _ _} Nc) :
  IsColimitCocone Nc :=
  AbsoluteColimitCocone_IsColimitCocone_up A.

(* C25: ... and the downward closure. *)
Definition p477_c25_codown_instance
  (A : AbsoluteColimitCocone@{jo co ch do _ _ _ _} Nc) :
  IsColimitCocone Nc :=
  AbsoluteColimitCocone_IsColimitCocone (AbsoluteColimitCocone_down A).

(* C12: preservation keeps the target level free, given the limit. *)
Definition p477_c12_preserves (HN : IsLimitCone N)
  (A : AbsoluteLimitCone@{jo co ch do _ _ _ _} N)
  (D : Category@{do ch ch}) (F : Cu ⟶ D) : PreservesLimitCone Ku F :=
  AbsoluteLimitCone_preserves HN A D F.

End IdInstance.

(* ------------------------------------------------------------------------ *)
(** ** The cofork: Structure/Coequalizer/Absolute.v *)

Section Cofork.

Context {C X : Category} (T : C ⟶ X) {x y : C} (f g : x ~> y)
  {q : C} (e : y ~> q) (H : e ∘ f ≈ e ∘ g).

(* C13: the image cocone's injection over ParX is T (e ∘ f) ... *)
Example p477_c13_inj_ParX :
  cocone_inj (FCocone T (cofork_cocone f g e H)) ParX = fmap[T] (e ∘ f)
  := eq_refl.

(* C14: ... and over ParY it is T e. *)
Example p477_c14_inj_ParY :
  cocone_inj (FCocone T (cofork_cocone f g e H)) ParY = fmap[T] e
  := eq_refl.

(* R5 *)
Fail Example p477_r5_inj_ParX_split :
  cocone_inj (FCocone T (cofork_cocone f g e H)) ParX
    = fmap[T] e ∘ fmap[T] f := eq_refl.

(* C15: the split form holds at ≈, by [fmap_comp]. *)
Definition p477_c15_inj_ParX_equiv :
  cocone_inj (FCocone T (cofork_cocone f g e H)) ParX
    ≈ fmap[T] e ∘ fmap[T] f := fmap_comp e f.

(* C16: the descent of the image coequalizer is the colimit's mediator. *)
Example p477_c16_desc
  (HC : IsColimitCocone (FCocone T (cofork_cocone f g e H)))
  {z : X} (h : T y ~{X}~> z) (Hh : h ∘ fmap[T] f ≈ h ∘ fmap[T] g) :
  unique_obj (coeq_desc (image_colimit_coequalizer T H HC) h Hh)
    = unique_obj (HC (parallel_cofork_cocone (T ◯ APair f g) h Hh))
  := eq_refl.

(* C32: [image_colimit_coequalizer] IS Structure/Coequalizer.v's general
   conversion at [T ◯ APair f g]. *)
Example p477_c32_image_is_general
  (HC : IsColimitCocone (FCocone T (cofork_cocone f g e H))) :
  image_colimit_coequalizer T H HC
    = parallel_colimit_coequalizer (T ◯ APair f g) _ HC := eq_refl.

End Cofork.

Section CoforkUniverse.

Universes co ch xo xh.
Constraint ch < xh.

Context (Cu : Category@{co ch ch}) {x y : Cu} (f g : x ~> y)
  (S : SplitCoequalizer f g).

(* C17: a split fork is absolute over targets with strictly larger
   hom-sets. *)
Definition p477_c17_split_absolute :
  AbsoluteCoequalizer@{co ch xo xh _} f g (scoeq_obj S) (scoeq_e S) :=
  split_coequalizer_absolute S.

(* C18: Split.v's preservation reaches such a target. *)
Definition p477_c18_split_preserved (Xu : Category@{xo xh xh})
  (T : Cu ⟶ Xu) :
  IsCoequalizer (fmap[T] f) (fmap[T] g) (T (scoeq_obj S))
    (fmap[T] (scoeq_e S)) :=
  split_coequalizer_preserved T f g S.

(* R6 *)
Fail Definition p477_r6_id_instance
  (A : AbsoluteCoequalizer@{co ch co xh _} f g (scoeq_obj S) (scoeq_e S)) :
  IsCoequalizer f g (scoeq_obj S) (scoeq_e S) :=
  AbsoluteCoequalizer_IsCoequalizer A.

(* C26: R6's statement is a theorem through the lift ... *)
Definition p477_c26_up_instance
  (A : AbsoluteCoequalizer@{co ch co xh _} f g (scoeq_obj S) (scoeq_e S)) :
  IsCoequalizer f g (scoeq_obj S) (scoeq_e S) :=
  AbsoluteCoequalizer_IsCoequalizer_up A.

(* C27: ... and through the downward closure to the [Id] instance. *)
Definition p477_c27_down_instance
  (A : AbsoluteCoequalizer@{co ch co xh _} f g (scoeq_obj S) (scoeq_e S)) :
  IsCoequalizer f g (scoeq_obj S) (scoeq_e S) :=
  AbsoluteCoequalizer_IsCoequalizer (AbsoluteCoequalizer_down A).

(* C19: at C's own levels "automatically a coequalizer" holds of a split
   fork ... *)
Definition p477_c19_id_instance :
  IsCoequalizer f g (scoeq_obj S) (scoeq_e S) :=
  AbsoluteCoequalizer_IsCoequalizer (split_coequalizer_absolute S).

(* C20: ... as Mac Lane's Lemma, Split.v's own, has it directly. *)
Definition p477_c20_lemma : IsCoequalizer f g (scoeq_obj S) (scoeq_e S) :=
  split_coequalizer_is_coequalizer f g S.

(* C21: a split fork reaches Structure/Limit/Constant.v's apex-only
   [AbsoluteColimit] through the cone-level predicate. *)
Definition p477_c21_split_apex :
  AbsoluteColimit (APair f g) (scoeq_obj S) :=
  AbsoluteColimitCocone_apex (split_cofork_AbsoluteColimitCocone S).

End CoforkUniverse.

(* C48: the limit side.  A split fork of C^op is an absolute limit cone in
   C itself, through the duality map, C^op^op being C by conversion. *)
Definition p477_c48_split_op_limit {C : Category} {x y : C^op}
  {f g : x ~{C^op}~> y} (S : SplitCoequalizer f g) :
  @AbsoluteLimitCone (Parallel^op) C ((APair f g)^op)
    (cofork_cocone f g (scoeq_e S) (scoeq_law1 S)) :=
  AbsoluteColimitCocone_op (split_cofork_AbsoluteColimitCocone S).

(* ------------------------------------------------------------------------ *)
(** ** The diagram-general conversions: Structure/Coequalizer.v *)

Section ParallelDiagram.

Context {C : Category}.

(* C28: at [APair f g] the general conversion has the type of
   [is_coequalizer_cocone_ump], packaged as a colimiting cocone ... *)
Definition p477_c28_apair_colimit {x y : C} (f g : x ~> y) {q : C}
  {e : y ~> q} (E : IsCoequalizer f g q e) :
  IsColimitCocone (is_coequalizer_cocone f g E) :=
  parallel_coequalizer_colimit (APair f g) E.

(* C29: ... and its converse the type of [coequalizer_is_coequalizer]. *)
Definition p477_c29_apair_coequalizer {x y : C} (f g : x ~> y)
  (L : Coequalizer (APair f g)) :
  IsCoequalizer f g (colimit_apex L)
    (colimit_inj (colimit_is_acolimit L) ParY) :=
  parallel_colimit_coequalizer (APair f g) L (colimit_colimitcocone L).

(* C30: any colimiting cocone over an image diagram [U ◯ APair f g] is an
   elementary coequalizer of the image pair. *)
Definition p477_c30_image_pair {D : Category} (U : C ⟶ D) {x y : C}
  (f g : x ~> y) (N : Cocone (U ◯ APair f g)) (HN : IsColimitCocone N) :
  IsCoequalizer (fmap[U] f) (fmap[U] g) vertex_obj[N] (cocone_inj N ParY) :=
  parallel_colimit_coequalizer (U ◯ APair f g) N HN.

(* C31: the converse Adjunction/Diagonal/Finite.v records as absent, at
   Adjunction/Diagonal/Limit.v's named type. *)
Definition p477_c31_has_colimits (HC : HasCoequalizers C) :
  HasColimitsOfShape Parallel C :=
  HasCoequalizers_HasColimitsOfShape HC.

End ParallelDiagram.

(* ------------------------------------------------------------------------ *)
(** ** The lift: Construction/Lift.v *)

Section LiftReadbacks.

Context (C X : Category) (T : C ⟶ X) {x y : C} (f : x ~{C}~> y).

(* C33: [Lift_in] is the identity on objects ... *)
Example p477_c33_in_fobj : fobj[Lift_in C] x = x := eq_refl.

(* C34: ... and on arrows. *)
Example p477_c34_in_fmap : fmap[Lift_in C] f = f := eq_refl.

(* C35: [Lift_after T] has T's object action ... *)
Example p477_c35_after_fobj : fobj[Lift_after T] x = T x := eq_refl.

(* C36: ... and its arrow action. *)
Example p477_c36_after_fmap : fmap[Lift_after T] f = fmap[T] f := eq_refl.

End LiftReadbacks.

Section LiftCompose.

Universes co ch xo xh yo yh.
Constraint xh < yh.

Context (Cl : Category@{co ch ch}) (Xl : Category@{xo xh xh})
  (Tl : Cl ⟶ Xl).

(* C37: [Lift_after] reads T into a lift with strictly larger hom-sets. *)
Definition p477_c37_after : Cl ⟶ LiftCat@{xo xh yo yh} Xl := Lift_after Tl.

(* R9 *)
Fail Definition p477_r9_compose : Cl ⟶ LiftCat@{xo xh yo yh} Xl :=
  Lift_in Xl ◯ Tl.

End LiftCompose.

Section LiftComposeObjects.

Universes co ch xo yo.
Constraint xo < yo.

Context (Cl : Category@{co ch ch}) (Xl : Category@{xo ch ch})
  (Tl : Cl ⟶ Xl).

(* C38: with the objects lifted alone the composite is formable. *)
Definition p477_c38_compose_objects : Cl ⟶ LiftCat@{xo ch yo ch} Xl :=
  Lift_in Xl ◯ Tl.

End LiftComposeObjects.

Section LiftBack.

Universes co ch xo xh.
Constraint ch < xh.

Context (Cb : Category@{co ch ch}).

(* C39: the functor type into the lift is formable ... *)
Definition p477_c39_in_type : Type := Cb ⟶ LiftCat@{co ch xo xh} Cb.

(* R10 *)
Fail Definition p477_r10_back_type : Type := LiftCat@{co ch xo xh} Cb ⟶ Cb.

End LiftBack.

(* ------------------------------------------------------------------------ *)
(** ** The carriers of the cone-level hom cap *)

(* C40, C41: Structure/Limit/Preservation.v's [cone_leg] and
   [IsLimitCone], with their binders written out and the shape's hom level
   at or below the ambient's. *)
Definition p477_c40_cone_leg@{jo jh co ch +} {J : Category@{jo jh jh}}
  {C : Category@{co ch ch}} {F : J ⟶ C} (N : Cone F) (x : J) :
  vertex_obj[N] ~{C}~> F x :=
  @vertex_map _ _ _ _ (@coneFrom _ _ _ N) x.

Definition p477_c41_IsLimitCone@{jo jh co ch +} {J : Category@{jo jh jh}}
  {C : Category@{co ch ch}} {K : J ⟶ C} (N : Cone K) : Type :=
  ∀ M : Cone K, ∃! u : vertex_obj[M] ~{C}~> vertex_obj[N],
    ∀ x : J, p477_c40_cone_leg N x ∘ u ≈ p477_c40_cone_leg M x.

(* C42: Functor/Opposite.v's [Opposite_Functor], with its binders written
   out. *)
Definition p477_c42_op@{jo jh co ch +}
  {J : Category@{jo jh jh}} {C : Category@{co ch ch}} (F : J ⟶ C) :
  J^op ⟶ C^op :=
  @Build_Functor (J^op) (C^op) F
    (λ (x y : (J^op)%category) (f : x ~{J^op}~> y), @fmap J C F y x f)
    (λ (x y : (J^op)%category) (f g : x ~{J^op}~> y),
       @fmap_respects _ _ F y x f g)
    (λ x : (J^op)%category, fmap_id)
    (λ (x y z : (J^op)%category) (f : y ~{J^op}~> z) (g : x ~{J^op}~> y),
       @fmap_comp _ _ F _ _ _ g f).

Section ConeCap.

Universes jo jh co ch.
Constraint jh < ch.

Context (Jw : Category@{jo jh jh}) (Cw : Category@{co ch ch})
  (Kw : Jw ⟶ Cw).

(* C43: cones over a diagram whose shape has strictly smaller hom-sets ... *)
Definition p477_c43_cone_type : Type := Cone Kw.

(* R7 *)
Fail Definition p477_r7_islimitcone (N : Cone Kw) : Type := IsLimitCone N.

(* C44: ... and the limit predicate over them, its binders written out. *)
Definition p477_c44_islimitcone (N : Cone Kw) : Type :=
  p477_c41_IsLimitCone N.

(* R8 *)
Fail Definition p477_r8_op : Jw^op ⟶ Cw^op := Kw^op.

(* C45: the opposite functor with its binders written out, and cones over
   it, which are the cocones over [Kw]. *)
Definition p477_c45_cocone_type : Type := Cone (p477_c42_op Kw).

End ConeCap.

(* ------------------------------------------------------------------------ *)
(** ** The Yoneda embedding as a target of the cone-level predicates *)

Section YonedaSmall.

Universes jo co ch.
Constraint co < ch.

Context (Jy : Category@{jo ch ch}) (Cy : Category@{co ch ch})
  (Ky : Jy ⟶ Cy) (Ny : Cocone Ky).

(* C46: an absolute colimit is preserved by the Yoneda embedding of a
   category whose objects lie strictly below its hom-sets ... *)
Definition p477_c46_yoneda_small (A : AbsoluteColimitCocone Ny) :
  IsColimitCocone (FCocone (Curried_CoHom Cy) Ny) :=
  A _ (Curried_CoHom Cy).

End YonedaSmall.

Section YonedaLarge.

Universes jo co ch.
Constraint ch < co.

Context (Jy : Category@{jo ch ch}) (Cy : Category@{co ch ch})
  (Ky : Jy ⟶ Cy) (Ny : Cocone Ky).

(* C47: ... while for one whose objects lie strictly above, the embedding
   is formable ... *)
Definition p477_c47_yoneda_type : Type := Cy ⟶ [Cy^op, Sets].

(* R11 *)
Fail Definition p477_r11_yoneda_large (A : AbsoluteColimitCocone Ny) :
  IsColimitCocone (FCocone (Curried_CoHom Cy) Ny) :=
  A _ (Curried_CoHom Cy).

End YonedaLarge.

(* ------------------------------------------------------------------------ *)
(** ** Guard: every constant #477 adds, by name *)

Check @Category.Construction.Lift.LiftCat.
Check @Category.Construction.Lift.Lift_in.
Check @Category.Construction.Lift.Lift_in_fobj.
Check @Category.Construction.Lift.Lift_in_fmap.
Check @Category.Construction.Lift.Lift_after.
Check @Category.Construction.Lift.Lift_after_fobj.
Check @Category.Construction.Lift.Lift_after_fmap.
Check @Category.Structure.Coequalizer.parallel_cofork_legs.
Check @Category.Structure.Coequalizer.parallel_cofork_legs_coherence.
Check @Category.Structure.Coequalizer.parallel_cofork_cocone.
Check @Category.Structure.Coequalizer.parallel_coequalizer_colimit.
Check @Category.Structure.Coequalizer.parallel_colimit_coequalizer.
Check @Category.Structure.Coequalizer.HasCoequalizers_HasColimitsOfShape.
Check @Category.Structure.Limit.Preservation.cone_id_comp.
Check @Category.Structure.Limit.Preservation.FCocone_iso.
Check @Category.Structure.Limit.Preservation.cocone_assoc_inv.
Check @Category.Structure.Limit.Comparison.PreservesColimitCocone_of_cocone.
Check @Category.Structure.Limit.Absolute.AbsoluteLimitCone.
Check @Category.Structure.Limit.Absolute.AbsoluteColimitCocone.
Check @Category.Structure.Limit.Absolute.FCone_Id_apex.
Check @Category.Structure.Limit.Absolute.FCone_Id_leg.
Check @Category.Structure.Limit.Absolute.AbsoluteLimitCone_IsLimitCone.
Check @Category.Structure.Limit.Absolute.AbsoluteColimitCocone_op.
Check @Category.Structure.Limit.Absolute.AbsoluteColimitCocone_of_op.
Check @Category.Structure.Limit.Absolute.AbsoluteColimitCocone_of_op_op.
Check @Category.Structure.Limit.Absolute.AbsoluteColimitCocone_op_of_op.
Check @Category.Structure.Limit.Absolute.AbsoluteColimitCocone_IsColimitCocone.
Check @Category.Structure.Limit.Absolute.AbsoluteLimitCone_IsLimitCone_up.
Check @Category.Structure.Limit.Absolute.AbsoluteColimitCocone_IsColimitCocone_up.
Check @Category.Structure.Limit.Absolute.AbsoluteLimitCone_down.
Check @Category.Structure.Limit.Absolute.AbsoluteColimitCocone_down.
Check @Category.Structure.Limit.Absolute.AbsoluteLimitCone_preserves.
Check @Category.Structure.Limit.Absolute.AbsoluteLimitCone_of_preserves.
Check @Category.Structure.Limit.Absolute.AbsoluteColimitCocone_preserves.
Check @Category.Structure.Limit.Absolute.AbsoluteColimitCocone_of_preserves.
Check @Category.Structure.Limit.Absolute.AbsoluteLimitCone_transport.
Check @Category.Structure.Limit.Absolute.AbsoluteColimitCocone_transport.
Check @Category.Structure.Limit.Absolute.AbsoluteLimitCone_limitcone.
Check @Category.Structure.Limit.Absolute.AbsoluteColimitCocone_colimitcocone.
Check @Category.Structure.Limit.Absolute.AbsoluteLimitCone_image.
Check @Category.Structure.Limit.Absolute.AbsoluteColimitCocone_image.
Check @Category.Structure.Limit.Absolute.empty_shape_cone.
Check @Category.Structure.Limit.Absolute.empty_shape_cocone.
Check @Category.Structure.Limit.Absolute.two_into_TwoY.
Check @Category.Structure.Limit.Absolute.two_out_of_TwoX.
Check @Category.Structure.Limit.Absolute.two_terminal_IsLimitCone.
Check @Category.Structure.Limit.Absolute.two_initial_IsColimitCocone.
Check @Category.Structure.Limit.Absolute.two_terminal_not_absolute.
Check @Category.Structure.Limit.Absolute.two_initial_not_absolute.
Check @Category.Structure.Coequalizer.Absolute.AbsoluteCoequalizer.
Check @Category.Structure.Coequalizer.Absolute.AbsoluteCoequalizer_IsCoequalizer.
Check @Category.Structure.Coequalizer.Absolute.split_coequalizer_absolute.
Check @Category.Structure.Coequalizer.Absolute.AbsoluteCoequalizer_IsCoequalizer_up.
Check @Category.Structure.Coequalizer.Absolute.AbsoluteCoequalizer_down.
Check @Category.Structure.Coequalizer.Absolute.image_cofork_inj_ParX.
Check @Category.Structure.Coequalizer.Absolute.image_cofork_inj_ParY.
Check @Category.Structure.Coequalizer.Absolute.image_coequalizer_colimit.
Check @Category.Structure.Coequalizer.Absolute.image_colimit_coequalizer.
Check @Category.Structure.Coequalizer.Absolute.image_colimit_coequalizer_desc.
Check @Category.Structure.Coequalizer.Absolute.AbsoluteCoequalizer_AbsoluteColimitCocone.
Check @Category.Structure.Coequalizer.Absolute.AbsoluteColimitCocone_AbsoluteCoequalizer.
Check @Category.Structure.Coequalizer.Absolute.split_cofork_AbsoluteColimitCocone.
Check @Category.Structure.Coequalizer.Absolute.split_coequalizer_PreservesColimitCocone.
Check @Category.Structure.Limit.Constant.AbsoluteLimitCone_apex.
Check @Category.Structure.Limit.Constant.AbsoluteColimitCocone_apex.
