Require Import Category.Lib.
Require Import Category.Lib.TList.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Construction.Groupoid.
Require Import Category.Structure.Groupoid.
Require Import Category.Construction.Free.Quiver.
Require Import Category.Construction.Free.Groupoid.
Require Import Category.Construction.Quotient.

Generalizable All Variables.

(** * The category of fractions, and the zig-zag localization

    nLab:      https://ncatlab.org/nlab/show/calculus+of+fractions
    nLab:      https://ncatlab.org/nlab/show/localization
    nLab:      https://ncatlab.org/nlab/show/core
    Wikipedia: https://en.wikipedia.org/wiki/Localization_of_a_category
    Book: Riehl, Category Theory in Context, 2nd ed., §4.1, Example 4.1.15,
          printed p. 137 — the inclusion of groupoids into categories has
          both adjoints; the LEFT one formally inverts every morphism,
          producing the category of fractions
    Book: Gabriel, Zisman, Calculus of Fractions and Homotopy Theory,
          Ergebnisse 35, Springer 1967, §I.1 — the construction of C[W⁻¹]
          by generators and relations
    Book: Mac Lane, Categories for the Working Mathematician, 2nd ed.,
          GTM 5, §II.8, printed pp. 51-52 — Proposition 1, the quotient of
          a category by a family of relations and its universal property

    WHAT IS BUILT.  Given a category [C] and a class [W] of its morphisms,
    [FracZigZag W] is the localization [C[W⁻¹]]: the free category on the quiver
    of [C] glued to the reversed quiver of the [W]-morphisms, quotiented by
    the congruence generated by

      - the identity relation      [zfwd id  ≈ id],
      - the composition relations  [zfwd g ∘ zfwd f ≈ zfwd (g ∘ f)], and
      - the two cancellation relations
        [zbwd f w ∘ zfwd f ≈ id] and [zfwd f ∘ zbwd f w ≈ id],
        one pair for each [f] in [W].

    The first two make the projection [ZigZagProj : C ⟶ FracZigZag W] a functor;
    the last two make it invert [W].  The category of fractions [C[C⁻¹]] of
    Riehl's example is the case [W = WAll C], and carries the name
    [Fractions C], with [FractionsProj C] for its projection.

    THE RECIPE IS THE TREE'S, NOT A NEW ONE.  Free-on-a-quiver, then quotient
    by a generated congruence, is [Construction/Free/Quiver/Presented.v]'s
    shape, and every part of it is a donor: [Construction/Free/Quiver.v]
    supplies [Quiver], [FreeOnQuiver] (whose morphisms are [Lib/TList.v]
    paths, i.e. words), [InducedFunctor] and [QuiverOfCat];
    [Construction/Quotient.v] supplies [CongClosure] (whence symmetry,
    transitivity, compatibility with composition and containment of the
    ambient [≈], so no bespoke inductive congruence is written here),
    [QuotientCong], [QuotientCongLift], [cc_kernel], and the
    [hom_cast]/[strict_of_hom_cast] kit in which the uniqueness clause is
    phrased.  Only [ZRel] — the four generating equations — is new relation
    data.

    RELATION TO [Construction/Free/Groupoid.v].  That file runs the SAME
    recipe one level down: on a QUIVER, with the two cancellation relations
    and nothing else.  Its [sedge] is this file's [ZEdge] at [W = WAll]
    with the membership witness erased, its [FreeSigned] is [FreeZigZag],
    and its [fgr_left]/[fgr_right] are [zr_inv_l]/[zr_inv_r]; what is added
    here is (a) the identity and composition relations of the source
    CATEGORY, which is what makes [ZigZagProj] a functor out of [C] rather
    than a map out of a bare quiver, and (b) the class parameter [W].
    [C[C⁻¹]] is accordingly a further quotient of the free groupoid on the
    underlying quiver of [C], and that is not left as prose:
    [FreeGroupoidToFractions] exhibits the comparison functor, produced by
    the free groupoid's own universal property, identity on objects and
    carrying positive generators to the images of [C]'s morphisms
    ([FreeGroupoidToFractions_pos], [FreeGroupoidToFractions_obj]).  The two
    hom TYPES are not literally the same — [sedge] uses a bare sum where
    [ZEdge] must use a sigma to carry the [W]-membership witness — so the
    comparison is a functor, not an identity.

    NOT [Construction/Localization.v].  That file is a DIFFERENT
    construction and must not be conflated with this one: it is reflective
    orthogonal-subcategory localization, whose [WLocal] and full subcategory
    [C_W] land in the full subcategory of [W]-local OBJECTS, under a
    [Reflective] hypothesis.  This file constructs [C[W⁻¹]] by generators
    and relations, with the same objects as [C], and needs no hypothesis on
    [C] or [W] whatever.

    THE CLASS PARAMETER, AND #1028.  Parameterizing over [W] cost one sigma
    in [ZEdge] and a witness argument on [zbwd]; nothing else in the
    development notices, and the whole universal property is proved at
    general [W].  A Gabriel-Zisman localization at a class [W] should
    therefore INSTANTIATE [FracZigZag W] rather than rebuild it.  Nothing here
    assumes a calculus of fractions (Ore conditions): the morphisms are
    arbitrary zig-zag words, not spans, so no roof-shaped normal form is
    claimed and none is proved.

    WHAT THE UNIVERSAL PROPERTY SAYS, AND AT WHAT STRENGTH.  A functor
    [F : C ⟶ D] that inverts every [W]-morphism extends to [ZigZagLift]
    along the projection ([ZigZagLift_factors]), and does so uniquely
    ([ZigZagLift_unique], [ZigZagLift_unique_strict]).  Both halves are
    stated at STRICT strength — an equality of functors in [StrictCat],
    i.e. Leibniz equality on objects together with [≈] on morphisms
    conjugated by [hom_cast] — which is the strength
    [Construction/Quotient.v]'s [QuotientLift_unique] and
    [Construction/Free/Groupoid.v]'s [FreeGroupoidFunctor_unique] are
    stated at.  In the [Fractions] case the hypothesis on [F] is automatic
    for a groupoid target, and [fractions_universal] bundles existence and
    uniqueness in the shape [free_groupoid_universal] uses, while
    [Fractions_UMP] packages the same content as a [Unique] record over
    [Functor_StrictEq_Setoid] and [Fractions_proj_epic] reads off the
    injective half of the resulting bijection.  [frac_restrict],
    [frac_restrict_recovers] and [frac_extend_restrict] give the two round
    trips.

    THE CONGRUENCE DOES NOT COLLAPSE EVERYTHING.  [FractionsProj_separates]
    says a groupoid-valued functor separating two morphisms of [C] keeps them
    separate in [C[C⁻¹]] — it factors through the projection, so no equation
    the congruence imposes can merge them.  The unconditional case is
    [FractionsProj_Faithful]: when [C] is ALREADY a groupoid there is nothing
    left to invert and the projection is [Faithful], the identity functor
    being the separating one; [FractionsProj_Faithful_core] instantiates that
    at the core of an arbitrary category ([Construction/Groupoid.v]'s
    [Groupoid C], a groupoid by [Structure/Groupoid.v]'s [core_is_groupoid]),
    so the statement has an inhabitant for every [C] and is not conditional
    on finding a groupoid.

    WHAT IS NOT DELIVERED, AND WHY — MEASURED, NOT ESTIMATED.  The
    adjunction is exhibited as its universal property, not as an
    [Adjunction] record.  An earlier revision of this paragraph gave the
    reason as "there is no category [Grpd] of groupoids in tree"; that was
    true when this file was written and is now FALSE — Instance/Grpd.v
    landed alongside it, defining [Grpd] as the full subcategory of [Cat]
    cut out by [IsGroupoid], with [Grpd_Incl] its full and faithful
    inclusion.  The real obstruction is finer and is a STRENGTH mismatch.

    The pieces do fit on the object side: [(Fractions C; Fractions_IsGroupoid C)]
    types as an [obj[Grpd]] and [FractionsProj C] types as
    [C ~{Cat}~> fobj[Grpd_Incl] (Fractions C; …)], both checked.  What does
    not fit is the [∃!] clause.  [universal_arrow_from_UMP] wants it at the
    AMBIENT's hom-setoid, and [Grpd] inherits [Cat]'s [Functor_Setoid];
    [Fractions_UMP_groupoid] supplies it at [Functor_StrictEq_Setoid].
    Feeding the one to the other is refused with

      The term "Fractions_UMP_groupoid `2 (d') f" has type
       "∃! L : Fractions C ⟶ `1 (d'), f ≈ L ◯ FractionsProj C"
      while it is expected to have type
       "∃! g : frac_obj C ~{ Grpd }~> d', f ≈ fmap[Grpd_Incl] g ∘ FractionsProj C".

    EXISTENCE transfers: Instance/StrictCat/ToCat.v:57's
    [strict_equiv_implies_fun_equiv] takes a [Functor_StrictEq_Setoid]
    equality to a [Functor_Setoid] one.  UNIQUENESS DOES NOT, and that is
    the whole gap: a functor factoring [F] only up to natural isomorphism
    need not factor it up to object equality, so strict uniqueness says
    nothing about it.

    TWO ROUTES CLOSE THIS, and neither is attempted here.  (a) Restate the
    universal property at [Functor_Setoid] strength, which means redoing
    [Fractions_UMP]'s uniqueness argument against natural isomorphism
    instead of the transport-along-[eq] reasoning it now uses.  (b) Build
    [Grpd] over [StrictCat] instead of [Cat]; the audit of this file did
    exactly that in about thirty-five lines and obtained a real
    [Adjunction] record, so the LEFT adjunction is available over the
    strict ambient today.  Route (b) is cheap for this half and expensive
    for the other: [Incl_Core_Adjunction] is built over [Cat] and its
    hom-setoid isomorphism is a natural-isomorphism statement, so moving it
    to [StrictCat] would strengthen what it must prove.  Riehl's triple
    [Fractions ⊣ Incl ⊣ Core] therefore is NOT assembled over one ambient
    here; the two adjunctions live at different strengths, and choosing
    which to move is a decision about the tree rather than about this
    file.  It is filed as a follow-on.  Nothing else about
    the right adjoint — the core functor [Cat ⟶ Grpd] and [Incl ⊣ Core] —
    is in this file.  Nor is there a refutation-probe file under [Test/], so
    none of the strengths above is guarded against later drift; there is no
    functoriality of [Fractions] in [C] and no naturality of the bijection in
    [C] or [D]; and the non-collapse results below are the only non-vacuity —
    nothing here exhibits a [C] whose projection is NOT faithful, so the
    reading in which [C[C⁻¹]] merely reproduces [C] is not refuted for any
    single [C].

    SCOPE, universes.  [QuotientCong] accepts only a [Category@{o h h}] with
    [o <= h]: the object and proof universes are constrained by
    [CongClosure]'s [cc_comp], which binds an intermediate object, and the
    hom and proof universes are identified.  That constraint is inherited
    verbatim, so [Fractions] and [FracZigZag] apply to a category whose objects
    do not live strictly above its homs — the small shape categories
    ([Instance/Two.v]'s [_2], [Instance/Parallel.v], [Instance/Roof.v],
    [Instance/One.v], [Instance/Zero.v]) are accepted, while [Sets], whose
    objects sit one universe above its homs, is refused.  [W] must land at
    or below the hom universe.

    SCOPE, witnesses.  [ZEdge_equiv] compares two backward letters by their
    underlying morphism of [C] alone, so two different proofs of [W x y f]
    give formal inverses that are [≈]-equal without being Leibniz-equal.
    That is deliberate: it is what makes [zbwd_respects] hold, and it is why
    the [W]-membership witness never appears in any equation below. *)

(* Transporting a two-sided inverse along object equalities: if [a] and [a']
   correspond under [hom_cast], so do their inverses. *)
Lemma hom_cast_inverse {D : Category} {A B A' B' : D}
  (α : A = A') (β : B = B')
  (a : A ~> B) (b : B ~> A) (a' : A' ~> B') (b' : B' ~> A')
  (Hab : a ∘ b ≈ id) (Hb'a' : b' ∘ a' ≈ id)
  (Haa' : hom_cast α β a ≈ a') :
  hom_cast β α b ≈ b'.
Proof.
  destruct α, β.
  change (hom_cast eq_refl eq_refl a) with a in Haa'.
  change (hom_cast eq_refl eq_refl b) with b.
  rewrite Haa' in Hab.
  exact (comp_inverse_unique a' b b' Hab Hb'a').
Qed.

(* A [hom_cast] agreement read backwards. *)
Lemma hom_cast_sym {D : Category} {x y x' y' : D} (ex : x = x') (ey : y = y')
  (f : x ~> y) (g : x' ~> y') :
  hom_cast ex ey f ≈ g → hom_cast (eq_sym ex) (eq_sym ey) g ≈ f.
Proof. destruct ex, ey; intro H; now symmetry. Qed.

Section FracZigZag.

Context {C : Category}.

Variable W : ∀ x y : C, (x ~> y) → Type.

(* An edge of the glued quiver. *)
Definition ZEdge (x y : C) : Type :=
  ((x ~> y) + { f : y ~> x & W y x f })%type.

Definition ZEdge_equiv {x y : C} (a b : ZEdge x y) : Type :=
  match a, b with
  | inl f, inl g => f ≈ g
  | inr f, inr g => projT1 f ≈ projT1 g
  | _, _ => False
  end.

#[local] Instance ZEdge_equiv_Equivalence {x y : C} :
  Equivalence (@ZEdge_equiv x y).
Proof.
  constructor.
  - intros [f|[f w]]; simpl; reflexivity.
  - intros [f|[f w]] [g|[g v]] H; simpl in *;
      solve [ destruct H | now symmetry ].
  - intros [f|[f w]] [g|[g v]] [h|[h u]] H1 H2; simpl in *;
      solve [ destruct H1 | destruct H2 | now transitivity g ].
Qed.

Program Definition ZQuiver : Quiver := {|
  nodes := @obj C;
  edges := ZEdge;
  edgeset := fun x y => {| equiv := @ZEdge_equiv x y |}
|}.

Definition FreeZigZag : Category := FreeOnQuiver ZQuiver.

Definition zfwd {x y : C} (f : x ~> y) : x ~{FreeZigZag}~> y :=
  tlist_singleton (inl f).

Definition zbwd {x y : C} (f : x ~> y) (w : W x y f) : y ~{FreeZigZag}~> x :=
  tlist_singleton (inr (existT _ f w)).

Lemma zsingleton_respects {x y : C} (a b : ZEdge x y) :
  ZEdge_equiv a b →
  @equiv _ (@homset FreeZigZag x y) (tlist_singleton a) (tlist_singleton b).
Proof.
  intro H.
  unfold tlist_singleton; simpl;
    unfold tlist_quiver_equiv, tlist'_quiver_equiv.
  exists eq_refl; [ exact H | reflexivity ].
Qed.

Lemma zfwd_respects {x y : C} (f g : x ~> y) :
  f ≈ g → @equiv _ (@homset FreeZigZag x y) (zfwd f) (zfwd g).
Proof. apply (zsingleton_respects (inl f) (inl g)). Qed.

Lemma zbwd_respects {x y : C} (f g : x ~> y) (v : W x y f) (w : W x y g) :
  f ≈ g → @equiv _ (@homset FreeZigZag y x) (zbwd f v) (zbwd g w).
Proof.
  apply (zsingleton_respects (inr (existT _ f v)) (inr (existT _ g w))).
Qed.

(* The generating relations. *)
Inductive ZRel : ∀ x y : C,
    (x ~{FreeZigZag}~> y) → (x ~{FreeZigZag}~> y) → Type :=
  | zr_id (x : C) : ZRel x x (zfwd (@id C x)) (@id FreeZigZag x)
  | zr_comp {x y z : C} (f : x ~> y) (g : y ~> z) :
      ZRel x z (zfwd g ∘ zfwd f) (zfwd (g ∘ f))
  | zr_inv_l {x y : C} (f : x ~> y) (w : W x y f) :
      ZRel x x (zbwd f w ∘ zfwd f) (@id FreeZigZag x)
  | zr_inv_r {x y : C} (f : x ~> y) (w : W x y f) :
      ZRel y y (zfwd f ∘ zbwd f w) (@id FreeZigZag y).

Definition FracZigZag : Category := QuotientCong FreeZigZag ZRel.

Definition ZigZagProj : C ⟶ FracZigZag :=
  Build_Functor C FracZigZag
    (fun x => x)
    (fun x y f => zfwd f)
    (fun x y f g Hfg => cc_equiv (zfwd_respects f g Hfg))
    (fun x => cc_gen (zr_id x))
    (fun x y z f g => cc_sym (cc_gen (zr_comp g f))).

(* Every W-morphism becomes invertible in the localization. *)
Definition ZigZagProj_inverts {x y : C} (f : x ~> y) (w : W x y f) :
  @IsIsomorphism FracZigZag x y (fmap[ZigZagProj] f) :=
  @Build_IsIsomorphism FracZigZag x y (fmap[ZigZagProj] f)
    (zbwd f w) (cc_gen (zr_inv_r f w)) (cc_gen (zr_inv_l f w)).

(* ...and so, symmetrically, does the formal inverse itself. *)
Definition zbwd_IsIso {x y : C} (f : x ~> y) (w : W x y f) :
  @IsIsomorphism FracZigZag y x (zbwd f w) :=
  @Build_IsIsomorphism FracZigZag y x (zbwd f w)
    (zfwd f) (cc_gen (zr_inv_l f w)) (cc_gen (zr_inv_r f w)).

(* The two cancellation equations, as they read after any functor out of the
   localization. *)
Lemma zbwd_zfwd_functor {D : Category} (K : FracZigZag ⟶ D)
  {x y : C} (f : x ~> y) (w : W x y f) :
  fmap[K] (zbwd f w) ∘ fmap[K] (zfwd f) ≈ id.
Proof.
  rewrite <- fmap_comp.
  transitivity (fmap[K] (@id FracZigZag x)).
  - apply fmap_respects; exact (cc_gen (zr_inv_l f w)).
  - apply fmap_id.
Qed.

Lemma zfwd_zbwd_functor {D : Category} (K : FracZigZag ⟶ D)
  {x y : C} (f : x ~> y) (w : W x y f) :
  fmap[K] (zfwd f) ∘ fmap[K] (zbwd f w) ≈ id.
Proof.
  rewrite <- fmap_comp.
  transitivity (fmap[K] (@id FracZigZag y)).
  - apply fmap_respects; exact (cc_gen (zr_inv_r f w)).
  - apply fmap_id.
Qed.

(** ** The universal property *)

Context {D : Category}.
Variable F : C ⟶ D.
Variable Winv : ∀ (x y : C) (f : x ~> y), W x y f →
  @IsIsomorphism D (F x) (F y) (fmap[F] f).

Definition winv {x y : C} (g : y ~> x) (w : W y x g) : F x ~{D}~> F y :=
  @two_sided_inverse D (F y) (F x) (fmap[F] g) (Winv y x g w).

Lemma winv_right {x y : C} (g : y ~> x) (w : W y x g) :
  fmap[F] g ∘ winv g w ≈ id.
Proof. exact (@is_right_inverse D _ _ _ (Winv y x g w)). Qed.

Lemma winv_left {x y : C} (g : y ~> x) (w : W y x g) :
  winv g w ∘ fmap[F] g ≈ id.
Proof. exact (@is_left_inverse D _ _ _ (Winv y x g w)). Qed.

Definition zump_edge {x y : C} (e : ZEdge x y) : F x ~{D}~> F y :=
  match e with
  | inl f => fmap[F] f
  | inr (existT _ g w) => winv g w
  end.

Lemma zump_edge_respects {x y : C} (a b : ZEdge x y) :
  ZEdge_equiv a b → zump_edge a ≈ zump_edge b.
Proof.
  destruct a as [f|[g w]], b as [f'|[g' w']]; simpl; intro H;
    try solve [ destruct H ].
  - now rewrite H.
  - apply (comp_inverse_unique (fmap[F] g')).
    + rewrite <- H; apply winv_right.
    + apply winv_left.
Qed.

Program Definition zump_qhom : QuiverHomomorphism ZQuiver (QuiverOfCat D) := {|
  fnodes := fun x => F x;
  fedgemap := fun x y e => zump_edge e
|}.
Next Obligation. repeat intro; now apply zump_edge_respects. Qed.

Definition zump_free : FreeZigZag ⟶ D := InducedFunctor ZQuiver zump_qhom.

Lemma zump_free_fwd {x y : C} (f : x ~> y) :
  fmap[zump_free] (zfwd f) ≈ fmap[F] f.
Proof. simpl; apply id_left. Qed.

Lemma zump_free_bwd {x y : C} (f : x ~> y) (w : W x y f) :
  fmap[zump_free] (zbwd f w) ≈ winv f w.
Proof. simpl; apply id_left. Qed.

(* [zump_free] merges every generating relation, hence (by [cc_kernel],
   inside [QuotientCongLift]) the whole generated congruence. *)
Lemma zump_merges : ∀ (x y : C) (a b : x ~{FreeZigZag}~> y),
  ZRel x y a b → fmap[zump_free] a ≈ fmap[zump_free] b.
Proof.
  intros x y a b H; destruct H.
  - now rewrite zump_free_fwd, !fmap_id.
  - rewrite fmap_comp, !zump_free_fwd.
    now rewrite fmap_comp.
  - now rewrite fmap_comp, zump_free_bwd, zump_free_fwd, fmap_id, winv_left.
  - now rewrite fmap_comp, zump_free_fwd, zump_free_bwd, fmap_id, winv_right.
Qed.

(* The induced functor out of the localization. *)
Definition ZigZagLift : FracZigZag ⟶ D :=
  @QuotientCongLift FreeZigZag D ZRel zump_free zump_merges.

Lemma ZigZagLift_fwd {x y : C} (f : x ~> y) :
  fmap[ZigZagLift] (fmap[ZigZagProj] f) ≈ fmap[F] f.
Proof. exact (zump_free_fwd f). Qed.

Lemma ZigZagLift_bwd {x y : C} (f : x ~> y) (w : W x y f) :
  fmap[ZigZagLift] (zbwd f w) ≈ winv f w.
Proof. exact (zump_free_bwd f w). Qed.

(* The factorization, as one equality of functors in [StrictCat]. *)
Lemma ZigZagLift_factors :
  @equiv _ (@Functor_StrictEq_Setoid C D) (ZigZagLift ◯ ZigZagProj) F.
Proof.
  apply (strict_of_hom_cast (ZigZagLift ◯ ZigZagProj) F (fun _ => eq_refl)).
  intros x y f; exact (ZigZagLift_fwd f).
Qed.

(** *** Uniqueness of the factorization *)

Lemma ZigZagLift_unique_edge (G : FracZigZag ⟶ D)
  (Hobj : ∀ x : C, fobj[G] x = fobj[F] x)
  (Hmor : ∀ (x y : C) (f : x ~{C}~> y),
      hom_cast (Hobj x) (Hobj y) (fmap[G] (fmap[ZigZagProj] f)) ≈ fmap[F] f)
  {x y : C} (e : ZEdge x y) :
  hom_cast (Hobj x) (Hobj y) (fmap[G] (tlist_singleton e))
    ≈ fmap[ZigZagLift] (tlist_singleton e).
Proof.
  destruct e as [f | [g w]].
  - transitivity (fmap[F] f).
    + exact (Hmor x y f).
    + symmetry; exact (ZigZagLift_fwd f).
  - unshelve eapply (hom_cast_inverse (Hobj y) (Hobj x)
                       (fmap[G] (zfwd g)) _
                       (fmap[ZigZagLift] (zfwd g)) _).
    + exact (zfwd_zbwd_functor G g w).
    + exact (zbwd_zfwd_functor ZigZagLift g w).
    + transitivity (fmap[F] g).
      * exact (Hmor y x g).
      * symmetry; exact (ZigZagLift_fwd g).
Qed.

(* Uniqueness: a competitor agreeing with [F] after precomposition with the
   projection is pinned on every zig-zag word, by induction on the word.  The
   backward letters are pinned because a functor carries the two cancellation
   equations to two-sided inverses, and inverses are unique. *)
Lemma ZigZagLift_unique (G : FracZigZag ⟶ D)
  (Hobj : ∀ x : C, fobj[G] x = fobj[F] x)
  (Hmor : ∀ (x y : C) (f : x ~{C}~> y),
      hom_cast (Hobj x) (Hobj y) (fmap[G] (fmap[ZigZagProj] f)) ≈ fmap[F] f) :
  ∀ (x y : C) (u : x ~{FracZigZag}~> y),
    hom_cast (Hobj x) (Hobj y) (fmap[G] u) ≈ fmap[ZigZagLift] u.
Proof.
  intros x y u.
  induction u as [| a b e rest IH].
  - rewrite !fmap_id; apply hom_cast_id.
  - assert (Hu : (e ::: rest)
                 = @compose FracZigZag a b y rest (tlist_singleton e))
      by apply tlist_app_cons.
    rewrite Hu, !fmap_comp.
    rewrite <- (hom_cast_comp (Hobj a) (Hobj b) (Hobj y)
                  (fmap[G] rest) (fmap[G] (tlist_singleton e))).
    rewrite IH, (ZigZagLift_unique_edge G Hobj Hmor e).
    reflexivity.
Qed.

(* The same uniqueness, as one equality of functors in [StrictCat]. *)
Corollary ZigZagLift_unique_strict (G : FracZigZag ⟶ D)
  (Hobj : ∀ x : C, fobj[G] x = fobj[F] x)
  (Hmor : ∀ (x y : C) (f : x ~{C}~> y),
      hom_cast (Hobj x) (Hobj y) (fmap[G] (fmap[ZigZagProj] f)) ≈ fmap[F] f) :
  @equiv _ (@Functor_StrictEq_Setoid FracZigZag D) G ZigZagLift.
Proof.
  apply (strict_of_hom_cast G ZigZagLift Hobj).
  exact (ZigZagLift_unique G Hobj Hmor).
Qed.

End FracZigZag.

Arguments ZEdge {C} W x y.
Arguments ZQuiver {C} W.
Arguments FreeZigZag {C} W.
Arguments zfwd {C} W {x y} f.
Arguments zbwd {C} W {x y} f w.
Arguments ZRel {C} W x y _ _.
Arguments FracZigZag {C} W.
Arguments ZigZagProj {C} W.

(** * The category of fractions [C[C⁻¹]] *)

(* The class consisting of every morphism.  It is [Type]-valued because the
   generating relation [ZRel] is, and [unit] rather than [True] so that no
   [Prop]-elimination restriction can arise. *)
Definition WAll (C : Category) : ∀ x y : C, (x ~> y) → Type :=
  fun _ _ _ => unit.

Definition Fractions (C : Category) : Category := FracZigZag (WAll C).

Definition FractionsProj (C : Category) : C ⟶ Fractions C :=
  ZigZagProj (WAll C).

(* Every morphism of [C] becomes invertible in [C[C⁻¹]]. *)
Definition FractionsProj_inverts {C : Category} {x y : C} (f : x ~> y) :
  @IsIsomorphism (Fractions C) x y (fmap[FractionsProj C] f) :=
  ZigZagProj_inverts (WAll C) f tt.

(* Composites of isomorphisms are isomorphisms, in the [IsIsomorphism]
   (predicate) presentation.  Theory/Isomorphism.v states this only for the
   bundled [Isomorphism] ([iso_compose]); this is the same fact in the
   presentation [IsGroupoid] is stated over. *)
Definition frac_IsIso_compose {E : Category} {x y z : E} {f : y ~> z} {g : x ~> y}
  (Hf : @IsIsomorphism E y z f) (Hg : @IsIsomorphism E x y g) :
  @IsIsomorphism E x z (f ∘ g).
Proof.
  unshelve eapply Build_IsIsomorphism.
  - exact (@two_sided_inverse E x y g Hg ∘ @two_sided_inverse E y z f Hf).
  - rewrite comp_assoc,
      <- (comp_assoc f g (@two_sided_inverse E x y g Hg)).
    rewrite (@is_right_inverse E x y g Hg), id_right.
    apply (@is_right_inverse E y z f Hf).
  - rewrite comp_assoc,
      <- (comp_assoc (@two_sided_inverse E x y g Hg)
                     (@two_sided_inverse E y z f Hf) f).
    rewrite (@is_left_inverse E y z f Hf), id_right.
    apply (@is_left_inverse E x y g Hg).
Defined.

Definition frac_IsIso_id {E : Category} (x : E) : @IsIsomorphism E x x id :=
  @Build_IsIsomorphism E x x id id (id_left id) (id_left id).

(* Riehl 4.1.15, the half that makes [Fractions] land in groupoids: every
   zig-zag word is invertible, by induction on the word — the empty word is
   the identity, and a word [e ::: rest] is [rest ∘ (e)], a composite of two
   invertible morphisms. *)
Theorem Fractions_IsGroupoid (C : Category) : IsGroupoid (Fractions C).
Proof.
  intros x y u.
  induction u as [| a b e rest IH].
  - exact (frac_IsIso_id (E:=Fractions C) y).
  - assert (Hu : (e ::: rest)
                 = @compose (Fractions C) a b y rest (tlist_singleton e))
      by apply tlist_app_cons.
    rewrite Hu.
    apply (frac_IsIso_compose IH).
    destruct e as [f | [g u]].
    + exact (ZigZagProj_inverts (WAll C) f tt).
    + exact (zbwd_IsIso (WAll C) g u).
Defined.

(** ** The universal property of [C[C⁻¹]] *)

Section FractionsUMP.

Context {C D : Category}.
Variable F : C ⟶ D.
Variable Finv : ∀ (x y : C) (f : x ~> y),
  @IsIsomorphism D (F x) (F y) (fmap[F] f).

Definition FractionsLift : Fractions C ⟶ D :=
  ZigZagLift (WAll C) F (fun x y f _ => Finv x y f).

Lemma FractionsLift_fwd {x y : C} (f : x ~> y) :
  fmap[FractionsLift] (fmap[FractionsProj C] f) ≈ fmap[F] f.
Proof. exact (ZigZagLift_fwd (WAll C) F (fun x y f _ => Finv x y f) f). Qed.

Lemma FractionsLift_factors :
  @equiv _ (@Functor_StrictEq_Setoid C D) (FractionsLift ◯ FractionsProj C) F.
Proof. exact (ZigZagLift_factors (WAll C) F (fun x y f _ => Finv x y f)). Qed.

Lemma FractionsLift_unique (G : Fractions C ⟶ D)
  (E : @equiv _ (@Functor_StrictEq_Setoid C D) F (G ◯ FractionsProj C)) :
  @equiv _ (@Functor_StrictEq_Setoid (Fractions C) D) FractionsLift G.
Proof.
  destruct (hom_cast_of_strict F (G ◯ FractionsProj C) E) as [Hobj Hmor].
  symmetry.
  exact (ZigZagLift_unique_strict (WAll C) F (fun x y f _ => Finv x y f) G
           (fun x => eq_sym (Hobj x))
           (fun x y f => hom_cast_sym (Hobj x) (Hobj y) _ _ (Hmor x y f))).
Qed.

Definition Fractions_UMP :
  @Unique _ (@Functor_StrictEq_Setoid (Fractions C) D)
    (fun L => @equiv _ (@Functor_StrictEq_Setoid C D)
                F (L ◯ FractionsProj C)) :=
  @Build_Unique _ (@Functor_StrictEq_Setoid (Fractions C) D) _
    FractionsLift
    (symmetry FractionsLift_factors)
    FractionsLift_unique.

End FractionsUMP.

(** ** Riehl 4.1.15, the left half, at a groupoid target *)

(* Every functor into a groupoid inverts every morphism, so the hypothesis of
   [Fractions_UMP] is automatic there. *)
Definition Fractions_UMP_groupoid {C D : Category} (Dg : IsGroupoid D)
  (F : C ⟶ D) :
  @Unique _ (@Functor_StrictEq_Setoid (Fractions C) D)
    (fun L => @equiv _ (@Functor_StrictEq_Setoid C D)
                F (L ◯ FractionsProj C)) :=
  Fractions_UMP F (fun x y f => Dg (F x) (F y) (fmap[F] f)).

(* The other half of the hom-set bijection: precomposition with the
   projection is injective on functors into a groupoid.  Two functors out of
   [C[C⁻¹]] that agree on [C] agree everywhere. *)
Corollary Fractions_proj_epic {C D : Category} (Dg : IsGroupoid D)
  (L L' : Fractions C ⟶ D)
  (E : @equiv _ (@Functor_StrictEq_Setoid C D)
         (L ◯ FractionsProj C) (L' ◯ FractionsProj C)) :
  @equiv _ (@Functor_StrictEq_Setoid (Fractions C) D) L L'.
Proof.
  pose (U := Fractions_UMP_groupoid Dg (L ◯ FractionsProj C)).
  transitivity (unique_obj U).
  - symmetry; exact (uniqueness U L (reflexivity _)).
  - exact (uniqueness U L' E).
Qed.

(** ** The bridge to the free groupoid on a quiver *)

(* [Construction/Free/Groupoid.v] runs the same recipe one level down: on the
   QUIVER of [C], with the two cancellation relations but WITHOUT the
   composition and identity relations of [C].  [C[C⁻¹]] is therefore a
   further quotient of [FreeGroupoid (QuiverOfCat C)], and the comparison
   functor is the one the free groupoid's own universal property produces —
   no new construction is needed to exhibit it. *)
Definition FreeGroupoidToFractions (C : Category) :
  FreeGroupoid (QuiverOfCat C) ⟶ Fractions C :=
  FreeGroupoidFunctor (QuiverOfCat C) (Fractions_IsGroupoid C)
    (QuiverHomomorphismOfFunctor C (Fractions C) (FractionsProj C)).

(* It carries a positive generator to the image of that morphism of [C]. *)
Lemma FreeGroupoidToFractions_pos {C : Category} {x y : C} (f : x ~> y) :
  fmap[FreeGroupoidToFractions C] (fgpos (G:=QuiverOfCat C) f)
    ≈ fmap[FractionsProj C] f.
Proof.
  exact (FreeGroupoidFunctor_gen (QuiverOfCat C) (Fractions_IsGroupoid C)
           (QuiverHomomorphismOfFunctor C (Fractions C) (FractionsProj C)) f).
Qed.

(* ...and it is the identity on objects. *)
Lemma FreeGroupoidToFractions_obj {C : Category} (x : C) :
  fobj[FreeGroupoidToFractions C] x = x.
Proof. reflexivity. Qed.

(** ** The universal property, bundled

    Riehl §4.1 Example 4.1.15, the left-adjoint half, in one statement, in
    the shape [Construction/Free/Groupoid.v]'s [free_groupoid_universal]
    uses: the object agreement [Hobj] is nested INSIDE the bundle, because
    for an abstract competitor [K'] the objects [fobj[K'] x] and [fobj[F] x]
    are not convertible until it is in scope. *)

Theorem fractions_universal {C D : Category} (Dg : IsGroupoid D)
  (F : C ⟶ D) :
  { K : Fractions C ⟶ D &
  { Hobj : ∀ x : C, fobj[K] x = fobj[F] x &
    ((∀ (x y : C) (f : x ~> y),
        hom_cast (Hobj x) (Hobj y)
          (fmap[K] (fmap[FractionsProj C] f)) ≈ fmap[F] f) *
     (∀ (K' : Fractions C ⟶ D)
        (Hobj' : ∀ x : C, fobj[K'] x = fobj[F] x),
        (∀ (x y : C) (f : x ~> y),
           hom_cast (Hobj' x) (Hobj' y)
             (fmap[K'] (fmap[FractionsProj C] f)) ≈ fmap[F] f) →
        ∀ (x y : C) (u : x ~{Fractions C}~> y),
          hom_cast (Hobj' x) (Hobj' y) (fmap[K'] u)
            ≈ hom_cast (Hobj x) (Hobj y) (fmap[K] u)))%type } }.
Proof.
  pose (Finv := fun (x y : C) (f : x ~> y) => Dg (F x) (F y) (fmap[F] f)).
  exists (FractionsLift F Finv), (fun _ => eq_refl).
  split.
  - intros x y f; exact (FractionsLift_fwd F Finv f).
  - intros K' Hobj' Hgen x y u.
    exact (ZigZagLift_unique (WAll C) F (fun x y f _ => Finv x y f)
             K' Hobj' Hgen x y u).
Qed.

(** ** The two round trips

    Restricting a functor out of [C[C⁻¹]] along the projection gives back a
    functor out of [C]; re-extending recovers it, and extending a functor and
    then restricting recovers that.  Both are stated at STRICT strength (an
    equality of functors in [StrictCat]), in the manner of
    [Construction/Free/Groupoid.v]'s [fg_restrict_recovers_strict] and
    [fg_extend_restrict]. *)

Definition frac_restrict {C D : Category} (S : Fractions C ⟶ D) : C ⟶ D :=
  S ◯ FractionsProj C.

Lemma frac_restrict_recovers {C D : Category} (Dg : IsGroupoid D)
  (S : Fractions C ⟶ D) :
  @equiv _ (@Functor_StrictEq_Setoid (Fractions C) D)
    (FractionsLift (frac_restrict S)
       (fun x y f => Dg _ _ (fmap[frac_restrict S] f))) S.
Proof.
  apply FractionsLift_unique.
  reflexivity.
Qed.

Lemma frac_extend_restrict {C D : Category} (F : C ⟶ D)
  (Finv : ∀ (x y : C) (f : x ~> y), @IsIsomorphism D (F x) (F y) (fmap[F] f)) :
  @equiv _ (@Functor_StrictEq_Setoid C D)
    (frac_restrict (FractionsLift F Finv)) F.
Proof. exact (FractionsLift_factors F Finv). Qed.

(** ** The congruence merges, but it does not merge everything

    A groupoid-valued functor that separates two morphisms of [C] keeps them
    separate in [C[C⁻¹]], because it factors through the projection.  This is
    the general non-collapse statement; it needs no concrete witness, only a
    functor that already separates. *)

Lemma FractionsProj_separates {C D : Category} (Dg : IsGroupoid D)
  (F : C ⟶ D) {x y : C} (f g : x ~> y)
  (H : fmap[F] f ≈ fmap[F] g → False) :
  @equiv _ (@homset (Fractions C) x y)
    (fmap[FractionsProj C] f) (fmap[FractionsProj C] g) → False.
Proof.
  intro E.
  apply H.
  pose (Finv := fun (a b : C) (h : a ~> b) => Dg (F a) (F b) (fmap[F] h)).
  rewrite <- (FractionsLift_fwd F Finv f), <- (FractionsLift_fwd F Finv g).
  now rewrite E.
Qed.

(* The sharpest unconditional form: when [C] is ALREADY a groupoid there is
   nothing left to invert, and the projection merges nothing at all — it is
   faithful.  The separating functor is the identity, which the groupoid
   hypothesis makes admissible for [FractionsLift]. *)
Definition FractionsProj_Faithful {C : Category} (Cg : IsGroupoid C) :
  Faithful (FractionsProj C).
Proof.
  unshelve econstructor.
  intros x y f g E.
  pose (Finv := fun (a b : C) (h : a ~> b) => Cg a b h).
  transitivity (fmap[FractionsLift (Id[C]) Finv] (fmap[FractionsProj C] f)).
  - symmetry; exact (FractionsLift_fwd (Id[C]) Finv f).
  - rewrite E; exact (FractionsLift_fwd (Id[C]) Finv g).
Defined.

(* An unconditional instance of that: the core of any category is a groupoid
   (Structure/Groupoid.v's [core_is_groupoid]), so localizing a core merges
   nothing. *)
Definition FractionsProj_Faithful_core (C : Category) :
  Faithful (FractionsProj (Groupoid C)) :=
  FractionsProj_Faithful (core_is_groupoid C).
