Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Functor.

Generalizable All Variables.

(** * The funny tensor product of categories

    nLab: https://ncatlab.org/nlab/show/funny+tensor+product

    The funny tensor product C □ D has the same objects as the cartesian
    product C ∏ D, but its morphisms (c1, d1) ~> (c2, d2) are words of steps,
    each step moving exactly ONE coordinate:

      an L-step  f : c1 ~> c2 in C   moves  (c1, d) ~> (c2, d);
      an R-step  g : d1 ~> d2 in D   moves  (c, d1) ~> (c, d2).

    The words are quotiented only by the relations that remember composition
    and identities in each coordinate separately.  Crucially there is NO
    relation commuting an L-step past an R-step: by contrast with C ∏ D, the
    square built from f : c1 ~> c2 and g : d1 ~> d2 does not commute in C □ D,
    and has two distinct diagonals (identified only by the comparison functor
    to C ∏ D).  The absence of this interchange law is the entire content of
    the construction.

    References:

    - F. Foltz, C. Lair, G. M. Kelly, "Algebraic categories with few monoidal
      biclosed structures or none", JPAA 17(2) (1980) 171-177,
      doi:10.1016/0022-4049(80)90082-1.  Up to isomorphism there are exactly
      two monoidal biclosed structures on Cat, and both are symmetric: the
      cartesian one (internal hom = functors and natural transformations) and
      the funny one (internal hom = functors and unnatural transformations).
    - Mark Weber, "Free products of higher operad algebras", TAC 28:2 (2013)
      24-65, §2: the generators-and-relations presentation used here, the
      pushout formula, and the comparison functor κ : C □ D ⟶ C ∏ D.
    - nLab, "funny tensor product": the pushout definition and the
      non-invariance under equivalence.

    A load-bearing caveat: the funny tensor is NOT invariant under equivalence
    of categories (with I the "walking isomorphism" chaotic groupoid on two
    objects, 1 □ 1 ≅ 1 while I □ I is equivalent to the group ℤ, freely
    generated by the interchange loop).  Consequently − □ − does NOT define a
    bifunctor on this library's weak [Cat] (whose hom-setoid identifies
    functors up to natural isomorphism): its [fmap_respects] is false.  The
    bifunctor and the symmetric monoidal structure live on [StrictCat]
    instead — the same shape of problem as the issue #138 discussion in
    Instance/StrictCat.v.  See Construction/Funny/Closed.v for the
    corresponding no-go results about stating the closed structure via
    [Adjunction] or [ClosedMonoidal]. *)

(* Gray's little brother: history, uses, and the computational reading

   nLab: https://ncatlab.org/nlab/show/Gray+tensor+product
   nLab: https://ncatlab.org/nlab/show/sesquicategory
   nLab: https://ncatlab.org/nlab/show/premonoidal+category

   The construction descends from dimension two.  John Gray introduced the
   Gray tensor product of 2-categories in "Formal Category Theory:
   Adjointness for 2-Categories" (Springer LNM 391, 1974); ignoring the
   2-cells in its definition leaves a canonical tensor product of plain
   categories "which has been called the funny tensor product" — the
   phrasing of Weber, whose abstract styles the result "Gray's little
   brother" and who attributes the coinage to no one (Weber, "Free products
   of higher operad algebras", TAC 28:2 (2013)).  The nLab calibrates the
   three tensors on one picture: in the tensor of the walking arrow with
   itself, the generating square commutes strictly for the cartesian
   product, commutes up to a specified isomorphism for the Gray tensor, and
   does not commute at all for the funny tensor.  Because Gray-categories
   suffice to model all tricategories (Gordon, Power and Street, Mem. AMS
   117, 1995), □ is the one-dimensional shadow of the tensor at the base of
   the semistrictness ladder.

   What the tensor classifies is evaluation order.  A functor out of C □ D
   is precisely a separately functorial assignment — the content of
   [SepFunctorial], its eliminator [FunnyUP], and the round trip through
   [toSep] below — functorial in each variable with no compatibility at all
   between the two actions, whereas a functor out of C ∏ D must
   additionally satisfy interchange.  It follows that the cartesian product
   is the quotient of □ by forgetting order: the comparison functor
   [FunnyToProduct] of Construction/Funny/Comparison.v is bijective on
   objects and full but not faithful ([funny_diagonals_distinct]), and the
   biclosed structure of the Foltz-Lair-Kelly classification is realized
   in-tree by the unnatural-transformation hom [UFun] of
   Construction/Funny/Hom.v with the currying and evaluation of
   Construction/Funny/Closed.v.

   Enrichment turns the missing law into structure.  A category enriched in
   the funny monoidal structure is precisely a sesquicategory, a notion
   credited to Ross Street ("Categorical Structures", Handbook of Algebra
   vol. 1, 1996; "sesqui" is Latin for "one and a half"): 2-cells whisker
   along 1-cells on either side, yet no horizontal composition is given,
   exactly because an enriched composition map is merely separately
   functorial.  Term rewriting supplied an early applied reading — rewrites
   whisker along contexts, with no interchange identification imposed
   between independent steps (Stell, "Modelling term rewriting systems by
   sesqui-categories", 1994).  One level down, a monoid in the funny
   monoidal structure — equivalently a one-object sesquicategory —
   is a strict premonoidal category in the sense of Power and Robinson,
   exactly as a monoid in the cartesian structure is a strict monoidal one
   (Power, Robinson, "Premonoidal categories and notions of computation",
   MSCS 7(5) 1997); the library proves the correspondence over
   [Funny_Monoidal] of Instance/StrictCat/Funny.v as [StrictPremonoidal] in
   Instance/StrictCat/Premonoid.v.  Premonoidal categories are the
   semantics of call-by-value effects: the Kleisli category of a strong
   monad is in general only premonoidal, full monoidal structure requiring
   a commutative monad, and the two composites around a square are the two
   orders in which a pair of effectful computations may run (Power-Robinson
   1997; the library's spine is Structure/Binoidal.v and
   Structure/Premonoidal.v).

   On one-object categories the tensor is classical algebra: for monoids M
   and N, M □ N is their coproduct in Mon — the free product, whose
   elements are the alternating words in nonidentity letters — while M × N
   is the direct product, and Weber names his operadic generalizations
   "free products" for this reason (Weber 2013, §2).  The header's I □ I
   example is the same phenomenon one categorical level up: nothing in the
   pushout forces the interchange loop to be trivial.  Read
   computationally, a [FunHom] word is a trace — an explicit interleaving
   of steps by two independent agents, remembered by [feq] up to per-agent
   composition and identity but never up to commuting independent steps
   past one another — and [FunnyToProduct] is the map that forgets the
   schedule.  The two diagonals of the fundamental square are the two
   sequencings of one effectful pair, "f then g" against "g then f":
   premonoidal semantics keeps them distinct, and cartesian semantics
   identifies them. *)

Section FunnyHom.

Context {C : Category}.
Context {D : Category}.

(* A morphism (c1,d1) ~> (c2,d2) of C □ D: a word of steps, each moving ONE
   coordinate.  Four scalar indices, never a pair.  NO constructor and NO
   relation commutes an L-step past an R-step: absence of interchange is the
   entire content (Weber TAC 28:2 §2; nLab "funny tensor product"; FLK
   1980). *)
Inductive FunHom : C → D → C → D → Type :=
  | fnil {c : C} {d : D} : FunHom c d c d
  | fconsL {c1 c2 : C} {d1 : D} (f : c1 ~{C}~> c2)
           {c3 : C} {d3 : D} (t : FunHom c2 d1 c3 d3) : FunHom c1 d1 c3 d3
  | fconsR {c1 : C} {d1 d2 : D} (g : d1 ~{D}~> d2)
           {c3 : C} {d3 : D} (t : FunHom c1 d2 c3 d3) : FunHom c1 d1 c3 d3.

(* Singleton words: the generating steps. *)
Definition lstep {c1 c2 : C} {d : D} (f : c1 ~{C}~> c2) : FunHom c1 d c2 d :=
  fconsL f fnil.
Definition rstep {c : C} {d1 d2 : D} (g : d1 ~{D}~> d2) : FunHom c d1 c d2 :=
  fconsR g fnil.

(* Words read source-to-target; append composes indices on the nose. *)
Fixpoint fapp {c1 d1 c2 d2} (t : FunHom c1 d1 c2 d2) :
  ∀ {c3 d3}, FunHom c2 d2 c3 d3 → FunHom c1 d1 c3 d3 :=
  match t in FunHom a b c d
        return ∀ c3 d3, FunHom c d c3 d3 → FunHom a b c3 d3 with
  | fnil        => fun _ _ u => u
  | fconsL f t' => fun _ _ u => fconsL f (fapp t' u)
  | fconsR g t' => fun _ _ u => fconsR g (fapp t' u)
  end.

Lemma fapp_nil_r {c1 d1 c2 d2} (t : FunHom c1 d1 c2 d2) : fapp t fnil = t.
Proof.
  induction t; simpl.
  - reflexivity.
  - now rewrite IHt.
  - now rewrite IHt.
Qed.

Lemma fapp_assoc {c1 d1 c2 d2 c3 d3 c4 d4} (t : FunHom c1 d1 c2 d2)
      (u : FunHom c2 d2 c3 d3) (v : FunHom c3 d3 c4 d4) :
  fapp t (fapp u v) = fapp (fapp t u) v.
Proof.
  revert u v; induction t; simpl; intros.
  - reflexivity.
  - now rewrite IHt.
  - now rewrite IHt.
Qed.

(* Congruence: equivalence + cons-congruence (payload ≈-respect, mandatory
   for nested payloads) + head-position same-side fusion + head-position
   identity removal.  Type-valued: it is eliminated into the crelation ≈ of
   arbitrary target categories, so Prop is not an option.  Head+tail form
   makes append-congruence derivable ([fapp_feq_l]/[fapp_feq_r] below) with
   no app constructor.  Source-to-target order: the word "f then f'" fuses to
   the composite f' ∘ f. *)
Inductive feq : ∀ {c1 d1 c2 d2},
    FunHom c1 d1 c2 d2 → FunHom c1 d1 c2 d2 → Type :=
  | feq_refl {c1 d1 c2 d2} (t : FunHom c1 d1 c2 d2) : feq t t
  | feq_sym {c1 d1 c2 d2} (t u : FunHom c1 d1 c2 d2) : feq t u → feq u t
  | feq_trans {c1 d1 c2 d2} (t u v : FunHom c1 d1 c2 d2) :
      feq t u → feq u v → feq t v
  | feq_consL {c1 c2 : C} {d1 : D} (f f' : c1 ~{C}~> c2) {c3 d3}
      (t u : FunHom c2 d1 c3 d3) :
      f ≈ f' → feq t u → feq (fconsL f t) (fconsL f' u)
  | feq_consR {c1 : C} {d1 d2 : D} (g g' : d1 ~{D}~> d2) {c3 d3}
      (t u : FunHom c1 d2 c3 d3) :
      g ≈ g' → feq t u → feq (fconsR g t) (fconsR g' u)
  | feq_fuseL {c1 c2 c3 : C} {d1 : D} (f : c1 ~{C}~> c2) (f' : c2 ~{C}~> c3)
      {c4 d4} (t : FunHom c3 d1 c4 d4) :
      feq (fconsL f (fconsL f' t)) (fconsL (f' ∘ f) t)
  | feq_fuseR {c1 : C} {d1 d2 d3 : D} (g : d1 ~{D}~> d2) (g' : d2 ~{D}~> d3)
      {c4 d4} (t : FunHom c1 d3 c4 d4) :
      feq (fconsR g (fconsR g' t)) (fconsR (g' ∘ g) t)
  | feq_idL {c1 : C} {d1 : D} {c2 d2} (t : FunHom c1 d1 c2 d2) :
      feq (fconsL id t) t
  | feq_idR {c1 : C} {d1 : D} {c2 d2} (t : FunHom c1 d1 c2 d2) :
      feq (fconsR id t) t.

#[export] Program Instance FunHom_Setoid {c1 d1 c2 d2} :
  Setoid (FunHom c1 d1 c2 d2) := {| equiv := @feq c1 d1 c2 d2 |}.
Next Obligation.
  constructor.
  - intro t. apply feq_refl.
  - intros t u. apply feq_sym.
  - intros t u v. apply feq_trans.
Qed.

Lemma fapp_feq_l {c1 d1 c2 d2} {t t' : FunHom c1 d1 c2 d2} (E : feq t t') :
  ∀ {c3 d3} (u : FunHom c2 d2 c3 d3), feq (fapp t u) (fapp t' u).
Proof.
  induction E; simpl; intros x y w.
  - apply feq_refl.
  - apply feq_sym, IHE.
  - eapply feq_trans; [ apply IHE1 | apply IHE2 ].
  - apply feq_consL; [ assumption | apply IHE ].
  - apply feq_consR; [ assumption | apply IHE ].
  - apply feq_fuseL.
  - apply feq_fuseR.
  - apply feq_idL.
  - apply feq_idR.
Qed.

Lemma fapp_feq_r {c1 d1 c2 d2 c3 d3} (t : FunHom c1 d1 c2 d2)
      {u u' : FunHom c2 d2 c3 d3} (E : feq u u') : feq (fapp t u) (fapp t u').
Proof.
  revert u u' E; induction t; simpl; intros u u' E.
  - exact E.
  - apply feq_consL; [ reflexivity | exact (IHt _ _ E) ].
  - apply feq_consR; [ reflexivity | exact (IHt _ _ E) ].
Qed.

(* Binary [Proper] phrasing of append-congruence.  A plain lemma, NOT a
   registered instance: because [fapp]'s implicit target indices {c3 d3}
   intervene between its two word arguments, the eta-expanded subject below
   is not a partial application of [@fapp], so setoid rewriting — which keys
   on the head constant of a literal application — could never select it.
   [fapp_respects_forall] below is the operative rewrite instance. *)
Lemma fapp_respects {c1 d1 c2 d2 c3 d3} :
  Proper (equiv ==> equiv ==> equiv)
    (fun (t : FunHom c1 d1 c2 d2) (u : FunHom c2 d2 c3 d3) => fapp t u).
Proof.
  intros t t' Et u u' Eu.
  exact (feq_trans _ _ _ (fapp_feq_l Et u) (fapp_feq_r t' Eu)).
Qed.

(* The same fact keyed on [fapp]'s actual argument structure (the target
   indices intervene between the two word arguments), so that setoid
   [rewrite] works under literal [fapp] applications. *)
#[export] Instance fapp_respects_forall {c1 d1 c2 d2} :
  Proper (equiv ==>
            forall_relation (fun c3 =>
              forall_relation (fun d3 => equiv ==> equiv)))
    (@fapp c1 d1 c2 d2).
Proof.
  intros t t' Et c3 d3 u u' Eu.
  exact (feq_trans _ _ _ (fapp_feq_l Et u) (fapp_feq_r t' Eu)).
Qed.

(* [fapp] flipped into composition order: this is [compose] of the category
   C □ D below.  A plain lemma, not an instance: keyed on a lambda it could
   never be selected by setoid rewriting (the same argument as
   [fapp_respects] above); its one consumer is the [compose_respects] field
   of [Funny]. *)
Lemma funny_compose_respects {c1 d1 c2 d2 c3 d3} :
  Proper (equiv ==> equiv ==> equiv)
    (fun (t : FunHom c2 d2 c3 d3) (u : FunHom c1 d1 c2 d2) => fapp u t).
Proof.
  intros t t' Et u u' Eu.
  exact (feq_trans _ _ _ (fapp_feq_r u Et) (fapp_feq_l Eu t')).
Qed.

Lemma feq_fapp_fnil {c1 d1 c2 d2} (t : FunHom c1 d1 c2 d2) :
  feq (fapp t fnil) t.
Proof. rewrite fapp_nil_r. apply feq_refl. Qed.

Lemma feq_fapp_assoc {c1 d1 c2 d2 c3 d3 c4 d4} (t : FunHom c1 d1 c2 d2)
      (u : FunHom c2 d2 c3 d3) (v : FunHom c3 d3 c4 d4) :
  feq (fapp (fapp t u) v) (fapp t (fapp u v)).
Proof. rewrite fapp_assoc. apply feq_refl. Qed.

End FunnyHom.

Arguments FunHom {C D} _ _ _ _.
Arguments fnil {C D c d}.
Arguments fconsL {C D c1 c2 d1} f {c3 d3} t.
Arguments fconsR {C D c1 d1 d2} g {c3 d3} t.
Arguments lstep {C D c1 c2 d} f.
Arguments rstep {C D c d1 d2} g.
Arguments fapp {C D c1 d1 c2 d2} t {c3 d3}.
Arguments feq {C D c1 d1 c2 d2} _ _.
Arguments feq_refl {C D c1 d1 c2 d2} t.
Arguments feq_sym {C D c1 d1 c2 d2} t u.
Arguments feq_trans {C D c1 d1 c2 d2} t u v.
Arguments feq_consL {C D c1 c2 d1} f f' {c3 d3} t u.
Arguments feq_consR {C D c1 d1 d2} g g' {c3 d3} t u.
Arguments feq_fuseL {C D c1 c2 c3 d1} f f' {c4 d4} t.
Arguments feq_fuseR {C D c1 d1 d2 d3} g g' {c4 d4} t.
Arguments feq_idL {C D c1 d1 c2 d2} t.
Arguments feq_idR {C D c1 d1 c2 d2} t.

(* The category.  Objects pair up ONLY here, accessed via fst/snd, never
   pattern matches (Construction/Product.v style).  Note the direction
   convention shared with Construction/Free.v: words read source-to-target,
   so [t ∘ u] is "u then t", i.e. [fapp u t]. *)
Definition Funny (C D : Category) : Category := {|
  obj     := C * D;
  hom     := fun x y => FunHom (fst x) (snd x) (fst y) (snd y);
  homset  := fun _ _ => FunHom_Setoid;
  id      := fun _ => fnil;
  compose := fun _ _ _ t u => fapp u t;
  compose_respects := fun _ _ _ => funny_compose_respects;
  id_left  := fun _ _ f => feq_fapp_fnil f;
  id_right := fun _ _ f => feq_refl f;   (* f ∘ id ≡ f definitionally *)
  comp_assoc := fun _ _ _ _ f g h => feq_fapp_assoc h g f;
  comp_assoc_sym := fun _ _ _ _ f g h => feq_sym _ _ (feq_fapp_assoc h g f)
|}.

Notation "C □ D" := (@Funny C D) (at level 90) : category_scope.

(* ---- singleton toolkit ---- *)

Lemma lstep_fuse {C D : Category} {c1 c2 c3 : C} {d : D}
  (f : c1 ~{C}~> c2) (f' : c2 ~{C}~> c3) :
  feq (fapp (lstep (d:=d) f) (lstep f')) (lstep (f' ∘ f)).
Proof. exact (feq_fuseL f f' fnil). Qed.

Lemma lstep_id {C D : Category} {c : C} {d : D} :
  feq (lstep (c1:=c) (d:=d) id) fnil.
Proof. exact (feq_idL fnil). Qed.

Lemma rstep_fuse {C D : Category} {c : C} {d1 d2 d3 : D}
  (g : d1 ~{D}~> d2) (g' : d2 ~{D}~> d3) :
  feq (fapp (rstep (c:=c) g) (rstep g')) (rstep (g' ∘ g)).
Proof. exact (feq_fuseR g g' fnil). Qed.

Lemma rstep_id {C D : Category} {c : C} {d : D} :
  feq (rstep (c:=c) (d1:=d) id) fnil.
Proof. exact (feq_idR fnil). Qed.

(* Every word decomposes at the head through a generating step; this equality
   is definitional (it is [t ∘[C □ D] lstep f] under the composition
   convention above), and is the joint-generation fact used by uniqueness
   arguments downstream. *)
Lemma fconsL_decomp {C D : Category} {c1 c2 : C} {d1 : D} {c3 : C} {d3 : D}
  (f : c1 ~{C}~> c2) (t : FunHom c2 d1 c3 d3) :
  fconsL f t = fapp (lstep f) t.
Proof. reflexivity. Qed.

Lemma fconsR_decomp {C D : Category} {c1 : C} {d1 d2 : D} {c3 : C} {d3 : D}
  (g : d1 ~{D}~> d2) (t : FunHom c1 d2 c3 d3) :
  fconsR g t = fapp (rstep g) t.
Proof. reflexivity. Qed.

(* ---- the separately-functorial eliminator (pushout universal property) ---- *)

Section FunnyUP.

Context {C : Category}.
Context {D : Category}.
Context {E : Category}.
Context {h : C → D → E}.

(* Separately functorial data: functorial in C at each d, functorial in D at
   each c, agreeing on objects via the SHARED object map h; NO mixed law and
   NO interchange condition relating the two actions (nLab: a functor out of
   C □ D is precisely a separately functorial assignment). *)
Record SepFunctorial : Type := {
  sf_lmap {c c' : C} (f : c ~{C}~> c') (d : D) : h c d ~{E}~> h c' d;
  sf_rmap (c : C) {d d' : D} (g : d ~{D}~> d') : h c d ~{E}~> h c d';
  sf_lmap_respects {c c' : C} {d : D} :
    Proper (equiv ==> equiv) (fun f : c ~{C}~> c' => sf_lmap f d);
  sf_rmap_respects {c : C} {d d' : D} :
    Proper (equiv ==> equiv) (fun g : d ~{D}~> d' => sf_rmap c g);
  sf_lmap_id {c : C} {d : D} : sf_lmap (@id C c) d ≈ id;
  sf_rmap_id {c : C} {d : D} : sf_rmap c (@id D d) ≈ id;
  sf_lmap_comp {c c' c'' : C} {d : D} (f' : c' ~{C}~> c'') (f : c ~{C}~> c') :
    sf_lmap (f' ∘ f) d ≈ sf_lmap f' d ∘ sf_lmap f d;
  sf_rmap_comp {c : C} {d d' d'' : D} (g' : d' ~{D}~> d'') (g : d ~{D}~> d') :
    sf_rmap c (g' ∘ g) ≈ sf_rmap c g' ∘ sf_rmap c g
}.

(* Fold a word through separately functorial data, one step at a time. *)
Fixpoint ffold (S : SepFunctorial) {c1 : C} {d1 : D} {c2 : C} {d2 : D}
    (t : FunHom c1 d1 c2 d2) : h c1 d1 ~{E}~> h c2 d2 :=
  match t in FunHom a b c d return h a b ~{E}~> h c d with
  | fnil        => id
  | fconsL f t' => ffold S t' ∘ sf_lmap S f _
  | fconsR g t' => ffold S t' ∘ sf_rmap S _ g
  end.

Lemma ffold_respects (S : SepFunctorial) {c1 : C} {d1 : D} {c2 : C} {d2 : D}
  {t u : FunHom c1 d1 c2 d2} (X : feq t u) : ffold S t ≈ ffold S u.
Proof.
  induction X; simpl.
  - reflexivity.
  - symmetry; exact IHX.
  - etransitivity; [ exact IHX1 | exact IHX2 ].
  - apply compose_respects; [ exact IHX | now apply (sf_lmap_respects S) ].
  - apply compose_respects; [ exact IHX | now apply (sf_rmap_respects S) ].
  - etransitivity;
      [ apply comp_assoc_sym
      | apply compose_respects;
          [ reflexivity | symmetry; apply (sf_lmap_comp S) ] ].
  - etransitivity;
      [ apply comp_assoc_sym
      | apply compose_respects;
          [ reflexivity | symmetry; apply (sf_rmap_comp S) ] ].
  - etransitivity;
      [ apply compose_respects; [ reflexivity | apply (sf_lmap_id S) ]
      | apply id_right ].
  - etransitivity;
      [ apply compose_respects; [ reflexivity | apply (sf_rmap_id S) ]
      | apply id_right ].
Qed.

Lemma ffold_app (S : SepFunctorial)
  {c1 : C} {d1 : D} {c2 : C} {d2 : D} {c3 : C} {d3 : D}
  (t : FunHom c1 d1 c2 d2) (u : FunHom c2 d2 c3 d3) :
  ffold S (fapp t u) ≈ ffold S u ∘ ffold S t.
Proof.
  revert u; induction t; simpl; intros u.
  - symmetry; apply id_right.
  - etransitivity;
      [ apply compose_respects; [ apply IHt | reflexivity ]
      | apply comp_assoc_sym ].
  - etransitivity;
      [ apply compose_respects; [ apply IHt | reflexivity ]
      | apply comp_assoc_sym ].
Qed.

Program Definition FunnyUP (S : SepFunctorial) : (C □ D) ⟶ E := {|
  fobj := fun x => h (fst x) (snd x);
  fmap := fun _ _ t => ffold S t
|}.
Next Obligation. proper. now apply ffold_respects. Qed.
Next Obligation. now apply ffold_app. Qed.

Lemma FunnyUP_lstep (S : SepFunctorial) {c c' : C} {d : D}
  (f : c ~{C}~> c') :
  @fmap (C □ D) E (FunnyUP S) (c, d) (c', d) (lstep f) ≈ sf_lmap S f d.
Proof. exact (id_left (sf_lmap S f d)). Qed.

Lemma FunnyUP_rstep (S : SepFunctorial) {c : C} {d d' : D}
  (g : d ~{D}~> d') :
  @fmap (C □ D) E (FunnyUP S) (c, d) (c, d') (rstep g) ≈ sf_rmap S c g.
Proof. exact (id_left (sf_rmap S c g)). Qed.

End FunnyUP.

Arguments SepFunctorial {C D E} h.

(* ---- transport-free uniqueness half of the universal property ---- *)

(* Every functor out of C □ D restricts to separately functorial data... *)
Program Definition toSep {C D E : Category} (H : (C □ D) ⟶ E) :
  SepFunctorial (fun c d => H (c, d)) := {|
  sf_lmap := fun c c' f d => @fmap (C □ D) E H (c, d) (c', d) (lstep f);
  sf_rmap := fun c d d' g => @fmap (C □ D) E H (c, d) (c, d') (rstep g)
|}.
Next Obligation.
  proper.
  apply fmap_respects.
  apply feq_consL; [ assumption | apply feq_refl ].
Qed.
Next Obligation.
  proper.
  apply fmap_respects.
  apply feq_consR; [ assumption | apply feq_refl ].
Qed.
Next Obligation.
  etransitivity.
  - apply fmap_respects. exact (feq_idL fnil).
  - exact (@fmap_id (C □ D) E H (c, d)).
Qed.
Next Obligation.
  etransitivity.
  - apply fmap_respects. exact (feq_idR fnil).
  - exact (@fmap_id (C □ D) E H (c, d)).
Qed.
Next Obligation.
  etransitivity.
  - apply fmap_respects. exact (feq_sym _ _ (feq_fuseL f f' fnil)).
  - exact (@fmap_comp (C □ D) E H (c, d) (c', d) (c'', d)
             (lstep f') (lstep f)).
Qed.
Next Obligation.
  etransitivity.
  - apply fmap_respects. exact (feq_sym _ _ (feq_fuseR g g' fnil)).
  - exact (@fmap_comp (C □ D) E H (c, d) (c, d') (c, d'')
             (rstep g') (rstep g)).
Qed.

(* ...and folding through that data recovers the functor: functors out of
   C □ D are determined by their action on the generating steps. *)
Lemma ffold_toSep {C D E : Category} (H : (C □ D) ⟶ E)
  {c1 : C} {d1 : D} {c2 : C} {d2 : D} (t : FunHom c1 d1 c2 d2) :
  ffold (toSep H) t ≈ @fmap (C □ D) E H (c1, d1) (c2, d2) t.
Proof.
  induction t as [ c d | ca cb da f cc dc t IHt | ca da db g cc dc t IHt ];
  simpl.
  - symmetry; exact (@fmap_id (C □ D) E H (c, d)).
  - etransitivity.
    + apply compose_respects; [ exact IHt | reflexivity ].
    + symmetry.
      exact (@fmap_comp (C □ D) E H (ca, da) (cb, da) (cc, dc) t (lstep f)).
  - etransitivity.
    + apply compose_respects; [ exact IHt | reflexivity ].
    + symmetry.
      exact (@fmap_comp (C □ D) E H (ca, da) (ca, db) (cc, dc) t (rstep g)).
Qed.

(* Two separately functorial data packages agreeing on the generating steps
   fold identically: uniqueness of the eliminator. *)
Lemma ffold_ext {C D E : Category} {h : C → D → E} (S S' : SepFunctorial h)
  (el : ∀ (c c' : C) (f : c ~{C}~> c') (d : D), sf_lmap S f d ≈ sf_lmap S' f d)
  (er : ∀ (c : C) (d d' : D) (g : d ~{D}~> d'), sf_rmap S c g ≈ sf_rmap S' c g)
  {c1 : C} {d1 : D} {c2 : C} {d2 : D} (t : FunHom c1 d1 c2 d2) :
  ffold S t ≈ ffold S' t.
Proof.
  induction t; simpl.
  - reflexivity.
  - apply compose_respects; [ exact IHt | apply el ].
  - apply compose_respects; [ exact IHt | apply er ].
Qed.

(* ---- injections ---- *)

(* NOTE: fmap[FunnyL d] f ≡ lstep f and fmap[FunnyR c] g ≡ rstep g
   DEFINITIONALLY — used by the nested associator/pentagon proofs. *)
Program Definition FunnyL {C D : Category} (d : D) : C ⟶ (C □ D) := {|
  fobj := fun c => (c, d);
  fmap := fun _ _ f => lstep f
|}.
Next Obligation.
  proper.
  apply feq_consL; [ assumption | apply feq_refl ].
Qed.
Next Obligation. exact (feq_idL fnil). Qed.
Next Obligation. exact (feq_sym _ _ (feq_fuseL g f fnil)). Qed.

Program Definition FunnyR {C D : Category} (c : C) : D ⟶ (C □ D) := {|
  fobj := fun d => (c, d);
  fmap := fun _ _ g => rstep g
|}.
Next Obligation.
  proper.
  apply feq_consR; [ assumption | apply feq_refl ].
Qed.
Next Obligation. exact (feq_idR fnil). Qed.
Next Obligation. exact (feq_sym _ _ (feq_fuseR g f fnil)). Qed.
