Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Construction.Product.

From Coq Require Import Eqdep_dec.

Generalizable All Variables.

(** * Quotient categories, and transport along object equalities

    nLab: https://ncatlab.org/nlab/show/quotient+category
    Wikipedia: https://en.wikipedia.org/wiki/Quotient_category

    This file is fully general — it never mentions any concrete category —
    and provides three kits, layered rather than independent, reusable by
    any construction that
    quotients a syntactic category or reasons about Leibniz-strict object
    equalities:

    (a) a transport kit for categories in which certain objects are related
        by Leibniz equality [=] (as happens in strict monoidal categories):
        the transported identities [id_cast]/[hom_cast] and their algebra,
        the [ObjDecEq] class giving axiom-free uniqueness of identity proofs
        on objects, and the [HomEqProp] class reflecting the hom-setoid
        equivalence into [Prop];

    (b) the quotient of an arbitrary category by a hom-congruence, whose
        relation family may be [Prop]-valued ([HomRel], as the syntactic
        layers use it) or [Type]-valued ([HomRelT], as a generated
        congruence must be): the quotient [Category] itself, the
        identity-on-objects projection functor, transfer of isomorphisms,
        the lifting universal property, and descent of bifunctors;

    (c) the least congruence generated by an arbitrary hom-relation,
        together with Mac Lane §II.8 Proposition 1 — the quotient by that
        closure, its projection, and the factorization of any functor
        merging the generating relation. *)

(** ** The [id_cast]/[hom_cast] transport kit

    [id_cast e] is the identity morphism transported along an object-level
    Leibniz equality [e : x = y].  It is deliberately spelled with the same
    [match e in _ = T return x ~> T with eq_refl => id end] shape as the
    [strict_*_to] fields of [Structure/Monoidal/Strict.v] and the
    [strict_pure_iso_id]/[strict_ap_iso_id] fields of
    [Functor/Structure/Monoidal/Strict.v], so those fields read as
    [to φ ≈ id_cast e] without any unfolding. *)

Section HomCast.

Context {C : Category}.

(** The identity morphism, transported along an object equality. *)
Definition id_cast {x y : C} (e : x = y) : x ~> y :=
  match e in _ = T return x ~> T with eq_refl => id end.

(** At [eq_refl], the cast is the literal identity. *)
Lemma id_cast_refl {x : C} : id_cast (@eq_refl _ x) = id.
Proof. reflexivity. Qed.

(** Composing two casts gives the cast along the composite equality. *)
Lemma id_cast_trans {x y z : C} (e1 : x = y) (e2 : y = z) :
  id_cast e2 ∘ id_cast e1 ≈ id_cast (eq_trans e1 e2).
Proof. destruct e2, e1; cat. Qed.

(** Casting along [e] and back along [eq_sym e] is the identity. *)
Lemma id_cast_inv_l {x y : C} (e : x = y) :
  id_cast (eq_sym e) ∘ id_cast e ≈ id.
Proof. destruct e; cat. Qed.

Lemma id_cast_inv_r {x y : C} (e : x = y) :
  id_cast e ∘ id_cast (eq_sym e) ≈ id.
Proof. destruct e; cat. Qed.

(** Solve [f ≈ g ∘ cast⁻¹] from [f ∘ cast ≈ g]. *)
Lemma comp_cast_shift {x y z : C} (e : x = y) (f : y ~> z) (g : x ~> z) :
  f ∘ id_cast e ≈ g → f ≈ g ∘ id_cast (eq_sym e).
Proof.
  intros Hf.
  rewrite <- Hf.
  rewrite <- comp_assoc.
  rewrite id_cast_inv_r.
  now rewrite id_right.
Qed.

(** Nested cast conjugations fuse along [eq_trans]. *)
Lemma id_cast_conj_fuse {x y x' y' x'' y'' : C}
  (e1 : x = x') (e2 : y = y') (d1 : x' = x'') (d2 : y' = y'')
  (f : x ~> y) :
  id_cast d2 ∘ (id_cast e2 ∘ f ∘ id_cast (eq_sym e1)) ∘ id_cast (eq_sym d1)
    ≈ id_cast (eq_trans e2 d2) ∘ f ∘ id_cast (eq_sym (eq_trans e1 d1)).
Proof. destruct e1, e2, d1, d2; cat. Qed.

(** Leibniz-equal objects are in particular isomorphic, via the casts. *)
Definition id_cast_iso {x y : C} (e : x = y) : x ≅ y := {|
  to := id_cast e;
  from := id_cast (eq_sym e);
  iso_to_from := id_cast_inv_r e;
  iso_from_to := id_cast_inv_l e
|}.

(** A whole morphism transported along equalities on both endpoints. *)
Definition hom_cast {x y x' y' : C} (ex : x = x') (ey : y = y')
  (f : x ~> y) : x' ~> y' :=
  match ey in _ = b return x' ~> b with eq_refl =>
    match ex in _ = a return a ~> y with eq_refl => f end end.

(** At [eq_refl] on both ends, the cast is the morphism itself. *)
Lemma hom_cast_refl {x y : C} (f : x ~> y) :
  hom_cast eq_refl eq_refl f = f.
Proof. reflexivity. Qed.

(** A [hom_cast] is conjugation by the endpoint [id_cast]s. *)
Lemma hom_cast_decompose {x y x' y' : C} (ex : x = x') (ey : y = y')
  (f : x ~> y) :
  hom_cast ex ey f ≈ id_cast ey ∘ f ∘ id_cast (eq_sym ex).
Proof. destruct ex, ey; cat. Qed.

(** Casting the identity along the same equality twice is the identity. *)
Lemma hom_cast_id {x x' : C} (e : x = x') : hom_cast e e id ≈ id.
Proof. destruct e; cat. Qed.

(** Casts fuse across composition when the middle equalities agree. *)
Lemma hom_cast_comp {x y z x' y' z' : C}
  (ex : x = x') (ey : y = y') (ez : z = z')
  (g : y ~> z) (f : x ~> y) :
  hom_cast ey ez g ∘ hom_cast ex ey f ≈ hom_cast ex ez (g ∘ f).
Proof. destruct ex, ey, ez; cat. Qed.

(** Casting there and back is the identity operation. *)
Lemma hom_cast_roundtrip {x y x' y' : C} (ex : x = x') (ey : y = y')
  (f : x' ~> y') :
  hom_cast ex ey (hom_cast (eq_sym ex) (eq_sym ey) f) = f.
Proof. destruct ex, ey; reflexivity. Qed.

(** [hom_cast] respects the hom-setoid equivalence. *)
#[export] Instance hom_cast_respects {x y x' y' : C}
  (ex : x = x') (ey : y = y') :
  Proper (equiv ==> equiv) (@hom_cast x y x' y' ex ey).
Proof. destruct ex, ey; repeat intro; assumption. Qed.

End HomCast.

(** Functors take [id_cast e] to [id_cast (f_equal F e)].  This is the
    [id_cast]-phrased sibling of [fmap_match_id] from
    [Functor/Structure/Monoidal/Strict.v]; it is reproved here (one line)
    to keep this root file independent of the monoidal-functor stack. *)
Lemma fmap_id_cast {C D : Category} (F : C ⟶ D) {x y : C} (e : x = y) :
  fmap[F] (id_cast e) ≈ id_cast (f_equal F e).
Proof. destruct e; apply fmap_id. Qed.

(** ** Decidable object equality gives axiom-free UIP

    When the objects of [C] have decidable Leibniz equality, uniqueness of
    identity proofs holds for them without any axiom, by
    [Eqdep_dec.UIP_dec].  This is the target-side mirror of the
    proof-irrelevance results available on syntactic categories with [nat]
    objects, and it makes every [id_cast]/[hom_cast] independent of the
    particular equality proof used. *)

Class ObjDecEq (C : Category) : Type :=
  obj_eq_dec : ∀ x y : obj[C], {x = y} + {x ≠ y}.

(** Uniqueness of identity proofs on objects, with no axioms. *)
Lemma obj_uip {C : Category} `{@ObjDecEq C} {x y : C} (e1 e2 : x = y) :
  e1 = e2.
Proof. exact (UIP_dec obj_eq_dec e1 e2). Qed.

(** [id_cast] does not depend on the choice of equality proof. *)
Lemma id_cast_irr {C : Category} `{@ObjDecEq C} {x y : C} (e1 e2 : x = y) :
  id_cast e1 = id_cast e2.
Proof. rewrite (obj_uip e1 e2); reflexivity. Qed.

(** Any cast along a loop equality [e : x = x] is the identity. *)
Lemma id_cast_loop {C : Category} `{@ObjDecEq C} {x : C} (e : x = x) :
  id_cast e = id.
Proof. rewrite (obj_uip e eq_refl); reflexivity. Qed.

(** Conjugation along different proofs of the same equalities agrees. *)
Lemma id_cast_conj_irr {C : Category} `{@ObjDecEq C} {x y x' y' : C}
  (p1 q1 : x = x') (p2 q2 : y = y') (f : x ~> y) :
  id_cast p2 ∘ f ∘ id_cast (eq_sym p1)
    ≈ id_cast q2 ∘ f ∘ id_cast (eq_sym q1).
Proof. rewrite (obj_uip p1 q1), (obj_uip p2 q2); reflexivity. Qed.

(** [hom_cast] does not depend on the choice of equality proofs. *)
Lemma hom_cast_irr {C : Category} `{@ObjDecEq C} {x y x' y' : C}
  (e1 e1' : x = x') (e2 e2' : y = y') (f : x ~> y) :
  hom_cast e1 e2 f = hom_cast e1' e2' f.
Proof. rewrite (obj_uip e1 e1'), (obj_uip e2 e2'); reflexivity. Qed.

(** Casting a morphism along loop equalities is the morphism itself. *)
Lemma hom_cast_loop {C : Category} `{@ObjDecEq C} {x y : C}
  (e1 : x = x) (e2 : y = y) (f : x ~> y) :
  hom_cast e1 e2 f = f.
Proof. rewrite (obj_uip e1 eq_refl), (obj_uip e2 eq_refl); reflexivity. Qed.

(** *** The strict functor-equality reading of a [hom_cast] conjugation

    Conjugating by [hom_cast] along Leibniz object equalities is exactly the
    data of [Functor_StrictEq_Setoid] ([Theory/Functor.v]), the hom-setoid
    of [StrictCat], modulo the [hom_cast] ↔ [transport]/[transport_r]
    reshuffle.  The three lemmas below make that reading available in both
    directions, so a uniqueness statement phrased with [hom_cast] — such as
    [QuotientLift_unique] below — is legible as an equality of functors in
    [StrictCat] with nothing further to prove. *)

(** The reshuffle itself, both directions, by [destruct] on the endpoint
    equalities. *)
Lemma hom_cast_transport_iff {D : Category} {a b a' b' : D}
  (ex : a = a') (ey : b = b') (f : a ~> b) (g : a' ~> b') :
  ((hom_cast ex ey f ≈ g) →
     (Logic.transport (fun z => hom a z) ey f
        ≈ Logic.transport_r (fun z => hom z b') ex g)) *
  ((Logic.transport (fun z => hom a z) ey f
      ≈ Logic.transport_r (fun z => hom z b') ex g) →
     (hom_cast ex ey f ≈ g)).
Proof. destruct ex, ey; split; intro; assumption. Qed.

(** A [hom_cast]-conjugated agreement of two functors IS their equality in
    [StrictCat]. *)
Lemma strict_of_hom_cast {C D : Category} (F G : C ⟶ D)
  (Hobj : ∀ x, fobj[F] x = fobj[G] x)
  (H : ∀ x y (f : x ~> y),
      hom_cast (Hobj x) (Hobj y) (fmap[F] f) ≈ fmap[G] f) :
  @equiv _ (@Functor_StrictEq_Setoid C D) F G.
Proof.
  exists Hobj. intros x y f.
  exact (fst (hom_cast_transport_iff (Hobj x) (Hobj y)
                (fmap[F] f) (fmap[G] f)) (H x y f)).
Qed.

(** ...and conversely, an equality of functors in [StrictCat] yields the
    object equalities together with the [hom_cast]-conjugated agreement. *)
Lemma hom_cast_of_strict {C D : Category} (F G : C ⟶ D)
  (E : @equiv _ (@Functor_StrictEq_Setoid C D) F G) :
  { Hobj : ∀ x, fobj[F] x = fobj[G] x &
      ∀ x y (f : x ~> y),
        hom_cast (Hobj x) (Hobj y) (fmap[F] f) ≈ fmap[G] f }.
Proof.
  destruct E as [Hobj Hmor].
  exists Hobj. intros x y f.
  exact (snd (hom_cast_transport_iff (Hobj x) (Hobj y)
                (fmap[F] f) (fmap[G] f)) (Hmor x y f)).
Qed.

(** ** [Prop]-reflected hom equivalence

    The hom-setoid equivalence [≈] of this library is [Type]-valued (it is
    a [crelation]; see [Lib/Setoid.v]).  A [Prop]-valued inductive with two
    or more constructors — such as the term congruence of a syntactic
    category — cannot be eliminated into that [Type]-valued [≈] of an
    abstract target category: the elimination restriction on [Prop] blocks
    the induction.  Soundness inductions therefore land in a [Prop]-valued
    reflection [heq] of the hom equivalence and round-trip through
    [heq_intro]/[heq_elim].

    No [Equivalence] field is required: reflexivity, symmetry and
    transitivity of [heq] all follow by round-tripping through [≈]. *)

Class HomEqProp (C : Category) : Type := {
  heq : ∀ {x y : C}, (x ~> y) → (x ~> y) → Prop;
  heq_intro : ∀ {x y : C} {f g : x ~> y}, f ≈ g → heq f g;
  heq_elim : ∀ {x y : C} {f g : x ~> y}, heq f g → f ≈ g
}.

(** ** Quotient by a hom-congruence

    [HomRel] is the [Prop]-valued relation family, and it remains the shape
    the syntactic term congruences of [Construction/PROP/Presentation.v]
    and [Construction/ColouredPROP/Presentation.v] use.

    [HomRelT] is the general [Type]-valued family, and [HomRel] embeds into
    it by [Prop ⊆ Type] cumulativity, so the congruence class and the
    quotient below are stated over [HomRelT] and every [Prop]-valued client
    is accepted unchanged.

    A [Type]-valued family can serve directly as the quotient's hom-setoid
    equivalence, since [Setoid]'s [equiv] is itself a [crelation].

    [Quotient_HomEqProp] below stays pinned to a [Prop]-valued [R], because
    its [heq] field must land in [Prop].  That is why the [Prop] family
    keeps a name of its own, and why a quotient by a generated congruence
    (the last subsection of this file) carries no [HomEqProp] instance. *)

Definition HomRel (C : Category) : Type :=
  ∀ x y : C, (x ~> y) → (x ~> y) → Prop.

Definition HomRelT (C : Category) : Type :=
  ∀ x y : C, (x ~> y) → (x ~> y) → Type.

(** A congruence: an equivalence on each hom containing [≈] (whence
    reflexivity) and compatible with composition. *)
Class HomCongruence {C : Category} (R : HomRelT C) : Type := {
  cong_incl {x y : C} {f g : x ~> y} : f ≈ g → R x y f g;
  cong_sym {x y : C} {f g : x ~> y} : R x y f g → R x y g f;
  cong_trans {x y : C} {f g h : x ~> y} :
    R x y f g → R x y g h → R x y f h;
  cong_comp {x y z : C} {f f' : y ~> z} {g g' : x ~> y} :
    R y z f f' → R x y g g' → R x z (f ∘ g) (f' ∘ g')
}.

(** Reflexivity of a congruence, from inclusion of [≈]. *)
Lemma cong_refl {C : Category} {R : HomRelT C} `{@HomCongruence C R}
  {x y : C} (f : x ~> y) : R x y f f.
Proof. apply cong_incl; reflexivity. Qed.

(** Each hom-relation of a congruence is an equivalence. *)
Lemma Quotient_equivalence {C : Category} {R : HomRelT C}
  `{@HomCongruence C R} (x y : C) : Equivalence (R x y).
Proof.
  constructor.
  - intros f. exact (cong_refl f).
  - intros f g Hfg. exact (cong_sym Hfg).
  - intros f g k Hfg Hgk. exact (cong_trans Hfg Hgk).
Qed.

(** The quotient category [C/R]: same objects and morphisms as [C], with
    the hom-setoid equivalence coarsened from [≈] to [R].  The category
    laws hold because [R] contains [≈] (via [cong_incl]) and [C] already
    satisfies them up to [≈]. *)
Definition Quotient (C : Category) (R : HomRelT C)
  `{@HomCongruence C R} : Category := {|
  obj := @obj C;
  hom := @hom C;
  homset := fun x y =>
    {| equiv := R x y; setoid_equiv := Quotient_equivalence x y |};
  id := @id C;
  compose := @compose C;
  compose_respects := fun x y z f f' Hf g g' Hg => cong_comp Hf Hg;
  id_left := fun x y f => cong_incl (id_left f);
  id_right := fun x y f => cong_incl (id_right f);
  comp_assoc := fun x y z w f g h => cong_incl (comp_assoc f g h);
  comp_assoc_sym := fun x y z w f g h => cong_incl (comp_assoc_sym f g h)
|}.

(** The quotient's [≈] IS [R x y] after reduction, so both directions of
    the [Prop] reflection are the identity. *)
#[export] Instance Quotient_HomEqProp (C : Category) (R : HomRel C)
  `{@HomCongruence C R} : HomEqProp (Quotient C R) :=
  Build_HomEqProp (Quotient C R)
    (fun x y f g => R x y f g)
    (fun x y f g Hfg => Hfg)
    (fun x y f g Hfg => Hfg).

(** The quotient has the same objects as [C], so decidability of object
    equality is inherited on the nose. *)
#[export] Instance Quotient_ObjDecEq (C : Category) (R : HomRel C)
  `{@HomCongruence C R} `{OD : @ObjDecEq C} : ObjDecEq (Quotient C R) := OD.

(** *** The universal property of the quotient *)

Section QuotientUMP.

Context {C : Category} {R : HomRelT C} `{@HomCongruence C R}.

(** The projection functor: identity on objects and on morphisms; only the
    equivalence coarsens.  (Here and below the record is built with an
    explicit [Build_Functor] so that the codomain category is pinned to the
    quotient; a bare record literal would infer it from the field values,
    which live in [C].) *)
Definition QuotientProj : C ⟶ Quotient C R :=
  Build_Functor C (Quotient C R)
    (fun x => x)
    (fun x y f => f)
    (fun x y f g Hfg => cong_incl Hfg)
    (fun x => cong_refl (@id C x))
    (fun x y z f g => cong_refl (f ∘ g)).

(** Isomorphisms in [C] descend to isomorphisms in the quotient. *)
Definition Quotient_iso {x y : C} (i : x ≅[C] y) : x ≅[Quotient C R] y :=
  @Build_Isomorphism (Quotient C R) x y (to i) (from i)
    (cong_incl (iso_to_from i))
    (cong_incl (iso_from_to i)).

Context {D : Category} (F : C ⟶ D)
  (HF : ∀ x y (f g : x ~> y), R x y f g → fmap[F] f ≈ fmap[F] g).

(** A functor identifying [R]-related morphisms lifts through the
    quotient. *)
Definition QuotientLift : Quotient C R ⟶ D :=
  Build_Functor (Quotient C R) D
    (fun x => F x)
    (fun x y f => fmap[F] f)
    HF
    (fun x => @fmap_id C D F x)
    (fun x y z f g => @fmap_comp C D F x y z f g).

(** The lift factors [F] through the projection — definitionally. *)
Lemma QuotientLift_proj {x y : C} (f : x ~> y) :
  fmap[QuotientLift] (fmap[QuotientProj] f) = fmap[F] f.
Proof. reflexivity. Qed.

(** The factorization, packaged as a single equality of functors in
    [StrictCat] — the same strength as [QuotientLift_unique] below. *)
Lemma QuotientLift_factors_strict :
  @equiv _ (@Functor_StrictEq_Setoid C D) (QuotientLift ◯ QuotientProj) F.
Proof. exists (fun _ => eq_refl). intros x y f. simpl. reflexivity. Qed.

(** Uniqueness: [QuotientProj] is the identity on objects and on
    morphisms, so any competitor agreeing with [F] after precomposition
    with the projection is pinned pointwise on every hom.  The competitor's
    object action agrees with [F]'s up to the Leibniz equalities [Hobj],
    and the morphism-level agreement is phrased by conjugating with
    [hom_cast] along them (see the transport kit above); when the object
    agreement is definitional, instantiating [Hobj] with [eq_refl] makes
    both [hom_cast]s disappear definitionally.

    That [hom_cast] conjugation along Leibniz object equalities IS
    [StrictCat]'s functor equality ([Functor_StrictEq_Setoid],
    [Theory/Functor.v]); [strict_of_hom_cast] and [hom_cast_of_strict]
    above convert between the two phrasings in both directions.  The
    factorization half at that same strength is
    [QuotientLift_factors_strict] just above, the pointwise Leibniz
    [QuotientLift_proj] being the sharper but weaker-typed statement. *)
Lemma QuotientLift_unique (G : Quotient C R ⟶ D)
  (Hobj : ∀ x : C, fobj[G] x = fobj[F] x)
  (HG : ∀ x y (f : x ~{C}~> y),
      hom_cast (Hobj x) (Hobj y) (fmap[G] (fmap[QuotientProj] f))
        ≈ fmap[F] f) :
  ∀ x y (f : x ~{Quotient C R}~> y),
    hom_cast (Hobj x) (Hobj y) (fmap[G] f) ≈ fmap[QuotientLift] f.
Proof. exact HG. Qed.

End QuotientUMP.

(** ** The projection identifies, and never separates

    Imposing equations can only merge morphisms; it never adds any.  The
    projection is the identity on objects and the identity on morphisms,
    and only the hom-setoid equivalence coarsens, so both halves of that
    reading are definitional here.  The projection is deliberately not
    [Faithful]: that non-instance is the whole content of Fong and
    Spivak's remark that imposing equations can merge morphisms but never
    add any (see [Construction/Free/Quiver/Presented.v]). *)

(** The projection is the identity on objects, on the nose — the honest
    reading of "bijective on objects". *)
Lemma QuotientProj_obj {C : Category} (R : HomRelT C)
  `{HR : @HomCongruence C R} (x : C) : fobj[@QuotientProj C R HR] x = x.
Proof. reflexivity. Qed.

(** The sharpest form of "equations merge and never add": the hom TYPE is
    unchanged by the quotient. *)
Lemma Quotient_hom_type {C : Category} (R : HomRelT C)
  `{HR : @HomCongruence C R} (x y : C) :
  (x ~{Quotient C R}~> y) = (x ~{C}~> y).
Proof. reflexivity. Qed.

(** Surjectivity on each hom-set, as a CHOSEN section, so no choice
    principle is used.  (The record is built with the fully applied
    [@Build_Full]: a bare record literal does not infer the functor.) *)
Definition QuotientProj_Full {C : Category} (R : HomRelT C)
  `{HR : @HomCongruence C R} : Full (@QuotientProj C R HR) :=
  @Build_Full C (Quotient C R) (@QuotientProj C R HR)
    (fun x y g => g) (fun x y g => @cong_refl C R HR x y g).

(** ** Bifunctor descent

    A bifunctor on [C] whose morphism action preserves [R] componentwise
    descends to a bifunctor on the quotient.  The object and morphism
    actions are unchanged; only the respectfulness proof is new (note that
    the product category's hom equivalence is a pair). *)
Definition Quotient_bifunctor {C : Category} {R : HomRelT C}
  `{@HomCongruence C R} (F : C ∏ C ⟶ C)
  (HF2 : ∀ (x y : C ∏ C) (f g : x ~{C ∏ C}~> y),
      R (fst x) (fst y) (fst f) (fst g) →
      R (snd x) (snd y) (snd f) (snd g) →
      R (F x) (F y) (fmap[F] f) (fmap[F] g)) :
  Quotient C R ∏ Quotient C R ⟶ Quotient C R :=
  Build_Functor (Quotient C R ∏ Quotient C R) (Quotient C R)
    (fun x => F x)
    (fun x y f => fmap[F] f)
    (fun x y f g Hfg => HF2 x y f g (fst Hfg) (snd Hfg))
    (fun x => cong_incl (@fmap_id _ _ F x))
    (fun x y z f g => cong_incl (@fmap_comp _ _ F x y z f g)).

(** ** The congruence generated by a hom-relation

    Book: Mac Lane, Categories for the Working Mathematician, 2nd ed.,
          §II.8, printed pp. 51-52 — Proposition 1 (the quotient by an
          arbitrary family of relations and its universal property), the
          definition of a congruence and of the least congruence containing
          a family, and the definition of a category presented by
          generators and relations
    nLab: https://ncatlab.org/nlab/show/quotient+category
    nLab: https://ncatlab.org/nlab/show/congruence

    WHY THE CLOSURE IS [Type]-VALUED.  The hom-setoid equivalence [≈] of
    this library is [Type]-valued (it is a [crelation]; see
    [Lib/Setoid.v]).  A [Prop]-valued inductive with two or more
    constructors cannot be eliminated into that [Type]-valued [≈] of an
    abstract target category, because the elimination restriction on [Prop]
    blocks the induction — the same obstruction the [HomEqProp] subsection
    above records.  The sharp form of it here is that the kernel congruence
    of a functor, [FunctorKernel] below, is [Type]-valued precisely because
    [≈] is, so it is not even expressible as a [HomRel]: Mac Lane's own
    proof of Proposition 1 cannot be transcribed in the [Prop] family.

    SCOPE, universes.  The composition constructor [cc_comp] binds an
    intermediate object, so the closure's sort absorbs the OBJECT universe,
    and the resulting quotient carries the constraint that the object
    universe is at most the proof universe.  This is harmless for
    quiver-presented categories, the intended application
    ([Construction/Free/Quiver/Presented.v]), but it would bite an attempt
    to present a category whose objects live strictly above its homs.

    SCOPE, reflection.  A quotient by a generated congruence has no
    [HomEqProp] instance, since [Quotient_HomEqProp] requires a
    [Prop]-valued relation; the consumers that require one —
    [Construction/PROP/Interp.v], [Construction/PROP/Algebra.v],
    [Construction/PROP/Universal.v], [Construction/ColouredPROP/Interp.v],
    [Construction/ColouredPROP/Algebra.v],
    [Construction/ColouredPROP/Universal.v], [Theory/Lawvere/PROP.v] — do
    not apply to it.  It has no need of one: the lift below no longer routes
    through [heq].

    RELATION TO THE SYNTACTIC CLOSURES.  [TermEqW]
    ([Construction/PROP/Presentation.v]) and [CTermEqW]
    ([Construction/ColouredPROP/Presentation.v]) are this closure shape run
    over term syntax: their [TEW_termeq], [TEW_ax], [TEW_sym], [TEW_trans]
    and [TEW_comp] are one for one [cc_equiv], [cc_gen], [cc_sym],
    [cc_trans] and [cc_comp], with [TermEq] playing the role the ambient
    hom-setoid [≈] plays here, whence reflexivity is derived on both sides
    ([TermEqW_refl] there, [cc_refl] here) rather than assumed.  They carry
    one constructor more, [TEW_tens] and [CTEW_tens], and it is NOT part of
    the least congruence in the categorical sense: it is exactly the
    hypothesis [Quotient_bifunctor] consumes, i.e. what makes those
    quotients monoidal rather than merely categories.  Formally [cc_least]
    yields the containment [CongClosure (smt_eqs E) ⊆ TermEqW E]; the
    converse is not available: nothing in the generic closure pushes a
    relation through a tensor context, and no in-tree countermodel is
    exhibited.  That containment is stated here in prose rather than as
    code because this file cannot depend on the PROP layer.  The phrase
    "smallest congruence" in both of those files reads in the TERM-ALGEBRA
    sense — least among relations closed under [T_comp] AND [T_tens] — and
    [cc_least] does not establish it: [cc_least] supplies only the
    containment above, the direction that leaves [TermEqW] the larger
    relation.  What [cc_least] does supply is the categorical half of the
    vocabulary those headers borrow: a formal least hom-congruence.

    Finally, [TermEqW] must STAY [Prop]-valued: that is what lets
    [Quotient_HomEqProp] supply the reflection its soundness inductions
    round-trip through, at the price that Proposition 1's arbitrary-target
    factorization is not available there — exactly the trade the
    [Type]-valued closure reverses. *)

(** Mac Lane's kernel congruence of a functor: the morphisms it merges.
    It is [Type]-valued because [≈] is. *)
Definition FunctorKernel {C D : Category} (F : C ⟶ D) : HomRelT C :=
  fun x y f g => fmap[F] f ≈ fmap[F] g.

(** The kernel of a functor is a congruence.  Kept a plain [Definition] and
    [Defined] rather than an [Instance], so that nothing new enters
    typeclass search and the congruence witness stays transparent where
    [cc_kernel] elaborates its type. *)
Definition FunctorKernel_Congruence {C D : Category} (F : C ⟶ D) :
  @HomCongruence C (FunctorKernel F).
Proof.
  unshelve econstructor; unfold FunctorKernel.
  - intros x y f g Hfg. now rewrite Hfg.
  - intros x y f g Hc. now symmetry.
  - intros x y f g h H1 H2. now transitivity (fmap[F] g).
  - intros x y z f f' g g' H1 H2. rewrite !fmap_comp. now rewrite H1, H2.
Defined.

Section CongruenceClosure.

Context {C : Category}.
Variable R : HomRelT C.

(** The congruence generated by [R]: five constructors — embed [R], embed
    the ambient [≈], symmetry, transitivity, and closure under composition
    on both flanks simultaneously (the shape that matches the [cong_comp]
    field verbatim).  There is deliberately no reflexivity constructor: it
    is derived below as [cc_refl], mirroring [TermEqW_refl] in the PROP
    presentation layer. *)
Inductive CongClosure : ∀ x y : C, (x ~> y) → (x ~> y) → Type :=
  | cc_gen {x y : C} {f g : x ~> y} : R x y f g → CongClosure x y f g
  | cc_equiv {x y : C} {f g : x ~> y} : f ≈ g → CongClosure x y f g
  | cc_sym {x y : C} {f g : x ~> y} :
      CongClosure x y f g → CongClosure x y g f
  | cc_trans {x y : C} {f g h : x ~> y} :
      CongClosure x y f g → CongClosure x y g h → CongClosure x y f h
  | cc_comp {x y z : C} {f f' : y ~> z} {g g' : x ~> y} :
      CongClosure y z f f' → CongClosure x y g g' →
      CongClosure x z (f ∘ g) (f' ∘ g').

(** The closure is a congruence, by a pure term: four of the five
    constructors map onto the four fields, with [cc_equiv] supplying
    [cong_incl]; [cc_gen] is what makes the closure contain [R] and plays
    no part here. *)
Definition CongClosure_Congruence : @HomCongruence C CongClosure :=
  @Build_HomCongruence C CongClosure
    (fun x y f g H => cc_equiv H)
    (fun x y f g H => cc_sym H)
    (fun x y f g h H1 H2 => cc_trans H1 H2)
    (fun x y z f f' g g' H1 H2 => cc_comp H1 H2).

(** Reflexivity, derived rather than assumed. *)
Definition cc_refl {x y : C} (f : x ~> y) : CongClosure x y f f :=
  cc_equiv (reflexivity f).

(** Leastness: the closure is contained in every congruence containing
    [R].  Because [HomCongruence] is stated over [HomRelT], a [Prop]-valued
    target congruence is covered by the same statement, through
    [Prop ⊆ Type] cumulativity. *)
Lemma cc_least (S : HomRelT C) `{@HomCongruence C S}
  (HRS : ∀ x y (f g : x ~> y), R x y f g → S x y f g)
  {x y : C} {f g : x ~> y} : CongClosure x y f g → S x y f g.
Proof.
  intro Hc; induction Hc.
  - now apply HRS.
  - now apply cong_incl.
  - now apply cong_sym.
  - now apply (cong_trans IHHc1 IHHc2).
  - now apply cong_comp.
Qed.

(** Mac Lane §II.8 Proposition 1's kernel lemma: a functor merging [R]
    merges the whole generated congruence.  It is a one-line corollary of
    leastness applied at the kernel congruence, not a second induction, and
    its type is exactly the hypothesis [QuotientLift] consumes. *)
Definition cc_kernel {D : Category} (F : C ⟶ D)
  (HF : ∀ x y (f g : x ~> y), R x y f g → fmap[F] f ≈ fmap[F] g)
  {x y : C} {f g : x ~> y} :
  CongClosure x y f g → fmap[F] f ≈ fmap[F] g :=
  @cc_least (FunctorKernel F) (FunctorKernel_Congruence F) HF x y f g.

End CongruenceClosure.

Arguments CongClosure {C} R x y f g.
Arguments cc_gen {C R x y f g} _.
Arguments cc_equiv {C R x y f g} _.
Arguments cc_sym {C R x y f g} _.
Arguments cc_trans {C R x y f g h} _ _.
Arguments cc_comp {C R x y z f f' g g'} _ _.
Arguments cc_refl {C} R {x y} f.
Arguments CongClosure_Congruence {C} R.

(** The quotient by the congruence GENERATED by an arbitrary relation
    family — Mac Lane §II.8 Proposition 1's category. *)
Definition QuotientCong (C : Category) (R : HomRelT C) : Category :=
  @Quotient C (CongClosure R) (CongClosure_Congruence R).

(** Its projection. *)
Definition QuotientCongProj {C : Category} (R : HomRelT C) :
  C ⟶ QuotientCong C R :=
  @QuotientProj C (CongClosure R) (CongClosure_Congruence R).

(** Proposition 1, clause (i): related arrows are identified by the
    projection. *)
Lemma cong_identifies {C : Category} (R : HomRelT C) {x y : C}
  {f g : x ~> y} (Hr : R x y f g) :
  fmap[QuotientCongProj R] f ≈ fmap[QuotientCongProj R] g.
Proof. exact (cc_gen Hr). Qed.

(** Proposition 1, clause (ii): any functor merging [R] factors through the
    projection, with no side condition on the target [D]. *)
Definition QuotientCongLift {C D : Category} (R : HomRelT C) (F : C ⟶ D)
  (HF : ∀ x y (f g : x ~> y), R x y f g → fmap[F] f ≈ fmap[F] g) :
  QuotientCong C R ⟶ D :=
  @QuotientLift C (CongClosure R) (CongClosure_Congruence R) D F
    (fun x y f g Hc => @cc_kernel C R D F HF x y f g Hc).
