(** * CRing is reflective in Ring: the commutator-ideal quotient

    Riehl, "Category Theory in Context", §4.6, Example 4.6.13 (ii),
    printed p. 170 (PDF p. 190), read from the page image, catalog item
    riehl:4.6:example13, the second half of the clause: after the
    abelianization of groups, "A similar construction defines a left
    adjoint to the inclusion CRing ↪ Ring of commutative rings into the
    category of all rings."  The box this file answers asks for "The
    reflector Ring ⟶ CRing, quotienting by the commutator ideal -- the
    two-sided ideal generated by xy − yx -- with the quotient map as
    unit, exhibiting CRing as a full reflective subcategory of Ring."
    Mac Lane, "Categories for the Working Mathematician", 2nd ed.,
    §IV.3, printed p. 92 (PDF p. 101), read from the page image, gives
    the group case this imitates: "Ab is reflective in Grp.  For, if
    G/[G, G] is the usual factor-commutator group of a group G, then
    hom(G/[G, G], A) ≅ hom(G, A) for A abelian, and Ab is full in Grp."
    nLab: https://ncatlab.org/nlab/show/reflective+subcategory

    BACKGROUND.  Riehl states the ring case in one sentence, as the
    analogue of abelianization, and neither Riehl nor Mac Lane spells
    out the construction.  The quotient is by the smallest two-sided
    ideal containing every commutator xy − yx: any ring map into a
    commutative ring sends each commutator to zero, hence kills that
    ideal, hence factors through the quotient, and the quotient is
    commutative because the class of xy − yx is zero.  That is the whole
    argument, and it is the one formalized below; the group case is
    Instance/Grp/Abelianize/Reflective.v.

    THE ROUTE.  Nothing about quotients is rebuilt.  #314's
    Instance/Rng/Quotient.v supplies two-sided ideals ([Ideal]), the
    quotient ring ([QuotientRing]), its projection ([rquot_proj]) and
    its universal property ([rquot_med], fed a map together with a
    proof that it kills the ideal).  #257's Instance/Rng.v supplies the
    full subcategory [CRng_Sub] of commutative rings and its fullness
    [CRng_Full], used unchanged.  NEW here:
      - [rcomm R x y], the commutator xy − yx through Instance/Ab/
        Subtract.v's [ab_sub];
      - [InCommIdeal], the ideal GENERATED by the commutators, as an
        ≈-saturated inductive generation (generators, zero, sums, both
        absorptions), and [CommIdeal : Ideal R], whose six fields ARE
        its constructors;
      - [Commutativize R := QuotientRing (CommIdeal R)], commutative by
        [Commutativize_comm];
      - [comm_kills]: a map into a commutative ring kills the ideal, by
        induction on the generation;
      - [crng_universal], its packaging [crng_universal_arrow], and
        through Theory/Universal/Arrow.v [CRng_reflector], [CRng_adj]
        and [CRng_Reflective_in_Rng : Reflective CRng_Sub];
      - [crng_reflect_iso], R/[R, R] ≅ R at a commutative R, as
        [reflective_counit_iso] instantiated.
    Membership in the ideal is [Type]-valued, as every membership
    predicate of the algebraic layer is since the "algebraic carriers
    are sets" regime; the quotient's equality is Quotient.v's
    [rquot_rel], the propositional truncation of membership of the
    difference.  So [comm_kills] eliminates the generation into the
    [Type]-valued equality of the target directly, and
    [Commutativize_comm] introduces the truncation with [constructor].

    STRENGTHS, measured strict first.  Four [Example]s hold at
    [eq_refl]: the membership predicate of [CRng_Sub] IS [IsCommutative]
    ([IsCommutative_is_CRng_sobj]); the reflection of R is
    [QuotientRing (CommIdeal R)] ([crng_reflector_obj]); the universal
    arrow IS [rquot_proj (CommIdeal R)] ([crng_arrow_is_proj]); and the
    unit applied to an element IS the projection applied to it
    ([crng_unit_pointwise]).  Falling back: the unit as a morphism is
    only [≈] the projection ([crng_unit_is_proj]).  Pinned in
    Test/ProbeReflective370.v, whose import list carries this file's,
    it is [fmap[Incl] id ∘ rquot_proj (CommIdeal R)] on the nose
    (accepted at [eq_refl]), while against [rquot_proj (CommIdeal R)]
    both its setoid-morphism component and the whole record are refused
    at [eq_refl] with "cannot unify".

    NON-VACUITY lives in the satellite Instance/Rng/Commutativize/UT2.v,
    at the non-commutative ring of upper-triangular integer matrices.
    It is a satellite for dependency weight: by a transitive closure over
    [coqdep -R . Category] of the [_CoqProject] files, excluding the
    file itself, this file depends on 71 modules and the satellite on
    80, the nine more being Instance/Rng/Algebras/Associative.v, where
    [UT2] lives, and what it brings (Instance/Mod.v,
    Structure/Additive.v and their kin), plus this file.

    UNIVERSES, read by [About] under [Set Printing Universes] on all
    twenty-six named constants (the inductive and its six constructors
    included).  Each binder names the levels its statement fixes, then
    [+]: [a c p], the three levels of [RingObject@{a c p}], for the
    ring-level constants ([rcomm], [InCommIdeal], [CommIdeal],
    [Commutativize], [IsCommutative], [Commutativize_comm],
    [CommutativizeC]); [u p], the object and hom levels of [Rng@{u p}],
    for the rest.  [InCommIdeal@{a c p}] reads
    [∀ R : RingObject@{a c p}, carrier … → Type@{max(c,p)}], its
    constructors carry the same three levels, and neither has a
    constraint beyond [c <= a], [p <= a].  [Commutativize] keeps the
    carrier level: [RingObject@{a c p} → RingObject@{u c u0}].  No block
    carries an equation.  Fourteen blocks carry an own [Set] bound:
    thirteen [Set < u] on [Rng]'s object level, which is [Rng]'s own
    ([About Rng]: [Set < u]; the [PropEquiv] field puts [Set+1] in the
    ring record's sort), and [CommutativizeC] on the object level of
    the [CRng] it lands in ([About CRng] carries the same bound).
    Eleven blocks read [Set < Projections.u0], each following from an
    own [Set] bound and the block's caps, and every global universe in
    every block is an upper bound.  Against a copy with every binder
    removed, compared under [Set Printing All], no constant lost a
    universe or gained an identification.

    AXIOMS.  All thirty constants of this module, the twenty-six above
    and the four eliminators of [InCommIdeal] ([_rect], [_ind], [_rec],
    [_sind]), are closed under the global context.

    NOT DELIVERED.
      - No statement that [InCommIdeal] is the SMALLEST ideal containing
        the commutators; the universal property is what is used.
      - No computation of R/[R, R] for a particular R beyond the UT2
        facts of the satellite.
      - No Riehl 5.3.ii instantiation at this reflection, although
        Construction/Reflective/Monadic.v's [Reflective_Monadic] applies
        to [CRng_Reflective_in_Rng] as it stands.
      - Nothing for rigs, or for the commutative-monoid analogue. *)

Require Import Category.Lib.
Require Import Category.Lib.Setoid.Propositional.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Universal.Arrow.
Require Import Category.Construction.Subcategory.
Require Import Category.Construction.Reflective.
Require Import Category.Instance.Sets.
Require Import Category.Instance.CMon.
Require Import Category.Instance.Ab.
Require Import Category.Instance.Ab.Subtract.
Require Import Category.Theory.Algebra.Rig.
Require Import Category.Instance.Rng.
Require Import Category.Instance.Rng.Quotient.

Generalizable All Variables.

(** ** The commutator ideal *)

(* The commutator [a, b] = ab − ba. *)
Definition rcomm@{a c p +} (R : RingObject@{a c p})
  (x y : carrier (rig_setoid R)) :
  carrier (rig_setoid R) :=
  ab_sub (ring_ab R) (rig_mul R x y) (rig_mul R y x).

(* The two-sided ideal GENERATED by the commutators, as a ≈-saturated
   inductive generation.  Under the project-wide uniform inductive
   parameters the constructors omit [R]. *)
Inductive InCommIdeal@{a c p +} (R : RingObject@{a c p}) :
  carrier (rig_setoid R) → Type :=
  | ici_gen (a b : carrier (rig_setoid R)) : InCommIdeal (rcomm R a b)
  | ici_zero : InCommIdeal (rig_zero R)
  | ici_add (a b : carrier (rig_setoid R)) :
      InCommIdeal a → InCommIdeal b → InCommIdeal (rig_add R a b)
  | ici_mul_l (r a : carrier (rig_setoid R)) :
      InCommIdeal a → InCommIdeal (rig_mul R r a)
  | ici_mul_r (a r : carrier (rig_setoid R)) :
      InCommIdeal a → InCommIdeal (rig_mul R a r)
  | ici_resp (a b : carrier (rig_setoid R)) :
      a ≈ b → InCommIdeal a → InCommIdeal b.

Arguments ici_gen {R} a b.
Arguments ici_zero {R}.
Arguments ici_add {R a b} _ _.
Arguments ici_mul_l {R} r {a} _.
Arguments ici_mul_r {R a} r _.
Arguments ici_resp {R a b} _ _.

(* The fields of Instance/Rng/Quotient.v's [Ideal] ARE the constructors. *)
Definition CommIdeal@{a c p +} (R : RingObject@{a c p}) : Ideal R := {|
  idl_mem      := InCommIdeal R;
  idl_resp     := fun a b H X => @ici_resp R a b H X;
  idl_zero     := @ici_zero R;
  idl_plus     := fun a b X Y => @ici_add R a b X Y;
  idl_absorb_l := fun r a X => @ici_mul_l R r a X;
  idl_absorb_r := fun a r X => @ici_mul_r R a r X
|}.

(** ** The quotient R/[R, R] is commutative *)

Definition Commutativize@{a c p +} (R : RingObject@{a c p}) : RingObject :=
  QuotientRing (CommIdeal R).

(* The membership predicate of Instance/Rng.v's [CRng_Sub], named. *)
Definition IsCommutative@{a c p +} (R : RingObject@{a c p}) : Type :=
  ∀ x y, rig_mul R x y ≈ rig_mul R y x.

Example IsCommutative_is_CRng_sobj@{u p +} (R : Rng@{u p}) :
  sobj Rng@{u p} CRng_Sub R = IsCommutative R := eq_refl.

Lemma Commutativize_comm@{a c p +} (R : RingObject@{a c p}) :
  IsCommutative (Commutativize R).
Proof.
  intros a b; simpl; unfold rquot_rel; constructor.
  exact (@ici_gen R a b).
Qed.

Definition CommutativizeC@{a c p +} (R : RingObject@{a c p}) : CRng :=
  (Commutativize R; Commutativize_comm R).

(** ** The universal property *)

(* A homomorphism into a commutative ring kills the commutator ideal: by
   induction on the generation, into the [Type]-valued equality of the
   target. *)
Lemma comm_kills@{u p +} {R K : Rng@{u p}} (HK : IsCommutative K)
  (f : R ~{Rng@{u p}}~> K) (a : carrier (rig_setoid R)) :
  InCommIdeal R a → rig_map f a ≈ rig_zero K.
Proof.
  intro Ha.
  induction Ha as [a b | | a b _ IHa _ IHb | r a _ IHa | a r _ IHa
                  | a b Hab _ IHa].
  - unfold rcomm; rewrite (rig_map_sub f).
    apply (snd (ab_sub_eq_zero_iff (ring_ab K) _ _)); simpl.
    rewrite !(rig_map_mul f). apply HK.
  - apply (rig_map_zero f).
  - rewrite (rig_map_add f), IHa, IHb. apply rig_add_zero_l.
  - rewrite (rig_map_mul f), IHa. apply rig_mul_zero_r.
  - rewrite (rig_map_mul f), IHa. apply rig_mul_zero_l.
  - rewrite <- Hab; exact IHa.
Qed.

(* The mediator is Instance/Rng/Quotient.v's [rquot_med], fed the map
   together with [comm_kills]. *)
Theorem crng_universal@{u p +} (R : Rng@{u p}) :
  ∀ (d : CRng) (f : R ~{Rng@{u p}}~> Incl Rng@{u p} CRng_Sub d),
    ∃! g : CommutativizeC R ~{CRng}~> d,
      f ≈ fmap[Incl Rng@{u p} CRng_Sub] g ∘ rquot_proj (CommIdeal R).
Proof.
  intros d f.
  pose (p := existT (fun h : R ~{Rng}~> `1 d =>
                       ∀ a, idl_mem (CommIdeal R) a →
                            rig_map h a ≈ rig_zero `1 d)
               f (comm_kills `2 d f)).
  unshelve eexists.
  - exact (rquot_med (CommIdeal R) p; I).
  - intro a; simpl; reflexivity.
  - intros g Hg a; simpl.
    exact (Hg a).
Defined.

Definition crng_universal_arrow@{u p +} (R : Rng@{u p})
  : @UniversalArrow Rng@{u p} CRng R (Incl Rng@{u p} CRng_Sub) :=
  @universal_arrow_from_UMP Rng@{u p} CRng R (Incl Rng@{u p} CRng_Sub)
    (CommutativizeC R) (rquot_proj (CommIdeal R)) (crng_universal R).

Definition CRng_reflector@{u p +} : Rng@{u p} ⟶ CRng :=
  LeftAdjointFunctorFromUniversalArrows (Incl Rng@{u p} CRng_Sub)
    crng_universal_arrow.

Definition CRng_adj@{u p +} : CRng_reflector ⊣ Incl Rng@{u p} CRng_Sub :=
  AdjunctionFromUniversalArrows (Incl Rng@{u p} CRng_Sub)
    crng_universal_arrow.

(* Riehl 4.6.13 (ii), second half: CRing is reflective in Ring.  The
   fullness field is Instance/Rng.v's [CRng_Full], unchanged. *)
Definition CRng_Reflective_in_Rng@{u p +} : @Reflective Rng@{u p} CRng_Sub :=
  @Build_Reflective Rng@{u p} CRng_Sub CRng_Full CRng_reflector CRng_adj.

(** ** Readbacks: the unit is the quotient map *)

Example crng_reflector_obj@{u p +} (R : Rng@{u p}) :
  `1 (fobj[CRng_reflector] R) = QuotientRing (CommIdeal R) := eq_refl.

Example crng_arrow_is_proj@{u p +} (R : Rng@{u p}) :
  @arrow Rng@{u p} CRng R (Incl Rng@{u p} CRng_Sub) (crng_universal_arrow R)
    = rquot_proj (CommIdeal R) := eq_refl.

Definition crng_unit@{u p +} (R : Rng@{u p})
  : R ~{Rng@{u p}}~> Incl Rng@{u p} CRng_Sub (fobj[CRng_reflector] R) :=
  @Category.Theory.Adjunction.unit _ _ _ _ CRng_adj R.

Example crng_unit_pointwise@{u p +} (R : Rng@{u p})
  (a : carrier (rig_setoid R)) :
  rig_map (crng_unit R) a = rig_map (rquot_proj (CommIdeal R)) a := eq_refl.

Lemma crng_unit_is_proj@{u p +} (R : Rng@{u p}) :
  crng_unit R ≈ rquot_proj (CommIdeal R).
Proof. intro a; reflexivity. Defined.

(* Mac Lane p. 91: at a commutative R, R/[R,R] ≅ R. *)
Definition crng_reflect_iso@{u p +} (R : Sub Rng@{u p} CRng_Sub) :
  fobj[CRng_reflector] (fobj[Incl Rng@{u p} CRng_Sub] R) ≅[CRng] R :=
  reflective_counit_iso CRng_Reflective_in_Rng R.
