Require Import Coq.ZArith.ZArith.

Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Universal.Arrow.
Require Import Category.Structure.Monoidal.
Require Import Category.Theory.Algebra.Monoid.
Require Import Category.Theory.Algebra.Monoid.Hom.
Require Import Category.Theory.Algebra.Rig.
Require Import Category.Instance.Sets.
Require Import Category.Instance.CMon.
Require Import Category.Instance.Ab.
Require Import Category.Instance.Rng.
Require Import Category.Instance.Rng.Algebras.
Require Import Category.Instance.Rng.Polynomial.
Require Import Category.Instance.Rng.Algebras.Associative.
Require Import Category.Instance.Mod.

Generalizable All Variables.

#[local] Obligation Tactic := idtac.

(** * The monoid ring R[M], and ℤ[M] as a universal arrow

    Book: Mac Lane, "Categories for the Working Mathematician", 2nd ed.,
          GTM 5, §III.1, printed p. 59, Exercise 1 — the integral group
          ring exhibited as a universal arrow (maclane:III.1:ex1); the
          roster of free constructions on printed p. 56
          (maclane:III.1:remark2)
    nLab:      https://ncatlab.org/nlab/show/monoid+algebra
    nLab:      https://ncatlab.org/nlab/show/group+algebra
    Wikipedia: https://en.wikipedia.org/wiki/Group_ring

    WHAT THE EXERCISE ASKS, AND THE GENERALIZATION TAKEN.  Mac Lane's
    Exercise 1 names the INTEGRAL GROUP RING ℤ[G] and asks for it as a
    universal arrow.  The construction never uses inverses, so what is
    built here is the MONOID ring R[M] over an arbitrary base ring R — as
    issue #310 itself proposes ("better, monoid ring") — with the group
    case read off it in Instance/Rng/GroupRing.v, where the target is the
    group of units and the exercise's own phrasing is recovered.
    Splitting the two costs nothing and buys the general statement: over
    ℤ the universal arrow below is stated against the whole of [Rng], not
    only against commutative rings, because ℤ is central in every unital
    ring.

    WHICH CATEGORY OF MONOIDS.  There are two records in this tree that
    could be called a setoid monoid, and letting them drift would be a
    mistake, so the choice is stated.  Construction/Deloop.v's
    [MonObject] is a bare record — carrier, unit, operation, three laws —
    used by the delooping dictionary, by Instance/Matr/GL.v's [UnitsOf]
    and by Instance/Grp.v.  Theory/Algebra/Monoid/Hom.v's [Mon C] is the
    category of INTERNAL monoids in a monoidal category, and at
    [(Sets, ∏)] its objects are the same mathematical thing packaged as a
    multiplication morphism out of the product setoid.  This file uses
    the SECOND, for one decisive reason: Theory/Algebra/Rig.v already
    builds [Rig_Forget_Mon : Rig ⟶ Mon Sets], the multiplicative-monoid
    forgetful functor, and a universal arrow needs a functor to be
    universal TO.  [MonSets] below abbreviates that category and
    [Rng_Forget_Mon] extends the donor functor along [Ring_Forget_Rig];
    the element-level reading is recovered by [mop] and [mone], and all
    four readings at a ring hold by [eq_refl] ([rng_forget_mon_carrier]
    and its three siblings).  Instance/Rep.v had to bridge two
    identically named [GrpObject] records with [grp_mon] and says so;
    this file avoids the bridge by never introducing the second record.

    HOW R[M] IS PRESENTED.  By generators and relations, in the pattern of
    Instance/Ab/Tensor.v, Instance/Mod/Free.v, Instance/Mod/Tensor.v,
    Instance/Rng/Polynomial.v and Instance/Vect/TensorAlgebra.v: [MRTerm]
    is a plain inductive of formal expressions built from scalars,
    generators, sum, negation and product, and [mr_eq] is the congruence
    generated by the ring laws (multiplication NOT commutative), the two
    clauses making the scalar inclusion a ring homomorphism, the two
    making the generator insertion a homomorphism of monoids, and ONE
    further equation: scalars commute with generators.  That last one is
    not decoration.  In the classical monoid ring R[M] = ⊕_{m∈M} R the
    element r·e commutes with 1·m because e·m = m·e = m, so the equation
    HOLDS there and has to be imposed if the construction is to be R[M];
    what the construction would present WITHOUT it is not investigated
    here and no claim about that is made.  Note that the equation is
    imposed between scalars and GENERATORS only, and correspondingly
    [mring_scal_central] proves the scalars central only under
    commutativity of R; no claim is made that centrality is FALSE over a
    non-commutative R.

    What is given up by this presentation is the coefficient
    decomposition: there is no support function, no coefficient
    extraction, no normal form, and hence no decision procedure for
    equality in R[M].  What is kept, and is what a reader of §III.1
    wants, is that the construction does not collapse — see the witnesses
    at the end, all obtained by mapping OUT into a concrete ring.

    STRENGTHS, MEASURED.

      - [eq_refl]: the extension restricted to generators IS the given
        monoid homomorphism and restricted to scalars IS the given ring
        homomorphism ([mring_extend_gen], [mring_extend_scal]); the four
        element-level readings of [Rng_Forget_Mon]; the universal arrow
        IS the insertion ([zmring_arrow_is_insert]); the free functor's
        object part IS [ZMonRing] ([MonoidRingFunctor_obj]); the unit of
        the adjunction IS the insertion ([zmring_unit_is_gen]); and the
        concrete evaluations in the witness section reduce.
      - `≈` only, and this was tried strictly first: preservation of ZERO
        and of ONE by the extension, for the same reason
        Instance/Rng/Polynomial.v records for K[x] — the zero and the one
        of R[M] are scalars, so the fold returns the structure map's value
        there and reaching the target's zero and one is that map's own
        preservation law.
      - `≈` only, unavoidably: the transposes obtained from
        [ump_universal_arrows], which is [Qed]-opaque.  The counit of
        [zmring_adjunction] is on that side and no [eq_refl] is claimed
        for it.

    WHAT IS DELIVERED.

      - [MonoidRing R M] for an arbitrary [RingObject] R and an arbitrary
        object M of [Mon Sets], with [mring_scal] and [mring_gen];
      - [mring_extend] and [mring_extend_unique], the universal property
        in element form, over the hypothesis [MRComm] that the images of R
        and of M commute — which is exactly what holds in R[M] itself, and
        that is a theorem here rather than prose: [mring_comm_self]
        discharges the hypothesis at the two insertions, and
        [mring_extend_self] then shows the resulting extension is the
        identity;
      - [zmring_universal_arrow : UniversalArrow M Rng_Forget_Mon] and
        [zmring_auniversal_arrow]: ℤ[M] is the free unital ring on the
        monoid M, in both of Theory/Universal/Arrow.v's encodings, with
        the left-adjoint reading [MonoidRingFunctor] and
        [zmring_adjunction : MonoidRingFunctor ⊣ Rng_Forget_Mon];
      - [mring_AAlg]: over a COMMUTATIVE base ring, R[M] is an object of
        Instance/Rng/Algebras/Associative.v's category of associative
        R-algebras — the scalars are central, by an induction that is a
        theorem rather than a further generating equation;
      - non-degeneracy, proved: [zmring_gen_not_scalar],
        [zmring_nontrivial] and [zmring_not_commutative], each by mapping
        out into the upper-triangular matrix ring of
        Instance/Rng/Algebras/Associative.v, whose multiplicative monoid
        is a non-commutative monoid available with no new construction.

    WHAT IS NOT DELIVERED.  No support, no coefficient uniqueness, no
    normal form, no decision procedure, no dimension.  No augmentation map
    R[M] → R and hence no augmentation ideal.  No comparison with
    Instance/Mod/Free.v's free module: R[M] is NOT shown to be the free
    R-module on M's carrier with convolution product.  That route was
    considered and not taken, and the reason is structural rather than a
    matter of taste.  Defining the convolution (f * g) at m as the sum
    over factorizations a·b = m needs the coefficients of an element to be
    DETERMINED by it, and Instance/Mod/Free.v does not supply that: its
    [fv_normal_form] proves every element equal to some finite formal
    combination, but its own deferral list says "No uniqueness of
    coefficients ... what is missing is not the existence of a
    linear-combination form but its CANONICITY".  A convolution defined
    off a non-canonical list would have to be shown independent of the
    choice, which is the missing half.  So the reuse would not be the
    cheap one it looks like.  No monoid
    ring over a non-commutative R as an algebra, for the reason stated
    above.  The group-ring reading against the units functor lives in
    Instance/Rng/GroupRing.v, not here. *)

(** ** The category of setoid monoids, at the element level

    [Mon Sets] states its laws through the tensor bifunctor and the
    unitors; the four readings below turn them back into element
    equations, which is what a construction by generators and relations
    consumes.  Each is one projection of the class applied at a literal
    pair, with no proof of its own. *)

Definition MonSets : Category := @Mon Sets Sets_Product_Monoidal.

Definition mcar (M : MonSets) : SetoidObject := `1 M.

Definition mop (M : MonSets) (a b : carrier (mcar M)) : carrier (mcar M) :=
  @mu Sets Sets_Product_Monoidal _ (`2 M) (a, b).

Definition mone (M : MonSets) : carrier (mcar M) :=
  @eta Sets Sets_Product_Monoidal _ (`2 M) ttt.

Lemma mop_respects (M : MonSets) : Proper (equiv ==> equiv ==> equiv) (mop M).
Proof.
  intros a a' Ha b b' Hb.
  exact (proper_morphism (@mu Sets Sets_Product_Monoidal _ (`2 M))
           (a, b) (a', b') (Ha, Hb)).
Qed.

Lemma mop_assoc (M : MonSets) (a b c : carrier (mcar M)) :
  mop M (mop M a b) c ≈ mop M a (mop M b c).
Proof. exact (@mu_assoc Sets Sets_Product_Monoidal _ (`2 M) ((a, b), c)). Qed.

Lemma mop_one_l (M : MonSets) (a : carrier (mcar M)) : mop M (mone M) a ≈ a.
Proof. exact (@mu_unit_left Sets Sets_Product_Monoidal _ (`2 M) (ttt, a)). Qed.

Lemma mop_one_r (M : MonSets) (a : carrier (mcar M)) : mop M a (mone M) ≈ a.
Proof. exact (@mu_unit_right Sets Sets_Product_Monoidal _ (`2 M) (a, ttt)). Qed.

Definition mmap {M N : MonSets} (f : M ~{MonSets}~> N)
  : carrier (mcar M) → carrier (mcar N) := `1 f.

Lemma mmap_op {M N : MonSets} (f : M ~{MonSets}~> N) (a b : carrier (mcar M)) :
  mmap f (mop M a b) ≈ mop N (mmap f a) (mmap f b).
Proof. exact (@hom_mu Sets Sets_Product_Monoidal _ _ _ _ _ (`2 f) (a, b)). Qed.

Lemma mmap_one {M N : MonSets} (f : M ~{MonSets}~> N) :
  mmap f (mone M) ≈ mone N.
Proof. exact (@hom_eta Sets Sets_Product_Monoidal _ _ _ _ _ (`2 f) ttt). Qed.

(* ...and back: element-level data assembles into a morphism of [MonSets]. *)
Program Definition mhom {M N : MonSets}
  (f : carrier (mcar M) → carrier (mcar N))
  (fp : Proper (equiv ==> equiv) f)
  (fo : ∀ a b, f (mop M a b) ≈ mop N (f a) (f b))
  (fu : f (mone M) ≈ mone N) : M ~{MonSets}~> N :=
  (({| morphism := f |} : mcar M ~{Sets}~> mcar N); _).
Next Obligation.
  intros M N f fp fo fu.
  unshelve econstructor.
  - intros [a b]; simpl; apply fo.
  - intros []; simpl; apply fu.
Qed.

(** The multiplicative-monoid forgetful functor of RINGS, obtained by
    extending Theory/Algebra/Rig.v's [Rig_Forget_Mon] along
    [Ring_Forget_Rig].  All four element-level readings hold on the
    nose. *)
Definition Rng_Forget_Mon : Rng ⟶ MonSets := Rig_Forget_Mon ◯ Ring_Forget_Rig.

Example rng_forget_mon_carrier (S : Rng) :
  mcar (Rng_Forget_Mon S) = rig_setoid S := eq_refl.
Example rng_forget_mon_op (S : Rng) (a b : carrier (rig_setoid S)) :
  mop (Rng_Forget_Mon S) a b = rig_mul S a b := eq_refl.
Example rng_forget_mon_one (S : Rng) :
  mone (Rng_Forget_Mon S) = rig_one S := eq_refl.
Example rng_forget_mon_map (S T : Rng) (f : S ~{Rng}~> T)
  (a : carrier (rig_setoid S)) :
  mmap (fmap[Rng_Forget_Mon] f) a = rig_map f a := eq_refl.

(** * The term algebra *)

Section MonoidRing.

Context (R : RingObject).
Context (M : MonSets).

Inductive MRTerm : Type :=
  | mr_scal : carrier (rig_setoid R) → MRTerm
  | mr_gen  : carrier (mcar M) → MRTerm
  | mr_add  : MRTerm → MRTerm → MRTerm
  | mr_neg  : MRTerm → MRTerm
  | mr_mul  : MRTerm → MRTerm → MRTerm.

Inductive mr_eq : MRTerm → MRTerm → Type :=
  (* congruence for each former, saturating under the two source setoids *)
  | me_scal {a b} : a ≈ b → mr_eq (mr_scal a) (mr_scal b)
  | me_gen {a b} : a ≈ b → mr_eq (mr_gen a) (mr_gen b)
  | me_add {s s' t t'} :
      mr_eq s s' → mr_eq t t' → mr_eq (mr_add s t) (mr_add s' t')
  | me_neg {s s'} : mr_eq s s' → mr_eq (mr_neg s) (mr_neg s')
  | me_mul {s s' t t'} :
      mr_eq s s' → mr_eq t t' → mr_eq (mr_mul s t) (mr_mul s' t')

  (* abelian group under addition *)
  | me_add_assoc s t u :
      mr_eq (mr_add (mr_add s t) u) (mr_add s (mr_add t u))
  | me_add_comm s t : mr_eq (mr_add s t) (mr_add t s)
  | me_add_zero_l s : mr_eq (mr_add (mr_scal (rig_zero R)) s) s
  | me_add_neg_l s : mr_eq (mr_add (mr_neg s) s) (mr_scal (rig_zero R))

  (* monoid under multiplication — commutativity is NOT among the laws *)
  | me_mul_assoc s t u :
      mr_eq (mr_mul (mr_mul s t) u) (mr_mul s (mr_mul t u))
  | me_mul_one_l s : mr_eq (mr_mul (mr_scal (rig_one R)) s) s
  | me_mul_one_r s : mr_eq (mr_mul s (mr_scal (rig_one R))) s

  (* distributivity on both sides *)
  | me_distr_l s t u :
      mr_eq (mr_mul s (mr_add t u)) (mr_add (mr_mul s t) (mr_mul s u))
  | me_distr_r s t u :
      mr_eq (mr_mul (mr_add s t) u) (mr_add (mr_mul s u) (mr_mul t u))

  (* the scalar inclusion is a homomorphism of rings *)
  | me_scal_add a b :
      mr_eq (mr_scal (rig_add R a b)) (mr_add (mr_scal a) (mr_scal b))
  | me_scal_mul a b :
      mr_eq (mr_scal (rig_mul R a b)) (mr_mul (mr_scal a) (mr_scal b))

  (* the generator insertion is a homomorphism of monoids *)
  | me_gen_op a b :
      mr_eq (mr_gen (mop M a b)) (mr_mul (mr_gen a) (mr_gen b))
  | me_gen_one : mr_eq (mr_gen (mone M)) (mr_scal (rig_one R))

  (* scalars commute with the generators — true in R[M], and not
     derivable from the rest *)
  | me_scal_gen a m :
      mr_eq (mr_mul (mr_scal a) (mr_gen m)) (mr_mul (mr_gen m) (mr_scal a))

  | me_sym {s t} : mr_eq s t → mr_eq t s
  | me_trans {s t u} : mr_eq s t → mr_eq t u → mr_eq s u.

Lemma mr_refl (s : MRTerm) : mr_eq s s.
Proof.
  induction s.
  - exact (me_scal (reflexivity _)).
  - exact (me_gen (reflexivity _)).
  - exact (me_add IHs1 IHs2).
  - exact (me_neg IHs).
  - exact (me_mul IHs1 IHs2).
Qed.

Lemma mr_eq_Equivalence : Equivalence mr_eq.
Proof.
  constructor.
  - exact mr_refl.
  - exact (fun s t => me_sym).
  - exact (fun s t u => me_trans).
Qed.

Definition mr_Setoid : Setoid MRTerm := {|
  equiv        := mr_eq;
  setoid_equiv := mr_eq_Equivalence
|}.

(** ** Derived laws *)

Let MZ : MRTerm := mr_scal (rig_zero R).
Let MO : MRTerm := mr_scal (rig_one R).

Lemma me_add_zero_r (s : MRTerm) : mr_eq (mr_add s MZ) s.
Proof. exact (me_trans (me_add_comm s MZ) (me_add_zero_l s)). Qed.

Lemma me_add_neg_r (s : MRTerm) : mr_eq (mr_add s (mr_neg s)) MZ.
Proof. exact (me_trans (me_add_comm s (mr_neg s)) (me_add_neg_l s)). Qed.

Lemma me_add_cancel_l (s t u : MRTerm) :
  mr_eq (mr_add s t) (mr_add s u) → mr_eq t u.
Proof.
  intro H.
  refine (me_trans (me_sym (me_add_zero_l t)) _).
  refine (me_trans (me_add (me_sym (me_add_neg_l s)) (mr_refl t)) _).
  refine (me_trans (me_add_assoc (mr_neg s) s t) _).
  refine (me_trans (me_add (mr_refl (mr_neg s)) H) _).
  refine (me_trans (me_sym (me_add_assoc (mr_neg s) s u)) _).
  refine (me_trans (me_add (me_add_neg_l s) (mr_refl u)) _).
  exact (me_add_zero_l u).
Qed.

Lemma me_mul_zero_l (s : MRTerm) : mr_eq (mr_mul MZ s) MZ.
Proof.
  apply (me_add_cancel_l (mr_mul MZ s)).
  refine (me_trans (me_sym (me_distr_r MZ MZ s)) _).
  refine (me_trans (me_mul _ (mr_refl s))
            (me_sym (me_add_zero_r (mr_mul MZ s)))).
  refine (me_trans (me_sym (me_scal_add (rig_zero R) (rig_zero R))) _).
  exact (me_scal (rig_add_zero_l R (rig_zero R))).
Qed.

Lemma me_mul_zero_r (s : MRTerm) : mr_eq (mr_mul s MZ) MZ.
Proof.
  apply (me_add_cancel_l (mr_mul s MZ)).
  refine (me_trans (me_sym (me_distr_l s MZ MZ)) _).
  refine (me_trans (me_mul (mr_refl s) _)
            (me_sym (me_add_zero_r (mr_mul s MZ)))).
  refine (me_trans (me_sym (me_scal_add (rig_zero R) (rig_zero R))) _).
  exact (me_scal (rig_add_zero_l R (rig_zero R))).
Qed.

(** ** The ring R[M] *)

Definition MonoidRig : RigObject := {|
  rig_setoid := {| carrier := MRTerm; is_setoid := mr_Setoid |};
  rig_zero := MZ;
  rig_add := mr_add;
  rig_one := MO;
  rig_mul := mr_mul;
  rig_add_respects := fun _ _ Hs _ _ Ht => me_add Hs Ht;
  rig_mul_respects := fun _ _ Hs _ _ Ht => me_mul Hs Ht;
  rig_add_assoc := me_add_assoc;
  rig_add_comm := me_add_comm;
  rig_add_zero_l := me_add_zero_l;
  rig_mul_assoc := me_mul_assoc;
  rig_mul_one_l := me_mul_one_l;
  rig_mul_one_r := me_mul_one_r;
  rig_distr_l := me_distr_l;
  rig_distr_r := me_distr_r;
  rig_mul_zero_l := me_mul_zero_l;
  rig_mul_zero_r := me_mul_zero_r
|}.

Definition MonoidRing : RingObject := {|
  ring_rig := MonoidRig;
  ring_neg := mr_neg;
  ring_neg_respects := fun _ _ Hs => me_neg Hs;
  ring_neg_l := me_add_neg_l
|}.

(** ** The two insertions *)

Program Definition mring_scal : R ~{Rng}~> MonoidRing := {|
  rig_map := {| morphism := mr_scal |}
|}.
Next Obligation. intros a b H; exact (me_scal H). Qed.
Next Obligation. simpl; exact (mr_refl MZ). Qed.
Next Obligation. intros a b; exact (me_scal_add a b). Qed.
Next Obligation. simpl; exact (mr_refl MO). Qed.
Next Obligation. intros a b; exact (me_scal_mul a b). Qed.

(** Over a COMMUTATIVE base ring the scalars are central in R[M].  This is
    a theorem, by induction on the term, and it is what makes R[M] an
    R-algebra; over a non-commutative R it is false already at the scalars,
    which is why the generating equation [me_scal_gen] is imposed between
    scalars and GENERATORS only. *)
Lemma mring_scal_central
  (Rcomm : ∀ a b, rig_mul R a b ≈ rig_mul R b a)
  (r : carrier (rig_setoid R)) (t : MRTerm) :
  mr_eq (mr_mul (mr_scal r) t) (mr_mul t (mr_scal r)).
Proof.
  induction t as [ a | m | s IHs u IHu | s IHs | s IHs u IHu ].
  - refine (me_trans (me_sym (me_scal_mul r a)) _).
    refine (me_trans (me_scal (Rcomm r a)) _).
    exact (me_scal_mul a r).
  - exact (me_scal_gen r m).
  - refine (me_trans (me_distr_l (mr_scal r) s u) _).
    refine (me_trans (me_add IHs IHu) _).
    exact (me_sym (me_distr_r s u (mr_scal r))).
  - refine (me_trans (rng_mul_neg_r MonoidRing (mr_scal r) s) _).
    refine (me_trans (me_neg IHs) _).
    exact (me_sym (rng_mul_neg_l MonoidRing s (mr_scal r))).
  - refine (me_trans (me_sym (me_mul_assoc (mr_scal r) s u)) _).
    refine (me_trans (me_mul IHs (mr_refl u)) _).
    refine (me_trans (me_mul_assoc s (mr_scal r) u) _).
    refine (me_trans (me_mul (mr_refl s) IHu) _).
    exact (me_sym (me_mul_assoc s u (mr_scal r))).
Qed.

End MonoidRing.

Arguments mr_scal {R M} a.
Arguments mr_gen {R M} m.
Arguments mr_add {R M} s t.
Arguments mr_neg {R M} s.
Arguments mr_mul {R M} s t.
Arguments mr_eq {R M} s t.
Arguments mr_refl {R M} s.

(** The generator insertion, as a morphism of [MonSets].  It is stated
    OUTSIDE the section deliberately: mentioning [Rng_Forget_Mon] inside
    would tie the section variable R's universes to those of [MonSets],
    through the functor's identification of source and target hom
    universes, and the ring S of the evaluation section could then no
    longer be an arbitrary [RingObject].  Stated here, with R and M
    explicit, nothing is tied. *)
Definition mring_gen (R : RingObject) (M : MonSets)
  : M ~{MonSets}~> Rng_Forget_Mon (MonoidRing R M) :=
  @mhom M (Rng_Forget_Mon (MonoidRing R M)) (@mr_gen R M)
    (fun a b H => me_gen R M H) (me_gen_op R M) (me_gen_one R M).

Example mring_gen_computes (R : RingObject) (M : MonSets)
  (m : carrier (mcar M)) : mmap (mring_gen R M) m = mr_gen m := eq_refl.

(** * Evaluation: the universal property in element form

    Given a ring S, a ring homomorphism phi out of R and a monoid
    homomorphism psi out of M into S's multiplicative monoid whose images
    COMMUTE, every formal element of R[M] has a value in S.  The
    commutation hypothesis is exactly what makes the fold respect the
    generating equation [me_scal_gen]; it holds in R[M] itself, and over
    ℤ it is discharged outright by the centrality of the integers.

    A UNIVERSE MEASUREMENT, and why this development is not in a section.
    [Rig_Forget_Mon] — hence [Rng_Forget_Mon] — is instantiable only at
    [RigObject@{Set Set _}], that is, at rigs whose carrier and whose [≈]
    both live in [Set].  The restriction is the DONOR'S, introduced by
    universe minimization inside Theory/Algebra/Rig.v's
    [rig_mult_monoid], not by anything here, and it is not shown to be
    unavoidable; a variant of that donor carrying explicit binders would
    lift it.  Its one visible consequence is structural: a section
    variable [S : RingObject] has its universes fixed at the [Context]
    command, and a later mention of [Rng_Forget_Mon S] inside the same
    section is then rejected, so the whole of the evaluation development
    is stated at top level with R, M and S as ordinary arguments.  At top
    level the constraint is absorbed into each constant's own instance,
    which is why everything below elaborates.  The consequence for the
    RESULTS is that [zmring_universal_arrow] and its consequences are
    statements about rings whose carrier sits in [Set] — a class that
    contains every concrete ALGEBRAIC ring in this tree ([Int_Ring],
    [Q_Ring], [Zero_Ring], [F2_Ring], [FracRing], [ZPoly] and [UT2] all
    instantiate, the witnesses used below among them).  The one closed
    [RingObject] it EXCLUDES is [CRingOb X], the ring of continuous
    real-valued functions: [Top]'s opens sit strictly above its points,
    so that carrier is above [Set] and can never reach
    [RigObject@{Set Set _}].  Test/ProbeAlgebras.v pins the boundary: a positive
    control at [Int_Ring@{Set Set Set}] against a rejected instance one
    universe up, for the donor and for the functor built from it. *)

Definition MRComm {R : RingObject} {M : MonSets} {S : RingObject}
  (phi : R ~{Rng}~> S) (psi : M ~{MonSets}~> Rng_Forget_Mon S) : Type :=
  ∀ (a : carrier (rig_setoid R)) (m : carrier (mcar M)),
    rig_mul S (rig_map phi a) (mmap psi m)
      ≈ rig_mul S (mmap psi m) (rig_map phi a).

Fixpoint mreval {R : RingObject} {M : MonSets} {S : RingObject}
  (phi : R ~{Rng}~> S) (psi : M ~{MonSets}~> Rng_Forget_Mon S)
  (t : MRTerm R M) : carrier (rig_setoid S) :=
  match t with
  | mr_scal a  => rig_map phi a
  | mr_gen m   => mmap psi m
  | mr_add s t => rig_add S (mreval phi psi s) (mreval phi psi t)
  | mr_neg s   => ring_neg S (mreval phi psi s)
  | mr_mul s t => rig_mul S (mreval phi psi s) (mreval phi psi t)
  end.

(** Twenty-one cases, one per constructor of [mr_eq].  Five are congruence
    for a former, the first two saturating under the source setoids; seven
    are ring laws of S, four of those additionally spending a preservation
    law of [phi], because the zero and the one of R[M] are scalars rather
    than formers of their own; two are [phi]'s preservation of sums and of
    products; two are [psi]'s preservation of the operation and of the
    unit, the second of these also spending [phi]'s preservation of the
    one; one is the commutation hypothesis; and the last two are the
    target setoid's symmetry and transitivity. *)
Lemma mreval_respects {R : RingObject} {M : MonSets} {S : RingObject}
  (phi : R ~{Rng}~> S) (psi : M ~{MonSets}~> Rng_Forget_Mon S)
  (Hcomm : MRComm phi psi) (s t : MRTerm R M) :
  mr_eq s t → mreval phi psi s ≈ mreval phi psi t.
Proof.
  intro He.
  induction He as
    [ a b Hab
    | a b Hab
    | s s' t t' _ IHs _ IHt
    | s s' _ IHs
    | s s' t t' _ IHs _ IHt
    | s t u | s t | s | s
    | s t u | s | s
    | s t u | s t u
    | a b | a b
    | a b |
    | a m
    | s t _ IHst
    | s t u _ IHst _ IHtu ]; simpl.
  - exact (proper_morphism (rig_map phi) _ _ Hab).
  - exact (proper_morphism (mmap psi : SetoidMorphism _ _) _ _ Hab).
  - exact (rig_add_respects S _ _ IHs _ _ IHt).
  - exact (ring_neg_respects S _ _ IHs).
  - exact (rig_mul_respects S _ _ IHs _ _ IHt).
  - exact (rig_add_assoc S _ _ _).
  - exact (rig_add_comm S _ _).
  - rewrite (rig_map_zero phi); apply rig_add_zero_l.
  - rewrite (rig_map_zero phi); apply (ring_neg_l S).
  - exact (rig_mul_assoc S _ _ _).
  - rewrite (rig_map_one phi); apply rig_mul_one_l.
  - rewrite (rig_map_one phi); apply rig_mul_one_r.
  - exact (rig_distr_l S _ _ _).
  - exact (rig_distr_r S _ _ _).
  - exact (rig_map_add phi a b).
  - exact (rig_map_mul phi a b).
  - exact (mmap_op psi a b).
  - rewrite (mmap_one psi); symmetry; apply (rig_map_one phi).
  - exact (Hcomm a m).
  - exact (symmetry IHst).
  - exact (transitivity IHst IHtu).
Qed.

Program Definition mring_extend {R : RingObject} {M : MonSets}
  {S : RingObject} (phi : R ~{Rng}~> S)
  (psi : M ~{MonSets}~> Rng_Forget_Mon S) (Hcomm : MRComm phi psi)
  : MonoidRing R M ~{Rng}~> S := {|
  rig_map := {| morphism := mreval phi psi |}
|}.
Next Obligation.
  intros R M S phi psi Hcomm s t He; exact (mreval_respects phi psi Hcomm s t He).
Qed.
Next Obligation.
  intros R M S phi psi Hcomm; simpl; exact (rig_map_zero phi).
Qed.
Next Obligation. intros R M S phi psi Hcomm s t; simpl; reflexivity. Qed.
Next Obligation.
  intros R M S phi psi Hcomm; simpl; exact (rig_map_one phi).
Qed.
Next Obligation. intros R M S phi psi Hcomm s t; simpl; reflexivity. Qed.

(** The extension restricts to [phi] on scalars and to [psi] on
    generators, both DEFINITIONALLY — the fixpoint's first two clauses are
    those equations.  This is the convertibility exception: the equations
    are between elements of S's carrier, not between morphisms. *)
Example mring_extend_scal {R : RingObject} {M : MonSets} {S : RingObject}
  (phi : R ~{Rng}~> S) (psi : M ~{MonSets}~> Rng_Forget_Mon S)
  (Hcomm : MRComm phi psi) (a : carrier (rig_setoid R)) :
  rig_map (mring_extend phi psi Hcomm) (mr_scal a) = rig_map phi a := eq_refl.

Example mring_extend_gen {R : RingObject} {M : MonSets} {S : RingObject}
  (phi : R ~{Rng}~> S) (psi : M ~{MonSets}~> Rng_Forget_Mon S)
  (Hcomm : MRComm phi psi) (m : carrier (mcar M)) :
  rig_map (mring_extend phi psi Hcomm) (mr_gen m) = mmap psi m := eq_refl.

(** Uniqueness: one case per former.  The two base cases are the
    hypotheses, and the other three are homomorphism laws of the
    competitor — preservation of sums, of negation (Theory/Algebra/Rig.v's
    [RigHom_neg], a theorem rather than a field) and of products. *)
Lemma mring_extend_unique {R : RingObject} {M : MonSets} {S : RingObject}
  (phi : R ~{Rng}~> S) (psi : M ~{MonSets}~> Rng_Forget_Mon S)
  (g : MonoidRing R M ~{Rng}~> S)
  (Hscal : ∀ a, rig_map g (mr_scal a) ≈ rig_map phi a)
  (Hgen : ∀ m, rig_map g (mr_gen m) ≈ mmap psi m) (t : MRTerm R M) :
  rig_map g t ≈ mreval phi psi t.
Proof.
  induction t as [ a | m | s IHs t IHt | s IHs | s IHs t IHt ]; simpl.
  - exact (Hscal a).
  - exact (Hgen m).
  - rewrite (rig_map_add g s t); exact (rig_add_respects S _ _ IHs _ _ IHt).
  - rewrite (RigHom_neg (MonoidRing R M) S g s).
    exact (ring_neg_respects S _ _ IHs).
  - rewrite (rig_map_mul g s t); exact (rig_mul_respects S _ _ IHs _ _ IHt).
Qed.

(** The commutation hypothesis of the universal property is not an
    artifact of the proof: it is exactly what holds in R[M] itself, by the
    generating equation, and the extension along the two insertions is
    then the identity.  Together they say that the universal property is
    applied at its own object with no side condition to discharge. *)

Lemma mring_comm_self (R : RingObject) (M : MonSets)
  : MRComm (mring_scal R M) (mring_gen R M).
Proof. intros a m; exact (me_scal_gen R M a m). Qed.

Lemma mring_extend_self (R : RingObject) (M : MonSets) (t : MRTerm R M) :
  rig_map (mring_extend (mring_scal R M) (mring_gen R M)
             (mring_comm_self R M)) t ≈ t.
Proof.
  symmetry.
  apply (mring_extend_unique (mring_scal R M) (mring_gen R M)
           (@id Rng (MonoidRing R M))).
  - intro a; exact (mr_refl _).
  - intro m; exact (mr_refl _).
Qed.

(** * R[M] as an associative R-algebra

    Over a commutative base ring the scalars are central, which is exactly
    the field Instance/Rng/Algebras/Associative.v's [AAlgObject] demands.
    [KAlg R] would not do: [zmring_not_commutative] below exhibits an M
    and a pair of generators whose two products cannot be identified in
    ℤ[M], so that ring is not commutative and is not an object of [KAlg].
    (Nothing here claims the converse — that R[M] IS commutative whenever
    R and M are — and no such statement is proved.)  This is the same
    obstruction Instance/Vect/TensorAlgebra.v runs into, and the same
    resolution. *)

Definition mring_AAlg (R : CRng) (M : MonSets) : AAlgObject R :=
  Build_AAlgObject R (MonoidRing (`1 R) M) (mring_scal (`1 R) M)
    (mring_scal_central (`1 R) M (`2 R)).

(** * Mac Lane §III.1 Exercise 1: ℤ[M] as a universal arrow

    Over ℤ the commutation hypothesis is free — the integers are central
    in EVERY unital ring, by Instance/Rng/Polynomial.v's [zring_central] —
    so the universal property is stated against the whole of [Rng], not
    only against commutative rings. *)

Definition ZMonRing (M : MonSets) : RingObject := MonoidRing Int_Ring M.

Definition zmring_insert (M : MonSets)
  : M ~{MonSets}~> Rng_Forget_Mon (ZMonRing M) :=
  mring_gen Int_Ring M.

(** Every ring homomorphism out of ℤ[M] agrees with [zring] on the
    scalars, because ℤ is initial in [Rng]: the restriction along the
    scalar inclusion is a homomorphism out of ℤ, and there is only one of
    those. *)
Lemma zmring_hom_scal (M : MonSets) (S : Rng) (g : ZMonRing M ~{Rng}~> S)
  (z : Z) : rig_map g (@mr_scal Int_Ring M z) ≈ zring S z.
Proof.
  exact (rng_from_Z_unique S (rig_hom_compose g (mring_scal Int_Ring M)) z).
Qed.

Definition zmring_eval (M : MonSets) (S : Rng)
  (h : M ~{MonSets}~> Rng_Forget_Mon S) : ZMonRing M ~{Rng}~> S.
Proof.
  refine (mring_extend (rng_from_Z S) h _).
  intros z m; simpl.
  apply zring_central.
Defined.

Lemma zmring_universal (M : MonSets) (S : Rng)
  (h : M ~{MonSets}~> Rng_Forget_Mon S) :
  ∃! g : ZMonRing M ~{Rng}~> S,
    h ≈ fmap[Rng_Forget_Mon] g ∘ zmring_insert M.
Proof.
  unshelve eexists.
  - exact (zmring_eval M S h).
  - intro m; simpl; reflexivity.
  - intros g Hg t; simpl.
    symmetry.
    apply (mring_extend_unique (rng_from_Z S) h g).
    + intro z; exact (zmring_hom_scal M S g z).
    + intro m; symmetry; exact (Hg m).
Qed.

Definition zmring_universal_arrow (M : MonSets)
  : UniversalArrow M Rng_Forget_Mon :=
  universal_arrow_from_UMP M Rng_Forget_Mon (ZMonRing M) (zmring_insert M)
    (zmring_universal M).

Program Definition zmring_auniversal_arrow (M : MonSets)
  : AUniversalArrow M Rng_Forget_Mon (ZMonRing M) := {|
  universal_arrow := zmring_insert M
|}.
Next Obligation.
  intros M S h.
  unshelve eexists.
  - exact (zmring_eval M S h).
  - intro m; simpl; reflexivity.
  - intros g Hg t; simpl.
    symmetry.
    apply (mring_extend_unique (rng_from_Z S) h g).
    + intro z; exact (zmring_hom_scal M S g z).
    + intro m; exact (Hg m).
Qed.

(** The left-adjoint reading: ℤ[−] is left adjoint to the
    multiplicative-monoid functor.  Both come out of the generic machinery
    with no further proof. *)
Definition MonoidRingFunctor : MonSets ⟶ Rng :=
  LeftAdjointFunctorFromUniversalArrows Rng_Forget_Mon zmring_universal_arrow.

Definition zmring_adjunction : MonoidRingFunctor ⊣ Rng_Forget_Mon :=
  AdjunctionFromUniversalArrows Rng_Forget_Mon zmring_universal_arrow.

Example MonoidRingFunctor_obj (M : MonSets) :
  fobj[MonoidRingFunctor] M = ZMonRing M := eq_refl.

Example zmring_arrow_is_insert (M : MonSets) :
  @arrow _ _ M Rng_Forget_Mon (zmring_universal_arrow M) = zmring_insert M
  := eq_refl.

Definition zmring_unit (M : MonSets)
  : M ~{MonSets}~> Rng_Forget_Mon (fobj[MonoidRingFunctor] M) :=
  @Category.Theory.Adjunction.unit _ _ _ _ zmring_adjunction M.

Example zmring_unit_is_gen (M : MonSets) (m : carrier (mcar M)) :
  mmap (zmring_unit M) m = @mr_gen Int_Ring M m := eq_refl.

(** * Non-degeneracy

    Nothing below is obtained by induction on [mr_eq]: an induction on a
    quotienting relation cannot produce a negative statement.  Every
    separation is obtained by mapping OUT into a concrete ring — here the
    upper-triangular 2×2 integer matrices of
    Instance/Rng/Algebras/Associative.v, whose multiplicative monoid is a
    NON-COMMUTATIVE monoid available with no new construction, so the
    witness monoid costs nothing. *)

Definition UT2_Mon : MonSets := Rng_Forget_Mon UT2.

(* The identity of UT2's carrier IS a monoid homomorphism from that
   multiplicative monoid to itself, since [Rng_Forget_Mon]'s operation and
   unit are UT2's own. *)
Definition ut2_mon_id : UT2_Mon ~{MonSets}~> Rng_Forget_Mon UT2 :=
  @id MonSets UT2_Mon.

Definition zmring_to_UT2 : ZMonRing UT2_Mon ~{Rng}~> UT2 :=
  zmring_eval UT2_Mon UT2 ut2_mon_id.

Example zmring_to_UT2_gen (x : ut2) :
  rig_map zmring_to_UT2 (@mr_gen Int_Ring UT2_Mon x) = x := eq_refl.

Example zmring_to_UT2_e11_e12 :
  rig_map zmring_to_UT2
    (mr_mul (@mr_gen Int_Ring UT2_Mon ut2_e11)
            (@mr_gen Int_Ring UT2_Mon ut2_e12)) = ut2_e12 := eq_refl.

Example zmring_to_UT2_e12_e11 :
  rig_map zmring_to_UT2
    (mr_mul (@mr_gen Int_Ring UT2_Mon ut2_e12)
            (@mr_gen Int_Ring UT2_Mon ut2_e11)) = ut2_zero := eq_refl.

(* ℤ[M] is non-commutative when M is. *)
Theorem zmring_not_commutative :
  mr_eq (mr_mul (@mr_gen Int_Ring UT2_Mon ut2_e11)
                (@mr_gen Int_Ring UT2_Mon ut2_e12))
        (mr_mul (@mr_gen Int_Ring UT2_Mon ut2_e12)
                (@mr_gen Int_Ring UT2_Mon ut2_e11)) → False.
Proof.
  intro H.
  apply UT2_not_commutative.
  exact (proper_morphism (rig_map zmring_to_UT2) _ _ H).
Qed.

(* A generator is not a scalar. *)
Theorem zmring_gen_not_scalar (r : Z) :
  mr_eq (@mr_gen Int_Ring UT2_Mon ut2_e12) (@mr_scal Int_Ring UT2_Mon r)
    → False.
Proof.
  intro H.
  (* The extension carries a scalar to [zring UT2 r], which does not
     reduce at an open [r]; [rng_from_Z_unique] identifies it with the
     scalar diagonal, which does. *)
  pose proof (proper_morphism (rig_map zmring_to_UT2) _ _ H) as H2.
  pose proof (rng_from_Z_unique UT2 ut2_scalar r) as H3.
  assert (Hx : ((0, 1, 0)%Z : ut2) = ((r, 0, r)%Z : ut2))
    by (unfold ut2_eqT in H2, H3; exact (eq_trans H2 (eq_sym H3))).
  inversion Hx.
Qed.

(* ...and the ring is not trivial. *)
Theorem zmring_nontrivial :
  mr_eq (@mr_scal Int_Ring UT2_Mon 1%Z) (@mr_scal Int_Ring UT2_Mon 0%Z)
    → False.
Proof.
  intro H.
  pose proof (proper_morphism (rig_map zmring_to_UT2) _ _ H) as H2.
  simpl in H2; unfold ut2_eqT in H2.
  inversion H2.
Qed.

(* Two distinct elements of the monoid stay distinct in ℤ[M]: the
   insertion does not collapse. *)
Theorem zmring_gens_distinct :
  mr_eq (@mr_gen Int_Ring UT2_Mon ut2_e11) (@mr_gen Int_Ring UT2_Mon ut2_e12)
    → False.
Proof.
  intro H.
  pose proof (proper_morphism (rig_map zmring_to_UT2) _ _ H) as H2.
  unfold ut2_eqT, ut2_e11, ut2_e12 in H2.
  inversion H2.
Qed.
