language: nix

sudo: true

git:
  depth: 1

install:
  - nix-shell --argstr compiler coq_8_6 --run true
  - nix-shell --argstr compiler coq_8_7 --run true
  - nix-shell --argstr compiler coq_8_8 --run true

env:
  global:
    - NIXPKGS_TESTS=yes
    - MATCHING_TESTS=yes
  matrix:
    - COQVERSION=coq_8_6
    - COQVERSION=coq_8_7
    - COQVERSION=coq_8_8

matrix:
  allow_failures:
    - env: COQVERSION=coq_8_8

script:
  - travis_wait 30 nix-build --argstr compiler $COQVERSION

branches:
  only:
    - master
