#!/bin/bash

git clean -dfx

nix-build --cores 4 . --argstr coqPackages coqPackages_8_14 > log_8_14.txt 2>&1 &
nix-build --cores 4 . --argstr coqPackages coqPackages_8_15 > log_8_15.txt 2>&1 &
nix-build --cores 4 . --argstr coqPackages coqPackages_8_16 > log_8_16.txt 2>&1 &

docker run -t coqorg/coq:8.16 bash -c '
    git clone https://github.com/jwiegley/category-theory;
    cd category-theory;
    opam update;
    opam pin add -n -y -k path coq-category-theory .;
    opam install -y -v -j 2 coq-category-theory --deps-only;
    opam install -y -v -j 2 coq-category-theory
'

wait
