Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Natural.Transformation.
Require Import Category.Functor.Bifunctor.
Require Import Category.Construction.Product.
Require Import Category.Functor.Construction.Product.
(* [Instance.Fun] is Required but NOT Imported: its functor-category
   notation "[ C , D ]" (level 90) and ListNotations' "[]" have
   grammatically incompatible bracket prefixes.  The one use site (the
   projection's tensor-comparison isomorphism below) writes the
   qualified [@Category.Instance.Fun.Fun] instead — the same
   discipline as [Universal.v], [Relabel.v] and
   [Presentation/Universal.v]. *)
Require Category.Instance.Fun.
Require Import Category.Structure.Monoidal.
Require Import Category.Structure.Monoidal.Braided.
Require Import Category.Structure.Monoidal.Symmetric.
Require Import Category.Structure.Monoidal.Strict.
Require Import Category.Functor.Structure.Monoidal.
Require Import Category.Functor.Structure.Monoidal.Strict.
Require Import Category.Functor.Structure.Monoidal.Braided.
Require Import Category.Construction.Quotient.
Require Import Category.Construction.ColouredPROP.
Require Import Category.Construction.ColouredPROP.Signature.
Require Import Category.Construction.ColouredPROP.TermEq.
Require Import Category.Construction.ColouredPROP.Free.
Require Import Category.Construction.ColouredPROP.Cast.
Require Import Category.Construction.ColouredPROP.Monoidal.
Require Import Category.Construction.ColouredPROP.Braided.
Require Import Category.Construction.ColouredPROP.Instance.

From Coq Require Import Lists.List.
Import ListNotations.

Generalizable All Variables.

(** * Presentations of coloured PROPs by many-sorted symmetric monoidal
      theories *)

(* nLab: https://ncatlab.org/nlab/show/PROP
   nLab: https://ncatlab.org/nlab/show/symmetric+monoidal+category
   nLab: https://ncatlab.org/nlab/show/generators+and+relations
   Wikipedia: https://en.wikipedia.org/wiki/PROP_(category_theory)
   Wikipedia: https://en.wikipedia.org/wiki/Presentation_of_a_monoid

   A COLOURED SYMMETRIC MONOIDAL THEORY (a [CSMT]) is a coloured
   signature [Σ] together with a family of equations between [Σ]-terms
   of matching boundaries.  The coloured PROP it PRESENTS is the free
   coloured PROP on [Σ], further quotiented by the congruence generated
   by those equations — exactly as a monoid presented by generators and
   relations is the free monoid quotiented by the relation-congruence.
   Classical examples: the theory of per-colour commutative comonoids
   presents the coloured PROP whose morphisms are "copy-and-delete"
   wirings; a typed circuit theory adds gate generators and their
   local rewrite equations.

   This file is the many-sorted mirror of
   [Construction/PROP/Presentation.v] (the one-sorted donor), with
   [list Colour] replacing [nat], [++] replacing [Nat.add], and the
   boundary equations [app_nil_l]/[app_nil_r]/[app_assoc] replacing
   [Nat.add_0_l]/[Nat.add_0_r]/[Nat.add_assoc].  Concretely it builds,
   for a theory [E : CSMT Colour] over [Σ := csmt_sig E]:

     - [CTermEqW E], the [Prop]-valued congruence on [CTerm Σ]
       generated by the free equations [CTermEq Σ] TOGETHER WITH the
       theory axioms [csmt_eqs E] (six constructors: embedding, axiom,
       symmetry, transitivity, and the two composition congruences —
       reflexivity is inherited from [CTE_refl] through the embedding);
     - [CPresentedCat E], the quotient of [CFreeCat Σ] by [CTermEqW E],
       via the fully general quotient kit of [Construction/Quotient.v],
       which is reused WHOLESALE: [HomRel], [HomCongruence],
       [Quotient], [QuotientProj], [Quotient_iso], [QuotientLift] and
       its uniqueness, [Quotient_bifunctor], [Quotient_HomEqProp] and
       [Quotient_ObjDecEq] all apply to [CFreeCat Σ] unchanged, and no
       quotient machinery is re-proved here;
     - the full coloured-PROP tower on the quotient: ONE shared
       [Monoidal] record [CPresented_Monoidal E Cdec], plus the
       Braided, Symmetric and Strict instances that all project it,
       culminating in [CPresentedColouredPROP E Cdec] — the library's
       SECOND inhabitant of [Construction/ColouredPROP.v]'s class,
       after [FreeColouredPROP] — whose [cprop_monoidal_coherence] is
       therefore [eq_refl], definitionally: the same shared-record
       wiring as [Construction/ColouredPROP/Instance.v];
     - the projection functor [CPresentedProj E : CFreeCat Σ ⟶
       CPresentedCat E], which is the identity on objects and on
       morphisms (only the equivalence coarsens), together with its
       strict/braided/symmetric monoidal functor structure — the
       projection-side symmetric-monoidal API of the presentation.
       (Of these, the universal-property file consumes
       [CPresentedProj_Strict], discharging the braid square of its
       precomposed competitor directly from the competitor's own
       square via the strict cast lemmas; the braided/symmetric
       packagings are exported for other clients.)

   Every equational field of the quotient structures is the
   corresponding FREE lemma embedded by [CTEW_termeq]: the underlying
   morphisms of [CPresentedCat E] ARE the terms of [CFreeCat Σ], so
   each free equation is verbatim an equation of the quotient, just
   under a coarser equivalence.  Following the coloured spine's
   discipline, the heavy records are assembled from standalone, named
   lemmas with every field explicit, with one calibrated exception:
   the reflexivity-grade strictness comparisons of [CPresented_Strict]
   and [CPresentedProj_Strict] are discharged as in-situ Program
   obligations, because a separately-declared comparison lemma
   carries its own universe instance of the polymorphic
   [CPresentedCat] and the record-field unifier stops at the instance
   mismatch inside the transported-identity [match] (see the comment
   at [CPresented_Strict]).

   The side conditions required of quotient categories by the
   interpretation files need nothing new here: the generic
   [Quotient_HomEqProp] and [Quotient_ObjDecEq] instances of
   [Construction/Quotient.v] apply to [CPresentedCat E] directly (the
   quotient's [≈] IS [CTermEqW E] after reduction, and objects are
   colour words, with decidability supplied by the explicit
   [CFreeCat_ObjDecEq Σ Cdec] of [Instance.v] under the D2 discipline:
   call sites pass the one canonical colour decider explicitly).

   D2 WARNING (see the foot of [Monoidal.v]): the shared free record
   [CFreeCat_Monoidal Σ Cdec] — and through it every Cdec-dependent
   record below — presumes that ONE canonical [Cdec] is fixed per
   colour type at each instance site.  Mixing deciders surfaces as an
   opaque unification error at exactly the
   [cprop_monoidal_coherence := eq_refl] field of
   [CPresentedColouredPROP].  If that [eq_refl] ever stops
   typechecking, the shared-record wiring broke — fix the wiring; do
   not generalize the field. *)

(** ** Coloured symmetric monoidal theories *)

(** An equation system over a coloured signature: for each pair of
    boundaries, a relation on the [Σ]-terms of that boundary.
    [Prop]-valued, matching the [Prop]-valued congruences that
    [Construction/Quotient.v] quotients by. *)
Definition CEqSystem {Colour : Type} (S : CSignature Colour) : Type :=
  ∀ cs ds : list Colour, CTerm S cs ds → CTerm S cs ds → Prop.

(** A coloured symmetric monoidal theory: generators plus equations. *)
Record CSMT (Colour : Type) : Type := {
  csmt_sig : CSignature Colour;
  csmt_eqs : CEqSystem csmt_sig
}.

Arguments csmt_sig {Colour} _.
Arguments csmt_eqs {Colour} _ cs ds _ _.

Section Presented.

Context {Colour : Type}.
Context (E : CSMT Colour).
Context (Cdec : forall c d : Colour, {c = d} + {c <> d}).

Notation Σ := (csmt_sig E).

(** ** The theory congruence

    [CTermEqW] ("W" for "with axioms") is the smallest congruence on
    [CTerm Σ] containing both the free equations [CTermEq Σ] and the
    theory axioms [csmt_eqs E].  Reflexivity is derivable —
    [CTEW_termeq _ _ (CTE_refl _)] — so it is not a constructor.

    As with [CTermEq] itself, the Section+Context style keeps [E] a
    section variable rather than a uniform inductive parameter; the
    section closes at the foot of this file, before any successor file
    performs induction over the relation. *)

Inductive CTermEqW : forall {cs ds}, CTerm Σ cs ds → CTerm Σ cs ds → Prop :=

  (** Every free equation holds in the presented coloured PROP. *)
  | CTEW_termeq {cs ds} (s t : CTerm Σ cs ds) :
      CTermEq Σ s t → CTermEqW s t

  (** Every axiom of the theory holds in the presented coloured PROP. *)
  | CTEW_ax {cs ds} (s t : CTerm Σ cs ds) :
      csmt_eqs E cs ds s t → CTermEqW s t

  (** Closure under symmetry and transitivity. *)
  | CTEW_sym {cs ds} (s t : CTerm Σ cs ds) :
      CTermEqW s t → CTermEqW t s
  | CTEW_trans {cs ds} (s t u : CTerm Σ cs ds) :
      CTermEqW s t → CTermEqW t u → CTermEqW s u

  (** Closure under the two composition operations. *)
  | CTEW_comp {cs ds es} (f f' : CTerm Σ ds es) (g g' : CTerm Σ cs ds) :
      CTermEqW f f' → CTermEqW g g' →
      CTermEqW (CT_comp f g) (CT_comp f' g')
  | CTEW_tens {cs1 ds1 cs2 ds2}
      (f f' : CTerm Σ cs1 ds1) (g g' : CTerm Σ cs2 ds2) :
      CTermEqW f f' → CTermEqW g g' →
      CTermEqW (CT_tens f g) (CT_tens f' g').

(** Reflexivity of the theory congruence, via the embedding. *)
Definition CTermEqW_refl {cs ds : list Colour} (t : CTerm Σ cs ds) :
  CTermEqW t t :=
  CTEW_termeq t t (CTE_refl t).

(** [CTermEqW] is a hom-congruence on [CFreeCat Σ] in the sense of
    [Construction/Quotient.v]: it contains the hom-setoid equivalence
    ([CTermEq Σ], via [CTEW_termeq]) and is closed under [CT_comp].
    All four fields are explicit constructor applications. *)
#[export] Instance CTermEqW_Congruence :
  @HomCongruence (CFreeCat Σ) (fun cs ds : list Colour => @CTermEqW cs ds) :=
  @Build_HomCongruence (CFreeCat Σ)
    (fun cs ds : list Colour => @CTermEqW cs ds)
    (fun (cs ds : list Colour) (s t : CTerm Σ cs ds) H =>
       CTEW_termeq s t H)
    (fun (cs ds : list Colour) (s t : CTerm Σ cs ds) H =>
       CTEW_sym s t H)
    (fun (cs ds : list Colour) (s t u : CTerm Σ cs ds) H1 H2 =>
       CTEW_trans s t u H1 H2)
    (fun (cs ds es : list Colour)
         (f f' : CTerm Σ ds es) (g g' : CTerm Σ cs ds) Hf Hg =>
       CTEW_comp f f' g g' Hf Hg).

(** ** The presented category

    Same objects (colour words) and same morphisms ([CTerm Σ]) as the
    free category; only the equivalence coarsens from [CTermEq Σ] to
    [CTermEqW].  The generic [Quotient_HomEqProp] and
    [Quotient_ObjDecEq] instances of [Construction/Quotient.v] apply
    to it as-is (the latter fed by [CFreeCat_ObjDecEq Σ Cdec]), so
    nothing further needs defining here. *)

Definition CPresentedCat : Category :=
  @Quotient (CFreeCat Σ) (fun cs ds : list Colour => @CTermEqW cs ds)
    CTermEqW_Congruence.

(** A term, viewed as a morphism of the presented category (the
    carrier of a hom of [CPresentedCat] IS [CTerm Σ]). *)
Definition cquot {cs ds : list Colour} (t : CTerm Σ cs ds) :
  cs ~{CPresentedCat}~> ds := t.

(** The projection functor: identity on objects and morphisms. *)
Definition CPresentedProj : CFreeCat Σ ⟶ CPresentedCat :=
  @QuotientProj (CFreeCat Σ) (fun cs ds : list Colour => @CTermEqW cs ds)
    CTermEqW_Congruence.

(** ** Term-level bookkeeping lemmas

    Small [CTermEq]-level facts used to discharge the comparison
    squares of the projection functor, where every comparison map is
    an identity or a tensor of identities. *)

(** An identity slides from one side of a morphism to the other. *)
Lemma cterm_id_swap {cs ds : list Colour} (t : CTerm Σ cs ds) :
  CTermEq Σ (CT_comp t (CT_id cs)) (CT_comp (CT_id ds) t).
Proof.
  apply CTE_trans with t.
  - apply CTE_id_right.
  - apply CTE_sym, CTE_id_left.
Qed.

(** A composite of identities equals a tensor of identities. *)
Lemma cterm_comp_id_tens (cs ds : list Colour) :
  CTermEq Σ (CT_comp (CT_id (cs ++ ds)) (CT_id (cs ++ ds)))
            (CT_tens (CT_id cs) (CT_id ds)).
Proof.
  apply CTE_trans with (CT_id (cs ++ ds)).
  - apply CTE_id_left.
  - apply CTE_sym, CTE_tens_id.
Qed.

(** Collapsing an identity and a tensor of identities after [t]. *)
Lemma cterm_collapse_r {m n p : list Colour} (t : CTerm Σ (m ++ n) p) :
  CTermEq Σ
    (CT_comp (CT_comp t (CT_id (m ++ n))) (CT_tens (CT_id m) (CT_id n)))
    t.
Proof.
  apply CTE_trans with (CT_comp t (CT_tens (CT_id m) (CT_id n))).
  - apply CTE_comp_cong.
    + apply CTE_id_right.
    + apply CTE_refl.
  - apply CTE_trans with (CT_comp t (CT_id (m ++ n))).
    + apply CTE_comp_cong.
      * apply CTE_refl.
      * apply CTE_tens_id.
    + apply CTE_id_right.
Qed.

(** Collapsing an identity and a tensor of identities before [t]. *)
Lemma cterm_collapse_l {m n p : list Colour} (t : CTerm Σ p (m ++ n)) :
  CTermEq Σ
    (CT_comp (CT_comp (CT_id (m ++ n)) (CT_tens (CT_id m) (CT_id n))) t)
    t.
Proof.
  apply CTE_trans with (CT_comp (CT_tens (CT_id m) (CT_id n)) t).
  - apply CTE_comp_cong.
    + apply CTE_id_left.
    + apply CTE_refl.
  - apply CTE_trans with (CT_comp (CT_id (m ++ n)) t).
    + apply CTE_comp_cong.
      * apply CTE_tens_id.
      * apply CTE_refl.
    + apply CTE_id_left.
Qed.

(** ** The tensor on the presented category

    The parallel-composition bifunctor descends to the quotient
    because [CTermEqW] is closed under [CT_tens]. *)

Definition CPresented_Tensor : CPresentedCat ∏ CPresentedCat ⟶ CPresentedCat :=
  @Quotient_bifunctor (CFreeCat Σ) (fun cs ds : list Colour => @CTermEqW cs ds)
    CTermEqW_Congruence (CFreeCat_Tensor Σ)
    (fun x y f g Hf Hg => CTEW_tens (fst f) (fst g) (snd f) (snd g) Hf Hg).

(** ** THE shared Monoidal record on [CPresentedCat]

    Unit [[]], tensor [CPresented_Tensor], structural isomorphisms the
    [CT_cast] isos of [Cast.v] pushed through [Quotient_iso].  Every
    proof field is the corresponding FREE lemma — the very same lemmas
    that assemble [CFreeCat_Monoidal Σ Cdec] in [Monoidal.v] —
    embedded by [CTEW_termeq]: the two sides of each square are
    syntactically the same terms, only compared under the coarser
    equivalence.

    Braided, Symmetric, Strict, and the bundled coloured PROP below
    all name this ONE record, so their agreement is definitional. *)

Program Definition CPresented_Monoidal : @Monoidal CPresentedCat := {|
  I            := (nil : list Colour);
  tensor       := CPresented_Tensor;
  unit_left    := fun x => Quotient_iso (CFreeCat_unit_left Σ x);
  unit_right   := fun x => Quotient_iso (CFreeCat_unit_right Σ x);
  tensor_assoc := fun x y z => Quotient_iso (CFreeCat_tensor_assoc Σ x y z);
  to_unit_left_natural := fun x y g =>
    CTEW_termeq _ _ (cleft_unit_natural Σ Cdec g);
  from_unit_left_natural := fun x y g =>
    CTEW_termeq _ _ (cleft_unit_natural_from Σ Cdec g);
  to_unit_right_natural := fun x y g =>
    CTEW_termeq _ _ (cright_unit_natural Σ g);
  from_unit_right_natural := fun x y g =>
    CTEW_termeq _ _ (cfrom_right_unit_natural Σ g);
  to_tensor_assoc_natural := fun _ _ _ _ _ _ g h i =>
    CTEW_termeq _ _ (cassoc_natural Σ g h i);
  from_tensor_assoc_natural := fun _ _ _ _ _ _ g h i =>
    CTEW_termeq _ _ (cfrom_assoc_natural Σ g h i);
  triangle_identity := fun x y =>
    CTEW_termeq _ _ (cfree_triangle Σ Cdec x y);
  pentagon_identity := fun x y z w =>
    CTEW_termeq _ _ (cfree_pentagon Σ Cdec x y z w)
|}.

(** ** The braided and symmetric structure

    The block braiding [CT_braid] descends unchanged; its naturality
    square, the two hexagons, and the involution are the free lemmas
    of [Construction/ColouredPROP/Braided.v], embedded.  The records
    are explicit [Build_BraidedMonoidal] / [Build_SymmetricMonoidal]
    applications, following the coloured spine's discipline. *)

Definition CPresented_Braided : @BraidedMonoidal CPresentedCat :=
  @Build_BraidedMonoidal CPresentedCat
    CPresented_Monoidal  (* THE shared record *)
    (fun cs ds : list Colour => CT_braid cs ds)
    (fun x y g z w h => CTEW_termeq _ _ (cfree_braid_square Σ g h))
    (fun x y z => CTEW_termeq _ _ (cfree_hexagon Σ x y z))
    (fun x y z => CTEW_termeq _ _ (cfree_hexagon_sym Σ x y z)).

Definition CPresented_Symmetric : @SymmetricMonoidal CPresentedCat :=
  @Build_SymmetricMonoidal CPresentedCat
    CPresented_Braided
    (fun x y => CTEW_termeq _ _ (cfree_braid_invol Σ x y)).

(** ** The strict structure

    Objects are colour words and the tensor on objects is
    concatenation, so the object-level strictness equalities are the
    boundary equations of [list]; the comparison fields are
    reflexivity-grade because [Cast.v] BUILT the structural
    isomorphisms as [CT_cast] maps, which are definitionally the
    transported identities the class asks for (same proof term on
    both sides).  Note the stdlib orientation of [app_assoc]
    (right-to-left reassociation), so the associator's [to] is the
    [eq_sym] cast — the orientation fixed once in [Cast.v] and
    repeated verbatim in [strict_assoc_obj] below. *)

(*  The three comparison fields are reflexivity-grade, as in the free
    donor [Construction/ColouredPROP/Instance.v], but here they are
    discharged as Program obligations rather than by applying
    standalone lemmas: a separately-declared lemma carries its own
    universe instance of the polymorphic [CPresentedCat], and the
    record-field unifier stops at the instance mismatch inside the
    transported-identity [match] before it would reduce both sides.
    Proving the field in situ keeps the whole comparison at the
    record's single instance. *)
Program Definition CPresented_Strict : @StrictMonoidal CPresentedCat := {|
  strict_is_monoidal    := CPresented_Monoidal;  (* THE shared record *)
  strict_assoc_obj      := fun x y z => eq_sym (app_assoc x y z);
  strict_unit_left_obj  := fun x => app_nil_l x;
  strict_unit_right_obj := fun x => app_nil_r x
|}.
Next Obligation. exact (CTermEqW_refl _). Qed.
Next Obligation. exact (CTermEqW_refl _). Qed.
Next Obligation. exact (CTermEqW_refl _). Qed.

(** ** The presented coloured PROP, bundled

    The library's SECOND [ColouredPROP] instance, after
    [FreeColouredPROP].  As there, every equality field is [eq_refl]
    because the whole tower shares the ONE [Monoidal] record
    [CPresented_Monoidal]: the quotient has the same objects as
    [CFreeCat Σ] and [CPresented_Tensor] has the same object action as
    [CFreeCat_Tensor Σ], so the object correspondence, the unit, and
    tensor-as-concatenation all hold on the nose.  The record is an
    explicit [Build_ColouredPROP] application, so no inference is left
    to a record literal.  If [cprop_monoidal_coherence := eq_refl]
    ever stops typechecking, the shared-record wiring broke — fix the
    wiring; do not generalize the field. *)

Definition CPresentedColouredPROP : ColouredPROP Colour :=
  Build_ColouredPROP Colour
    CPresentedCat
    CPresented_Strict
    CPresented_Symmetric

    (* [strict_is_monoidal CPresented_Strict] and
       [braided_is_monoidal (symmetric_is_braided CPresented_Symmetric)]
       both reduce to the literal term [CPresented_Monoidal]. *)
    eq_refl

    (* Objects of [CPresentedCat] are literally the colour words. *)
    (fun cs : list Colour => cs)

    (* [I] of [CPresented_Monoidal] is the literal [[]]. *)
    eq_refl

    (* [fobj CPresented_Tensor (cs, ds)] reduces to [cs ++ ds]. *)
    (fun cs ds : list Colour => eq_refl).

(** ** The projection is a strict symmetric monoidal functor

    [CPresentedProj] is the identity on objects and morphisms, so both
    comparison maps are identities and every coherence square is an
    identity-bookkeeping equation, discharged by the term-level
    lemmas above through [CTEW_termeq]. *)

(** The tensor-then-project and project-then-tensor composites that
    the tensor comparison relates. *)
Definition CPresented_ap_dom : CFreeCat Σ ∏ CFreeCat Σ ⟶ CPresentedCat :=
  CPresented_Tensor ◯ (CPresentedProj ∏⟶ CPresentedProj).

Definition CPresented_ap_cod : CFreeCat Σ ∏ CFreeCat Σ ⟶ CPresentedCat :=
  CPresentedProj ◯ CFreeCat_Tensor Σ.

(** Both directions of the tensor comparison are families of
    identities; naturality is [cterm_id_swap]. *)
Definition CPresented_ap_to : CPresented_ap_dom ⟹ CPresented_ap_cod :=
  @Build_Transform' (CFreeCat Σ ∏ CFreeCat Σ) CPresentedCat
    CPresented_ap_dom CPresented_ap_cod
    (fun p => CT_id ((fst p ++ snd p)%list))
    (fun p q f => CTEW_termeq _ _ (cterm_id_swap (CT_tens (fst f) (snd f)))).

Definition CPresented_ap_from : CPresented_ap_cod ⟹ CPresented_ap_dom :=
  @Build_Transform' (CFreeCat Σ ∏ CFreeCat Σ) CPresentedCat
    CPresented_ap_cod CPresented_ap_dom
    (fun p => CT_id ((fst p ++ snd p)%list))
    (fun p q f => CTEW_termeq _ _ (cterm_id_swap (CT_tens (fst f) (snd f)))).

(** The identity components are inverse up to [CTermEqW] (the identity
    natural transformation of a composite-with-tensor functor has
    components [CT_tens (CT_id _) (CT_id _)]).  Explicit
    [Build_Isomorphism] application, pinning the functor category. *)
Definition CPresented_ap_iso :
  @Isomorphism
    (@Category.Instance.Fun.Fun (CFreeCat Σ ∏ CFreeCat Σ) CPresentedCat)
    CPresented_ap_dom CPresented_ap_cod :=
  @Build_Isomorphism
    (@Category.Instance.Fun.Fun (CFreeCat Σ ∏ CFreeCat Σ) CPresentedCat)
    CPresented_ap_dom CPresented_ap_cod
    CPresented_ap_to CPresented_ap_from
    (fun p => CTEW_termeq _ _ (cterm_comp_id_tens (fst p) (snd p)))
    (fun p => CTEW_termeq _ _ (cterm_comp_id_tens (fst p) (snd p))).

Program Definition CPresentedProj_Monoidal :
  @MonoidalFunctor (CFreeCat Σ) CPresentedCat
    (CFreeCat_Monoidal Σ Cdec) CPresented_Monoidal CPresentedProj := {|
  pure_iso := iso_id;
  ap_functor_iso := CPresented_ap_iso;
  pure_iso_left  := fun x => iso_id;
  pure_iso_right := fun x => iso_id;
  ap_iso_assoc := fun x y z =>
    @tensor_assoc CPresentedCat CPresented_Monoidal x y z;
  monoidal_unit_left := fun x =>
    CTEW_termeq _ _
      (CTE_sym _ _ (cterm_collapse_r (CT_cast (app_nil_l x))));
  monoidal_unit_right := fun x =>
    CTEW_termeq _ _
      (CTE_sym _ _ (cterm_collapse_r (CT_cast (app_nil_r x))));
  monoidal_assoc := fun x y z =>
    CTEW_termeq _ _
      (CTE_trans _ _ _
         (cterm_collapse_r (CT_cast (eq_sym (app_assoc x y z))))
         (CTE_sym _ _
            (cterm_collapse_l (CT_cast (eq_sym (app_assoc x y z))))))
|}.

(** Both comparison maps of the projection are identities on the
    nose, so the projection is STRICT monoidal, with [eq_refl] object
    equalities. *)

Lemma CPresentedProj_pure_id :
  to (@pure_iso _ _ _ _ CPresentedProj CPresentedProj_Monoidal)
  ≈[CPresentedCat] @id CPresentedCat (nil : list Colour).
Proof. exact (CTermEqW_refl _). Qed.

Lemma CPresentedProj_ap_id (x y : list Colour) :
  to (@ap_iso _ _ _ _ CPresentedProj CPresentedProj_Monoidal x y)
  ≈[CPresentedCat] @id CPresentedCat ((x ++ y)%list).
Proof. exact (CTermEqW_refl _). Qed.

(*  As with [CPresented_Strict], the two comparison fields are
    discharged in situ (both comparison maps are identities on the
    nose), keeping the whole record at a single universe instance of
    [CPresentedCat]. *)
Program Definition CPresentedProj_Strict :
  @StrictMonoidalFunctor (CFreeCat Σ) CPresentedCat
    (CFreeCat_Monoidal Σ Cdec) CPresented_Monoidal CPresentedProj := {|
  strict_functor_is_monoidal := CPresentedProj_Monoidal;
  strict_pure_obj := eq_refl;
  strict_ap_obj := fun x y => eq_refl
|}.
Next Obligation. exact (CTermEqW_refl _). Qed.
Next Obligation. exact (CTermEqW_refl _). Qed.

(** The braid-compatibility square of the projection: the free braid
    maps to the presented braid, conjugated by the (identity) tensor
    comparisons.  This is the [SymmetricMonoidalFunctor] square in
    the strict setting, provided as projection-side API; the
    universal-property file does not consume it — when transferring
    uniqueness across the projection it discharges the composite's
    braid square directly from the competitor's own square,
    rewriting all four tensor comparisons to casts with
    [strict_ap_iso_id]. *)
Lemma CPresentedProj_braid (cs ds : list Colour) :
  fmap[CPresentedProj] (@braid (CFreeCat Σ) (CFreeCat_Braided Σ Cdec) cs ds)
    ∘ to (@ap_iso _ _ _ _ CPresentedProj CPresentedProj_Monoidal cs ds)
  ≈[CPresentedCat]
  to (@ap_iso _ _ _ _ CPresentedProj CPresentedProj_Monoidal ds cs)
    ∘ @braid CPresentedCat CPresented_Braided cs ds.
Proof.
  exact (CTEW_termeq _ _ (cterm_id_swap (CT_braid cs ds))).
Qed.

(** The braided packaging of the projection, as an explicit
    [Build_BraidedMonoidalFunctor] application; the compatibility
    square is the same identity-sliding fact as
    [CPresentedProj_braid]. *)
Definition CPresentedProj_Braided :
  @BraidedMonoidalFunctor (CFreeCat Σ) CPresentedCat
    (CFreeCat_Braided Σ Cdec) CPresented_Braided CPresentedProj :=
  @Build_BraidedMonoidalFunctor (CFreeCat Σ) CPresentedCat
    (CFreeCat_Braided Σ Cdec) CPresented_Braided CPresentedProj
    CPresentedProj_Monoidal
    (fun x y => CTEW_termeq _ _ (cterm_id_swap (CT_braid x y))).

(** A braided monoidal functor between symmetric monoidal categories
    IS a symmetric monoidal functor ([SymmetricMonoidalFunctor] is a
    definition, not a class); supplied explicitly, as the alias does
    not participate in instance resolution. *)
Definition CPresentedProj_Symmetric :
  @SymmetricMonoidalFunctor (CFreeCat Σ) CPresentedCat
    (CFreeCat_Symmetric Σ Cdec) CPresented_Symmetric CPresentedProj :=
  CPresentedProj_Braided.

(** ** Machine-checked sanity

    Each [Example] holds by [eq_refl] (or a single constructor),
    witnessing that the corresponding field or action is definitional;
    any regression in the shared-record wiring is caught here rather
    than at a distant use site. *)

(** The coherence between the strict and symmetric [Monoidal] paths
    is the reflexivity proof itself. *)
Example CPresentedColouredPROP_coherence_is_refl :
  @cprop_monoidal_coherence Colour CPresentedColouredPROP = eq_refl := eq_refl.

(** The object correspondence is the identity on colour words. *)
Example CPresentedColouredPROP_of_list_id (cs : list Colour) :
  cprop_of_list (ColouredPROP := CPresentedColouredPROP) cs = cs := eq_refl.

(** Tensor-on-objects is literally concatenation, with [eq_refl]
    proof. *)
Example CPresentedColouredPROP_tensor_app_is_refl (cs ds : list Colour) :
  cprop_tensor_app (ColouredPROP := CPresentedColouredPROP) cs ds = eq_refl
  := eq_refl.

(** The singleton wire object for colour [c] is the literal
    one-element word [c :: nil]. *)
Example CPresentedColouredPROP_wire (c : Colour) :
  wire (P := CPresentedColouredPROP) c = (c :: nil) := eq_refl.

(** The projection functor acts as the identity on terms. *)
Example CPresentedProj_fmap_id_on_terms {cs ds : list Colour}
  (t : CTerm Σ cs ds) :
  fmap[CPresentedProj] t = cquot t := eq_refl.

(** Every axiom of the theory holds in the presented category. *)
Example CPresented_axioms_hold {cs ds : list Colour}
  (s t : CTerm Σ cs ds) (H : csmt_eqs E cs ds s t) :
  cquot s ≈[CPresentedCat] cquot t := CTEW_ax s t H.

End Presented.

Arguments CTermEqW {Colour} E {cs ds} _ _.
Arguments CPresentedCat {Colour} E : assert.
Arguments cquot {Colour} E {cs ds} t : assert.
Arguments CPresentedProj {Colour} E : assert.
Arguments CPresented_Tensor {Colour} E : assert.
Arguments CPresented_Monoidal {Colour} E Cdec : assert.
Arguments CPresented_Braided {Colour} E Cdec : assert.
Arguments CPresented_Symmetric {Colour} E Cdec : assert.
Arguments CPresented_Strict {Colour} E Cdec : assert.
Arguments CPresentedColouredPROP {Colour} E Cdec : assert.
Arguments CPresentedProj_Monoidal {Colour} E Cdec : assert.
Arguments CPresentedProj_Strict {Colour} E Cdec : assert.
Arguments CPresentedProj_braid {Colour} E Cdec cs ds : assert.
Arguments CPresentedProj_Braided {Colour} E Cdec : assert.
Arguments CPresentedProj_Symmetric {Colour} E Cdec : assert.
