Require Import Category.Lib.
Require Import Category.Lib.TList.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Structure.Thin.
Require Import Category.Structure.Groupoid.
Require Import Category.Construction.Quotient.
Require Import Category.Construction.Free.Quiver.
Require Import Category.Construction.Free.Quiver.Presented.

Require Import Coq.Vectors.Fin.
Require Import Coq.Lists.List.
Require Import Coq.micromega.Lia.

Generalizable All Variables.

(** [edgeset] is section-local in [Construction/Free/Quiver.v] and does
    not escape it; [Construction/Free/Quiver/Presented.v] and
    [Instance/Square.v] each re-declare it locally for the same reason,
    and neither declaration escapes its file.  Without it the first
    statement about edge equivalence reports a missing [Setoid]
    instance, which reads like a universe problem and is not one. *)
#[local] Existing Instance edgeset.

(** * The walking isomorphism, by generators and relations

    nLab: https://ncatlab.org/nlab/show/walking+isomorphism
    nLab: https://ncatlab.org/nlab/show/free+category
    Book: Awodey, Category Theory, 1st ed., §4.4 Example 4.9, printed
          p. 90 (the category generated by two objects A and B and two
          arrows f : A → B, g : B → A subject to g ∘ f = 1_A and
          f ∘ g = 1_B)

    Awodey's example is the smallest presentation whose relations do
    something a finite enumeration cannot see.  Two nodes, two edges,
    two equations — and the free category on that quiver is INFINITE:
    the paths A → A are the alternating words (gf)^n of every even
    length, and they are pairwise distinct.  The two relations collapse
    that infinity to a single arrow in each of the four hom-sets, so
    the presented category has exactly four arrows, two of them
    identities, and the surviving pair is an isomorphism.

    That is the whole point of the example, and it is what separates it
    from [Instance/Square.v]'s walking commutative square: there the
    free category is already finite (ten arrows) and one relation merges
    one pair, so a classification of paths can be a finite enumeration
    of Leibniz equalities.  Here it cannot be, and the classification
    below is by ENDPOINTS AND LENGTH instead — every path is [wi_AA n],
    [wi_AB n], [wi_BA n] or [wi_BB n] for a unique [n], according to its
    two endpoints.

    WHAT IS DELIVERED.  (1) the presentation [WalkingIsoPresentation]
    and the category [WalkingIso] ([FinitelyPresented] of it), with the
    quiver, the finiteness data and the two equations all carried as
    data in the shape [Construction/Free/Quiver/Presented.v] fixes;
    (2) [wi_classify], a classification of every PATH of the underlying
    free category by its endpoints and its length, at LEIBNIZ strength —
    each path IS one of the four canonical families on the nose, not
    merely [≈] to it; (3) the two relations, [wiso_gf] and [wiso_fg],
    and from them [walking_iso], an inhabitant of [Theory/Isomorphism.v]'s
    [Isomorphism] whose two inverse laws ARE those two relations;
    (4) [WalkingIso_Thin] — every hom-set is a singleton — together with
    [wiso_hom_singleton], which pairs thinness with an inhabitant of each
    of the four hom-sets, and [WalkingIso_IsGroupoid], so [WalkingIso] is
    the chaotic groupoid on two points; (5) the counts, proved and not
    asserted: two objects, four arrows, two of them identities, two
    generators; (6) that the presenting projection is not
    faithful, measured — the free hom-set A → A carries the pairwise
    distinct family [wi_AA n] ([free_wi_AA_inj]) while all of them
    collapse in [WalkingIso] ([wi_AA_collapse]), whence
    [WalkingIsoProj_not_faithful], so [WalkingIso] is not free on its own
    quiver; and [free_iso_lengths], the general fact that a free category
    has no non-identity isomorphism, which is where an argument for "free
    on NO quiver" would start and which this file does not finish;
    (7) the universal property: a functor out of [WalkingIso] is exactly
    an isomorphism in the target, with both round trips and uniqueness at
    strict strength.

    WHAT IS CONSUMED RATHER THAN REBUILT.  All of the presentation
    machinery: [FiniteQuiver], [FiniteEquations], [fe_rel],
    [FinitePresentation], [FinitelyPresented], [pgen],
    [PresentedQuiverProj], [PresentedFunctor], [PresentedFunctor_gen] and
    [PresentedFunctor_unique] are
    [Construction/Free/Quiver/Presented.v]'s, and no analogue of any of
    them is declared here.  [FreeOnQuiver],
    [Build_Quiver_Standard_Eq], [InducedFunctor], [QuiverOfCat] and the
    whole [tlist] path algebra ([tlist_app_cons],
    [tlist'_equiv_lengths]) are [Construction/Free/Quiver.v]'s and
    [Lib/TList.v]'s.  The congruence is
    [Construction/Quotient.v]'s [CongClosure]: [≈] in a presented
    category IS a term of that inductive family, which is why
    [wiso_gf] and [wiso_fg] are one [cc_gen] each, and why
    [strict_of_hom_cast] converts the uniqueness clause.  [Thin] is
    [Structure/Thin.v]'s and [IsGroupoid] is [Structure/Groupoid.v]'s;
    requiring the latter costs exactly one module over the closure
    without it (34 against 35, measured with [coqdep -sort] on this
    file's own [Require] list), because
    [Instance/Sets] and [Construction/Deloop] are already reached
    through [Presented.v].

    DESIGN DECISIONS.

    THE CLASSIFICATION IS AT LEIBNIZ STRENGTH, and that is a genuine
    strengthening rather than a stylistic one.  The edges of
    [WIsoQuiver] carry the standard [eq] setoid
    ([Build_Quiver_Standard_Eq]), so [wi_classify] can and does conclude
    a Leibniz equality of paths rather than a [tlist] equivalence.  It
    is what makes [free_wi_AA_inj] a statement about ARROWS of the free
    category rather than about representatives: length is an invariant
    of the hom-setoid ([wi_equiv_length]), so the classification's [=]
    upgrades to a statement about [≈]-classes.  Every claim about an
    arrow of [WalkingIso] is at [≈]; the Leibniz equations elsewhere in
    the file are about term structure — that a composite of one-step
    paths IS a two-step path, that the projection IS the identity on
    morphisms — and each is marked where it occurs.

    THE ISOMORPHISM IS BUILT DIRECTLY FROM THE TWO RELATIONS, not
    through [Structure/Thin.v]'s [thin_iso].  Both routes exist, but the
    direct one is the honest reading of Awodey's example: the two
    inverse laws of [walking_iso] are literally [wiso_fg] and
    [wiso_gf], which are literally the two imposed equations, so the
    isomorphism is the presentation and not a consequence of a later
    theorem.  [thin_iso WalkingIso_Thin iso_f iso_g] would inhabit the
    same type by a different route; that alternative is not built here,
    and no claim is made that the two agree.

    THE FOUR CANONICAL FAMILIES ARE TWO FIXPOINTS AND TWO ABBREVIATIONS.
    [wi_AA] and [wi_BB] recurse two edges at a time, so neither needs
    mutual recursion; [wi_AB] and [wi_BA] are one edge on top of the
    other family's [n]-th term.  That is what lets [wi_classify] be a
    single induction on the path with the target destructed in both
    branches — [Instance/Square.v]'s [wsq_classify] idiom, which is
    forced here for the same reason it is forced there.  Measured: on a
    path whose endpoints are given as CONSTRUCTORS, a direct
    [induction p] is refused with "Abstracting over the terms \"WI_A\"
    and \"p\" leads to a term ... which is ill-typed", since the
    eliminator would have to generalize the endpoint the statement
    names.  Routing the induction through [wi_spec], which matches on
    the target and takes the source as an argument, is what makes the
    abstraction well typed.

    TWO TRAPS THIS FILE MET, both recorded because the error message
    names neither cause.

    THE FIRST IS THAT THE TWO CATEGORIES SHARE THEIR HOM TYPES.
    [WalkingIso] and [FreeWIso] have the same hom TYPES (equations merge
    and never add — [WalkingIso_hom_is_free]) and the same [compose]
    ([WalkingIso_compose_is_free]), so a morphism term does not say
    which category it is being read in, while the [≈] of a goal does.
    In the successor case of [wi_AA_collapse] the goal displays as
    [wi_AA n ∘ wi_g ∘ wi_f ≈ id{WalkingIso}] — visibly an instance of
    [comp_assoc]'s right-hand side — and yet a bare
    [rewrite <- comp_assoc] is refused, the setoid relation to rewrite
    under being left as an unresolved evar; the same rewrite with the
    category given explicitly as [FreeWIso] is refused identically, with
    the same message, which is what shows the obstruction to be the
    RELATION and not the term.  Naming
    [WalkingIso] resolves it, so every appeal to associativity below
    names its category.

    THE SECOND IS THAT [simpl] UNFOLDS PAST THE PATTERN.  In
    [wi_AA_step] the generators are [tlist_singleton] applications, and
    after [simpl] a [rewrite <- wi_cons_g] reports "Found no subterm
    matching \"?M ∘ wi_g\"" — the composite it wants has been unfolded
    to its [tlist] normal form.  Both step lemmas are therefore supplied
    as TERMS, built from [eq_trans] and [f_equal] over [tlist_app_cons],
    with no tactic at all.

    WHAT IS NOT DELIVERED.  No decision procedure on the hom-sets: the
    classification is a proof by induction, and no [ObjDecEq] or
    hom-decidability instance is registered.  Nothing is registered as
    an [Instance] at all.  No comparison with any other in-tree shape:
    neither [Instance/Indiscrete.v]'s [Indiscrete bool] nor
    [Instance/Two.v]'s [_2] is related to [WalkingIso] here, no
    comparison functor is built, and nothing is claimed about whether
    any of them are isomorphic or equivalent.
    [WalkingIsoProj_not_faithful] says that THIS presentation's
    projection from THIS free category is not faithful; it does NOT say
    that [WalkingIso] is not the free category on some other quiver, and
    no such statement is proved or attempted.  The free category's
    infinitude is delivered as the injectivity of one family
    ([free_wi_AA_inj]) rather than as a cardinality statement, the tree
    carrying no vocabulary for the latter.  No vertex group is computed,
    no [Deloop] comparison is made, and nothing is said about
    [WalkingIso]'s skeleton. *)

(** ** The quiver

    Two nodes and two edges, one in each direction.  Awodey draws them
    as f : A → B and g : B → A. *)

Inductive WIsoNode : Set := WI_A | WI_B.

Inductive WIsoEdge : WIsoNode -> WIsoNode -> Set :=
  | WI_f : WIsoEdge WI_A WI_B
  | WI_g : WIsoEdge WI_B WI_A.

Definition WIsoQuiver : Quiver :=
  Build_Quiver_Standard_Eq WIsoNode WIsoEdge.

(** The free category on it: paths are alternating words in f and g. *)
Definition FreeWIso : Category := FreeOnQuiver WIsoQuiver.

(** The two generating edges, as one-step paths. *)
Definition wi_f : WI_A ~{FreeWIso}~> WI_B :=
  tlist_singleton (B:=@edges WIsoQuiver) WI_f.
Definition wi_g : WI_B ~{FreeWIso}~> WI_A :=
  tlist_singleton (B:=@edges WIsoQuiver) WI_g.

(** ** The four canonical path families

    A path alternates, so it is determined by its two endpoints and its
    length.  [wi_AA n] and [wi_BB n] are the loops of length 2n; the two
    families of odd-length paths are one edge on top of them.  Only
    these two recurse, and each consumes two edges at a step, so no
    mutual recursion is needed. *)

Fixpoint wi_AA (n : nat) : WI_A ~{FreeWIso}~> WI_A :=
  match n with
  | O => tnil
  | S m => tcons (B:=@edges WIsoQuiver) _ WI_f
             (tcons (B:=@edges WIsoQuiver) _ WI_g (wi_AA m))
  end.

Fixpoint wi_BB (n : nat) : WI_B ~{FreeWIso}~> WI_B :=
  match n with
  | O => tnil
  | S m => tcons (B:=@edges WIsoQuiver) _ WI_g
             (tcons (B:=@edges WIsoQuiver) _ WI_f (wi_BB m))
  end.

Definition wi_AB (n : nat) : WI_A ~{FreeWIso}~> WI_B :=
  tcons (B:=@edges WIsoQuiver) _ WI_f (wi_BB n).
Definition wi_BA (n : nat) : WI_B ~{FreeWIso}~> WI_A :=
  tcons (B:=@edges WIsoQuiver) _ WI_g (wi_AA n).

(** The empty path is the length-zero loop, and each generator is the
    length-one path of its own family. *)
Example wi_AA_0 : wi_AA 0 = @id FreeWIso WI_A := eq_refl.
Example wi_BB_0 : wi_BB 0 = @id FreeWIso WI_B := eq_refl.
Example wi_AB_0 : wi_AB 0 = wi_f := eq_refl.
Example wi_BA_0 : wi_BA 0 = wi_g := eq_refl.

(** ** Classifying every path by its endpoints and its length

    The specification: for each ordered pair of nodes, exactly which
    paths join them.  Unlike [Instance/Square.v]'s [wsq_spec] this is
    not a finite enumeration — the hom-sets of [FreeWIso] are infinite —
    but each is still pinned down completely, by a natural number.  The
    equalities are Leibniz, not [≈]; see the header. *)
Definition wi_spec (y : WIsoNode) :
  forall x : WIsoNode, (x ~{FreeWIso}~> y) -> Type :=
  match y as y0 return forall x : WIsoNode, (x ~{FreeWIso}~> y0) -> Type
  with
  | WI_A => fun x => match x as x0
                      return (x0 ~{FreeWIso}~> WI_A) -> Type with
      | WI_A => fun p => { n : nat & p = wi_AA n }
      | WI_B => fun p => { n : nat & p = wi_BA n }
      end
  | WI_B => fun x => match x as x0
                      return (x0 ~{FreeWIso}~> WI_B) -> Type with
      | WI_A => fun p => { n : nat & p = wi_AB n }
      | WI_B => fun p => { n : nat & p = wi_BB n }
      end
  end.

(** Every path meets its specification.  One induction on the path: the
    empty path forces source and target to agree and is the zeroth term
    of the appropriate family, and a step is one of the two edges, which
    pins the source and hands the rest to the induction hypothesis.  The
    two loop branches are the only ones that increment the index. *)
Theorem wi_classify (y x : WIsoNode) (p : x ~{FreeWIso}~> y) :
  wi_spec y x p.
Proof.
  induction p as [ | i j e p IH ].
  - destruct y; exists 0%nat; reflexivity.
  - destruct e; destruct y; simpl in *;
      destruct IH as [n Hn]; subst.
    + exists (S n); reflexivity.
    + exists n; reflexivity.
    + exists n; reflexivity.
    + exists (S n); reflexivity.
Qed.

(** ** The presentation

    Two nodes, two edges, TWO relations — one at each loop.  Finiteness
    is carried as data throughout, in the shape
    [Construction/Free/Quiver/Presented.v] fixes: [Fin.t] indices with
    retractions, no existence claim over lists, hence no choice
    principle anywhere. *)

Definition WIsoEqn_count (x y : WIsoQuiver) : nat :=
  match x, y with
  | WI_A, WI_A => 1 | WI_B, WI_B => 1 | _, _ => 0
  end.

Definition WIsoEqn_lhs (x y : WIsoQuiver) :
  Fin.t (WIsoEqn_count x y) -> x ~{FreeWIso}~> y.
Proof.
  destruct x, y; simpl; intro i;
    solve [ exact (Fin.case0 _ i) | exact (wi_AA 1) | exact (wi_BB 1) ].
Defined.

Definition WIsoEqn_rhs (x y : WIsoQuiver) :
  Fin.t (WIsoEqn_count x y) -> x ~{FreeWIso}~> y.
Proof.
  destruct x, y; simpl; intro i;
    solve [ exact (Fin.case0 _ i) | exact (wi_AA 0) | exact (wi_BB 0) ].
Defined.

Definition WIsoEqns : FiniteEquations WIsoQuiver := {|
  fe_count := WIsoEqn_count;
  fe_lhs   := WIsoEqn_lhs;
  fe_rhs   := WIsoEqn_rhs
|}.

Definition WIso_node (i : Fin.t 2) : WIsoNode :=
  match i with Fin.F1 => WI_A | Fin.FS _ => WI_B end.

Definition WIso_index (x : WIsoNode) : Fin.t 2 :=
  match x with WI_A => Fin.F1 | WI_B => Fin.FS Fin.F1 end.

Lemma WIso_node_rt (x : WIsoNode) : WIso_node (WIso_index x) = x.
Proof. destruct x; reflexivity. Qed.

Definition WIso_ecount (x y : WIsoNode) : nat :=
  match x, y with
  | WI_A, WI_B => 1 | WI_B, WI_A => 1 | _, _ => 0
  end.

Definition WIso_edge (x y : WIsoNode) :
  Fin.t (WIso_ecount x y) -> WIsoEdge x y.
Proof.
  destruct x, y; simpl; intro i;
    solve [ exact (Fin.case0 _ i) | exact WI_f | exact WI_g ].
Defined.

Definition WIso_eindex (x y : WIsoNode) (e : WIsoEdge x y) :
  Fin.t (WIso_ecount x y) :=
  match e in WIsoEdge a b return Fin.t (WIso_ecount a b) with
  | WI_f => Fin.F1
  | WI_g => Fin.F1
  end.

Lemma WIso_edge_rt (x y : WIsoNode) (e : WIsoEdge x y) :
  WIso_edge x y (WIso_eindex x y e) = e.
Proof. destruct e; reflexivity. Qed.

Definition WIsoFinite : FiniteQuiver WIsoQuiver :=
  @Build_FiniteQuiver WIsoQuiver 2 WIso_node WIso_index WIso_node_rt
    WIso_ecount WIso_edge WIso_eindex WIso_edge_rt.

Definition WalkingIsoPresentation : FinitePresentation := {|
  fp_quiver := WIsoQuiver;
  fp_finite := WIsoFinite;
  fp_eqns   := WIsoEqns
|}.

(** The walking isomorphism. *)
Definition WalkingIso : Category :=
  FinitelyPresented WalkingIsoPresentation.

(** ...which is the presented category of the quiver and the relation,
    definitionally. *)
Example WalkingIso_is_presented :
  WalkingIso = PresentedQuiver WIsoQuiver (fe_rel WIsoEqns) := eq_refl.

(** The hom TYPES of [WalkingIso] are the free ones: equations merge,
    and never add.  This is what makes the trap in the header
    possible. *)
Example WalkingIso_hom_is_free (x y : WIsoNode) :
  (x ~{WalkingIso}~> y) = (x ~{FreeWIso}~> y) := eq_refl.

(** Composition is the free category's, on the nose. *)
Example WalkingIso_compose_is_free {x y z : WIsoNode}
  (p : y ~{FreeWIso}~> z) (q : x ~{FreeWIso}~> y) :
  @compose WalkingIso x y z p q = @compose FreeWIso x y z p q := eq_refl.

(** ** The generators, and the two relations *)

Definition iso_f : WI_A ~{WalkingIso}~> WI_B :=
  @pgen WIsoQuiver (fe_rel WIsoEqns) _ _ WI_f.
Definition iso_g : WI_B ~{WalkingIso}~> WI_A :=
  @pgen WIsoQuiver (fe_rel WIsoEqns) _ _ WI_g.

(** Each composite of one-step paths IS the corresponding two-step loop,
    definitionally — composition in [FreeOnQuiver] is [tlist]
    concatenation with the arguments flipped.  Recorded as a Leibniz
    equality because the two sides are the very same term after
    reduction. *)
Example free_gf_is_loop :
  @compose FreeWIso _ _ _ wi_g wi_f = wi_AA 1 := eq_refl.
Example free_fg_is_loop :
  @compose FreeWIso _ _ _ wi_f wi_g = wi_BB 1 := eq_refl.

(** Awodey's two equations, holding in the presented category.  Each is
    a single [cc_gen] — the generating constructor of
    [Construction/Quotient.v]'s congruence closure — applied to the
    corresponding index of the finite equation data. *)
Lemma wiso_gf :
  @equiv _ (@homset WalkingIso WI_A WI_A)
    (@compose WalkingIso _ _ _ iso_g iso_f) (@id WalkingIso WI_A).
Proof. apply cc_gen. exists Fin.F1. split; reflexivity. Qed.

Lemma wiso_fg :
  @equiv _ (@homset WalkingIso WI_B WI_B)
    (@compose WalkingIso _ _ _ iso_f iso_g) (@id WalkingIso WI_B).
Proof. apply cc_gen. exists Fin.F1. split; reflexivity. Qed.

(** ** The headline: f is an isomorphism

    The example's whole content.  The two inverse laws of the record are
    the two imposed equations verbatim; nothing is proved here that was
    not proved by writing the presentation down. *)
Definition walking_iso : @Isomorphism WalkingIso WI_A WI_B := {|
  to          := iso_f;
  from        := iso_g;
  iso_to_from := wiso_fg;
  iso_from_to := wiso_gf
|}.

Example walking_iso_to : to walking_iso = iso_f := eq_refl.
Example walking_iso_from : from walking_iso = iso_g := eq_refl.

(** ** Collapsing the free hom-sets

    Every path is one of the four families, and every member of a family
    is equivalent in [WalkingIso] to the family's zeroth term.  That is
    what makes the presented category thin. *)

(** Consing an edge onto a path IS composing with the corresponding
    generator, at Leibniz equality — [Lib/TList.v]'s [tlist_app_cons]
    read at this quiver. *)
Lemma wi_cons_f {y : WIsoNode} (t : WI_B ~{FreeWIso}~> y) :
  tcons (B:=@edges WIsoQuiver) _ WI_f t = @compose FreeWIso _ _ _ t wi_f.
Proof. exact (tlist_app_cons WI_f t). Qed.

Lemma wi_cons_g {y : WIsoNode} (t : WI_A ~{FreeWIso}~> y) :
  tcons (B:=@edges WIsoQuiver) _ WI_g t = @compose FreeWIso _ _ _ t wi_g.
Proof. exact (tlist_app_cons WI_g t). Qed.

(** Hence each loop is its predecessor followed by the round trip.
    Supplied as a term rather than by tactics: [simpl] unfolds the
    generators past the pattern the rewrite is looking for. *)
Definition wi_AA_step (n : nat) :
  wi_AA (S n) = @compose FreeWIso _ _ _
                  (@compose FreeWIso _ _ _ (wi_AA n) wi_g) wi_f :=
  eq_trans (wi_cons_f (tcons (B:=@edges WIsoQuiver) _ WI_g (wi_AA n)))
           (f_equal (fun t => @compose FreeWIso _ _ _ t wi_f)
                    (wi_cons_g (wi_AA n))).

Definition wi_BB_step (n : nat) :
  wi_BB (S n) = @compose FreeWIso _ _ _
                  (@compose FreeWIso _ _ _ (wi_BB n) wi_f) wi_g :=
  eq_trans (wi_cons_g (tcons (B:=@edges WIsoQuiver) _ WI_f (wi_BB n)))
           (f_equal (fun t => @compose FreeWIso _ _ _ t wi_g)
                    (wi_cons_f (wi_BB n))).

(** Every loop at A collapses to the identity.  The appeal to
    associativity names [WalkingIso] explicitly; see the header. *)
Lemma wi_AA_collapse (n : nat) :
  @equiv _ (@homset WalkingIso WI_A WI_A) (wi_AA n) (@id WalkingIso WI_A).
Proof.
  induction n as [ | n IH ]; [ reflexivity | ].
  rewrite wi_AA_step.
  rewrite <- (@comp_assoc WalkingIso _ _ _ _ (wi_AA n) wi_g wi_f).
  rewrite wiso_gf, id_right.
  exact IH.
Qed.

Lemma wi_BB_collapse (n : nat) :
  @equiv _ (@homset WalkingIso WI_B WI_B) (wi_BB n) (@id WalkingIso WI_B).
Proof.
  induction n as [ | n IH ]; [ reflexivity | ].
  rewrite wi_BB_step.
  rewrite <- (@comp_assoc WalkingIso _ _ _ _ (wi_BB n) wi_f wi_g).
  rewrite wiso_fg, id_right.
  exact IH.
Qed.

Lemma wi_AB_collapse (n : nat) :
  @equiv _ (@homset WalkingIso WI_A WI_B) (wi_AB n) iso_f.
Proof.
  unfold wi_AB; rewrite (wi_cons_f (wi_BB n)).
  change (@compose FreeWIso ?x ?y ?z ?a ?b)
    with (@compose WalkingIso x y z a b).
  rewrite wi_BB_collapse; apply id_left.
Qed.

Lemma wi_BA_collapse (n : nat) :
  @equiv _ (@homset WalkingIso WI_B WI_A) (wi_BA n) iso_g.
Proof.
  unfold wi_BA; rewrite (wi_cons_g (wi_AA n)).
  change (@compose FreeWIso ?x ?y ?z ?a ?b)
    with (@compose WalkingIso x y z a b).
  rewrite wi_AA_collapse; apply id_left.
Qed.

(** ** Thinness: every hom-set of [WalkingIso] is a singleton *)

(** Any two parallel arrows agree.  Each of the four cases classifies
    both arrows and collapses each to the same normal form. *)
Theorem WalkingIso_Thin : Thin WalkingIso.
Proof.
  intros x y p q; destruct x, y;
    destruct (wi_classify _ _ p) as [m Hm];
    destruct (wi_classify _ _ q) as [n Hn]; subst.
  - transitivity (@id WalkingIso WI_A);
      [ apply wi_AA_collapse | symmetry; apply wi_AA_collapse ].
  - transitivity iso_f;
      [ apply wi_AB_collapse | symmetry; apply wi_AB_collapse ].
  - transitivity iso_g;
      [ apply wi_BA_collapse | symmetry; apply wi_BA_collapse ].
  - transitivity (@id WalkingIso WI_B);
      [ apply wi_BB_collapse | symmetry; apply wi_BB_collapse ].
Qed.

(** A chosen inhabitant of each of the four hom-sets. *)
Definition wiso_arrow (x y : WIsoNode) : x ~{WalkingIso}~> y :=
  match x, y with
  | WI_A, WI_A => id
  | WI_A, WI_B => iso_f
  | WI_B, WI_A => iso_g
  | WI_B, WI_B => id
  end.

(** "Singleton" in full: inhabited, and any two members agree.  Both
    halves are needed — thinness alone would be satisfied by an empty
    hom-set, and this is what makes the arrow count below a count of
    arrows and not an upper bound. *)
Theorem wiso_hom_singleton (x y : WIsoNode) :
  ((x ~{WalkingIso}~> y) *
   (forall p q : x ~{WalkingIso}~> y, p ≈ q))%type.
Proof. exact (wiso_arrow x y, WalkingIso_Thin x y). Qed.

(** Every endomorphism is the identity: there are no nontrivial loops
    downstairs, though there are infinitely many upstairs. *)
Corollary wiso_endo_id {x : WalkingIso} (p : x ~> x) : p ≈ id.
Proof. exact (WalkingIso_Thin x x p id). Qed.

(** [WalkingIso] is the chaotic groupoid on two points: every arrow is
    invertible.  The inverse is the opposing arrow, which exists because
    every hom-set is inhabited, and both inverse laws are thinness.  The
    record is built directly rather than through [Structure/Thin.v]'s
    [thin_iso], which produces an [Isomorphism] where [IsGroupoid] asks
    for an [IsIsomorphism]. *)
Theorem WalkingIso_IsGroupoid : IsGroupoid WalkingIso.
Proof.
  intros x y f.
  unshelve eapply Build_IsIsomorphism.
  - exact (wiso_arrow y x).
  - apply WalkingIso_Thin.
  - apply WalkingIso_Thin.
Qed.

(** ** The presenting projection is not faithful, measured

    The free category is infinite where the presented one is not.  The
    contrast is exhibited on the loops at A: they are pairwise distinct
    upstairs and all equal downstairs.  READ THE WORD CAREFULLY: what
    this section establishes is that THIS presentation's projection from
    THIS free category is not faithful, so [WalkingIso] is not free on
    ITS OWN quiver.  It does NOT establish that [WalkingIso] is free on
    no quiver at all; [free_iso_lengths] below is the general fact that
    would begin such an argument, and the isomorphism-invariance step it
    would still need is neither proved nor attempted. *)

(** Equivalent paths of the free category have equal length —
    [tlist'_equiv_lengths] ([Construction/Free/Quiver.v]) at this
    quiver. *)
Lemma wi_equiv_length {x y : WIsoNode} (p q : x ~{FreeWIso}~> y) :
  p ≈ q -> tlist_length p = tlist_length q.
Proof. intro H; exact (tlist'_equiv_lengths _ _ _ _ _ _ _ H). Qed.

(* A FREE CATEGORY HAS NO NON-IDENTITY ISOMORPHISM: both legs of one have
   length zero, because length is additive under concatenation and
   invariant under the hom-setoid.  Stated for an ARBITRARY quiver -- it
   mentions nothing of this file -- so it is an upstreaming candidate for
   [Construction/Free/Quiver.v].  Note the composition orientation:
   [g ∘ f] in [FreeOnQuiver] is [f +++ g], so the [change] is what lets
   [tlist_app_length] fire. *)
Lemma free_iso_lengths {Q : Quiver} {x y : Q}
  (f : x ~{FreeOnQuiver Q}~> y) (g : y ~{FreeOnQuiver Q}~> x)
  (H : @equiv _ (@homset (FreeOnQuiver Q) x x)
         (@compose (FreeOnQuiver Q) x y x g f) (@id (FreeOnQuiver Q) x)) :
  (tlist_length f = 0)%nat /\ (tlist_length g = 0)%nat.
Proof.
  pose proof (tlist'_equiv_lengths _ _ _ _ _ _ _ H) as HL.
  change (@compose (FreeOnQuiver Q) x y x g f) with (f +++ g) in HL.
  rewrite tlist_app_length in HL. simpl in HL. split; lia.
Qed.

Lemma wi_AA_length (n : nat) : tlist_length (wi_AA n) = (n + n)%nat.
Proof.
  induction n as [ | n IH ]; [ reflexivity | ].
  simpl; rewrite PeanoNat.Nat.add_succ_r; do 2 f_equal; exact IH.
Qed.

Lemma wi_BB_length (n : nat) : tlist_length (wi_BB n) = (n + n)%nat.
Proof.
  induction n as [ | n IH ]; [ reflexivity | ].
  simpl; rewrite PeanoNat.Nat.add_succ_r; do 2 f_equal; exact IH.
Qed.

Lemma wi_double_inj (m n : nat) : (m + m)%nat = (n + n)%nat -> m = n.
Proof.
  revert n; induction m as [ | m IH ]; intros [ | n ] H; simpl in H;
    try discriminate; try reflexivity.
  f_equal; apply IH.
  injection H as H.
  rewrite !PeanoNat.Nat.add_succ_r in H.
  now injection H.
Qed.

(** The loops at A are pairwise distinct AS ARROWS of the free category
    — the statement is about [≈]-classes, not about representatives, so
    it survives the hom-setoid.  Hence [wi_AA] injects the naturals into
    that one hom-set. *)
Theorem free_wi_AA_inj (m n : nat) :
  @equiv _ (@homset FreeWIso WI_A WI_A) (wi_AA m) (wi_AA n) -> m = n.
Proof.
  intro H.
  apply wi_double_inj.
  rewrite <- (wi_AA_length m), <- (wi_AA_length n).
  exact (wi_equiv_length _ _ H).
Qed.

Corollary free_wi_AA_distinct (m n : nat) (Hmn : m <> n) :
  @equiv _ (@homset FreeWIso WI_A WI_A) (wi_AA m) (wi_AA n) -> False.
Proof. intro H; exact (Hmn (free_wi_AA_inj m n H)). Qed.

(** The presenting projection.  It is the identity on objects and on
    morphisms; only the hom-setoid coarsens. *)
Definition WalkingIsoProj : FreeWIso ⟶ WalkingIso :=
  @PresentedQuiverProj WIsoQuiver (fe_rel WIsoEqns).

Example WalkingIsoProj_hom {x y : WIsoNode} (p : x ~{FreeWIso}~> y) :
  fmap[WalkingIsoProj] p = p := eq_refl.

(** The two sides of the contrast at one concrete pair: the round trip
    (gf) and the empty path are distinct arrows of [FreeWIso] and the
    same arrow of [WalkingIso]. *)
Theorem walking_iso_merges_the_loops :
  ((@equiv _ (@homset FreeWIso WI_A WI_A) (wi_AA 1) (wi_AA 0) -> False) *
   (@equiv _ (@homset WalkingIso WI_A WI_A) (wi_AA 1) (wi_AA 0)))%type.
Proof.
  split.
  - apply free_wi_AA_distinct; discriminate.
  - exact (wi_AA_collapse 1).
Qed.

(** So the projection is not faithful.  Read this at exactly its
    strength: it says that THIS free category maps onto [WalkingIso]
    non-injectively on hom-sets, which is what "the relations do
    something" means.  It does NOT say that [WalkingIso] is not free on
    some other quiver, and no such claim is made anywhere in this
    file. *)
Theorem WalkingIsoProj_not_faithful : Faithful WalkingIsoProj -> False.
Proof.
  intro HF.
  apply (free_wi_AA_distinct 1 0); [ discriminate | ].
  apply (@fmap_inj _ _ _ HF WI_A WI_A (wi_AA 1) (wi_AA 0)).
  exact (wi_AA_collapse 1).
Qed.

(** ** The counts

    Two objects and four arrows, both proved.  [WalkingIso] is thin and
    every hom-set is inhabited ([wiso_hom_singleton]), so an arrow is
    determined by its endpoints and counting arrows is counting the
    ordered pairs of nodes. *)

Definition wi_nodes : list WIsoNode := WI_A :: WI_B :: nil.

Lemma wi_nodes_complete (x : WIsoNode) : In x wi_nodes.
Proof. destruct x; simpl; auto. Qed.

Lemma wi_nodes_nodup : NoDup wi_nodes.
Proof. repeat constructor; simpl; intuition congruence. Qed.

(** Two objects. *)
Theorem wiso_object_total : length wi_nodes = 2%nat.
Proof. reflexivity. Qed.

Definition wi_all_pairs : list (WIsoNode * WIsoNode) :=
  list_prod wi_nodes wi_nodes.

Example wi_all_pairs_4 : length wi_all_pairs = 4%nat := eq_refl.

Lemma wi_all_pairs_complete (x y : WIsoNode) : In (x, y) wi_all_pairs.
Proof. apply in_prod; apply wi_nodes_complete. Qed.

(** Every hom-set has exactly one arrow — the constant is what
    [wiso_hom_singleton] licenses, and nothing else in this section
    depends on which pair is being counted. *)
Definition wiso_homcount (x y : WIsoNode) : nat := 1%nat.

Definition wiso_arrow_total : nat :=
  fold_right (fun q n => wiso_homcount (fst q) (snd q) + n)%nat 0%nat
    wi_all_pairs.

(** Four arrows. *)
Theorem wiso_arrow_total_4 : wiso_arrow_total = 4%nat.
Proof. reflexivity. Qed.

Definition wiso_identity_total : nat :=
  fold_right (fun x n => wiso_homcount x x + n)%nat 0%nat wi_nodes.

(** ...two of them identities. *)
Theorem wiso_identity_total_2 : wiso_identity_total = 2%nat.
Proof. reflexivity. Qed.

Definition wiso_nonidentity_total : nat :=
  (wiso_arrow_total - wiso_identity_total)%nat.

(** ...and two of them not: [iso_f] and [iso_g]. *)
Theorem wiso_nonidentity_total_2 : wiso_nonidentity_total = 2%nat.
Proof. reflexivity. Qed.

(** The two non-identity arrows are not identities, because their
    endpoints differ. *)
Lemma wiso_nonidentity_endpoints : WI_A <> WI_B.
Proof. discriminate. Qed.

(** Neither of the two arrows is a composite of others: the quiver has
    exactly two edges, computed from the [FiniteQuiver] data rather than
    asserted, and the presented category has exactly two non-identity
    arrows. *)
Definition wiso_generator_total : nat :=
  fold_right
    (fun q n => fq_edges WIsoQuiver WIsoFinite (fst q) (snd q) + n)%nat
    0%nat wi_all_pairs.

Theorem wiso_generator_total_2 : wiso_generator_total = 2%nat.
Proof. reflexivity. Qed.

(** ** The universal property: a functor out of [WalkingIso] is an
       isomorphism

    This is what the word "walking" means, and it is the converse
    direction that makes the presentation worth having. *)

Section IndexShape.

Context {C : Category}.

Definition wiso_node {a b : C} (i : a ≅ b) (n : WIsoNode) : C :=
  match n with WI_A => a | WI_B => b end.

Definition wiso_edgemap {a b : C} (i : a ≅ b) (x y : WIsoNode)
  (e : WIsoEdge x y) : wiso_node i x ~> wiso_node i y :=
  match e in WIsoEdge u v return wiso_node i u ~> wiso_node i v with
  | WI_f => to i
  | WI_g => from i
  end.

Definition wiso_quiver_hom {a b : C} (i : a ≅ b) :
  QuiverHomomorphism WIsoQuiver (QuiverOfCat C).
Proof.
  unshelve eapply Build_QuiverHomomorphism.
  - exact (wiso_node i).
  - exact (wiso_edgemap i).
  - intros x y u v Huv; simpl in Huv; subst; reflexivity.
Defined.

(** The two imposed relations are merged: they are exactly the two
    inverse laws, modulo the trailing identity a [tlist] fold leaves
    behind. *)
Lemma wiso_quiver_hom_merges {a b : C} (i : a ≅ b) :
  forall x y (p q : x ~{FreeWIso}~> y), fe_rel WIsoEqns x y p q ->
    fmap[@InducedFunctor WIsoQuiver C (wiso_quiver_hom i)] p
      ≈ fmap[@InducedFunctor WIsoQuiver C (wiso_quiver_hom i)] q.
Proof.
  intros x y p q [k [Hp Hq]].
  destruct x, y; simpl in k; try solve [ exact (Fin.case0 _ k) ];
    simpl in Hp, Hq; rewrite Hp, Hq; simpl; rewrite !id_left.
  - exact (iso_from_to i).
  - exact (iso_to_from i).
Qed.

(** The functor an isomorphism names. *)
Definition WalkingIsoFunctor {a b : C} (i : a ≅ b) : WalkingIso ⟶ C :=
  @PresentedFunctor WIsoQuiver (fe_rel WIsoEqns) C
    (wiso_quiver_hom i) (wiso_quiver_hom_merges i).

Example WalkingIsoFunctor_A {a b : C} (i : a ≅ b) :
  fobj[WalkingIsoFunctor i] WI_A = a := eq_refl.
Example WalkingIsoFunctor_B {a b : C} (i : a ≅ b) :
  fobj[WalkingIsoFunctor i] WI_B = b := eq_refl.

Lemma WalkingIsoFunctor_f {a b : C} (i : a ≅ b) :
  fmap[WalkingIsoFunctor i] iso_f ≈ to i.
Proof.
  exact (@PresentedFunctor_gen WIsoQuiver (fe_rel WIsoEqns) C
           (wiso_quiver_hom i) (wiso_quiver_hom_merges i) _ _ WI_f).
Qed.

Lemma WalkingIsoFunctor_g {a b : C} (i : a ≅ b) :
  fmap[WalkingIsoFunctor i] iso_g ≈ from i.
Proof.
  exact (@PresentedFunctor_gen WIsoQuiver (fe_rel WIsoEqns) C
           (wiso_quiver_hom i) (wiso_quiver_hom_merges i) _ _ WI_g).
Qed.

(** The converse: a functor out of [WalkingIso] carries the two
    generators to an inverse pair, the two laws coming from [wiso_fg]
    and [wiso_gf] under [fmap_respects]. *)
Lemma functor_iso_to_from (F : WalkingIso ⟶ C) :
  fmap[F] iso_f ∘ fmap[F] iso_g ≈ id.
Proof.
  rewrite <- fmap_comp.
  rewrite (@fmap_respects _ _ F _ _ _ _ wiso_fg).
  apply fmap_id.
Qed.

Lemma functor_iso_from_to (F : WalkingIso ⟶ C) :
  fmap[F] iso_g ∘ fmap[F] iso_f ≈ id.
Proof.
  rewrite <- fmap_comp.
  rewrite (@fmap_respects _ _ F _ _ _ _ wiso_gf).
  apply fmap_id.
Qed.

Definition IsoOfFunctor (F : WalkingIso ⟶ C) :
  fobj[F] WI_A ≅ fobj[F] WI_B := {|
  to          := fmap[F] iso_f;
  from        := fmap[F] iso_g;
  iso_to_from := functor_iso_to_from F;
  iso_from_to := functor_iso_from_to F
|}.

(** Round trip one, on the isomorphism side: the objects come back on
    the nose and the two morphisms up to [≈]. *)
Example wiso_round_obj_a {a b : C} (i : a ≅ b) :
  fobj[WalkingIsoFunctor i] WI_A = a := eq_refl.
Example wiso_round_obj_b {a b : C} (i : a ≅ b) :
  fobj[WalkingIsoFunctor i] WI_B = b := eq_refl.

Theorem wiso_round_morphisms {a b : C} (i : a ≅ b) :
  ((to (IsoOfFunctor (WalkingIsoFunctor i)) ≈ to i) *
   (from (IsoOfFunctor (WalkingIsoFunctor i)) ≈ from i))%type.
Proof. exact (WalkingIsoFunctor_f i, WalkingIsoFunctor_g i). Qed.

(** Round trip two, on the functor side, at STRICT strength — Leibniz on
    objects and a [hom_cast] conjugation on morphisms, which is
    [StrictCat]'s functor equality ([Functor_StrictEq_Setoid], via
    [strict_of_hom_cast]).  As in [Instance/Square.v], the object
    agreement is [eq_refl] at each node but not uniformly in a variable
    node, since [wiso_node] is a match; that is a statement about
    reduction, not a weakening. *)
Definition wiso_round_obj (F : WalkingIso ⟶ C) (x : WIsoNode) :
  fobj[F] x = wiso_node (IsoOfFunctor F) x :=
  match x with WI_A => eq_refl | WI_B => eq_refl end.

Theorem wiso_functor_round (F : WalkingIso ⟶ C) :
  forall (x y : WIsoNode) (p : x ~{WalkingIso}~> y),
    hom_cast (wiso_round_obj F x) (wiso_round_obj F y) (fmap[F] p)
      ≈ fmap[WalkingIsoFunctor (IsoOfFunctor F)] p.
Proof.
  apply (@PresentedFunctor_unique WIsoQuiver (fe_rel WIsoEqns) C
           (wiso_quiver_hom (IsoOfFunctor F))
           (wiso_quiver_hom_merges (IsoOfFunctor F))
           F (wiso_round_obj F)).
  intros x y e; destruct e; reflexivity.
Qed.

Theorem wiso_functor_round_strict (F : WalkingIso ⟶ C) :
  @equiv _ (@Functor_StrictEq_Setoid WalkingIso C)
    F (WalkingIsoFunctor (IsoOfFunctor F)).
Proof.
  apply (strict_of_hom_cast F (WalkingIsoFunctor (IsoOfFunctor F))
           (wiso_round_obj F)).
  exact (wiso_functor_round F).
Qed.

(** The universal property, bundled: to give a functor out of
    [WalkingIso] is exactly to give an isomorphism, and the functor is
    unique at strict strength. *)
Theorem walking_iso_universal {a b : C} (i : a ≅ b) :
  { F : WalkingIso ⟶ C &
  { Hobj : forall x : WIsoNode, fobj[F] x = wiso_node i x &
    (((hom_cast (Hobj WI_A) (Hobj WI_B) (fmap[F] iso_f) ≈ to i) *
      (hom_cast (Hobj WI_B) (Hobj WI_A) (fmap[F] iso_g) ≈ from i)) *
     (forall (K : WalkingIso ⟶ C)
        (Hobj' : forall x : WIsoNode, fobj[K] x = wiso_node i x),
        (forall (x y : WIsoNode) (e : WIsoEdge x y),
           hom_cast (Hobj' x) (Hobj' y)
             (fmap[K] (@pgen WIsoQuiver (fe_rel WIsoEqns) x y e))
             ≈ wiso_edgemap i x y e) ->
        forall (x y : WIsoNode) (p : x ~{WalkingIso}~> y),
          hom_cast (Hobj' x) (Hobj' y) (fmap[K] p)
            ≈ hom_cast (Hobj x) (Hobj y) (fmap[F] p)))%type } }.
Proof.
  exists (WalkingIsoFunctor i), (fun _ => eq_refl).
  split; [ split | ].
  - exact (WalkingIsoFunctor_f i).
  - exact (WalkingIsoFunctor_g i).
  - intros K Hobj' Hgen x y p.
    exact (@PresentedFunctor_unique WIsoQuiver (fe_rel WIsoEqns) C
             (wiso_quiver_hom i) (wiso_quiver_hom_merges i)
             K Hobj' Hgen x y p).
Qed.

End IndexShape.
