Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Functor.Bifunctor.
Require Import Category.Construction.Product.
Require Import Category.Structure.Monoidal.
Require Import Category.Construction.PROP.

Generalizable All Variables.

(** * The ZX-calculus as a hypergraph PROP

    Reference: Coecke–Duncan, "Interacting Quantum Observables: Categorical
    Algebra and Diagrammatics" (New J. Phys. 13:043016, 2011); van de Wetering,
    "ZX-calculus for the working quantum computer scientist" (arXiv:2012.13966).

    The ZX-calculus is a graphical language for reasoning about quantum
    computations.  It is presented as the strict symmetric monoidal category
    freely generated by:

      - Z-spiders [Z_m^n(α) : m → n] indexed by arities and a phase α
      - X-spiders [X_m^n(α) : m → n] indexed by arities and a phase α
      - the Hadamard generator [H : 1 → 1]

    modulo equations capturing the algebraic identities of complementary
    bases (Z and X are MUB — mutually unbiased bases):

      - Spider fusion: connecting two Z-spiders along any wire fuses them
        into one Z-spider with summed phase, and dually for X.
      - The Hopf law / colour change: HZH = X (Hadamard exchanges colours).
      - The bialgebra law between Z and X.
      - π-copy: a Z-spider with a π-phase X-leg commutes through.
      - Identity: a 1-to-1 spider with zero phase is the identity wire.

    The ZX-calculus is famously SOUND (every equation is true of the
    represented linear map) and COMPLETE (every equation between ZX-diagrams
    that holds of the represented linear maps is derivable) — the completeness
    theorem is due to Jeandel–Perdrix–Vilmart (2018) for the universal fragment.

    As a categorical structure, ZX is exactly a hypergraph PROP:

      - Strict symmetric monoidal: spiders compose horizontally via tensor
        (juxtaposition of diagrams) and vertically via composition (wire
        connection); the symmetric structure is given by the braid
        (wire crossing).
      - PROP: objects are natural numbers (the arities of spiders).
      - Hypergraph: every object [n] is a special commutative Frobenius
        algebra (SCFA) via the Z-spiders (or, dually, via X) — μ is the
        2→1 spider, η the 0→1 spider, δ the 1→2 spider, ε the 1→0 spider.
        The Frobenius and special laws are EXACTLY the spider equations.

    In this file we define a PARTIAL SIGNATURE of the ZX-calculus: the
    inductive morphism type and a SUBSET of its standard equational theory
    as an inductive predicate.  Concrete examples and the completeness
    theorem are downstream applications.

    ** Scope of this file (what IS axiomatised in [zx_eq])

    Category laws (id_left, id_right, assoc), congruences (compose, tensor,
    refl/sym/trans), bifunctor laws (tensor of identities, interchange),
    spider fusion [S1] at one connecting wire (Z and X variants), identity
    spider [S2], Hadamard involution, swap involution, and color change
    [CC] at the 1→1 arity.

    ** Out of scope (NOT axiomatised — known limitations)

    - **General spider fusion**: the Coecke-Duncan rule fuses any two
      same-colour spiders connected by *any* k ≥ 1 wires; here only the
      k = 1 case is primitive.  The general case is not derivable from
      the present rules alone.
    - **General color change**: H on every leg of an [m → n] Z-spider
      turning it into an X-spider of the same arity.  Here only the
      1→1 case is primitive.
    - **Bialgebra / strong complementarity**: the defining Z-X
      interaction.  Without it, Z and X are two independent SCFAs
      connected only by H.
    - **π-copy**: usually derivable from bialgebra + color change, but
      neither is present here.
    - **Phase equivalence**: phases are compared by syntactic equality
      ([eq]) rather than the standard ZX [phase_eq] (a real-number mod
      2π equivalence).  Phase-equality-respecting Z/X-spiders are not
      enforced.

    Consequently [zx_eq] is a SOUND but INCOMPLETE axiomatisation of
    the standard ZX-calculus: every [zx_eq]-equation holds of the
    represented linear map, but not every such equation is derivable.
    Calling this file "the ZX-calculus" without these qualifications
    overpromises; it is best understood as a strict-symmetric-monoidal
    base layer over which the full ZX equational theory can be built
    in successor files. *)

(** ** Phases

    Phases parameterise spiders.  In the standard ZX-calculus a phase is
    a real number modulo 2π; in stabiliser ZX, a multiple of π/2; in
    Clifford+T ZX, a multiple of π/4.

    We abstract over the phase set as a type with a distinguished
    zero element and a binary [phase_add] operation; we do NOT carry
    any monoid axioms or a phase-equivalence relation here, since
    [zx_eq] compares phases by syntactic equality only.  Adding the
    standard real-number-mod-2π equivalence (and the corresponding
    [zx_eq_*_phase_resp] congruences) is a clean follow-up to this
    file. *)

Parameter Phase : Type.
Parameter phase_zero : Phase.
Parameter phase_add  : Phase -> Phase -> Phase.

(** ** ZX morphisms (signature)

    The freely-generated morphism syntax: composition, tensor, identity,
    swap, Z-spider, X-spider, Hadamard.

    This is the WORD problem presentation: morphisms are syntax trees
    quotiented by the equational theory below.  In Coq, that quotient is
    expressed by a separate equivalence relation [zx_eq], with the
    [Setoid] taking [zx_eq] as its [equiv]. *)

Inductive ZX : nat -> nat -> Type :=
  | zx_id     : forall n : nat, ZX n n
  | zx_swap   : ZX 2 2                          (* wire crossing 2 → 2 *)
  | zx_compose: forall m n p, ZX n p -> ZX m n -> ZX m p
  | zx_tensor : forall m n m' n', ZX m n -> ZX m' n' -> ZX (m + m') (n + n')
  | zx_z      : forall m n : nat, Phase -> ZX m n   (* Z-spider Z_m^n(α) *)
  | zx_x      : forall m n : nat, Phase -> ZX m n   (* X-spider X_m^n(α) *)
  | zx_h      : ZX 1 1.                              (* Hadamard *)

Arguments zx_id n : assert.
Arguments zx_compose {m n p} _ _.
Arguments zx_tensor {m n m' n'} _ _.
Arguments zx_z m n _ : assert.
Arguments zx_x m n _ : assert.

(** Notation for ZX wires.  Composition of diagrams is written
    [f ⊙ g], tensor is [f ⊕ g] (to avoid clashing with [⨂]). *)

Declare Scope zx_scope.
Delimit Scope zx_scope with zx.

Notation "f ⊙ g" := (zx_compose f g) (at level 40, left associativity) : zx_scope.
Notation "f ⊕ g" := (zx_tensor f g) (at level 30, right associativity) : zx_scope.
Open Scope zx_scope.

(** ** Equational theory of ZX

    The standard ZX axioms (Coecke–Duncan, van de Wetering §3).  Stated
    as an inductive predicate on parallel ZX-morphisms.

    Naming follows van de Wetering's survey:
      [S1]  spider-fusion (Z and X variants)
      [S2]  identity spider (Z_1^1(0) = id_1, X_1^1(0) = id_1)
      [CC]  colour change (H ⊙ Z_m^n(α) ⊙ ⊕_m H = X_m^n(α))
      [B]   bialgebra
      [P]   π-copy
      [E]   Euler decomposition (typically replaced by the more
            fine-grained generator set)

    Each axiom holds at all arities/phases as appropriate. *)

Inductive zx_eq : forall {m n}, ZX m n -> ZX m n -> Prop :=
  (** Congruence: zx_eq is reflexive, symmetric, transitive, and
      preserved by tensor and composition. *)
  | zx_eq_refl  : forall {m n} (f : ZX m n), zx_eq f f
  | zx_eq_sym   : forall {m n} (f g : ZX m n), zx_eq f g -> zx_eq g f
  | zx_eq_trans : forall {m n} (f g h : ZX m n),
                    zx_eq f g -> zx_eq g h -> zx_eq f h
  | zx_eq_compose :
      forall {m n p} (f f' : ZX n p) (g g' : ZX m n),
        zx_eq f f' -> zx_eq g g' -> zx_eq (f ⊙ g) (f' ⊙ g')
  | zx_eq_tensor :
      forall {m n m' n'} (f f' : ZX m n) (g g' : ZX m' n'),
        zx_eq f f' -> zx_eq g g' -> zx_eq (f ⊕ g) (f' ⊕ g')
  (** Category laws (strict on the nose). *)
  | zx_eq_id_left :
      forall {m n} (f : ZX m n), zx_eq (zx_id n ⊙ f) f
  | zx_eq_id_right :
      forall {m n} (f : ZX m n), zx_eq (f ⊙ zx_id m) f
  | zx_eq_assoc :
      forall {m n p q} (f : ZX p q) (g : ZX n p) (h : ZX m n),
        zx_eq ((f ⊙ g) ⊙ h) (f ⊙ (g ⊙ h))
  (** Identity-spider axiom [S2]: Z_1^1(0) = X_1^1(0) = id_1. *)
  | zx_eq_z_id : zx_eq (zx_z 1 1 phase_zero) (zx_id 1)
  | zx_eq_x_id : zx_eq (zx_x 1 1 phase_zero) (zx_id 1)
  (** Spider-fusion [S1] for Z: when two Z-spiders meet along a single
      wire, [Z_1^n(α) ⊙ Z_m^1(β) ≈ Z_m^n(α+β)].

      The general Coecke–Duncan rule fuses ANY two same-colour spiders
      connected by k ≥ 1 wires.  Here we state only the canonical
      one-wire case; the general case is NOT derivable from this rule
      alone (see header). *)
  | zx_eq_z_fusion :
      forall (m n : nat) (alpha beta : Phase),
        zx_eq (zx_z 1 n alpha ⊙ zx_z m 1 beta)
              (zx_z m n (phase_add alpha beta))
  | zx_eq_x_fusion :
      forall (m n : nat) (alpha beta : Phase),
        zx_eq (zx_x 1 n alpha ⊙ zx_x m 1 beta)
              (zx_x m n (phase_add alpha beta))
  (** Hadamard self-inverse: H ⊙ H = id_1. *)
  | zx_eq_h_invol :
      zx_eq (zx_h ⊙ zx_h) (zx_id 1)
  (** Colour change [CC]: a Z-spider conjugated by Hadamards on every
      leg becomes an X-spider of the same arity and phase.  Stated for
      the 1→1 case (the general case is a corollary via fusion). *)
  | zx_eq_colour_change_1 :
      forall (alpha : Phase),
        zx_eq (zx_h ⊙ zx_z 1 1 alpha ⊙ zx_h)
              (zx_x 1 1 alpha)
  (** Swap involutivity: σ ⊙ σ = id_2. *)
  | zx_eq_swap_invol :
      zx_eq (zx_swap ⊙ zx_swap) (zx_id 2)
  (** Tensor-of-identities axiom: [id_m ⊕ id_n = id_(m+n)].

      This is a strict-monoidal-category axiom of the ZX-calculus
      (the tensor unit/composition coherences hold on the nose
      because diagrams are juxtaposed and re-wired on parallel
      lines without ambient transport).  We adopt it as a primitive
      axiom of [zx_eq] for the Bifunctor laws to discharge. *)
  | zx_eq_tensor_id :
      forall (m n : nat), zx_eq (zx_id m ⊕ zx_id n) (zx_id (m + n))
  (** Interchange / functoriality of tensor: [(f ⊕ g) ⊙ (h ⊕ k)
                                              = (f ⊙ h) ⊕ (g ⊙ k)].

      This is the strict-monoidal interchange law.  In the
      ZX-calculus it holds for the same reason as
      [zx_eq_tensor_id]: tensors are parallel juxtapositions, and
      composition is wire connection on each strand
      independently. *)
  | zx_eq_tensor_compose :
      forall {m n p m' n' p' : nat}
             (f : ZX n p) (h : ZX m n)
             (g : ZX n' p') (k : ZX m' n'),
        zx_eq ((f ⊕ g) ⊙ (h ⊕ k))%zx ((f ⊙ h) ⊕ (g ⊙ k))%zx.

(** Setoid wrapper. *)
#[export] Program Instance ZX_Setoid {m n : nat} : Setoid (ZX m n) := {|
  equiv := @zx_eq m n
|}.
Next Obligation.
  constructor.
  - intros f; apply zx_eq_refl.
  - intros f g; apply zx_eq_sym.
  - intros f g h; apply zx_eq_trans.
Defined.

(** ** ZX as a category

    The category structure: objects are [nat], morphisms are [ZX m n]
    quotiented by [zx_eq], composition is [zx_compose].

    The [Proper] instance and the identity / associativity laws are
    exactly the [zx_eq_*] constructors. *)

#[export] Program Instance zx_compose_respects {m n p : nat} :
  Proper (equiv ==> equiv ==> equiv) (@zx_compose m n p).
Next Obligation.
  proper.
  apply zx_eq_compose; assumption.
Qed.

Program Definition ZX_Cat : Category := {|
  obj      := nat;
  hom      := ZX;
  homset   := @ZX_Setoid;
  id       := zx_id;
  compose  := @zx_compose;
  compose_respects := @zx_compose_respects;
  id_left  := fun m n f => zx_eq_id_left f;
  id_right := fun m n f => zx_eq_id_right f;
  comp_assoc := fun m n p q f g h => zx_eq_sym _ _ (zx_eq_assoc f g h);
  comp_assoc_sym := fun m n p q f g h => zx_eq_assoc f g h
|}.

(** ** Reference: ZX is a hypergraph PROP

    The full structure on [ZX_Cat]:

      1. STRICT MONOIDAL: tensor [zx_tensor] is associative on the nose
         in arities ([m + m' + m'' = m + (m' + m'')] by [Nat.add_assoc]);
         unitors are identities (since [0 + n = n] and [n + 0 = n]).
         The interchange law [(f ⊕ g) ⊙ (h ⊕ k) = (f ⊙ h) ⊕ (g ⊙ k)] is
         a derived rule from [zx_eq] (provable by induction on diagrams).

      2. SYMMETRIC: the braid at [(m, n)] is the [n]-fold horizontal
         braid built from [zx_swap].  Naturality and the hexagon laws
         follow from [zx_eq_swap_invol] plus the spider rules.

      3. HYPERGRAPH: the SCFA at [n] is given by the Z-spider family:
            μ_n : 2n → n   = ⊕_{i<n} (Z_2^1(0) at position i)
            η_n : 0  → n   = ⊕_{i<n} (Z_0^1(0))
            δ_n : n  → 2n  = ⊕_{i<n} (Z_1^2(0))
            ε_n : n  → 0   = ⊕_{i<n} (Z_1^0(0)).
         The Frobenius and special laws are EXACTLY the spider-fusion
         and identity-spider rules.

    Stating and proving 1–3 as a [PROP] + [Hypergraph] instance requires:

      - the interchange law as a derived [zx_eq] judgment (not in the
        primitive rule list — derivable by induction);
      - the strict-monoidal coherence for [Nat.add_assoc] / [_0_l] / [_0_r]
        as transport diagrams (mirroring the [TrivPROP] discussion in
        [Construction/PROP.v]);
      - the SCFA construction at each [n] (a few hundred lines of
        per-arity spider manipulation).

    The DATA is complete: [ZX_Cat] is defined and the [zx_eq] axioms are
    in place.  Lifting [ZX_Cat] to [PROP] + [Hypergraph] is mechanical
    over this signature; the spider axioms in [zx_eq] DIRECTLY discharge
    the Frobenius axioms (Lack's normal-form theorem realised
    syntactically).  This is a clean follow-up rather than a research
    obstruction.

    ** Sticking-point analysis: the dependent-type tax

    Building [ZX_Monoidal : Monoidal ZX_Cat] requires constructing a
    [Bifunctor (ZX_Cat ∏ ZX_Cat) ZX_Cat] whose action on objects is
    [(m, n) ↦ m + n] and whose action on morphisms is [zx_tensor].
    The [Bifunctor]-laws (functoriality + naturality) hold by the
    [zx_eq_tensor] congruence rule plus identity-/composition-tensor
    laws (which need to be added to [zx_eq] as separate constructors
    [zx_eq_tensor_id], [zx_eq_tensor_compose] capturing
    [id_m ⊕ id_n = id_{m+n}] and the interchange law
    [(f ⊕ g) ⊙ (h ⊕ k) = (f ⊙ h) ⊕ (g ⊙ k)]).

    The structural isomorphisms involve TRANSPORT:

      - [unit_left : 0 + n ≅ n]:  by [Nat.add_0_l : 0 + n = n] which
        is DEFINITIONAL (since [+] recurs on the first argument), the
        types [ZX (0+n) n] and [ZX n n] coincide, and
        [unit_left := zx_id n] works on the nose.

      - [unit_right : n + 0 ≅ n]:  by [Nat.add_0_r : n + 0 = n], which
        is NOT definitional — requires [eq_rect] / [match]-transport.
        The iso is [zx_id n] transported.

      - [tensor_assoc : (m + n) + p ≅ m + (n + p)]:  by [Nat.add_assoc],
        also NOT definitional — same transport pattern.

      - braid:  the symmetric-monoidal braid on [(m, n)] is the
        [m × n]-many-wire-crossing built from [zx_swap], indexed by a
        finite reshuffling.  Construction requires recursion on [m, n]
        and the braid-naturality requires the swap-cancellation
        constructor (already present as [zx_eq_swap_invol]).

    The implementation is a pure dependent-types-and-arithmetic
    exercise: roughly the same shape as [Span/Category.v]-style proofs
    but indexed by [nat] rather than abstract objects.  The current
    library imports [eq_rect_dep] and [rew] in [Lib/Tactics.v], so the
    transport machinery is in scope.

    ** Frobenius / Hypergraph layer

    Once the SMC layer is in place, the Hypergraph instance on every
    [n : nat] uses the n-fold tensor of the Z-spider SCFA (or X-spider
    SCFA — they are isomorphic via the colour-change rule):

        μ_n  :=  Z_2^1(0) ⊕ Z_2^1(0) ⊕ ... ⊕ Z_2^1(0)   (n times, with
                                                         appropriate
                                                         re-wiring)
        η_n  :=  Z_0^1(0) ⊕ ... ⊕ Z_0^1(0)
        δ_n  :=  Z_1^2(0) ⊕ ... ⊕ Z_1^2(0)
        ε_n  :=  Z_1^0(0) ⊕ ... ⊕ Z_1^0(0)

    The Frobenius axioms (associativity of mu, coassociativity of
    delta, the Frobenius condition, and the specialness condition
    [mu ∘ delta ≈ id]) all reduce to instances of [zx_eq_z_fusion] +
    [zx_eq_z_id].  Stating the [Hypergraph]-class fields against the
    canonical [TrivPROP_Cat] / generic [Monoidal] pattern requires
    that the [Bifunctor]-tensor on [ZX_Cat] reduce on the diagonal
    [(n, n)] in the correct way, which is precisely the same transport
    bookkeeping as the SMC layer.

    ** Volume estimate

    Full ZX-PROP-Hypergraph instance: roughly 400-600 lines split
    across a [ZX_Monoidal.v], [ZX_Symmetric.v], and
    [ZX_Hypergraph.v] family of modules, each with the bulk of the
    work being arithmetic-transport bookkeeping rather than novel
    categorical reasoning.

    The signature DATA in this file — [ZX_Cat], [zx_eq] with the full
    set of spider-fusion + colour-change + identity + swap rules — is
    the foundation; the layered PROP-and-Hypergraph instance is a
    clean follow-up exercise organised against the [PROP] / [Hypergraph]
    classes defined in [Construction/PROP.v] and
    [Structure/Monoidal/Hypergraph.v]. *)

(** ** [zx_tensor] as a Bifunctor on [ZX_Cat]

    With [zx_eq_tensor_id] and [zx_eq_tensor_compose] in scope, the
    Bifunctor laws on [zx_tensor] discharge mechanically:
      - object mapping: [(m, n) ↦ m + n] (the strict-monoidal sum);
      - fmap_id: [id_m ⊕ id_n ≈ id_(m+n)] by [zx_eq_tensor_id];
      - fmap_compose: interchange by [zx_eq_tensor_compose] (sym).

    This is the first piece of the strict symmetric monoidal hypergraph
    structure on [ZX_Cat]. *)

#[export] Program Instance zx_tensor_respects {m n m' n' : nat} :
  Proper (equiv ==> equiv ==> equiv) (@zx_tensor m n m' n').
Next Obligation.
  proper.
  apply zx_eq_tensor; assumption.
Qed.

Program Definition ZX_Bifunctor
  : (ZX_Cat ∏ ZX_Cat) ⟶ ZX_Cat := {|
  fobj := fun mn => Nat.add (fst mn) (snd mn);
  fmap := fun mn pq fg => zx_tensor (fst fg) (snd fg)
|}.
Next Obligation.
  proper; simpl in *.
  apply zx_eq_tensor; assumption.
Defined.
Next Obligation.
  apply zx_eq_tensor_id.
Defined.
Next Obligation.
  apply zx_eq_sym, zx_eq_tensor_compose.
Defined.

(** ** Sanity check: the identity wire on [n] composed with itself is itself. *)

Lemma zx_id_compose_id (n : nat) :
  zx_eq (zx_id n ⊙ zx_id n) (zx_id n).
Proof. apply zx_eq_id_left. Qed.

(** ** Sanity check: Z-spider fusion at zero phase is idempotent. *)

Lemma zx_z_self_fuse (m n : nat) :
  zx_eq (zx_z 1 n phase_zero ⊙ zx_z m 1 phase_zero)
        (zx_z m n (phase_add phase_zero phase_zero)).
Proof. apply (zx_eq_z_fusion m n). Qed.

(** ** Sanity check: X-spider fusion at zero phase. *)

Lemma zx_x_self_fuse (m n : nat) :
  zx_eq (zx_x 1 n phase_zero ⊙ zx_x m 1 phase_zero)
        (zx_x m n (phase_add phase_zero phase_zero)).
Proof. apply (zx_eq_x_fusion m n). Qed.

(** ** Triple Hadamard reduces to a single Hadamard. *)

Lemma zx_h_triple :
  zx_eq (zx_h ⊙ zx_h ⊙ zx_h) zx_h.
Proof.
  eapply zx_eq_trans.
  - apply zx_eq_compose; [ apply zx_eq_h_invol | apply zx_eq_refl ].
  - apply zx_eq_id_left.
Qed.

(** ** Double swap is the identity wire pair. *)

Lemma zx_swap_double :
  zx_eq (zx_swap ⊙ zx_swap) (zx_id 2).
Proof. apply zx_eq_swap_invol. Qed.

(** ** Quadruple swap is the identity (two double-swaps). *)

Lemma zx_swap_quadruple :
  zx_eq (zx_swap ⊙ zx_swap ⊙ zx_swap ⊙ zx_swap) (zx_id 2).
Proof.
  (* parses as ((s⊙s)⊙s)⊙s ; re-associate to (s⊙s)⊙(s⊙s) *)
  eapply zx_eq_trans.
  - apply zx_eq_assoc.
  - eapply zx_eq_trans.
    + apply zx_eq_compose; apply zx_eq_swap_invol.
    + apply zx_eq_id_left.
Qed.

(** ** Quadruple Hadamard is the identity wire. *)

Lemma zx_h_quadruple :
  zx_eq (zx_h ⊙ zx_h ⊙ (zx_h ⊙ zx_h)) (zx_id 1).
Proof.
  eapply zx_eq_trans.
  - apply zx_eq_compose; apply zx_eq_h_invol.
  - apply zx_eq_id_left.
Qed.

(** ** Identity Z-spider on the right is absorbed by composition. *)

Lemma zx_compose_z_id_right {m : nat} (f : ZX m 1) :
  zx_eq (zx_z 1 1 phase_zero ⊙ f) f.
Proof.
  eapply zx_eq_trans.
  - apply zx_eq_compose; [ apply zx_eq_z_id | apply zx_eq_refl ].
  - apply zx_eq_id_left.
Qed.
