Require Import Category.Lib.
Require Import Category.Lib.Setoid.Propositional.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Morphisms.
(* Imported before Theory/Subobject.v on purpose: Adjunction/SAFT.v's
   record [SubobjectIndex] has its own [sub_dom] and [sub_mono], which
   must not shadow the subobject projections used throughout. *)
Require Import Category.Adjunction.SAFT.
Require Import Category.Theory.Subobject.
Require Import Category.Theory.Subobject.Lattice.
Require Import Category.Theory.Subobject.Quotient.
Require Import Category.Construction.Opposite.
Require Import Category.Structure.WellPowered.
Require Import Category.Structure.Generator.
Require Import Category.Structure.Generator.Dual.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Sets.Powerset.
Require Import Category.Instance.Sets.Classifier.OneLevel.
Require Import Category.Instance.CMon.
Require Import Category.Instance.Ab.
Require Import Category.Instance.Ab.Subtract.
Require Import Category.Theory.Algebra.Rig.
Require Import Category.Instance.Rng.
Require Import Category.Instance.Mod.
Require Import Category.Instance.Mod.Quotient.
Require Import Category.Instance.Mod.Spanning.
Require Import Category.Instance.Mod.Representable.

Generalizable All Variables.

(** * R-Mod: well-powered, co-well-powered, and generated by R *)

(* nLab:      https://ncatlab.org/nlab/show/well-powered+category
   nLab:      https://ncatlab.org/nlab/show/generator
   nLab:      https://ncatlab.org/nlab/show/Eilenberg-Watts+theorem
   Wikipedia: https://en.wikipedia.org/wiki/Submodule
   Wikipedia: https://en.wikipedia.org/wiki/Quotient_module

   Mac Lane, "Categories for the Working Mathematician", 2nd ed. (GTM 5),
   §V.8, book p. 130 (PDF p. 139): a category is well-powered when the
   subobjects of each object form a small set, and co-well-powered when
   its quotient objects do.  Watt's theorem, on book p. 131 (PDF p. 140;
   its covariant form is Exercise 3, on p. 132), applies the special
   adjoint functor theorem at (R-Mod)^op and opens with the sentence "Any
   ring R is a generator in the category R-Mod, hence a cogenerator in
   (R-Mod)^op", read from the printed page.  (The in-repo catalog's
   summary for maclane:V.8:thm-watt, doc/plan/books/maclane/inventory/
   V.json, omits "the category".)  At (R-Mod)^op the special adjoint
   functor theorem asks,
   beyond completeness, for a cogenerator and for well-poweredness of
   (R-Mod)^op, which is co-well-poweredness of R-Mod; its covariant use
   (Exercise 3 of the same section) asks for well-poweredness of R-Mod.
   This file supplies those size facts about [RMod R], at the strengths
   the tree allows.  Watt's theorem itself is not stated here, and no
   adjoint functor theorem is applied.

   CONSUMED.  Instance/Mod/Spanning.v's round trip between submodules and
   subobjects ([smod_subobj], [subobj_smod], [smod_subobj_image_equiv],
   #449); Instance/Mod/Quotient.v's [Submodule], [SubmoduleMod],
   [QuotientMod], [mquot_proj] and [mquot_proj_epic]; Instance/Mod.v's
   [rmod_epic_surjective] and [Ring_RMod]; Theory/Subobject/Quotient.v's
   [mk_quot] and [quot_equiv_of_cod_iso]; Theory/Subobject/Lattice.v's
   [sub_le_antisym]; Instance/Mod/Representable.v's [rmod_by_element];
   Structure/Generator.v's [Generator_of_separator] and Structure/
   Generator/Dual.v's [cog_of_gen]; Instance/Sets/Classifier/OneLevel.v's
   [Untruncate] and Instance/Sets/Powerset.v's [Powerset_squash].

   ** WHAT IS BUILT

   (1) [RMod_WellPoweredAt_up W]: [RMod R] is well-powered ONE UNIVERSE UP,
   with nothing assumed.  The index is [Submodule W], whose membership is
   [Type]-valued, and the witness is Spanning.v's round trip with nothing
   added: [wp_to] is [smod_subobj], [wp_from] is [subobj_smod] (the image
   submodule of the mono, its preimage carried as data) and [wp_to_from]
   is [smod_subobj_image_equiv].  It is the module counterpart of
   Instance/Grp/WellPowered.v's [Grp_WellPoweredAt_up].

   (2) [RMod_WellPowered_untruncate U : WellPowered (RMod R)], AT THE PIN,
   under the hypothesis [U : Untruncate].  The index is [PSubmodule W], a
   submodule whose membership is a [Prop].  [wp_to] reads it as a
   [Submodule] ([psm_sub]) and takes the inclusion; [wp_from] is the
   truncated image [pimage] ("has a preimage", as the impredicative
   [Powerset_squash]); the round trip [pim_to_from] composes
   [sub_le_antisym] with [smod_subobj_image_equiv], and it spends [U]
   exactly once, in [pim_fn], to turn a truncated preimage back into a
   carried one.

   (3) [RMod_CoWellPowered_untruncate U : CoWellPowered (RMod R)], AT THE
   PIN, under the same hypothesis, over the same index.  [wp_to] sends [N]
   to the quotient object [pquot N], the projection W -> W/N; [wp_from]
   sends a quotient object to the kernel [pker e] of its epi, whose
   membership is the target's [Prop] mirror of "e x ≈ 0" (every module
   carries [cmon_prop] since the PR "algebraic carriers are sets",
   2026-09-17).  The round trip [cwp_to_from] is [quot_equiv_of_cod_iso] at
   the codomain isomorphism [pre_iso] : cod e ≅ W/ker e, whose forward map
   [pre_map] sends each element of cod e to a preimage under e.  That
   preimage is DATA, and [pre_fn] obtains it by spending [U] on the
   [Prop]-level surjectivity [rmod_epic_surjective] returns.

   (4) [RMod_ring_separates]: R, as a module over itself, separates [RMod R]
   -- two homomorphisms W -> V that agree after every R -> W agree, by
   evaluating at [rmod_by_element], the homomorphism sending 1 to a given
   element.  [RMod_Generator R] packages it as a one-object [Generator],
   and [RModop_Cogenerator R] reads that, through [cog_of_gen], as a
   [Cogenerator] of (RMod R)^op: Watt's opening sentence, quoted above.
   Nothing is assumed.

   (5) [RMod_CoWellPoweredAt_up W]: [RMod R] is co-well-powered ONE
   UNIVERSE UP, with nothing assumed -- the dual of (1), and the
   counterpart of Instance/Sets/WellPowered.v's [Sets_CoWellPoweredAt_up];
   [RMod_CoWellPowered_up] is the family over every W.  The index is the
   quotient objects themselves, read at the carrier level: a codomain
   module Q ([RModObject] at RMod's object instance), a map e : W -> Q and
   [RModPropSurjective e].  [wp_to] rebuilds the epi by Instance/Mod.v's
   [rmod_prop_surjective_epic]; [wp_from] reads a quotient object's epi
   back through [rmod_epic_surjective], whose [Prop]-level answer is all
   the index asks for; the round trip is the identity isomorphism of the
   codomain.  [Epic] quantifies over every object, which puts [QuotObj] at
   the object universe; [RModPropSurjective] quantifies over the carrier
   only, which puts this index at [max(c+1, a)].  No preimage is needed as
   data, so [Untruncate] is not spent.

   ** WHY [Untruncate], MEASURED

   Each refusal below was taken by appending ONE command to a copy of this
   whole file (so under exactly its imports) and compiling it; each has an
   accepted control.  They refuse particular constructions; no
   impossibility is proved (see NOT DELIVERED).

     - The index of (1) sits one universe above the pin.  Offering
       [RMod_WellPoweredAt_up W] where [WellPowered@{o c c o x}
       (RMod@{o x a p c} R)] is expected -- [RMod_WellPowered_untruncate]'s
       binder, without [U] -- is refused, in environment [R : RingObject],
       [W : obj[RMod R]]: "The term "RMod_WellPoweredAt_up W" has type
       "WellPoweredAt@{<1> o o c x} W" while it is expected to have type
       "WellPoweredAt@{c o o c x} W" (universe inconsistency: Cannot enforce
       <1> = c because c < <1>)", <1> a universe the scratch compile
       generated (its serial is not printed, since it moves with every
       edit above the appended command).  Control: the same
       binder with body [fun W => RMod_WellPoweredAt_untruncate U W] is
       accepted.
     - A [Prop]-valued index sits at the pin, but without [U] it cannot
       rebuild the domain of the subobject it names.  [pim_fn] with
       [U _ (`2 p)] replaced by the truncation applied to the identity,
       [(`2 p) _ (fun x => x)], is refused, in environment [R], [W],
       [m : SubObj W], [p], [x]: "The term "x" has type "∃ a : sub_dom m,
       sub_mono m a ≈ `1 (p)" while it is expected to have type "?Q"
       (unable to find a well-typed instantiation for "?Q": cannot ensure
       that "Type" is a subtype of "Prop")".  That is the refusal Instance/
       Sets/WellPowered.v quotes for [Sets], up to names.  The [PropEquiv]
       field regime does not change it: [pequiv_to] turns a [Prop] into
       `≈`, not into an element of [sub_dom m].  A module mono is injective,
       so the preimage is unique, but uniqueness is not data.
     - The co-well-powered side needs a preimage under an EPI as data, and
       [rmod_epic_surjective] returns only [RModPropSurjective], an [ex] in
       [Prop] -- since #1320 the coset relation of its test object is a
       [Prop], and Instance/Mod.v's comment above [RModPropSurjective]
       records that the witness may no longer be read back out.  [pre_fn]
       written as a [match] on that [ex], without [U], is refused, in
       environment [R], [W], [u : QuotObj W], [q]: "Incorrect elimination of
       "rmod_epic_surjective (quot_epi u) (quot_is_epic u) q" in the
       inductive type "ex": the return type has sort "Type" while it should
       be SProp or Prop."  The obstacle belongs to the KERNEL index: a
       kernel names its quotient only through the codomain isomorphism
       cod e ≅ W/ker e, whose forward map sends cod e into W's own carrier
       (the carrier of W/N is W's, Instance/Mod/Quotient.v's
       [QuotientMod]) -- the function [pre_fn] builds.  An index other
       than the kernel avoids it: (5) indexes each quotient object by
       ITSELF -- its codomain module, the map into it and that map's
       [Prop]-level surjectivity -- rebuilds nothing from a kernel, and is
       co-well-poweredness one universe up with NO hypothesis, at
       [c < w] and [a <= w] ([c < w] alone at [RingObject@{c c c}]), well
       below the object universe.  [U] is spent on reaching the PIN, where
       of these two indexes only the kernel one fits.
     - The index of (5) sits one universe above the pin, as (1)'s does.
       Offering [RMod_CoWellPoweredAt_up W] where
       [CoWellPowered@{o c c o x} (RMod@{o x a p c} R)] is expected --
       [RMod_CoWellPowered_untruncate]'s binder, without [U] -- is
       refused, in environment
       [R : RingObject], [W : obj[(RMod R)^op]]: "The term
       "RMod_CoWellPoweredAt_up W" has type "WellPoweredAt@{<1> <2> <2> c
       <3>} W" while it is expected to have type "WellPoweredAt@{c o o c x}
       W" (universe inconsistency: Cannot enforce <1> = c because c <
       <1>)", <1>, <2> and <3> being universes the scratch compile
       generated.  Control: the same binder with a [U : Untruncate]
       argument and body [fun W => RMod_CoWellPoweredAt_untruncate U W] is
       accepted.  [CoWellPowered] itself demands [w <= h], so the one-up
       family (5) is stated in [WellPoweredAt]'s form, not as a
       [CoWellPowered].

   ** THE RING AS A MODULE: ITS THREE UNIVERSES COINCIDE

   (4) holds at [RingObject@{c c c}] only, and that is forced by
   Instance/Mod.v's [Ring_RMod] as it is typed, not shown to be forced
   otherwise.  Appending
   [Definition ring_obj@{a c p o x | Set < o, c < o, c < x, p <= a, c <= a,
   a <= o} (R : RingObject@{a c p}) : obj[RMod@{o x a p c} R] := Ring_RMod
   R] to a copy of this file is refused with "Universe constraints are not
   implied by the ones declared: a < o a < x a <= compose.u0 a <= compose.u1
   a <= compose.u2 a <= ID.u0 a = c a = p"; at [RingObject@{c c c}] the same
   definition asks only for the four stdlib bounds [c <= compose.u0],
   [c <= compose.u1], [c <= compose.u2], [c <= ID.u0].  The equations come
   from Instance/Mod.v's [Ring_RMod], whose abelian group is R's own
   [ring_ab R] at R's universes, while an object of [RMod@{o x a p c} R]
   carries its abelian group at [AbObject@{c c c}] (measured by [Check] on
   [rm_ab W]).  A copy of R's abelian group re-typed at the carrier universe
   was not attempted.  [Int_Ring] meets the restriction: [About] reads
   [Int_Ring@{o p q} : RingObject@{q o p}] with only [o <= q] and
   [p <= q], so [Int_Ring@{c c c}] is expressible.

   ** STRENGTHS

   Every comparison is `≈` in the subobject or quotient-object setoid, an
   isomorphism of domains (codomains) over [W]; nothing is Leibniz.  13
   [Defined] and 4 [Qed], counted by token outside comments.  Flipping
   each [Defined] to [Qed] in a copy of the whole file, seven are
   load-bearing -- [pimage], [pker] (their memberships must reduce),
   [pim_to_tim], [tim_to_pim], [pre_map], [ev_map] and [pre_iso] (a later
   proof computes with them) -- and six recompile: [pim_le], [pim_ge],
   [pim_to_from], [cwp_to_from], kept transparent because `≈` on
   subobjects and quotient objects is an isomorphism, which is data,
   [squash_of_ex], and (5)'s [RMod_CoWellPoweredAt_up], kept transparent
   because it is a [WellPoweredAt] record, which is data.  The four [Qed]s are
   [pre_spec], [rel_of_image], [image_of_rel] and [RMod_ring_separates].

   ** UNIVERSES, MEASURED

   By [About] under [Set Printing Universes], stdlib bounds ([compose.u0],
   [Projections.u0], [prod_rect.u0], [ID.u0], ...) left out.
   [RMod@{o x a p c} : RingObject@{a c p} → Category@{o c c}] names the
   ring's (auxiliary, carrier, proof) universes and [RMod]'s object and
   second universe; the hom universe is the carrier [c], and every block
   below also carries [RMod]'s own [Set < o], [c < o], [c < x], [c <= a],
   [p <= a], [a <= o].  Every top-level binder names the ring's, RMod's
   and the index universes; several constants read back further
   universes, the co-well-powered ones among them (below).

     RMod_WellPoweredAt_up@{a c p o x w} :
       ∀ {R : RingObject@{a c p}} (W : obj[RMod@{o x a p c} R]),
       WellPoweredAt@{w o o c x} W            (* c < w *)
     PSubmodule@{a c p m0 m1 m2 m3 m4} :
       RModObject@{m0 m1 m2 m3 m4 a c p} R → Type@{max(Set+1,m3)}
     RMod_WellPowered_untruncate@{a c p o x} :
       Untruncate@{c} → WellPowered@{o c c o x} (RMod@{o x a p c} R)
                                              (* Set < c *)
     RMod_CoWellPowered_untruncate@{a c p o x u u0} :
       Untruncate@{c} → CoWellPowered@{o c c o x} (RMod@{o x a p c} R)
                                              (* Set < c *)
     RMod_ring_separates@{c o x} :
       ∀ {R : RingObject@{c c c}}, IsSeparator@{o o c} (Ring_RMod R)
     RMod_Generator@{c o x u} :
       ∀ R, Generator@{u o c} (RMod@{o x c c c} R)
     RModop_Cogenerator@{c o x u} :
       ∀ R, Cogenerator@{u o c} ((RMod@{o x c c c} R)^op)
     RMod_CoWellPoweredAt_up@{a c p o x w u} :
       ∀ {R : RingObject@{a c p}} (W : obj[RMod@{o x a p c} R]),
       WellPoweredAt@{w o o c x} W          (* in (RMod R)^op;
                                c < w, a <= w, Set < w, u <= w *)
     RMod_CoWellPowered_up@{a c p o x w u} : the same, as a family over W

   The universes these four readbacks show beyond the named ones: (3)'s
   [RMod_CoWellPoweredAt_untruncate] and [RMod_CoWellPowered_untruncate]
   carry [u] and [u0], which occur in their bodies only and in no
   constraint at all -- [u] is the membership universe of the
   [Submodule] that [psm_sub] makes inside [pquot], [u0] one of
   [cwp_to_from]'s own -- and (5)'s two constants carry [u],
   [RModPropSurjective]'s own sort (that definition is declared at
   [Type]), bounded only by [u <= w].  Their binders stay extensible.
   Closing (3)'s at [@{a c p o x | …}] is refused, "Universes … are
   unbound", naming the two body universes, and naming them would take
   explicit instances of this file's extensible [pquot] and
   [cwp_to_from].  A closed binder for (5), even with [RModPropSurjective]
   unfolded into its [Prop] so that no sort is left over, is refused the
   same way, the instances of [rmod_prop_surjective_epic] and
   [rmod_epic_surjective] in the body being unbound.  At
   [RingObject@{c c c}], (5) reads back [c < w] with no [a] left to bound
   (measured on [cwp_up_ccc], a scratch copy's appended alias).

   [WellPoweredAt]'s first slot is the index universe, its fourth the hom
   universe and its fifth the second universe of the subobject setoid, so
   (1) has its index strictly above the homs with no equation, and (2) and
   (3) have it equal to them.  Naming (1)'s fifth slot [w] instead adds
   the equation [x = w] (measured by [About]); the slot is [x], which is
   what [WellPowered]'s pinned [t] reads at [RMod].  The [Set < c] of (2)
   and (3) is the cost of the [Prop]-valued index: [PSubmodule] lives at
   [max(Set+1, carrier)], the same cost as Instance/Sets/WellPowered.v's
   [Sets_WellPowered_untruncate], and it excludes rings whose carrier
   universe is [Set].  (1) and (4) carry no [Set] bound; (5) carries
   [Set < w] only, which [c < w] already implies.

   ** NON-VACUITY

   (1) and (5) hold at every ring and (4) at every ring whose three
   universes coincide, [Int_Ring@{c c c}] among them; (2) and (3) inherit
   [Untruncate], which has no in-tree inhabitant (Instance/Fun/Topos.v's
   header; [untruncate_of_IEM] derives it from informative excluded
   middle), so they are conditionals and nothing here witnesses their
   hypothesis.

   ** AXIOMS AND MEASUREMENTS

   [Print Module] lists 37 names (35 constants, field projections
   included, the record [PSubmodule] and its constructor; 35 and 33
   before (5) was added); every one
   reports "Closed under the global context" under [Print Assumptions] by
   its fully qualified name.  No [Program] obligation exists: [Print
   Module] lists none, and [strings] on the .vo finds no [_obligation_]
   name of this module.  Imports: Adjunction/SAFT.v (for [Cogenerator]) is
   imported BEFORE Theory/Subobject.v on purpose, since its record
   [SubobjectIndex] has fields [sub_dom] and [sub_mono] of its own, which
   would otherwise shadow the subobject projections.

   ** NOT DELIVERED

   [RMod R] well-powered or co-well-powered at the pin WITHOUT a
   hypothesis: no construction, and no impossibility proof (one universe
   up both hold with none, (1) and (5); the special adjoint functor
   theorem consumes them at the pin).  No [Ab] analogue is stated.  No
   application of Structure/WellPowered.v's intersection theorem at
   [RMod R].  No cogenerator of [RMod R] itself here (the module
   hom_ℤ(R, ℚ/ℤ) of Mac Lane's Exercise 2(b) is Instance/Mod/
   Cogenerator.v's, conditional on the book's premise, beside that file's
   unconditional but large [RMod_Cogenerator_large]).  (4) only at
   [RingObject@{c c c}].  No [Instance] is registered. *)

(** ** 1. Well-powered one universe up, unconditionally *)

(* Instance/Mod/Spanning.v's round trip between submodules and
   subobjects IS a [WellPoweredAt]; nothing is added. *)
Definition RMod_WellPoweredAt_up@{a c p o x w +| c < w +}
  {R : RingObject@{a c p}} (W : obj[RMod@{o x a p c} R]) :
  WellPoweredAt@{w o o c x} W :=
  {| wp_index   := Submodule W;
     wp_to      := smod_subobj;
     wp_from    := subobj_smod;
     wp_to_from := smod_subobj_image_equiv |}.

(** ** 2. [Prop]-valued submodules *)

(* The index at the pin: a submodule whose membership is a [Prop].  It
   sits at the carrier universe, where [Submodule]'s [Type]-valued
   membership sits one above. *)
Record PSubmodule@{a c p m0 m1 m2 m3 m4}
  {R : RingObject@{a c p}} (M : RModObject@{m0 m1 m2 m3 m4 a c p} R) := {
  psm_mem : carrier (cmon_setoid M) → Prop;
  psm_resp : ∀ a b : carrier (cmon_setoid M), a ≈ b → psm_mem a → psm_mem b;
  psm_zero : psm_mem (cmon_zero M);
  psm_plus : ∀ a b, psm_mem a → psm_mem b → psm_mem (cmon_plus M a b);
  psm_smul : ∀ (r : carrier (rig_setoid (ring_rig R))) a,
      psm_mem a → psm_mem (rm_smul M r a)
}.

Arguments psm_mem {R M} _ _.
Arguments psm_resp {R M} _ _ _ _ _.
Arguments psm_zero {R M} _.
Arguments psm_plus {R M} _ _ _ _ _.
Arguments psm_smul {R M} _ _ _ _.

(* A [Prop] submodule read as a [Submodule]: [Prop] is a [Type]. *)
Definition psm_sub@{a c p o x +}
  {R : RingObject@{a c p}} {M : obj[RMod@{o x a p c} R]} (P : PSubmodule M) :
  Submodule M :=
  {| smod_mem  := fun a => psm_mem P a;
     smod_resp := psm_resp P;
     smod_zero := psm_zero P;
     smod_plus := psm_plus P;
     smod_smul := psm_smul P |}.

(* The image of a homomorphism, truncated: "has a preimage" as the
   impredicative [Powerset_squash] of Instance/Sets/Powerset.v. *)
Definition pimage@{a c p o x +}
  {R : RingObject@{a c p}} {M N : obj[RMod@{o x a p c} R]}
  (f : M ~{RMod@{o x a p c} R}~> N) : PSubmodule N.
Proof.
  unshelve refine {| psm_mem := fun b => Powerset_squash
        { a : carrier (cmon_setoid M) & cmon_map (rm_hom f) a ≈ b } |}.
  - intros a b Hab H Q k. apply H. intros [x Hx]. apply k.
    exists x. exact (Equivalence_Transitive _ _ _ Hx Hab).
  - intros Q k; apply k; exists (cmon_zero M);
      exact (cmon_map_zero (rm_hom f)).
  - intros a b Ha Hb Q k. apply Ha; intros [x Hx]. apply Hb; intros [y Hy].
    apply k. exists (cmon_plus M x y).
    rewrite (cmon_map_plus (rm_hom f)). now rewrite Hx, Hy.
  - intros r a Ha Q k. apply Ha; intros [x Hx]; apply k.
    exists (rm_smul M r x). rewrite (rm_map_smul f). now rewrite Hx.
Defined.

(** ** 3. Well-powered at the pin, under [Untruncate] *)

Section Untrunc.

Universes a c p o x.
Constraint Set < c, c < o, c < x, p <= a, c <= a, a <= o.

Context {R : RingObject@{a c p}} (U : Untruncate@{c})
        {W : obj[RMod@{o x a p c} R]} (m : @SubObj (RMod@{o x a p c} R) W).

(* The one place [Untruncate] is spent: the truncated preimage becomes
   the carried one. *)
Definition pim_fn (p : smod_carrier (psm_sub (pimage (sub_mono m)))) :
  smod_carrier (subobj_smod m) :=
  existT (fun b => smod_mem (subobj_smod m) b) (`1 p) (U _ (`2 p)).

Definition tim_fn (p : smod_carrier (subobj_smod m)) :
  smod_carrier (psm_sub (pimage (sub_mono m))) :=
  existT (fun b => smod_mem (psm_sub (pimage (sub_mono m))) b) (`1 p)
         (Powerset_squash_intro (`2 p)).

Definition pim_to_tim :
  RModHom (SubmoduleMod (psm_sub (pimage (sub_mono m))))
          (SubmoduleMod (subobj_smod m)).
Proof using R U W m.
  unshelve econstructor; [unshelve econstructor; [unshelve econstructor|..]|].
  - exact pim_fn.
  - intros p q H; exact H.
  - simpl; reflexivity.
  - intros a b; simpl; reflexivity.
  - intros r a; simpl; reflexivity.
Defined.

Definition tim_to_pim :
  RModHom (SubmoduleMod (subobj_smod m))
          (SubmoduleMod (psm_sub (pimage (sub_mono m)))).
Proof.
  unshelve econstructor; [unshelve econstructor; [unshelve econstructor|..]|].
  - exact tim_fn.
  - intros p q H; exact H.
  - simpl; reflexivity.
  - intros a b; simpl; reflexivity.
  - intros r a; simpl; reflexivity.
Defined.

Definition pim_le :
  sub_le (smod_subobj (psm_sub (pimage (sub_mono m))))
         (smod_subobj (subobj_smod m)).
Proof using R U W m. exists pim_to_tim. intro p; simpl; reflexivity. Defined.

Definition pim_ge :
  sub_le (smod_subobj (subobj_smod m))
         (smod_subobj (psm_sub (pimage (sub_mono m)))).
Proof. exists tim_to_pim. intro p; simpl; reflexivity. Defined.

Definition pim_to_from :
  smod_subobj (psm_sub (pimage (sub_mono m))) ≈ m.
Proof using R U W m.
  etransitivity.
  - apply sub_le_antisym; [exact pim_le | exact pim_ge].
  - exact (smod_subobj_image_equiv m).
Defined.

End Untrunc.

Definition RMod_WellPoweredAt_untruncate@{a c p o x +|
    Set < c, c < o, c < x, p <= a, c <= a, a <= o +}
  {R : RingObject@{a c p}} (U : Untruncate@{c}) (W : obj[RMod@{o x a p c} R]) :
  WellPoweredAt@{c o o c x} W :=
  {| wp_index   := PSubmodule W;
     wp_to      := fun P => smod_subobj (psm_sub P);
     wp_from    := fun m => pimage (sub_mono m);
     wp_to_from := pim_to_from U |}.

Definition RMod_WellPowered_untruncate@{a c p o x +|
    Set < c, c < o, c < x, p <= a, c <= a, a <= o +}
  {R : RingObject@{a c p}} (U : Untruncate@{c}) :
  WellPowered@{o c c o x} (RMod@{o x a p c} R) :=
  fun W => RMod_WellPoweredAt_untruncate U W.

(** ** 4. Co-well-powered at the pin, under [Untruncate] *)

(* The kernel of a homomorphism as a [Prop] submodule: membership is the
   target's [Prop] mirror of "e x ≈ 0" ([cmon_prop], a field of every
   module since the PR "algebraic carriers are sets", 2026-09-17). *)
Definition pker@{a c p o x +}
  {R : RingObject@{a c p}} {W Q : obj[RMod@{o x a p c} R]}
  (e : W ~{RMod@{o x a p c} R}~> Q) : PSubmodule W.
Proof.
  unshelve refine {| psm_mem := fun x =>
     @pequiv _ _ (cmon_prop Q) (cmon_map (rm_hom e) x) (cmon_zero Q) |}.
  - intros a b Hab Ha. apply pequiv_from.
    rewrite <- Hab. exact (pequiv_to _ _ Ha).
  - apply pequiv_from. exact (cmon_map_zero (rm_hom e)).
  - intros a b Ha Hb. apply pequiv_from.
    rewrite (cmon_map_plus (rm_hom e)).
    rewrite (pequiv_to _ _ Ha), (pequiv_to _ _ Hb). apply cmon_plus_zero_l.
  - intros r a Ha. apply pequiv_from. rewrite (rm_map_smul e).
    rewrite (pequiv_to _ _ Ha). apply rm_smul_zero_r.
Defined.

(* The quotient object a [Prop] submodule names: the projection onto the
   quotient module, epic by Instance/Mod/Quotient.v's [mquot_proj_epic]. *)
Definition pquot@{a c p o x +}
  {R : RingObject@{a c p}} {W : obj[RMod@{o x a p c} R]}
  (N : PSubmodule W) : @QuotObj (RMod@{o x a p c} R) W :=
  mk_quot (mquot_proj (psm_sub N)) (mquot_proj_epic (psm_sub N)).

(* An existential in [Prop] read as an impredicative truncation. *)
Definition squash_of_ex@{c +} {A : Type@{c}} {P : A → Prop} :
  (exists a, P a)%type → Powerset_squash@{c} { a : A & P a }.
Proof. intros [a Ha] Qp k. exact (k (existT _ a Ha)). Defined.

Section CoUntrunc.

Universes a c p o x.
Constraint Set < c, c < o, c < x, p <= a, c <= a, a <= o.

Context {R : RingObject@{a c p}} (U : Untruncate@{c})
        {W : obj[RMod@{o x a p c} R]} (u : @QuotObj (RMod@{o x a p c} R) W).

Let Q := quot_cod u.
Let e : W ~{RMod R}~> Q := quot_epi u.
Let S := psm_sub (pker e).

(* The one place [Untruncate] is spent: a preimage under the epi, chosen
   from the [Prop]-level surjectivity of Instance/Mod.v's
   [rmod_epic_surjective]. *)
Definition pre_fn (q : carrier (cmon_setoid Q)) : carrier (cmon_setoid W) :=
  `1 (U _ (squash_of_ex (rmod_epic_surjective e (quot_is_epic u) q))).

Lemma pre_spec (q : carrier (cmon_setoid Q)) :
  cmon_map (rm_hom e) (pre_fn q) ≈ q.
Proof using R U W u.
  unfold pre_fn.
  destruct (U _ _) as [a Ha]; simpl. exact (pequiv_to _ _ Ha).
Qed.

(* x ~ y in W/ker e as soon as e x ≈ e y, and conversely. *)
Lemma rel_of_image (x y : carrier (cmon_setoid W)) :
  cmon_map (rm_hom e) x ≈ cmon_map (rm_hom e) y → mquot_rel S x y.
Proof using R W u.
  intro H. constructor. simpl. apply pequiv_from.
  rewrite (ab_map_sub (rm_hom e)). exact (snd (ab_sub_eq_zero_iff _ _ _) H).
Qed.

Lemma image_of_rel (x y : carrier (cmon_setoid W)) :
  mquot_rel S x y → cmon_map (rm_hom e) x ≈ cmon_map (rm_hom e) y.
Proof using R W u.
  intro H. apply pequiv_to. destruct H as [K]. apply pequiv_from.
  simpl in K. apply (pequiv_to _ _) in K.
  rewrite (ab_map_sub (rm_hom e)) in K.
  exact (fst (ab_sub_eq_zero_iff _ _ _) K).
Qed.

Definition pre_map : Q ~{RMod R}~> QuotientMod S.
Proof using R U W u.
  unshelve econstructor; [unshelve econstructor; [unshelve econstructor|..]|].
  - exact pre_fn.
  - intros q q' H. apply rel_of_image. now rewrite !pre_spec.
  - apply rel_of_image. rewrite pre_spec. symmetry.
    exact (cmon_map_zero (rm_hom e)).
  - intros a b. apply rel_of_image. simpl.
    rewrite (cmon_map_plus (rm_hom e)), !pre_spec. reflexivity.
  - intros r a. apply rel_of_image. simpl.
    rewrite (rm_map_smul e), !pre_spec. reflexivity.
Defined.

Definition ev_map : QuotientMod S ~{RMod R}~> Q.
Proof using R W u.
  unshelve econstructor; [unshelve econstructor; [unshelve econstructor|..]|].
  - exact (cmon_map (rm_hom e)).
  - intros x y H. exact (image_of_rel x y H).
  - exact (cmon_map_zero (rm_hom e)).
  - intros a b. exact (cmon_map_plus (rm_hom e) a b).
  - intros r a. exact (rm_map_smul e r a).
Defined.

Definition pre_iso : Q ≅[RMod R] QuotientMod S.
Proof using R U W u.
  unshelve econstructor.
  - exact pre_map.
  - exact ev_map.
  - intro x. apply rel_of_image. simpl. apply pre_spec.
  - intro q. simpl. apply pre_spec.
Defined.

Definition cwp_to_from : pquot (pker e) ≈ u.
Proof using R U W u.
  apply (quot_equiv_of_cod_iso (pquot (pker e)) u pre_iso).
  intro x. apply rel_of_image. simpl. apply pre_spec.
Defined.

End CoUntrunc.

Definition RMod_CoWellPoweredAt_untruncate@{a c p o x +|
    Set < c, c < o, c < x, p <= a, c <= a, a <= o +}
  {R : RingObject@{a c p}} (U : Untruncate@{c}) (W : obj[RMod@{o x a p c} R]) :
  @WellPoweredAt@{c o o c x} ((RMod@{o x a p c} R)^op) W :=
  {| wp_index   := PSubmodule W;
     wp_to      := pquot;
     wp_from    := fun u => pker (quot_epi u);
     wp_to_from := cwp_to_from U |}.

Definition RMod_CoWellPowered_untruncate@{a c p o x +|
    Set < c, c < o, c < x, p <= a, c <= a, a <= o +}
  {R : RingObject@{a c p}} (U : Untruncate@{c}) :
  CoWellPowered@{o c c o x} (RMod@{o x a p c} R) :=
  fun W => RMod_CoWellPoweredAt_untruncate U W.

(** ** 5. R is a generator of R-Mod *)

(* Two homomorphisms that agree after every [R ⟶ W] agree: evaluate at
   the homomorphism sending 1 to the element (Instance/Mod/
   Representable.v's [rmod_by_element]). *)
Lemma RMod_ring_separates@{c o x +| Set < o, c < o, c < x +}
  {R : RingObject@{c c c}} :
  @IsSeparator (RMod@{o x c c c} R) (Ring_RMod R).
Proof.
  intros x y f g Hk m.
  pose proof (Hk (rmod_by_element R x m) (rig_one (ring_rig R))) as H.
  simpl in H.
  rewrite (rm_smul_one x m) in H. exact H.
Qed.

Definition RMod_Generator@{c o x +| Set < o, c < o, c < x +}
  (R : RingObject@{c c c}) : Generator (RMod@{o x c c c} R) :=
  @Generator_of_separator (RMod R) (Ring_RMod R) RMod_ring_separates.

Definition RModop_Cogenerator@{c o x +| Set < o, c < o, c < x +}
  (R : RingObject@{c c c}) : Cogenerator ((RMod@{o x c c c} R)^op) :=
  cog_of_gen (RMod_Generator R).

(** ** 6. Co-well-powered one universe up, unconditionally *)

(* A quotient object indexed by ITSELF, read at the carrier level: its
   codomain module, the map into it, and that map's [Prop]-level
   surjectivity.  [Epic] quantifies over every object of [RMod R], which is
   why [QuotObj] sits at the object universe; [RModPropSurjective]
   quantifies over the carrier only.  Nothing is rebuilt from a kernel, so
   no preimage is needed as data and [Untruncate] is not spent; the
   round trip is the identity isomorphism of the codomain. *)
Definition RMod_CoWellPoweredAt_up@{a c p o x w +| c < w, a <= w +}
  {R : RingObject@{a c p}} (W : obj[RMod@{o x a p c} R]) :
  @WellPoweredAt@{w o o c x} ((RMod@{o x a p c} R)^op) W.
Proof.
  unshelve refine {|
    wp_index := { Q : RModObject@{c a c c c a c p} R
                & { e : W ~{RMod@{o x a p c} R}~> Q & RModPropSurjective e } };
    wp_to := fun i => @mk_quot (RMod@{o x a p c} R) W (`1 i) (`1 (`2 i))
                        (rmod_prop_surjective_epic _ (`2 (`2 i)));
    wp_from := fun u => existT _ (quot_cod u)
                 (existT _ (quot_epi u)
                    (rmod_epic_surjective _ (quot_is_epic u))) |}.
  intro u. exists iso_id. simpl. cat.
Defined.

(* The family, in [CoWellPowered]'s shape but one universe up, which
   [CoWellPowered]'s own [w <= h] rules out. *)
Definition RMod_CoWellPowered_up@{a c p o x w +| c < w, a <= w +}
  {R : RingObject@{a c p}} :
  ∀ W : obj[RMod@{o x a p c} R],
    @WellPoweredAt@{w o o c x} ((RMod@{o x a p c} R)^op) W :=
  fun W => RMod_CoWellPoweredAt_up W.
