Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Adjunction.
Require Import Category.Structure.Complete.
Require Import Category.Adjunction.GAFT.
Require Import Category.Construction.Comma.Creation.
Require Import Category.Theory.Monad.
Require Import Category.Monad.Comparison.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Natural.Transformation.
Require Import Category.Instance.Fun.
Require Import Category.Functor.Hom.
Require Import Category.Functor.Representable.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Grp.
Require Import Category.Instance.Grp.Free.
Require Import Category.Instance.Grp.Limit.

Generalizable All Variables.

(** * The free group functor, read through the adjoint functor theorem *)

(* nLab: https://ncatlab.org/nlab/show/adjoint+functor+theorem
   nLab: https://ncatlab.org/nlab/show/free+group

   Mac Lane §V.6, book p. 124.  Freyd's theorem produces a left adjoint to
   the underlying-set functor of groups, the solution set being the
   subgroups generated by the image.

   ** READ THIS BEFORE READING ANYTHING ELSE

   THE FREE GROUP FUNCTOR IS NOT CONSTRUCTED HERE, AND NOTHING BELOW IS
   AN INDEPENDENT PROOF THAT IT EXISTS.  It is constructed in
   Instance/Grp/Free.v, which builds it from words and proves
   [free_group_adjunction : FreeGrp ⊣ Grp_Forget] (:435, :438).

   Issue #442's survey of the tree is false in SEVEN places, each checked
   here against a green build on 2026-09-12:

   1. "The category of groups is not in-tree" — [Grp], Instance/Grp.v.
   2. "neither the forgetful functor ... exists" — [Grp_Forget], same file.
   3. "...nor its free object exists" — [FreeGrp], Instance/Grp/Free.v:435.
   4. The adjunction the issue asks to produce — [free_group_adjunction],
      Instance/Grp/Free.v:438, delivered by #298.
   5. GAFT's first hypothesis — [Grp_Complete], Instance/Grp/Limit.v:691.
   6. GAFT's second — [Grp_Forget_continuous], Instance/Grp/Limit.v:699.
   7. The Riehl §4.7 section's "NO concrete solution set is exhibited
      anywhere in the tree, so the whole GAFT development is currently
      uninhabited at its distinctive premise" — [Sets_Id_SolutionSet],
      Adjunction/GAFT/Sets.v:140, hand-built with all four parameters
      written out and fed to GAFT at :160.  That same application also
      refutes the "Current state" line that the only worked GAFT
      application is `Δ ⊣ (×)`.

   None of the seven is established here — each was already in tree when
   this file was started, which is the whole difficulty.  What is NOT
   false is the issue's requirement, which is why this file exists.

   What this file does is VERIFY THAT FREYD'S THEOREM APPLIES at this
   instance and that its output is the functor already in tree.  That is
   worth having — it is the §V.6 statement instantiated where the book
   instantiates it — but it must not be mistaken for the construction,
   and the reason is the next paragraph.

   ** THE SOLUTION SET USED HERE IS CIRCULAR, AND SAYING SO IS THE POINT

   GAFT's third hypothesis is a solution set for each set [X].  The one
   fed to it below, [Grp_Forget_solution_set_from_adjunction], is
   [solution_set_of_adjunction] applied to [free_group_adjunction] — the
   singleton family at the unit of THE VERY ADJUNCTION THE THEOREM IS
   MEANT TO PRODUCE.  So [free_group_via_GAFT] is a genuine application
   of a genuine theorem, and it is worthless as an existence proof: strip
   [Instance/Grp/Free.v] and nothing here survives.  The same disclosure,
   for the same reason, is what Adjunction/GAFT/Sets.v's header makes
   about its own instance.

   ** WHY MAC LANE'S OWN SOLUTION SET IS NOT USED

   His is the family of subgroups generated by the image of [X], cut down
   by a cardinality bound.  Two things stand in the way, and the second one
   is where an earlier revision of this header was WRONG.

   First, the generated-subgroup API does not exist: nothing over
   Instance/Grp.v's [GrpObject] forms the subgroup generated by a subset.
   Instance/Grp/Abelianization.v:119's [InCommutator] is the exact
   template — a `≈`-saturated inductive closure — and
   Instance/Grp/Quotient.v:202's [SubgroupGrp] is what it would feed.
   That is ordinary work, and it is the real remaining obstacle.

   Second, a universe artifact.  In the tree as it stands, Mac Lane's
   literal index IS refused: feeding [GAFT Grp_Forget Grp_Complete
   (Continuous_PreservesImageLimit Grp_Forget_continuous)] a [SolutionSet]
   whose [sol_index] is [Subgroup Gfix] is rejected with the expected type
   printed literally as [SolutionSet@{Set …}], and [Subgroup G]
   (Instance/Grp/Quotient.v:156) is never at [Set].
   Test/ProbeGrpFreeAFT442.v's N5 pins exactly that, with a paired control
   at a [Set]-level index that IS accepted.

   An earlier revision of this header said the pin was GAFT's and that
   relaxing it meant editing a [Qed]-opaque theorem with [eq_refl]
   readbacks hanging off its term, so that it "belongs to that file's own
   issue".  Measured on 2026-09-12, that names the wrong file and the wrong
   cost.  The [Set] is a universe-MINIMIZATION artifact of
   Instance/Discrete.v:59's [DiscreteCat_Functor], which carries no
   universe binders and so elaborates with the source shape's hom AND proof
   at the literal [Set]:

     DiscreteCat_Functor@{u u0 u1 u2} :
       ∀ {A : Type@{u}} {C : Category@{u0 u2 u2}},
         (A → obj[C]) → DiscreteCat@{u Set Set} A ⟶ C

   even though [DiscreteCat@{o h p}] itself is fully polymorphic.  GAFT's
   proof takes a limit over [DiscreteCat_Functor (wif_obj W)] (GAFT.v:249)
   and [Complete] identifies the shape's hom with the ambient's, so the
   [Set] lands in GAFT's own statement and any real [Complete] then squeezes
   the index onto it.  [Grp_Complete] and [Grp_Forget_continuous] transmit
   the pin; neither creates it.  The tree already recorded this about the
   same donor: Instance/Cat/Objects.v:112-128 quotes that signature and says
   "the pin is NOT claimed unavoidable -- it is a minimization artifact",
   and :373's [disc_ext@{o h p q}] is the same construction with the binders
   written out, [Set]-free.

   So the repair is three lines in Instance/Discrete.v and touches no
   [Qed]-opaque term:

     Program Definition DiscreteCat_Functor@{o h p co ch cp +}
       {A : Type@{o}} {C : Category@{co ch cp}} (f : A → C) :
       DiscreteCat@{o h p} A ⟶ C := …

   (the [+] is what makes this possible, and it also corrects
   Instance/Cat/Objects.v:371's remark that "a [Program Definition] cannot
   be annotated here at all, since its obligations mint fresh universes" —
   that is why [disc_ext] was written with [refine]).  Measured in a full
   copy of this worktree, Rocq 9.1.1, with that edit and NOTHING else —
   Adjunction/GAFT.v, Instance/Grp/Limit.v and Instance/Grp/Quotient.v
   byte-identical: the [Subgroup Gfix] solution set is ACCEPTED, and a
   whole-tree [make -k -j8] over the 977-file build set produces exactly
   eleven errors, every one of them the same one: a negative probe whose
   guarded command is now accepted, so its refutation no longer triggers.
   They are at Instance/Cat/Objects.v:747, Structure/Limit/Components.v:1166
   and nine Test/Probe* lines, this file's own N5 among them.  ZERO proofs
   break — there is not one type error or universe inconsistency in the
   eleven.

   That is why the change is not made here.  It is not an obstruction, it
   is bookkeeping against eleven recorded boundaries in eleven files, and
   re-measuring those is a donor-wide decision belonging to
   Instance/Discrete.v, not to this issue.  It is filed as #1309, together
   with the generated-subgroup API and the non-circular solution set they
   would jointly make possible.

   ** What is therefore delivered

   Five things, of which only the first is compromised by the circularity
   section above.

   1. The AFT application at this instance, [free_group_via_GAFT], with the
      circularity of its solution set disclosed at every use site.
   2. The issue's QA-correction clause: #298 landed the word-model free
      group first, so this file owes the proof that the two agree.
      [free_group_via_GAFT_agrees] is it, at `≈` — left adjoints to a fixed
      functor are isomorphic.
   3. The Awodey §7.2 clause, [Grp_Forget_Representable].  Nothing in the
      tree represented [Grp_Forget] before this file; the three mentions of
      [Representable] under Instance/Grp/ that predate it
      (Quotient.v:538, EckmannHilton.v:388, Abelianize.v:238) are all
      disclaimers.
   4. The Riehl §5.1 clause: the induced monad, with its unit and
      multiplication recorded at [eq_refl] and its carrier pinned to
      [FGWord].
   5. Mac Lane's injectivity clause for the universal arrow, in the general
      embedding form and in the two-element-group form the book gives,
      the latter carrying the decision procedure that form genuinely needs.

   Items 2-5 do not depend on the AFT application at all, and none of them
   is circular. *)

(** ** The solution set, and the application *)

(* Circular, as the header says.  It is named so that the circularity is
   visible at every use site rather than buried in a term. *)
Definition Grp_Forget_solution_set_from_adjunction (X : Sets) :
  SolutionSet Grp_Forget X :=
  solution_set_of_adjunction free_group_adjunction X.

Definition free_group_via_GAFT : ∃ F : Sets ⟶ Grp, F ⊣ Grp_Forget :=
  GAFT Grp_Forget Grp_Complete
       (Continuous_PreservesImageLimit Grp_Forget_continuous)
       Grp_Forget_solution_set_from_adjunction.

(* The issue's QA clause: the theorem's output is the functor the tree
   already has.  Left adjoints to a fixed functor are isomorphic, so this
   is [left_adjoint_iso] (Theory/Adjunction.v:407) and not a computation
   — the two terms are very different, and only `≈` is claimed. *)
Definition free_group_via_GAFT_agrees : `1 free_group_via_GAFT ≈ FreeGrp :=
  left_adjoint_iso Grp_Forget _ FreeGrp (`2 free_group_via_GAFT)
                   free_group_adjunction.

(** ** Riehl §5.1: the induced monad on Sets *)

Definition free_group_monad : @Monad Sets (Grp_Forget ◯ FreeGrp) :=
  Adjunction_Induced_Monad free_group_adjunction.

(* Riehl's clause asks for the unit and multiplication to be RECORDED, and
   both are available at [eq_refl] because [Adjunction_Induced_Monad] is a
   [Build_Monad] applied to them (Monad/Comparison.v:123-131): the unit is
   the free-group unit and the multiplication is [U] applied to the counit
   at [F X], i.e. "evaluate a word of words". *)

Example free_group_monad_ret (X : Sets) :
  @ret Sets (Grp_Forget ◯ FreeGrp) free_group_monad X = free_group_unit X
  := eq_refl.

Example free_group_monad_join (X : Sets) :
  @join Sets (Grp_Forget ◯ FreeGrp) free_group_monad X
    = fmap[Grp_Forget] (free_group_counit (FreeGrp X))
  := eq_refl.

(* ...and Riehl's description of the underlying endofunctor — a set goes to
   the words in its letters and their formal inverses — is the carrier of
   [(U ◯ F) X], on the nose. *)
Example free_group_monad_carrier (X : Sets) :
  carrier ((Grp_Forget ◯ FreeGrp) X) = FGWord X := eq_refl.

(** ** Awodey §7.2: the underlying-set functor is representable

    [U : Grp ⟶ Sets] is represented by the free group on one generator:
    a homomorphism out of it is exactly an element of the target, which
    is the free/forgetful adjunction read at the singleton.  Nothing in
    the tree represented [Grp_Forget] before this file — the three mentions
    of [Representable] under Instance/Grp/ that predate it are all
    disclaimers. *)

Notation SetOne := unit_setoid_object.

Notation grp_adj G :=
  (@adj Grp Sets FreeGrp Grp_Forget free_group_adjunction SetOne G).

(* The two directions are lifted out of the record literal: inside
   [{| to := … |}] the names [to] and [from] resolve to the fields being
   defined, not to [Isomorphism]'s projections. *)

Program Definition grp_repr_const (G : Grp) (a : carrier (Grp_Forget G)) :
  SetOne ~{Sets}~> Grp_Forget G := {| morphism := fun _ => a |}.

Definition grp_repr_to (G : Grp) (f : FreeGrp SetOne ~{Grp}~> G) :
  carrier (Grp_Forget G) := to (grp_adj G) f ttt.

Definition grp_repr_from (G : Grp) (a : carrier (Grp_Forget G)) :
  FreeGrp SetOne ~{Grp}~> G := from (grp_adj G) (grp_repr_const G a).

(* The two naturality facts, proved once here rather than inside the
   instance's obligations.  Each needs a transport step: the transpose's
   naturality is stated against [fmap[U] f ∘ k], and the constant map at
   [f a] is pointwise equal to that but is a different record. *)

Lemma grp_repr_to_natural {x y : Grp} (f : x ~{Grp}~> y)
  (h : FreeGrp SetOne ~{Grp}~> x) :
  grp_repr_to y (f ∘ h) ≈ f (grp_repr_to x h).
Proof.
  exact (@to_adj_nat_r Grp Sets FreeGrp Grp_Forget free_group_adjunction
                       SetOne x y f h ttt).
Qed.

Lemma grp_repr_from_natural {x y : Grp} (f : x ~{Grp}~> y)
  (a : carrier (Grp_Forget x)) (w : carrier (Grp_Forget (FreeGrp SetOne))) :
  grp_repr_from y (f a) w ≈ f (grp_repr_from x a w).
Proof.
  unfold grp_repr_from.
  transitivity (from (grp_adj y) (fmap[Grp_Forget] f ∘ grp_repr_const x a) w).
  - exact (proper_morphism (from (grp_adj y))
             (grp_repr_const y (f a))
             (fmap[Grp_Forget] f ∘ grp_repr_const x a)
             (fun _ => reflexivity _) w).
  - exact (@from_adj_nat_r Grp Sets FreeGrp Grp_Forget free_group_adjunction
                           SetOne x y f (grp_repr_const x a) w).
Qed.

Program Definition Grp_Forget_Representable : Representable Grp_Forget := {|
  repr_obj := FreeGrp SetOne;
  represented :=
    {| to   := {| transform := fun G => {| morphism := grp_repr_to G |} |}
     ; from := {| transform := fun G => {| morphism := grp_repr_from G |} |} |}
|}.
Next Obligation. symmetry; exact (grp_repr_to_natural f x0). Qed.
Next Obligation. exact (grp_repr_to_natural f x0). Qed.
Next Obligation.
  exact (proper_morphism (from (grp_adj G))
           (grp_repr_const G x) (grp_repr_const G y) (fun _ => H) a).
Qed.
Next Obligation. symmetry; exact (grp_repr_from_natural f x0 a). Qed.
Next Obligation. exact (grp_repr_from_natural f x0 a). Qed.
(* The two isomorphism laws are the adjunction's own, read at [ttt].  In
   [Sets] an equation between morphisms is pointwise, so each is the
   corresponding [iso_?_from] applied to a point. *)
Next Obligation. exact (iso_to_from (grp_adj x) (grp_repr_const x x0) ttt). Qed.
Next Obligation.
  unfold grp_repr_from, grp_repr_to.
  transitivity (from (grp_adj x) (to (grp_adj x) x0) a).
  - refine (proper_morphism (from (grp_adj x))
              (grp_repr_const x (to (grp_adj x) x0 ttt))
              (to (grp_adj x) x0) _ a).
    intro u; destruct u; reflexivity.
  - exact (iso_from_to (grp_adj x) x0 a).
Qed.

(** ** Mac Lane §V.6's injectivity clause, and where its argument stops

    The issue's Verification block asks for [Free_Grp_unit_injective]: the
    universal arrow [X → U (F X)] is injective, "by the two-element-group
    separation argument".  Both halves of that are delivered below, and the
    argument's constructive limit is disclosed rather than papered over.

    The general form is one transpose.  If [X] embeds in the underlying set
    of ANY group at all, the unit is injective, because the transpose of the
    embedding factors it through the unit.  That is
    [free_group_unit_injective_of_embedding], and it needs no hypothesis on
    [X] and no reference to the word model.

    Mac Lane's separation argument is the instance that manufactures such an
    embedding out of nothing — for [a] apart from [b], map [X] to Z/2 by the
    characteristic function of [a].  The Z/2 used is Instance/Grp.v:1087's
    [Z2], with its non-triviality at :1102; nothing new is built for it, and
    Construction/Deloop.v:395's [Bool_Xor_Grp] is a DIFFERENT thing — it
    inhabits that file's own record also named [GrpObject], the collision
    that makes Instance/Grp/Free.v import Instance/Grp.v last.  On SETOIDS
    the characteristic function does not exist without a decision procedure
    for [≈], so
    [free_group_unit_injective_dec] carries one, and the uniform statement
    is NOT proved here.  It is also not refuted: the obstruction is to this
    ARGUMENT, not to the conclusion.  Proving it uniformly would mean
    analysing [FreeGroupoidRel] (Construction/Free/Groupoid.v:251), the
    generated congruence on words, and that file states in terms that it
    offers no normal form and no decision procedure (:166-171), so every
    negative statement there is proved by mapping into a concrete groupoid
    — which is exactly the route taken here.

    CONFIRMED AND SHARPENED by the PR "algebraic carriers are sets"
    (2026-09-17).  That PR had to give the free group a [Prop]-valued
    equality, and measured that the free groupoid's hom-equality — Construction/
    Quotient.v's [CongClosure] — has no [Prop] mirror out of which the
    [Type]-valued equation can be recovered: a truncation of it cannot be
    eliminated into [Type], and a hand [Prop] mirror inductive has no
    [_rect].  The only shape that would have worked is a normal form, i.e.
    exactly the decision procedure this paragraph says does not exist.  So
    the free group's `≈` is the propositional TRUNCATION of the groupoid's
    (Instance/Grp/Free.v's [fg_equiv]), and the totality of everything below
    over ALL of [Sets] is unaffected: no constant in this file gained a
    hypothesis. *)

Notation grp_adj_at X H :=
  (@adj Grp Sets FreeGrp Grp_Forget free_group_adjunction X H).

(* The transpose of [g] agrees with [g] at the unit.  This is
   [to_adj_unit] composed with [iso_to_from], read pointwise. *)
Lemma free_group_transpose_at_unit {X : Sets} (H : Grp)
      (g : X ~{Sets}~> Grp_Forget H) (a : carrier X) :
  g a ≈ fmap[Grp_Forget] (from (grp_adj_at X H) g) (free_group_unit X a).
Proof.
  transitivity (to (grp_adj_at X H) (from (grp_adj_at X H) g) a).
  - symmetry; exact (iso_to_from (grp_adj_at X H) g a).
  - exact (@to_adj_unit Grp Sets FreeGrp Grp_Forget free_group_adjunction
             X H (from (grp_adj_at X H) g) a).
Qed.

(** Any embedding of [X] into a group's underlying set forces the unit to
    be injective. *)
Theorem free_group_unit_injective_of_embedding {X : Sets} (H : Grp)
        (g : X ~{Sets}~> Grp_Forget H)
        (Hg : ∀ a b : carrier X, g a ≈ g b → a ≈ b)
        (a b : carrier X) :
  free_group_unit X a ≈ free_group_unit X b → a ≈ b.
Proof.
  intro Heq.
  apply Hg.
  transitivity (fmap[Grp_Forget] (from (grp_adj_at X H) g)
                  (free_group_unit X a)).
  { exact (free_group_transpose_at_unit H g a). }
  transitivity (fmap[Grp_Forget] (from (grp_adj_at X H) g)
                  (free_group_unit X b)).
  { exact (proper_morphism (fmap[Grp_Forget] (from (grp_adj_at X H) g))
             (free_group_unit X a) (free_group_unit X b) Heq). }
  symmetry; exact (free_group_transpose_at_unit H g b).
Qed.

(* A decision procedure for a [Sets] object's own [≈].  Stated as a
   [Type]-valued sum rather than [sumbool]: [≈] is a [crelation], so it does
   not fit in [Prop]. *)
Definition SetoidDecidable (X : Sets) : Type :=
  ∀ a b : carrier X, (a ≈ b) + ((a ≈ b) → False).

(* The characteristic map of [a], the separating map of Mac Lane's
   argument.  This is the step that needs [dec]: without it there is no
   function at all, respectfulness aside. *)
Program Definition grp_chi {X : Sets} (dec : SetoidDecidable X)
        (a : carrier X) : X ~{Sets}~> Grp_Forget Z2 := {|
  morphism := fun x => if dec x a then true else false
|}.
Next Obligation.
  proper.
  destruct (dec x a) as [e1|n1], (dec y a) as [e2|n2]; auto.
  - now destruct (n2 (transitivity (symmetry H) e1)).
  - now destruct (n1 (transitivity H e2)).
Qed.

(** Mac Lane's separation argument, with the decision procedure it needs
    made explicit.  Distinct generators stay distinct in the free group. *)
Theorem free_group_unit_injective_dec {X : Sets} (dec : SetoidDecidable X)
        (a b : carrier X) :
  free_group_unit X a ≈ free_group_unit X b → a ≈ b.
Proof.
  intro Heq.
  destruct (dec a b) as [Hab|Hab]; [exact Hab|].
  (* The two sides disagree at [grp_chi dec a], which the transpose
     forbids. *)
  assert (Hchi : grp_chi dec a a ≈ grp_chi dec a b).
  { transitivity (fmap[Grp_Forget]
                    (from (grp_adj_at X Z2) (grp_chi dec a))
                    (free_group_unit X a)).
    { exact (free_group_transpose_at_unit Z2 (grp_chi dec a) a). }
    transitivity (fmap[Grp_Forget]
                    (from (grp_adj_at X Z2) (grp_chi dec a))
                    (free_group_unit X b)).
    { exact (proper_morphism
               (fmap[Grp_Forget] (from (grp_adj_at X Z2) (grp_chi dec a)))
               (free_group_unit X a) (free_group_unit X b) Heq). }
    symmetry; exact (free_group_transpose_at_unit Z2 (grp_chi dec a) b). }
  simpl in Hchi.
  destruct (dec a a) as [_|Haa]; [| now destruct (Haa (reflexivity a))].
  destruct (dec b a) as [Hba|_]; [| discriminate Hchi].
  now destruct (Hab (symmetry Hba)).
Qed.

(* Non-vacuity, and the connection to what was already in tree.
   Instance/Grp/Free.v:586's [free_group_two_generators_distinct] is the
   two-letter case, proved by mapping into S3; it is recovered here as an
   instance of the general statement, over Z/2 instead.  The two are
   independent proofs of the same fact, and neither is deleted: the S3 one
   also carries non-commutativity, which Z/2 cannot. *)

Definition TwoLetters_dec : SetoidDecidable TwoLetters :=
  fun a b => match Bool.bool_dec a b with
             | left e  => inl e
             | right n => inr n
             end.

Corollary free_group_two_letters_distinct :
  free_group_unit TwoLetters true ≈ free_group_unit TwoLetters false → False.
Proof.
  intro Heq.
  exact (Bool.diff_true_false
           (free_group_unit_injective_dec TwoLetters_dec true false Heq)).
Qed.
