Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Adjunction.
Require Import Category.Functor.Hom.Limit.
Require Import Category.Functor.Representable.
Require Import Category.Structure.Complete.
Require Import Category.Structure.WellPowered.
Require Import Category.Construction.Comma.Limit.
Require Import Category.Construction.Comma.Creation.
Require Import Category.Instance.Discrete.Reconstruct.
Require Import Category.Instance.Adjoints.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Sets.Complete.
Require Import Category.Instance.Sets.Classifier.OneLevel.
Require Import Category.Instance.Sets.WellPowered.
Require Import Category.Instance.Sets.Cogenerator.
Require Import Category.Instance.Powerset.
Require Import Category.Instance.Powerset.WellPowered.
Require Import Category.Adjunction.GAFT.Sets.
Require Import Category.Adjunction.SAFT.
Require Import Category.Adjunction.SAFT.Sets.
Require Import Category.Adjunction.SAFT.WellPowered.
Require Import Category.Adjunction.SAFT.InitialObject.Examples.
Require Import Category.Adjunction.SAFT.Characterization.
Require Import Category.Adjunction.SAFT.Characterization.Cover.
Require Import Category.Adjunction.SAFT.Characterization.Corollaries.

Generalizable All Variables.

(** * The special adjoint functor theorem at [Sets], [Subsets] and [Indiscrete] *)

(* nLab:      https://ncatlab.org/nlab/show/adjoint+functor+theorem
   nLab:      https://ncatlab.org/nlab/show/well-powered+category

   Mac Lane, "Categories for the Working Mathematician", 2nd ed., §V.8,
   Corollary, book p. 130 ([maclane:V.8:cor1]), and Riehl, "Category
   Theory in Context", Corollary 4.7.13, printed p. 178
   ([riehl:4.7:cor13]), as the catalogue under doc/plan/books summarizes
   them (the printed books were not consulted).  This satellite applies
   Adjunction/SAFT/Characterization.v's [SAFT_wellpowered] and, once, its
   [SAFT_thm2], Adjunction/SAFT/Characterization/Cover.v's
   [SAFT_cover_wp] and [saft_cover_at], and the corollaries of
   Adjunction/SAFT/Characterization/Corollaries.v, with every premise
   supplied in tree, at three categories.

   [Sets] UNDER [Untruncate].  With one [Un : Untruncate@{o}] (the
   hypothesis of Instance/Sets/Classifier/OneLevel.v), [Sets@{o so}] has
   every premise: Instance/Sets/Complete.v's [Sets_Complete],
   Instance/Sets/Cogenerator.v's [Sets_Cogenerator_untruncate Un] and
   Instance/Sets/WellPowered.v's [Sets_WellPowered_untruncate Un].
   [Sets] is not thin, so here [cog_separates] does work.
     - [sets_id_saft] and [sets_id_saft_cover]: the identity, by both
       routes.  Its continuity, Adjunction/GAFT/Sets.v's
       [Sets_Id_PreservesImageLimit], is itself obtained from [adj_id],
       so at [Id] the conclusion was known: [sets_id_saft_iso] identifies
       the constructed left adjoint with [Id] by Theory/Adjunction.v's
       [left_adjoint_iso].
     - [sets_hom_saft]: the covariant hom functor [HomFrom A], whose
       continuity is Functor/Hom/Limit.v's [hom_ContinuousFunctor],
       proved directly and not from an adjunction.  This is the witness
       whose premises are not read off a known adjoint; the left adjoint
       it constructs (classically [A × −]) is not identified here.
     - [sets_id_repr_saft], [sets_hom_repr_saft]: the representability
       corollary at both functors; [sets_saft_cocomplete]: the
       cocompleteness corollary.  Instance/Sets/Cocomplete.v's
       [Sets_Cocomplete] needs no [Untruncate], so this one is the
       corollary's non-vacuity, not new content.
     - [sets_id_cover_separation]: at ONE tuple, Cover.v's covering datum
       [SubobjectCoverAt] is inhabited at every [d] ([sets_id_new_cover])
       and Adjunction/SAFT.v's [SubobjectCover], fed
       Adjunction/SAFT/WellPowered.v's [WellPowered_SubobjectIndex] of
       the same well-powering, is refuted by Adjunction/SAFT/Sets.v's
       [SubobjectCover_Id_Sets_absurd] ([sets_id_old_cover_refuted]).
       Its binder names the well-powering's upper universe [t] so that
       the statement holds at every [t] above [o].

   [Subsets] (Instance/Powerset.v), THIN AND UNCONDITIONAL.  Complete by
   Instance/Powerset/WellPowered.v's [Subsets_Complete_free],
   well-powered by its [Subsets_WellPowered], cogenerated by the empty
   family ([Subsets_Cogenerator_empty], Adjunction/SAFT/InitialObject/
   Examples.v): in a thin category separation is vacuous.
     - [subsets_inverse_image_saft]: [InverseImage f] has a left adjoint.
       Its continuity is read off Instance/Powerset.v's
       [image_preimage_adjunction], so the conclusion was known;
       [subsets_inverse_image_saft_iso] identifies the constructed left
       adjoint with [DirectImage f].
     - [subsets_inverse_image_thm2]: Mac Lane's Theorem 2 at the same
       functor, the one application of [SAFT_thm2] in tree.  Its
       wide-pullback premise is Adjunction/SAFT/Characterization.v's
       [Complete_HasSubobjectWidePullbacks] of [Subsets_Complete_free Y],
       whose index universe [q] may reach the objects here because the
       objects sit at or below the shape universe.  CIRCULAR: both
       preservation premises, [right_adjoint_PreservesImageLimit] and
       [right_adjoint_PreservesWidePullbacks], are read off
       [image_preimage_adjunction f], the adjunction whose left adjoint
       the theorem then builds.  It shows Theorem 2's premises
       satisfiable together at a thin category, not a new adjoint.
       Test/ProbeSAFT453.v's [p453_thm2_subsets_is_library] reads it, by
       [eq_refl], as that file's own assembly [p453_thm2_subsets].
     - [subsets_saft_cocomplete]: [Subsets@{o u} X] is cocomplete for [o
       <= u].  Instance/Powerset.v's [Subsets_Cocomplete] is stated at
       [Subsets@{o Set} X]; the record is not cumulative, and this is the
       instance [Subsets_WellPowered] asks for.

   [Indiscrete@{o j j} Type@{j}], [j < o], DEGENERATE AND UNCONDITIONAL:
   every hom is [unit].  Structure/WellPowered.v's [Indiscrete_Complete]
   and [Indiscrete_WellPowered], and Adjunction/SAFT/InitialObject/
   Examples.v's [Indiscrete_Cogenerator_empty].
   [indiscrete_saft] takes the well-powering with its index at [Set],
   strictly below the hom universe [j]: [SAFT_wellpowered]'s index is
   bounded by the homs, not equal to them (Test/ProbeSAFT453.v's
   [p453_indiscrete_set_index] restates it, and its N17 refuses the index
   at [Set] through an unannotated wrapper, whose minimization puts the
   index at the homs).  Its continuity is
   [right_adjoint_PreservesImageLimit] of [adj_id], so here too the
   conclusion was known.  [indiscrete_saft_cocomplete] is the
   cocompleteness corollary there; it takes the index at [j], and in a
   scratch file carrying this file's import list,
   Instance/Sets/SpecialInitial.v and Adjunction/GAFT.v, the same term
   with the index at [Set] is accepted too, as is [indiscrete_saft]'s
   term with the index at [j], both closed: either choice serves both.

   NO UNCONDITIONAL NON-THIN WITNESS AMONG THE CANDIDATES MEASURED.
   Measured in scratch files with this file's import list and
   Instance/Sets/SpecialInitial.v, each refusal beside an instrument and
   a control that are accepted (<1> to <3> number universes the scratch
   compile generated, by first appearance):
     - [Sets@{o so}] without [Untruncate]: the unconditional
       well-powerings in tree include Instance/Sets/WellPowered.v's
       [Sets_WellPoweredAt_up], whose index sits one universe up, at its
       own upper universe, and Structure/WellPowered.v's [wp_trivial],
       whose index [SubObj x] sits at or above the objects' [so]; both
       index strictly above the homs [o] (Test/ProbeSAFT453.v's
       [p453_sets_wp_trivial] states the second at [so],
       [WellPoweredAt@{so so so o so}]).  Cover.v's [saft_cover_at]
       accepts each (the cover bounds no index; control, with a small
       [Cogenerator] taken as a hypothesis, since none is built without
       [Untruncate] or [IEM]; the probe's [p453_cover_up] and
       [p453_sets_cover_trivial]), but [SAFT_cover_wp_at] refuses the
       first at the argument: "The term "Sets_WellPoweredAt_up ?X" has
       type "WellPoweredAt@{…} ?X" while it is expected to have type
       "WellPoweredAt@{<1> so … o <3>} (saft_prod@{so so o o …}
       Id[Sets@{o so}] Sets_Complete@{o so} G d)" (universe
       inconsistency: Cannot enforce <1> = <3> because <1> <= <2> <
       <3>)".  That refusal is at [SAFT_cover_wp_at]'s own binder [w <=
       h]; the pin is [GAFT]'s: with Adjunction/GAFT.v added to the
       scratch file (under this file's import list [GAFT] is not in
       scope, and a refusal there would be the missing name, not the
       pin), [GAFT (@Id Sets@{o so}) Sets_Complete
       Sets_Id_PreservesImageLimit (fun d => saft_solution_set_at … G d
       (Sets_WellPoweredAt_up _))] is refused at the solution set: "… has
       type "SolutionSet@{<1> so so o} Id[Sets@{o so}] d" while it is
       expected to have type "SolutionSet@{o so so o} Id[Sets@{o so}] d"
       (universe inconsistency: Cannot enforce <1> = o because o < <2> <=
       <1>)", beside the accepted control [saft_solution_set_at … G d
       (Sets_WellPoweredAt_up _)] not handed to [GAFT].
       Test/ProbeSAFT453.v pins both, as N11 ([p453_n11_cover_wp_at_up])
       and N12 ([p453_n12_gaft_at_up]), beside [p453_cover_up] and
       [p453_solution_set_up]; its N14 and N28 pin the same two steps for
       [wp_trivial] at an arbitrary [C] with [h < o].  #451's
       [WellPowered] refuses the same well-powering by its own pin before
       any theorem is applied: [fun x => Sets_WellPoweredAt_up x :
       WellPowered Sets@{o so}] is refused with the same inconsistency
       ("Cannot enforce <1> = <3> because <1> <= <2> < <3>").
       Test/ProbeSAFT453.v pins it as N13 ([p453_n13_wp_up]), beside
       [p453_wp_up_at].
     - [Sets^op]: complete and cogenerated unconditionally
       (Instance/Sets/SpecialInitial.v's [setsop_comp], [setsop_cog]),
       but co-well-powered only one universe up
       ([Sets_CoWellPoweredAt_up]); the cover accepts it and
       [SAFT_cover_wp_at] refuses it, the expected type ending "…
       (saft_prod@{so so o o …} Id[Sets@{o so}^op] setsop_comp@{o so}
       setsop_cog@{o o so} d)" and the message ending "(universe
       inconsistency: Cannot enforce <1> = <3> because <1> <= <2> <
       <3>)".  Test/ProbeSAFT453.v pins it as N25
       ([p453_n25_setsop_cover_wp_at_up]), beside [p453_setsop_cover_up],
       and the same well-powering's solution set handed to [GAFT]
       directly as N29 ([p453_n29_setsop_gaft_up]), refused with "… has
       type "SolutionSet@{<1> so so o} Id[Sets@{o so}^op] d" while it is
       expected to have type "SolutionSet@{o so so o} Id[Sets@{o so}^op]
       d" (universe inconsistency: Cannot enforce <1> = o because o < <2>
       <= <1>)", beside [p453_setsop_solution_set_up].
     - The unconditional LARGE cogenerator,
       Instance/Sets/Cogenerator.v's [Sets_Cogenerator_large], indexed by
       all objects, is refused by [SAFT_cover_wp]: "The term
       "Sets_Cogenerator_large" has type "Cogenerator@{…} Sets@{<1> …}"
       while it is expected to have type "Cogenerator@{o so o} Sets@{o
       so}" (universe inconsistency: Cannot enforce <1> = o because <1> <
       o)", and [SAFT_wellpowered], whose [Cogenerator@{c o h}] carries
       [c <= so], refuses it at the same argument.  Test/ProbeSAFT453.v
       pins the two as N15 and N16 ([p453_n15_large_cog_cover],
       [p453_n16_large_cog_comma]), beside [p453_large_cog] and
       [p453_large_cog_abstract].
   So the non-thin witnesses are conditional on [Untruncate], and the
   thin and degenerate ones are unconditional.  The survey is of those
   three candidates only.  Not surveyed: a category whose objects sit at
   or below its homs, which Structure/WellPowered.v's [trivial_small]
   makes well-powered unconditionally (a complete one with an
   [ArrowIndex] and decidable hom-setoids is thin, by
   Structure/Complete/Freyd.v's [small_complete_is_thin]); and [Grp],
   well-powered in tree only one universe up
   (Instance/Grp/WellPowered.v's [Grp_WellPoweredAt_up]) and with no
   [Cogenerator] built.  (An earlier revision said "(a grep for
   "Cogenerator" under Instance/ finds Instance/Sets files only)"; since
   #454 the same grep, [find Instance -name '*.v' | xargs grep -l
   Cogenerator], finds sixteen files, four under Instance/Sets.  Of the
   other twelve, eight only name the file Instance/Mod/Cogenerator.v in
   prose, Instance/Mod/Watts/Unconditional.v names it and
   [RModop_Cogenerator] in prose only, as a route it does not take, and
   three use the record: Instance/Mod/Cogenerator.v,
   Instance/Mod/WellPowered.v and Instance/Mod/Watts.v, none of them
   about [Grp].  They build a cogenerator of (RMod R)^op
   unconditionally, [RModop_Cogenerator], and two of RMod R: one on the
   premise that ℚ/ℤ is an injective cogenerator of Ab,
   [QZ_injective_cogenerator], and an unconditional but large one,
   [RMod_Cogenerator_large], which [cogen_prod] refuses.  Watts.v applies
   the Corollary with the first two, under [Untruncate].)

   UNIVERSES.  Every constant names the universes of its category ([o so]
   for [Sets@{o so}], [o u] for [Subsets@{o u} X], [j o] for the
   indiscrete category) and leaves the rest to the theorems it applies.
   [subsets_inverse_image_saft_iso] ascribes the adjunction's type to
   name [u]: without it, [u] was left out of the statement and
   minimization set it to [o].

   NOT DELIVERED.  No unconditional witness at a category that is not
   thin; no identification of the left adjoint of [HomFrom A]; no witness
   of Mac Lane's Theorem 2 at a category that is not thin, and none whose
   preservation premises are not read off a known adjoint.

   MEASUREMENTS.  Sixteen constants ([Print Module]), no [Program]
   obligation, all transparent, each "Closed under the global context"
   by its fully qualified name.  Closure 179 files excluding itself,
   counted over .Makefile.coq.d. *)

(** ** [Sets] under [Untruncate]: the identity *)

Definition sets_id_saft@{o so +| Set < o, o < so +} (Un : Untruncate@{o}) :
  { F : Sets@{o so} ⟶ Sets@{o so} & F ⊣ @Id Sets@{o so} } :=
  SAFT_wellpowered (@Id Sets@{o so}) Sets_Complete Sets_Id_PreservesImageLimit
    (Sets_Cogenerator_untruncate Un) (Sets_WellPowered_untruncate Un).

(* The same tuple through the GAFT route. *)
Definition sets_id_saft_cover@{o so +| Set < o, o < so +} (Un : Untruncate@{o}) :
  { F : Sets@{o so} ⟶ Sets@{o so} & F ⊣ @Id Sets@{o so} } :=
  SAFT_cover_wp (@Id Sets@{o so}) Sets_Complete Sets_Id_PreservesImageLimit
    (Sets_Cogenerator_untruncate Un) (Sets_WellPowered_untruncate Un).

(** ** The separation: one tuple, the new cover inhabited, the old refuted *)

Definition sets_id_new_cover@{o so t +| Set < o, o < so, o < t +}
  (Un : Untruncate@{o}) (d : Sets@{o so}) :=
  saft_cover_at (@Id Sets@{o so}) Sets_Complete Sets_Id_PreservesImageLimit
    (Sets_Cogenerator_untruncate Un) d
    (Sets_WellPowered_untruncate@{o so t} Un _).

Definition sets_id_old_cover_refuted@{o so t +| Set < o, o < so, o < t +}
  (Un : Untruncate@{o}) :=
  SubobjectCover_Id_Sets_absurd Sets_Complete (Sets_Cogenerator_untruncate Un)
    (WellPowered_SubobjectIndex (Sets_WellPowered_untruncate@{o so t} Un)).

(* Both halves in one statement, so that "the same completeness, cogenerator
   and well-powering" is read off the type. *)
Definition sets_id_cover_separation@{o so t +| Set < o, o < so, o < t +}
  (Un : Untruncate@{o}) :
  (∀ d : Sets@{o so},
     SubobjectCoverAt (@Id Sets@{o so}) Sets_Complete
       (Sets_Cogenerator_untruncate Un) d
       (Sets_WellPowered_untruncate@{o so t} Un _))
  * (SubobjectCover (@Id Sets@{o so}) Sets_Complete
       (Sets_Cogenerator_untruncate Un)
       (WellPowered_SubobjectIndex (Sets_WellPowered_untruncate@{o so t} Un))
     → False) :=
  (sets_id_new_cover Un, sets_id_old_cover_refuted Un).

(** ** [Sets] under [Untruncate]: a hom functor *)

Definition sets_hom_saft@{o so +| Set < o, o < so +} (Un : Untruncate@{o})
  (A : Sets@{o so}) :
  { F : Sets@{o so} ⟶ Sets@{o so} & F ⊣ @HomFrom Sets@{o so} A } :=
  SAFT_wellpowered (@HomFrom Sets@{o so} A) Sets_Complete
    (Continuous_PreservesImageLimit (hom_ContinuousFunctor A))
    (Sets_Cogenerator_untruncate Un) (Sets_WellPowered_untruncate Un).

(** ** The corollaries at [Sets] under [Untruncate] *)

Definition sets_id_repr_saft@{o so +| Set < o, o < so +} (Un : Untruncate@{o}) :
  Representable (@Id Sets@{o so}) :=
  continuous_Set_functor_representable (@Id Sets@{o so}) Sets_Complete
    Sets_Id_PreservesImageLimit (Sets_Cogenerator_untruncate Un)
    (Sets_WellPowered_untruncate Un).

Definition sets_hom_repr_saft@{o so +| Set < o, o < so +} (Un : Untruncate@{o})
  (A : Sets@{o so}) : Representable (@HomFrom Sets@{o so} A) :=
  continuous_Set_functor_representable (@HomFrom Sets@{o so} A) Sets_Complete
    (Continuous_PreservesImageLimit (hom_ContinuousFunctor A))
    (Sets_Cogenerator_untruncate Un) (Sets_WellPowered_untruncate Un).

Definition sets_saft_cocomplete@{o so +| Set < o, o < so +}
  (Un : Untruncate@{o}) : @Cocomplete Sets@{o so} :=
  saft_cocomplete Sets_Complete (Sets_Cogenerator_untruncate Un)
    (Sets_WellPowered_untruncate Un).

(** ** Thin and unconditional: the powerset lattices *)

Definition subsets_inverse_image_saft@{o so u +| Set < o, o < so, o <= u +}
  {X Y : SetoidObject@{o o}} (f : X ~{Sets@{o so}}~> Y) :
  { F : Subsets@{o u} X ⟶ Subsets@{o u} Y & F ⊣ InverseImage f } :=
  SAFT_wellpowered (InverseImage f) (Subsets_Complete_free Y)
    (right_adjoint_PreservesImageLimit (image_preimage_adjunction f))
    (Subsets_Cogenerator_empty Y) (Subsets_WellPowered Y).

(* Mac Lane's Theorem 2 at the same functor: every premise is inhabited,
   the wide pullbacks by [Complete_HasSubobjectWidePullbacks].  CIRCULAR:
   both preservation premises are read off [image_preimage_adjunction f],
   the adjunction whose left adjoint the theorem then builds, so this
   shows the premises satisfiable together, not a new adjoint. *)
Definition subsets_inverse_image_thm2@{o so u +| Set < o, o < so, o <= u +}
  {X Y : SetoidObject@{o o}} (f : X ~{Sets@{o so}}~> Y) :
  { F : Subsets@{o u} X ⟶ Subsets@{o u} Y & F ⊣ InverseImage f } :=
  SAFT_thm2 (InverseImage f) (Subsets_Complete_free Y)
    (right_adjoint_PreservesImageLimit (image_preimage_adjunction f))
    (Subsets_Cogenerator_empty Y)
    (Complete_HasSubobjectWidePullbacks (Subsets_Complete_free Y))
    (right_adjoint_PreservesWidePullbacks (image_preimage_adjunction f)).

Definition subsets_saft_cocomplete@{o u +| Set < o, o <= u +}
  (X : SetoidObject@{o o}) : @Cocomplete (Subsets@{o u} X) :=
  saft_cocomplete (Subsets_Complete_free X) (Subsets_Cogenerator_empty X)
    (Subsets_WellPowered X).

(** ** Degenerate and unconditional: an indiscrete category *)

(* Objects the types of [Type@{j}], one universe above the homs; the
   well-powering is indexed at [Set], strictly below the homs. *)
Definition indiscrete_saft@{j o +| j < o +} :
  { F : Indiscrete@{o j j} Type@{j} ⟶ Indiscrete@{o j j} Type@{j}
    & F ⊣ @Id (Indiscrete@{o j j} Type@{j}) } :=
  SAFT_wellpowered (@Id (Indiscrete@{o j j} Type@{j}))
    (Indiscrete_Complete (Datatypes.unit : Type@{j}))
    (right_adjoint_PreservesImageLimit
       (@adj_id (Indiscrete@{o j j} Type@{j})))
    (Indiscrete_Cogenerator_empty Type@{j})
    (Indiscrete_WellPowered@{o j Set o _} Type@{j}).

Definition indiscrete_saft_cocomplete@{j o +| j < o +} :
  @Cocomplete (Indiscrete@{o j j} Type@{j}) :=
  saft_cocomplete (Indiscrete_Complete (Datatypes.unit : Type@{j}))
    (Indiscrete_Cogenerator_empty Type@{j})
    (Indiscrete_WellPowered@{o j j o _} Type@{j}).

(** ** What the constructed adjoints are, up to isomorphism *)

(* At [Id] the left adjoint is the identity, by uniqueness of adjoints. *)
Definition sets_id_saft_iso@{o so +| Set < o, o < so +} (Un : Untruncate@{o}) :
  projT1 (sets_id_saft Un) ≈ @Id Sets@{o so} :=
  left_adjoint_iso (@Id Sets@{o so}) _ _ (projT2 (sets_id_saft Un)) adj_id.

(* At [InverseImage f] it is the direct image. *)
Definition subsets_inverse_image_saft_iso@{o so u +| Set < o, o < so, o <= u +}
  {X Y : SetoidObject@{o o}} (f : X ~{Sets@{o so}}~> Y) :
  projT1 (subsets_inverse_image_saft f
            : { F : Subsets@{o u} X ⟶ Subsets@{o u} Y
              & F ⊣ InverseImage@{o so u} f })
    ≈ DirectImage@{o so u} f :=
  left_adjoint_iso (InverseImage@{o so u} f) _ _
    (projT2 (subsets_inverse_image_saft f))
    (image_preimage_adjunction f).
