Require Import Category.Lib.
Require Import Category.Instance.Comp.

Generalizable All Variables.

(** * Derived operators: the clone of a signature *)

(* nLab:      https://ncatlab.org/nlab/show/clone
   nLab:      https://ncatlab.org/nlab/show/Lawvere+theory
   Wikipedia: https://en.wikipedia.org/wiki/Clone_(algebra)

   Mac Lane §V.6, book p. 124 (PDF p. 133), the definition of a DERIVED
   OPERATOR.  The derived operators of a type close the given operations
   under composition and substitution, and Mac Lane's point is that the
   action of the clone on any algebra is already determined by the action
   of the basic operations: every action of Ω extends uniquely to an
   action of Λ.

   ** What the tree had, measured

   Nothing arity-graded with a substitution action.  Instance/Comp.v's
   [Tree] is a term over a WHOLE variable type, not an operator of a
   specific arity, and names no composition or substitution operation.
   Construction/PROP/Term.v:39's [Term] is arity-graded and closes under
   composition, tensor and braids, but NOT under substitution along an
   arbitrary function between finite arities — braids are bijections, and
   Mac Lane's substitution duplicates and deletes variables.

   ** The index type costs nothing

   [Fin.t] is already in scope everywhere: Lib/Setoid.v:5 requires
   Coq.Vectors.Fin and :89 defines [Fin_Setoid], and every file in
   _CoqProject requires Category.Lib.  So grading on [Fin.t n] and
   substituting along an ARBITRARY [Fin.t m → Fin.t n] adds no [Require].
   Instance/FinSet.v:118 is built on exactly this shape, which is to say
   the tree's own [FinSet] already IS "arbitrary maps between finite
   arities".

   ** Substitution is the free-algebra universal property, not a new
      recursion

   [clone_subst] is [induced_map] at the free algebra on the target
   arity.  That makes HALF of the issue's phrase "recovering
   [induced_hom] / [from_free_unique] as the free-algebra instance"
   literally true rather than a remark: substitution IS the induced
   homomorphism's underlying map, and renaming is substitution by
   variables.  The other half is NOT delivered and an audit was right to
   say so — [from_free_unique] is not recovered here at all.  Its
   analogue is [action_extends_to_clone] below, which is a different
   statement (uniqueness of an ACTION extending the basic operations, in
   setoid form) rather than that constant re-derived.

   ** The unique-extension theorem, in two forms, and why

   The theorem is shipped TWICE, and the difference is the whole point of
   the file's discipline.

   [action_extends_to_clone] — the name the issue's Verification block
   checks — is stated against a [SetoidAction]: a carrier with a setoid,
   operations, and an argumentwise-congruence field [sact_op_respects].
   It is CLOSED UNDER THE GLOBAL CONTEXT.

   [action_extends_to_clone_leibniz] is the same theorem with [=] for `≈`
   and no congruence field, and it reports
   [functional_extensionality_dep].  It cannot avoid it: the inductive
   step compares [op A o (fun j => F (args j) env)] with
   [op A o (fun j => clone_act (args j) env)], two argument bundles that
   the induction hypothesis makes pointwise equal and that are not
   convertible.  That is the identical wall as Instance/Comp.v:116's
   [from_free_unique], whose own marker comment at :124 already names the
   cure.

   Nothing is smuggled by the setoid form.  [sact_op_respects] is
   precisely what [functional_extensionality] supplies for [eq_Setoid], so
   the setoid statement is strictly more general and strictly weaker in
   assumptions — which is why it, and not the Leibniz shadow, carries the
   headline name.  Only the axiom-free constants are gated;
   docs/AXIOMS.md records the two that are not.

   ** Not delivered

   No setoid on [Tree] itself — the cure Instance/Comp.v:124 proposes.
   AN EARLIER REVISION OF THIS PARAGRAPH GAVE A REASON THAT IS WRONG, and
   it is corrected here rather than quietly dropped.  It said such a
   congruence "risks pulling in [Eqdep]/[JMeq_eq]", because transitivity
   would have to invert [tree_equiv (node o k) (node o' k')] and so want
   injectivity of [existT] on an [operation S] with no decidable
   equality.  Measured: there is no such risk.  Making symmetry and
   transitivity CONSTRUCTORS of the inductive rather than theorems means
   no inversion is ever performed, and reflexivity is then derived by
   plain induction on the tree; the whole thing is Closed under the
   global context.  (It must be [Type]-valued rather than [Prop]-valued,
   since [Setoid]'s [equiv] is a crelation.)

   The honest reason it is absent is simply that this file does not need
   it: what the clone's unique-extension theorem needs is a setoid on the
   TARGET of an action, which is what [SetoidAction] supplies, and the
   congruence generated by [E] on terms belongs to the free-algebra
   construction (#441) rather than here.  No clone as a CATEGORY and so
   no Lawvere theory — see the closing comment of Instance/Variety.v. *)

Module UA := Category.Instance.Comp.UniversalAlgebra.

Section Clone.

Context (S : UA.OpSignature).

(** ** The arity-graded derived operators *)

Definition DerivedOperators (n : nat) : Type := UA.Tree S (Fin.t n).

Definition clone_var {n} (i : Fin.t n) : DerivedOperators n :=
  UA.generator S (Fin.t n) i.

Definition clone_op {n} (o : UA.operation S)
  (args : UA.arity o → DerivedOperators n) : DerivedOperators n :=
  UA.node S (Fin.t n) o args.

(** ** Closure under substitution, along an ARBITRARY map of arities

    [clone_subst] is Instance/Comp.v:102's [induced_map] at the free
    algebra on [Fin.t n]; [clone_rename] is substitution by variables, and
    it is where "arbitrary function between finite arities" — duplication
    and deletion included, not merely a braid — enters. *)

Definition clone_subst {m n} (s : Fin.t m → DerivedOperators n)
  : DerivedOperators m → DerivedOperators n :=
  UA.induced_map S (Fin.t m) (UA.Free S (Fin.t n)) s.

Definition clone_rename {m n} (phi : Fin.t m → Fin.t n)
  : DerivedOperators m → DerivedOperators n :=
  clone_subst (fun i => clone_var (phi i)).

(** ** Actions, up to a setoid on the target *)

Record SetoidAction := {
  sact_carrier : Type;
  sact_setoid  : Setoid sact_carrier;
  sact_op      : ∀ o : UA.operation S,
                  (UA.arity o → sact_carrier) → sact_carrier;

  (* the congruence field that replaces functional extensionality *)
  sact_op_respects : ∀ (o : UA.operation S) (k1 k2 : UA.arity o → sact_carrier),
    (∀ j, @equiv _ sact_setoid (k1 j) (k2 j)) →
    @equiv _ sact_setoid (sact_op o k1) (sact_op o k2)
}.

(* A [#[local]] notation, and it SHADOWS Theory/Category.v:186/:189's
   [x ≈[ C ] y] for morphism equivalence in a named category, for the
   remainder of this section.  That is harmless here — this file never
   compares morphisms of a category — and the [#[local]] keeps it out of
   every other file, but it is worth knowing before copying the idiom
   somewhere that does. *)
#[local] Notation "x ≈[ A ] y" := (@equiv _ (sact_setoid A) x y)
  (at level 79, only parsing).

(* Every [SetoidAction] has an underlying [OpAlgebra]: the setoid and its
   congruence field are extra structure, not a weakening. *)
Definition sact_alg (A : SetoidAction) : UA.OpAlgebra S :=
  {| UA.carrier := sact_carrier A ; UA.op := sact_op A |}.

Fixpoint clone_act {n} (A : SetoidAction) (t : DerivedOperators n)
  (env : Fin.t n → sact_carrier A) : sact_carrier A :=
  match t with
  | UA.generator _ _ i    => env i
  | UA.node _ _ o args => sact_op A o (fun j => clone_act A (args j) env)
  end.

(* Both computation rules hold definitionally; [reflexivity] is not
   hiding a rewrite. *)

Lemma clone_act_var {n} (A : SetoidAction) (i : Fin.t n)
  (env : Fin.t n → sact_carrier A) :
  clone_act A (clone_var i) env ≈[A] env i.
Proof. reflexivity. Qed.

Lemma clone_act_op {n} (A : SetoidAction) (o : UA.operation S)
  (args : UA.arity o → DerivedOperators n)
  (env : Fin.t n → sact_carrier A) :
  clone_act A (clone_op o args) env
    ≈[A] sact_op A o (fun j => clone_act A (args j) env).
Proof. reflexivity. Qed.

(** ** Mac Lane's theorem: the action of Ω determines the action of Λ

    Any operator [F] that acts like the variables on variables and like
    the basic operations on nodes agrees with [clone_act] everywhere.
    AXIOM-FREE: the inductive step closes with [sact_op_respects] where the
    Leibniz form below must close with functional extensionality. *)

Theorem action_extends_to_clone (A : SetoidAction)
  (F : ∀ n, DerivedOperators n → (Fin.t n → sact_carrier A) → sact_carrier A)
  (Hvar : ∀ n (i : Fin.t n) env, F n (clone_var i) env ≈[A] env i)
  (Hop : ∀ n (o : UA.operation S) (args : UA.arity o → DerivedOperators n) env,
           F n (clone_op o args) env
             ≈[A] sact_op A o (fun j => F n (args j) env)) :
  ∀ n (t : DerivedOperators n) env, F n t env ≈[A] clone_act A t env.
Proof.
  intros n t.
  induction t as [i | o args IH]; intro env.
  - apply Hvar.
  - rewrite (Hop n o args env).
    apply sact_op_respects.
    intro j.
    apply IH.
Qed.

(** ** The substitution and renaming laws for the action *)

Lemma clone_act_subst {m n} (A : SetoidAction)
  (s : Fin.t m → DerivedOperators n) (t : DerivedOperators m)
  (env : Fin.t n → sact_carrier A) :
  clone_act A (clone_subst s t) env
    ≈[A] clone_act A t (fun i => clone_act A (s i) env).
Proof.
  induction t as [i | o args IH]; simpl.
  - reflexivity.
  - apply sact_op_respects.
    intro j.
    apply IH.
Qed.

Lemma clone_act_rename {m n} (A : SetoidAction)
  (phi : Fin.t m → Fin.t n) (t : DerivedOperators m)
  (env : Fin.t n → sact_carrier A) :
  clone_act A (clone_rename phi t) env
    ≈[A] clone_act A t (fun i => env (phi i)).
Proof. apply clone_act_subst. Qed.

End Clone.

Arguments clone_var {_ _} _.
Arguments clone_op {_ _} _ _.
Arguments clone_subst {_ _ _} _ _.
Arguments clone_rename {_ _ _} _ _.
Arguments sact_carrier {_} _.
Arguments sact_op {_} _ _ _.
Arguments clone_act {_ _} _ _ _.

(** ** The Leibniz shadows, and their cost

    Shipped so the comparison is available in the tree rather than only in
    this header, and named so that no one mistakes them for the headline
    statements.  BOTH REPORT [functional_extensionality_dep]; neither is
    gated. *)

Section CloneLeibniz.

Context (S : UA.OpSignature).

(* An action with no setoid: Leibniz [=] throughout. *)
Definition leibniz_action (A : UA.OpAlgebra S) : SetoidAction S :=
  {| sact_carrier := UA.carrier A
   ; sact_setoid  := eq_Setoid (UA.carrier A)
   ; sact_op      := UA.op A
   ; sact_op_respects := fun o k1 k2 H =>
       f_equal (UA.op A o) (functional_extensionality_dep k1 k2 H)
  |}.

Theorem action_extends_to_clone_leibniz (A : UA.OpAlgebra S)
  (F : ∀ n, DerivedOperators S n → (Fin.t n → UA.carrier A) → UA.carrier A)
  (Hvar : ∀ n (i : Fin.t n) env, F n (clone_var i) env = env i)
  (Hop : ∀ n (o : UA.operation S) (args : UA.arity o → DerivedOperators S n) env,
           F n (clone_op o args) env
             = UA.op A o (fun j => F n (args j) env)) :
  ∀ n (t : DerivedOperators S n) env,
    F n t env = clone_act (leibniz_action A) t env.
Proof.
  exact (action_extends_to_clone S (leibniz_action A) F Hvar Hop).
Qed.

Lemma clone_act_subst_leibniz {m n} (A : UA.OpAlgebra S)
  (s : Fin.t m → DerivedOperators S n) (t : DerivedOperators S m)
  (env : Fin.t n → UA.carrier A) :
  clone_act (leibniz_action A) (clone_subst s t) env
    = clone_act (leibniz_action A) t
        (fun i => clone_act (leibniz_action A) (s i) env).
Proof. exact (clone_act_subst S (leibniz_action A) s t env). Qed.

End CloneLeibniz.
