Require Import Category.Lib.
Require Import Category.Lib.Setoid.Propositional.
Require Import Category.Theory.Category.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Universal.Arrow.
Require Import Category.Construction.Subcategory.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Comp.
Require Import Category.Instance.Variety.

Generalizable All Variables.

(** * The free-algebra adjunction for a variety *)

(* nLab:      https://ncatlab.org/nlab/show/variety+of+algebras
   nLab:      https://ncatlab.org/nlab/show/free+object
   Wikipedia: https://en.wikipedia.org/wiki/Free_object

   Mac Lane §V.6, book p. 124 (PDF pp. 133–134).  For any variety the
   underlying-set functor has a left adjoint — the free algebra on a set —
   and Mac Lane gets it from the adjoint functor theorem, the solution set
   being the subalgebra generated by the image.  This file gets it
   directly.  An earlier revision went on: "and the reason is measured
   rather than stylistic".  Since #450 Mac Lane's route is in tree as
   well, and the direct one is kept for the reasons "Why not GAFT" below
   now gives.

   ** The one design decision, and what is actually true about it

   AN EARLIER REVISION OF THIS HEADER SAID, IN CAPITALS, THAT THE FREE
   OBJECT OF A VARIETY "CANNOT LIVE IN #440's [Variety E]", because
   quotienting a type by a relation is what Coq does not offer.  THAT IS
   FALSE, and it was refuted by construction rather than by argument: the
   free commutative magma on two generators DOES exist as an object of
   #440's Leibniz [Variety CommEq], built by sorting terms into normal
   forms under a decidable total order, with its universal arrow packaged
   through the same [universal_arrow_from_UMP] this file uses.  A cheap
   in-tree witness of the same point is
   Test/ProbeVarietyFree441.v's [free_empty_eq_leibniz]: with no
   equations at all the term algebra is already a Leibniz-variety object.

   What IS true, and is the actual reason for the design:

   (1) The TERM ALGEBRA is not a Leibniz-variety object once the
   equations bite.  [free_magma_not_comm_leibniz] proves it for the
   commutative magma — [x * y] and [y * x] are different terms — against
   a control showing the shape is inhabited at the booleans under [xorb].
   So the naive construction, the one Mac Lane's prose describes, does
   not land in [Variety E].

   (2) Making it land requires a NORMAL FORM for the presentation:
   a computable choice of representative per congruence class, which is
   solving that presentation's word problem.  That is available for the
   commutative magma and is not available uniformly — there are finitely
   presented algebraic theories with undecidable word problems, so no
   construction uniform in ⟨Ω,E⟩ can take this route.  This file's
   deliverable is exactly such a uniform construction: [Free_Variety] is
   defined for EVERY [E], with no decidability hypothesis anywhere.

   So the setoid carrier is what buys UNIFORMITY, not existence.  The
   quotient becomes a choice of `≈` on the same carrier rather than a new
   type — the design Instance/Sets/Quotient.v's header states for
   quotients of sets — and the two varieties are deliberately built in the
   same shape, both as [Sub] of a category of algebras, so they read as
   siblings; #440's [Instance/Variety.v]'s [Variety_sub] is the model this
   file follows.

   ** Why the general theory is AXIOM-FREE although #440's [GroupVariety]
      is not

   This is the fact that makes the file possible, and it is worth stating
   precisely because it looks like a contradiction of #440.  The
   equations enter here ONLY through [EqSignature]'s [lhs_natural] and
   [rhs_natural] (Instance/Comp.v), and every construction
   below CONSUMES those fields; none of them proves one.  #440's
   [functional_extensionality_dep] is the cost of BUILDING a particular
   [EqSignature] — of discharging those two naturality fields for the
   group laws — not of using one.  Hence: the general adjunction is
   Closed under the global context, and INSTANTIATING it at
   [UA.GroupEq] is not.  [FreeGroupOn] and [FreeGroup_adjunction] below
   carry the axiom for exactly that inherited reason and are not gated;
   the depth-1 [CommMagmaFree] is closed and is.

   ** The congruence on terms is axiom-free, and #440 said otherwise

   Instance/Variety/Clone.v's "Not delivered" block declined a setoid on
   [Tree] on the ground that transitivity would have to invert
   [tree_equiv] at a node, wanting injectivity of [existT] on an
   [operation S] with no decidable equality, and so would risk
   [Eqdep]/[JMeq_eq].  That reason was WRONG and the block now says so:
   making symmetry and transitivity CONSTRUCTORS rather than theorems
   means no inversion is ever performed.  [tc_refl] is then derived by
   plain induction on the tree.

   CORRECTION (#450).  An earlier revision said here: "The relation must
   be [Type]-valued, not [Prop]-valued, because [Setoid]'s [equiv] is a
   crelation and [free_alg_ext_respects] eliminates a derivation into
   it."  [tree_equiv] is now [Prop]-valued.  The first half was never a
   reason: a [crelation] field accepts a [Prop]-valued relation by
   cumulativity, which is how [Tree_Setoid] now uses it.  The second
   stopped being one: the single elimination into a [Type]-sorted goal,
   [free_alg_ext_respects], now goes through the TARGET's [soa_prop]
   (next section): [pequiv_to] first turns the goal into a [Prop], and
   the derivation is eliminated into that, exactly as
   Instance/Mod/Free.v's [fv_eval_respects] did in the PR "algebraic
   carriers are sets".  The reason for the move is [soa_prop] (next
   section): [FreeSOA]'s `≈` must be interderivable with a
   [Prop]-valued relation, and a [Prop]-valued [tree_equiv] is that
   relation directly.  Necessity is argued, not measured: no alternative
   (a [Type]-valued [tree_equiv] beside a separate [Prop] mirror) was
   built or probed.  The [Prop] sort is also what
   Instance/Variety/Colimit.v's solution sets use: their kernel
   congruences are carrier-sized only as [Prop]s (Structure/Complete.v's
   size note, item 1).
   [About tree_equiv] now reports "may only be eliminated to produce
   values whose type is SProp or Prop", and Test/ProbeVarietyFree441.v's
   n4 pins the refusal of an elimination into a [Type]-sorted goal
   against a [Prop]-sorted control.  Its [_rect] and [_rec] eliminators
   are gone ([_ind] and [_sind] remain), and no gate line named them.

   [tc_gen] relates generators that are `≈` in the GENERATOR setoid, not
   merely equal ones; that is what makes the free construction a functor
   on [Sets] rather than on bare types.

   ** The carrier's `≈` is a proposition (#450)

   [SetoidOpAlgebra] carries a fourth field, [soa_prop : PropEquiv
   (is_setoid soa_obj)] (Lib/Setoid/Propositional.v), the same property
   the PR "algebraic carriers are sets" put on the object records of
   CMon, Rig and Grp.  The six construction sites that existed before
   #450 supply it: [FreeSOA] from the congruence itself
   ([PropEquiv_of_relation]), [soa_prod] as the conjunction of the
   factors', [leibniz_soa] and [F2] as [eq_PropEquiv],
   Instance/Variety/Spanning.v's [sa_soa] along the first projection
   ([sigma_first_PropEquiv]), and Test/ProbeVarietyFree441.v's
   [BoolCommMagma] as [eq_PropEquiv].  The three #450 adds are
   Instance/Variety/Limit.v's [svlim_soa] (Instance/Sets/Propositional.v's
   [limit_PropEquiv], from the components' fields) and
   Instance/Variety/Colimit.v's [VQ_soa] and [FQ_soa] (the indexing
   congruence itself).
   Measured with [About] under [Set Printing Universes] against the tree
   before #450: [SetoidAlgs] keeps its seven universe binders and gains
   exactly [Set < u1], its object universe; [SVariety] keeps fifteen and
   gains [Set < u7]; the record's sort goes from
   [Type@{max(u,u0,u1+1,u2+1)}] to [Type@{max(Set+1,u,u0,u1+1,u2+1)}];
   and [SVariety_Forget] goes from ten universe binders to eleven.
   Unlike CMon, no category here had to be pinned by hand.
   The theorems of Blocks F and H quantify over [SetoidOpAlgebra], so
   since #450 they range over algebras whose `≈` is a proposition, and
   they did NOT all become stronger.  Block F's [soa_prod_satisfies]
   quantifies over its algebras A and B outright, so it now says less:
   the old statement implies the new one by forgetting [soa_prop], and
   the new one says nothing about an algebra whose `≈` is not a
   proposition.  Block F's schema [not_equationally_definable] now asks
   for propositional witnesses A and B (weaker) while its soundness and
   completeness hypotheses range over fewer algebras (stronger), so it
   is incomparable with its old form.  Only Block H's two theorems,
   whose witness [F2] is fixed and carries [eq_PropEquiv bool], changed
   in their hypotheses alone, and each became (weakly) stronger (the
   comment opening Block H says so).

   ** Why not GAFT -- and, since #450, GAFT as well

   Mac Lane's own route is the adjoint functor theorem, and the tree has
   GAFT (Adjunction/GAFT.v).  The direct route here is two definitions
   over [universal_arrow_from_UMP] (Theory/Universal/Arrow.v), which is
   the same shape Construction/Free/Quiver.v already uses for the free
   category on a quiver.

   CORRECTION (#450).  An earlier revision of this block said GAFT
   "loses here on four counts, of which the universe pin is the least":
   it wants [Complete (SVariety E)], "which is not in hand";
   [PreservesImageLimit] for the forgetful functor, "likewise"; "a
   [SolutionSet] with §V.7's cardinality bound, which does not exist
   constructively in this setting at all", Instance/Comp.v's arities
   being ARBITRARY TYPES (its header says so in terms) so that "the
   subalgebra generated by the image" has no cardinality bound to state;
   and "the [Set] pin GAFT carries is real but is not why it loses".
   Measured since: the arities are still arbitrary types and no
   cardinality bound is stated anywhere, but none of the four counts
   stands.  Completeness and preservation are Instance/Variety/Limit.v's
   [SVariety_Complete] (limits computed on the compatible families of
   Instance/Sets/Complete.v) and [SVariety_Forget_continuous].  The
   solution set never needed a cardinality bound, only an index at the
   carrier universe (Structure/Complete.v's size note), and the
   [Prop]-valued congruences on the term algebra over [X] are such an
   index once every algebra carries [soa_prop]: that family is
   Instance/Variety/Colimit.v's [SVariety_Forget_solution_set], which
   REPLACES Mac Lane's generated-subalgebra family rather than bounding
   it.  The [Set] pin was removed from GAFT's signature by the PR
   "algebraic carriers are sets" (the size note's history paragraph),
   and [About Free_Variety_via_GAFT] instantiates no universe at [Set]:
   its one local mention of [Set] is the lower bound [Set < u9] on the
   carrier universe (the printed block also has [Set < Projections.u0],
   a bound on a stdlib global, of the kind this file's readbacks drop).
   That bound is [GAFT]'s: [GAFT] puts its solution set's index AT the
   carrier universe, and the congruence index, carrier-sized because
   every algebra carries [soa_prop], sits strictly above [Set].  Measured
   in a scratch file with the carrier at [Set]:
   [SVariety_Forget_solution_set] is accepted, and so is [GAFT] at
   [SVariety_Forget] with every argument but the solution set, while the
   full application is refused.  So Mac Lane's route is
   Instance/Variety/Colimit.v's [Free_Variety_via_GAFT], closed under the
   global context, and [Free_Variety_via_GAFT_agrees] identifies its
   left adjoint with [Free_Variety_Functor] up to natural isomorphism.

   The direct construction stays the primary one for two measured
   reasons.  It is TRANSPARENT where the other is not: [GAFT] ends in
   [Qed], so the GAFT left adjoint supports none of the [eq_refl]
   readbacks Test/ProbeVarietyFree441.v states for this one (its
   [p441_left_adjoint_obj] among them).  And GAFT does not avoid the
   construction: every member of the congruence-indexed solution set is
   this file's term algebra under a coarser `≈`, so the theorem reaches
   the free algebra only by way of the carrier built here.

   ** Transparency, measured

   Four [Defined] in this file, and exactly ONE is load-bearing: [FreeUA].
   Flipping it to [Qed] stops Test/ProbeVarietyFree441.v at
   [p441_left_adjoint_obj], the readback that the left adjoint's action
   on objects IS [Free_Variety] — which is only visible because the
   universal arrow's construction reduces.  The other three
   ([F2_HasDivision], [F2_IsField] and [EmptyEq]'s sibling work) flip
   cleanly and are transparent only by the convention that data-like
   constructions stay so.  Twenty-seven [Qed].

   Two names are used twice, for a [Section] and for a constant declared
   inside it: [SetoidAlgs] and [SVariety].  That is legal and the
   constant is what survives the section, but it is worth knowing when
   grepping.

   ** A degeneracy this does NOT rule out

   Axiom-freedom of the general adjunction is compatible with the free
   algebra being a single `≈`-class: for an [E] whose laws identify
   everything, [Free_Variety E X] is the one-point algebra and the
   adjunction still holds, axiom-free.  Nothing here excludes that, and
   nothing should — it is the correct answer for such an [E].  What rules
   it out at a PARTICULAR presentation is a separation result, and the
   one shipped is Test/ProbeVarietyFree441.v's [free_comm_not_collapsed]
   for the commutative magma.  No general non-collapse statement is made.

   ** Not delivered

   No [Free_Variety : Variety E] for #440's Leibniz variety.  Note the
   corrected reason: not "impossible" — it exists whenever the
   presentation has a computable normal form, and the free commutative
   magma was built that way to refute the earlier claim — but not
   uniformly in ⟨Ω,E⟩, which is what this file delivers.  The
   normal-form construction for that one presentation is about 250 lines
   concerning a single signature and is not shipped.  No
   Birkhoff HSP theorem: the non-example below is stated over a FIXED
   signature and rules out every [EqSignature RingOp] whose models are
   exactly the fields, which is what Mac Lane's remark needs and no more.
   No cardinality bound.  An earlier revision continued "and no solution
   set, hence no GAFT route"; since #450 both are in tree
   (Instance/Variety/Colimit.v's [SVariety_Forget_solution_set] and
   [Free_Variety_via_GAFT], "Why not GAFT" above), and the bound is
   still not stated because the congruence index makes it unnecessary.
   No functor [Variety E ⟶ SVariety E]: [leibniz_soa] is an object map only,
   so #440's category and this one are not related as categories here.
   No
   free ring, free abelian group or free module as named instances —
   those need their signatures spelled out, and the two shipped instances
   (the commutative magma and the group) are what the issue's own
   Verification block asks to run. *)

Module UA := Category.Instance.Comp.UniversalAlgebra.

(* The global [Obligation Tactic := cat_simpl] introduces binders under
   names of its own choosing, which makes obligation scripts brittle;
   Instance/Sets/Quotient.v sets it aside for the same reason and its
   header says so. *)
#[local] Obligation Tactic := idtac.

(** ** Block A: setoid algebras of an operation signature *)

Section SetoidAlgs.

Context (S : UA.OpSignature).

(* The carrier is a [SetoidObject], and each operation must respect `≈`
   argumentwise — the field that, in Instance/Variety/Clone.v's
   [SetoidAction], replaced functional extensionality.  Since #450 the
   carrier's `≈` is also required to be a proposition, [soa_prop]: the
   header's section "The carrier's `≈` is a proposition" says what that
   costs and what it buys. *)
Record SetoidOpAlgebra := {
  soa_obj : SetoidObject;
  soa_op  : ∀ o : UA.operation S, (UA.arity o → soa_obj) → soa_obj;
  soa_op_respects : ∀ (o : UA.operation S) (k1 k2 : UA.arity o → soa_obj),
    (∀ j, k1 j ≈ k2 j) → soa_op o k1 ≈ soa_op o k2;
  soa_prop : PropEquiv (is_setoid soa_obj)
}.

(* Forgetting the setoid gives an ordinary [OpAlgebra], which is how the
   equations of an [EqSignature] are read on a setoid algebra at all. *)
Definition soa_alg (A : SetoidOpAlgebra) : UA.OpAlgebra S :=
  UA.Build_OpAlgebra S (carrier (soa_obj A)) (soa_op A).

Record SAlgHom (A B : SetoidOpAlgebra) := {
  salg_map :> soa_obj A → soa_obj B;
  salg_respects : Proper (equiv ==> equiv) salg_map;
  salg_commute : ∀ (o : UA.operation S) (args : UA.arity o → soa_obj A),
    salg_map (soa_op A o args) ≈ soa_op B o (fun i => salg_map (args i))
}.

Arguments salg_map {_ _} _ _.
Arguments salg_respects {_ _} _.
Arguments salg_commute {_ _} _ _ _.

Program Definition SAlgHom_Setoid (A B : SetoidOpAlgebra) : Setoid (SAlgHom A B) := {|
  equiv := fun f g => ∀ x, salg_map f x ≈ salg_map g x
|}.
Next Obligation.
  intros A B; constructor; repeat intro.
  - reflexivity.
  - symmetry; auto.
  - transitivity (salg_map y x0); auto.
Qed.

Program Definition SAlg_id (A : SetoidOpAlgebra) : SAlgHom A A := {|
  salg_map := fun x => x
|}.
Next Obligation. intros A; repeat intro; auto. Qed.
Next Obligation. intros A o args; simpl; reflexivity. Qed.

Program Definition SAlg_comp (A B C : SetoidOpAlgebra)
  (f : SAlgHom B C) (g : SAlgHom A B) : SAlgHom A C := {|
  salg_map := fun x => salg_map f (salg_map g x)
|}.
Next Obligation.
  intros A B C f g x y Hxy.
  apply (salg_respects f), (salg_respects g), Hxy.
Qed.
(* Explicit [transitivity] rather than [rewrite]: the setoid rewrite
   cannot infer a [Proper] instance for the composite's outer map, since
   respectfulness here is a FIELD of [SAlgHom] and not a registered
   instance. *)
Next Obligation.
  intros A B C f g o args; simpl.
  transitivity (salg_map f (soa_op B o (fun i => salg_map g (args i)))).
  - apply (salg_respects f), (salg_commute g).
  - apply (salg_commute f).
Qed.

Program Definition SetoidAlgs : Category := {|
  obj     := SetoidOpAlgebra;
  hom     := SAlgHom;
  homset  := SAlgHom_Setoid;
  id      := SAlg_id;
  compose := SAlg_comp
|}.
(* Binder names are chosen here rather than inherited: with
   [Obligation Tactic := idtac] nothing is pre-introduced, and naming
   them makes the script independent of Coq's generated names. *)
Next Obligation.
  simpl; intros A B C f f' Hf g g' Hg z.
  transitivity (salg_map f (salg_map g' z)).
  - apply (salg_respects f), Hg.
  - apply Hf.
Qed.
Next Obligation. repeat intro; simpl; reflexivity. Qed.
Next Obligation. repeat intro; simpl; reflexivity. Qed.
Next Obligation. repeat intro; simpl; reflexivity. Qed.
Next Obligation. repeat intro; simpl; reflexivity. Qed.

End SetoidAlgs.

Arguments soa_obj {_} _.
Arguments soa_op {_} _ _ _.
Arguments soa_op_respects {_} _ _ _ _ _.
Arguments soa_prop {_} _.
Arguments soa_alg {_} _.
Arguments salg_map {_ _ _} _ _.
Arguments salg_respects {_ _ _} _.
Arguments salg_commute {_ _ _} _ _ _.


(** ** Block B: the setoid variety *)

Section SVariety.

Context {S : UA.OpSignature}.
Context (E : UA.EqSignature S).

(* Satisfaction, now up to the carrier's own `≈` rather than Leibniz [=].
   The equations are read through [soa_alg], so [UA.lhs] and [UA.rhs] are
   exactly Instance/Comp.v's. *)
Definition ssatisfies (A : SetoidOpAlgebra S) : Type :=
  ∀ (e : UA.eq S E) (args : UA.eq_arity e → carrier (soa_obj A)),
    @UA.lhs S E (soa_alg A) e args ≈ @UA.rhs S E (soa_alg A) e args.

Definition SVariety_sub : Subcategory (SetoidAlgs S) :=
  @Build_Subcategory (SetoidAlgs S)
    ssatisfies
    (fun _ _ _ _ _ => True)
    (fun _ _ _ _ _ _ _ _ _ _ => I)
    (fun _ _ => I).

Definition SVariety : Category := Sub (SetoidAlgs S) SVariety_sub.

Definition SVariety_Full : Full (SetoidAlgs S) SVariety_sub :=
  fun _ _ _ _ _ => I.

Definition SVariety_Incl : SVariety ⟶ SetoidAlgs S :=
  Incl (SetoidAlgs S) SVariety_sub.

(* The underlying-set functor.  Unlike #440's [Variety_Forget], which
   lands on the DISCRETE setoid because its carriers are bare types, this
   one carries the algebra's own setoid.  An earlier revision added "which
   is what lets a free object exist over it"; that is false for the same
   reason the header records — free objects can exist over the discrete
   one too, for presentations with a normal form.  What the algebra's own
   setoid buys is that the free object exists for EVERY [E], uniformly. *)
Program Definition SVariety_Forget : SVariety ⟶ Sets := {|
  fobj := fun A => soa_obj (`1 A);
  fmap := fun _ _ f => {| morphism := salg_map (`1 f) |}
|}.
Next Obligation. intros A B f; apply (salg_respects (`1 f)). Qed.
Next Obligation. repeat intro; simpl; auto. Qed.
Next Obligation. repeat intro; simpl; reflexivity. Qed.
Next Obligation. repeat intro; simpl; reflexivity. Qed.

Lemma SVariety_Forget_Faithful : Functor.Faithful SVariety_Forget.
Proof. construct; simpl in *; auto. Qed.

End SVariety.

Arguments ssatisfies {_} _ _.
Arguments SVariety {_} _.
Arguments SVariety_sub {_} _.
Arguments SVariety_Full {_} _.
Arguments SVariety_Incl {_} _.
Arguments SVariety_Forget {_} _.
Arguments SVariety_Forget_Faithful {_} _.

(** ** Block C: the free algebra — terms modulo the congruence

    The carrier is Instance/Comp.v's [Tree], UNCHANGED; what is new is
    the equivalence it is equipped with.  Nothing is rebuilt, which is
    what makes this honest to the issue's phrase "the term algebra
    quotiented by the congruence generated by E": the quotient is a
    coarser `≈` on the same carrier, not a new type. *)

Section FreeVariety.

Context {S : UA.OpSignature}.
Context (E : UA.EqSignature S).
Context (X : SetoidObject).

(* Symmetry and transitivity are CONSTRUCTORS, not theorems.  That is the
   whole trick: no inversion is ever performed on a derivation, so the
   [Eqdep]/[JMeq_eq] hazard Instance/Variety/Clone.v feared does not
   arise.  [Prop]-valued since #450; an earlier revision said
   "[Type]-valued because [Setoid]'s [equiv] is a crelation", and the
   header's correction under "The congruence on terms is axiom-free"
   says why that was no reason. *)
Inductive tree_equiv : UA.Tree S X → UA.Tree S X → Prop :=
  | tc_gen : ∀ x y : X, x ≈ y →
      tree_equiv (UA.generator S X x) (UA.generator S X y)
  | tc_op : ∀ (o : UA.operation S) (k1 k2 : UA.arity o → UA.Tree S X),
      (∀ j, tree_equiv (k1 j) (k2 j)) →
      tree_equiv (UA.node S X o k1) (UA.node S X o k2)
  | tc_law : ∀ (e : UA.eq S E) (args : UA.eq_arity e → UA.Tree S X),
      tree_equiv (@UA.lhs S E (UA.Free S X) e args)
                 (@UA.rhs S E (UA.Free S X) e args)
  | tc_sym : ∀ t u, tree_equiv t u → tree_equiv u t
  | tc_trans : ∀ t u v, tree_equiv t u → tree_equiv u v → tree_equiv t v.

(* Reflexivity is DERIVED, by plain induction on the tree — again no
   inversion.  The generator case needs [X]'s own reflexivity, which is
   where the setoid on the generators enters. *)
Fixpoint tc_refl (t : UA.Tree S X) : tree_equiv t t :=
  match t with
  | UA.generator _ _ x => tc_gen x x (reflexivity x)
  | UA.node _ _ o k    => tc_op o k k (fun j => tc_refl (k j))
  end.

Program Definition Tree_Setoid : Setoid (UA.Tree S X) := {|
  equiv := tree_equiv
|}.
Next Obligation.
  constructor.
  - exact tc_refl.
  - exact tc_sym.
  - exact tc_trans.
Qed.

Definition FreeSOA : SetoidOpAlgebra S := {|
  soa_obj := {| carrier := UA.Tree S X ; is_setoid := Tree_Setoid |};
  soa_op  := UA.node S X;
  soa_op_respects := tc_op;
  soa_prop := @PropEquiv_of_relation _ Tree_Setoid tree_equiv
                (fun _ _ h => h) (fun _ _ h => h)
|}.

(* The laws hold in the free algebra BY CONSTRUCTION — [tc_law] is
   literally the satisfaction proof, which is the sense in which the
   congruence is "generated by E". *)
Definition FreeSOA_satisfies : ssatisfies E FreeSOA := tc_law.

Definition Free_Variety : SVariety E := (FreeSOA; FreeSOA_satisfies).

End FreeVariety.

Arguments tree_equiv {_} _ _ _ _.
Arguments tc_refl {_ _ _} _.
Arguments Tree_Setoid {_} _ _.
Arguments FreeSOA {_} _ _.
Arguments FreeSOA_satisfies {_} _ _.
Arguments Free_Variety {_} _ _.

(** ** Block D: the universal property

    Every map from the generators into an algebra of the variety extends
    to a unique homomorphism.  The extension is Instance/Comp.v's
    [induced_map] verbatim — nothing is re-recursed — so the only work is
    showing it respects the congruence, and THAT is where the variety's
    satisfaction of the laws is consumed. *)

Section FreeUP.

Context {S : UA.OpSignature}.
Context (E : UA.EqSignature S).
Context (X : SetoidObject).
Context (A : SVariety E).
Context (h : X ~{Sets}~> soa_obj (`1 A)).

Definition free_alg_ext : UA.Tree S X → soa_obj (`1 A) :=
  UA.induced_map S X (soa_alg (`1 A)) h.

(* The congruence is respected.  Each constructor is discharged by the
   corresponding structure of [A]: [tc_gen] by [h]'s respectfulness,
   [tc_op] by [soa_op_respects], and [tc_law] — the only interesting
   case — by [A]'s own satisfaction proof, transported along the
   naturality of [lhs]/[rhs] at [induced_hom].

   Since #450 the derivation is a [Prop] and the goal is the [Type]-valued
   `≈` of [A], so the proof first moves to [A]'s propositional mirror with
   [pequiv_to], eliminates the derivation there, and returns each branch
   with [pequiv_from].  An earlier revision called this lemma "the single
   place where [EqSignature]'s naturality fields are CONSUMED, and the
   reason the whole development is axiom-free".  It was not the single
   place even in this file -- [soa_prod_satisfies] below consumes them too
   -- and since #450 Instance/Variety/Limit.v's [svlim_satisfies] and
   Instance/Variety/Colimit.v's [vker_cong] do as well.  What makes the
   development axiom-free is that every consumer CONSUMES those fields and
   none proves one, as the header says. *)
Lemma free_alg_ext_respects (t u : UA.Tree S X) :
  tree_equiv E X t u → free_alg_ext t ≈ free_alg_ext u.
Proof.
  intro D.
  apply (@pequiv_to _ _ (soa_prop (`1 A))).
  induction D as [ x y Hxy | o k1 k2 Hk IH | e args | t u D IH | t u v D1 IH1 D2 IH2 ].
  - apply pequiv_from; exact (proper_morphism h x y Hxy).
  - apply pequiv_from; apply (soa_op_respects (`1 A) o);
      intro j; exact (pequiv_to _ _ (IH j)).
  - apply pequiv_from; unfold free_alg_ext.
    (* [UA.map (induced_hom …)] and [induced_map …] are convertible but
       not syntactically equal, and [simpl] on the naturality equation
       also unfolds [soa_alg] and so walks away from the goal's shape.
       So each equation is ASSERTED at exactly the shape the goal has and
       discharged by [exact], which uses full conversion. *)
    assert (HL : UA.induced_map S X (soa_alg (`1 A)) h
                   (@UA.lhs S E (UA.Free S X) e args)
                 = @UA.lhs S E (soa_alg (`1 A)) e
                     (fun i => UA.induced_map S X (soa_alg (`1 A)) h (args i)))
      by exact (@UA.lhs_natural S E (UA.Free S X) (soa_alg (`1 A))
                  (UA.induced_hom S X (soa_alg (`1 A)) h) e args).
    assert (HR : UA.induced_map S X (soa_alg (`1 A)) h
                   (@UA.rhs S E (UA.Free S X) e args)
                 = @UA.rhs S E (soa_alg (`1 A)) e
                     (fun i => UA.induced_map S X (soa_alg (`1 A)) h (args i)))
      by exact (@UA.rhs_natural S E (UA.Free S X) (soa_alg (`1 A))
                  (UA.induced_hom S X (soa_alg (`1 A)) h) e args).
    rewrite HL, HR.
    exact (`2 A e (fun i => UA.induced_map S X (soa_alg (`1 A)) h (args i))).
  - symmetry; exact IH.
  - transitivity (free_alg_ext u); assumption.
Qed.

Program Definition free_alg_hom : Free_Variety E X ~{SVariety E}~> A :=
  ({| salg_map := free_alg_ext |}; I).
Next Obligation. repeat intro; apply free_alg_ext_respects; assumption. Qed.
Next Obligation. intros o args; simpl; reflexivity. Qed.

(* Uniqueness: two homomorphisms out of the free algebra that agree on
   generators agree everywhere, by induction on the term. *)
Theorem free_alg_hom_unique (f g : Free_Variety E X ~{SVariety E}~> A) :
  (∀ x : X, salg_map (`1 f) (UA.generator S X x)
              ≈ salg_map (`1 g) (UA.generator S X x)) →
  f ≈ g.
Proof.
  intros Hgen t.
  induction t as [ x | o k IH ]; simpl.
  - exact (Hgen x).
  - transitivity (soa_op (`1 A) o (fun j => salg_map (`1 f) (k j))).
    + exact (salg_commute (`1 f) o k).
    + transitivity (soa_op (`1 A) o (fun j => salg_map (`1 g) (k j))).
      * apply (soa_op_respects (`1 A) o); exact IH.
      * symmetry; exact (salg_commute (`1 g) o k).
Qed.

End FreeUP.

Arguments free_alg_ext {_ _ _} _ _ _.
Arguments free_alg_hom {_ _ _} _ _.
(* [h] is absent from this statement, so the section discharges only
   S, E, X and A — hence four arguments, not five. *)
Arguments free_alg_hom_unique {_ _ _} _ _ _ _.

(** ** Block E: the adjunction

    Blocks C and D are exactly a universal arrow from each set to the
    forgetful functor, so the packaging is
    Theory/Universal/Arrow.v's [universal_arrow_from_UMP] followed by
    [AdjunctionFromUniversalArrows] — the same two steps
    Construction/Free/Quiver.v uses for the free category on a
    quiver. *)

Section FreeAdjunction.

Context {S : UA.OpSignature}.
Context (E : UA.EqSignature S).

(* The unit: a generator is its own term.  It respects `≈` by [tc_gen],
   which is the clause that made the generators' setoid matter. *)
Program Definition free_unit (X : Sets) :
  X ~{Sets}~> SVariety_Forget E (Free_Variety E X) := {|
  morphism := UA.generator S X
|}.
Next Obligation. intros X x y Hxy; exact (tc_gen E X x y Hxy). Qed.

Definition FreeUA (X : Sets) : @UniversalArrow Sets (SVariety E) X (SVariety_Forget E).
Proof.
  unshelve eapply (universal_arrow_from_UMP X (SVariety_Forget E)
                     (Free_Variety E X) (free_unit X)).
  intros A h.
  unshelve econstructor.
  - exact (free_alg_hom A h).
  - simpl; intro x; reflexivity.
  - simpl; intros g Hg.
    (* [salg_map] of the extension at a generator iota-reduces to [h x],
       so [Hg] already has the needed type up to conversion and [exact]
       takes it. *)
    exact (free_alg_hom_unique A (free_alg_hom A h) g (fun x => Hg x)).
Defined.

Definition Free_Variety_Functor : Sets ⟶ SVariety E :=
  LeftAdjointFunctorFromUniversalArrows (SVariety_Forget E) FreeUA.

Definition Free_Variety_adjunction :
  Free_Variety_Functor ⊣ SVariety_Forget E :=
  AdjunctionFromUniversalArrows (SVariety_Forget E) FreeUA.

End FreeAdjunction.

Arguments free_unit {_} _ _.
Arguments FreeUA {_} _ _.
Arguments Free_Variety_Functor {_} _.
Arguments Free_Variety_adjunction {_} _.

(** ** Block F: products, and what they rule out

    Varieties are closed under products, and that is the lever for
    Mac Lane's field non-example: a class of algebras that is NOT closed
    under products cannot be the models of any equational theory over
    its signature, whatever the equations are.

    [soa_prod] is the componentwise CONSTRUCTION and nothing more is
    claimed for it: the two projections are shipped, but no pairing map,
    no triangle and no uniqueness, so it is NOT established here to be
    the categorical product of [SetoidAlgs S] — the name is descriptive.
    Closure under this construction is all the non-example needs.
    Instance/Variety/Limit.v (#450) builds the limits of [SVariety E],
    binary products among them, on a different carrier -- the compatible
    families over a shape -- and does not relate [soa_prod] to them. *)

Section Products.

Context {S : UA.OpSignature}.
Context (E : UA.EqSignature S).

Program Definition soa_prod_setoid (A B : SetoidOpAlgebra S) :
  Setoid (carrier (soa_obj A) * carrier (soa_obj B)) := {|
  equiv := fun p q => (fst p ≈ fst q) * (snd p ≈ snd q)
|}.
Next Obligation.
  intros A B; constructor; repeat intro.
  - split; reflexivity.
  - split; symmetry; apply X.
  - split; [ transitivity (fst y) | transitivity (snd y) ]; first [ apply X | apply X0 ].
Qed.

Definition soa_prod (A B : SetoidOpAlgebra S) : SetoidOpAlgebra S := {|
  soa_obj := {| carrier := carrier (soa_obj A) * carrier (soa_obj B)
              ; is_setoid := soa_prod_setoid A B |};
  soa_op  := fun o k => (soa_op A o (fun i => fst (k i)),
                         soa_op B o (fun i => snd (k i)));
  soa_op_respects := fun o k1 k2 H =>
    (soa_op_respects A o _ _ (fun j => fst (H j)),
     soa_op_respects B o _ _ (fun j => snd (H j)));
  soa_prop := @PropEquiv_of_relation _ (soa_prod_setoid A B)
    (fun p q => @pequiv _ _ (soa_prop A) (fst p) (fst q)
                /\ @pequiv _ _ (soa_prop B) (snd p) (snd q))
    (fun p q h => (pequiv_to _ _ (proj1 h), pequiv_to _ _ (proj2 h)))
    (fun p q h => conj (pequiv_from _ _ (fst h)) (pequiv_from _ _ (snd h)))
|}.

(* The two projections are homomorphisms ON THE NOSE: the product's
   operation is literally the pair of the components', so [op_commute] is
   [eq_refl].  They are [Instance/Comp.v] [AlgHom]s rather than
   [SAlgHom]s because that is what [lhs_natural] consumes. *)

Program Definition soa_prod_exl (A B : SetoidOpAlgebra S) :
  UA.AlgHom (soa_alg (soa_prod A B)) (soa_alg A) := {| UA.map := fst |}.
Next Obligation. intros A B o args; reflexivity. Qed.

Program Definition soa_prod_exr (A B : SetoidOpAlgebra S) :
  UA.AlgHom (soa_alg (soa_prod A B)) (soa_alg B) := {| UA.map := snd |}.
Next Obligation. intros A B o args; reflexivity. Qed.

(* Satisfaction is componentwise.  It needs no extensionality, and the
   operative reason is the one the proof uses: each component is the
   factor's own satisfaction transported along a PROJECTION by
   [lhs_natural]/[rhs_natural] — consuming those fields, as everywhere
   else here, rather than proving them.  An earlier revision gave the
   reason as "because the product setoid is componentwise `≈`", which is
   a property of the construction rather than of this proof and is not
   what discharges the goal. *)
Theorem soa_prod_satisfies (A B : SetoidOpAlgebra S) :
  ssatisfies E A → ssatisfies E B → ssatisfies E (soa_prod A B).
Proof.
  intros HA HB e args.
  split.
  - assert (HL : fst (@UA.lhs S E (soa_alg (soa_prod A B)) e args)
                 = @UA.lhs S E (soa_alg A) e (fun i => fst (args i)))
      by exact (@UA.lhs_natural S E (soa_alg (soa_prod A B)) (soa_alg A)
                  (soa_prod_exl A B) e args).
    assert (HR : fst (@UA.rhs S E (soa_alg (soa_prod A B)) e args)
                 = @UA.rhs S E (soa_alg A) e (fun i => fst (args i)))
      by exact (@UA.rhs_natural S E (soa_alg (soa_prod A B)) (soa_alg A)
                  (soa_prod_exl A B) e args).
    rewrite HL, HR.
    exact (HA e (fun i => fst (args i))).
  - assert (HL : snd (@UA.lhs S E (soa_alg (soa_prod A B)) e args)
                 = @UA.lhs S E (soa_alg B) e (fun i => snd (args i)))
      by exact (@UA.lhs_natural S E (soa_alg (soa_prod A B)) (soa_alg B)
                  (soa_prod_exr A B) e args).
    assert (HR : snd (@UA.rhs S E (soa_alg (soa_prod A B)) e args)
                 = @UA.rhs S E (soa_alg B) e (fun i => snd (args i)))
      by exact (@UA.rhs_natural S E (soa_alg (soa_prod A B)) (soa_alg B)
                  (soa_prod_exr A B) e args).
    rewrite HL, HR.
    exact (HB e (fun i => snd (args i))).
Qed.

End Products.

Arguments soa_prod_setoid {_} _ _.
Arguments soa_prod_exl {_} _ _.
Arguments soa_prod_exr {_} _ _.
Arguments soa_prod {_} _ _.
Arguments soa_prod_satisfies {_} _ _ _ _ _ _ _.

(* The schema Mac Lane's remark needs: if a property P of setoid algebras
   holds of two algebras but not of their product, then no equational
   theory over that signature has exactly the P-algebras as its models.
   Stated over a FIXED signature — this is not Birkhoff's HSP theorem and
   does not pretend to be. *)
Theorem not_equationally_definable {S : UA.OpSignature}
  (P : SetoidOpAlgebra S → Type) (A B : SetoidOpAlgebra S)
  (HA : P A) (HB : P B) (Hprod : P (soa_prod A B) → False) :
  ∀ E : UA.EqSignature S,
    (∀ C : SetoidOpAlgebra S, P C → ssatisfies E C) →
    (∀ C : SetoidOpAlgebra S, ssatisfies E C → P C) →
    False.
Proof.
  intros E Hsound Hcomplete.
  apply Hprod, Hcomplete.
  exact (soa_prod_satisfies E A B (Hsound A HA) (Hsound B HB)).
Qed.

(** ** Block G: worked instances

    The depth-1 one is axiom-free and gated; the group one inherits
    #440's [functional_extensionality_dep] through [UA.GroupEq] and is
    not.  Both are here so the contrast is visible in one place. *)

Definition CommMagmaFree (X : Sets) : SVariety CommEq := Free_Variety CommEq X.

(* The axiom-free NAMED instance.  An audit pointed out that the only
   named concrete adjunction here was the group one, which carries the
   axiom — so the headline result had no closed instance under a name of
   its own. *)
Definition CommMagmaFree_adjunction :
  Free_Variety_Functor CommEq ⊣ SVariety_Forget CommEq :=
  Free_Variety_adjunction CommEq.

Definition SGroupVariety : Category := SVariety UA.GroupEq.

Definition FreeGroupOn (X : Sets) : SGroupVariety := Free_Variety UA.GroupEq X.

Definition FreeGroup_adjunction :
  Free_Variety_Functor UA.GroupEq ⊣ SVariety_Forget UA.GroupEq :=
  Free_Variety_adjunction UA.GroupEq.

(* Every Leibniz algebra is a setoid algebra on the discrete setoid, so
   #440's objects embed here — but the passage costs the axiom, because
   [soa_op_respects] at [eq_Setoid] is exactly what extensionality
   supplies. *)
Definition leibniz_soa {S : UA.OpSignature} (A : UA.OpAlgebra S) :
  SetoidOpAlgebra S := {|
  soa_obj := {| carrier := UA.carrier A ; is_setoid := eq_Setoid (UA.carrier A) |};
  soa_op  := UA.op A;
  soa_op_respects := fun o k1 k2 H =>
    f_equal (UA.op A o) (functional_extensionality_dep k1 k2 H);
  soa_prop := eq_PropEquiv (UA.carrier A)
|}.

(** ** Block H: fields are not a variety

    Mac Lane's remark is that the free-algebra construction gives free
    rings, free abelian groups and free modules but NOT free fields.  The
    issue states the reason as "the multiplicative inverse is a partial
    operation", which is the motivation; the PROOF is the one Mac Lane's
    own framework supplies and it is a different argument — varieties are
    closed under products, and fields are not.  [F2 × F2] has a nonzero
    element with no inverse.

    TWO statements are shipped, and the difference between them is the
    substance of an audit finding.  The weaker one,
    [division_is_not_equationally_definable], is about the DIVISION
    PROPERTY alone; an earlier revision called that predicate [IsField]
    and claimed the theorem ruled out every [EqSignature RingOp] whose
    models are exactly the fields.  It did not, and the counterexamples
    are cheap: the one-element algebra has the division property (and
    [1 = 0] in it), and so does a "ring" whose addition has no unit — so
    no [E] whose models are exactly the fields can satisfy that theorem's
    soundness hypothesis, and the theorem said nothing about such an [E].
    The stronger one, [fields_are_not_a_variety], is stated over an
    [IsField] that imposes the ring axioms, additive inverses, [1 ≉ 0]
    and division, and it does say what its name says.

    The quantifier is still worth reading exactly: this rules out every
    [EqSignature RingOp] whose models are exactly the fields, over this
    FIXED signature.  It is not Birkhoff's HSP theorem and does not imply
    it.  Note also that [RingOp] carries no negation operation, which is
    why additive inverses appear in [IsField] as a Σ-clause rather than
    as an operation.

    Since #450 [SetoidOpAlgebra] carries [soa_prop], so "the fields" here
    are the fields whose carrier's `≈` is a proposition, [F2] supplying
    it as [eq_PropEquiv bool].  Both theorems' soundness and completeness
    hypotheses quantify over [SetoidOpAlgebra RingOp] and so over fewer
    algebras than before, which makes each (weakly) stronger. *)

Inductive ring_op : Set := rzero | rone | radd | rmul.

Definition RingOp : UA.OpSignature := {|
  UA.operation := ring_op;
  UA.arity := fun o => match o with
                       | rzero | rone => UA.nullary
                       | radd | rmul  => UA.binary
                       end
|}.

(* The signature argument of [UA.arity] must be given explicitly in the
   return clause: [UA.operation RingOp] reduces to [ring_op], and the
   elaborator will not run that delta backwards to recover [RingOp] from
   the match variable.  Instance/Comp.v annotates for the same
   reason. *)
Definition F2_op (o : UA.operation RingOp) : (UA.arity o → bool) → bool :=
  match o as o0 return (@UA.arity RingOp o0 → bool) → bool with
  | rzero => fun _ => false
  | rone  => fun _ => true
  | radd  => fun k => xorb (k UA.Fst) (k UA.Snd)
  | rmul  => fun k => andb (k UA.Fst) (k UA.Snd)
  end.

(* Respectfulness needs NO extensionality even at the discrete setoid,
   because each operation reads its bundle only at the finitely many
   elements of the arity. *)
Program Definition F2 : SetoidOpAlgebra RingOp := {|
  soa_obj := {| carrier := bool ; is_setoid := eq_Setoid bool |};
  soa_op  := F2_op;
  soa_prop := eq_PropEquiv bool
|}.
Next Obligation.
  intros o k1 k2 H; destruct o as [ | | | ]; simpl in *; try reflexivity;
    rewrite (H UA.Fst), (H UA.Snd); reflexivity.
Qed.

Definition r_zero (A : SetoidOpAlgebra RingOp) : carrier (soa_obj A) :=
  soa_op A rzero (fun i => match i return carrier (soa_obj A) with end).

Definition r_one (A : SetoidOpAlgebra RingOp) : carrier (soa_obj A) :=
  soa_op A rone (fun i => match i return carrier (soa_obj A) with end).

Definition r_mul (A : SetoidOpAlgebra RingOp)
  (x y : carrier (soa_obj A)) : carrier (soa_obj A) :=
  soa_op A rmul (fun i => match i with UA.Fst => x | UA.Snd => y end).

Definition r_add (A : SetoidOpAlgebra RingOp)
  (x y : carrier (soa_obj A)) : carrier (soa_obj A) :=
  soa_op A radd (fun i => match i with UA.Fst => x | UA.Snd => y end).

(* THE DIVISION PROPERTY ALONE — every nonzero element has a right
   inverse for multiplication.  An earlier revision called this [IsField]
   and an audit was right to object: it imposes no ring axiom and does
   not ask [1 ≉ 0], so the ONE-ELEMENT algebra satisfies it, and so does
   a "ring" with no additive unit.  The name now says what it is, and the
   theorem built from it below says what that theorem actually rules out.

   It is [Type]-valued because it returns a chosen inverse.  An earlier
   revision gave the reason as "since it must feed
   [not_equationally_definable]", which is false — that schema takes a
   [Prop]-valued [P] perfectly well. *)
Definition HasDivision (A : SetoidOpAlgebra RingOp) : Type :=
  ∀ x : carrier (soa_obj A),
    (x ≈ r_zero A → False) → { y : carrier (soa_obj A) & r_mul A x y ≈ r_one A }.

Definition F2_HasDivision : HasDivision F2.
Proof.
  intros x Hx.
  destruct x.
  - exists true; reflexivity.
  - destruct (Hx eq_refl).
Defined.

(* [(true, false)] is nonzero and has no inverse: the second component of
   any product with it is [false], never [true]. *)
Definition F2xF2_no_division : HasDivision (soa_prod F2 F2) → False.
Proof.
  intro HF.
  destruct (HF (true, false)) as [y Hy].
  - intro Hz; destruct Hz as [H1 H2]; simpl in H1; discriminate H1.
  - destruct Hy as [H1 H2]; simpl in H2; discriminate H2.
Defined.

Definition division_is_not_equationally_definable :
  ∀ E : UA.EqSignature RingOp,
    (∀ C : SetoidOpAlgebra RingOp, HasDivision C → ssatisfies E C) →
    (∀ C : SetoidOpAlgebra RingOp, ssatisfies E C → HasDivision C) →
    False :=
  not_equationally_definable HasDivision F2 F2
    F2_HasDivision F2_HasDivision F2xF2_no_division.

(** *** And now the statement Mac Lane's remark actually needs

    [IsField] imposes the ring axioms, additive inverses (as a Σ-clause,
    since [RingOp] carries no negation operation), [1 ≉ 0], and division.
    With it, [fields_are_not_a_variety] says what its name says. *)

Definition IsField (A : SetoidOpAlgebra RingOp) : Type :=
  (((∀ x y z, r_add A (r_add A x y) z ≈ r_add A x (r_add A y z)) *
    (∀ x y, r_add A x y ≈ r_add A y x) *
    (∀ x, r_add A x (r_zero A) ≈ x) *
    (∀ x, { y & r_add A x y ≈ r_zero A }) *
    (∀ x y z, r_mul A (r_mul A x y) z ≈ r_mul A x (r_mul A y z)) *
    (∀ x y, r_mul A x y ≈ r_mul A y x) *
    (∀ x, r_mul A x (r_one A) ≈ x) *
    (∀ x y z, r_mul A x (r_add A y z) ≈ r_add A (r_mul A x y) (r_mul A x z)) *
    ((r_one A ≈ r_zero A) → False))
   * HasDivision A)%type.

Definition F2_IsField : IsField F2.
Proof.
  unfold IsField, HasDivision; simpl.
  refine ((((((((( _ , _ ) , _ ) , _ ) , _ ) , _ ) , _ ) , _ ) , _ ) , _ );
    try solve [ intros; repeat match goal with [ x : bool |- _ ] => destruct x end;
                simpl; reflexivity ].
  all: try solve [ intro x; exists x; destruct x; reflexivity ].
  all: try solve [ intro H; discriminate H ].
  all: try solve [ intros x Hx; destruct x;
                   [ exists true; reflexivity | destruct (Hx eq_refl) ] ].
Defined.

Definition F2xF2_not_field : IsField (soa_prod F2 F2) → False :=
  fun HF => F2xF2_no_division (snd HF).

Definition fields_are_not_a_variety :
  ∀ E : UA.EqSignature RingOp,
    (∀ C : SetoidOpAlgebra RingOp, IsField C → ssatisfies E C) →
    (∀ C : SetoidOpAlgebra RingOp, ssatisfies E C → IsField C) →
    False :=
  not_equationally_definable IsField F2 F2 F2_IsField F2_IsField F2xF2_not_field.
