Require Import Category.Lib.
Require Import Category.Lib.Setoid.Propositional.
Require Import Category.Theory.Category.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Morphisms.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Subobject.
Require Import Category.Theory.Subobject.Lattice.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Comp.
Require Import Category.Instance.Variety.
Require Import Category.Instance.Variety.Free.
Require Import Category.Adjunction.GAFT.
Require Import Category.Adjunction.SpanningArrow.

Generalizable All Variables.

(** * Spanning arrows for a variety: Mac Lane's Remark 1 *)

(* nLab: https://ncatlab.org/nlab/show/subobject
   nLab: https://ncatlab.org/nlab/show/solution+set+condition
   nLab: https://ncatlab.org/nlab/show/variety+of+algebras

   Mac Lane, "Categories for the Working Mathematician", 2nd ed. (GTM 5),
   §V.7 ("Subobjects and Generators"), book pp. 127-128 (PDF pp. 136-137).
   Definition 6 calls an arrow f : x → G a SPANNING when it factors
   through no proper subobject of a; Lemma 2 says that when every family
   of subobjects of A has an intersection and G preserves those
   intersections, every arrow factors through a spanning one, so the
   spanning arrows out of x form a solution set; Remark 1 is the
   application Mac Lane cares about -- for the underlying-set functor of
   a variety the spanning factorization is the SUBALGEBRA GENERATED BY
   THE IMAGE, and the solution set it yields is what the free-algebra
   construction runs on.

   THIS FILE IS THE REMARK, NOT THE LEMMA.  The definitions are the
   frozen ones of Adjunction/SpanningArrow.v -- [SubFactorsThrough],
   [Spanning] and [SpanningArrowsOutOf] -- and nothing here renames or
   restates them.  The general Lemma is the other half of
   #448 and is not repeated.

   ** Why the Remark is proved DIRECTLY and not through the Lemma

   The Lemma takes the intersection of all subobjects a given arrow
   factors through, which in this library is
   Theory/Subobject/Lattice.v's [sub_wide_intersection] (and its
   [sub_intersection] under Structure/Pullback/Wide.v's
   [HasWidePullbacks]).  Both want wide pullbacks in the ambient
   category, and [SVariety] has none in tree: over this worktree,
   every file OTHER THAN THIS ONE naming [HasPullbacks] or
   [HasWidePullbacks] and also naming [SVariety] numbers ZERO
   (find . -name '*.v' | xargs grep -ln 'HasWidePullbacks\|HasPullbacks'
   | xargs grep -l 'SVariety' | wc -l, with this work's three files --
   this one, Adjunction/SpanningArrow.v and
   Test/ProbeVarietySpanning448.v -- excluded through -not -path on the
   find; unexcluded, the command reports exactly those three and
   nothing older).
   Building that instance is a
   development of its own and is out of scope here, so the spanning
   factorization below is constructed by hand, as Mac Lane's own prose
   does it -- by generating a subalgebra rather than by intersecting
   subobjects -- and the two Lattice.v facts that ARE used are
   TRANSPORTED, never re-proved: [sub_top_greatest] and [sub_le_antisym], both consumed by Adjunction/SpanningArrow.v's
   [spanning_forces_top] (first proved in this file and lifted there at
   integration, together with [sub_le_top_iso]).

   ** What a subalgebra is here, and why the closure is INDUCTIVE

   Instance/Variety/Free.v's [SVariety E] is a full subcategory of
   setoid algebras (its [SVariety_sub], which that file proves full),
   so a
   subalgebra is a membership predicate on the carrier that respects `≈`
   and is closed under every operation: [SubAlg] below, three fields.
   It carries a setoid algebra ([sa_soa]), it satisfies E because A does
   ([sa_satisfies], by Instance/Comp.v's [lhs_natural] and
   [rhs_natural] along the inclusion -- CONSUMING those fields exactly
   as Free.v's product does, never proving one), and its inclusion is
   monic ([sa_incl_monic]), so it is a [SubObj] of A in the sense of
   Theory/Subobject.v.

   The subalgebra GENERATED by the image of h : X → G A is [SubGen], an
   inductive predicate with three constructors (a generator is in it, it
   respects `≈`, it is closed under the operations).  The other textbook
   definition -- the intersection of all subalgebras containing the
   image -- was not chosen, and the reason is a universe one rather than
   a matter of taste: that predicate quantifies over [SubAlg E A], whose
   own [sa_mem] field lands in the universe the predicate would have to
   inhabit, so the intersection is not itself a [SubAlg] at the same
   level.  The inductive closure has no such problem and it is what
   makes the leastness clause ([sgen_least]) a plain recursion.

   ** Monos of [SVariety] are exactly the injections

   The spanning proof needs to turn a monomorphism into an injection,
   and that direction is not formal: it needs a PROBE object.  No such
   bridge existed for [SAlgHom] (measured: besides this file, no file
   naming [SAlgHom] or [SVariety] also names [Monic]); the tree has
   bridges for other categories -- 40 non-Test files naming both [Monic]
   and [injective] besides this work's two (grep -rlE '\bMonic\b'
   --include='*.v' . | grep -v /Test/ | xargs grep -l injective), including the
   generic Theory/Concrete/Morphisms.v [concrete_injective_monic] --
   and none applies, because no file gives [SVariety E] a [Concrete]
   instance.  In
   Instance/Sets.v ([injectivity_is_monic]) the probe is the
   singleton; here it is the FREE ALGEBRA ON ONE GENERATOR,
   [Free_Variety E unit_setoid_object], and the two constant maps out of
   it are separated by Free.v's [free_alg_hom_unique].  That is
   [svariety_monic_injective]; the converse [svariety_injective_monic]
   is immediate from [Sub]'s pointwise hom-setoid, and
   [svariety_monic_iff_injective] is the biconditional.  With it,
   [svariety_iso] is the analogue of Instance/Sets.v's
   [bijective_is_iso]: an injective and split-surjective homomorphism is
   an isomorphism OF ALGEBRAS, the inverse being a homomorphism because
   injectivity transports the two laws back across f.  [injective] and
   [surjective] are Lib/Setoid.v, not new vocabulary.

   ** The spanning factorization, and what it is a factorization OF

   [variety_spanning] proves [Spanning SVariety_Forget] of the
   corestriction of h to the generated subalgebra.  The argument is
   Mac Lane's: a subobject m of the generated subalgebra that the
   corestriction factors through has, pushed forward into A, an IMAGE
   that is a subalgebra of A containing every h x ([img_subalg]); by
   leastness it contains the whole closure; so the mono of m is
   surjective; being also monic it is injective, hence invertible, and
   [sub_le sub_top m] follows.  [variety_spanning_forces_top] then reads
   that back in Mac Lane's own words -- m ≈ [sub_top], so no PROPER
   subobject receives the corestriction.

   [variety_solution_set] is Remark 1 itself: a
   Adjunction/GAFT.v [SolutionSet] for [SVariety_Forget E] at every
   set X, whose [sol_index] IS [SpanningArrowsOutOf SVariety_Forget X].
   Three [Example]s read that back at [eq_refl] -- the index, the object
   map and the member covering a given h -- so the claim is not merely
   that a solution set exists but that it is the one Mac Lane names.

   ** Not delivered

   THE CARDINALITY BOUND IS NOT DELIVERED.  Mac Lane's Remark bounds the
   generated subalgebra by the cardinality of the set of terms over X
   (for a finitary signature, at most max(|X|, ℵ₀) many), which is what
   makes the spanning arrows out of X range over a SET of isomorphism
   types and so makes the solution set genuinely small.  Nothing of that
   kind is stated here.  The tree has no cardinal arithmetic, and
   Instance/Comp.v gives operations ARBITRARY TYPES as arities, so
   there is no finitary hypothesis to count with either --
   Instance/Variety/Free.v already says so in terms.  What replaces
   the bound is weaker and is stated as what it is: [sgen_free_cover] is
   a homomorphism from the free algebra on X onto the generated
   subalgebra and [sgen_free_cover_surjective] proves it (split)
   surjective, so the generated subalgebra is a quotient of the term
   algebra.  That establishes the SHAPE of Mac Lane's argument -- terms
   exhaust the closure -- and establishes nothing about size: no
   smallness of [sol_index] is claimed, and [About] reports it at a
   [Type] one universe above the carrier (u3 < u6 in
   [variety_solution_set]'s constraints), a strict bound owned by
   [SolutionSet]'s own [sol_index : Type] field, not introduced here.
   CORRECTION (#450): that readback is the one before #450, when the
   type read [SolutionSet@{u6 u6 u6 u3}].  Re-measured by [About] under
   [Set Printing Universes] after #450 split the universes with
   [soa_prop]: [variety_solution_set@{u u0 u1 u2 u3 u4 u5 u6 u7 u8 u9}]
   returns [SolutionSet@{u8 u9 u8 u3}], the index at [u8], which is also
   the object universe of [SVariety E], and its block has [u3 <= u6] and
   no [u3 < u6]; the strict step is now [u3 < u5] with [u5 <= u8], [u5]
   being the universe that also carries the block's one local [Set]
   bound, [Set < u5] (a second, [Set < Projections.u0], bounds a stdlib
   global).  So the index still sits strictly above the carrier [u3],
   through [u5] rather than [u6].

   Also not delivered: no leastness in the SUBOBJECT order --
   [sgen_least] states it on membership predicates ([sa_mem]) and
   nothing states [sub_le (sgen_subobj h) (sa_subobj B)] in the lattice
   the Remark is phrased in; no [HasWidePullbacks (SVariety E)] and hence no
   route through the general Lemma, as above; no left adjoint is
   rebuilt from THIS solution set.  An earlier revision gave the reason
   as "Free.v's [Free_Variety_adjunction] already has one directly, and
   Free.v's "Why not GAFT" block says why that route is the one taken".
   Since #450 that block records the opposite: GAFT DOES rebuild the free
   algebra (Instance/Variety/Colimit.v's [Free_Variety_via_GAFT]), from a
   DIFFERENT family, indexed by [Prop]-valued congruences on the term
   algebra.  This file's family cannot be the one fed to it, and that is
   measured rather than assumed: with Instance/Variety/Limit.v's
   [SVariety_Complete] and [SVariety_Forget_continuous] as the other two
   arguments, [GAFT (SVariety_Forget E) _ _ (variety_solution_set E)] is
   refused, "universe inconsistency: Cannot enforce VS.103 = VS.160
   because VS.160 < VS.115 <= VS.103" (the universe names are the scratch
   file's): the index is a Σ over the OBJECTS of [SVariety E] and so one
   universe above the carrier (Structure/Complete.v's size note, item 3),
   while the congruence-indexed [SVariety_Forget_solution_set] is
   accepted by the same call earlier in the same scratch file; no
   uniqueness of the spanning factorization -- [SolutionSet] asks for
   none and none is proved; and no claim that distinct spanning arrows
   out of X are pairwise non-isomorphic.

   ** Transparency, measured

   Four [Defined] and twenty-three [Qed]
   (grep -c '^Defined\.', and grep -c 'Qed\.').  Exactly ONE [Defined]
   is load-bearing: [variety_solution_set]'s obligation.  Flipping it to
   [Qed] stops [variety_solution_set_covers], the readback that the
   member covering h IS the generated subalgebra, with "cannot unify
   projT1 (sol_covers (variety_solution_set X) h) and
   variety_spanning_arrow E A X h".  The other three ([variety_spanning],
   [sgen_covered_by_terms], [sgen_free_cover_surjective]) flip with the
   file still compiling, and
   are transparent only by the convention that data-like constructions
   stay so.

   ** Assumptions, measured

   Every constant of this file is closed.  [Print Assumptions] over all
   45 [.glob] heads plus the 17 [Program] obligations, [Build_SubAlg]
   and the four [SubGen] eliminators -- 67 commands -- returns "Closed
   under the global context" 67 times.  Note what that does NOT say
   about the neighbourhood: Instance/Variety/Free.v's own
   [FreeGroupOn] and [FreeGroup_adjunction] carry
   [functional_extensionality_dep] inherited from Instance/Comp.v, and
   docs/AXIOMS.md records them.  Nothing here instantiates an
   [EqSignature], which is where that axiom is paid, so nothing here
   inherits it. *)

Module UA := Category.Instance.Comp.UniversalAlgebra.

#[local] Obligation Tactic := idtac.

(** ** Block A: monos of [SVariety] are the injections *)

Section SVarietyMonos.

Context {S : UA.OpSignature}.
Context (E : UA.EqSignature S).

Program Definition svariety_const (B : SVariety E)
  (x : carrier (soa_obj (`1 B))) :
  unit_setoid_object ~{Sets}~> SVariety_Forget E B := {|
  morphism := fun _ => x
|}.
Next Obligation. intros B x u v Huv; reflexivity. Qed.

Definition svariety_probe (B : SVariety E) (x : carrier (soa_obj (`1 B))) :
  Free_Variety E unit_setoid_object ~{SVariety E}~> B :=
  free_alg_hom B (svariety_const B x).

Lemma svariety_injective_monic {B C : SVariety E} (f : B ~{SVariety E}~> C) :
  injective (salg_map (`1 f)) → Monic f.
Proof.
  intros Hi.
  constructor; intros Z g1 g2 Hg z.
  exact (@inj _ _ _ _ _ Hi _ _ (Hg z)).
Qed.

Lemma svariety_monic_injective {B C : SVariety E} (f : B ~{SVariety E}~> C) :
  Monic f → injective (salg_map (`1 f)).
Proof.
  intros Hm.
  constructor; intros x y Hxy.
  assert (Heq : svariety_probe B x ≈ svariety_probe B y).
  { apply (monic (Monic:=Hm)).
    apply (free_alg_hom_unique C).
    intro u; simpl; exact Hxy. }
  exact (Heq (UA.generator S unit_setoid_object ttt)).
Qed.

Theorem svariety_monic_iff_injective {B C : SVariety E}
  (f : B ~{SVariety E}~> C) : injective (salg_map (`1 f)) ↔ Monic f.
Proof.
  split.
  - exact (svariety_injective_monic f).
  - exact (svariety_monic_injective f).
Qed.

Program Definition svariety_inverse {B C : SVariety E}
  (f : B ~{SVariety E}~> C)
  (Hi : injective (salg_map (`1 f))) (Hs : surjective (salg_map (`1 f))) :
  C ~{SVariety E}~> B :=
  ({| salg_map := fun y => `1 (@surj _ _ _ _ Hs y) |}; I).
Next Obligation.
  intros B C f Hi Hs y1 y2 Hy; simpl.
  apply (@inj _ _ _ _ _ Hi).
  transitivity y1; [ exact (`2 (@surj _ _ _ _ Hs y1)) | ].
  transitivity y2; [ exact Hy | ].
  symmetry; exact (`2 (@surj _ _ _ _ Hs y2)).
Qed.
Next Obligation.
  intros B C f Hi Hs o args; simpl.
  apply (@inj _ _ _ _ _ Hi).
  transitivity (soa_op (`1 C) o args);
    [ exact (`2 (@surj _ _ _ _ Hs _)) | ].
  transitivity (soa_op (`1 C) o
                  (fun i => salg_map (`1 f) (`1 (@surj _ _ _ _ Hs (args i))))).
  - apply (soa_op_respects (`1 C) o); intro i.
    symmetry; exact (`2 (@surj _ _ _ _ Hs (args i))).
  - symmetry.
    exact (salg_commute (`1 f) o (fun i => `1 (@surj _ _ _ _ Hs (args i)))).
Qed.

Lemma svariety_inverse_section {B C : SVariety E} (f : B ~{SVariety E}~> C)
  (Hi : injective (salg_map (`1 f))) (Hs : surjective (salg_map (`1 f))) :
  f ∘ svariety_inverse f Hi Hs ≈ id[C].
Proof. intro y; exact (`2 (@surj _ _ _ _ Hs y)). Qed.

Lemma svariety_inverse_retraction {B C : SVariety E} (f : B ~{SVariety E}~> C)
  (Hi : injective (salg_map (`1 f))) (Hs : surjective (salg_map (`1 f))) :
  svariety_inverse f Hi Hs ∘ f ≈ id[B].
Proof.
  intro x; simpl.
  apply (@inj _ _ _ _ _ Hi).
  exact (`2 (@surj _ _ _ _ Hs (salg_map (`1 f) x))).
Qed.

Program Definition svariety_iso {B C : SVariety E} (f : B ~{SVariety E}~> C)
  (Hi : injective (salg_map (`1 f))) (Hs : surjective (salg_map (`1 f))) :
  B ≅[SVariety E] C := {|
  to := f;
  from := svariety_inverse f Hi Hs
|}.
Next Obligation. intros; apply svariety_inverse_section. Qed.
Next Obligation. intros; apply svariety_inverse_retraction. Qed.

End SVarietyMonos.

Arguments svariety_const {_ _} _ _.
Arguments svariety_probe {_ _} _ _.
Arguments svariety_injective_monic {_ _ _ _} _ _.
Arguments svariety_monic_injective {_ _ _ _} _ _.
Arguments svariety_monic_iff_injective {_ _ _ _} _.
Arguments svariety_inverse {_ _ _ _} _ _ _.
Arguments svariety_inverse_section {_ _ _ _} _ _ _.
Arguments svariety_inverse_retraction {_ _ _ _} _ _ _.
Arguments svariety_iso {_ _ _ _} _ _ _.

(** ** Block B: subalgebras, and their subobjects *)

Section Subalgebra.

Context {S : UA.OpSignature}.
Context (E : UA.EqSignature S).
Context (A : SVariety E).

Record SubAlg := {
  sa_mem : carrier (soa_obj (`1 A)) → Type;
  sa_respects : ∀ u v, u ≈ v → sa_mem u → sa_mem v;
  sa_closed : ∀ (o : UA.operation S)
                (k : UA.arity o → carrier (soa_obj (`1 A))),
    (∀ i, sa_mem (k i)) → sa_mem (soa_op (`1 A) o k)
}.

Program Definition sa_setoid (B : SubAlg) :
  Setoid { t : carrier (soa_obj (`1 A)) & sa_mem B t } := {|
  equiv := fun p q => `1 p ≈ `1 q
|}.
Next Obligation.
  intros B; constructor; repeat intro.
  - reflexivity.
  - symmetry; auto.
  - transitivity (`1 y); auto.
Qed.

Definition sa_obj (B : SubAlg) : SetoidObject :=
  {| carrier   := { t : carrier (soa_obj (`1 A)) & sa_mem B t }
   ; is_setoid := sa_setoid B |}.

(* Since #450 a setoid algebra carries [soa_prop]; a subalgebra's `≈` is
   the ambient one read on first projections, so its propositional mirror
   is the ambient algebra's, transported by [sigma_first_PropEquiv]. *)
Program Definition sa_soa (B : SubAlg) : SetoidOpAlgebra S := {|
  soa_obj := sa_obj B;
  soa_op  := fun o k => (soa_op (`1 A) o (fun i => `1 (k i));
                         sa_closed B o (fun i => `1 (k i)) (fun i => `2 (k i)));
  soa_prop := sigma_first_PropEquiv (sa_setoid B) (fun _ _ h => h) (fun _ _ h => h)
                (soa_prop (`1 A))
|}.
Next Obligation.
  intros B o k1 k2 H; simpl.
  apply (soa_op_respects (`1 A) o); exact H.
Qed.

Program Definition sa_incl_alghom (B : SubAlg) :
  UA.AlgHom (soa_alg (sa_soa B)) (soa_alg (`1 A)) :=
  {| UA.map := fun p => `1 p |}.
Next Obligation. intros B o args; reflexivity. Qed.

Theorem sa_satisfies (B : SubAlg) : ssatisfies E (sa_soa B).
Proof.
  intros e args.
  assert (HL : `1 (@UA.lhs S E (soa_alg (sa_soa B)) e args)
               = @UA.lhs S E (soa_alg (`1 A)) e (fun i => `1 (args i)))
    by exact (@UA.lhs_natural S E (soa_alg (sa_soa B)) (soa_alg (`1 A))
                (sa_incl_alghom B) e args).
  assert (HR : `1 (@UA.rhs S E (soa_alg (sa_soa B)) e args)
               = @UA.rhs S E (soa_alg (`1 A)) e (fun i => `1 (args i)))
    by exact (@UA.rhs_natural S E (soa_alg (sa_soa B)) (soa_alg (`1 A))
                (sa_incl_alghom B) e args).
  change (`1 (@UA.lhs S E (soa_alg (sa_soa B)) e args)
          ≈ `1 (@UA.rhs S E (soa_alg (sa_soa B)) e args)).
  rewrite HL, HR.
  exact (`2 A e (fun i => `1 (args i))).
Qed.

Definition sa_alg (B : SubAlg) : SVariety E := (sa_soa B; sa_satisfies B).

Program Definition sa_incl (B : SubAlg) : sa_alg B ~{SVariety E}~> A :=
  ({| salg_map := fun p => `1 p |}; I).
Next Obligation. intros B p q H; exact H. Qed.
Next Obligation. intros B o args; simpl; reflexivity. Qed.

Lemma sa_incl_injective (B : SubAlg) : injective (salg_map (`1 (sa_incl B))).
Proof. constructor; intros p q H; exact H. Qed.

Definition sa_incl_monic (B : SubAlg) : Monic (sa_incl B) :=
  svariety_injective_monic (sa_incl B) (sa_incl_injective B).

Definition sa_subobj (B : SubAlg) : @SubObj (SVariety E) A := {|
  sub_dom      := sa_alg B;
  sub_mono     := sa_incl B;
  sub_is_monic := sa_incl_monic B
|}.

(** *** The image of a homomorphism is a subalgebra *)

Program Definition img_subalg {B : SVariety E} (f : B ~{SVariety E}~> A) :
  SubAlg := {|
  sa_mem := fun t => { d : carrier (soa_obj (`1 B)) & salg_map (`1 f) d ≈ t }
|}.
Next Obligation.
  intros B f u v Huv D; simpl in *.
  exists (`1 D).
  transitivity u; [ exact (`2 D) | exact Huv ].
Qed.
Next Obligation.
  intros B f o k Hk; simpl in *.
  exists (soa_op (`1 B) o (fun i => `1 (Hk i))).
  transitivity (soa_op (`1 A) o (fun i => salg_map (`1 f) (`1 (Hk i)))).
  - exact (salg_commute (`1 f) o (fun i => `1 (Hk i))).
  - apply (soa_op_respects (`1 A) o); intro i; exact (`2 (Hk i)).
Qed.

End Subalgebra.

Arguments SubAlg {_} _ _.
Arguments sa_mem {_ _ _} _ _.
Arguments sa_respects {_ _ _} _ _ _ _ _.
Arguments sa_closed {_ _ _} _ _ _ _.
Arguments sa_setoid {_ _ _} _.
Arguments sa_obj {_ _ _} _.
Arguments sa_soa {_ _ _} _.
Arguments sa_incl_alghom {_ _ _} _.
Arguments sa_satisfies {_ _ _} _ _ _.
Arguments sa_alg {_ _ _} _.
Arguments sa_incl {_ _ _} _.
Arguments sa_incl_injective {_ _ _} _.
Arguments sa_incl_monic {_ _ _} _.
Arguments sa_subobj {_ _ _} _.
Arguments img_subalg {_ _ _ _} _.

(** ** Block C: the subalgebra generated by the image of a function *)

Section Generated.

Context {S : UA.OpSignature}.
Context (E : UA.EqSignature S).
Context (A : SVariety E).
Context (X : Sets).
Context (h : X ~{Sets}~> SVariety_Forget E A).

Inductive SubGen : carrier (soa_obj (`1 A)) → Type :=
  | sgen_base : ∀ x : X, SubGen (h x)
  | sgen_resp : ∀ u v, u ≈ v → SubGen u → SubGen v
  | sgen_op : ∀ (o : UA.operation S)
                (k : UA.arity o → carrier (soa_obj (`1 A))),
      (∀ i, SubGen (k i)) → SubGen (soa_op (`1 A) o k).

Definition sgen_subalg : SubAlg E A := {|
  sa_mem      := SubGen;
  sa_respects := sgen_resp;
  sa_closed   := sgen_op
|}.

Definition sgen_alg : SVariety E := sa_alg sgen_subalg.

Definition sgen_subobj : @SubObj (SVariety E) A := sa_subobj sgen_subalg.

Program Definition sgen_corestrict :
  X ~{Sets}~> SVariety_Forget E sgen_alg := {|
  morphism := fun x => (h x; sgen_base x)
|}.
Next Obligation. intros x y Hxy; exact (proper_morphism h x y Hxy). Qed.

Program Definition sgen_factors :
  SubFactorsThrough (SVariety_Forget E) h sgen_subobj := (sgen_corestrict; _).
Next Obligation. intro x; simpl; reflexivity. Qed.

Fixpoint sgen_least (B : SubAlg E A) (HB : ∀ x : X, sa_mem B (h x))
  (t : carrier (soa_obj (`1 A))) (D : SubGen t) {struct D} : sa_mem B t :=
  match D in SubGen t' return sa_mem B t' with
  | sgen_base x        => HB x
  | sgen_resp u v H D' => sa_respects B u v H (sgen_least B HB u D')
  | sgen_op o k Hk     =>
      sa_closed B o k (fun i => sgen_least B HB (k i) (Hk i))
  end.

End Generated.

Arguments SubGen {_ _ _ _} _ _.
Arguments sgen_base {_ _ _ _} _ _.
Arguments sgen_resp {_ _ _ _} _ _ _ _ _.
Arguments sgen_op {_ _ _ _} _ _ _ _.
Arguments sgen_subalg {_ _ _ _} _.
Arguments sgen_alg {_ _ _ _} _.
Arguments sgen_subobj {_ _ _ _} _.
Arguments sgen_corestrict {_ _ _ _} _.
Arguments sgen_factors {_ _ _ _} _.
Arguments sgen_least {_ _ _ _} _ _ _ _ _.

(** ** Block D: the spanning factorization and the solution set *)

Section VarietySpanning.

Context {S : UA.OpSignature}.
Context (E : UA.EqSignature S).
Context (A : SVariety E).
Context (X : Sets).
Context (h : X ~{Sets}~> SVariety_Forget E A).

Theorem variety_spanning :
  Spanning (SVariety_Forget E) (sgen_corestrict h).
Proof.
  intros m Hm.
  destruct Hm as [j Hj].
  pose (n := sa_incl (sgen_subalg h) ∘ sub_mono m).
  assert (Hcov : ∀ x : X, sa_mem (img_subalg n) (h x)).
  { intro x; exists (j x); exact (Hj x). }
  assert (Hs : surjective (salg_map (`1 (sub_mono m)))).
  { constructor; intro p.
    destruct (sgen_least h (img_subalg n) Hcov (`1 p) (`2 p)) as [d Hd].
    exists d; exact Hd. }
  pose (Hi := svariety_monic_injective (sub_mono m) (sub_is_monic m)).
  exists (svariety_inverse (sub_mono m) Hi Hs).
  exact (svariety_inverse_section (sub_mono m) Hi Hs).
Defined.

Definition variety_spanning_arrow :
  SpanningArrowsOutOf (SVariety_Forget E) X :=
  (sgen_alg h; (sgen_corestrict h; variety_spanning)).

(* Mac Lane's own phrasing, recovered: no PROPER subobject of the generated
   subalgebra receives the corestriction.  [spanning_forces_top] is the only
   step, and it is where the two Lattice.v facts are transported. *)
Definition variety_spanning_forces_top (m : SubObj (sgen_alg h)) :
  SubFactorsThrough (SVariety_Forget E) (sgen_corestrict h) m → m ≈ sub_top :=
  spanning_forces_top (SVariety_Forget E) (sgen_corestrict h)
    variety_spanning m.

End VarietySpanning.

Arguments variety_spanning {_} _ _ _ _ _ _.
Arguments variety_spanning_arrow {_} _ _ _ _.
Arguments variety_spanning_forces_top {_} _ _ _ _ _ _.

Section SolutionSetOfVariety.

Context {S : UA.OpSignature}.
Context (E : UA.EqSignature S).

Program Definition variety_solution_set (X : Sets) :
  SolutionSet (SVariety_Forget E) X := {|
  sol_index := SpanningArrowsOutOf (SVariety_Forget E) X;
  sol_obj   := fun i => `1 i;
  sol_arr   := fun i => `1 (`2 i)
|}.
Next Obligation.
  intros X c g.
  exists (variety_spanning_arrow E c X g).
  exists (sa_incl (sgen_subalg g)).
  exact (`2 (sgen_factors g)).
Defined.

(* The three readbacks that say the Remark is the Remark: the index IS the
   spanning arrows out of [X], and the member covering a given [h] IS the
   subalgebra generated by its image.  Leibniz [=] is used here only in the
   sense the repository allows -- [eq_refl] about DATA, never about
   morphisms. *)
Example variety_solution_set_index (X : Sets) :
  sol_index (variety_solution_set X)
    = SpanningArrowsOutOf (SVariety_Forget E) X := eq_refl.

Example variety_solution_set_obj (X : Sets)
  (i : SpanningArrowsOutOf (SVariety_Forget E) X) :
  sol_obj (variety_solution_set X) i = `1 i := eq_refl.

Example variety_solution_set_covers (A : SVariety E) (X : Sets)
  (h : X ~{Sets}~> SVariety_Forget E A) :
  `1 (sol_covers (variety_solution_set X) h)
    = variety_spanning_arrow E A X h := eq_refl.

End SolutionSetOfVariety.

Arguments variety_solution_set {_} _ _.

(** ** Block E: the generated subalgebra is covered by terms *)

Section Terms.

Context {S : UA.OpSignature}.
Context (E : UA.EqSignature S).
Context (A : SVariety E).
Context (X : Sets).
Context (h : X ~{Sets}~> SVariety_Forget E A).

Lemma sgen_covered_by_terms (t : carrier (soa_obj (`1 A))) (D : SubGen h t) :
  { u : UA.Tree S X & free_alg_ext A h u ≈ t }.
Proof.
  induction D as [ x | u v Huv D IH | o k Hk IH ].
  - exists (UA.generator S X x); reflexivity.
  - exists (`1 IH); transitivity u; [ exact (`2 IH) | exact Huv ].
  - exists (UA.node S X o (fun i => `1 (IH i))).
    apply (soa_op_respects (`1 A) o); intro i; exact (`2 (IH i)).
Defined.

Fixpoint sgen_of_term (t : UA.Tree S X) : SubGen h (free_alg_ext A h t) :=
  match t with
  | UA.generator _ _ x => sgen_base h x
  | UA.node _ _ o k    =>
      sgen_op h o (fun i => free_alg_ext A h (k i))
        (fun i => sgen_of_term (k i))
  end.

Program Definition sgen_free_cover :
  Free_Variety E X ~{SVariety E}~> sgen_alg h :=
  ({| salg_map := fun t => (free_alg_ext A h t; sgen_of_term t) |}; I).
Next Obligation. intros t u Htu; apply free_alg_ext_respects; exact Htu. Qed.
Next Obligation. intros o args; simpl; reflexivity. Qed.

Lemma sgen_free_cover_surjective :
  surjective (salg_map (`1 sgen_free_cover)).
Proof.
  constructor; intro p.
  destruct (sgen_covered_by_terms (`1 p) (`2 p)) as [u Hu].
  exists u; exact Hu.
Defined.

End Terms.

Arguments sgen_covered_by_terms {_ _ _ _} _ _ _.
Arguments sgen_of_term {_ _ _ _} _ _.
Arguments sgen_free_cover {_ _ _ _} _.
Arguments sgen_free_cover_surjective {_ _ _ _} _.
