Require Import Category.Lib.
Require Import Category.Lib.TList.
Require Import Category.Theory.Category.
Require Import Category.Theory.Functor.
Require Import Category.Construction.Quotient.
Require Import Category.Construction.Free.Quiver.
Require Import Category.Construction.Deloop.

Require Import Coq.Vectors.Fin.

Generalizable All Variables.

(** [Construction/Free/Quiver.v] declares [edgeset] as a section-local
    instance and again as a [Local Existing Instance], so it does not
    escape that file.  Re-declaring it here — locally, so it does not
    escape this one either — is mandatory: without it the very first
    statement about edge equivalence reports a missing [Setoid] instance,
    which reads like a universe problem and is not one. *)
#[local] Existing Instance edgeset.

(** * Categories presented by generators and relations

    nLab: https://ncatlab.org/nlab/show/quotient+category
    nLab: https://ncatlab.org/nlab/show/congruence
    Book: Mac Lane, Categories for the Working Mathematician, 2nd ed.,
          §II.8, printed pp. 51-52 (Proposition 1; congruences and the
          least congruence containing a family; categories presented by
          generators and relations)
    Book: Awodey, Category Theory, §4.4, printed p. 89 (the finitely
          presented category C(G,Σ))
    Book: Fong and Spivak, Seven Sketches in Compositionality, CUP 2019,
          §3.2.2, printed p. 84 (path equations, finite presentations, and
          finitely presented categories)
    Book: Riehl, Category Theory in Context, §1.6 Remark 1.6.7, printed
          p. 41

    THE RECIPE.  Take the free category on a quiver, then quotient it by
    the congruence generated by a family of path equations.  This is the
    categorical analogue of presenting a monoid or a group by generators
    and relations, and it is Mac Lane's §II.7 followed immediately by his
    §II.8: [Construction/Free/Quiver.v] supplies the first half,
    [Construction/Quotient.v] the second, and this file is the chaining
    that [Construction/Free.v]'s header narrates.

    PARALLELISM IS STRUCTURAL, not a side condition.  Seven Sketches
    restricts an imposed equation to paths sharing both a source and a
    target.  Here that restriction costs nothing: [PathRel] is indexed by a
    source and a target with both arguments paths between exactly those
    endpoints, so an equation between non-parallel paths cannot be written
    down at all.  [PathRel_parallel] records the unfolding as a
    definitional equality.

    EQUATIONS ONLY MERGE.  The projection is the identity on objects and
    the identity on morphisms; only the hom-setoid equivalence coarsens.
    Hence [presented_proj_obj], [presented_hom_type] and
    [PresentedQuiverProj_Full] (restated existentially as
    [presented_proj_hom_surjective]), and hence also the projection is
    deliberately not [Faithful] — that non-instance is the whole content of
    Fong and Spivak's remark that imposing equations can merge morphisms
    but never add any.

    THE STRENGTH OF THE UNIVERSAL PROPERTY, which is the opposite of what a
    reader expects.  [presented_universal] is STRICT: the object agreement
    is Leibniz [=] and the morphism agreement is a [hom_cast] conjugation
    along it, which is exactly [StrictCat]'s functor equality
    ([Functor_StrictEq_Setoid]) — the level at which
    [Construction/Free/Quiver.v]'s free universal property already lives,
    since [Forgetful] is a functor over [StrictCat] and has no [Cat]
    counterpart ([Test/Issue138.v]).  Strict is STRONGER than a [Cat]-level
    reading, and the weaker one follows from it rather than replacing it:
    [strict_of_hom_cast] ([Construction/Quotient.v]) followed by
    [strict_equiv_implies_fun_equiv] ([Instance/StrictCat/ToCat.v]) turns
    the uniqueness clause into a natural isomorphism in [Cat] in two lines.
    Nothing here is stated only at that weaker level.

    THE ORDINAL 3.  The free category on the two-edge LINEAR quiver is
    already the ordinal 3 — its homs are the empty path at each node, [a],
    [b] and [a] then [b] — so a relation-free "presentation of 3 by a
    composable pair" is degenerate.  The non-degenerate reading, and the
    one the example below takes, is three generators a : 0 → 1, b : 1 → 2
    and c : 0 → 2 with the single relation c = b ∘ a, the commutative
    triangle.  [Instance/Ordinal.v]'s [Ordinal 3] is the comparison target
    for an isomorphism [Ord3 ≅ Ordinal 3]; that isomorphism is NOT proven
    here, and this file deliberately does not depend on
    [Instance/Ordinal.v], which would pull [Instance/Cat], [Instance/Two],
    [Coq.Lists.List] and [Coq.micromega.Lia] into the [Construction/] layer
    for a comparison this file does not make.  What is proven is that the two
    paths are distinct in the free category ([ord3_free_distinct]) and
    identified in the presented one ([ord3_relation_holds]);
    [presented_no_eqns_separates] below shows the quotient does not
    collapse indiscriminately.

    RIEHL'S SQUARE.  Riehl §1.6 Remark 1.6.7 asks that
    [funny_diagonals_distinct] ([Construction/Funny/Comparison.v]) be cited
    rather than reproved.  That instruction is not followable as written:
    the theorem is stated about [feq] in [_2 □ _2], and transporting it to
    [FreeOnQuiver] of the square quiver needs a comparison
    [_2 □ _2 ≅ FreeOnQuiver (square quiver)] which is not in tree.  This
    file therefore proves the [FreeOnQuiver]-native form directly
    ([free_square_diagonals_distinct], six lines, axiom-free) and cites
    [funny_diagonals_distinct] here as the independent shadow of the same
    fact under a different name.  No [Require] on [Construction/Funny/] is
    added.

    THE ONE-OBJECT CASE.  [hom_monoid] ([Construction/Deloop.v]), not
    [Deloop], is the relevant direction: the endomorphism monoid of the
    single node of a one-node quiver recovers the free monoid
    ([FreeMonoidOn]) and, after quotienting, the presented monoid
    ([PresentedMonoidOn]).

    FINITENESS IS DATA.  [FiniteQuiver] enumerates nodes and edges as
    [Fin.t] indices with retractions back onto them; [FiniteEquations]
    carries a per-endpoint-pair count with the two sides of each equation
    indexed by [Fin.t].  Neither is an existence claim over lists, so no
    choice principle is used anywhere.  [Ord3Finite] and
    [Ord3Presentation] are the in-tree witnesses.

    WHERE THE ENGINE IS.  The [Type]-valuedness rationale for the generated
    congruence, the universe constraint it carries, and the comparison with
    the bespoke [TermEqW] closure of the PROP presentation layer are stated
    once, in [Construction/Quotient.v]'s subsection on the congruence
    generated by a hom-relation; they are cross-referenced from here rather
    than repeated. *)

Section Presentation.

Universes o h p.
Context (G : Quiver@{o h p}).

(** ** Path equations

    A family of equations between paths of [G].  It is exactly a relation
    family on [FreeOnQuiver G], and it must be spelled as that alias rather
    than written out: recovering the ambient category from a spelled-out
    [∀ x y : G, tlist edges x y → …] is a higher-order problem, and
    [QuotientCong] then does not accept it. *)
Definition PathRel : Type := HomRelT (FreeOnQuiver G).

(** Parallelism, as a definitional fact.  The family is indexed by a source
    and a target, and both arguments are paths between exactly those
    endpoints, so an equation between non-parallel paths is not merely
    disallowed — it cannot be written. *)
Example PathRel_parallel :
  PathRel = (∀ x y : G, tlist edges x y → tlist edges x y → Type).
Proof. reflexivity. Qed.

(** ** Finiteness, carried as data

    Seven Sketches §3.2.2 asks for finiteness as enumerations rather than
    as an existence claim.  [FiniteQuiver] carries [Fin.t] indices with
    retractions; [FiniteEquations] carries a [Fin.t]-indexed family of
    equations.  No choice principle is used.  Nodes are compared by
    Leibniz [=] (a quiver's nodes are a strict [Type]) and edges by [≈]
    (they carry [edgeset]). *)
Record FiniteQuiver : Type := {
  fq_nodes : nat;
  fq_node : Fin.t fq_nodes → G;
  fq_index : G → Fin.t fq_nodes;
  fq_node_rt : ∀ x : G, fq_node (fq_index x) = x;
  fq_edges : G → G → nat;
  fq_edge : ∀ x y : G, Fin.t (fq_edges x y) → edges x y;
  fq_eindex : ∀ x y : G, edges x y → Fin.t (fq_edges x y);
  fq_edge_rt : ∀ (x y : G) (e : edges x y),
      fq_edge x y (fq_eindex x y e) ≈ e
}.

(** Finitely many equations, per parallel pair of endpoints. *)
Record FiniteEquations : Type := {
  fe_count : G → G → nat;
  fe_lhs : ∀ x y : G, Fin.t (fe_count x y) → x ~{FreeOnQuiver G}~> y;
  fe_rhs : ∀ x y : G, Fin.t (fe_count x y) → x ~{FreeOnQuiver G}~> y
}.

(** The path relation a finite equation set names.  [∃] is [sigT] here, so
    this lands in [Type], matching [PathRel]. *)
Definition fe_rel (E : FiniteEquations) : PathRel :=
  fun x y f g => ∃ i : Fin.t (fe_count E x y),
    (f ≈ fe_lhs E x y i) * (g ≈ fe_rhs E x y i).

Context (R : PathRel).

(** ** The presented category

    Generators [G], relations [R]: the free category on [G], quotiented by
    the congruence generated by [R]. *)
Definition PresentedQuiver : Category := QuotientCong (FreeOnQuiver G) R.

(** The presenting projection. *)
Definition PresentedQuiverProj : FreeOnQuiver G ⟶ PresentedQuiver :=
  QuotientCongProj R.

(** A generating edge, read as a morphism of the presented category. *)
Definition pgen {x y : G} (e : edges x y) : x ~{PresentedQuiver}~> y :=
  tlist_singleton e.

(** Mac Lane §II.8 Proposition 1, clause (i), specialized: the imposed
    equations hold in the presented category. *)
Lemma presented_relations_hold {x y : G}
  {p q : x ~{FreeOnQuiver G}~> y} (Hr : R x y p q) :
  fmap[PresentedQuiverProj] p ≈ fmap[PresentedQuiverProj] q.
Proof. exact (cong_identifies R Hr). Qed.

(** The projection is the identity on objects. *)
Lemma presented_proj_obj (x : G) : fobj[PresentedQuiverProj] x = x.
Proof. reflexivity. Qed.

(** The hom TYPES are untouched: equations merge, and never add. *)
Lemma presented_hom_type (x y : G) :
  (x ~{PresentedQuiver}~> y) = (x ~{FreeOnQuiver G}~> y).
Proof. reflexivity. Qed.

(** Surjectivity on each hom-set, as a CHOSEN section. *)
Definition PresentedQuiverProj_Full : Full PresentedQuiverProj :=
  @QuotientProj_Full (FreeOnQuiver G) (CongClosure R)
    (CongClosure_Congruence R).

(** The same, restated for readers who want the existential. *)
Lemma presented_proj_hom_surjective {x y : G}
  (f : x ~{PresentedQuiver}~> y) :
  { p : x ~{FreeOnQuiver G}~> y & fmap[PresentedQuiverProj] p ≈ f }.
Proof. exists f. reflexivity. Qed.

(** ** The universal property

    A functor out of the presented category is exactly a quiver
    homomorphism whose induced functor merges the relations. *)

Section PresentedUMP.

Context {D : Category}.
Context (F : QuiverHomomorphism G (QuiverOfCat D)).
Context (HF : ∀ x y (f g : x ~{FreeOnQuiver G}~> y), R x y f g →
              fmap[InducedFunctor G F] f ≈ fmap[InducedFunctor G F] g).

(** The induced functor out of the presented category. *)
Definition PresentedFunctor : PresentedQuiver ⟶ D :=
  QuotientCongLift R (InducedFunctor G F) HF.

(** It sends each generator where the quiver homomorphism does.  (The
    [id_left] is the path fold's trailing identity on a singleton path.) *)
Lemma PresentedFunctor_gen {x y : G} (e : edges x y) :
  fmap[PresentedFunctor] (pgen e) ≈ @fedgemap _ _ F x y e.
Proof. simpl. now rewrite id_left. Qed.

(** ...and each node likewise, on the nose. *)
Lemma PresentedFunctor_obj (x : G) :
  fobj[PresentedFunctor] x = @fnodes _ _ F x.
Proof. reflexivity. Qed.

(** Uniqueness, at STRICT strength: Leibniz equality on objects and a
    [hom_cast] conjugation on morphisms — [StrictCat]'s functor equality,
    which [strict_of_hom_cast] ([Construction/Quotient.v]) converts.  The
    induction is [Construction/Free/Quiver.v]'s, with [transport] and
    [transport_r] replaced by [hom_cast] and [hom_cast_comp]. *)
Lemma PresentedFunctor_unique (K : PresentedQuiver ⟶ D)
  (Hobj : ∀ x : G, fobj[K] x = @fnodes _ _ F x)
  (Hgen : ∀ (x y : G) (e : edges x y),
      hom_cast (Hobj x) (Hobj y) (fmap[K] (pgen e))
        ≈ @fedgemap _ _ F x y e) :
  ∀ (x y : G) (f : x ~{PresentedQuiver}~> y),
    hom_cast (Hobj x) (Hobj y) (fmap[K] f) ≈ fmap[PresentedFunctor] f.
Proof.
  intros x y f.
  induction f.
  - change (@tnil _ _ y) with (@id PresentedQuiver y).
    rewrite fmap_id. simpl. rewrite hom_cast_id. reflexivity.
  - assert (RW : @equiv (@hom PresentedQuiver i y) _ (b ::: f)
                   (@compose PresentedQuiver _ _ _ f (pgen b))).
    { unfold pgen, tlist_singleton. simpl.
      apply cc_equiv. simpl. now rewrite <- tlist_app_cons. }
    rewrite RW, fmap_comp.
    rewrite <- (hom_cast_comp (Hobj i) (Hobj j) (Hobj y)).
    rewrite IHf, Hgen.
    now rewrite fmap_comp, PresentedFunctor_gen.
Qed.

(** *** The converse leg

    Restricting a functor out of the presented category along the unit
    gives back a quiver homomorphism, and that homomorphism automatically
    satisfies the relations.  This is what makes Riehl's "exactly" honest
    in both directions. *)

Section Restrict.

Context (S : PresentedQuiver ⟶ D).

(** The quiver homomorphism underlying [S]. *)
Definition presented_restrict : QuiverHomomorphism G (QuiverOfCat D) :=
  QuiverComp (UnitQuiverCatAdjunction G)
    (QuiverHomomorphismOfFunctor _ _ (S ◯ PresentedQuiverProj)).

(** On generators the restriction is [S] itself, definitionally — a
    Leibniz equality of morphisms, stated at that strength deliberately,
    in the manner of [QuotientLift_proj] ([Construction/Quotient.v]). *)
Lemma presented_restrict_gen {x y : G} (e : edges x y) :
  @fedgemap _ _ presented_restrict x y e = fmap[S] (pgen e).
Proof. reflexivity. Qed.

(** The functor induced by the restriction agrees with [S] on every
    path. *)
Lemma presented_restrict_induced {a b : G}
  (u : a ~{FreeOnQuiver G}~> b) :
  fmap[InducedFunctor G presented_restrict] u ≈ fmap[S] u.
Proof.
  induction u; simpl.
  - now rewrite fmap_id.
  - transitivity (fmap[S] u ∘ fmap[S] (pgen b0)).
    + apply compose_respects; [ exact IHu | reflexivity ].
    + rewrite <- fmap_comp. apply fmap_respects.
      unfold pgen, tlist_singleton; simpl.
      apply cc_equiv; simpl. now rewrite <- tlist_app_cons.
Qed.

(** Every functor out of the presented category merges [R] automatically —
    the converse of the merging hypothesis [HF]. *)
Lemma presented_restrict_satisfies {x y : G}
  {p q : x ~{FreeOnQuiver G}~> y} (Hr : R x y p q) :
  fmap[InducedFunctor G presented_restrict] p
    ≈ fmap[InducedFunctor G presented_restrict] q.
Proof.
  transitivity (fmap[S] p); [ exact (presented_restrict_induced p) | ].
  transitivity (fmap[S] q);
    [ exact (@fmap_respects _ _ S x y p q (cc_gen Hr))
    | symmetry; exact (presented_restrict_induced q) ].
Qed.

End Restrict.

End PresentedUMP.

End Presentation.

Arguments PathRel G : assert.
Arguments PresentedQuiver G R : assert.
Arguments pgen {G R x y} e.
Arguments fe_rel {G} E.

(** ** Finite presentations

    A finite presentation quantifies over its own quiver, so it lives
    outside the section above. *)
Record FinitePresentation : Type := {
  fp_quiver : Quiver;
  fp_finite : FiniteQuiver fp_quiver;
  fp_eqns : FiniteEquations fp_quiver
}.

(** Seven Sketches §3.2.2's finitely presented category, with finiteness
    carried as data throughout. *)
Definition FinitelyPresented (P : FinitePresentation) : Category :=
  PresentedQuiver (fp_quiver P) (fe_rel (fp_eqns P)).

(** ** The generators-and-relations universal property, bundled *)

Section PresentedUniversal.

Context (G : Quiver) (R : PathRel G) {D : Category}.

(** Riehl §1.6 Remark 1.6.7, in full: to give a functor out of the
    presented category it suffices to name the images of the generators
    subject to the relations, and the result is unique at STRICT strength.
    The object agreement [Hobj] is nested INSIDE the bundle on purpose: a
    flat statement of the generator clause has no common hom, since for an
    abstract [K] the objects [fobj[K] x] and [@fnodes _ _ F x] are not
    convertible until [Hobj] is in scope. *)
Theorem presented_universal
  (F : QuiverHomomorphism G (QuiverOfCat D))
  (HF : ∀ x y (f g : x ~{FreeOnQuiver G}~> y), R x y f g →
        fmap[InducedFunctor G F] f ≈ fmap[InducedFunctor G F] g) :
  { K : PresentedQuiver G R ⟶ D &
  { Hobj : ∀ x : G, fobj[K] x = @fnodes _ _ F x &
    ((∀ (x y : G) (e : edges x y),
        hom_cast (Hobj x) (Hobj y) (fmap[K] (pgen e))
          ≈ @fedgemap _ _ F x y e) *
     (∀ (K' : PresentedQuiver G R ⟶ D)
        (Hobj' : ∀ x : G, fobj[K'] x = @fnodes _ _ F x),
        (∀ (x y : G) (e : edges x y),
           hom_cast (Hobj' x) (Hobj' y) (fmap[K'] (pgen e))
             ≈ @fedgemap _ _ F x y e) →
        ∀ (x y : G) (f : x ~{PresentedQuiver G R}~> y),
          hom_cast (Hobj' x) (Hobj' y) (fmap[K'] f)
            ≈ hom_cast (Hobj x) (Hobj y) (fmap[K] f)))%type } }.
Proof.
  exists (@PresentedFunctor G R D F HF), (fun _ => eq_refl).
  split.
  - intros x y e. exact (@PresentedFunctor_gen G R D F HF x y e).
  - intros K' Hobj' Hgen x y f.
    exact (@PresentedFunctor_unique G R D F HF K' Hobj' Hgen x y f).
Qed.

End PresentedUniversal.

(** ** Presented monoids: the one-object case

    A one-node quiver presents a monoid.  [hom_monoid]
    ([Construction/Deloop.v]) is the relevant direction — [Deloop] goes the
    other way, from a monoid to a one-object category. *)

(** The quiver with one node and one edge set.  [poly_unit] keeps the
    object universe free rather than pinning it at [Set]. *)
Definition OneNodeQuiver (A : Type) : Quiver :=
  Build_Quiver_Standard_Eq poly_unit (fun _ _ => A).

(** The free monoid on [A]: its carrier reduces to the paths from the
    single node to itself, i.e. the [tlist] encoding of [list A]. *)
Definition FreeMonoidOn (A : Type) : MonObject :=
  hom_monoid (FreeOnQuiver (OneNodeQuiver A)) ttt.

(** The monoid presented by generators [A] and relations [R]. *)
Definition PresentedMonoidOn (A : Type) (R : PathRel (OneNodeQuiver A)) :
  MonObject :=
  hom_monoid (PresentedQuiver (OneNodeQuiver A) R) ttt.

(** ** The book's example: presenting the ordinal 3

    Three generators a : 0 → 1, b : 1 → 2, c : 0 → 2 with the single
    relation c = b ∘ a — the commutative triangle.  See the header for why
    the two-edge linear quiver would be the degenerate reading. *)

Inductive Ord3Node : Set := Ord3_0 | Ord3_1 | Ord3_2.

Inductive Ord3Edge : Ord3Node → Ord3Node → Set :=
  | Ord3_a : Ord3Edge Ord3_0 Ord3_1
  | Ord3_b : Ord3Edge Ord3_1 Ord3_2
  | Ord3_c : Ord3Edge Ord3_0 Ord3_2.

Definition Ord3Quiver : Quiver := Build_Quiver_Standard_Eq Ord3Node Ord3Edge.

(** The two paths the relation identifies. *)
Definition ord3_path_c : Ord3_0 ~{FreeOnQuiver Ord3Quiver}~> Ord3_2 :=
  tlist_singleton (B:=@edges Ord3Quiver) Ord3_c.

Definition ord3_path_ab : Ord3_0 ~{FreeOnQuiver Ord3Quiver}~> Ord3_2 :=
  tcons (B:=@edges Ord3Quiver) _ Ord3_a
    (tlist_singleton (B:=@edges Ord3Quiver) Ord3_b).

(** In the FREE category they are distinct.  The discriminator is the
    intermediate node equality that [tlist'_quiver_equiv] exposes as the
    first component of its [sigT]. *)
Lemma ord3_free_distinct : ord3_path_c ≈ ord3_path_ab → False.
Proof.
  unfold ord3_path_c, ord3_path_ab, tlist_singleton; simpl.
  unfold tlist_quiver_equiv; simpl. intros [q He Ht]. discriminate q.
Qed.

(** The single equation, as finite data. *)
Definition Ord3_count (x y : Ord3Quiver) : nat :=
  match x, y with Ord3_0, Ord3_2 => 1 | _, _ => 0 end.

Definition Ord3_lhs (x y : Ord3Quiver) :
  Fin.t (Ord3_count x y) → x ~{FreeOnQuiver Ord3Quiver}~> y.
Proof.
  destruct x, y; simpl; intro i;
    solve [ exact (Fin.case0 _ i) | exact ord3_path_c ].
Defined.

Definition Ord3_rhs (x y : Ord3Quiver) :
  Fin.t (Ord3_count x y) → x ~{FreeOnQuiver Ord3Quiver}~> y.
Proof.
  destruct x, y; simpl; intro i;
    solve [ exact (Fin.case0 _ i) | exact ord3_path_ab ].
Defined.

Definition Ord3Eqns : FiniteEquations Ord3Quiver := {|
  fe_count := Ord3_count;
  fe_lhs := Ord3_lhs;
  fe_rhs := Ord3_rhs
|}.

(** The quiver is finite, with the enumeration carried as data. *)
Definition Ord3_node (i : Fin.t 3) : Ord3Node :=
  match i with
  | Fin.F1 => Ord3_0
  | Fin.FS j =>
      match j with
      | Fin.F1 => Ord3_1
      | Fin.FS _ => Ord3_2
      end
  end.

Definition Ord3_index (x : Ord3Node) : Fin.t 3 :=
  match x with
  | Ord3_0 => Fin.F1
  | Ord3_1 => Fin.FS Fin.F1
  | Ord3_2 => Fin.FS (Fin.FS Fin.F1)
  end.

Lemma Ord3_node_rt (x : Ord3Node) : Ord3_node (Ord3_index x) = x.
Proof. destruct x; reflexivity. Qed.

Definition Ord3_ecount (x y : Ord3Node) : nat :=
  match x, y with
  | Ord3_0, Ord3_1 => 1
  | Ord3_1, Ord3_2 => 1
  | Ord3_0, Ord3_2 => 1
  | _, _ => 0
  end.

Definition Ord3_edge (x y : Ord3Node) :
  Fin.t (Ord3_ecount x y) → Ord3Edge x y.
Proof.
  destruct x, y; simpl; intro i;
    solve [ exact (Fin.case0 _ i)
          | exact Ord3_a | exact Ord3_b | exact Ord3_c ].
Defined.

Definition Ord3_eindex (x y : Ord3Node) (e : Ord3Edge x y) :
  Fin.t (Ord3_ecount x y) :=
  match e in Ord3Edge a b return Fin.t (Ord3_ecount a b) with
  | Ord3_a => Fin.F1
  | Ord3_b => Fin.F1
  | Ord3_c => Fin.F1
  end.

Lemma Ord3_edge_rt (x y : Ord3Node) (e : Ord3Edge x y) :
  Ord3_edge x y (Ord3_eindex x y e) = e.
Proof. destruct e; reflexivity. Qed.

Definition Ord3Finite : FiniteQuiver Ord3Quiver :=
  @Build_FiniteQuiver Ord3Quiver 3 Ord3_node Ord3_index Ord3_node_rt
    Ord3_ecount Ord3_edge Ord3_eindex Ord3_edge_rt.

Definition Ord3Presentation : FinitePresentation := {|
  fp_quiver := Ord3Quiver;
  fp_finite := Ord3Finite;
  fp_eqns := Ord3Eqns
|}.

(** The presented category. *)
Definition Ord3 : Category :=
  PresentedQuiver Ord3Quiver (fe_rel Ord3Eqns).

(** ...in which the two paths ARE identified. *)
Lemma ord3_relation_holds :
  @equiv _ (@homset Ord3 Ord3_0 Ord3_2) ord3_path_c ord3_path_ab.
Proof. apply cc_gen. exists Fin.F1. split; reflexivity. Qed.

(** ** Riehl's walking commutative square

    The free category on the square quiver has two distinct diagonals; the
    relations are what distinguish the walking commutative square from it.
    See the header for why this is proved natively rather than cited from
    [Construction/Funny/Comparison.v]. *)

Inductive SquareNode : Set := Sq_A | Sq_B | Sq_C | Sq_D.

Inductive SquareEdge : SquareNode → SquareNode → Set :=
  | Sq_f : SquareEdge Sq_A Sq_B
  | Sq_g : SquareEdge Sq_A Sq_C
  | Sq_h : SquareEdge Sq_B Sq_D
  | Sq_k : SquareEdge Sq_C Sq_D.

Definition SquareQuiver : Quiver :=
  Build_Quiver_Standard_Eq SquareNode SquareEdge.

Definition square_diag_fh : Sq_A ~{FreeOnQuiver SquareQuiver}~> Sq_D :=
  tcons (B:=@edges SquareQuiver) _ Sq_f
    (tlist_singleton (B:=@edges SquareQuiver) Sq_h).

Definition square_diag_gk : Sq_A ~{FreeOnQuiver SquareQuiver}~> Sq_D :=
  tcons (B:=@edges SquareQuiver) _ Sq_g
    (tlist_singleton (B:=@edges SquareQuiver) Sq_k).

(** Riehl §1.6 Remark 1.6.7's negative half.  The in-tree shadow of the
    same fact under a different name is [funny_diagonals_distinct]
    ([Construction/Funny/Comparison.v]), which this file does not
    [Require]. *)
Theorem free_square_diagonals_distinct :
  square_diag_fh ≈ square_diag_gk → False.
Proof.
  unfold square_diag_fh, square_diag_gk, tlist_singleton; simpl.
  unfold tlist_quiver_equiv; simpl. intros [q He Ht]. discriminate q.
Qed.

(** Soundness of the recipe: quotienting by no equations changes nothing.
    The congruence generated by the empty relation is the ambient [≈], so
    the two diagonals stay apart in the presented category too — the
    quotient does not collapse indiscriminately. *)
Definition AmbientCong (C : Category) : @HomCongruence C (fun x y f g => f ≈ g).
Proof.
  unshelve econstructor.
  - intros x y f g H; exact H.
  - intros x y f g H; symmetry; exact H.
  - intros x y f g h H1 H2; transitivity g; assumption.
  - intros x y z f f' g g' H1 H2; now rewrite H1, H2.
Defined.

Definition SquareNoEqns : FiniteEquations SquareQuiver :=
  {| fe_count := fun _ _ => O;
     fe_lhs := fun x y i => Fin.case0 _ i;
     fe_rhs := fun x y i => Fin.case0 _ i |}.

Definition SquareFree : Category :=
  PresentedQuiver SquareQuiver (fe_rel SquareNoEqns).

Theorem presented_no_eqns_separates :
  @equiv _ (@homset SquareFree Sq_A Sq_D) square_diag_fh square_diag_gk → False.
Proof.
  intro H.
  apply free_square_diagonals_distinct.
  refine (@cc_least (FreeOnQuiver SquareQuiver) (fe_rel SquareNoEqns)
            (fun x y f g => f ≈ g) (AmbientCong _) _ _ _ _ _ H).
  intros x y f g [i _]. exact (Fin.case0 _ i).
Qed.
