Require Import Coq.ZArith.ZArith.

Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Universal.Arrow.
Require Import Category.Theory.Algebra.Rig.
Require Import Category.Instance.Sets.
Require Import Category.Instance.CMon.
Require Import Category.Instance.Ab.
Require Import Category.Instance.Rng.
Require Import Category.Instance.Mod.
Require Import Category.Instance.Rng.Algebras.Associative.
Require Import Category.Instance.Lie.

Generalizable All Variables.

#[local] Obligation Tactic := idtac.

(** * The universal enveloping algebra, and E ⊣ V

    Book: Mac Lane, "Categories for the Working Mathematician", 2nd ed.,
          GTM 5, §IV.2, printed p. 89 (PDF p. 98), Exercise 3
          (maclane:IV.2:ex3).  With Lie_K the category of small Lie
          algebras over K and V : Alg_K ⟶ Lie_K the functor putting the
          commutator bracket [a,b] = ab - ba on an associative algebra,
          the exercise asks that the universal enveloping algebra
          functor E be exhibited as a left adjoint of V.
    nLab:      https://ncatlab.org/nlab/show/universal+enveloping+algebra
    nLab:      https://ncatlab.org/nlab/show/Poincare-Birkhoff-Witt+theorem
    Wikipedia: https://en.wikipedia.org/wiki/Universal_enveloping_algebra

    THIS FILE IS E AND THE ADJUNCTION, work items 3 and 4 of the issue,
    and nothing else.  Items 1 and 2 -- the two categories and the
    commutator functor V -- are Instance/Rng/Algebras/Associative.v and
    Instance/Lie.v, both of which are CONSUMED here and neither of which
    is modified: [AAlgObject], [AAlg], [AAlgHom], [AAlg_RMod],
    [aalg_central], [UT2_AAlg] come from the first, and [LieObject],
    [LieHom], [Lie], [lie_of_aalg], [CommutatorFunctor], [lie_abelian]
    and [Lie_UT2] from the second.  The issue's "Current state" clause
    "There is no category of associative algebras" was already stale
    when Instance/Lie.v landed, and that file's header records the
    correction; it is not repeated here.

    ** POINCARÉ-BIRKHOFF-WITT: DEFERRED, AND NOTHING BELOW DEPENDS ON IT

    The issue's reviewer check is that the adjunction be proved WITHOUT
    appealing to PBW.  It is, and the reason is structural rather than a
    matter of care: an adjunction is a statement about a universal
    property, and the universal property here is proved by ONE induction
    over the term type ([uenv_extend_unique], five cases) and ONE
    induction over the generating congruence ([uenv_eval_respects],
    twenty-two cases).  Neither mentions a basis, a filtration, a
    grading, an ordering of generators, or a symmetric algebra, and the
    strings "basis", "filtration" and "PBW" occur nowhere below this
    essay.

    PBW IS NOT PROVED AND IS NOT ASSUMED.  What it would give, and what
    is therefore NOT claimed anywhere in this file: that [uenv_insert]
    is injective; that L embeds in U(L); that [EnvelopingFunctor] is
    faithful; that U(L) of an abelian Lie algebra is a polynomial
    algebra.  In particular [uenv_ut2_gens_distinct] is NOT an instance
    of PBW -- it separates two SPECIFIC generators of ONE Lie algebra by
    mapping OUT into [UT2], and says nothing about any other L, nor
    about any other pair of elements.

    ** WHICH ROUTE TO U(L), AND WHAT THE OTHER WOULD HAVE COST

    ROUTE (b) IS TAKEN: U(L) is built DIRECTLY by generators and
    relations -- an inductive term type [UEnvTerm] with five formers and
    an inductive congruence [uenv_eq] with twenty-two constructors,
    twenty of them the associative-algebra laws in the shape
    Instance/Vect/TensorAlgebra.v and Instance/Rng/MonoidRing.v already
    use, plus [uq_bracket], the enveloping relation, plus symmetry and
    transitivity.  Reflexivity is derived, keeping the relation's
    induction principle one case shorter wherever it is consumed.

    ROUTE (a) -- quotient the tensor algebra by the two-sided ideal
    generated by x⊗y - y⊗x - [x,y] -- IS AVAILABLE, and the issue's own
    warning about it needs correcting in one direction and confirming in
    another.  The warning says Construction/Quotient.v is a
    HOM-CONGRUENCE quotient, so an object-level quotient may have to be
    built.  That is true of THAT module, but it does not follow that
    nothing object-level exists: Instance/Rng/Quotient.v supplies
    [Ideal] (:125), [QuotientRing] (:423), [rquot_proj] (:468),
    [rquot_proj_epic] (:498) and the descent [rquot_med] (:572) --
    quotients of RINGS by ideals, exactly the layer route (a) needs.
    What route (a) would still have to build is measured rather than
    guessed: a sweep for the REQUIRED field [idl_mem :=], which every
    [Ideal] literal must supply, returns SIX inhabitants
    ([KernelIdeal], [TrivialIdeal], [TotalIdeal], [EvenIdeal],
    [SixIdeal] in Instance/Rng/Quotient.v, and [StrictUpper] in
    Instance/Rng/Quotient/OneSided.v:171 -- an ideal of UT2, this
    development's own witness ring).  A NAME-based sweep returns five
    and misses [StrictUpper], whose name omits the word "Ideal"; the
    field-based one is exhaustive by construction.  All six are
    closed-form membership predicates,
    and no ideal GENERATED by a set of elements anywhere --
    so the inductive closure (a generator clause, saturation under [≈],
    zero, sums, and both absorptions), the five [Ideal] fields over it,
    the rebuilt [AAlgObject] on the quotient with its centrality, the
    rebuilt insertion, an induction over that closure showing [teval]
    kills the ideal, and uniqueness through [rquot_proj_epic].

    THE MODULE COST IS MEASURED, by closing the [Require] graph: this
    file's closure is 53 modules; adding Instance/Vect/TensorAlgebra.v
    and Instance/Rng/Quotient.v takes it to 66, THIRTEEN more, among
    them Functor/Hom/Yoneda.v, Functor/Hom/Yoneda/Iso.v,
    Functor/Representable.v, Structure/UniversalProperty.v,
    Construction/Elements.v and Theory/Sheaf.v, none of which this
    development mentions.  A second, smaller measurement of the same
    kind decided a lemma: TensorAlgebra.v spends
    Instance/Rng/Polynomial.v's [rng_mul_neg_l]/[rng_mul_neg_r] for two
    rewrites in its centrality induction, and Instance/Lie.v carries the
    identical statements as [lie_mul_neg_l]/[lie_mul_neg_r], so this
    file spends THOSE and does not [Require] Polynomial.v -- which alone
    would have added ELEVEN modules to the closure (53 to 64).

    Route (b) also buys one thing route (a) structurally cannot, though
    this is an ARGUMENT and not a measurement, no route-(a) version
    having been built: the extension's value on a generator is a clause
    of a [Fixpoint], so [uenv_extend_gen] closes by [eq_refl], whereas
    on route (a) the insertion would be [rquot_proj] composed with the
    tensor-algebra generator and the analogous readback would have to
    traverse that projection.  No claim is made that route (a) fails, or
    that it would give a different object up to isomorphism.

    ** WHAT IS BUILT

    [UEnvRing L] is the ring of formal expressions modulo [uenv_eq];
    [uenv_scal] the scalar inclusion, whose image is CENTRAL
    ([uenv_scal_central], by induction on the term rather than by a
    further generating equation), so [UEnvAlg L : AAlgObject K].
    [uenv_insert L : LieHom L (lie_of_aalg (UEnvAlg L))] is the
    insertion, and its bracket clause IS the generating equation: the
    proof of [uenv_insert_br] is a bare [exact (uq_bracket x y)].

    [uenv_universal] is the universal mapping property in the shape
    Theory/Universal/Arrow.v's [universal_arrow_from_UMP] consumes;
    [uenv_universal_arrow] and the direct-encoding
    [uenv_auniversal_arrow] package it both ways; and then

      EnvelopingFunctor : Lie K ⟶ AAlg K
      enveloping_adjunction : EnvelopingFunctor ⊣ CommutatorFunctor K

    come out of the generic machinery with no further proof.  The
    headline is an inhabitant of Theory/Adjunction.v's [Adjunction]
    record, not a bare hom-set bijection.

    ** MEASURED FACTS: WHICH LEMMA SPENDS WHICH HYPOTHESIS

      - THE LIE MAP'S BRACKET LAW IS SPENT EXACTLY ONCE.  [lie_map_br]
        occurs at exactly one place in the file, the [uq_bracket] case
        of [uenv_eval_respects], where it is the whole proof
        ([exact (lie_map_br f x y)]).  That single line is the
        mathematical content of the forward direction: the evaluation
        obligation attached to the enveloping relation IS the
        hypothesis that f preserves the bracket, on the nose, with no
        rearrangement, because [lie_br (lie_of_aalg A)] unfolds to
        Instance/Lie.v's [lie_comm_br A] and that is definitionally the
        right-hand side of [uq_bracket] evaluated.
      - CENTRALITY OF THE ALGEBRA'S STRUCTURE MAP is spent exactly once,
        at the [uq_gen_smul_r] case of [uenv_eval_respects] -- the same
        place TensorAlgebra.v spends it, and the reason the
        centre-valued [AAlgObject] rather than the commutative
        [KAlgObject] is the right target.
      - COMMUTATIVITY OF THE BASE RING ([`2 K]) is spent exactly once,
        at the scalar case of [uenv_scal_central].
      - [uenv_extend_unique] consumes NO Lie structure at all: its
        induction has one case per former, the two base cases being its
        two hypotheses and the other three the competitor's own
        homomorphism laws ([rig_map_add], [RigHom_neg] -- a theorem
        rather than a field -- and [rig_map_mul]).  Uniqueness is a fact
        about the formers and never sees the bracket.
      - NO LIE AXIOM IS CONSUMED ANYWHERE.  Certified at the PROOF
        TERMS, which is what the claim needs: a source grep can miss a
        typeclass-resolved constant, and demonstrably does here --
        [LieHom_Setoid] occurs in neither this file's source nor its
        [.glob], yet appears seven times in the printed terms.  The
        identifiers [lie_alt], [lie_jacobi], [lie_br_add_l],
        [lie_br_add_r], [lie_br_smul_l], [lie_br_smul_r],
        [lie_antisym] and [lie_br_respects] occur ZERO times below.
        Read that at exactly its strength -- it says what the proofs
        here consume, and it is part of why no PBW-like input is
        needed.  It is NOT a claim that the construction works for a
        category of bare bracketed modules: no such category is built,
        no generalisation is stated, and the theorem delivered is about
        [Lie K].
      - [uq_gen_smul_r], right K-linearity of the insertion, is carried
        as a generating equation for the reason TensorAlgebra.v gives
        for its counterpart -- it is what makes the scalars central.
        NO non-derivability is proved here and none is claimed; dropping
        it was not attempted.

    ** REUSED VERSUS BUILT

    REUSED, not rebuilt: [LieObject], [LieHom], [Build_LieHom], [Lie],
    [lie_mod], [lie_br], [lie_hom], [lie_map_br], [lie_of_aalg],
    [CommutatorFunctor], [lie_abelian], [Lie_UT2], [lie_mul_neg_l],
    [lie_mul_neg_r] (Instance/Lie.v); [AAlgObject], [AAlg], [AAlgHom],
    [AAlg_RMod], [aalg_ring], [aalg_unit], [aalg_central], [UT2],
    [UT2_AAlg], [ut2_e11], [ut2_e12], [ut2_eqT] (Associative.v);
    [RModHom], [rm_hom], [rm_map_smul] (Mod.v); [ab_cancel_l] (Ab.v);
    [RigHom_neg], [Int_CRng] and the rig/ring calculus (Rng.v, Rig.v);
    [universal_arrow_from_UMP], [AUniversalArrow],
    [LeftAdjointFunctorFromUniversalArrows],
    [AdjunctionFromUniversalArrows] (Theory/Universal/Arrow.v); [unit],
    [counit] and [fmap_counit_unit] (Theory/Adjunction.v).

    BUILT here: everything named [UEnv*], [uen_*], [uq_*], [uenv_*],
    [EnvelopingFunctor] or [enveloping_adjunction].  One of them,
    [uenv_sub_zero] (a + (-b) ≈ 0 implies a ≈ b), mentions neither a Lie
    algebra nor an enveloping algebra and is an upstreaming candidate
    for Instance/Rng.v; it is declared here for the reason
    Instance/Ab/Subtract.v and Instance/Lie.v give for the same choice.

    ** STRICT VERSUS SETOID

    TWELVE identifications close at [eq_refl], of which two are probe
    controls, so TEN belong to the development proper:
    [uenv_extend_gen] and [uenv_extend_scal] (the extension restricted
    to generators and to scalars -- clauses of the fixpoint);
    [uenv_universal_med] (THE MEDIATOR THE UNIVERSAL PROPERTY PRODUCES
    IS the fixpoint extension, which is why [uenv_universal] is
    [Defined] and not [Qed]; nothing else in the file reads through it);
    [EnvelopingFunctor_obj]; [uenv_arrow_is_insert];
    [uenv_unit_is_gen] (THE UNIT SENDS A GENERATOR TO ITSELF);
    [uenv_ut2_gen], [uenv_ut2_one], [uenv_ut2_zero] (the map out of
    U(Lie_UT2) computes); and [uenv_ut2_bracket_computes].

    What does NOT close at [eq_refl], with the reason in each case, all
    four pinned as probe negatives:

      - The unit's underlying module homomorphism is not [uenv_insert]'s
        RECORD, although the two agree POINTWISE by [eq_refl].  The unit
        is ⌊id⌋, hence [fmap[CommutatorFunctor K] id ∘ uenv_insert L],
        and composition in [Lie K] rebuilds the record through
        [rmod_hom_compose]; the pointwise reading survives because the
        identity algebra map's action reduces away.  [uenv_unit_is_insert]
        is the [≈] statement that does hold.
      - The counit is the extension of the identity Lie map only up to
        [≈] ([uenv_counit_is_extend]).  It is ⌈id⌉, produced by
        [ump_universal_arrows], which Theory/Universal/Arrow.v closes
        with [Qed], so nothing about it reduces -- which is also why
        [uenv_counit_gen] is proved from [fmap_counit_unit] rather than
        by computation.
      - The enveloping relation is a GENERATING EQUATION, not a
        computation rule: [uenv_eq] is an inductive relation and its two
        sides are distinct constructors of [UEnvTerm], so the strict
        form fails even at closed [UT2] arguments where the bracket
        itself computes.
      - [≈] between two BARE terms does not resolve, because
        [uenv_Setoid] is deliberately NOT registered as an instance --
        the convention Instance/Ab/Tensor.v, Instance/Rng/Polynomial.v
        and Instance/Vect/TensorAlgebra.v all follow, so that the [≈] of
        [UEnvRing] IS [uenv_eq] definitionally and Theory/Algebra/Rig.v's
        lemmas apply to it unchanged.  Read through the ring it resolves,
        and the control is that same statement.

    ** NON-DEGENERACY

    Proved in BOTH directions, and nothing below is obtained by
    induction on [uenv_eq]: an induction on a quotienting relation
    cannot produce a negative statement.  Every separation is obtained
    by mapping OUT into a concrete algebra, the route
    Instance/Vect/TensorAlgebra.v, Instance/Rng/Polynomial.v and
    Instance/Mod/Tensor.v all take.

    THE RELATION CONSTRAINS: over an abelian Lie algebra the generators
    COMMUTE ([uenv_abelian_gens_commute]), proved from [uq_bracket] and
    [uq_gen_zero] alone.  AND IT DOES NOT COLLAPSE: over [Lie_UT2] --
    the commutator Lie algebra of the upper-triangular 2x2 integer
    matrices, whose hom-setoid is Leibniz equality on Z-triples, so
    every image REDUCES -- the two generators E11 and E12 do NOT commute
    ([uenv_ut2_gens_do_not_commute]), are distinct
    ([uenv_ut2_gens_distinct]), neither is a scalar
    ([uenv_ut2_gen_not_scalar]), and U(L) is not the trivial algebra
    ([uenv_ut2_one_not_zero]); [uenv_not_all_commutative] packages the
    consequence that no theorem of this file can force U(L) to be
    commutative.  The map out is the extension of the IDENTITY Lie map
    of [Lie_UT2], which exists because [Lie_UT2] IS
    [lie_of_aalg UT2_AAlg].  The relation is exercised at a NON-ZERO
    bracket: [uenv_ut2_bracket_relation] is [uq_bracket] at E11 and E12,
    whose bracket is E12 and not zero.

    ** AUDIT

    110/110 CONSTANTS CLOSED UNDER THE GLOBAL CONTEXT, all queried by
    fully qualified name, and the count reconciles exactly rather than
    being asserted: [Print Module] lists 110 names, decomposing as 63
    source-declared heads + 5 constructors of [UEnvTerm] + 22
    constructors of [uenv_eq] + 8 generated eliminators
    ([UEnvTerm_ind]/[_rec]/[_rect]/[_sind] and the four for [uenv_eq]) +
    12 [Program] obligations, of which no source sweep sees the last
    three groups.  An independent count of declaration heads in the
    source returns 63, matching.

    ZERO NAME COLLISIONS.  All 110 names were swept against the
    declaration heads of the other 820 [.v] files in the tree, with
    attribute prefixes allowed, and nothing matched.  This matters
    because [make print-assumptions] loads many modules into ONE scope,
    where a shared name silently audits the wrong constant.  The
    prefixes were chosen after a sweep found [ue_*] already taken by
    Theory/Universal/Element.v and [env_*] partly taken by the Env
    comonad.

    ** NOT DELIVERED

      - No Poincaré-Birkhoff-Witt theorem, and hence no injectivity of
        [uenv_insert], no embedding of L in U(L), no faithfulness of
        [EnvelopingFunctor], and no basis, filtration or grading of
        U(L).  Nothing above depends on any of these, as the second
        section of this essay states.
      - No normal form for [uenv_eq], hence no decision procedure and no
        uniqueness of coefficients.
      - No comparison with Instance/Vect/TensorAlgebra.v: that module is
        NOT [Require]d and no STATEMENT below mentions it.  The route
        discussion above cites it in prose as prior art for the idiom
        and for the module measurement; that is a citation, not a
        dependency.  In particular U(L) is NOT exhibited as a quotient
        of T(L), and no comparison map between them is built.
      - No ideal, and no use of Instance/Rng/Quotient.v.
      - No coalgebra structure on U(L): no comultiplication, no counit
        in the Hopf sense, no antipode, nothing about bialgebras.  The
        word "counit" below always means the counit of the adjunction.
      - Nothing about monadicity: [CommutatorFunctor] is not claimed
        monadic, and no comparison with the Eilenberg-Moore category of
        the induced monad is made.
      - K is an arbitrary commutative RING throughout, where Mac Lane's
        exercise fixes a field; that is more general on that axis, and
        nothing below consumes invertibility of scalars.  No claim is
        made that the field case is thereby settled in any respect the
        general case does not already cover -- PBW is precisely where
        the two differ, and PBW is deferred.
      - No free Lie algebra and no left adjoint to [Lie_Forget_Mod].
      - No naturality statement beyond what the [Adjunction] record
        itself carries; no uniqueness of E up to isomorphism is stated
        beyond what Theory/Universal/Arrow.v's own uniqueness gives.
      - No universe measurement: this file declares no universe binder
        and inspects no constraint block.
      - The Lie-GROUP deferral Instance/Rng/Frac.v records (§I.3
        Exercise 1, the Lie algebra of a Lie group) is a different item
        and is untouched, as Instance/Lie.v already says. *)

Section UEnveloping.

Context (K : CRng).
Context (L : LieObject K).

(** ** Formal expressions *)

Inductive UEnvTerm : Type :=
  | uen_scal : carrier (rig_setoid (`1 K)) → UEnvTerm
  | uen_gen  : carrier (cmon_setoid (lie_mod L)) → UEnvTerm
  | uen_add  : UEnvTerm → UEnvTerm → UEnvTerm
  | uen_neg  : UEnvTerm → UEnvTerm
  | uen_mul  : UEnvTerm → UEnvTerm → UEnvTerm.

(** ** The congruence *)

Inductive uenv_eq : UEnvTerm → UEnvTerm → Type :=
  | uq_scal {a b} : a ≈ b → uenv_eq (uen_scal a) (uen_scal b)
  | uq_gen {v w} : v ≈ w → uenv_eq (uen_gen v) (uen_gen w)
  | uq_add {s s' t t'} :
      uenv_eq s s' → uenv_eq t t' → uenv_eq (uen_add s t) (uen_add s' t')
  | uq_neg {s s'} : uenv_eq s s' → uenv_eq (uen_neg s) (uen_neg s')
  | uq_mul {s s' t t'} :
      uenv_eq s s' → uenv_eq t t' → uenv_eq (uen_mul s t) (uen_mul s' t')

  | uq_add_assoc s t u :
      uenv_eq (uen_add (uen_add s t) u) (uen_add s (uen_add t u))
  | uq_add_comm s t : uenv_eq (uen_add s t) (uen_add t s)
  | uq_add_zero_l s : uenv_eq (uen_add (uen_scal (rig_zero (`1 K))) s) s
  | uq_add_neg_l s :
      uenv_eq (uen_add (uen_neg s) s) (uen_scal (rig_zero (`1 K)))

  | uq_mul_assoc s t u :
      uenv_eq (uen_mul (uen_mul s t) u) (uen_mul s (uen_mul t u))
  | uq_mul_one_l s : uenv_eq (uen_mul (uen_scal (rig_one (`1 K))) s) s
  | uq_mul_one_r s : uenv_eq (uen_mul s (uen_scal (rig_one (`1 K)))) s

  | uq_distr_l s t u :
      uenv_eq (uen_mul s (uen_add t u))
              (uen_add (uen_mul s t) (uen_mul s u))
  | uq_distr_r s t u :
      uenv_eq (uen_mul (uen_add s t) u)
              (uen_add (uen_mul s u) (uen_mul t u))

  | uq_scal_add a b :
      uenv_eq (uen_scal (rig_add (`1 K) a b))
              (uen_add (uen_scal a) (uen_scal b))
  | uq_scal_mul a b :
      uenv_eq (uen_scal (rig_mul (`1 K) a b))
              (uen_mul (uen_scal a) (uen_scal b))

  | uq_gen_add v w :
      uenv_eq (uen_gen (cmon_plus (lie_mod L) v w))
              (uen_add (uen_gen v) (uen_gen w))
  | uq_gen_smul_l r v :
      uenv_eq (uen_gen (rm_smul (lie_mod L) r v))
              (uen_mul (uen_scal r) (uen_gen v))
  | uq_gen_smul_r r v :
      uenv_eq (uen_gen (rm_smul (lie_mod L) r v))
              (uen_mul (uen_gen v) (uen_scal r))

  (* THE ENVELOPING RELATION. *)
  | uq_bracket x y :
      uenv_eq (uen_gen (lie_br L x y))
              (uen_add (uen_mul (uen_gen x) (uen_gen y))
                       (uen_neg (uen_mul (uen_gen y) (uen_gen x))))

  | uq_sym {s t} : uenv_eq s t → uenv_eq t s
  | uq_trans {s t u} : uenv_eq s t → uenv_eq t u → uenv_eq s u.

Lemma uenv_refl (s : UEnvTerm) : uenv_eq s s.
Proof.
  induction s.
  - exact (uq_scal (reflexivity _)).
  - exact (uq_gen (reflexivity _)).
  - exact (uq_add IHs1 IHs2).
  - exact (uq_neg IHs).
  - exact (uq_mul IHs1 IHs2).
Qed.

Lemma uenv_eq_Equivalence : Equivalence uenv_eq.
Proof.
  constructor.
  - exact uenv_refl.
  - exact (fun s t => uq_sym).
  - exact (fun s t u => uq_trans).
Qed.

Definition uenv_Setoid : Setoid UEnvTerm := {|
  equiv        := uenv_eq;
  setoid_equiv := uenv_eq_Equivalence
|}.

(** ** Derived laws *)

Let UZ : UEnvTerm := uen_scal (rig_zero (`1 K)).
Let UO : UEnvTerm := uen_scal (rig_one (`1 K)).

Lemma uq_add_zero_r (s : UEnvTerm) : uenv_eq (uen_add s UZ) s.
Proof. exact (uq_trans (uq_add_comm s UZ) (uq_add_zero_l s)). Qed.

Lemma uq_add_neg_r (s : UEnvTerm) : uenv_eq (uen_add s (uen_neg s)) UZ.
Proof. exact (uq_trans (uq_add_comm s (uen_neg s)) (uq_add_neg_l s)). Qed.

Lemma uq_add_cancel_l (s t u : UEnvTerm) :
  uenv_eq (uen_add s t) (uen_add s u) → uenv_eq t u.
Proof.
  intro H.
  refine (uq_trans (uq_sym (uq_add_zero_l t)) _).
  refine (uq_trans (uq_add (uq_sym (uq_add_neg_l s)) (uenv_refl t)) _).
  refine (uq_trans (uq_add_assoc (uen_neg s) s t) _).
  refine (uq_trans (uq_add (uenv_refl (uen_neg s)) H) _).
  refine (uq_trans (uq_sym (uq_add_assoc (uen_neg s) s u)) _).
  refine (uq_trans (uq_add (uq_add_neg_l s) (uenv_refl u)) _).
  exact (uq_add_zero_l u).
Qed.

Lemma uq_mul_zero_l (s : UEnvTerm) : uenv_eq (uen_mul UZ s) UZ.
Proof.
  apply (uq_add_cancel_l (uen_mul UZ s)).
  refine (uq_trans (uq_sym (uq_distr_r UZ UZ s)) _).
  refine (uq_trans (uq_mul _ (uenv_refl s))
            (uq_sym (uq_add_zero_r (uen_mul UZ s)))).
  refine (uq_trans (uq_sym (uq_scal_add (rig_zero (`1 K))
                              (rig_zero (`1 K)))) _).
  exact (uq_scal (rig_add_zero_l (`1 K) (rig_zero (`1 K)))).
Qed.

Lemma uq_mul_zero_r (s : UEnvTerm) : uenv_eq (uen_mul s UZ) UZ.
Proof.
  apply (uq_add_cancel_l (uen_mul s UZ)).
  refine (uq_trans (uq_sym (uq_distr_l s UZ UZ)) _).
  refine (uq_trans (uq_mul (uenv_refl s) _)
            (uq_sym (uq_add_zero_r (uen_mul s UZ)))).
  refine (uq_trans (uq_sym (uq_scal_add (rig_zero (`1 K))
                              (rig_zero (`1 K)))) _).
  exact (uq_scal (rig_add_zero_l (`1 K) (rig_zero (`1 K)))).
Qed.

Lemma uq_gen_zero : uenv_eq (uen_gen (cmon_zero (lie_mod L))) UZ.
Proof.
  apply (uq_add_cancel_l (uen_gen (cmon_zero (lie_mod L)))).
  refine (uq_trans _
            (uq_sym (uq_add_zero_r (uen_gen (cmon_zero (lie_mod L)))))).
  refine (uq_trans (uq_sym (uq_gen_add (cmon_zero (lie_mod L))
                              (cmon_zero (lie_mod L)))) _).
  exact (uq_gen (cmon_plus_zero_l (lie_mod L) (cmon_zero (lie_mod L)))).
Qed.

(** ** The ring U(L) *)

Definition UEnvRig : RigObject := {|
  rig_setoid := {| carrier := UEnvTerm; is_setoid := uenv_Setoid |};
  rig_zero := UZ;
  rig_add := uen_add;
  rig_one := UO;
  rig_mul := uen_mul;
  rig_add_respects := fun _ _ Hs _ _ Ht => uq_add Hs Ht;
  rig_mul_respects := fun _ _ Hs _ _ Ht => uq_mul Hs Ht;
  rig_add_assoc := uq_add_assoc;
  rig_add_comm := uq_add_comm;
  rig_add_zero_l := uq_add_zero_l;
  rig_mul_assoc := uq_mul_assoc;
  rig_mul_one_l := uq_mul_one_l;
  rig_mul_one_r := uq_mul_one_r;
  rig_distr_l := uq_distr_l;
  rig_distr_r := uq_distr_r;
  rig_mul_zero_l := uq_mul_zero_l;
  rig_mul_zero_r := uq_mul_zero_r
|}.

Definition UEnvRing : RingObject := {|
  ring_rig := UEnvRig;
  ring_neg := uen_neg;
  ring_neg_respects := fun _ _ Hs => uq_neg Hs;
  ring_neg_l := uq_add_neg_l
|}.

(** ** The scalar inclusion, and centrality of its image *)

Program Definition uenv_scal : `1 K ~{Rng}~> UEnvRing := {|
  rig_map := {| morphism := uen_scal |}
|}.
Next Obligation. intros a b H; exact (uq_scal H). Qed.
Next Obligation. simpl; exact (uenv_refl UZ). Qed.
Next Obligation. intros a b; exact (uq_scal_add a b). Qed.
Next Obligation. simpl; exact (uenv_refl UO). Qed.
Next Obligation. intros a b; exact (uq_scal_mul a b). Qed.

Lemma uenv_scal_central (r : carrier (rig_setoid (`1 K))) (t : UEnvTerm) :
  uenv_eq (uen_mul (uen_scal r) t) (uen_mul t (uen_scal r)).
Proof.
  induction t as [ a | v | s IHs u IHu | s IHs | s IHs u IHu ].
  - refine (uq_trans (uq_sym (uq_scal_mul r a)) _).
    refine (uq_trans (uq_scal (`2 K r a)) _).
    exact (uq_scal_mul a r).
  - exact (uq_trans (uq_sym (uq_gen_smul_l r v)) (uq_gen_smul_r r v)).
  - refine (uq_trans (uq_distr_l (uen_scal r) s u) _).
    refine (uq_trans (uq_add IHs IHu) _).
    exact (uq_sym (uq_distr_r s u (uen_scal r))).
  - refine (uq_trans (lie_mul_neg_r UEnvRing (uen_scal r) s) _).
    refine (uq_trans (uq_neg IHs) _).
    exact (uq_sym (lie_mul_neg_l UEnvRing s (uen_scal r))).
  - refine (uq_trans (uq_sym (uq_mul_assoc (uen_scal r) s u)) _).
    refine (uq_trans (uq_mul IHs (uenv_refl u)) _).
    refine (uq_trans (uq_mul_assoc s (uen_scal r) u) _).
    refine (uq_trans (uq_mul (uenv_refl s) IHu) _).
    exact (uq_sym (uq_mul_assoc s u (uen_scal r))).
Qed.

Definition UEnvAlg : AAlgObject K :=
  Build_AAlgObject K UEnvRing uenv_scal uenv_scal_central.

(** ** The insertion of the Lie algebra *)

Program Definition uenv_insert_mod
  : RModHom (lie_mod L) (AAlg_RMod UEnvAlg) := {|
  rm_hom := {| cmon_map := {| morphism := uen_gen ;
                              proper_morphism := fun v w H => uq_gen H |} ;
               cmon_map_zero := uq_gen_zero ;
               cmon_map_plus := uq_gen_add |}
|}.
Next Obligation. intros r v; exact (uq_gen_smul_l r v). Qed.

Lemma uenv_insert_br (x y : carrier (cmon_setoid (lie_mod L))) :
  cmon_map (rm_hom uenv_insert_mod) (lie_br L x y)
    ≈ lie_br (lie_of_aalg UEnvAlg)
        (cmon_map (rm_hom uenv_insert_mod) x)
        (cmon_map (rm_hom uenv_insert_mod) y).
Proof. exact (uq_bracket x y). Qed.

Definition uenv_insert : LieHom L (lie_of_aalg UEnvAlg) :=
  @Build_LieHom K L (lie_of_aalg UEnvAlg) uenv_insert_mod uenv_insert_br.

(** * Evaluation *)

Section UEnvEvaluation.

Context (A : AAlgObject K).
Context (f : LieHom L (lie_of_aalg A)).

Fixpoint uenv_eval (t : UEnvTerm) : carrier (rig_setoid (aalg_ring A)) :=
  match t with
  | uen_scal a  => rig_map (aalg_unit A) a
  | uen_gen v   => cmon_map (rm_hom (lie_hom f)) v
  | uen_add s t => rig_add (aalg_ring A) (uenv_eval s) (uenv_eval t)
  | uen_neg s   => ring_neg (aalg_ring A) (uenv_eval s)
  | uen_mul s t => rig_mul (aalg_ring A) (uenv_eval s) (uenv_eval t)
  end.

Lemma uenv_eval_respects (s t : UEnvTerm) :
  uenv_eq s t → uenv_eval s ≈ uenv_eval t.
Proof.
  intro He.
  induction He as
    [ a b Hab
    | v w Hvw
    | s s' t t' _ IHs _ IHt
    | s s' _ IHs
    | s s' t t' _ IHs _ IHt
    | s t w | s t | s | s
    | s t w | s | s
    | s t w | s t w
    | a b | a b
    | v w | r v | r v
    | x y
    | s t _ IHst
    | s t w _ IHst _ IHtw ]; simpl.
  - exact (proper_morphism (rig_map (aalg_unit A)) _ _ Hab).
  - exact (proper_morphism (cmon_map (rm_hom (lie_hom f))) _ _ Hvw).
  - exact (rig_add_respects (aalg_ring A) _ _ IHs _ _ IHt).
  - exact (ring_neg_respects (aalg_ring A) _ _ IHs).
  - exact (rig_mul_respects (aalg_ring A) _ _ IHs _ _ IHt).
  - exact (rig_add_assoc (aalg_ring A) _ _ _).
  - exact (rig_add_comm (aalg_ring A) _ _).
  - rewrite (rig_map_zero (aalg_unit A)); apply rig_add_zero_l.
  - rewrite (rig_map_zero (aalg_unit A)); apply (ring_neg_l (aalg_ring A)).
  - exact (rig_mul_assoc (aalg_ring A) _ _ _).
  - rewrite (rig_map_one (aalg_unit A)); apply rig_mul_one_l.
  - rewrite (rig_map_one (aalg_unit A)); apply rig_mul_one_r.
  - exact (rig_distr_l (aalg_ring A) _ _ _).
  - exact (rig_distr_r (aalg_ring A) _ _ _).
  - exact (rig_map_add (aalg_unit A) a b).
  - exact (rig_map_mul (aalg_unit A) a b).
  - exact (cmon_map_plus (rm_hom (lie_hom f)) v w).
  - exact (rm_map_smul (lie_hom f) r v).
  - rewrite (rm_map_smul (lie_hom f) r v); apply aalg_central.
  - exact (lie_map_br f x y).
  - exact (symmetry IHst).
  - exact (transitivity IHst IHtw).
Qed.

Program Definition uenv_extend_ring : UEnvRing ~{Rng}~> aalg_ring A := {|
  rig_map := {| morphism := uenv_eval |}
|}.
Next Obligation. intros s t He; exact (uenv_eval_respects s t He). Qed.
Next Obligation. simpl; exact (rig_map_zero (aalg_unit A)). Qed.
Next Obligation. intros s t; simpl; reflexivity. Qed.
Next Obligation. simpl; exact (rig_map_one (aalg_unit A)). Qed.
Next Obligation. intros s t; simpl; reflexivity. Qed.

Lemma uenv_extend_triangle :
  aalg_unit A ≈ uenv_extend_ring ∘ aalg_unit UEnvAlg.
Proof. intro a; simpl; reflexivity. Qed.

Definition uenv_extend : UEnvAlg ~{AAlg K}~> A :=
  (uenv_extend_ring; uenv_extend_triangle).

Example uenv_extend_gen (v : carrier (cmon_setoid (lie_mod L))) :
  rig_map (`1 uenv_extend) (uen_gen v)
    = cmon_map (rm_hom (lie_hom f)) v := eq_refl.

Example uenv_extend_scal (a : carrier (rig_setoid (`1 K))) :
  rig_map (`1 uenv_extend) (uen_scal a) = rig_map (aalg_unit A) a := eq_refl.

Lemma uenv_extend_unique (g : UEnvRing ~{Rng}~> aalg_ring A)
  (Hscal : ∀ a, rig_map g (uen_scal a) ≈ rig_map (aalg_unit A) a)
  (Hgen : ∀ v, rig_map g (uen_gen v) ≈ cmon_map (rm_hom (lie_hom f)) v)
  (t : UEnvTerm) : rig_map g t ≈ uenv_eval t.
Proof.
  induction t as [ a | v | s IHs t IHt | s IHs | s IHs t IHt ]; simpl.
  - exact (Hscal a).
  - exact (Hgen v).
  - rewrite (rig_map_add g s t).
    exact (rig_add_respects (aalg_ring A) _ _ IHs _ _ IHt).
  - rewrite (RigHom_neg UEnvRing (aalg_ring A) g s).
    exact (ring_neg_respects (aalg_ring A) _ _ IHs).
  - rewrite (rig_map_mul g s t).
    exact (rig_mul_respects (aalg_ring A) _ _ IHs _ _ IHt).
Qed.

End UEnvEvaluation.

Lemma uenv_alg_hom_scal (A : AAlgObject K) (g : UEnvAlg ~{AAlg K}~> A)
  (a : carrier (rig_setoid (`1 K))) :
  rig_map (`1 g) (uen_scal a) ≈ rig_map (aalg_unit A) a.
Proof. symmetry; exact (`2 g a). Qed.

End UEnveloping.

Arguments UEnvTerm {K} L.
Arguments uen_scal {K L} a.
Arguments uen_gen {K L} v.
Arguments uen_add {K L} s t.
Arguments uen_neg {K L} s.
Arguments uen_mul {K L} s t.
Arguments uenv_eq {K L} s t.
Arguments uq_scal {K L a b} _.
Arguments uq_gen {K L v w} _.
Arguments uq_add {K L s s' t t'} _ _.
Arguments uq_neg {K L s s'} _.
Arguments uq_mul {K L s s' t t'} _ _.
Arguments uq_bracket {K L} x y.
Arguments uq_sym {K L s t} _.
Arguments uq_trans {K L s t u} _ _.
Arguments uenv_refl {K L} s.
Arguments uq_gen_zero {K} L.
Arguments UEnvRing {K} L.
Arguments UEnvAlg {K} L.
Arguments uenv_scal {K} L.
Arguments uenv_insert {K} L.
Arguments uenv_eval {K L} A f t.
Arguments uenv_extend {K L} A f.
Arguments uenv_extend_unique {K L} A f g Hscal Hgen t.
Arguments uenv_alg_hom_scal {K L} A g a.

(** * The universal property, and Mac Lane's E *)

Section EnvelopingUniversal.

Context (K : CRng).

(** The universal mapping property in the shape [universal_arrow_from_UMP]
    consumes. *)
Lemma uenv_universal (L : Lie K) (A : AAlg K)
  (h : L ~{Lie K}~> fobj[CommutatorFunctor K] A) :
  ∃! g : UEnvAlg L ~{AAlg K}~> A,
    h ≈ fmap[CommutatorFunctor K] g ∘ uenv_insert L.
Proof.
  unshelve eexists.
  - exact (uenv_extend A h).
  - intro v; simpl; reflexivity.
  - intros g Hg t; simpl.
    symmetry.
    apply (uenv_extend_unique A h (`1 g)).
    + intro a; exact (uenv_alg_hom_scal A g a).
    + intro v; symmetry; exact (Hg v).
Defined.

(* The mediator the universal property produces IS the fixpoint
   extension, on the nose -- which is why [uenv_universal] is [Defined].
   Nothing else in the file reads through it. *)
Example uenv_universal_med (L : Lie K) (A : AAlg K)
  (h : L ~{Lie K}~> fobj[CommutatorFunctor K] A) :
  unique_obj (uenv_universal L A h) = uenv_extend A h := eq_refl.

Definition uenv_universal_arrow (L : Lie K)
  : UniversalArrow L (CommutatorFunctor K) :=
  universal_arrow_from_UMP L (CommutatorFunctor K) (UEnvAlg L)
    (uenv_insert L) (uenv_universal L).

(* The same content in the direct encoding, where the universal object is
   named rather than projected out of a comma category. *)
Program Definition uenv_auniversal_arrow (L : Lie K)
  : AUniversalArrow L (CommutatorFunctor K) (UEnvAlg L) := {|
  universal_arrow := uenv_insert L
|}.
Next Obligation.
  intros L A h.
  unshelve eexists.
  - exact (uenv_extend A h).
  - intro v; simpl; reflexivity.
  - intros g Hg t; simpl.
    symmetry.
    apply (uenv_extend_unique A h (`1 g)).
    + intro a; exact (uenv_alg_hom_scal A g a).
    + intro v; exact (Hg v).
Qed.

(** ** The enveloping functor and THE ADJUNCTION *)

Definition EnvelopingFunctor : Lie K ⟶ AAlg K :=
  LeftAdjointFunctorFromUniversalArrows (CommutatorFunctor K)
    uenv_universal_arrow.

Definition enveloping_adjunction
  : EnvelopingFunctor ⊣ CommutatorFunctor K :=
  AdjunctionFromUniversalArrows (CommutatorFunctor K) uenv_universal_arrow.

Example EnvelopingFunctor_obj (L : Lie K) :
  fobj[EnvelopingFunctor] L = UEnvAlg L := eq_refl.

Example uenv_arrow_is_insert (L : Lie K) :
  @arrow _ _ L (CommutatorFunctor K) (uenv_universal_arrow L)
    = uenv_insert L := eq_refl.

(** ** The unit *)

Definition uenv_unit (L : Lie K)
  : L ~{Lie K}~> fobj[CommutatorFunctor K] (fobj[EnvelopingFunctor] L) :=
  @Category.Theory.Adjunction.unit _ _ _ _ enveloping_adjunction L.

Example uenv_unit_is_gen (L : Lie K)
  (v : carrier (cmon_setoid (lie_mod L))) :
  cmon_map (rm_hom (lie_hom (uenv_unit L))) v = uen_gen v := eq_refl.

(* The unit and the insertion agree POINTWISE on the nose, by the
   [eq_refl] above; the two underlying module homomorphisms are
   nevertheless not the same record, and the probe section pins that. *)
Theorem uenv_unit_is_insert (L : Lie K) :
  uenv_unit L ≈ uenv_insert L.
Proof. intro v; reflexivity. Qed.

(** ** The counit *)

Definition uenv_counit (A : AAlg K)
  : fobj[EnvelopingFunctor] (fobj[CommutatorFunctor K] A) ~{AAlg K}~> A :=
  @Category.Theory.Adjunction.counit _ _ _ _ enveloping_adjunction A.

(* The counit evaluates a generator to the element it names. *)
Lemma uenv_counit_gen (A : AAlg K)
  (v : carrier (cmon_setoid (lie_mod (fobj[CommutatorFunctor K] A)))) :
  rig_map (`1 (uenv_counit A)) (uen_gen v) ≈ v.
Proof.
  exact (@fmap_counit_unit _ _ _ _ enveloping_adjunction A v).
Qed.

(* ...hence it IS the extension of the identity Lie map, up to [≈]. *)
Theorem uenv_counit_is_extend (A : AAlg K) :
  uenv_counit A
    ≈ uenv_extend A (@id (Lie K) (fobj[CommutatorFunctor K] A)).
Proof.
  intro t.
  apply (uenv_extend_unique A (@id (Lie K) (fobj[CommutatorFunctor K] A))
           (`1 (uenv_counit A))).
  - intro a; exact (uenv_alg_hom_scal A (uenv_counit A) a).
  - intro v; exact (uenv_counit_gen A v).
Qed.

End EnvelopingUniversal.

Arguments uenv_universal {K} L A h.
Arguments uenv_universal_arrow {K} L.
Arguments uenv_unit {K} L.
Arguments uenv_counit {K} A.
Arguments uenv_unit_is_insert {K} L.
Arguments uenv_counit_gen {K} A v.
Arguments uenv_counit_is_extend {K} A.

(** * Non-degeneracy

    Nothing below is obtained by induction on [uenv_eq]: an induction on
    a quotienting relation cannot produce a negative statement.  Every
    separation is obtained by mapping OUT of U(L) into a concrete
    algebra where the two candidates have visibly different values --
    the route Instance/Vect/TensorAlgebra.v, Instance/Rng/Polynomial.v
    and Instance/Mod/Tensor.v all take for their own negatives. *)

(** ** A ring fact the positive half needs *)

Lemma uenv_sub_zero (R : RingObject) (a b : carrier (rig_setoid R)) :
  rig_add R a (ring_neg R b) ≈ rig_zero R → a ≈ b.
Proof.
  intro H.
  apply (ab_cancel_l (ring_ab R) (ring_neg R b)); simpl.
  rewrite (rig_add_comm R (ring_neg R b) a).
  rewrite H.
  rewrite (ring_neg_l R b).
  reflexivity.
Qed.

(** ** The relation constrains: over an ABELIAN Lie algebra the
       generators commute

    This is the positive half, and it is proved from the generating
    equation alone: [uq_bracket] at v and w says the commutator of the
    two generators IS the generator of [v,w], which the abelian bracket
    makes the generator of zero, which [uq_gen_zero] makes the scalar
    zero. *)
Theorem uenv_abelian_gens_commute (K : CRng) (M : RModObject (`1 K))
  (v w : carrier (cmon_setoid M)) :
  uenv_eq
    (uen_mul (@uen_gen K (lie_abelian M) v) (@uen_gen K (lie_abelian M) w))
    (uen_mul (@uen_gen K (lie_abelian M) w) (@uen_gen K (lie_abelian M) v)).
Proof.
  apply (uenv_sub_zero (UEnvRing (lie_abelian M))).
  refine (uq_trans (uq_sym (@uq_bracket K (lie_abelian M) v w)) _).
  exact (uq_gen_zero (lie_abelian M)).
Qed.

(** ** ...and it does not collapse: over [Lie_UT2] they do not

    The witness algebra is Instance/Rng/Algebras/Associative.v's
    upper-triangular 2x2 integer matrices, whose hom-setoid is Leibniz
    equality on Z-triples, so every image below REDUCES and each
    negative closes by [discriminate].  The map out is the extension of
    the IDENTITY Lie map of [Lie_UT2], which exists because
    [Lie_UT2] IS [lie_of_aalg UT2_AAlg]. *)

Definition uenv_ut2 : UEnvAlg Lie_UT2 ~{AAlg Int_CRng}~> UT2_AAlg :=
  uenv_extend UT2_AAlg (@id (Lie Int_CRng) Lie_UT2).

Definition uenv_ut2_g (x : ut2) : UEnvTerm Lie_UT2 :=
  @uen_gen Int_CRng Lie_UT2 x.

(* The map out evaluates a generator to the matrix it names, on the
   nose: the fixpoint's generator clause is the identity map. *)
Example uenv_ut2_gen (x : ut2) :
  rig_map (`1 uenv_ut2) (uenv_ut2_g x) = x := eq_refl.

Example uenv_ut2_one :
  rig_map (`1 uenv_ut2) (rig_one (UEnvRing Lie_UT2)) = rig_one UT2 := eq_refl.

Example uenv_ut2_zero :
  rig_map (`1 uenv_ut2) (rig_zero (UEnvRing Lie_UT2)) = rig_zero UT2
  := eq_refl.

(* Distinct generators stay distinct: the insertion does not collapse
   the Lie algebra. *)
Theorem uenv_ut2_gens_distinct :
  uenv_eq (uenv_ut2_g ut2_e11) (uenv_ut2_g ut2_e12) → False.
Proof.
  intro H.
  pose proof (proper_morphism (rig_map (`1 uenv_ut2)) _ _ H) as HH.
  unfold ut2_eqT in HH; simpl in HH; discriminate.
Qed.

(* A generator is not a scalar. *)
Theorem uenv_ut2_gen_not_scalar :
  uenv_eq (uenv_ut2_g ut2_e11) (uen_scal (rig_zero (`1 Int_CRng))) → False.
Proof.
  intro H.
  pose proof (proper_morphism (rig_map (`1 uenv_ut2)) _ _ H) as HH.
  unfold ut2_eqT in HH; simpl in HH; discriminate.
Qed.

(* U(L) is not the trivial algebra. *)
Theorem uenv_ut2_one_not_zero :
  rig_one (UEnvRing Lie_UT2) ≈ rig_zero (UEnvRing Lie_UT2) → False.
Proof.
  intro H.
  pose proof (proper_morphism (rig_map (`1 uenv_ut2)) _ _ H) as HH.
  unfold ut2_eqT in HH; simpl in HH; discriminate.
Qed.

(* THE SHARP ONE: U(L) is genuinely non-commutative, so the abelian
   theorem above is not a theorem about every Lie algebra, and the
   enveloping algebra is not a polynomial algebra in disguise. *)
Theorem uenv_ut2_gens_do_not_commute :
  uenv_eq (uen_mul (uenv_ut2_g ut2_e11) (uenv_ut2_g ut2_e12))
          (uen_mul (uenv_ut2_g ut2_e12) (uenv_ut2_g ut2_e11)) → False.
Proof.
  intro H.
  pose proof (proper_morphism (rig_map (`1 uenv_ut2)) _ _ H) as HH.
  unfold ut2_eqT in HH; simpl in HH; discriminate.
Qed.

Theorem uenv_not_all_commutative :
  (∀ (K : CRng) (L : LieObject K) (s t : UEnvTerm L),
     uenv_eq (uen_mul s t) (uen_mul t s)) → False.
Proof.
  intro H.
  exact (uenv_ut2_gens_do_not_commute
           (H Int_CRng Lie_UT2 (uenv_ut2_g ut2_e11) (uenv_ut2_g ut2_e12))).
Qed.

(* And the enveloping relation is exercised at a NON-ZERO bracket: the
   commutator of the two generators is the generator of [E11,E12],
   which is E12 and not zero. *)
Example uenv_ut2_bracket_computes :
  lie_br Lie_UT2 ut2_e11 ut2_e12 = ut2_e12 := eq_refl.

Theorem uenv_ut2_bracket_relation :
  uenv_eq (uenv_ut2_g ut2_e12)
          (uen_add (uen_mul (uenv_ut2_g ut2_e11) (uenv_ut2_g ut2_e12))
                   (uen_neg (uen_mul (uenv_ut2_g ut2_e12)
                                     (uenv_ut2_g ut2_e11)))).
Proof. exact (@uq_bracket Int_CRng Lie_UT2 ut2_e11 ut2_e12). Qed.

(** * Probes

    Each negative is stated beside an APPLIED positive control.  Each
    was stripped ONE AT A TIME -- the others left as [Fail], since a
    [Fail] spans several lines and commenting out only its first line
    yields a syntax error and so a FALSE pass -- compiled alone, and its
    kind read off the WHOLE error message rather than its tail.  Each
    was confirmed to fire at ITS OWN command, by reading the reported
    line back against the source.

    FIVE NEGATIVES OF THREE KINDS, kept lexically apart: three
    CONVERSION (1-3, each reporting "cannot unify" between two terms of
    one type), one TYPING (4, a plain mismatch with NO "cannot unify"
    and no universe clause -- it reports that [h] has type [RModHom ...]
    while a [LieHom] is expected), and one RESOLUTION (5, which reports
    "Cannot infer the implicit parameter Setoid of equiv ... (no type
    class instance found)" and is the only one whose failure is an
    instance search rather than a type error), plus a scope-free
    instrument check.  NO FORMABILITY (universe) negative is delivered,
    and that is not an oversight: this file declares no universe binder
    and inspects no constraint block, so there is nothing here whose
    universes could be measured. *)

(* Negative 1 -- CONVERSION.  The unit of the adjunction and the
   insertion agree POINTWISE on the nose ([uenv_unit_is_gen] above, and
   the control below), but the two underlying module homomorphisms are
   not the same record: the unit is [⌊id⌋], which composes
   [fmap[CommutatorFunctor K] id] with the insertion, and
   [rmod_hom_compose] rebuilds the [rm_map_smul] field. *)
Fail Example uenv_probe_unit_strict (K : CRng) (L : Lie K) :
  lie_hom (uenv_unit L) = lie_hom (uenv_insert L) := eq_refl.

Example uenv_probe_unit_ctrl (K : CRng) (L : Lie K)
  (v : carrier (cmon_setoid (lie_mod L))) :
  cmon_map (rm_hom (lie_hom (uenv_unit L))) v = uen_gen v := eq_refl.

Example uenv_probe_unit_equiv_ctrl (K : CRng) (L : Lie K) :
  uenv_unit L ≈ uenv_insert L := uenv_unit_is_insert L.

(* Negative 2 -- CONVERSION.  The counit is the extension of the
   identity Lie map only up to [≈]: it is [⌈id⌉], produced by
   [ump_universal_arrows], which Theory/Universal/Arrow.v closes with
   [Qed], so nothing about it reduces. *)
Fail Example uenv_probe_counit_strict (K : CRng) (A : AAlg K) :
  uenv_counit A = uenv_extend A (@id (Lie K) (fobj[CommutatorFunctor K] A))
  := eq_refl.

Example uenv_probe_counit_ctrl (K : CRng) (A : AAlg K) :
  uenv_counit A
    ≈ uenv_extend A (@id (Lie K) (fobj[CommutatorFunctor K] A))
  := uenv_counit_is_extend A.

(* Negative 3 -- CONVERSION.  The enveloping relation is a GENERATING
   EQUATION, not a computation rule: [uenv_eq] is an inductive relation
   and the two sides are distinct constructors of [UEnvTerm], so the
   identification fails even at closed [UT2] arguments where the bracket
   itself computes ([uenv_ut2_bracket_computes] above).  The controls
   are the [≈] form and an [eq_refl] that DOES hold in the same
   vocabulary, so the failure is located at the relation and not at the
   arguments. *)
Fail Example uenv_probe_bracket_strict :
  uenv_ut2_g ut2_e12
    = uen_add (uen_mul (uenv_ut2_g ut2_e11) (uenv_ut2_g ut2_e12))
              (uen_neg (uen_mul (uenv_ut2_g ut2_e12) (uenv_ut2_g ut2_e11)))
  := eq_refl.

Example uenv_probe_bracket_ctrl :
  uenv_eq (uenv_ut2_g ut2_e12)
          (uen_add (uen_mul (uenv_ut2_g ut2_e11) (uenv_ut2_g ut2_e12))
                   (uen_neg (uen_mul (uenv_ut2_g ut2_e12)
                                     (uenv_ut2_g ut2_e11))))
  := uenv_ut2_bracket_relation.

Example uenv_probe_gen_ctrl (x : ut2) :
  rig_map (`1 uenv_ut2) (uenv_ut2_g x) = x := eq_refl.

(* Negative 4 -- TYPING.  A bare module homomorphism does not extend:
   the evaluation's respectfulness proof consumes the bracket clause at
   the [uq_bracket] case and NOWHERE else, so preservation of the
   bracket is genuine data the extension needs, not a property
   recoverable from the module map.  The control supplies the clause and
   the same extension goes through. *)
Fail Definition uenv_probe_needs_bracket
  (K : CRng) (L : LieObject K) (A : AAlgObject K)
  (h : RModHom (lie_mod L) (AAlg_RMod A)) : UEnvAlg L ~{AAlg K}~> A :=
  uenv_extend A h.

Definition uenv_probe_bracket_hom_ctrl
  (K : CRng) (L : LieObject K) (A : AAlgObject K)
  (h : RModHom (lie_mod L) (AAlg_RMod A))
  (Hb : ∀ x y, cmon_map (rm_hom h) (lie_br L x y)
                 ≈ lie_br (lie_of_aalg A) (cmon_map (rm_hom h) x)
                                          (cmon_map (rm_hom h) y))
  : UEnvAlg L ~{AAlg K}~> A :=
  uenv_extend A (@Build_LieHom K L (lie_of_aalg A) h Hb).

(* Negative 5 -- RESOLUTION.  [uenv_Setoid] is deliberately NOT
   registered as an instance -- the convention Instance/Ab/Tensor.v,
   Instance/Rng/Polynomial.v and Instance/Vect/TensorAlgebra.v all
   follow, so that the [≈] of [UEnvRing] IS [uenv_eq] definitionally and
   Theory/Algebra/Rig.v's lemmas apply to it unchanged.  The price is
   that [≈] between two BARE terms does not resolve; read through the
   ring it does, and the control is that same statement.  This is the
   one negative here whose report is an INSTANCE failure rather than a
   type error. *)
Fail Definition uenv_probe_setoid_unregistered
  (K : CRng) (L : LieObject K) (s t : UEnvTerm L) : Type := s ≈ t.

Definition uenv_probe_setoid_ctrl (K : CRng) (L : LieObject K)
  (s t : carrier (rig_setoid (UEnvRing L))) : Type := s ≈ t.

(* Instrument check: a name that exists nowhere, so the [Fail]
   mechanism itself is exercised without reference to any constant
   declared here. *)
Fail Check uenv_probe_instrument_absent.
