(** * Ab is reflective in Grp: the abelianization as a [Reflective] record

    Mac Lane, "Categories for the Working Mathematician", 2nd ed.,
    Springer GTM 5, §IV.3, printed p. 92 (PDF p. 101), read from the
    page image, catalog item maclane:IV.3:construction1: "Here are some
    examples.  Ab is reflective in Grp.  For, if G/[G, G] is the usual
    factor-commutator group of a group G, then hom(G/[G, G], A) ≅
    hom(G, A) for A abelian, and Ab is full in Grp."  The definition is
    on printed p. 91 (PDF p. 100): "A subcategory A of B is called
    reflective in B when the inclusion functor K: A → B has a left
    adjoint F: B → A", and "If a full subcategory A ⊂ B is reflective in
    B, then by Theorem 1 each object a ∈ A is isomorphic to FKa".
    Riehl, "Category Theory in Context", §4.6, Example 4.6.13 (ii),
    printed p. 170 (PDF p. 190), read from the page image, catalog item
    riehl:4.6:example13: "Abelian groups define a reflective subcategory
    Ab ↪ Group of the category of groups.  The reflector carries a group
    G to its abelianization, the quotient G/[G,G] by the commutator
    subgroup, the normal subgroup generated by elements ghg⁻¹h⁻¹.  The
    quotient maps G → G/[G,G] define the components of the unit."
    Fong and Spivak, "Seven Sketches in Compositionality", §3.4.2,
    Example 3.74 (5), printed p. 104 (PDF p. 116), read from the page
    image, catalog item 7sketches:3.4.2:example3.74: "Given a group, you
    can quotient by its commutator subgroup to get an abelian group;
    this is a left adjoint.  The right adjoint is the inclusion of
    abelian groups into groups."
    nLab: https://ncatlab.org/nlab/show/abelianization
    nLab: https://ncatlab.org/nlab/show/reflective+subcategory

    BACKGROUND.  nLab describes abelianization as "the process of
    freely making an algebraic structure 'abelian'", the group case
    being the notable one.  Mac Lane gives it as the first of his
    examples of a reflection, Riehl as the second clause of her roster,
    and Seven Sketches as a plain adjunction, with no mention of
    reflectivity.  The library already had the construction and the
    adjunction: Instance/Grp/Abelianization.v builds [AbelianizationOb],
    [Abelianization_Functor], the inclusion [Ab_to_Grp] and the
    projection [abel_proj], and Instance/Grp/Abelianize.v proves
    [abelianize_adjunction_via_transform : Abelianization_Functor ⊣
    Ab_to_Grp] and that [Ab_to_Grp] is full and faithful.  What was
    missing is the record of Construction/Reflective.v.

    WHY A NEW SUBCATEGORY.  [Reflective] is stated over the [Sub]
    inclusions of Construction/Subcategory.v, and [Ab_to_Grp] is not one
    of them: its objects are Instance/Ab.v's [AbObject] records, not
    groups carrying a predicate.  Measured, for an arbitrary
    [S : Subcategory Grp]: [Incl Grp S = Ab_to_Grp] is refused with
    "The term "Ab_to_Grp" has type "Ab ⟶ Grp" while it is expected to
    have type "Sub Grp S ⟶ Grp"", and building the record from
    Abelianize.v's adjunction is refused with "The term
    "Abelianization_Functor" has type "Grp ⟶ Ab" while it is expected to
    have type "Grp ⟶ Sub Grp S"".  Both are typing refusals.  So the
    subcategory is cut out of [Grp] by a commutativity predicate
    ([IsAbelian], [AbGrp_Sub], [AbGrp]), full with the trivially true
    [shom] of Instance/Rng.v's [CRng_Sub], and the universal arrow is
    rebuilt at it: [abel_kills_grp] is Abelianize.v's [abel_kills] with
    the target a commutative GROUP, [abel_med_grp] reads a homomorphism
    out of the quotient, [abgrp_universal] is the ∃!, and
    Theory/Universal/Arrow.v's plumbing gives [AbGrp_reflector],
    [AbGrp_adj] and the issue's pinned name
    [Ab_Reflective_in_Grp : Reflective AbGrp_Sub].

    THE ISSUE'S PATH.  The issue's verification step compiles
    Instance/Grp/Abelianization.v.  That file cannot host the record:
    the proof needs Abelianize.v's [ab_is_abelian] (and the S₃ witness
    needs its [AbTwo] and [ab_two_sign]), and Abelianize.v itself
    requires Abelianization.v.  So the record lives here, below
    Abelianize.v, and Abelianization.v is untouched.

    THE TWO PRESENTATIONS AGREE.  [Ab_to_AbGrp : Ab ⟶ AbGrp] is full,
    faithful and essentially surjective, so [Ab_AbGrp_Equivalence] is an
    equivalence of categories by [FF_ESO_Equivalence]; its object
    inverse is [Grp_to_AbOb], which reads a commutative group back as an
    [AbObject] with the group's own setoid, operations and [PropEquiv]
    field.  Seven Sketches' adjunction factors through it on both sides:
    the inclusion as [Incl ◯ Ab_to_AbGrp ≈ Ab_to_Grp]
    ([ab_to_grp_factors]), the reflector as [AbGrp_reflector ≈
    Ab_to_AbGrp ◯ Abelianization_Functor] ([abgrp_reflector_factors]).
    The adjunction reading the issue asks to keep visible is the
    constant [AbGrp_adj].

    STRENGTHS, measured strict first.  Nine [Example]s hold at
    [eq_refl]: the reflection of G is Mac Lane's G/[G, G]
    ([abgrp_reflector_obj], [abgrp_record_reflector]); the universal
    arrow IS [abel_proj G] ([abgrp_arrow_is_proj]); the unit applied to
    an element IS the projection applied to it ([abgrp_unit_pointwise]);
    the inclusion factors on objects and arrows
    ([ab_to_grp_factors_obj], [ab_to_grp_factors_fmap]) and the
    reflector on objects ([abgrp_reflector_factors_obj]); and the two
    S₃ values below.  Falling back, each refusal pinned in
    Test/ProbeReflective370.v, whose import list carries this file's:
      - the unit as a morphism is only [≈] the projection
        ([abgrp_unit_is_proj]).  It is [fmap[Incl] id ∘ abel_proj G] on
        the nose (accepted at [eq_refl]), a composite whose
        setoid-morphism component is already refused at [eq_refl]
        against [abel_proj G]'s, and so is the whole record, with
        "cannot unify";
        CORRECTION (#1347): the setoid-morphism component now holds at
        [eq_refl] (the probe's N8, now a control), since Instance/Sets.v
        gives its identity's and composite's properness fields as terms;
        the whole record is still refused (N7);
      - the reflector's arrow part is only [≈] Abelianize.v's
        ([abgrp_reflector_factors_fmap]).  It is [unique_obj] of
        Theory/Universal/Arrow.v's [Qed]-closed [ump_universal_arrows],
        and that [Qed] blocks even the pointwise readback, but it is not
        the whole cause.  Measured by flipping: through a transparent
        copy of the universal property the pointwise value reads back
        at [eq_refl], yet the setoid-morphism component and the whole
        arrow are still refused (the two sides differ in that
        component; not isolated further), while the torsion
        coreflector's arrow part (Instance/Ab/Torsion.v) reads back
        whole under the same flip;
      - the two functor factorizations hold as whole functors only up to
        [≈]: with objects and arrows agreeing on the nose, the refusal of
        [Incl ◯ Ab_to_AbGrp = Ab_to_Grp] at [eq_refl] sits in the law
        fields.  The two [≈] witnesses, [ab_to_grp_factors] and
        [abgrp_reflector_factors], are closed with [Defined]: [≈] of
        functors is a Σ of component isomorphisms (here [iso_id]) and a
        naturality proof, and the components stay transparent to a
        consumer that transports along them;
      - the counit is not read back: applied to an element it does not
        reduce ([projT1 counit a = a] is refused), being the opaque
        backward transpose.  Its invertibility is what is used:
        [abgrp_reflect_iso], G/[G, G] ≅ G at an abelian G, is
        [reflective_counit_iso] instantiated.
    Riehl 5.3.ii at this reflection: [AbGrp_IdempotentMonad] and
    [AbGrp_Incl_Monadic], through Construction/Reflective/Monadic.v.

    NON-VACUITY AT S₃ (Instance/Grp/TwoFunctors.v).  S₃ is not an object
    of the subcategory ([S3_not_IsAbelian], by computing r·s and s·r);
    the unit at S₃ merges the commutator of the two generators with the
    identity ([abgrp_unit_S3_merges], Abelianize.v's
    [abelianize_S3_identifies]) and is therefore not invertible
    ([abgrp_unit_S3_not_iso], through Abelianization.v's
    [commutator_S3_nontrivial]); and the reflection is not the trivial
    group: in G/[G, G] at S₃, on the reflection's own setoid, the class
    of the reflection s is apart from the class of the identity
    ([S3_reflection_nontrivial]).  The proof exercises the NEW universal
    property on the sign character: its mediator sends s to 1 and the
    identity to 0 ([abgrp_S3_med_s], [abgrp_S3_med_unit] at [eq_refl]),
    and 1 ≉ 0 in ℤ/2 ([abgrp_S3_separates], a statement about the
    mediator's values in ℤ/2, which the mediator carries back to the
    quotient because it respects the quotient's equality).

    UNIVERSES, read by [About] under [Set Printing Universes] on all
    forty-two named constants.  Each binder names the levels its
    statement fixes, then [+]: [u p], the object and hom levels of
    [Grp@{u p}], or of [Ab@{u p}] for [Ab_to_AbGrp], its faithful, full
    and essentially surjective witnesses, [Ab_AbGrp_Equivalence] and
    the two [ab_to_grp] readbacks; [a c p], the three levels of
    [GrpObject@{a c p}], for [IsAbelian] and [Grp_to_AbOb]; [u] alone
    for the six S₃ statements over [Grp@{u Set}]; and [a] for
    [S3_not_IsAbelian].  No block carries an equation.
    Thirty-nine blocks carry [Set < u] on that object level and on no
    other universe; it is [Grp]'s and [Ab]'s own bound ([About Grp]
    reads [Set < u]): the [PropEquiv] field puts [Set+1] in the record
    sort of [GrpObject] ([About GrpObject]: [Type@{max(Set+1, …)}]).
    The three without it are [IsAbelian], [Grp_to_AbOb] and
    [S3_not_IsAbelian].  Twenty-six blocks also read
    [Set < Projections.u0]; in each it follows from [Set < u] and a
    chain of the block's own caps up to the standard library's
    monomorphic [Projections.u0], and every global universe in every
    block is such an upper bound.  The six S₃ statements sit at
    [Grp@{u Set}], because [S3@{a} : GrpObject@{a Set Set}] (its
    carrier is built on [bool]) and an object of [Grp@{u p}] is a
    [GrpObject@{p p p}]; [S3_not_IsAbelian], which is not about [Grp],
    is general in [a] with an empty block.  Against a copy with every
    binder removed, compared under [Set Printing All], no constant lost
    a universe or gained an identification; [S3_not_IsAbelian] was
    [IsAbelian@{Set Set Set} S3@{Set}] there and is general here.

    AXIOMS.  All sixty-one constants of this module, the forty-two above
    and nineteen [Program] obligations, are closed under the global context
    ([Print Module] lists them; [Print Assumptions] on each).

    NOT DELIVERED.
      - No [Reflective] record over Instance/Ab.v's [Ab] itself, for the
        typing reason above; the equivalence is the bridge.
      - No identification of [AbGrp_adj] with Abelianize.v's two
        adjunctions as adjunctions: only the functor factorizations.
      - The counit is not computed; only its invertibility is used.
      - The other examples on Mac Lane's page are not here: the
        torsion coreflection is Instance/Ab/Torsion.v, and completion
        and the Stone–Čech compactification are not in this file. *)

Require Import Category.Lib.
Require Import Category.Lib.Setoid.Propositional.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Natural.Transformation.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Universal.Arrow.
Require Import Category.Theory.Monad.
Require Import Category.Theory.Equivalence.
Require Import Category.Theory.Equivalence.FullFaithful.
Require Import Category.Monad.Comparison.
Require Import Category.Construction.Subcategory.
Require Import Category.Construction.Reflective.
Require Import Category.Construction.Reflective.Idempotent.
Require Import Category.Construction.Reflective.Monadic.
Require Import Category.Instance.Sets.
Require Import Category.Instance.CMon.
Require Import Category.Instance.Ab.
Require Import Category.Instance.Grp.
Require Import Category.Instance.Grp.Epi.
Require Import Category.Instance.Grp.Center.
Require Import Category.Instance.Grp.TwoFunctors.
Require Import Category.Instance.Grp.Abelianization.
Require Import Category.Instance.Grp.Abelianize.

Generalizable All Variables.

#[local] Obligation Tactic := idtac.

(** ** The full subcategory of abelian groups *)

Definition IsAbelian@{a c p +} (G : GrpObject@{a c p}) : Type@{a} :=
  ∀ a b : carrier G, grp_mul G a b ≈ grp_mul G b a.

Definition AbGrp_Sub@{u p +} : Subcategory Grp@{u p} :=
  @Build_Subcategory Grp@{u p} IsAbelian
    (fun _ _ _ _ _ => True)
    (fun _ _ _ _ _ _ _ _ _ _ => I)
    (fun _ _ => I).

Definition AbGrp@{u p +} : Category := Sub Grp@{u p} AbGrp_Sub.

Definition AbGrp_Full@{u p +} :
  Category.Construction.Subcategory.Full Grp@{u p} AbGrp_Sub :=
  fun _ _ _ _ _ => I.

(** ** Descent into an abelian group *)

(* Abelianize.v's [abel_kills] with the target a commutative GROUP rather
   than an [AbObject]: the same argument, the commutativity now a
   hypothesis.  The truncation [abel_eq] is opened under [pequiv_to] of
   the target's own [grp_prop]. *)
Lemma abel_kills_grp@{u p +} {G H : GrpObject@{p p p}} (HH : IsAbelian H)
  (f : G ~{Grp@{u p}}~> H) (a b : carrier G) :
  abel_eq G a b → grp_map f a ≈ grp_map f b.
Proof.
  intro Hab.
  apply (@pequiv_to _ _ (grp_prop H)).
  destruct Hab as [Hab].
  apply pequiv_from.
  pose proof (hom_to_abelian_kills HH f _ Hab) as E.
  rewrite (grp_map_mul f), (grp_map_inv f) in E.
  apply (grp_cancel_r _ (grp_inv H (grp_map f b))).
  rewrite E.
  symmetry; apply grp_mul_inv_r.
Qed.

(* G/[G,G], as an object of the subcategory. *)
Definition AbelianizationGrp@{u p +} (G : Grp@{u p}) : AbGrp :=
  (Ab_to_GrpOb (AbelianizationOb G); ab_is_abelian (AbelianizationOb G)).

(* The mediator: the SAME underlying map as [f], read out of the
   quotient. *)
Program Definition abel_med_grp@{u p +} {G H : Grp@{u p}} (HH : IsAbelian H)
  (f : G ~{Grp@{u p}}~> H) :
  Ab_to_GrpOb (AbelianizationOb G) ~{Grp@{u p}}~> H := {|
  grp_map := {| morphism := fun a : carrier G => grp_map f a |}
|}.
Next Obligation.
  intros G H HH f a b Hab; exact (abel_kills_grp HH f a b Hab).
Qed.
Next Obligation. intros G H HH f; exact (grp_map_unit f). Qed.
Next Obligation. intros G H HH f a b; exact (grp_map_mul f a b). Qed.

(** ** Mac Lane's universal arrow: the quotient projection *)

Theorem abgrp_universal@{u p +} (G : Grp@{u p}) :
  ∀ (d : AbGrp) (f : G ~{Grp@{u p}}~> Incl Grp@{u p} AbGrp_Sub d),
    ∃! g : AbelianizationGrp G ~{AbGrp}~> d,
      f ≈ fmap[Incl Grp@{u p} AbGrp_Sub] g ∘ abel_proj G.
Proof.
  intros d f.
  unshelve eexists.
  - exact (abel_med_grp `2 d f; I).
  - intro a; simpl; reflexivity.
  - intros g Hg a; simpl.
    exact (Hg a).
Defined.

Definition abgrp_universal_arrow@{u p +} (G : Grp@{u p})
  : @UniversalArrow Grp@{u p} AbGrp G (Incl Grp@{u p} AbGrp_Sub) :=
  @universal_arrow_from_UMP Grp@{u p} AbGrp G (Incl Grp@{u p} AbGrp_Sub)
    (AbelianizationGrp G) (abel_proj G) (abgrp_universal G).

Definition AbGrp_reflector@{u p +} : Grp@{u p} ⟶ AbGrp :=
  LeftAdjointFunctorFromUniversalArrows (Incl Grp@{u p} AbGrp_Sub)
    abgrp_universal_arrow.

(* The adjunction reading Seven Sketches Example 3.74 asks to see. *)
Definition AbGrp_adj@{u p +} : AbGrp_reflector ⊣ Incl Grp@{u p} AbGrp_Sub :=
  AdjunctionFromUniversalArrows (Incl Grp@{u p} AbGrp_Sub)
    abgrp_universal_arrow.

(* The issue's pinned name. *)
Definition Ab_Reflective_in_Grp@{u p +} : @Reflective Grp@{u p} AbGrp_Sub :=
  @Build_Reflective Grp@{u p} AbGrp_Sub AbGrp_Full AbGrp_reflector AbGrp_adj.

(** ** Readbacks: the unit is the map Mac Lane names *)

Example abgrp_reflector_obj@{u p +} (G : Grp@{u p}) :
  `1 (fobj[AbGrp_reflector] G) = Ab_to_GrpOb (AbelianizationOb G)
  := eq_refl.

Example abgrp_arrow_is_proj@{u p +} (G : Grp@{u p}) :
  @arrow Grp@{u p} AbGrp G (Incl Grp@{u p} AbGrp_Sub)
    (abgrp_universal_arrow G)
    = abel_proj G := eq_refl.

Example abgrp_record_reflector@{u p +} (G : Grp@{u p}) :
  fobj[reflector Ab_Reflective_in_Grp] G = AbelianizationGrp G := eq_refl.

Definition abgrp_unit@{u p +} (G : Grp@{u p})
  : G ~{Grp@{u p}}~> Incl Grp@{u p} AbGrp_Sub (fobj[AbGrp_reflector] G) :=
  @Category.Theory.Adjunction.unit _ _ _ _ AbGrp_adj G.

Example abgrp_unit_pointwise@{u p +} (G : Grp@{u p}) (a : carrier G) :
  grp_map (abgrp_unit G) a = grp_map (abel_proj G) a := eq_refl.

Lemma abgrp_unit_is_proj@{u p +} (G : Grp@{u p}) :
  abgrp_unit G ≈ abel_proj G.
Proof. intro a; reflexivity. Defined.

(* Mac Lane p. 91: for a full reflective subcategory each object is
   isomorphic to its reflection.  At an abelian G, G/[G,G] ≅ G. *)
Definition abgrp_reflect_iso@{u p +} (G : Sub Grp@{u p} AbGrp_Sub) :
  fobj[AbGrp_reflector] (fobj[Incl Grp@{u p} AbGrp_Sub] G) ≅[AbGrp] G :=
  reflective_counit_iso Ab_Reflective_in_Grp G.

(** ** The adjunction of Abelianize.v, factored through the subcategory *)

(* An abelian group in [Grp]'s sense, read back as an [AbObject].  The
   setoid, unit, operation, inverse and [PropEquiv] field are the group's
   own; the law fields are the group's laws plus the hypothesis. *)
Program Definition Grp_to_AbOb@{a c p +} (G : GrpObject@{a c p})
  (HG : IsAbelian G) : AbObject@{a c p} := {|
  ab_cmon := {| cmon_setoid := grp_setoid G
              ; cmon_zero   := grp_unit G
              ; cmon_plus   := grp_mul G
              ; cmon_prop   := grp_prop G |}
 ; ab_neg := grp_inv G
|}.
Solve All Obligations with
  (intros G HG;
   first [ exact (grp_mul_respects G)
         | exact (grp_mul_assoc G)
         | exact HG
         | exact (grp_mul_unit_l G)
         | exact (grp_inv_Proper G)
         | exact (grp_mul_inv_l G) ]).

(* [Ab] (Instance/Ab.v) into the subcategory. *)
Program Definition Ab_to_AbGrp@{u p +} : Ab@{u p} ⟶ AbGrp := {|
  fobj := fun A => (Ab_to_GrpOb A; ab_is_abelian A);
  fmap := fun A B f => (fmap[Ab_to_Grp] f; I)
|}.
Next Obligation. intros A B f g Hfg a; exact (Hfg a). Qed.
Next Obligation. intros A a; simpl; reflexivity. Qed.
Next Obligation. intros A B C f g a; simpl; reflexivity. Qed.

Definition Ab_to_AbGrp_Faithful@{u p +} :
  @Faithful Ab@{u p} AbGrp Ab_to_AbGrp.
Proof. constructor; intros A B f g H; exact H. Defined.

Program Definition Ab_to_AbGrp_Full@{u p +} :
  @Functor.Full Ab@{u p} AbGrp Ab_to_AbGrp := {|
  prefmap := fun A B (h : Ab_to_AbGrp A ~{AbGrp}~> Ab_to_AbGrp B) =>
    {| cmon_map      := grp_map `1 h
     ; cmon_map_zero := grp_map_unit `1 h
     ; cmon_map_plus := grp_map_mul `1 h |}
|}.
Next Obligation. intros A B h a; simpl; reflexivity. Qed.

(* Every object of the subcategory is, up to the identity function, the
   image of the [AbObject] read off it. *)
Program Definition AbGrp_iso@{u p +} (d : Sub Grp@{u p} AbGrp_Sub) :
  Ab_to_AbGrp (Grp_to_AbOb `1 d `2 d) ≅[AbGrp] d := {|
  to   := ({| grp_map := {| morphism := fun a : carrier `1 d => a |} |}; I);
  from := ({| grp_map := {| morphism := fun a : carrier `1 d => a |} |}; I)
|}.
Next Obligation. intros d a b H; exact H. Qed.
Next Obligation. intros d; simpl; reflexivity. Qed.
Next Obligation. intros d a b; simpl; reflexivity. Qed.
Next Obligation. intros d a b H; exact H. Qed.
Next Obligation. intros d; simpl; reflexivity. Qed.
Next Obligation. intros d a b; simpl; reflexivity. Qed.
Next Obligation. intros d a; simpl; reflexivity. Qed.
Next Obligation. intros d a; simpl; reflexivity. Qed.

Definition Ab_to_AbGrp_ESO@{u p +} :
  @EssentiallySurjective Ab@{u p} AbGrp Ab_to_AbGrp :=
  @Build_EssentiallySurjective Ab@{u p} AbGrp Ab_to_AbGrp
    (fun d : AbGrp => Grp_to_AbOb `1 d `2 d) AbGrp_iso.

Definition Ab_AbGrp_Equivalence@{u p +} :
  @EquivalenceOfCategories Ab@{u p} AbGrp Ab_to_AbGrp :=
  @FF_ESO_Equivalence Ab@{u p} _ Ab_to_AbGrp
    Ab_to_AbGrp_Full Ab_to_AbGrp_Faithful
    Ab_to_AbGrp_ESO.

(* Abelianize.v's inclusion [Ab_to_Grp] factors as [Ab_to_AbGrp]
   followed by the inclusion of the subcategory. *)
Example ab_to_grp_factors_obj@{u p +} (A : Ab@{u p}) :
  Incl Grp AbGrp_Sub (Ab_to_AbGrp A) = Ab_to_Grp A := eq_refl.

Example ab_to_grp_factors_fmap@{u p +} (A B : Ab@{u p})
  (f : A ~{Ab@{u p}}~> B) :
  fmap[Incl Grp AbGrp_Sub] (fmap[Ab_to_AbGrp] f) = fmap[Ab_to_Grp] f
  := eq_refl.

(* As functors the two agree up to [≈], with identity components. *)
Lemma ab_to_grp_factors@{u p +} :
  Incl Grp@{u p} AbGrp_Sub ◯ Ab_to_AbGrp ≈ Ab_to_Grp.
Proof.
  exists (fun A => @iso_id Grp@{u p} (Ab_to_GrpOb A)).
  intros A B f a; simpl; reflexivity.
Defined.

(* And the reflector factors as Abelianize.v's left adjoint followed by
   [Ab_to_AbGrp]: on objects on the nose, on arrows up to [≈] by the
   uniqueness clause of the universal property. *)
Example abgrp_reflector_factors_obj@{u p +} (G : Grp@{u p}) :
  fobj[AbGrp_reflector] G = fobj[Ab_to_AbGrp] (fobj[Abelianization_Functor] G)
  := eq_refl.

Lemma abgrp_reflector_factors_fmap@{u p +} (G H : Grp@{u p})
  (f : G ~{Grp@{u p}}~> H) :
  fmap[AbGrp_reflector] f
    ≈ fmap[Ab_to_AbGrp] (fmap[Abelianization_Functor] f).
Proof.
  apply (uniqueness (ump_universal_arrows (abgrp_universal_arrow G) _)).
  intro a; simpl; apply abel_eq_refl.
Qed.

Lemma abgrp_reflector_factors@{u p +} :
  @equiv _ (@Functor_Setoid Grp@{u p} AbGrp) AbGrp_reflector
    (Ab_to_AbGrp ◯ Abelianization_Functor).
Proof.
  exists (fun G => @iso_id AbGrp (AbelianizationGrp G)).
  intros G H f a; simpl.
  exact (abgrp_reflector_factors_fmap G H f a).
Defined.

(** ** Riehl 5.3.ii at this reflection *)

Definition AbGrp_IdempotentMonad@{u p +} :
  @IdempotentMonad Grp@{u p} (Incl Grp@{u p} AbGrp_Sub ◯ AbGrp_reflector)
    (Reflective_Monad Ab_Reflective_in_Grp) :=
  Reflective_IdempotentMonad Ab_Reflective_in_Grp.

Definition AbGrp_Incl_Monadic@{u p +} : Monadic (Incl Grp@{u p} AbGrp_Sub) :=
  Reflective_Monadic Ab_Reflective_in_Grp.

(** ** Non-vacuity at S₃ *)

(* S₃ is not an object of the subcategory. *)
Lemma S3_not_IsAbelian@{a +} : IsAbelian (S3 : GrpObject@{a a a}) → False.
Proof.
  intro HS3.
  pose proof (HS3 S3_r S3_s) as E.
  vm_compute in E; discriminate E.
Qed.

(* The unit at S₃ merges the commutator of the two generators with the
   identity... *)
Lemma abgrp_unit_S3_merges@{u +} :
  grp_map (abgrp_unit (S3 : Grp@{u Set})) (gcomm S3 S3_r S3_s)
    ≈ grp_map (abgrp_unit (S3 : Grp@{u Set})) s3_unit.
Proof. exact abelianize_S3_identifies. Qed.

(* ...which were apart in S₃, so the unit at S₃ is not invertible. *)
Theorem abgrp_unit_S3_not_iso@{u +} :
  IsIsomorphism (abgrp_unit (S3 : Grp@{u Set})) → False.
Proof.
  intros [g _ Hgf].
  apply (snd commutator_S3_nontrivial).
  refine (transitivity (symmetry (Hgf (gcomm S3 S3_r S3_s))) _).
  refine (transitivity _ (Hgf s3_unit)).
  exact (proper_morphism (grp_map g) _ _ abgrp_unit_S3_merges).
Qed.

(* The reflection of S₃ is not the trivial group: exercising the
   universal property of the NEW universal arrow on the sign character,
   the mediator separates the reflection from the identity. *)
Definition AbTwo_in_AbGrp@{u p +} : Sub Grp@{u p} AbGrp_Sub :=
  (Ab_to_GrpOb AbTwo; ab_is_abelian AbTwo).

Example abgrp_S3_med_s@{u +} :
  grp_map
    `1 (unique_obj
          (abgrp_universal (S3 : Grp@{u Set}) AbTwo_in_AbGrp ab_two_sign))
    S3_s = grp_two_one := eq_refl.

Example abgrp_S3_med_unit@{u +} :
  grp_map
    `1 (unique_obj
          (abgrp_universal (S3 : Grp@{u Set}) AbTwo_in_AbGrp ab_two_sign))
    s3_unit = grp_two_zero := eq_refl.

Theorem abgrp_S3_separates@{u +} :
  grp_map
    `1 (unique_obj
          (abgrp_universal (S3 : Grp@{u Set}) AbTwo_in_AbGrp ab_two_sign))
    S3_s
    ≈ grp_map
        `1 (unique_obj
              (abgrp_universal (S3 : Grp@{u Set}) AbTwo_in_AbGrp ab_two_sign))
        s3_unit → False.
Proof. intro H; vm_compute in H; exact H. Qed.

(* The same fact on the reflection's own setoid: the class of s and the
   class of the identity stay apart in G/[G, G] at S₃, because the
   mediator above respects that setoid's equality. *)
Lemma S3_reflection_nontrivial@{u +} :
  @equiv (carrier `1 (fobj[AbGrp_reflector] (S3 : Grp@{u Set}))) _
    S3_s s3_unit → False.
Proof.
  intro H.
  apply abgrp_S3_separates.
  exact (proper_morphism
    (grp_map `1 (unique_obj
       (abgrp_universal (S3 : Grp@{u Set}) AbTwo_in_AbGrp ab_two_sign))) _ _ H).
Qed.
