Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Functor.
Require Import Category.Functor.Bifunctor.
Require Import Category.Functor.Opposite.
Require Import Category.Construction.Product.
Require Import Category.Construction.Opposite.
Require Import Category.Structure.End.
Require Import Category.Structure.Coend.
Require Import Category.Instance.Sets.

Generalizable All Variables.

(** * Coends in [Sets] *)

(* nLab:      https://ncatlab.org/nlab/show/coend
   Wikipedia: https://en.wikipedia.org/wiki/Coend

   For a functor of mixed variance [F : C^op ∏ C ⟶ Sets] the coend
   [∫^x F(x,x)] is realised here as a concrete setoid, with no recourse to
   function-extensionality.  It is the dual of the direct end construction in
   Instance/Sets/End: where the end is a subsetoid of compatible families, the
   coend is a quotient of the disjoint sum.

   The carrier is the sum [coend_sum] with one summand per object: an element
   is [ci x a] for some [x : C] and [a : F (x, x)].  On it we impose the finest
   congruence [coend_eq] generated by

     - [ce_point]: the fibre equivalence, [a ≈ b] in [F(x,x)] identifies
       [ci x a] with [ci x b]; and

     - [ce_glue]: the coend (co-dinaturality) glue, for [f : x ~> y] and
       [a : F (y, x)], identifying the contravariant image at [x] with the
       covariant image at [y],

         ci x (bimap[F] (op f) id a)  ~  ci y (bimap[F] id f a).

   The pair [(op f, id)] is the contravariant action [F(f,1)] carrying
   [F(y,x)] to [F(x,x)], and [(id, f)] the covariant action [F(1,f)] carrying
   [F(y,x)] to [F(y,y)]; this matches the [Cowedge_cond] of Structure/Coend
   exactly.  Reflexivity, symmetry and transitivity are supplied as the
   remaining constructors ([ce_sym], [ce_trans]) with reflexivity derived as a
   lemma; there is no [ce_refl] constructor, keeping the induction on
   [coend_eq] to four cases.

   Because the apex is a setoid, this equivalence is carried by the object
   itself rather than by a Coq quotient type, so the construction is
   [funext]-free.  The injection legs are [ci x] packaged as setoid maps
   [F(x,x) ~> coend_apex]; their cowedge condition is precisely [ce_glue].
   The coend UMP sends a competing cowedge [(Q, i')] to the mediator
   [ci x a ↦ i' x a], whose respect for [coend_eq] is proved by induction on
   the relation — the [ce_glue] case being exactly [i']'s own cowedge law read
   pointwise.  Commuting holds by reflexivity and uniqueness is the pointwise
   reading of the leg equations.  This yields [SetsCoend F : Coend F] for every
   [F : C^op ∏ C ⟶ Sets].

   As with every Sets-valued (co)limit in this development the indexing
   category's object level is constrained to sit below Sets' carrier level, so
   that the sum [coend_sum] over [obj[C]] fits as a setoid carrier; this
   smallness constraint is inferred by universe polymorphism and recorded on
   [SetsCoend]. *)

Section SetsCoend.

Context {C : Category}.
Context (F : C^op ∏ C ⟶ Sets).

(** Elements: one summand per object [x], namely [F (x, x)]. *)
Inductive coend_sum : Type :=
  | ci : forall x : C, F (x, x) -> coend_sum.

(** The finest congruence identifying the fibre equivalence ([ce_point]) and
    the coend glue ([ce_glue]); [ce_sym] and [ce_trans] close it into an
    equivalence, with reflexivity derived below. *)
Inductive coend_eq : coend_sum -> coend_sum -> Type :=
  | ce_point : forall (x : C) (a b : F (x, x)),
      a ≈ b -> coend_eq (ci x a) (ci x b)
  | ce_glue  : forall (x y : C) (f : x ~{C}~> y) (a : F (y, x)),
      coend_eq (ci x (bimap[F] (op f) id a)) (ci y (bimap[F] id f a))
  | ce_sym   : forall s t : coend_sum, coend_eq s t -> coend_eq t s
  | ce_trans : forall s t u : coend_sum,
      coend_eq s t -> coend_eq t u -> coend_eq s u.

(** Reflexivity comes from [ce_point] applied to the fibre setoid's own
    reflexivity. *)
Lemma coend_eq_refl (s : coend_sum) : coend_eq s s.
Proof.
  destruct s as [x a].
  apply ce_point; reflexivity.
Qed.

(** The coend apex as a [SetoidObject]. *)
Program Definition coend_apex_setoid : SetoidObject :=
  {| carrier := coend_sum;
     is_setoid := {| equiv := coend_eq; setoid_equiv := _ |} |}.
Next Obligation.
  constructor.
  - intros s. apply coend_eq_refl.
  - intros s t H. apply ce_sym; exact H.
  - intros s t u H1 H2. eapply ce_trans; [ exact H1 | exact H2 ].
Qed.

(** The injection leg at [x]: send [a : F (x, x)] to [ci x a].  It respects
    the fibre equivalence by [ce_point]. *)
Program Definition coend_inj_mor (x : C) :
  SetoidMorphism (F (x, x)) coend_apex_setoid :=
  {| morphism := fun a => ci x a |}.
Next Obligation.
  unfold Proper, respectful; intros a b Hab.
  apply ce_point; exact Hab.
Qed.

(** The universal cowedge condition of the injections is exactly [ce_glue],
    read pointwise. *)
Lemma coend_apex_cowedge :
  Cowedge_cond F coend_apex_setoid coend_inj_mor.
Proof.
  intros x y f a.
  exact (ce_glue x y f a).
Qed.

(** The underlying function of the mediator into a competing cowedge [(Q, i')]:
    send [ci x a] to [i' x a]. *)
Definition coend_med_fun {Q : SetoidObject}
  (i' : forall x : C, SetoidMorphism (F (x, x)) Q) (s : coend_sum) : Q :=
  match s with ci x a => i' x a end.

(** Respectfulness of [coend_med_fun] for [coend_eq], by induction on the
    equivalence-closure derivation.  The [ce_glue] case is precisely [i']'s own
    cowedge law [cond'] read at the point [a]. *)
Lemma coend_med_respects {Q : SetoidObject}
  (i' : forall x : C, SetoidMorphism (F (x, x)) Q)
  (cond' : Cowedge_cond F Q i')
  (s t : coend_sum) (H : coend_eq s t) :
  coend_med_fun i' s ≈ coend_med_fun i' t.
Proof.
  induction H as
    [ x a b Hab
    | x y f a
    | s1 s2 Hs IH
    | s1 s2 s3 Hs1 IH1 Hs2 IH2 ].
  - simpl. apply proper_morphism; exact Hab.
  - exact (cond' x y f a).
  - symmetry; exact IH.
  - transitivity (coend_med_fun i' s2); [ exact IH1 | exact IH2 ].
Qed.

(** The mediator as a setoid map [coend_apex ~> Q]. *)
Program Definition coend_mediator {Q : SetoidObject}
  (i' : forall x : C, SetoidMorphism (F (x, x)) Q)
  (cond' : Cowedge_cond F Q i') :
  SetoidMorphism coend_apex_setoid Q :=
  {| morphism := coend_med_fun i' |}.
Next Obligation.
  unfold Proper, respectful; intros s t Hst.
  exact (coend_med_respects i' cond' s t Hst).
Qed.

(** The coend and its universal property.  For every cowedge [(Q, i')] the
    mediator above is the unique setoid map out of the coend recovering each
    leg [i' x]; commuting holds by reflexivity and uniqueness is the pointwise
    reading of the leg equations. *)
Definition SetsCoend : Coend F.
Proof.
  unshelve refine
    (@Build_Coend C Sets F coend_apex_setoid coend_inj_mor coend_apex_cowedge _).
  intros Q i' cond'.
  unshelve refine
    (Build_Unique _ _ _ (coend_mediator i' cond') _ _).
  - intros x a. reflexivity.
  - intros v Hv s.
    destruct s as [x a].
    symmetry.
    exact (Hv x a).
Defined.

End SetsCoend.

Arguments coend_sum {C} F.
Arguments coend_eq {C} F _ _.
Arguments coend_apex_setoid {C} F.
Arguments coend_inj_mor {C} F x.
Arguments coend_med_fun {C} F {Q} i' s.
Arguments coend_mediator {C} F {Q} i' cond'.
Arguments SetsCoend {C} F.
