Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Isomorphism.
Require Import Category.Structure.Coequalizer.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Sets.Quotient.

Generalizable All Variables.

#[local] Obligation Tactic := idtac.

(** * Coequalizers in [Sets] *)

(* nLab:      https://ncatlab.org/nlab/show/coequalizer
   Wikipedia: https://en.wikipedia.org/wiki/Coequaliser

   Mac Lane, "Categories for the Working Mathematician" 2nd ed., §III.3
   remark 2 (p. 65) and exercise 5 (p. 68); Awodey, "Category Theory"
   (1st ed., CMU pre-print 2005), §3.4 example 3.19 and the unnumbered
   construction on p. 72, and §3.5 exercise 4 (p. 76); Fong and Spivak,
   "Seven Sketches in Compositionality", §6.2.4 example 6.42 (p. 194).

   Those six citations make TWO statements between them, and this file
   proves both.  Four of them -- Mac Lane's remark 2, Awodey's p. 72
   construction and §3.5 exercise 4, and Seven Sketches' example 6.42 --
   say that the coequalizer in Set of a parallel pair f, g : A ⇉ B is B
   modulo the equivalence relation GENERATED by the equations f a = g a.
   The other two -- Mac Lane's exercise 5 and Awodey's example 3.19 --
   say that the quotient X/E is itself the coequalizer of the two
   projections of E, viewed as a subset of X × X.

   Awodey's exercise 4 phrases the generated relation impredicatively --
   "the intersection of all equivalence relations on B containing the
   pairs (f x, g x)" -- and that phrasing does not fit at the universe
   [Sets] lives in: intersecting over ALL [crelation]s on B quantifies
   over [carrier B → carrier B → Type@{o}], which sits one level above
   the carrier, so the resulting relation is not one the setoid can
   carry.  Test/ProbeSetsQuotient.v pins that, beside the same wall
   Instance/Sets/Quotient/Partition.v meets for the set of classes.  The
   inductive generation used here is the substitute, and it is the idiom
   already in tree at Instance/Sets/Pushout.v and Instance/Sets/Coend.v.
   It has the property the intersection description is used for, namely
   LEASTNESS, and leastness is exactly what [coeq_rel_respects] below
   proves.

   Two constructions, one object.  [Instance/Sets/Quotient.v] supplies the
   quotient of a setoid by an equivalence relation together with its
   universal property; all this file adds is the RELATION -- four
   constructors -- plus the observation that a map out of B coforks the
   pair exactly when it respects that relation.  The coequalizer's
   universal property is then the quotient's, transported across that
   observation, and the identification of X/E with the coequalizer of the
   projections is the same theorem read the other way round. *)

(* Why there is no route through completeness, and what was in tree

   The equalizer story in [Sets] runs through a general theorem:
   [Complete_HasEqualizers] (Adjunction/GAFT.v:193) turns any [Complete]
   category into one with equalizers, and Adjunction/GAFT/Sets.v:175
   applies it to [Sets_Complete] to get [Sets_HasEqualizers].  The dual
   route is not available: [Cocomplete Sets] is NOT in tree, and
   Instance/Sets/Complete.v:106 says so and says why -- colimits of
   setoids need exactly the quotient this file's donor supplies.  So the
   coequalizer has to be built by hand, and the hand-built object is what
   a later [Cocomplete Sets] would itself need.

   Before this file the tree had no [HasCoequalizers] inhabitant at all.
   The name occurred as the class ([Structure/Coequalizer.v:68]), as the
   DERIVED [HasCoequalizers_HasReflexiveCoequalizers]
   ([Structure/Coequalizer/Reflexive.v:75], which consumes the class
   rather than inhabiting it), and otherwise only in prose
   ([Structure/Coequalizer.v:47], [Structure/Coequalizer/Reflexive.v:26]
   and [:51], [Structure/Equalizer/Fork.v:67],
   [Instance/Grp/Quotient/Colimit.v:69]).  [Sets_HasCoequalizers] is
   therefore the first.

   ERRATUM, and it concerns a sentence in this issue's own Seven Sketches
   §6.2.4 block.  That block asserts that "rg -i 'coequalizer' Instance/
   returns exactly two hits, both prose comments at
   Instance/Parallel.v:25 and Instance/Two.v:51".  The COUNT was true
   when the block was written and is no longer, and the second LINE
   NUMBER is off by four.  Re-measured against this worktree's parent
   commit, over `*.v` files only: twenty-two hits in three files --
   Parallel.v:25, Two.v:55, and twenty in Instance/Grp/Quotient/Colimit.v,
   which has landed since.  Among the twenty are two genuine
   [IsCoequalizer] INHABITANTS, [quot_IsCoequalizer] (:138) and
   [normal_closure_IsCoequalizer] (:264), so the block's implied "no
   coequalizer has ever been inhabited under Instance/" is also gone.
   What the block was getting at survives the correction, and is the
   sentence above about [HasCoequalizers]: those two inhabitants are
   coequalizers of a morphism against a ZERO morphism in [Grp], not a
   construction for an arbitrary parallel pair, and Colimit.v:69 says as
   much itself. *)

(* WHAT IS DELIVERED

   * [coeq_rel f g], the equivalence relation generated by the equations
     f a ~ g a, as a four-constructor inductive on [carrier B] --
     [cq_base] (the setoid's own `≈`), [cq_glue], [cq_sym], [cq_trans].
     Reflexivity is DERIVED rather than a constructor
     ([coeq_rel_refl]), which is Instance/Sets/Coend.v's convention and
     keeps every induction below to four cases.

   * [coeq_rel_respects], the leastness property in the form the universal
     property needs: a map out of B respects [coeq_rel f g] if and only if
     it coforks the pair.  The interesting direction is the induction; the
     other is one constructor.

   * [sets_coeq_IsCoequalizer] and [Sets_HasCoequalizers], the FIRST
     inhabitant of [Structure/Coequalizer.v]'s class anywhere in the tree.
     The chosen coequalizer is DATA -- the library's `∃` is [sigT] -- so
     no choice principle is consumed.

   * DELIVERABLE: X/E is the coequalizer of the two projections of E.  The
     relation is presented as an object of [Sets] by
     [SetsRelObj X R], the setoid of TRIPLES ⟨x, y, w⟩ with w : R x y,
     compared by `≈` in the two components; [sets_rel_fst] and
     [sets_rel_snd] are the projections.  Read what that choice does and
     does not say: the witness w is carried as DATA and is IGNORED by the
     setoid, so [SetsRelObj] is the image of E in X × X and not a set of
     derivations -- but it is not a SUBOBJECT of X × X either, since
     nothing here proves the evident map to X × X monic.  The
     identification is [sets_rel_IsCoequalizer], and it is an identity, not
     an isomorphism: the coequalizer object IS [SetsQuotient X R HR], with
     [sets_quot_proj] as the coequalizing map.

   * The comparison of the two, [sets_rel_coeq_rel_iff]: generating an
     equivalence relation from the projections of an equivalence relation
     gives that relation back.  Hence the generated-closure coequalizer
     and the direct one agree, and [sets_rel_coeq_iso] exhibits the
     isomorphism with the IDENTITY on carriers in both directions.

   * Non-vacuity in both directions, and both by proof.  [bool_flip_coeq]
     collapses the two-element setoid ([bool_flip_merges]); the
     coequalizer of a map WITH ITSELF merges nothing
     ([coeq_rel_diagonal], proved by induction, with
     [bool_id_coeq_separates] the concrete consequence).  The degenerate
     reading "every coequalizer collapses its codomain" is therefore
     refuted, and so is "no coequalizer collapses anything".

   WHAT IS NOT DELIVERED

   * NO [Cocomplete Sets], and no claim that this file is a step towards
     one beyond supplying one shape.

   * NO [HasCoequalizers FinSet].  The evaluated witness of
     Instance/Sets/Coequalizer/Interconnect.v is over [Sets], for the
     reason given there; nothing here says anything about FinSet.

   * NO REGULAR-EPI STATEMENT.  [coequalizer_epic] (Structure/Coequalizer.v)
     gives that the projection is epic, and [Structure/Regular.v]'s
     [RegularEpi] is not instantiated here.

   * NO NORMAL FORM for [coeq_rel], hence no decision procedure: negative
     results about it are obtained by mapping OUT through the mediator
     into a setoid where the question is decidable, never by induction on
     the relation -- an induction on a generated congruence cannot yield a
     negative.

   STATUS: axiom-free.  42 named constants (the four [coeq_rel]
   constructors and the [Sets_HasCoequalizers] instance included), no
   [Program] obligations, all reporting
   "Closed under the global context"; the Makefile's
   [print-assumptions] target audits twelve of them. *)

(** ** The generated relation *)

Section CoeqRel.

Context {A B : SetoidObject}.
Context (f g : A ~{Sets}~> B).

(* The finest equivalence relation on [carrier B] containing `≈` and the
   pairs ⟨f a, g a⟩.  [cq_base] is what makes it coarser than B's own
   equality -- which is [SetoidCoarser], the hypothesis
   Instance/Sets/Quotient.v's projection needs -- and it is also what
   supplies reflexivity, so there is no [cq_refl] constructor. *)
Inductive coeq_rel : carrier B -> carrier B -> Type :=
  | cq_base  : forall b1 b2 : carrier B, b1 ≈ b2 -> coeq_rel b1 b2
  | cq_glue  : forall a : carrier A, coeq_rel (f a) (g a)
  | cq_sym   : forall b1 b2 : carrier B, coeq_rel b1 b2 -> coeq_rel b2 b1
  | cq_trans : forall b1 b2 b3 : carrier B,
      coeq_rel b1 b2 -> coeq_rel b2 b3 -> coeq_rel b1 b3.

Lemma coeq_rel_refl (b : carrier B) : coeq_rel b b.
Proof. apply cq_base; reflexivity. Qed.

Lemma coeq_rel_Equivalence : Equivalence coeq_rel.
Proof.
  constructor.
  - exact coeq_rel_refl.
  - intros b1 b2 H; exact (cq_sym b1 b2 H).
  - intros b1 b2 b3 H1 H2; exact (cq_trans b1 b2 b3 H1 H2).
Qed.

Definition coeq_rel_coarser : SetoidCoarser coeq_rel := cq_base.

End CoeqRel.

Arguments coeq_rel {A B} f g _ _.
Arguments coeq_rel_refl {A B} f g b.
Arguments coeq_rel_Equivalence {A B} f g.
Arguments coeq_rel_coarser {A B} f g.

(** ** Leastness: respecting the closure IS coforking *)

Section Leastness.

Context {A B : SetoidObject}.
Context (f g : A ~{Sets}~> B).
Context {X : SetoidObject}.

(* The induction.  Four cases, one per constructor: [cq_base] is h's own
   respectfulness, [cq_glue] is the cofork hypothesis read at a point, and
   the last two are the target setoid's symmetry and transitivity.  This
   is the LEASTNESS of the generated relation, in the only form the
   universal property uses. *)
Lemma coeq_rel_of_cofork (h : B ~{Sets}~> X) (Hh : h ∘ f ≈ h ∘ g) :
  SetsRespects (coeq_rel f g) X h.
Proof.
  intros b1 b2 Hb.
  induction Hb as
    [ b1 b2 Hb | a | b1 b2 Hb IH | b1 b2 b3 Hb1 IH1 Hb2 IH2 ].
  - now apply proper_morphism.
  - exact (Hh a).
  - now symmetry.
  - now transitivity (h b2).
Qed.

(* ... and back, by the [cq_glue] constructor alone. *)
Lemma cofork_of_coeq_rel (h : B ~{Sets}~> X)
  (Hh : SetsRespects (coeq_rel f g) X h) : h ∘ f ≈ h ∘ g.
Proof. intro a; exact (Hh (f a) (g a) (cq_glue f g a)). Qed.

Theorem coeq_rel_respects (h : B ~{Sets}~> X) :
  SetsRespects (coeq_rel f g) X h ↔ h ∘ f ≈ h ∘ g.
Proof.
  split.
  - exact (cofork_of_coeq_rel h).
  - exact (coeq_rel_of_cofork h).
Qed.

End Leastness.

(** ** The coequalizer object *)

Section SetsCoeq.

Context {A B : SetoidObject}.
Context (f g : A ~{Sets}~> B).

Definition SetsCoeq : SetoidObject :=
  SetsQuotient B (coeq_rel f g) (coeq_rel_Equivalence f g).

Definition sets_coeq_proj : B ~{Sets}~> SetsCoeq :=
  sets_quot_proj B (coeq_rel f g) (coeq_rel_Equivalence f g)
    (coeq_rel_coarser f g).

(* The carrier is B's, and the coequalizing map is the identity function
   -- both by conversion, the [eq_refl] exception. *)
Example sets_coeq_carrier : carrier SetsCoeq = carrier B.
Proof. reflexivity. Qed.

Example sets_coeq_proj_at (b : carrier B) : sets_coeq_proj b = b.
Proof. reflexivity. Qed.

(* Awodey §3.4's construction and Seven Sketches §6.2.4's example, as the
   elementary universal property of Structure/Coequalizer.v. *)
Definition sets_coeq_IsCoequalizer :
  IsCoequalizer f g SetsCoeq sets_coeq_proj.
Proof.
  unshelve refine {| cofork := _ |}.
  - (* the projection coforks: this is [cq_glue] read pointwise *)
    intro a; exact (cq_glue f g a).
  - intros X h Hh.
    unshelve refine
      {| unique_obj :=
           sets_quot_med (coeq_rel f g) (coeq_rel_Equivalence f g)
             (existT (SetsRespects (coeq_rel f g) X) h
                (coeq_rel_of_cofork f g h Hh)) |}.
    + intro b; simpl; reflexivity.
    + intros v Hv b; simpl; symmetry; exact (Hv b).
Defined.

End SetsCoeq.

Arguments SetsCoeq {A B} f g.
Arguments sets_coeq_proj {A B} f g.

(* THE INSTANCE.  [∃] is [sigT], so the coequalizer is a CHOSEN one,
   supplied as data; no choice principle is consumed. *)
#[export] Instance Sets_HasCoequalizers : HasCoequalizers Sets := {|
  coeq := fun x y f g =>
    existT (fun q : Sets => { e : y ~{Sets}~> q & IsCoequalizer f g q e })
      (SetsCoeq f g)
      (existT (fun e : y ~{Sets}~> SetsCoeq f g =>
                 IsCoequalizer f g (SetsCoeq f g) e)
         (sets_coeq_proj f g) (sets_coeq_IsCoequalizer f g))
|}.

(* The chosen object and map are the ones built above, by conversion. *)
Example sets_hascoeq_obj {A B : SetoidObject} (f g : A ~{Sets}~> B) :
  `1 (@coeq Sets Sets_HasCoequalizers A B f g) = SetsCoeq f g.
Proof. reflexivity. Qed.

Example sets_hascoeq_map {A B : SetoidObject} (f g : A ~{Sets}~> B) :
  `1 (`2 (@coeq Sets Sets_HasCoequalizers A B f g)) = sets_coeq_proj f g.
Proof. reflexivity. Qed.

(** ** Mac Lane §III.3 exercise 5: X/E is the coequalizer of E ⇉ X *)

(* The relation, as an object of [Sets].  A point is a triple ⟨x, y, w⟩
   with w a derivation of R x y; two triples are identified when their
   first two components are, so the witness is carried as data and
   ignored by `≈`.  That is the honest rendering of "E ⊆ X × X" in a
   library whose `∃` is [sigT]: the underlying set is the image of E in
   X × X.  It is NOT claimed to be a subobject -- the evident map to
   X × X is not built here, and nothing proves it monic. *)

Section RelObject.

Context {X : SetoidObject}.
Context (R : crelation (carrier X)).

Definition sets_rel_carrier : Type :=
  { x : carrier X & { y : carrier X & R x y } }.

Definition sets_rel_equiv : crelation sets_rel_carrier :=
  fun s t => (`1 s ≈ `1 t) ∧ (`1 (`2 s) ≈ `1 (`2 t)).

Lemma sets_rel_equivalence : Equivalence sets_rel_equiv.
Proof.
  unfold sets_rel_equiv; constructor.
  - intro s; split; reflexivity.
  - intros s t [H1 H2]; split; now symmetry.
  - intros s t u [H1 H2] [H3 H4]; split;
      [ now transitivity (`1 t) | now transitivity (`1 (`2 t)) ].
Qed.

Definition SetsRelObj : SetoidObject :=
  {| carrier := sets_rel_carrier ;
     is_setoid := {| equiv := sets_rel_equiv ;
                     setoid_equiv := sets_rel_equivalence |} |}.

Definition sets_rel_fst : SetsRelObj ~{Sets}~> X.
Proof.
  unshelve refine {| morphism := fun s : sets_rel_carrier => `1 s |}.
  intros s t Hst; exact (fst Hst).
Defined.

Definition sets_rel_snd : SetsRelObj ~{Sets}~> X.
Proof.
  unshelve refine {| morphism := fun s : sets_rel_carrier => `1 (`2 s) |}.
  intros s t Hst; exact (snd Hst).
Defined.

(* The pair ⟨x, y, w⟩ is where the two projections separate, and it is
   what makes the cofork condition say exactly "h respects R". *)
Definition sets_rel_pt {x y : carrier X} (w : R x y) : carrier SetsRelObj :=
  existT (fun x' : carrier X => { y' : carrier X & R x' y' }) x
    (existT (fun y' : carrier X => R x y') y w).

Example sets_rel_fst_at {x y : carrier X} (w : R x y) :
  sets_rel_fst (sets_rel_pt w) = x.
Proof. reflexivity. Qed.

Example sets_rel_snd_at {x y : carrier X} (w : R x y) :
  sets_rel_snd (sets_rel_pt w) = y.
Proof. reflexivity. Qed.

(* Coforking the projection pair IS respecting R.  Unlike
   [coeq_rel_respects] this needs no induction at all: one direction
   evaluates at [sets_rel_pt], the other reads a triple apart. *)
Lemma sets_rel_cofork_iff {Z : SetoidObject} (h : X ~{Sets}~> Z) :
  (h ∘ sets_rel_fst ≈ h ∘ sets_rel_snd) ↔ SetsRespects R Z h.
Proof.
  split.
  - intros Hh x y w; exact (Hh (sets_rel_pt w)).
  - intros Hh s; exact (Hh (`1 s) (`1 (`2 s)) (`2 (`2 s))).
Qed.

(* Mac Lane §III.3 exercise 5 / Awodey §3.4 example 3.19.  Note that the
   coequalizer object here is the quotient ON THE NOSE, not merely
   isomorphic to it. *)
Definition sets_rel_IsCoequalizer (HR : Equivalence R) (HC : SetoidCoarser R) :
  IsCoequalizer sets_rel_fst sets_rel_snd (SetsQuotient X R HR)
    (sets_quot_proj X R HR HC).
Proof.
  unshelve refine {| cofork := _ |}.
  - intro s; exact (`2 (`2 s)).
  - intros Z h Hh.
    unshelve refine
      {| unique_obj :=
           sets_quot_med R HR
             (existT (SetsRespects R Z) h
                (fst (sets_rel_cofork_iff h) Hh)) |}.
    + intro x; simpl; reflexivity.
    + intros v Hv x; simpl; symmetry; exact (Hv x).
Defined.

End RelObject.

Arguments SetsRelObj {X} R.
Arguments sets_rel_fst {X} R.
Arguments sets_rel_snd {X} R.
Arguments sets_rel_pt {X R x y} w.

(** ** The two readings agree *)

Section Comparison.

Context {X : SetoidObject}.
Context (R : crelation (carrier X)).
Context (HR : Equivalence R).
(* Generating an equivalence relation from the projections of an
   equivalence relation returns it.  Forward is the four-case induction
   ([cq_base] consumes coarseness, [cq_glue] returns the carried witness),
   backward is one constructor. *)
Lemma sets_rel_coeq_rel_iff (HR' : Equivalence R) (HC' : SetoidCoarser R)
  (x y : carrier X) :
  coeq_rel (sets_rel_fst R) (sets_rel_snd R) x y ↔ R x y.
Proof.
  split.
  - intro H.
    induction H as
      [ b1 b2 Hb | s | b1 b2 Hb IH | b1 b2 b3 Hb1 IH1 Hb2 IH2 ].
    + exact (HC' b1 b2 Hb).
    + exact (`2 (`2 s)).
    + now symmetry.
    + now transitivity b2.
  - intro H; exact (cq_glue (sets_rel_fst R) (sets_rel_snd R) (sets_rel_pt H)).
Qed.

(* ... so the coequalizer produced by [Sets_HasCoequalizers] at the
   projection pair and the quotient itself are isomorphic in [Sets], with
   the IDENTITY function in both directions -- the carriers are the same
   type and only `≈` moves. *)
Definition sets_rel_coeq_iso (HC' : SetoidCoarser R) :
  @Isomorphism Sets (SetsCoeq (sets_rel_fst R) (sets_rel_snd R))
    (SetsQuotient X R HR).
Proof.
  unshelve refine {| to := _ ; from := _ |}.
  - unshelve refine {| morphism := fun x : carrier X => x |}.
    intros a b Hab; exact (fst (sets_rel_coeq_rel_iff HR HC' a b) Hab).
  - unshelve refine {| morphism := fun x : carrier X => x |}.
    intros a b Hab; exact (snd (sets_rel_coeq_rel_iff HR HC' a b) Hab).
  - intro x; exact (@Equivalence_Reflexive _ R HR x).
  - intro x; exact (coeq_rel_refl (sets_rel_fst R) (sets_rel_snd R) x).
Defined.

(* Both legs are the identity function, by conversion. *)
Example sets_rel_coeq_iso_to (HC : SetoidCoarser R) (x : carrier X) :
  to (sets_rel_coeq_iso HC) x = x.
Proof. reflexivity. Qed.

Example sets_rel_coeq_iso_from (HC : SetoidCoarser R) (x : carrier X) :
  from (sets_rel_coeq_iso HC) x = x.
Proof. reflexivity. Qed.

End Comparison.

(** ** Non-vacuity *)

(* A coequalizer that MERGES.  The two constant maps out of the singleton
   into the two-element discrete setoid identify [false] with [true], so
   the coequalizer collapses [bool]. *)

Definition UnitSet : SetoidObject :=
  {| carrier := poly_unit ; is_setoid := unit_setoid |}.

(* [BoolSet] is Instance/Sets/Quotient.v's, reused rather than
   redeclared: the two files' witnesses then live over the same object. *)

Definition bool_false_map : UnitSet ~{Sets}~> BoolSet.
Proof. unshelve refine {| morphism := fun _ : poly_unit => false |}. Defined.

Definition bool_true_map : UnitSet ~{Sets}~> BoolSet.
Proof. unshelve refine {| morphism := fun _ : poly_unit => true |}. Defined.

Definition bool_flip_coeq : SetoidObject :=
  SetsCoeq bool_false_map bool_true_map.

Lemma bool_flip_merges : @equiv _ bool_flip_coeq false true.
Proof. exact (cq_glue bool_false_map bool_true_map ttt). Qed.

(* A coequalizer that MERGES NOTHING.  For f = g the generated relation
   collapses to the setoid's own `≈`; the proof is the four-case
   induction, with [cq_glue] contributing [reflexivity] because its two
   sides are the same term. *)
Lemma coeq_rel_diagonal {A B : SetoidObject} (f : A ~{Sets}~> B)
  (b1 b2 : carrier B) : coeq_rel f f b1 b2 → b1 ≈ b2.
Proof.
  intro H.
  induction H as
    [ b1 b2 Hb | a | b1 b2 Hb IH | b1 b2 b3 Hb1 IH1 Hb2 IH2 ].
  - exact Hb.
  - reflexivity.
  - now symmetry.
  - now transitivity b2.
Qed.

Lemma bool_id_coeq_separates :
  @equiv _ (SetsCoeq bool_false_map bool_false_map) false true → False.
Proof.
  intro H.
  pose proof (coeq_rel_diagonal bool_false_map false true H) as E.
  discriminate E.
Qed.

(* The two witnesses are over the SAME domain and codomain and share
   their FIRST leg, so what separates them is the second leg of the pair
   and nothing about the ambient setoids.  That the two legs are genuinely
   different morphisms of [Sets] -- and hence that [bool_flip_coeq] and
   the diagonal coequalizer are coequalizers of DIFFERENT pairs -- is this
   refutation, not an appeal to how they were written. *)
Lemma bool_legs_distinct : bool_false_map ≈ bool_true_map → False.
Proof. intro H; pose proof (H ttt) as E; discriminate E. Qed.
