Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Natural.Transformation.
Require Import Category.Functor.Bifunctor.
Require Import Category.Construction.Product.
Require Import Category.Functor.Construction.Product.
Require Import Category.Instance.Fun.
Require Import Category.Structure.Monoidal.
Require Import Category.Structure.Monoidal.Braided.
Require Import Category.Structure.Monoidal.Symmetric.
Require Import Category.Structure.Monoidal.Strict.
Require Import Category.Functor.Structure.Monoidal.
Require Import Category.Functor.Structure.Monoidal.Strict.
Require Import Category.Functor.Structure.Monoidal.Braided.
Require Import Category.Construction.Quotient.
Require Import Category.Construction.PROP.
Require Import Category.Construction.PROP.Signature.
Require Import Category.Construction.PROP.Term.
Require Import Category.Construction.PROP.TermEq.
Require Import Category.Construction.PROP.Free.
Require Import Category.Construction.PROP.Tensor.
Require Import Category.Construction.PROP.Cast.
Require Import Category.Construction.PROP.Structural.
Require Import Category.Construction.PROP.Monoidal.
Require Import Category.Construction.PROP.Braided.
Require Import Category.Construction.PROP.Symmetric.
Require Import Category.Construction.PROP.Strict.
Require Import Category.Construction.PROP.Instance.

From Coq Require Import Arith.

Generalizable All Variables.

(** * Presentations of PROPs by symmetric monoidal theories *)

(* nLab: https://ncatlab.org/nlab/show/PROP
   nLab: https://ncatlab.org/nlab/show/symmetric+monoidal+category
   nLab: https://ncatlab.org/nlab/show/generators+and+relations
   Wikipedia: https://en.wikipedia.org/wiki/PROP_(category_theory)
   Wikipedia: https://en.wikipedia.org/wiki/Presentation_of_a_monoid

   A SYMMETRIC MONOIDAL THEORY (an [SMT]) is a signature [Σ] together
   with a family of equations between [Σ]-terms of matching arities.
   The PROP it PRESENTS is the free PROP on [Σ], further quotiented by
   the congruence generated by those equations — exactly as a monoid
   presented by generators and relations is the free monoid quotiented
   by the relation-congruence.  Classical examples: the theory of
   commutative monoids presents the PROP of finite sets and functions;
   the theory of special commutative Frobenius algebras presents the
   PROP of cospans of finite sets.

   Concretely, this file builds, for a theory [E : SMT] over
   [Σ := smt_sig E]:

     - [TermEqW E], the [Prop]-valued congruence on [Term Σ] generated
       by the free equations [TermEq Σ] TOGETHER WITH the axioms
       [smt_eqs E] (six constructors: embedding, axiom, symmetry,
       transitivity, and the two composition congruences — reflexivity
       is inherited from [TE_refl] through the embedding);
     - [PresentedCat E], the quotient of [FreeCat Σ] by [TermEqW E],
       via the fully general quotient kit of [Construction/Quotient.v];
     - the full PROP tower on the quotient: ONE shared [Monoidal]
       record [Presented_Monoidal E], plus the Braided, Symmetric and
       Strict instances that all project it, culminating in
       [PresentedPROP E] whose [prop_monoidal_coherence] is therefore
       [eq_refl], definitionally — the same shared-record wiring as
       [FreePROP] in [Construction/PROP/Instance.v];
     - the projection functor [PresentedProj E : FreeCat Σ ⟶
       PresentedCat E], which is the identity on objects and on
       morphisms (only the equivalence coarsens), together with its
       strict/braided/symmetric monoidal functor structure — the
       projection-side symmetric-monoidal API of the presentation.
       (Of these, the universal-property file consumes
       [PresentedProj_Strict], discharging the braid square of its
       precomposed competitor directly from the competitor's own
       square via the strict cast lemmas; the braided/symmetric
       packagings are exported for other clients.)

   Every equational field of the quotient structures is the
   corresponding FREE lemma embedded by [TEW_termeq]: the underlying
   morphisms of [PresentedCat E] ARE the terms of [FreeCat Σ], so each
   free equation is verbatim an equation of the quotient, just under a
   coarser equivalence.  Following the [Free.v] discipline, the heavy
   records are assembled from standalone, named lemmas with every
   field explicit, with one calibrated exception: the
   reflexivity-grade strictness comparisons of [Presented_Strict] and
   [PresentedProj_Strict] are discharged as in-situ Program
   obligations, because a separately-declared comparison lemma
   carries its own universe instance of the polymorphic
   [PresentedCat] and the record-field unifier stops at the instance
   mismatch inside the transported-identity [match] (see the comment
   at [Presented_Strict]).

   The side conditions required of quotient categories by the
   interpretation files need nothing new here: the generic
   [Quotient_HomEqProp] and [Quotient_ObjDecEq] instances of
   [Construction/Quotient.v] apply to [PresentedCat E] directly (the
   quotient's [≈] IS [TermEqW E] after reduction, and objects are
   [nat], with decidability inherited from [FreeCat_ObjDecEq]). *)

(** ** Symmetric monoidal theories *)

(** An equation system over a signature: for each pair of arities, a
    relation on the [Σ]-terms of that arity.  [Prop]-valued, matching
    the [Prop]-valued congruences that [Construction/Quotient.v]
    quotients by. *)
Definition EqSystem (S : Signature) : Type :=
  ∀ m n : nat, Term S m n → Term S m n → Prop.

(** A symmetric monoidal theory: generators plus equations. *)
Record SMT : Type := {
  smt_sig : Signature;
  smt_eqs : EqSystem smt_sig
}.

Section Presented.

Context (E : SMT).

Notation Σ := (smt_sig E).

Open Scope nat_scope.

(** ** The theory congruence

    [TermEqW] ("W" for "with axioms") is the smallest congruence on
    [Term Σ] containing both the free equations [TermEq Σ] and the
    theory axioms [smt_eqs E].  Reflexivity is derivable —
    [TEW_termeq _ _ (TE_refl _)] — so it is not a constructor.

    As with [TermEq] itself, the Section+Context style keeps [E] a
    section variable rather than a uniform inductive parameter. *)

Inductive TermEqW : forall {m n}, Term Σ m n → Term Σ m n → Prop :=

  (** Every free equation holds in the presented PROP. *)
  | TEW_termeq {m n} (s t : Term Σ m n) :
      TermEq Σ s t → TermEqW s t

  (** Every axiom of the theory holds in the presented PROP. *)
  | TEW_ax {m n} (s t : Term Σ m n) :
      smt_eqs E m n s t → TermEqW s t

  (** Closure under symmetry and transitivity. *)
  | TEW_sym {m n} (s t : Term Σ m n) :
      TermEqW s t → TermEqW t s
  | TEW_trans {m n} (s t u : Term Σ m n) :
      TermEqW s t → TermEqW t u → TermEqW s u

  (** Closure under the two composition operations. *)
  | TEW_comp {m n p} (f f' : Term Σ n p) (g g' : Term Σ m n) :
      TermEqW f f' → TermEqW g g' →
      TermEqW (T_comp f g) (T_comp f' g')
  | TEW_tens {m1 n1 m2 n2} (f f' : Term Σ m1 n1) (g g' : Term Σ m2 n2) :
      TermEqW f f' → TermEqW g g' →
      TermEqW (T_tens f g) (T_tens f' g').

(** [TermEqW] is a hom-congruence on [FreeCat Σ] in the sense of
    [Construction/Quotient.v]: it contains the hom-setoid equivalence
    ([TermEq Σ], via [TEW_termeq]) and is closed under [T_comp]. *)
#[export] Instance TermEqW_Congruence :
  @HomCongruence (FreeCat Σ) (fun m n : nat => @TermEqW m n) :=
  @Build_HomCongruence (FreeCat Σ) (fun m n : nat => @TermEqW m n)
    (fun (m n : nat) (s t : Term Σ m n) H => TEW_termeq s t H)
    (fun (m n : nat) (s t : Term Σ m n) H => TEW_sym s t H)
    (fun (m n : nat) (s t u : Term Σ m n) H1 H2 => TEW_trans s t u H1 H2)
    (fun (m n p : nat) (f f' : Term Σ n p) (g g' : Term Σ m n) Hf Hg =>
       TEW_comp f f' g g' Hf Hg).

(** ** The presented category

    Same objects ([nat]) and same morphisms ([Term Σ]) as the free
    category; only the equivalence coarsens from [TermEq Σ] to
    [TermEqW].  The generic [Quotient_HomEqProp] and
    [Quotient_ObjDecEq] instances of [Construction/Quotient.v] apply
    to it as-is, so nothing further needs defining here. *)

Definition PresentedCat : Category :=
  @Quotient (FreeCat Σ) (fun m n : nat => @TermEqW m n) TermEqW_Congruence.

(** A term, viewed as a morphism of the presented category (the
    carrier of a hom of [PresentedCat] IS [Term Σ]). *)
Definition quot {m n : nat} (t : Term Σ m n) : m ~{PresentedCat}~> n := t.

(** The projection functor: identity on objects and morphisms. *)
Definition PresentedProj : FreeCat Σ ⟶ PresentedCat :=
  @QuotientProj (FreeCat Σ) (fun m n : nat => @TermEqW m n) TermEqW_Congruence.

(** ** Term-level bookkeeping lemmas

    Small [TermEq]-level facts used to discharge the comparison
    squares of the projection functor, where every comparison map is
    an identity or a tensor of identities. *)

(** An identity slides from one side of a morphism to the other. *)
Lemma term_id_swap {m n : nat} (t : Term Σ m n) :
  TermEq Σ (T_comp t (T_id m)) (T_comp (T_id n) t).
Proof.
  apply TE_trans with t.
  - apply TE_id_right.
  - apply TE_sym, TE_id_left.
Qed.

(** A composite of identities equals a tensor of identities. *)
Lemma term_comp_id_tens (m n : nat) :
  TermEq Σ (T_comp (T_id (m + n)) (T_id (m + n))) (T_tens (T_id m) (T_id n)).
Proof.
  apply TE_trans with (T_id (m + n)).
  - apply TE_id_left.
  - apply TE_sym, TE_tens_id.
Qed.

(** Reflexivity of the theory congruence, via the embedding. *)
Definition TermEqW_refl {m n : nat} (t : Term Σ m n) : TermEqW t t :=
  TEW_termeq t t (TE_refl t).

(** Collapsing an identity and a tensor of identities after [t]. *)
Lemma term_collapse_r {m n p : nat} (t : Term Σ (m + n) p) :
  TermEq Σ (T_comp (T_comp t (T_id (m + n))) (T_tens (T_id m) (T_id n))) t.
Proof.
  apply TE_trans with (T_comp t (T_tens (T_id m) (T_id n))).
  - apply TE_comp_cong.
    + apply TE_id_right.
    + apply TE_refl.
  - apply TE_trans with (T_comp t (T_id (m + n))).
    + apply TE_comp_cong.
      * apply TE_refl.
      * apply TE_tens_id.
    + apply TE_id_right.
Qed.

(** Collapsing an identity and a tensor of identities before [t]. *)
Lemma term_collapse_l {m n p : nat} (t : Term Σ p (m + n)) :
  TermEq Σ (T_comp (T_comp (T_id (m + n)) (T_tens (T_id m) (T_id n))) t) t.
Proof.
  apply TE_trans with (T_comp (T_tens (T_id m) (T_id n)) t).
  - apply TE_comp_cong.
    + apply TE_id_left.
    + apply TE_refl.
  - apply TE_trans with (T_comp (T_id (m + n)) t).
    + apply TE_comp_cong.
      * apply TE_tens_id.
      * apply TE_refl.
    + apply TE_id_left.
Qed.

(** ** The tensor on the presented category

    The parallel-composition bifunctor descends to the quotient
    because [TermEqW] is closed under [T_tens]. *)

Definition Presented_Tensor : PresentedCat ∏ PresentedCat ⟶ PresentedCat :=
  @Quotient_bifunctor (FreeCat Σ) (fun m n : nat => @TermEqW m n)
    TermEqW_Congruence (FreeCat_Tensor Σ)
    (fun x y f g Hf Hg => TEW_tens (fst f) (fst g) (snd f) (snd g) Hf Hg).

(** ** THE shared Monoidal record on [PresentedCat]

    Unit [0], tensor [Presented_Tensor], structural isomorphisms the
    [T_cast] isos of [Structural.v] pushed through [Quotient_iso].
    Every proof field is the corresponding FREE lemma — the very same
    lemmas that assemble [FreeCat_Monoidal] — embedded by
    [TEW_termeq]: the two sides of each square are syntactically the
    same terms, only compared under the coarser equivalence.

    Braided, Symmetric, Strict, and the bundled PROP below all name
    this ONE record, so their agreement is definitional. *)

Program Definition Presented_Monoidal : @Monoidal PresentedCat := {|
  I            := 0;
  tensor       := Presented_Tensor;
  unit_left    := fun x => Quotient_iso (FreeCat_unit_left Σ x);
  unit_right   := fun x => Quotient_iso (FreeCat_unit_right Σ x);
  tensor_assoc := fun x y z => Quotient_iso (FreeCat_tensor_assoc Σ x y z);
  to_unit_left_natural := fun x y g =>
    TEW_termeq _ _ (@to_unit_left_natural _ (FreeCat_Monoidal Σ) x y g);
  from_unit_left_natural := fun x y g =>
    TEW_termeq _ _ (@from_unit_left_natural _ (FreeCat_Monoidal Σ) x y g);
  to_unit_right_natural := fun x y g =>
    TEW_termeq _ _ (right_unit_natural Σ g);
  from_unit_right_natural := fun x y g =>
    TEW_termeq _ _ (right_unit_natural_from Σ g);
  to_tensor_assoc_natural := fun _ _ _ _ _ _ g h i =>
    TEW_termeq _ _ (assoc_natural Σ g h i);
  from_tensor_assoc_natural := fun _ _ _ _ _ _ g h i =>
    TEW_termeq _ _ (assoc_natural_from Σ g h i);
  triangle_identity := fun x y =>
    TEW_termeq _ _ (free_triangle Σ x y);
  pentagon_identity := fun x y z w =>
    TEW_termeq _ _ (free_pentagon Σ x y z w)
|}.

(** ** The braided and symmetric structure

    The block braiding [T_braid] descends unchanged; its naturality
    square, the two hexagons, and the involution are the free lemmas
    of [Construction/PROP/{Braided,Symmetric}.v], embedded.  (The
    synonym lemmas of [Construction/PROP/Naturality.v] are
    deliberately not imported: their names [braid_natural] and
    [braid_invol] would shadow the class projections of the same
    names in the record literals below.) *)

Program Definition Presented_Braided : @BraidedMonoidal PresentedCat := {|
  braided_is_monoidal := Presented_Monoidal;  (* THE shared record *)
  braid := fun m n => T_braid m n;
  braid_natural := fun x y g z w h =>
    TEW_termeq _ _ (free_braid_square Σ g h);
  hexagon_identity := fun x y z =>
    TEW_termeq _ _ (free_hexagon Σ x y z);
  hexagon_identity_sym := fun x y z =>
    TEW_termeq _ _ (free_hexagon_sym Σ x y z)
|}.

Program Definition Presented_Symmetric : @SymmetricMonoidal PresentedCat := {|
  symmetric_is_braided := Presented_Braided;
  braid_invol := fun x y =>
    TEW_termeq _ _ (free_braid_invol Σ x y)
|}.

(** ** The strict structure

    Objects are naturals and the tensor on objects is addition, so
    the object-level strictness equalities are the arity equations of
    [Nat]; the comparison fields are reflexivity-grade because
    [Structural.v] BUILT the structural isomorphisms as [T_cast]
    maps, which are definitionally the transported identities the
    class asks for (same proof term on both sides). *)

(*  The three comparison fields are reflexivity-grade, as in the free
    donor [Construction/PROP/Strict.v], but here they are discharged
    as Program obligations rather than by applying standalone lemmas:
    a separately-declared lemma carries its own universe instance of
    the polymorphic [PresentedCat], and the record-field unifier stops
    at the instance mismatch inside the transported-identity [match]
    before it would reduce both sides.  Proving the field in situ
    keeps the whole comparison at the record's single instance. *)
Program Definition Presented_Strict : @StrictMonoidal PresentedCat := {|
  strict_is_monoidal    := Presented_Monoidal;  (* THE shared record *)
  strict_assoc_obj      := fun x y z => eq_sym (Nat.add_assoc x y z);
  strict_unit_left_obj  := fun x => Nat.add_0_l x;
  strict_unit_right_obj := fun x => Nat.add_0_r x
|}.
Next Obligation. exact (TermEqW_refl _). Qed.
Next Obligation. exact (TermEqW_refl _). Qed.
Next Obligation. exact (TermEqW_refl _). Qed.

(** ** The presented PROP, bundled

    As with [FreePROP], every equality field is [eq_refl] because the
    whole tower shares the ONE [Monoidal] record [Presented_Monoidal].
    If [prop_monoidal_coherence := eq_refl] ever stops typechecking,
    the shared-record wiring broke — fix the wiring; do not generalize
    the field. *)

Definition PresentedPROP : PROP := {|
  prop_cat       := PresentedCat;
  prop_strict    := Presented_Strict;
  prop_symmetric := Presented_Symmetric;
  prop_monoidal_coherence := eq_refl;
  prop_of_nat    := fun n : nat => n;
  prop_unit_zero := eq_refl;
  prop_tensor_plus := fun m n => eq_refl
|}.

(** ** The projection is a strict symmetric monoidal functor

    [PresentedProj] is the identity on objects and morphisms, so both
    comparison maps are identities and every coherence square is an
    identity-bookkeeping equation, discharged by the term-level
    lemmas above through [TEW_termeq]. *)

(** The tensor-then-project and project-then-tensor composites that
    the tensor comparison relates. *)
Definition Presented_ap_dom : FreeCat Σ ∏ FreeCat Σ ⟶ PresentedCat :=
  Presented_Tensor ◯ (PresentedProj ∏⟶ PresentedProj).

Definition Presented_ap_cod : FreeCat Σ ∏ FreeCat Σ ⟶ PresentedCat :=
  PresentedProj ◯ FreeCat_Tensor Σ.

(** Both directions of the tensor comparison are families of
    identities; naturality is [term_id_swap]. *)
Definition Presented_ap_to : Presented_ap_dom ⟹ Presented_ap_cod :=
  @Build_Transform' (FreeCat Σ ∏ FreeCat Σ) PresentedCat
    Presented_ap_dom Presented_ap_cod
    (fun p => T_id (fst p + snd p))
    (fun p q f => TEW_termeq _ _ (term_id_swap (T_tens (fst f) (snd f)))).

Definition Presented_ap_from : Presented_ap_cod ⟹ Presented_ap_dom :=
  @Build_Transform' (FreeCat Σ ∏ FreeCat Σ) PresentedCat
    Presented_ap_cod Presented_ap_dom
    (fun p => T_id (fst p + snd p))
    (fun p q f => TEW_termeq _ _ (term_id_swap (T_tens (fst f) (snd f)))).

(** The identity components are inverse up to [TermEqW] (the identity
    natural transformation of a composite-with-tensor functor has
    components [T_tens (T_id _) (T_id _)]). *)
Program Definition Presented_ap_iso :
  Presented_ap_dom ≅[[FreeCat Σ ∏ FreeCat Σ, PresentedCat]] Presented_ap_cod := {|
  to   := Presented_ap_to;
  from := Presented_ap_from;
  iso_to_from := fun p =>
    TEW_termeq _ _ (term_comp_id_tens (fst p) (snd p));
  iso_from_to := fun p =>
    TEW_termeq _ _ (term_comp_id_tens (fst p) (snd p))
|}.

Program Definition PresentedProj_Monoidal :
  @MonoidalFunctor (FreeCat Σ) PresentedCat
    (FreeCat_Monoidal Σ) Presented_Monoidal PresentedProj := {|
  pure_iso := iso_id;
  ap_functor_iso := Presented_ap_iso;
  pure_iso_left  := fun x => iso_id;
  pure_iso_right := fun x => iso_id;
  ap_iso_assoc := fun x y z => @tensor_assoc PresentedCat Presented_Monoidal x y z;
  monoidal_unit_left := fun x =>
    TEW_termeq _ _ (TE_sym _ _ (term_collapse_r (T_cast (Nat.add_0_l x))));
  monoidal_unit_right := fun x =>
    TEW_termeq _ _ (TE_sym _ _ (term_collapse_r (T_cast (Nat.add_0_r x))));
  monoidal_assoc := fun x y z =>
    TEW_termeq _ _
      (TE_trans _ _ _
         (term_collapse_r (T_cast (eq_sym (Nat.add_assoc x y z))))
         (TE_sym _ _
            (term_collapse_l (T_cast (eq_sym (Nat.add_assoc x y z))))))
|}.

(** Both comparison maps of the projection are identities on the
    nose, so the projection is STRICT monoidal, with [eq_refl] object
    equalities. *)

Lemma PresentedProj_pure_id :
  to (@pure_iso _ _ _ _ PresentedProj PresentedProj_Monoidal)
  ≈[PresentedCat] @id PresentedCat 0.
Proof. exact (TermEqW_refl _). Qed.

Lemma PresentedProj_ap_id (x y : nat) :
  to (@ap_iso _ _ _ _ PresentedProj PresentedProj_Monoidal x y)
  ≈[PresentedCat] @id PresentedCat (x + y).
Proof. exact (TermEqW_refl _). Qed.

(*  As with [Presented_Strict], the two comparison fields are
    discharged in situ (both comparison maps are identities on the
    nose), keeping the whole record at a single universe instance of
    [PresentedCat]. *)
Program Definition PresentedProj_Strict :
  @StrictMonoidalFunctor (FreeCat Σ) PresentedCat
    (FreeCat_Monoidal Σ) Presented_Monoidal PresentedProj := {|
  strict_functor_is_monoidal := PresentedProj_Monoidal;
  strict_pure_obj := eq_refl;
  strict_ap_obj := fun x y => eq_refl
|}.
Next Obligation. exact (TermEqW_refl _). Qed.
Next Obligation. exact (TermEqW_refl _). Qed.

(** The braid-compatibility square of the projection: the free braid
    maps to the presented braid, conjugated by the (identity) tensor
    comparisons.  This is the [SymmetricMonoidalFunctor] square in
    the strict setting, provided as projection-side API; the
    universal-property file does not consume it — when transferring
    uniqueness across the projection it discharges the composite's
    braid square directly from the competitor's own square,
    rewriting all four tensor comparisons to casts with
    [strict_ap_iso_id]. *)
Lemma PresentedProj_braid (m n : nat) :
  fmap[PresentedProj] (@braid (FreeCat Σ) (FreeCat_Braided Σ) m n)
    ∘ to (@ap_iso _ _ _ _ PresentedProj PresentedProj_Monoidal m n)
  ≈[PresentedCat]
  to (@ap_iso _ _ _ _ PresentedProj PresentedProj_Monoidal n m)
    ∘ @braid PresentedCat Presented_Braided m n.
Proof.
  exact (TEW_termeq _ _ (term_id_swap (T_braid m n))).
Qed.

Program Definition PresentedProj_Braided :
  @BraidedMonoidalFunctor (FreeCat Σ) PresentedCat
    (FreeCat_Braided Σ) Presented_Braided PresentedProj := {|
  braided_is_strong := PresentedProj_Monoidal
|}.
Next Obligation.
  exact (TEW_termeq _ _ (term_id_swap (T_braid x y))).
Qed.

(** A braided monoidal functor between symmetric monoidal categories
    IS a symmetric monoidal functor ([SymmetricMonoidalFunctor] is a
    definition, not a class); supplied explicitly, as the alias does
    not participate in instance resolution. *)
Definition PresentedProj_Symmetric :
  @SymmetricMonoidalFunctor (FreeCat Σ) PresentedCat
    (FreeCat_Symmetric Σ) Presented_Symmetric PresentedProj :=
  PresentedProj_Braided.

(** ** Machine-checked sanity

    Each [Example] holds by [eq_refl], witnessing that the
    corresponding field or action is definitional; any regression in
    the shared-record wiring is caught here rather than at a distant
    use site. *)

(** The coherence between the strict and symmetric [Monoidal] paths
    is the reflexivity proof itself. *)
Example PresentedPROP_coherence_is_refl :
  @prop_monoidal_coherence PresentedPROP = eq_refl := eq_refl.

(** Tensor-on-objects is literally addition, with [eq_refl] proof. *)
Example PresentedPROP_tensor_plus_is_refl (m n : nat) :
  @prop_tensor_plus PresentedPROP m n = eq_refl := eq_refl.

(** The projection functor acts as the identity on terms. *)
Example PresentedProj_fmap_id_on_terms {m n : nat} (t : Term Σ m n) :
  fmap[PresentedProj] t = quot t := eq_refl.

(** Every axiom of the theory holds in the presented category. *)
Example Presented_axioms_hold {m n : nat} (s t : Term Σ m n)
  (H : smt_eqs E m n s t) : quot s ≈[PresentedCat] quot t := TEW_ax s t H.

End Presented.

Arguments TermEqW E {m n} _ _.
Arguments PresentedCat E : assert.
Arguments quot E {m n} t : assert.
Arguments PresentedProj E : assert.
Arguments Presented_Tensor E : assert.
Arguments Presented_Monoidal E : assert.
Arguments Presented_Braided E : assert.
Arguments Presented_Symmetric E : assert.
Arguments Presented_Strict E : assert.
Arguments PresentedPROP E : assert.
Arguments PresentedProj_Monoidal E : assert.
Arguments PresentedProj_Strict E : assert.
Arguments PresentedProj_braid E m n : assert.
Arguments PresentedProj_Braided E : assert.
Arguments PresentedProj_Symmetric E : assert.
