Require Import Category.Lib.
Require Import Category.Lib.TList.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Construction.Quotient.
Require Import Category.Construction.Free.Quiver.
Require Import Category.Structure.Groupoid.
Require Import Category.Construction.Deloop.

Generalizable All Variables.

(** [Construction/Free/Quiver.v] declares [edgeset] as a section-local
    instance and again as a [Local Existing Instance], so it does not escape
    that file.  Re-declaring it here — locally, so it does not escape this
    one either — is mandatory: without it the very first statement about edge
    equivalence reports a missing [Setoid] instance. *)
#[local] Existing Instance edgeset.

(** * The free groupoid on a quiver

    nLab:      https://ncatlab.org/nlab/show/free+groupoid
    nLab:      https://ncatlab.org/nlab/show/groupoid
    nLab:      https://ncatlab.org/nlab/show/quotient+category
    Wikipedia: https://en.wikipedia.org/wiki/Groupoid
    Book: Mac Lane, Categories for the Working Mathematician, 2nd ed.,
          GTM 5, §II.7, printed p. 51 (Exercise 3: the free groupoid on a
          graph, and the free group as its one-object case)
    Book: Riehl, Category Theory in Context, §4.2, printed p. 139 (free ⊣
          forgetful, of which the groupoid case is an example)
    Book: Higgins, Categories and Groupoids, Van Nostrand 1971, reprinted
          as TAC Reprints 7 (2005) — the standard reference for free
          groupoids and their word calculus
    Book: Brown, Topology and Groupoids, 2006 (free groupoids, and the case
          for the fundamental groupoid rather than the fundamental group)

    WHY A GROUPOID AND NOT A GROUP.  The classical construction adjoins to
    every generator a formal inverse and cancels; taking one object recovers
    the free group, which is what Mac Lane's exercise asks for at the end.
    The reason to do the many-object case first is the one Brown makes for
    the fundamental groupoid: the group version has to choose a base point,
    and a graph with several components — or several vertices — has no
    canonical one.  A groupoid keeps every vertex, and the group at a chosen
    vertex is recovered afterwards (in tree: [vertex_group],
    Structure/Groupoid.v).  [Instance/Grp/Free.v] takes the one-object case
    and lands it in [Grp].

    THE RECIPE, AND WHY IT IS ASSEMBLY.  Take the quiver [G], adjoin a
    reversed copy of every edge ([SignedQuiver]), take the free category on
    that ([Construction/Free/Quiver.v]'s [FreeOnQuiver], whose morphisms are
    [Lib/TList.v] paths), and quotient by the congruence GENERATED by two
    equations per edge ([Construction/Quotient.v]'s [CongClosure]).  No
    bespoke inductive congruence is written here: symmetry, transitivity,
    compatibility with composition and containment of the ambient [≈] all
    come from [CongClosure], and [cc_kernel] turns "the functor merges the
    two generating equations" into "the functor merges the whole
    congruence" with no second induction.  This is
    [Construction/Free/Quiver/Presented.v]'s recipe — free-on-a-quiver, then
    quotient — instantiated at a two-equation presentation, and it is
    deliberately the same shape.

    THE REVERSAL KIT WAS ALREADY THERE.  [Lib/TList.v]'s [tlist_rev],
    parameterized by an edge-flipping operation, is exactly word reversal.
    Measured against the tree at the time of writing, the string [tlist_rev]
    occurs on 21 lines of [Lib/TList.v] and on no line of any other [.v]
    file; the apparent hit in [Lib/NETList.v] is its sibling [netlist_rev], a
    different function whose name merely contains the substring, and which
    is likewise unused outside its own file.  (Outside the [.v] sources it
    also appears once, as the string [tlist_rev_length], in
    doc/plan/books/seven-sketches/coverage/verified-3-0.json — a coverage
    note, which consumes nothing.)  So this file is the first consumer.  What it buys is not convenience but STRENGTH:
    [tlist_rev_app_distr] IS the anti-homomorphism law (g ∘ f)⁻¹ = f⁻¹ ∘ g⁻¹
    and [tlist_rev_involutive] IS involutivity of inversion, both at Leibniz
    [=] rather than at [≈] — see [fginv_compose] and [fginv_involutive]
    below.  The [flip_involutive] hypothesis [tlist_rev_involutive] carries
    is discharged ON THE NOSE by the sum swap ([sflip_involutive], one
    [destruct]).

    WHICH GROUPOID NOTION.  What is proved is [IsGroupoid FreeGroupoid], the
    PREDICATE of Structure/Groupoid.v — every morphism has a two-sided
    inverse.  It is NOT a [Groupoid] of something: Construction/Groupoid.v's
    [Groupoid C] is the CORE, which DISCARDS the non-invertible arrows of
    [C], whereas this construction ADJOINS inverses.  The two are different
    adjoints to the same inclusion, and that file's header says so.
    [IsGroupoid] is a plain [Definition], deliberately not a [Class] and
    never registered for resolution, so it is passed explicitly everywhere
    below.

    STRENGTHS, MEASURED RATHER THAN ASSUMED.

      - Leibniz [=]: [fginv_involutive], [fginv_compose], [fginv_gen],
        [sflip_involutive].  These are facts about words, before any
        quotient.
      - [eq_refl]: the chosen inverse of the groupoid structure IS word
        reversal ([fg_ginv_is_reversal]); the projection is the identity on
        objects ([fg_proj_obj]); the hom TYPES of the free groupoid and of
        the free category on the signed quiver are the same type
        ([fg_hom_type]); restriction along the unit recovers a functor's
        action on generators ([fg_restrict_gen]).
      - [≈] only: the two inverse laws ([fginv_left], [fginv_right]) — they
        are exactly what the quotient is for, and Test/ProbeFreeGroupoid.v
        pins the negative side with a [Fail] probe.
      - STRICT: uniqueness in the universal property
        ([FreeGroupoidFunctor_unique]) is stated with Leibniz equality on
        objects and a [hom_cast] conjugation on morphisms, which IS
        [StrictCat]'s functor equality ([Functor_StrictEq_Setoid]);
        [Construction/Quotient.v]'s [strict_of_hom_cast] converts, and
        [Instance/StrictCat/ToCat.v]'s [strict_equiv_implies_fun_equiv] then
        weakens to a natural isomorphism in [Cat].  Strict is STRONGER, and
        nothing here is stated only at the weaker level.

    THE HYPOTHESIS ON A COMPETITOR IS ONLY ABOUT POSITIVE GENERATORS, which
    is the whole content of freeness for groupoids as against freeness for
    categories.  A competitor functor is constrained on the edges of [G] and
    on nothing else; its value on a REVERSED edge is then forced, because a
    functor carries the imposed cancellation equations to genuine inverse
    equations in the target and inverses are unique ([unique_neg], through
    [ginv_unique_l]).  Every [ginv] identity used here is obtained by
    exhibiting a one-sided inverse, never by unfolding the choice, which is
    Structure/Groupoid.v's discipline.

    THE CORRESPONDENCE RUNS BOTH WAYS, with both round trips proved.
    [fg_restrict] restricts a functor along the unit; [fg_extend_restrict]
    shows that extending a quiver homomorphism and then restricting recovers
    it, as an equality in [QuiverCategory]; and [fg_restrict_recovers_strict]
    shows that restricting a functor and then extending recovers it at
    STRICT strength, an equality of functors in [StrictCat].  What is NOT
    claimed is a bijection of the underlying TYPES: both round trips are up
    to the respective hom-setoid equivalences, and respectfulness of the two
    maps is not established, so they do not descend to a bijection of the
    setoid quotients either.  That is the same honest scoping
    Theory/Diagram.v applies to its free-category bridge.

    NON-VACUITY IS PROVED, NOT GESTURED AT.  The quotient is necessary:
    [free_signed_not_groupoid] shows that as soon as the quiver has one edge
    the free CATEGORY on the signed quiver fails to be a groupoid, and
    [free_signed_no_cancellation] refutes the cancellation equation there by
    a path-length argument, whence [fg_proj_not_faithful].  The quotient
    also does not collapse: over the quiver with one node and one loop, the
    generator is provably NOT the identity ([loop_generator_not_identity]),
    separated by a functor into the delooping of Z/2.  The nonabelian
    witness lives one door down, in [Instance/Grp/Free.v].

    PRIOR ART, measured against the tree at the time of writing.  The names
    [FreeGroupoid], [FreeGrp], [FreeGroup], [free_groupoid], [free_group]
    and [ReducedWord] occurred in zero files.  "free group" occurred as
    PROSE in four places — Theory/Universal/Arrow.v:39 and :45,
    Instance/Grp.v:137, Structure/Terminal.v:38 — and nowhere as a
    construction.  Nothing in tree formed a formal inverse of a free arrow:
    Construction/Free/Quiver.v's syntactic [Mor] has [Ident], [Morph] and
    [Comp] and no inverse constructor; Construction/Groupoid.v discards
    non-invertible arrows rather than adjoining inverses; and
    Construction/Localization.v inverts a [MorphismClass], but through a
    reflective subcategory, with no formal-inverse syntax.

    WHAT IS NOT DELIVERED, and why.

      - No adjunction at the quiver level.  There is no category of
        groupoids in tree — Construction/Groupoid.v builds the core of one
        category, not a category of them — so "free ⊣ forgetful for
        groupoids" cannot be STATED here, only its universal property, which
        is what [free_groupoid_universal] is.  The adjunction the issue asks
        for is delivered in [Instance/Grp/Free.v], over [Grp], which does
        exist.  Consequently [FreeGroupoid] is also not exhibited as a
        functor out of [QuiverCategory].
      - No normal form.  Words are not reduced; two words are equal exactly
        when the generated congruence says so, and no decision procedure is
        offered.  Every negative statement below is therefore proved by
        mapping into a concrete groupoid or by a path-length invariant, not
        by normalizing.  In particular the word problem, Nielsen-Schreier,
        and freeness of subgroupoids are all out of scope.
      - No comparison with Construction/Localization.v, which universally
        inverts a class of morphisms in an existing category rather than
        building a free one. *)

Section SignedQuiver.

Universes o h p.
Context (G : Quiver@{o h p}).

(** ** The signed quiver

    Adjoin to every edge a formal inverse: an edge of [SignedQuiver G] from
    [x] to [y] is either an edge of [G] from [x] to [y] or an edge of [G]
    from [y] to [x], read backwards. *)
Definition sedge (x y : G) : Type@{h} := (edges x y + edges y x)%type.

Definition sedge_equiv {x y : G} (a b : sedge x y) : Type@{p} :=
  match a, b with
  | inl e, inl e' => e ≈ e'
  | inr e, inr e' => e ≈ e'
  | _, _ => False
  end.

Definition sedge_equivalence (x y : G) : Equivalence (@sedge_equiv x y).
Proof.
  constructor.
  - intros [e|e]; simpl; reflexivity.
  - intros [e|e] [e'|e'] H; simpl in *;
      solve [ contradiction | now symmetry ].
  - intros [e|e] [e'|e'] [e''|e''] H1 H2; simpl in *;
      solve [ contradiction | now transitivity e' ].
Defined.

Definition SignedQuiver : Quiver@{o h p} := {|
  nodes   := @nodes G;
  edges   := sedge;
  edgeset := fun x y => {| equiv        := @sedge_equiv x y;
                           setoid_equiv := sedge_equivalence x y |}
|}.

(** Flipping the sign of an edge.  This is [Lib/TList.v]'s edge-flipping
    operation, and it is involutive ON THE NOSE — the sum swap needs no
    proof beyond a case split, which is exactly the hypothesis
    [tlist_rev_involutive] consumes. *)
Definition sflip (x y : G) (a : sedge x y) : sedge y x :=
  match a with
  | inl e => inr e
  | inr e => inl e
  end.

Lemma sflip_involutive (x y : G) (a : sedge x y) :
  sflip y x (sflip x y a) = a.
Proof. now destruct a. Qed.

(** ** Words in the edges and their formal inverses

    A morphism of the free category on the signed quiver is a path of signed
    edges: a WORD.  Composition is concatenation (in the flipped order
    [FreeOnQuiver] uses), the identity is the empty word. *)
Definition FreeSigned : Category@{o h p} := FreeOnQuiver SignedQuiver.

(** A generator, positive and negative. *)
Definition spos {x y : G} (e : edges x y) : x ~{FreeSigned}~> y :=
  tlist_singleton (B:=@edges SignedQuiver) (inl e).

Definition sneg {x y : G} (e : edges x y) : y ~{FreeSigned}~> x :=
  tlist_singleton (B:=@edges SignedQuiver) (inr e).

(** ** The cancellation relations

    Exactly two generating equations, one for each side.  Everything else a
    congruence needs — reflexivity, symmetry, transitivity, compatibility
    with composition, and containment of the ambient [≈] — is supplied by
    [CongClosure] ([Construction/Quotient.v]), so no bespoke inductive
    congruence is written here.

    The relation is [Type]-valued because [HomRelT] is, and [HomRelT] is
    because [≈] is a [crelation]; see [Construction/Quotient.v]'s subsection
    on the generated congruence for why a [Prop] family cannot serve. *)
Inductive FreeGroupoidRel : ∀ x y : FreeSigned,
    (x ~{FreeSigned}~> y) → (x ~{FreeSigned}~> y) → Type :=
  | fgr_left  {x y : G} (e : edges x y) :
      FreeGroupoidRel x x (sneg e ∘ spos e) id
  | fgr_right {x y : G} (e : edges x y) :
      FreeGroupoidRel y y (spos e ∘ sneg e) id.

(** ** The free groupoid *)
Definition FreeGroupoid : Category@{o h p} :=
  QuotientCong FreeSigned FreeGroupoidRel.

(** The projection from words to their classes. *)
Definition FreeGroupoidProj : FreeSigned ⟶ FreeGroupoid :=
  QuotientCongProj FreeGroupoidRel.

(** A signed generator, read as a morphism of the free groupoid. *)
Definition fgen {x y : G} (a : @edges SignedQuiver x y)
  : x ~{FreeGroupoid}~> y := tlist_singleton a.

(** A positive generator, i.e. the image of an edge of [G]. *)
Definition fgpos {x y : G} (e : edges x y) : x ~{FreeGroupoid}~> y :=
  fgen (inl e).

(** ...and a negative one. *)
Definition fgneg {x y : G} (e : edges x y) : y ~{FreeGroupoid}~> x :=
  fgen (inr e).

(** The two imposed equations, holding in the free groupoid. *)
Lemma fg_cancel_left {x y : G} (e : edges x y) :
  fgneg e ∘ fgpos e ≈ @id FreeGroupoid x.
Proof. exact (cc_gen (fgr_left e)). Qed.

Lemma fg_cancel_right {x y : G} (e : edges x y) :
  fgpos e ∘ fgneg e ≈ @id FreeGroupoid y.
Proof. exact (cc_gen (fgr_right e)). Qed.

(** Both at once, for an arbitrary SIGNED generator: the flip of a generator
    is a left inverse of it.  The case split is on the sign, and each branch
    is one of the two imposed equations. *)
Lemma fgen_flip_left {x y : G} (a : @edges SignedQuiver x y) :
  fgen (sflip x y a) ∘ fgen a ≈ @id FreeGroupoid x.
Proof.
  destruct a as [e|e].
  - exact (fg_cancel_left e).
  - exact (fg_cancel_right e).
Qed.

(** ** Inversion of a word

    [Lib/TList.v]'s [tlist_rev], parameterized by an edge-flipping operation,
    is exactly the reversal a groupoid needs, and it was previously used
    nowhere in the tree.  Its [tlist_rev_app_distr] IS the anti-homomorphism
    law (g ∘ f)⁻¹ = f⁻¹ ∘ g⁻¹ — modulo [FreeOnQuiver]'s composition being
    [g +++ f] — and it holds at Leibniz [=], which is stronger than the [≈]
    the quotient needs. *)
Definition fginv {x y : G} (f : x ~{FreeGroupoid}~> y)
  : y ~{FreeGroupoid}~> x := tlist_rev sflip f.

(** Inversion is involutive on the nose, before any quotient is taken. *)
Lemma fginv_involutive {x y : G} (f : x ~{FreeGroupoid}~> y) :
  fginv (fginv f) = f.
Proof. exact (tlist_rev_involutive sflip sflip_involutive f). Qed.

(** The anti-homomorphism law, likewise at Leibniz [=]. *)
Lemma fginv_compose {x y z : G}
  (f : y ~{FreeGroupoid}~> z) (g : x ~{FreeGroupoid}~> y) :
  fginv (f ∘ g) = fginv g ∘ fginv f.
Proof. exact (tlist_rev_app_distr sflip g f). Qed.

(** Reversing a one-letter word flips its sign, again at Leibniz [=]. *)
Lemma fginv_gen {x y : G} (a : @edges SignedQuiver x y) :
  fginv (fgen a) = fgen (sflip x y a).
Proof.
  unfold fginv, fgen, tlist_singleton.
  rewrite tlist_rev_equation_2, tlist_rev_equation_1.
  now rewrite tlist_app_tnil_l.
Qed.

(** A word composed with its reversal is the empty word, in the quotient.
    The induction peels one letter at a time; the base case is the empty
    word and the step case is [fgen_flip_left] under the induction
    hypothesis. *)
Lemma fginv_left {x y : G} (f : x ~{FreeGroupoid}~> y) :
  fginv f ∘ f ≈ @id FreeGroupoid x.
Proof.
  induction f.
  - transitivity (@compose FreeGroupoid y y y id id).
    + apply compose_respects; [ | reflexivity ].
      unfold fginv; rewrite tlist_rev_equation_1; reflexivity.
    + apply id_left.
  - rewrite (tlist_app_cons b f).
    change ((b ::: tnil) +++ f)
      with (@compose FreeGroupoid i j y f (fgen b)).
    rewrite fginv_compose, fginv_gen.
    rewrite <- comp_assoc, (comp_assoc (fginv f) f (fgen b)).
    rewrite IHf, id_left.
    apply fgen_flip_left.
Qed.

(** ...and on the other side, by applying the previous lemma at [fginv f]
    and using involutivity.  No second induction. *)
Lemma fginv_right {x y : G} (f : x ~{FreeGroupoid}~> y) :
  f ∘ fginv f ≈ @id FreeGroupoid y.
Proof.
  transitivity (@compose FreeGroupoid y x y (fginv (fginv f)) (fginv f)).
  - apply compose_respects; [ | reflexivity ].
    now rewrite fginv_involutive.
  - apply fginv_left.
Qed.

(** ** Deliverable 1: the free groupoid IS a groupoid

    [IsGroupoid] ([Structure/Groupoid.v]) is the PREDICATE — every morphism
    has a two-sided inverse — and is what "the free groupoid" must satisfy.
    It is deliberately not a [Class] and is never registered for resolution,
    so it is passed explicitly at every use site below. *)
Definition FreeGroupoid_IsGroupoid : IsGroupoid FreeGroupoid :=
  fun x y f =>
    {| two_sided_inverse := fginv f;
       is_right_inverse  := fginv_right f;
       is_left_inverse   := fginv_left f |}.

(** The chosen inverse of [Structure/Groupoid.v]'s [ginv] IS word reversal,
    definitionally: [ginv] projects [two_sided_inverse] out of the record
    just built. *)
Example fg_ginv_is_reversal {x y : G} (f : x ~{FreeGroupoid}~> y) :
  ginv FreeGroupoid_IsGroupoid f = fginv f := eq_refl.

(** ** The unit: a quiver homomorphism into the underlying quiver *)

Definition FreeGroupoidUnit
  : QuiverHomomorphism G (QuiverOfCat FreeGroupoid).
Proof.
  unshelve eapply Build_QuiverHomomorphism.
  - exact Datatypes.id.
  - exact (fun x y e => fgpos e).
  - intros x y e e' He.
    apply cc_equiv.
    unfold fgpos, fgen, tlist_singleton; simpl.
    exists eq_refl; [ exact He | reflexivity ].
Defined.

(** ** Deliverable 2: the universal property

    Mac Lane §II.7 Ex. 3 and Riehl §4.2 Example 4: a quiver homomorphism
    from [G] into (the underlying quiver of) a GROUPOID extends to a functor
    out of the free groupoid, uniquely. *)

Section FreeGroupoidUMP.

Context {D : Category}.
Context (Dg : IsGroupoid D).
Context (F : QuiverHomomorphism G (QuiverOfCat D)).

(** The signed extension of [F]: a positive edge goes where [F] sends it, a
    negative edge to the INVERSE of where [F] sends it.  This is the only
    place the groupoid hypothesis on [D] is used to build anything. *)
Definition signed_hom : QuiverHomomorphism SignedQuiver (QuiverOfCat D).
Proof using D Dg F G.
  unshelve eapply Build_QuiverHomomorphism.
  - exact (@fnodes _ _ F).
  - intros x y a.
    exact (match a with
           | inl e => @fedgemap _ _ F x y e
           | inr e => ginv Dg (@fedgemap _ _ F y x e)
           end).
  - intros x y [e|e] [e'|e'] Ha; simpl in Ha;
      solve [ contradiction
            | now apply (@fedgemap_respects _ _ F)
            | now rewrite (@fedgemap_respects _ _ F _ _ _ _ Ha) ].
Defined.

(** The functor out of the free CATEGORY on the signed quiver. *)
Definition signed_functor : FreeSigned ⟶ D :=
  InducedFunctor SignedQuiver signed_hom.

(** On a one-letter word it is the signed extension.  (The [id_left] is the
    path fold's trailing identity on a singleton path.) *)
Lemma signed_functor_gen {x y : G} (a : @edges SignedQuiver x y) :
  fmap[signed_functor] (tlist_singleton a)
    ≈ @fedgemap _ _ signed_hom x y a.
Proof. simpl; now rewrite id_left. Qed.

(** It merges the cancellation relations — this is the hypothesis
    [QuotientCongLift] consumes, and [cc_kernel] extends it to the whole
    generated congruence with no second induction. *)
Lemma signed_functor_merges :
  ∀ x y (f g : x ~{FreeSigned}~> y), FreeGroupoidRel x y f g →
    fmap[signed_functor] f ≈ fmap[signed_functor] g.
Proof.
  intros x y f g Hr; destruct Hr as [x' y' e|x' y' e];
    rewrite fmap_comp, fmap_id;
    unfold spos, sneg;
    rewrite !signed_functor_gen; simpl.
  - apply (ginv_left Dg).
  - apply (ginv_right Dg).
Qed.

(** The induced functor out of the free groupoid. *)
Definition FreeGroupoidFunctor : FreeGroupoid ⟶ D :=
  QuotientCongLift FreeGroupoidRel signed_functor signed_functor_merges.

(** It agrees with [F] on nodes, on the nose... *)
Lemma FreeGroupoidFunctor_obj (x : G) :
  fobj[FreeGroupoidFunctor] x = @fnodes _ _ F x.
Proof. reflexivity. Qed.

(** ...and on the generating edges, up to [≈]. *)
Lemma FreeGroupoidFunctor_gen {x y : G} (e : edges x y) :
  fmap[FreeGroupoidFunctor] (fgpos e) ≈ @fedgemap _ _ F x y e.
Proof. exact (signed_functor_gen (inl e)). Qed.

(** The negative generators are forced: their images are the inverses. *)
Lemma FreeGroupoidFunctor_neg {x y : G} (e : edges x y) :
  fmap[FreeGroupoidFunctor] (fgneg e) ≈ ginv Dg (@fedgemap _ _ F x y e).
Proof. exact (signed_functor_gen (inr e)). Qed.

(** *** Uniqueness

    Stated at STRICT strength, in the shape [Construction/Quotient.v]'s
    [strict_of_hom_cast] converts to an equality of functors in [StrictCat]:
    Leibniz equality on objects, and a [hom_cast] conjugation along it on
    morphisms.

    The hypothesis constrains a competitor ONLY on the POSITIVE generators —
    the images of the edges of [G] — which is what makes this the universal
    property of the free groupoid rather than of the free category on the
    signed quiver.  The negative generators are then forced, because a
    functor carries the imposed cancellation equations to genuine inverse
    equations in [D], and inverses are unique. *)

Section Unique.

Context (K : FreeGroupoid ⟶ D).
Context (Hobj : ∀ x : G, fobj[K] x = @fnodes _ _ F x).
Context (Hgen : ∀ (x y : G) (e : edges x y),
            hom_cast (Hobj x) (Hobj y) (fmap[K] (fgpos e))
              ≈ @fedgemap _ _ F x y e).

(** The forced clause: a competitor's action on a negative generator is the
    inverse of its action on the corresponding positive one, hence — by
    [Hgen] and uniqueness of inverses — the inverse of [F e]. *)
Lemma unique_neg {x y : G} (e : edges x y) :
  hom_cast (Hobj y) (Hobj x) (fmap[K] (fgneg e))
    ≈ ginv Dg (@fedgemap _ _ F x y e).
Proof using D Dg F G Hgen Hobj K.
  symmetry.
  apply (ginv_unique_l Dg).
  rewrite <- (Hgen x y e).
  rewrite (hom_cast_comp (Hobj x) (Hobj y) (Hobj x)).
  rewrite <- fmap_comp.
  rewrite (fg_cancel_left e).
  rewrite fmap_id.
  apply hom_cast_id.
Qed.

(** The same for a signed generator of either sign. *)
Lemma unique_gen {x y : G} (a : @edges SignedQuiver x y) :
  hom_cast (Hobj x) (Hobj y) (fmap[K] (fgen a))
    ≈ @fedgemap _ _ signed_hom x y a.
Proof using D Dg F G Hgen Hobj K.
  destruct a as [e|e].
  - exact (Hgen x y e).
  - exact (unique_neg e).
Qed.

(** Uniqueness on every word, by the path induction of
    [Construction/Free/Quiver/Presented.v]'s [PresentedFunctor_unique]. *)
Lemma FreeGroupoidFunctor_unique :
  ∀ (x y : G) (f : x ~{FreeGroupoid}~> y),
    hom_cast (Hobj x) (Hobj y) (fmap[K] f) ≈ fmap[FreeGroupoidFunctor] f.
Proof using D Dg F G Hgen Hobj K.
  intros x y f.
  induction f.
  - change (@tnil _ _ y) with (@id FreeGroupoid y).
    rewrite fmap_id; simpl; rewrite hom_cast_id.
    reflexivity.
  - assert (RW : @equiv _ (@homset FreeGroupoid i y) (b ::: f)
                   (@compose FreeGroupoid i j y f (fgen b))).
    { apply cc_equiv; unfold fgen, tlist_singleton; simpl.
      now rewrite <- tlist_app_cons. }
    rewrite RW, fmap_comp.
    rewrite <- (hom_cast_comp (Hobj i) (Hobj j) (Hobj y)).
    rewrite IHf, unique_gen.
    rewrite fmap_comp.
    apply compose_respects; [ reflexivity | ].
    symmetry; exact (signed_functor_gen b).
Qed.

End Unique.

End FreeGroupoidUMP.

End SignedQuiver.

Arguments sedge G x y : assert.
Arguments SignedQuiver G : assert.
Arguments FreeSigned G : assert.
Arguments FreeGroupoid G : assert.
Arguments spos {G x y} e.
Arguments sneg {G x y} e.
Arguments fgen {G x y} a.
Arguments fgpos {G x y} e.
Arguments fgneg {G x y} e.
Arguments fginv {G x y} f.
Arguments fg_cancel_left {G x y} e.
Arguments fg_cancel_right {G x y} e.
Arguments fgen_flip_left {G x y} a.
Arguments fginv_involutive {G x y} f.
Arguments fginv_compose {G x y z} f g.
Arguments fginv_gen {G x y} a.
Arguments fginv_left {G x y} f.
Arguments fginv_right {G x y} f.
Arguments sflip_involutive {G} x y a.

(** ** The universal property, bundled

    Riehl §4.2 Example 4 and Mac Lane §II.7 Ex. 3 in one statement.  The
    object agreement [Hobj] is nested INSIDE the bundle on purpose, exactly
    as in [Construction/Free/Quiver/Presented.v]'s [presented_universal]: a
    flat statement of the generator clause has no common hom, since for an
    abstract [K] the objects [fobj[K] x] and [@fnodes _ _ F x] are not
    convertible until [Hobj] is in scope.

    The generator clause constrains only the POSITIVE generators — the edges
    of [G] — which is what makes this the universal property of the free
    GROUPOID rather than of the free category on the signed quiver. *)

Section FreeGroupoidUniversal.

Context (G : Quiver) {D : Category}.
Context (Dg : IsGroupoid D).

Theorem free_groupoid_universal
  (F : QuiverHomomorphism G (QuiverOfCat D)) :
  { K : FreeGroupoid G ⟶ D &
  { Hobj : ∀ x : G, fobj[K] x = @fnodes _ _ F x &
    ((∀ (x y : G) (e : edges x y),
        hom_cast (Hobj x) (Hobj y) (fmap[K] (fgpos e))
          ≈ @fedgemap _ _ F x y e) *
     (∀ (K' : FreeGroupoid G ⟶ D)
        (Hobj' : ∀ x : G, fobj[K'] x = @fnodes _ _ F x),
        (∀ (x y : G) (e : edges x y),
           hom_cast (Hobj' x) (Hobj' y) (fmap[K'] (fgpos e))
             ≈ @fedgemap _ _ F x y e) →
        ∀ (x y : G) (f : x ~{FreeGroupoid G}~> y),
          hom_cast (Hobj' x) (Hobj' y) (fmap[K'] f)
            ≈ hom_cast (Hobj x) (Hobj y) (fmap[K] f)))%type } }.
Proof using D Dg G.
  exists (FreeGroupoidFunctor G Dg F), (fun _ => eq_refl).
  split.
  - intros x y e. exact (FreeGroupoidFunctor_gen G Dg F e).
  - intros K' Hobj' Hgen x y f.
    exact (FreeGroupoidFunctor_unique G Dg F K' Hobj' Hgen x y f).
Qed.

End FreeGroupoidUniversal.

(** ** The converse leg

    Restricting a functor out of the free groupoid along the unit gives back
    a quiver homomorphism, and re-extending recovers the functor.  This is
    what makes Riehl's "exactly" honest in both directions. *)

Definition fg_restrict {G : Quiver} {D : Category} (S : FreeGroupoid G ⟶ D)
  : QuiverHomomorphism G (QuiverOfCat D) :=
  QuiverComp (FreeGroupoidUnit G) (QuiverHomomorphismOfFunctor _ _ S).

(** On generators the restriction is [S] itself, definitionally — a Leibniz
    equality of morphisms, stated at that strength deliberately, in the
    manner of [QuotientLift_proj] ([Construction/Quotient.v]). *)
Lemma fg_restrict_gen {G : Quiver} {D : Category} (S : FreeGroupoid G ⟶ D)
  {x y : G} (e : edges x y) :
  @fedgemap _ _ (fg_restrict S) x y e = fmap[S] (fgpos e).
Proof. reflexivity. Qed.

(** ...and the restriction re-extends to [S] on every word. *)
Lemma fg_restrict_recovers {G : Quiver} {D : Category} (Dg : IsGroupoid D)
  (S : FreeGroupoid G ⟶ D) (x y : G) (f : x ~{FreeGroupoid G}~> y) :
  fmap[S] f ≈ fmap[FreeGroupoidFunctor G Dg (fg_restrict S)] f.
Proof.
  refine (FreeGroupoidFunctor_unique G Dg (fg_restrict S) S
            (fun _ => eq_refl) _ x y f).
  intros a b e; reflexivity.
Qed.

(** The round trip at STRICT strength: an equality of functors in
    [StrictCat], via [Construction/Quotient.v]'s [strict_of_hom_cast]. *)
Lemma fg_restrict_recovers_strict {G : Quiver} {D : Category}
  (Dg : IsGroupoid D) (S : FreeGroupoid G ⟶ D) :
  @equiv _ (@Functor_StrictEq_Setoid (FreeGroupoid G) D)
    S (FreeGroupoidFunctor G Dg (fg_restrict S)).
Proof.
  apply (strict_of_hom_cast S (FreeGroupoidFunctor G Dg (fg_restrict S))
           (fun _ => eq_refl)).
  intros x y f.
  exact (fg_restrict_recovers Dg S x y f).
Qed.

(** ...and the OTHER round trip: extending a quiver homomorphism and then
    restricting recovers it, as an equality in [QuiverCategory].  The two
    together make the correspondence run both ways with both round trips
    proved, which is what "exactly" has to mean. *)
Lemma fg_extend_restrict {G : Quiver} {D : Category} (Dg : IsGroupoid D)
  (F : QuiverHomomorphism G (QuiverOfCat D)) :
  @equiv _ (@homset QuiverCategory G (QuiverOfCat D))
    (fg_restrict (FreeGroupoidFunctor G Dg F)) F.
Proof.
  exists (fun _ => eq_refl).
  intros x y e; simpl.
  exact (FreeGroupoidFunctor_gen G Dg F e).
Qed.

(** ** Equations merge, and never add

    The projection is the identity on objects and on morphisms; only the
    hom-setoid equivalence coarsens.  It is full, and — as the witnesses
    below show — deliberately NOT faithful. *)

Lemma fg_proj_obj {G : Quiver} (x : G) :
  fobj[FreeGroupoidProj G] x = x.
Proof. reflexivity. Qed.

Lemma fg_hom_type {G : Quiver} (x y : G) :
  (x ~{FreeGroupoid G}~> y) = (x ~{FreeSigned G}~> y).
Proof. reflexivity. Qed.

Definition FreeGroupoidProj_Full {G : Quiver} : Full (FreeGroupoidProj G) :=
  @QuotientProj_Full (FreeSigned G) (CongClosure (FreeGroupoidRel G))
    (CongClosure_Congruence (FreeGroupoidRel G)).

(** ** Non-vacuity

    The quotient genuinely does something, and it does not do everything.
    Both halves are proved, not asserted. *)

(** In the free CATEGORY on the signed quiver, the cancellation equation
    FAILS: a two-letter word is not the empty word, by the path-length
    invariant [tlist'_equiv_lengths] ([Construction/Free/Quiver.v]). *)
Theorem free_signed_no_cancellation {G : Quiver} {x y : G} (e : edges x y) :
  @equiv _ (@homset (FreeSigned G) x x) (sneg e ∘ spos e) id → False.
Proof.
  intro H.
  pose proof (tlist'_equiv_lengths (SignedQuiver G) x x x
                (spos e +++ sneg e) tnil eq_refl H) as Hl.
  unfold spos, sneg, tlist_singleton in Hl.
  rewrite tlist_app_length in Hl.
  simpl in Hl.
  discriminate.
Qed.

(** The quotient is NECESSARY, not a convenience: as soon as the quiver has
    an edge, the free CATEGORY on the signed quiver is not a groupoid.  Any
    left inverse of a one-letter word would compose with it to a word of
    length at least one, and the empty word has length zero. *)
Theorem free_signed_not_groupoid {G : Quiver} {x y : G} (e : edges x y) :
  IsGroupoid (FreeSigned G) → False.
Proof.
  intro Hg.
  pose proof (@is_left_inverse _ _ _ _ (Hg x y (spos e))) as Hinv.
  pose proof (tlist'_equiv_lengths (SignedQuiver G) x x x
                (spos e +++ @two_sided_inverse _ _ _ _ (Hg x y (spos e)))
                tnil eq_refl Hinv) as Hl.
  rewrite tlist_app_length in Hl.
  unfold spos, tlist_singleton in Hl.
  simpl in Hl.
  discriminate.
Qed.

(** Hence the projection is not faithful: it identifies the two-letter word
    with the empty one.  Fong and Spivak's "equations merge, but never add",
    with both halves in hand. *)
Theorem fg_proj_not_faithful {G : Quiver} {x y : G} (e : edges x y) :
  Faithful (FreeGroupoidProj G) → False.
Proof.
  intro HF.
  apply (free_signed_no_cancellation e).
  apply (@fmap_inj _ _ _ HF).
  exact (fg_cancel_left e).
Qed.

(** *** A generator that is provably not an identity

    The quotient does not collapse: over the quiver with one node and one
    loop, the generator stays apart from the identity.  The separating
    functor lands in the delooping of Z/2 ([Construction/Deloop.v]'s
    [Bool_Xor_Grp], a groupoid by [Structure/Groupoid.v]'s
    [deloop_bool_groupoid]). *)

(* NAME. This is [FGLoopQuiver] and not [LoopQuiver] because the tree already
   has TWO quivers by the latter name: [Theory/Diagram.v]'s (one node, one
   loop — differing from this one only in the node type) and
   [Construction/Free/Quiver/Concrete.v]'s (one node, TWO loops). Neither is
   imported here, so a third would not have conflicted today; it is renamed
   rather than merely disclosed because a silent shadow is exactly the hazard
   the two-[GrpObject] note above spends a paragraph on, and this file should
   not create the kind of collision it warns about. *)
Definition FGLoopQuiver : Quiver :=
  Build_Quiver_Standard_Eq poly_unit (fun _ _ => unit).

(** The loop, as a morphism of the free groupoid. *)
Definition loop_gen : ttt ~{FreeGroupoid FGLoopQuiver}~> ttt :=
  @fgpos FGLoopQuiver ttt ttt tt.

Definition loop_to_Z2
  : QuiverHomomorphism FGLoopQuiver (QuiverOfCat (Deloop Bool_Xor_Grp)).
Proof.
  unshelve eapply Build_QuiverHomomorphism.
  - exact (fun _ => ttt).
  - exact (fun _ _ _ => true).
  - intros a b u v Huv; reflexivity.
Defined.

Definition loop_Z2 : FreeGroupoid FGLoopQuiver ⟶ Deloop Bool_Xor_Grp :=
  FreeGroupoidFunctor FGLoopQuiver deloop_bool_groupoid loop_to_Z2.

Theorem loop_generator_not_identity :
  loop_gen ≈ @id (FreeGroupoid FGLoopQuiver) ttt → False.
Proof.
  intro H.
  assert (Hb : @equiv _ (@homset (Deloop Bool_Xor_Grp) ttt ttt)
                 (fmap[loop_Z2] loop_gen)
                 (fmap[loop_Z2] (@id (FreeGroupoid FGLoopQuiver) ttt)))
    by (now rewrite H).
  rewrite fmap_id in Hb.
  rewrite (FreeGroupoidFunctor_gen FGLoopQuiver deloop_bool_groupoid
             loop_to_Z2 (x:=ttt) (y:=ttt) tt) in Hb.
  simpl in Hb.
  discriminate.
Qed.

(** ...and it IS invertible, with the negative generator as its inverse —
    which is the whole point of passing to the groupoid. *)
Example loop_generator_invertible :
  ginv (FreeGroupoid_IsGroupoid FGLoopQuiver) loop_gen
    = @fgneg FGLoopQuiver ttt ttt tt.
Proof. reflexivity. Qed.
