Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Construction.Opposite.
Require Import Category.Structure.Pullback.
Require Import Category.Structure.Pushout.
Require Import Category.Instance.FinSet.

Require Import Coq.Vectors.Fin.
Require Import Coq.Arith.PeanoNat.
Require Import Coq.Lists.List.
Require Import Coq.Bool.Bool.
Require Import Coq.Logic.Eqdep_dec.

Generalizable All Variables.

(** * Pushouts in skeletal FinSet

    nLab:      https://ncatlab.org/nlab/show/pushout
    Wikipedia: https://en.wikipedia.org/wiki/Pushout_(category_theory)

    For a span [y <-f- x -g-> z] of finite sets, the pushout is the
    coproduct [y + z] modulo the least equivalence relation identifying
    [inl (f i)] with [inr (g i)] for every [i].  In the skeletal
    presentation of [Instance/FinSet.v] every object is a natural number,
    so the apex object must itself be a natural number: the count of the
    equivalence classes.  The construction therefore has genuine
    computational content beyond the setoid pushout of [Instance/Sets.v],
    where the apex carrier is simply the Coq sum type.  What is required
    here is the connected-components computation on the canonical
    [(y + z)]-element set, which this file performs by a union-find
    labeling.

    The equivalence generated by a finite set of edges on a finite
    carrier is the connected-components relation of the corresponding
    graph, and the union-find labeling that computes it is a classical
    device (Tarjan, "Efficiency of a Good But Not Linear Set Union
    Algorithm", Journal of the ACM 22, 1975).  The labeling maintained
    below assigns to each element a canonical representative of its class;
    processing an edge redirects one representative onto the other, and
    the fold over all edges yields an idempotent map whose fibres are
    exactly the classes.  The count of its fixed points is the apex, and
    the standard rank/unrank codec on a decidable predicate over [Fin.t]
    (the [fin_countP]/[fin_select]/[fin_rank] triple) supplies the
    order-preserving bijection between representatives and the canonical
    set of that size.

    This is the single instance the cospan hypergraph tower of
    [Construction/Cospan/] requires in order to be witnessed over a
    concrete category: with [FinSet_Cocartesian], [FinSet_Initial] and
    [FinSet_HasPushouts] in hand, [Cospan_Hypergraph] realizes the special
    commutative Frobenius structure of cospans of finite sets, the prop
    for that structure in the network-theory correspondence of Baez, Coya
    and Rebro ("Props in Network Theory", Theory and Applications of
    Categories 33, 2018), already discussed in the header of
    [Instance/FinSet.v].

    NOTE on names: [Structure/Cocartesian.v] (imported through [FinSet])
    defines [inl], [inr], [left] and [right] for the coproduct calculus,
    shadowing the sum-type constructors, which are therefore qualified
    [Datatypes.inl] and [Datatypes.inr] throughout this file, exactly as
    in [Instance/FinSet.v].

    NOTE on reuse: the rank/unrank codec below ([fin_eqb], [fin_countP],
    [fin_select], [fin_rank] with their laws) mirrors the codec proved for
    the subobject classifier in [Instance/FinSet/Classifier.v].  It is
    reproduced here rather than imported so that this pushout development
    depends only on [Instance/FinSet.v] and the standard library, and does
    not drag the subobject-classifier tower into its dependency cone. *)

(** ** The rank/unrank codec on a decidable predicate over [Fin.t]

    [fin_eqb] is a heterogeneous boolean equality; [fin_countP P] counts
    the elements satisfying a boolean predicate; [fin_select] tabulates
    the satisfying elements in order (unrank), and [fin_rank] sends a
    satisfying element to its index.  These are the structural fixpoints
    of [Instance/FinSet/Classifier.v]. *)

Fixpoint fin_eqb {m n : nat} (i : Fin.t m) (j : Fin.t n) : bool :=
  match i, j with
  | Fin.F1, Fin.F1 => true
  | Fin.FS i', Fin.FS j' => fin_eqb i' j'
  | _, _ => false
  end.

Lemma fin_eqb_refl {n : nat} (i : Fin.t n) : fin_eqb i i = true.
Proof. induction i; simpl; auto. Qed.

Lemma fin_eqb_eq {n : nat} (i j : Fin.t n) : fin_eqb i j = true → i = j.
Proof.
  revert j; induction i as [n' | n' i' IH]; intro j.
  - apply (Fin.caseS' j (fun j => fin_eqb Fin.F1 j = true → Fin.F1 = j)).
    + reflexivity.
    + intros j' H; discriminate H.
  - apply (Fin.caseS' j
             (fun j => fin_eqb (Fin.FS i') j = true → Fin.FS i' = j)).
    + intro H; discriminate H.
    + intros j' H; simpl in H.
      now rewrite (IH j' H).
Qed.

Fixpoint fin_countP {n : nat} : (Fin.t n → bool) → nat :=
  match n return (Fin.t n → bool) → nat with
  | O => fun _ => 0%nat
  | S n' => fun P =>
      ((if P Fin.F1 then 1 else 0) + fin_countP (fun i => P (Fin.FS i)))%nat
  end.

Fixpoint fin_select {n : nat} :
  ∀ P : Fin.t n → bool, Fin.t (fin_countP P) → Fin.t n :=
  match n return ∀ P : Fin.t n → bool, Fin.t (fin_countP P) → Fin.t n with
  | O => fun _ k => Fin.case0 (fun _ => Fin.t 0) k
  | S n' => fun P =>
      match P Fin.F1 as b return
        Fin.t ((if b then 1 else 0) + fin_countP (fun i => P (Fin.FS i)))%nat
          → Fin.t (S n')
      with
      | true => fun k =>
          match @fin_split 1 (fin_countP (fun i => P (Fin.FS i))) k with
          | Datatypes.inl _ => Fin.F1
          | Datatypes.inr k' =>
              Fin.FS (fin_select (fun i => P (Fin.FS i)) k')
          end
      | false => fun k => Fin.FS (fin_select (fun i => P (Fin.FS i)) k)
      end
  end.

Fixpoint fin_rank {n : nat} :
  ∀ (P : Fin.t n → bool) (i : Fin.t n), P i = true → Fin.t (fin_countP P) :=
  match n return
    ∀ (P : Fin.t n → bool) (i : Fin.t n), P i = true → Fin.t (fin_countP P)
  with
  | O => fun P i => Fin.case0 (fun i => P i = true → Fin.t (fin_countP P)) i
  | S n' => fun P i =>
      Fin.caseS' i (fun i => P i = true → Fin.t (fin_countP P))
        (fun H =>
           match P Fin.F1 as b return
             P Fin.F1 = b →
             Fin.t ((if b then 1 else 0)
                    + fin_countP (fun j => P (Fin.FS j)))%nat
           with
           | true => fun _ => Fin.F1
           | false => fun E =>
               match eq_trans (eq_sym H) E in _ = y
                 return (if y then True
                         else Fin.t (fin_countP (fun j => P (Fin.FS j))))
               with eq_refl => I end
           end eq_refl)
        (fun i' (H : P (Fin.FS i') = true) =>
           match P Fin.F1 as b return
             Fin.t ((if b then 1 else 0)
                    + fin_countP (fun j => P (Fin.FS j)))%nat
           with
           | true => Fin.R 1 (fin_rank (fun j => P (Fin.FS j)) i' H)
           | false => fin_rank (fun j => P (Fin.FS j)) i' H
           end)
  end.

Lemma fin_select_sat {n : nat} (P : Fin.t n → bool)
      (k : Fin.t (fin_countP P)) :
  P (fin_select P k) = true.
Proof.
  revert P k; induction n as [| n' IH]; intros P k.
  - exact (Fin.case0 (fun k : Fin.t 0 => _) k).
  - revert k; simpl; destruct (P Fin.F1) eqn:E; intro k.
    + pattern k; apply (Fin.caseS' k); simpl.
      * exact E.
      * intro k'; apply (IH (fun i => P (Fin.FS i)) k').
    + apply (IH (fun i => P (Fin.FS i)) k).
Qed.

Lemma fin_select_rank {n : nat} (P : Fin.t n → bool) (i : Fin.t n)
      (H : P i = true) :
  fin_select P (fin_rank P i H) = i.
Proof.
  revert P i H; induction n as [| n' IH]; intros P i.
  - exact (Fin.case0
             (fun i => ∀ H : P i = true, fin_select P (fin_rank P i H) = i)
             i).
  - apply (Fin.caseS' i
             (fun i => ∀ H : P i = true,
                fin_select P (fin_rank P i H) = i)).
    + simpl; destruct (P Fin.F1) eqn:E; intro H.
      * reflexivity.
      * discriminate H.
    + intro i'; simpl; destruct (P Fin.F1) eqn:E; intro H; simpl.
      * now rewrite (IH (fun j => P (Fin.FS j)) i' H).
      * now rewrite (IH (fun j => P (Fin.FS j)) i' H).
Qed.

(* [Fin.FS] is injective, by applying the evident retraction (with default
   [d] at [Fin.F1]) to the equation. *)
Definition fin_pred {n : nat} (d : Fin.t n) (i : Fin.t (S n)) : Fin.t n :=
  Fin.caseS' i (fun _ => Fin.t n) d (fun j => j).

Lemma fin_FS_inj {n : nat} (x y : Fin.t n) : Fin.FS x = Fin.FS y → x = y.
Proof. intro H; exact (f_equal (fin_pred x) H). Qed.

Lemma fin_select_inj {n : nat} (P : Fin.t n → bool)
      (a b : Fin.t (fin_countP P)) :
  fin_select P a = fin_select P b → a = b.
Proof.
  revert P a b; induction n as [| n' IH]; intros P a b.
  - exact (Fin.case0 (fun a : Fin.t 0 => _) a).
  - revert a b; simpl; destruct (P Fin.F1) eqn:E; intros a b.
    + pattern a; apply (Fin.caseS' a); [| intro a'];
        (pattern b; apply (Fin.caseS' b); [| intro b']); simpl;
        intro Heq.
      * reflexivity.
      * discriminate Heq.
      * discriminate Heq.
      * apply fin_FS_inj in Heq.
        now rewrite (IH (fun i => P (Fin.FS i)) a' b' Heq).
    + intro Heq; apply fin_FS_inj in Heq.
      apply (IH (fun i => P (Fin.FS i)) a b Heq).
Qed.

(** The two derived codec laws this development needs: ranking after
    selecting recovers the index ([fin_rank_select], from injectivity of
    selection), and [fin_rank] depends only on the ranked element, not on
    the proof that it is satisfying ([fin_rank_resp], from decidable
    equality of booleans, hence axiom-free). *)

Lemma fin_rank_select {n : nat} (P : Fin.t n → bool)
      (k : Fin.t (fin_countP P)) (H : P (fin_select P k) = true) :
  fin_rank P (fin_select P k) H = k.
Proof.
  apply fin_select_inj. rewrite fin_select_rank. reflexivity.
Qed.

Lemma fin_rank_resp {n : nat} (P : Fin.t n → bool) (i j : Fin.t n)
      (E : i = j) (Hi : P i = true) (Hj : P j = true) :
  fin_rank P i Hi = fin_rank P j Hj.
Proof.
  revert Hi Hj. rewrite E. intros Hi Hj.
  now rewrite (UIP_dec Bool.bool_dec Hi Hj).
Qed.

(** ** Enumeration of the canonical finite set

    [all_fin n] lists every element of [Fin.t n]; completeness is all that
    is required below, so no order or duplicate-freeness is proved. *)

Fixpoint all_fin (n : nat) : list (Fin.t n) :=
  match n with
  | O => nil
  | S m => cons Fin.F1 (map Fin.FS (all_fin m))
  end.

Lemma In_all_fin {n : nat} (i : Fin.t n) : In i (all_fin n).
Proof.
  induction i as [m | m i IH]; simpl.
  - left; reflexivity.
  - right; apply in_map; exact IH.
Qed.

(** ** The union-find labeling

    Over a fixed carrier [Fin.t N], a labeling is a map
    [Fin.t N -> Fin.t N] sending each element to the current
    representative of its class.  [ustep l ab] processes one edge by
    redirecting every element currently labeled as [fst ab] onto the
    representative of [snd ab]; [components] folds this over a list of
    edges.  Starting from the identity labeling, the result is idempotent
    and its fibres are the connected components generated by the edges. *)

Section Components.

Context {N : nat}.

Definition ustep (l : Fin.t N → Fin.t N) (ab : Fin.t N * Fin.t N)
  : Fin.t N → Fin.t N :=
  fun p => if fin_eqb (l p) (l (fst ab)) then l (snd ab) else l p.

Fixpoint components (edges : list (Fin.t N * Fin.t N))
                    (l : Fin.t N → Fin.t N) : Fin.t N → Fin.t N :=
  match edges with
  | nil => l
  | cons ab rest => components rest (ustep l ab)
  end.

(** One step preserves idempotence of the labeling. *)
Lemma ustep_idem (l : Fin.t N → Fin.t N) (ab : Fin.t N * Fin.t N) :
  (∀ p, l (l p) = l p) →
  ∀ p, ustep l ab (ustep l ab p) = ustep l ab p.
Proof.
  intros Hl p.
  destruct (fin_eqb (l p) (l (fst ab))) eqn:E.
  - assert (Hp : ustep l ab p = l (snd ab))
      by (unfold ustep; rewrite E; reflexivity).
    rewrite Hp. unfold ustep. rewrite Hl.
    destruct (fin_eqb (l (snd ab)) (l (fst ab))); reflexivity.
  - assert (Hp : ustep l ab p = l p)
      by (unfold ustep; rewrite E; reflexivity).
    rewrite Hp. unfold ustep. rewrite Hl, E. reflexivity.
Qed.

(** The whole fold preserves idempotence. *)
Lemma components_idem (edges : list (Fin.t N * Fin.t N))
      (l : Fin.t N → Fin.t N) :
  (∀ p, l (l p) = l p) →
  ∀ p, components edges l (components edges l p) = components edges l p.
Proof.
  revert l; induction edges as [| ab rest IH]; intros l Hl; simpl.
  - exact Hl.
  - apply IH. apply ustep_idem. exact Hl.
Qed.

(** Elements sharing a current label keep sharing it under the fold. *)
Lemma components_congr (edges : list (Fin.t N * Fin.t N))
      (l : Fin.t N → Fin.t N) (p q : Fin.t N) :
  l p = l q → components edges l p = components edges l q.
Proof.
  revert l; induction edges as [| ab rest IH]; intros l H; simpl.
  - exact H.
  - apply IH. unfold ustep. rewrite H. reflexivity.
Qed.

(** Immediately after an edge is processed, its endpoints share a label. *)
Lemma ustep_equalizes (l : Fin.t N → Fin.t N) (ab : Fin.t N * Fin.t N) :
  ustep l ab (fst ab) = ustep l ab (snd ab).
Proof.
  unfold ustep. rewrite fin_eqb_refl.
  destruct (fin_eqb (l (snd ab)) (l (fst ab))); reflexivity.
Qed.

(** Every edge in the list has its endpoints identified by the fold. *)
Lemma components_edge_eq (edges : list (Fin.t N * Fin.t N))
      (l : Fin.t N → Fin.t N) (e : Fin.t N * Fin.t N) :
  In e edges →
  components edges l (fst e) = components edges l (snd e).
Proof.
  revert l; induction edges as [| ab rest IH]; intros l Hin.
  - destruct Hin.
  - destruct Hin as [Heq | Hin].
    + subst e; simpl. apply components_congr. apply ustep_equalizes.
    + simpl. apply IH. exact Hin.
Qed.

(** A map [h] agreeing on the endpoints of one edge is unchanged by the
    corresponding step; below this is used with the copairing of the
    competing cocone. *)
Lemma ustep_resp {X : Type} (h : Fin.t N → X)
      (l : Fin.t N → Fin.t N) (ab : Fin.t N * Fin.t N) :
  (∀ p, h (l p) = h p) →
  h (fst ab) = h (snd ab) →
  ∀ p, h (ustep l ab p) = h p.
Proof.
  intros Hl Hab p.
  destruct (fin_eqb (l p) (l (fst ab))) eqn:E.
  - assert (Hp : ustep l ab p = l (snd ab))
      by (unfold ustep; rewrite E; reflexivity).
    rewrite Hp. apply fin_eqb_eq in E.
    rewrite (Hl (snd ab)), <- Hab, <- (Hl (fst ab)), <- E. apply Hl.
  - assert (Hp : ustep l ab p = l p)
      by (unfold ustep; rewrite E; reflexivity).
    rewrite Hp. apply Hl.
Qed.

(** A map agreeing on the endpoints of every edge factors through the
    labeling: it takes the same value on an element and on the
    representative the fold assigns to it. *)
Lemma components_resp {X : Type} (h : Fin.t N → X)
      (edges : list (Fin.t N * Fin.t N)) (l : Fin.t N → Fin.t N) :
  (∀ e, In e edges → h (fst e) = h (snd e)) →
  (∀ p, h (l p) = h p) →
  ∀ p, h (components edges l p) = h p.
Proof.
  revert l; induction edges as [| ab rest IH]; intros l Hedges Hl p; simpl.
  - apply Hl.
  - apply IH.
    + intros e He. apply Hedges. right. exact He.
    + apply ustep_resp.
      * exact Hl.
      * apply Hedges. left. reflexivity.
Qed.

End Components.

(** ** The pushout of a span, built from the labeling *)

Section PushoutBuild.

Context {x y z : nat}.
Context (f : Fin.t x → Fin.t y) (g : Fin.t x → Fin.t z).

(** The two endpoints of the edge contributed by index [i]: the [f]-image
    injected on the left and the [g]-image injected on the right of the
    coproduct [y + z]. *)
Definition po_src (i : Fin.t x) : Fin.t (y + z) :=
  fin_join (Datatypes.inl (f i)).
Definition po_dst (i : Fin.t x) : Fin.t (y + z) :=
  fin_join (Datatypes.inr (g i)).

Definition po_edges : list (Fin.t (y + z) * Fin.t (y + z)) :=
  map (fun i => (po_src i, po_dst i)) (all_fin x).

(** The connected-components labeling and its representative predicate. *)
Definition po_lab : Fin.t (y + z) → Fin.t (y + z) :=
  components po_edges (fun p => p).

Definition po_isrep (p : Fin.t (y + z)) : bool := fin_eqb (po_lab p) p.

(** The apex object: the number of representatives, that is, the number
    of connected components. *)
Definition po_apex : nat := fin_countP po_isrep.

Lemma po_lab_idem : ∀ p, po_lab (po_lab p) = po_lab p.
Proof.
  unfold po_lab. apply components_idem. intros p; reflexivity.
Qed.

Lemma po_isrep_lab : ∀ p, po_isrep (po_lab p) = true.
Proof.
  intro p. unfold po_isrep. rewrite po_lab_idem. apply fin_eqb_refl.
Qed.

(** The class map sends an element to the index of its representative
    among the representatives. *)
Definition po_cls (p : Fin.t (y + z)) : Fin.t po_apex :=
  fin_rank po_isrep (po_lab p) (po_isrep_lab p).

(** The two pushout injections, as class maps of the coproduct
    injections. *)
Definition po_in1 (i : Fin.t y) : Fin.t po_apex :=
  po_cls (fin_join (Datatypes.inl i)).
Definition po_in2 (j : Fin.t z) : Fin.t po_apex :=
  po_cls (fin_join (Datatypes.inr j)).

(** Elements with equal labels have equal classes. *)
Lemma po_cls_lab_eq (p q : Fin.t (y + z)) :
  po_lab p = po_lab q → po_cls p = po_cls q.
Proof.
  intro E. unfold po_cls. apply fin_rank_resp. exact E.
Qed.

(** Each representative is a fixed point of the labeling. *)
Lemma po_rep_fixed (k : Fin.t po_apex) :
  po_lab (fin_select po_isrep k) = fin_select po_isrep k.
Proof.
  apply fin_eqb_eq. exact (fin_select_sat po_isrep k).
Qed.

(** The chosen representative of a class is a section of the class map. *)
Lemma po_cls_rep (k : Fin.t po_apex) :
  po_cls (fin_select po_isrep k) = k.
Proof.
  unfold po_cls.
  rewrite (fin_rank_resp po_isrep
             (po_lab (fin_select po_isrep k)) (fin_select po_isrep k)
             (po_rep_fixed k)
             (po_isrep_lab (fin_select po_isrep k))
             (fin_select_sat po_isrep k)).
  apply fin_rank_select.
Qed.

(** The two coproduct injections cover the apex: every class is the class
    of a left or a right injection. *)
Lemma apex_cover (k : Fin.t po_apex) :
  (∃ b, k = po_in1 b) ∨ (∃ c, k = po_in2 c).
Proof.
  pose proof (po_cls_rep k) as Hk.
  destruct (fin_split (fin_select po_isrep k)) as [b | c] eqn:Hs.
  - left; exists b.
    transitivity (po_cls (fin_select po_isrep k)).
    + symmetry; exact Hk.
    + unfold po_in1. f_equal.
      rewrite <- (fin_join_split (fin_select po_isrep k)), Hs. reflexivity.
  - right; exists c.
    transitivity (po_cls (fin_select po_isrep k)).
    + symmetry; exact Hk.
    + unfold po_in2. f_equal.
      rewrite <- (fin_join_split (fin_select po_isrep k)), Hs. reflexivity.
Qed.

(** A map agreeing on the endpoints of every span edge factors through
    the labeling.  This is [components_resp] transported across the fact
    that [po_edges] enumerates exactly the span edges. *)
Lemma po_lab_resp {Q : nat} (h : Fin.t (y + z) → Fin.t Q)
      (Hh : ∀ i, h (po_src i) = h (po_dst i)) :
  ∀ p, h (po_lab p) = h p.
Proof.
  apply (components_resp h po_edges (fun p => p)).
  - intros e He. apply in_map_iff in He.
    destruct He as [i [Hi _]]. subst e. simpl. apply Hh.
  - intros p; reflexivity.
Qed.

(** The span edges receive equal labels, whence the pushout square
    commutes. *)
Lemma po_lab_edge (i : Fin.t x) : po_lab (po_src i) = po_lab (po_dst i).
Proof.
  exact (components_edge_eq po_edges (fun p => p) (po_src i, po_dst i)
           (in_map (fun i => (po_src i, po_dst i)) (all_fin x) i
              (In_all_fin i))).
Qed.

Lemma po_commutes (i : Fin.t x) : po_in1 (f i) = po_in2 (g i).
Proof.
  apply po_cls_lab_eq. apply po_lab_edge.
Qed.

End PushoutBuild.

(** ** The [HasPushouts FinSet] instance

    Each pushout is packaged as a [Pullback] in [FinSet^op], following the
    representation of [Structure/Pushout.v] and the [HasPushouts Sets]
    instance of [Instance/Sets/Pushout.v]. *)

Local Obligation Tactic := idtac.

#[export] Program Instance FinSet_HasPushouts : HasPushouts FinSet := {
  pushout := fun x y z f g =>
    {| Pull         := po_apex f g;
       pullback_fst := po_in1 f g;
       pullback_snd := po_in2 f g
    |}
}.
Next Obligation.
  (* The square commutes: the two injections agree on the span. *)
  intros x y z f g i.
  exact (po_commutes f g i).
Qed.
Next Obligation.
  (* The universal property.  Given a competing cocone (q1, q2) with
     q1 ∘ f ≈ q2 ∘ g, the copairing [Qof] of q1 and q2 factors through the
     labeling, and the mediator reads it off the chosen representative. *)
  intros x y z f g Q q1 q2 Hc.
  pose (Qof := fun p : Fin.t (y + z) =>
                 match @fin_split y z p with
                 | Datatypes.inl b => q1 b
                 | Datatypes.inr c => q2 c
                 end).
  (* [po_src] is discharged over [f] alone and [po_dst] over [g] alone,
     since each names a single leg of the span. *)
  assert (HQ : ∀ i : Fin.t x, Qof (po_src f i) = Qof (po_dst g i)).
  { intro i. unfold Qof, po_src, po_dst.
    rewrite !fin_split_join. exact (Hc i). }
  pose proof (po_lab_resp f g Qof HQ) as Qstar.
  pose (u := fun k : Fin.t (po_apex f g) =>
               Qof (fin_select (po_isrep f g) k)).
  assert (Hucls : ∀ w, u (po_cls f g w) = Qof w).
  { intro w. unfold u, po_cls. rewrite fin_select_rank. apply Qstar. }
  assert (Hu1 : ∀ b, u (po_in1 f g b) = q1 b).
  { intro b. unfold po_in1. rewrite Hucls. unfold Qof.
    rewrite fin_split_join. reflexivity. }
  assert (Hu2 : ∀ c, u (po_in2 f g c) = q2 c).
  { intro c. unfold po_in2. rewrite Hucls. unfold Qof.
    rewrite fin_split_join. reflexivity. }
  unshelve refine {| unique_obj := u |}.
  - split.
    + intro i. change (u (po_in1 f g i) = q1 i). exact (Hu1 i).
    + intro j. change (u (po_in2 f g j) = q2 j). exact (Hu2 j).
  - intros v [Hv1 Hv2] k.
    destruct (apex_cover f g k) as [[b Hb] | [c Hcc]].
    + subst k. change (u (po_in1 f g b) = v (po_in1 f g b)).
      rewrite (Hu1 b). symmetry. exact (Hv1 b).
    + subst k. change (u (po_in2 f g c) = v (po_in2 f g c)).
      rewrite (Hu2 c). symmetry. exact (Hv2 c).
Qed.
