Require Import Coq.ZArith.ZArith.

Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Isomorphism.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Adjunction.
Require Import Category.Theory.Universal.Arrow.
Require Import Category.Theory.Universal.Element.
Require Import Category.Functor.Hom.
Require Import Category.Functor.Representable.
Require Import Category.Construction.Elements.
Require Import Category.Theory.Algebra.Rig.
Require Import Category.Instance.Sets.
Require Import Category.Instance.Fun.
Require Import Category.Instance.CMon.
Require Import Category.Instance.Ab.
Require Import Category.Instance.Rng.
Require Import Category.Instance.Rng.Algebras.
Require Import Category.Instance.Rng.Polynomial.
Require Import Category.Instance.Rng.Algebras.Associative.
Require Import Category.Instance.Mod.

Generalizable All Variables.

#[local] Obligation Tactic := idtac.

(** * The tensor algebra and the exterior algebra as universal arrows

    Book: Mac Lane, "Categories for the Working Mathematician", 2nd ed.,
          GTM 5, §III.1, printed p. 59, Exercise 1 — the tensor algebra of
          a vector space and the exterior algebra, each to be exhibited as
          a universal arrow (maclane:III.1:ex1)
    Book: Mac Lane, ibid., §IV.2, printed p. 89, Exercise 1 — the same
          constructions read as left adjoints (maclane:IV.2:ex1)
    nLab:      https://ncatlab.org/nlab/show/tensor+algebra
    nLab:      https://ncatlab.org/nlab/show/exterior+algebra
    Wikipedia: https://en.wikipedia.org/wiki/Tensor_algebra
    Wikipedia: https://en.wikipedia.org/wiki/Exterior_algebra

    TWO CONSTRUCTIONS, ONE TERM ALGEBRA.  Mac Lane's exercise names the
    tensor algebra and the exterior algebra separately, and every textbook
    builds the second as a quotient of the first.  That is exactly how
    they are related here, and the relation is visible in the code rather
    than argued for in prose: [TTerm] is one inductive type of formal
    expressions, [tt_eq] is the congruence generated by the
    associative-algebra laws together with K-linearity of the insertion,
    and [et_eq] is [tt_eq] with ONE further generating equation, v·v ≈ 0,
    adjoined — its first constructor [ee_base] embeds the whole of
    [tt_eq], so the exterior relation is by construction coarser and
    nothing about the ring structure has to be re-proved.  The projection
    [ext_proj : T(V) → Λ(V)] is then the identity on terms
    ([ext_proj_computes], by [eq_refl]).

    THE ALTERNATING RELATION, AND WHY IT IS NOT ANTISYMMETRY.  The
    defining relation of Λ(V) is v ∧ v ≈ 0 for GENERATORS v, not
    v ∧ w ≈ −(w ∧ v).  The squares-vanish form is the one imposed, and it
    IMPLIES antisymmetry: [ext_anticomm] derives v ∧ w ≈ −(w ∧ v) by
    expanding (v + w) ∧ (v + w) ≈ 0.  The converse implication is the one
    that needs 2 to be cancellable, and over a base ring in which 2 ≈ 0
    antisymmetry degenerates into COMMUTATIVITY of the generators — which
    is a condition, but not the one wanted, since it does not give
    v ∧ v ≈ 0.  So the direction proved here is the useful one.  What is
    NOT proved here is that the converse is underivable: no countermodel
    is exhibited, and no claim of strict strength is made — what IS proved
    beyond the implication is that the derived antisymmetry is not vacuous
    ([ext_anticomm_nontrivial], where v ∧ w and w ∧ v are provably
    distinct).  There is in-tree precedent for taking this care, with a
    DIFFERENT degeneracy: Instance/Matr/Determinant.v derives its general
    alternation [det_alt] and records that it does "NOT follow from
    [det M ≈ ⊖ det M] — that is vacuous in characteristic 2", the
    self-equation x ≈ −x being vacuous there in a way that the two-element
    equation above is not.  Note also that v ∧ v ≈ 0 is demanded of
    GENERATORS only — of elements of V, that is, of the image of [tt_gen] —
    and not of arbitrary elements of Λ(V); [ext_alt] is stated at that
    scope and nowhere widened.

    WHY [AAlg] AND NOT [KAlg].  Instance/Rng/Algebras/Associative.v
    carries the reason at length: [KAlgObject]'s [kalg_comm] field makes
    every object of [KAlg K] commutative, so T(V) — which is
    non-commutative already at the V used below, proved at
    [tensor_not_commutative] — is not an object of it, and Λ(V) is
    anticommutative rather than commutative.  The exercise is therefore
    stated over [AAlg K], the associative K-algebras, which that file
    builds.

    A CORRECTION TO THE ISSUE'S PRIOR ART, recorded here because a header
    is where a reader looks.  Issue #310's "Current state in the library"
    section says the material is "Absent" and that "No categories of
    rings, K-algebras, or vector spaces exist in Instance/ to host the
    constructions".  Every clause of that but its closing rider was already
    false when this was written — and the rider, "to host the
    constructions", was substantively RIGHT about the algebra half, which
    is the whole reason [AAlg K] exists: Instance/Rng.v is the category of unital rings,
    Instance/Rng/Algebras.v the category [KAlg] of COMMUTATIVE K-algebras,
    Instance/Mod.v the category of R-modules with Instance/Vect/Free.v and
    Instance/FdVect.v the vector-space readings, and Instance/Mod/Tensor.v
    the tensor product of two modules as a universal element.  What was
    genuinely absent is narrower, and is what this pair of files supplies:
    a category of algebras that does NOT demand commutativity, and the two
    constructions themselves.  The issue's own scope note — that a bundled
    PR is acceptable "only if the algebra-category substrate from the
    dependencies is already in place" — was therefore NOT met as written:
    the COMMUTATIVE substrate was in place, the associative one had to be
    built first, and building it is part of this work rather than a
    precondition of it.

    THE ROUTE NOT TAKEN, and it was measured rather than guessed.  The
    classical construction T(V) = ⊕_n V^⊗n over Instance/Mod/Tensor.v's
    binary tensor product is not available in this tree: it needs
    countable direct sums of modules, and [HasIndexedCoproducts] has
    exactly one instance anywhere (Instance/Sets/Products.v, at [Sets]),
    with no [Cocartesian (RMod R)] and no direct sum of modules of any
    kind.  So T(V) is built directly by generators and relations, which is
    the house pattern for exactly this situation — Instance/Ab/Tensor.v,
    Instance/Sets/Coend.v, Instance/Mod/Free.v, Instance/Mod/Tensor.v and
    Instance/Rng/Polynomial.v all present a quotient this way — and the
    grading is what is given up: there is no degree function on [TTerm],
    hence no decomposition of T(V) into homogeneous pieces, no normal
    form, and no decision procedure for equality.

    STRENGTHS, MEASURED, and they differ between the two halves of each
    extension.

      - [eq_refl]: evaluation restricted to the generators IS the given
        linear map, and restricted to the scalars IS the structure map
        ([tensor_extend_gen], [tensor_extend_scal], and the exterior
        counterparts); the exterior projection is the identity on terms
        ([ext_proj_computes]); the universal arrow of the tensor algebra IS
        the insertion ([tensor_arrow_is_insert]); the free functor's object
        part IS [TensorAlg] ([TensorFunctor_obj]); the unit of the
        adjunction IS the generator insertion ([tensor_unit_is_gen]); the
        universal element of [AltFunctor] IS the exterior insertion
        ([ext_universal_elem_is_insert]); and the concrete computations in
        the witness section reduce.
      - `≈` only, and this was tried strictly first: preservation of ZERO
        and of ONE by the extension.  The zero of T(V) is
        [tt_scal (rig_zero K)], so the fold returns the structure map's
        value at K's zero, and reaching the target's zero is that map's own
        preservation law.  Instance/Rng/Polynomial.v records the identical
        seam for K[x], for the identical reason.
      - `≈` only, unavoidably: the transposes obtained from
        [ump_universal_arrows], which is [Qed]-opaque.  The counit of
        [tensor_adjunction] is on that side and no [eq_refl] is claimed for
        it; Instance/Mod/Free.v records the same for the free module.

    WHAT IS DELIVERED.

      - [TensorAlg V : AAlgObject K] for any K-module V, with the insertion
        [tensor_insert : AAlgLinear V (TensorAlg V)];
      - [tensor_extend] and [tensor_extend_unique]: every K-linear map from
        V into an associative K-algebra extends uniquely to an algebra map
        out of T(V);
      - [tensor_universal_arrow : UniversalArrow V (AAlg_Forget_Mod K)] and
        [tensor_auniversal_arrow], Mac Lane's §III.1 Exercise 1 in both of
        Theory/Universal/Arrow.v's encodings, with the §IV.2 left-adjoint
        reading [TensorFunctor] and
        [tensor_adjunction : TensorFunctor ⊣ AAlg_Forget_Mod K];
      - [ExtAlg V : AAlgObject K] with [ext_insert], [ext_alt] and the
        derived [ext_anticomm]; [ext_extend], [ext_extend_unique];
        [ext_proj : T(V) ⟶ Λ(V)], the identity on terms;
      - [tensor_extend_self] and [ext_extend_self]: each universal
        property applied at its own object, so that the extension of an
        insertion along itself is the identity;
      - [AltLinear] and [AltFunctor V : AAlg K ⟶ Sets], and
        [ext_universal_element : AUniversalElement (AltFunctor V)
        (ExtAlg V)] — the exterior algebra in UNIVERSAL-ARROW form, with
        [ext_representation] exhibiting Λ(V) as representing the functor of
        alternating maps, [ext_representable], and [ext_auniversal_arrow]
        the arrow reading out of the one-point setoid;
      - non-degeneracy, proved and not asserted: [tensor_not_commutative]
        (T(V) is genuinely non-commutative for a concrete V, so the passage
        to [AAlg] was necessary), [tensor_gen_not_scalar],
        [ext_nontrivial], [ext_gen_not_scalar] and
        [ext_anticomm_nontrivial] (e₁∧e₂ and e₂∧e₁ are provably distinct in
        a concrete Λ, so antisymmetry is not vacuous), each obtained by
        mapping OUT into a concrete algebra, since no induction on the
        quotienting relation could yield a negative.

    THE TWO DEGENERACIES, NAMED AND EXCLUDED.  Both constructions have a
    degenerate case, and the witnesses below are chosen to avoid each.
    (i) A TRIVIAL BASE RING: if 1 ≈ 0 in K then the one and the zero of
    T(V) and of Λ(V) are the same scalar, and the separations below would
    be false.  The witnesses are over ℤ, and the exclusion is proved
    INSIDE the constructions rather than assumed of the base:
    [tensor_nontrivial] and [ext_nontrivial] show 1 ≉ 0 in T(V) and in
    Λ(V) themselves.  (ii) A ZERO MODULE: [te_gen_zero] proves the
    generator of the zero vector IS the scalar zero, so over V = 0 every
    generator is a scalar and [tensor_gen_not_scalar] would be false.  The
    witnesses avoid it, and again the avoidance is proved rather than
    assumed: [tensor_gen_not_scalar] and [ext_gen_not_scalar] exhibit
    generators that are provably not scalars, and [ext_gens_distinct] two
    generators that are provably distinct.  (No notion of linear
    independence is defined in this file and none is claimed; what is
    proved is exactly the distinctness just listed.)

    WHAT §IV.2 ASKS FOR BEYOND THIS, AND IS DELIBERATELY NOT DELIVERED.
    Mac Lane's §IV.2 Exercise 1 asks for the exterior algebra as a LEFT
    ADJOINT of a forgetful functor whose codomain is the category of GRADED
    ANTICOMMUTATIVE K-algebras, and makes a point of that forgetful functor
    being NOT FAITHFUL.  Neither is delivered here.  No category of graded
    anticommutative K-algebras is built — the tree has no grading on
    algebras at all, and neither dependency of this issue supplies one —
    and consequently no adjunction over such a category, and no
    non-faithfulness lemma.  NEITHER IS ASSUMED ANYWHERE in what follows:
    no proof below uses a grading, an anticommutativity law of a target
    algebra, or any property of a forgetful functor out of a graded
    category, and no comment below asserts any of the three as known.  What
    IS delivered for Λ(V) is the universal-arrow form over the same
    [AAlg K] substrate as T(V), which is what the issue's own scope
    increment specifies.  The left-adjoint upgrade and the
    non-faithfulness lemma are follow-up work over a category that does not
    yet exist.

    OTHER DEFERRALS.  No grading, no homogeneous components, no normal
    form, no coefficient uniqueness, hence no decision procedure and no
    dimension count — in particular Λ(V) is NOT shown to be finitely
    generated when V is, and no basis of Λ(V) is exhibited.  No symmetric
    algebra, and so no identification of the symmetric algebra as the
    [KAlg] reading of the same universal property.  No comparison with
    Instance/Mod/Tensor.v's binary tensor product: T(V) is not shown to
    contain V ⊗ V as its degree-two part, because there is no degree.  No
    functoriality of Λ in V as a stated functor — T gains it as the [fmap]
    of the left adjoint, and Λ has no adjunction here to inherit it from,
    since the alternating maps out of V do not arise as maps into a
    forgetful image.  The witnesses below are over ℤ; no field-specific
    statement is made, and Instance/FdVect.v's finite-dimensional vector
    spaces are not connected to this file.

    ONE IMPORT EXPLAINED.  Instance/Rng/Polynomial.v is required for
    exactly two lemmas, [rng_mul_neg_l] and [rng_mul_neg_r], which it
    proves for an arbitrary [RingObject] by uniqueness of additive
    inverses.  They are consumed once each, in [tensor_scal_central].
    Proving them a second time here would be duplication; nothing else of
    that file is used. *)

(** ** Alternating linear maps

    The data the universal property of Λ(V) consumes: a K-linear map whose
    values SQUARE TO ZERO.  Stated at [AAlgLinear] plus one field, so that
    everything Instance/Rng/Algebras/Associative.v proves about linear maps
    applies unchanged. *)

Record AltLinear {K : CRng} (V : RModObject (`1 K)) (A : AAlgObject K) := {
  alt_lin :> AAlgLinear V A;

  alt_sq : ∀ v, rig_mul (aalg_ring A) (alin_map alt_lin v) (alin_map alt_lin v)
                  ≈ rig_zero (aalg_ring A)
}.

Arguments alt_lin {K V A} _.
Arguments alt_sq {K V A} _ _.

Program Definition AltLinear_Setoid {K : CRng} (V : RModObject (`1 K))
  (A : AAlgObject K) : Setoid (AltLinear V A) := {|
  equiv := fun f g => ∀ v, alin_map (alt_lin f) v ≈ alin_map (alt_lin g) v
|}.
Next Obligation.
  intros K V A.
  constructor.
  - intros f v; reflexivity.
  - intros f g Hfg v; symmetry; apply Hfg.
  - intros f g h Hfg Hgh v; transitivity (alin_map (alt_lin g) v);
      [ apply Hfg | apply Hgh ].
Qed.

(* Postcomposing an alternating map with an algebra morphism keeps it
   alternating: the morphism carries the square to the square and the zero
   to the zero. *)
Program Definition alt_compose {K : CRng} {V : RModObject (`1 K)}
  {A B : AAlgObject K} (g : AAlgHom A B) (f : AltLinear V A)
  : AltLinear V B := {|
  alt_lin := alin_compose g (alt_lin f)
|}.
Next Obligation.
  intros K V A B g f v; simpl.
  rewrite <- (rig_map_mul (`1 g)).
  rewrite (proper_morphism (rig_map (`1 g)) _ _ (alt_sq f v)).
  apply (rig_map_zero (`1 g)).
Qed.

(* The functor of alternating maps out of V.  Λ(V) is what represents it,
   and that is [ext_universal_element] below. *)
Program Definition AltFunctor {K : CRng} (V : RModObject (`1 K))
  : AAlg K ⟶ Sets := {|
  fobj := fun A => {| carrier := AltLinear V A;
                      is_setoid := AltLinear_Setoid V A |};
  fmap := fun A B g => {| morphism := alt_compose g |}
|}.
Next Obligation.
  intros K V A B g f f' Hff' v; simpl.
  exact (proper_morphism (rig_map (`1 g)) _ _ (Hff' v)).
Qed.
Next Obligation.
  intros K V A B g g' Hgg' f v; simpl; exact (Hgg' _).
Qed.
Next Obligation. intros K V A f v; simpl; reflexivity. Qed.
Next Obligation. intros K V A B C g h f v; simpl; reflexivity. Qed.

(** * The term algebra *)

Section Algebras.

Context (K : CRng).
Context (V : RModObject (`1 K)).

(** ** Formal expressions

    Five formers: scalars, generators, sum, negation and product.  There is
    no former for the unit or for the zero — those are [tt_scal] of K's one
    and zero, exactly as in Instance/Rng/Polynomial.v. *)

Inductive TTerm : Type :=
  | tt_scal : carrier (rig_setoid (`1 K)) → TTerm
  | tt_gen  : carrier (cmon_setoid V) → TTerm
  | tt_add  : TTerm → TTerm → TTerm
  | tt_neg  : TTerm → TTerm
  | tt_mul  : TTerm → TTerm → TTerm.

(** The congruence: the ring laws with multiplication NOT commutative, the
    two clauses making the scalar inclusion a ring homomorphism, and
    K-linearity of the generator insertion stated on BOTH sides — the
    right-hand form [te_gen_smul_r] is what makes the scalars central,
    and it is not derivable from the left-hand form alone. *)

Inductive tt_eq : TTerm → TTerm → Type :=
  (* congruence for each former, saturating under the two source setoids *)
  | te_scal {a b} : a ≈ b → tt_eq (tt_scal a) (tt_scal b)
  | te_gen {v w} : v ≈ w → tt_eq (tt_gen v) (tt_gen w)
  | te_add {s s' t t'} :
      tt_eq s s' → tt_eq t t' → tt_eq (tt_add s t) (tt_add s' t')
  | te_neg {s s'} : tt_eq s s' → tt_eq (tt_neg s) (tt_neg s')
  | te_mul {s s' t t'} :
      tt_eq s s' → tt_eq t t' → tt_eq (tt_mul s t) (tt_mul s' t')

  (* abelian group under addition *)
  | te_add_assoc s t u :
      tt_eq (tt_add (tt_add s t) u) (tt_add s (tt_add t u))
  | te_add_comm s t : tt_eq (tt_add s t) (tt_add t s)
  | te_add_zero_l s : tt_eq (tt_add (tt_scal (rig_zero (`1 K))) s) s
  | te_add_neg_l s : tt_eq (tt_add (tt_neg s) s) (tt_scal (rig_zero (`1 K)))

  (* monoid under multiplication — commutativity is NOT among the laws *)
  | te_mul_assoc s t u :
      tt_eq (tt_mul (tt_mul s t) u) (tt_mul s (tt_mul t u))
  | te_mul_one_l s : tt_eq (tt_mul (tt_scal (rig_one (`1 K))) s) s
  | te_mul_one_r s : tt_eq (tt_mul s (tt_scal (rig_one (`1 K)))) s

  (* distributivity on both sides *)
  | te_distr_l s t u :
      tt_eq (tt_mul s (tt_add t u)) (tt_add (tt_mul s t) (tt_mul s u))
  | te_distr_r s t u :
      tt_eq (tt_mul (tt_add s t) u) (tt_add (tt_mul s u) (tt_mul t u))

  (* the scalar inclusion is a homomorphism of rings *)
  | te_scal_add a b :
      tt_eq (tt_scal (rig_add (`1 K) a b)) (tt_add (tt_scal a) (tt_scal b))
  | te_scal_mul a b :
      tt_eq (tt_scal (rig_mul (`1 K) a b)) (tt_mul (tt_scal a) (tt_scal b))

  (* the generator insertion is K-linear, on both sides *)
  | te_gen_add v w :
      tt_eq (tt_gen (cmon_plus V v w)) (tt_add (tt_gen v) (tt_gen w))
  | te_gen_smul_l r v :
      tt_eq (tt_gen (rm_smul V r v)) (tt_mul (tt_scal r) (tt_gen v))
  | te_gen_smul_r r v :
      tt_eq (tt_gen (rm_smul V r v)) (tt_mul (tt_gen v) (tt_scal r))

  | te_sym {s t} : tt_eq s t → tt_eq t s
  | te_trans {s t u} : tt_eq s t → tt_eq t u → tt_eq s u.

(* Reflexivity is derived, keeping the relation's induction principle one
   case shorter wherever it is consumed. *)
Lemma tt_refl (s : TTerm) : tt_eq s s.
Proof.
  induction s.
  - exact (te_scal (reflexivity _)).
  - exact (te_gen (reflexivity _)).
  - exact (te_add IHs1 IHs2).
  - exact (te_neg IHs).
  - exact (te_mul IHs1 IHs2).
Qed.

Lemma tt_eq_Equivalence : Equivalence tt_eq.
Proof.
  constructor.
  - exact tt_refl.
  - exact (fun s t => te_sym).
  - exact (fun s t u => te_trans).
Qed.

(* As in Instance/Ab/Tensor.v and Instance/Rng/Polynomial.v this setoid is
   deliberately NOT registered as an instance: the [≈] of [TensorRing] IS
   [tt_eq] definitionally, so Theory/Algebra/Rig.v's lemmas apply to it
   unchanged. *)
Definition tt_Setoid : Setoid TTerm := {|
  equiv        := tt_eq;
  setoid_equiv := tt_eq_Equivalence
|}.

(** ** Derived laws *)

Let TZ : TTerm := tt_scal (rig_zero (`1 K)).
Let TO : TTerm := tt_scal (rig_one (`1 K)).

Lemma te_add_zero_r (s : TTerm) : tt_eq (tt_add s TZ) s.
Proof. exact (te_trans (te_add_comm s TZ) (te_add_zero_l s)). Qed.

Lemma te_add_neg_r (s : TTerm) : tt_eq (tt_add s (tt_neg s)) TZ.
Proof. exact (te_trans (te_add_comm s (tt_neg s)) (te_add_neg_l s)). Qed.

Lemma te_add_cancel_l (s t u : TTerm) :
  tt_eq (tt_add s t) (tt_add s u) → tt_eq t u.
Proof.
  intro H.
  refine (te_trans (te_sym (te_add_zero_l t)) _).
  refine (te_trans (te_add (te_sym (te_add_neg_l s)) (tt_refl t)) _).
  refine (te_trans (te_add_assoc (tt_neg s) s t) _).
  refine (te_trans (te_add (tt_refl (tt_neg s)) H) _).
  refine (te_trans (te_sym (te_add_assoc (tt_neg s) s u)) _).
  refine (te_trans (te_add (te_add_neg_l s) (tt_refl u)) _).
  exact (te_add_zero_l u).
Qed.

Lemma te_mul_zero_l (s : TTerm) : tt_eq (tt_mul TZ s) TZ.
Proof.
  (* 0·s ≈ (0+0)·s ≈ 0·s + 0·s, so 0·s ≈ 0 by cancellation. *)
  apply (te_add_cancel_l (tt_mul TZ s)).
  refine (te_trans (te_sym (te_distr_r TZ TZ s)) _).
  refine (te_trans (te_mul _ (tt_refl s))
            (te_sym (te_add_zero_r (tt_mul TZ s)))).
  refine (te_trans (te_sym (te_scal_add (rig_zero (`1 K)) (rig_zero (`1 K)))) _).
  exact (te_scal (rig_add_zero_l (`1 K) (rig_zero (`1 K)))).
Qed.

Lemma te_mul_zero_r (s : TTerm) : tt_eq (tt_mul s TZ) TZ.
Proof.
  apply (te_add_cancel_l (tt_mul s TZ)).
  refine (te_trans (te_sym (te_distr_l s TZ TZ)) _).
  refine (te_trans (te_mul (tt_refl s) _)
            (te_sym (te_add_zero_r (tt_mul s TZ)))).
  refine (te_trans (te_sym (te_scal_add (rig_zero (`1 K)) (rig_zero (`1 K)))) _).
  exact (te_scal (rig_add_zero_l (`1 K) (rig_zero (`1 K)))).
Qed.

(* The generator of the zero vector IS the scalar zero — additivity plus
   cancellation.  This is the second degeneracy named in the header: over
   the zero module every generator is a scalar. *)
Lemma te_gen_zero : tt_eq (tt_gen (cmon_zero V)) TZ.
Proof.
  apply (te_add_cancel_l (tt_gen (cmon_zero V))).
  refine (te_trans _ (te_sym (te_add_zero_r (tt_gen (cmon_zero V))))).
  refine (te_trans (te_sym (te_gen_add (cmon_zero V) (cmon_zero V))) _).
  exact (te_gen (cmon_plus_zero_l V (cmon_zero V))).
Qed.

(** ** The ring T(V) *)

Definition TensorRig : RigObject := {|
  rig_setoid := {| carrier := TTerm; is_setoid := tt_Setoid |};
  rig_zero := TZ;
  rig_add := tt_add;
  rig_one := TO;
  rig_mul := tt_mul;
  rig_add_respects := fun _ _ Hs _ _ Ht => te_add Hs Ht;
  rig_mul_respects := fun _ _ Hs _ _ Ht => te_mul Hs Ht;
  rig_add_assoc := te_add_assoc;
  rig_add_comm := te_add_comm;
  rig_add_zero_l := te_add_zero_l;
  rig_mul_assoc := te_mul_assoc;
  rig_mul_one_l := te_mul_one_l;
  rig_mul_one_r := te_mul_one_r;
  rig_distr_l := te_distr_l;
  rig_distr_r := te_distr_r;
  rig_mul_zero_l := te_mul_zero_l;
  rig_mul_zero_r := te_mul_zero_r
|}.

Definition TensorRing : RingObject := {|
  ring_rig := TensorRig;
  ring_neg := tt_neg;
  ring_neg_respects := fun _ _ Hs => te_neg Hs;
  ring_neg_l := te_add_neg_l
|}.

(** ** The scalar inclusion and the generator insertion *)

Program Definition tensor_scal : `1 K ~{Rng}~> TensorRing := {|
  rig_map := {| morphism := tt_scal |}
|}.
Next Obligation. intros a b H; exact (te_scal H). Qed.
Next Obligation. simpl; exact (tt_refl TZ). Qed.
Next Obligation. intros a b; exact (te_scal_add a b). Qed.
Next Obligation. simpl; exact (tt_refl TO). Qed.
Next Obligation. intros a b; exact (te_scal_mul a b). Qed.

(** Scalars are CENTRAL in T(V).  This is a theorem, by induction on the
    term, rather than a further generating equation: the generator case is
    the two linearity clauses composed, the scalar case is commutativity of
    K, and the three recursive cases are the ring laws of [TensorRing]
    together with Instance/Rng/Polynomial.v's negation lemmas. *)
Lemma tensor_scal_central (r : carrier (rig_setoid (`1 K))) (t : TTerm) :
  tt_eq (tt_mul (tt_scal r) t) (tt_mul t (tt_scal r)).
Proof.
  induction t as [ a | v | s IHs u IHu | s IHs | s IHs u IHu ].
  - refine (te_trans (te_sym (te_scal_mul r a)) _).
    refine (te_trans (te_scal (`2 K r a)) _).
    exact (te_scal_mul a r).
  - exact (te_trans (te_sym (te_gen_smul_l r v)) (te_gen_smul_r r v)).
  - refine (te_trans (te_distr_l (tt_scal r) s u) _).
    refine (te_trans (te_add IHs IHu) _).
    exact (te_sym (te_distr_r s u (tt_scal r))).
  - refine (te_trans (rng_mul_neg_r TensorRing (tt_scal r) s) _).
    refine (te_trans (te_neg IHs) _).
    exact (te_sym (rng_mul_neg_l TensorRing s (tt_scal r))).
  - refine (te_trans (te_sym (te_mul_assoc (tt_scal r) s u)) _).
    refine (te_trans (te_mul IHs (tt_refl u)) _).
    refine (te_trans (te_mul_assoc s (tt_scal r) u) _).
    refine (te_trans (te_mul (tt_refl s) IHu) _).
    exact (te_sym (te_mul_assoc s u (tt_scal r))).
Qed.

(** T(V) as an object of [AAlg K]. *)
Definition TensorAlg : AAlgObject K :=
  Build_AAlgObject K TensorRing tensor_scal tensor_scal_central.

(** The insertion of the generators, K-linear by two of the generating
    equations. *)
Program Definition tensor_insert : AAlgLinear V TensorAlg := {|
  alin_map := {| morphism := tt_gen |}
|}.
Next Obligation. intros v w H; exact (te_gen H). Qed.
Next Obligation. intros v w; exact (te_gen_add v w). Qed.
Next Obligation. intros r v; exact (te_gen_smul_l r v). Qed.

(** * Evaluation: the universal property in element form *)

Section TensorEvaluation.

Context (A : AAlgObject K).
Context (f : AAlgLinear V A).

Notation AR := (aalg_ring A).

Fixpoint teval (t : TTerm) : carrier (rig_setoid AR) :=
  match t with
  | tt_scal a  => rig_map (aalg_unit A) a
  | tt_gen v   => alin_map f v
  | tt_add s t => rig_add AR (teval s) (teval t)
  | tt_neg s   => ring_neg AR (teval s)
  | tt_mul s t => rig_mul AR (teval s) (teval t)
  end.

(** Twenty cases, one per constructor of [tt_eq].  Five are congruence for
    a former, the first two saturating under the source setoids; seven are
    ring laws of A, four of those additionally spending a preservation law
    of the structure map, because the zero and the one of T(V) are scalars
    rather than formers of their own; two are the structure map's
    preservation of sums and of products; three are the linear map's own
    laws, of which the right-hand linearity clause is the one that spends
    CENTRALITY of the structure map's image; and the last two are the
    target setoid's symmetry and transitivity. *)
Lemma teval_respects (s t : TTerm) : tt_eq s t → teval s ≈ teval t.
Proof.
  intro He.
  induction He as
    [ a b Hab
    | v w Hvw
    | s s' t t' _ IHs _ IHt
    | s s' _ IHs
    | s s' t t' _ IHs _ IHt
    | s t w | s t | s | s
    | s t w | s | s
    | s t w | s t w
    | a b | a b
    | v w | r v | r v
    | s t _ IHst
    | s t w _ IHst _ IHtw ]; simpl.
  - exact (proper_morphism (rig_map (aalg_unit A)) _ _ Hab).
  - exact (proper_morphism (alin_map f) _ _ Hvw).
  - exact (rig_add_respects AR _ _ IHs _ _ IHt).
  - exact (ring_neg_respects AR _ _ IHs).
  - exact (rig_mul_respects AR _ _ IHs _ _ IHt).
  - exact (rig_add_assoc AR _ _ _).
  - exact (rig_add_comm AR _ _).
  - rewrite (rig_map_zero (aalg_unit A)); apply rig_add_zero_l.
  - rewrite (rig_map_zero (aalg_unit A)); apply (ring_neg_l AR).
  - exact (rig_mul_assoc AR _ _ _).
  - rewrite (rig_map_one (aalg_unit A)); apply rig_mul_one_l.
  - rewrite (rig_map_one (aalg_unit A)); apply rig_mul_one_r.
  - exact (rig_distr_l AR _ _ _).
  - exact (rig_distr_r AR _ _ _).
  - exact (rig_map_add (aalg_unit A) a b).
  - exact (rig_map_mul (aalg_unit A) a b).
  - exact (alin_add f v w).
  - exact (alin_smul f r v).
  - rewrite (alin_smul f r v); apply aalg_central.
  - exact (symmetry IHst).
  - exact (transitivity IHst IHtw).
Qed.

(** *** The extension

    STRENGTH, MEASURED.  Preservation of ADDITION and of MULTIPLICATION
    close by [reflexivity] — those are clauses of the fixpoint.
    Preservation of ZERO and of ONE does NOT: the zero of T(V) is
    [tt_scal (rig_zero K)], so the fold returns the structure map's value
    there, and reaching the target's zero is that map's own preservation
    law.  Only respectfulness has content beyond that. *)
Program Definition tensor_extend_ring : TensorRing ~{Rng}~> AR := {|
  rig_map := {| morphism := teval |}
|}.
Next Obligation. intros s t He; exact (teval_respects s t He). Qed.
Next Obligation. simpl; exact (rig_map_zero (aalg_unit A)). Qed.
Next Obligation. intros s t; simpl; reflexivity. Qed.
Next Obligation. simpl; exact (rig_map_one (aalg_unit A)). Qed.
Next Obligation. intros s t; simpl; reflexivity. Qed.

Lemma tensor_extend_triangle :
  aalg_unit A ≈ tensor_extend_ring ∘ aalg_unit TensorAlg.
Proof. intro a; simpl; reflexivity. Qed.

Definition tensor_extend : TensorAlg ~{AAlg K}~> A :=
  (tensor_extend_ring; tensor_extend_triangle).

(** The extension restricts to [f] on generators and to the structure map
    on scalars, both DEFINITIONALLY — the fixpoint's first two clauses are
    those two equations.  This is the convertibility exception: the
    equations are between elements of A's carrier, not between
    morphisms. *)
Example tensor_extend_gen (v : carrier (cmon_setoid V)) :
  rig_map (`1 tensor_extend) (tt_gen v) = alin_map f v := eq_refl.

Example tensor_extend_scal (a : carrier (rig_setoid (`1 K))) :
  rig_map (`1 tensor_extend) (tt_scal a) = rig_map (aalg_unit A) a := eq_refl.

(** *** Uniqueness

    Any ring homomorphism out of T(V) agreeing with [f] on generators and
    with the structure map on scalars IS the evaluation.  The induction has
    one case per former: the two base cases are the hypotheses, and the
    other three are homomorphism laws of the competitor — preservation of
    sums, of negation (Theory/Algebra/Rig.v's [RigHom_neg], a theorem
    rather than a field) and of products. *)
Lemma tensor_extend_unique (g : TensorRing ~{Rng}~> AR)
  (Hscal : ∀ a, rig_map g (tt_scal a) ≈ rig_map (aalg_unit A) a)
  (Hgen : ∀ v, rig_map g (tt_gen v) ≈ alin_map f v) (t : TTerm) :
  rig_map g t ≈ teval t.
Proof.
  induction t as [ a | v | s IHs t IHt | s IHs | s IHs t IHt ]; simpl.
  - exact (Hscal a).
  - exact (Hgen v).
  - rewrite (rig_map_add g s t); exact (rig_add_respects AR _ _ IHs _ _ IHt).
  - rewrite (RigHom_neg TensorRing AR g s).
    exact (ring_neg_respects AR _ _ IHs).
  - rewrite (rig_map_mul g s t); exact (rig_mul_respects AR _ _ IHs _ _ IHt).
Qed.

End TensorEvaluation.

(* A morphism of algebras out of T(V) automatically agrees with the
   structure map on scalars: that is exactly its triangle. *)
Lemma tensor_alg_hom_scal (A : AAlgObject K) (g : TensorAlg ~{AAlg K}~> A)
  (a : carrier (rig_setoid (`1 K))) :
  rig_map (`1 g) (tt_scal a) ≈ rig_map (aalg_unit A) a.
Proof. symmetry; exact (`2 g a). Qed.

(** * The exterior algebra

    Λ(V) is T(V) with the single further generating equation v·v ≈ 0 for
    generators v.  The relation [et_eq] therefore has SEVEN constructors
    rather than twenty: the first embeds the whole of [tt_eq], so every
    ring law and every linearity clause is inherited rather than restated,
    and the remaining six are the new equation, congruence for the three
    formers it can appear under, and the two closure rules. *)

Inductive et_eq : TTerm → TTerm → Type :=
  | ee_base {s t} : tt_eq s t → et_eq s t

  (* the alternating relation, at GENERATORS only *)
  | ee_alt v : et_eq (tt_mul (tt_gen v) (tt_gen v))
                     (tt_scal (rig_zero (`1 K)))

  | ee_add {s s' t t'} :
      et_eq s s' → et_eq t t' → et_eq (tt_add s t) (tt_add s' t')
  | ee_neg {s s'} : et_eq s s' → et_eq (tt_neg s) (tt_neg s')
  | ee_mul {s s' t t'} :
      et_eq s s' → et_eq t t' → et_eq (tt_mul s t) (tt_mul s' t')

  | ee_sym {s t} : et_eq s t → et_eq t s
  | ee_trans {s t u} : et_eq s t → et_eq t u → et_eq s u.

Lemma et_refl (s : TTerm) : et_eq s s.
Proof. exact (ee_base (tt_refl s)). Qed.

Lemma et_eq_Equivalence : Equivalence et_eq.
Proof.
  constructor.
  - exact et_refl.
  - exact (fun s t => ee_sym).
  - exact (fun s t u => ee_trans).
Qed.

Definition et_Setoid : Setoid TTerm := {|
  equiv        := et_eq;
  setoid_equiv := et_eq_Equivalence
|}.

(** Every law is [ee_base] of the corresponding law of T(V): the ring
    structure is inherited wholesale, which is the formal content of "Λ(V)
    is a quotient of T(V)". *)

Definition ExtRig : RigObject := {|
  rig_setoid := {| carrier := TTerm; is_setoid := et_Setoid |};
  rig_zero := TZ;
  rig_add := tt_add;
  rig_one := TO;
  rig_mul := tt_mul;
  rig_add_respects := fun _ _ Hs _ _ Ht => ee_add Hs Ht;
  rig_mul_respects := fun _ _ Hs _ _ Ht => ee_mul Hs Ht;
  rig_add_assoc := fun s t u => ee_base (te_add_assoc s t u);
  rig_add_comm := fun s t => ee_base (te_add_comm s t);
  rig_add_zero_l := fun s => ee_base (te_add_zero_l s);
  rig_mul_assoc := fun s t u => ee_base (te_mul_assoc s t u);
  rig_mul_one_l := fun s => ee_base (te_mul_one_l s);
  rig_mul_one_r := fun s => ee_base (te_mul_one_r s);
  rig_distr_l := fun s t u => ee_base (te_distr_l s t u);
  rig_distr_r := fun s t u => ee_base (te_distr_r s t u);
  rig_mul_zero_l := fun s => ee_base (te_mul_zero_l s);
  rig_mul_zero_r := fun s => ee_base (te_mul_zero_r s)
|}.

Definition ExtRing : RingObject := {|
  ring_rig := ExtRig;
  ring_neg := tt_neg;
  ring_neg_respects := fun _ _ Hs => ee_neg Hs;
  ring_neg_l := fun s => ee_base (te_add_neg_l s)
|}.

Program Definition ext_scal : `1 K ~{Rng}~> ExtRing := {|
  rig_map := {| morphism := tt_scal |}
|}.
Next Obligation. intros a b H; exact (ee_base (te_scal H)). Qed.
Next Obligation. simpl; exact (et_refl TZ). Qed.
Next Obligation. intros a b; exact (ee_base (te_scal_add a b)). Qed.
Next Obligation. simpl; exact (et_refl TO). Qed.
Next Obligation. intros a b; exact (ee_base (te_scal_mul a b)). Qed.

Lemma ext_scal_central (r : carrier (rig_setoid (`1 K))) (t : TTerm) :
  et_eq (tt_mul (tt_scal r) t) (tt_mul t (tt_scal r)).
Proof. exact (ee_base (tensor_scal_central r t)). Qed.

Definition ExtAlg : AAlgObject K :=
  Build_AAlgObject K ExtRing ext_scal ext_scal_central.

Program Definition ext_insert_lin : AAlgLinear V ExtAlg := {|
  alin_map := {| morphism := tt_gen |}
|}.
Next Obligation. intros v w H; exact (ee_base (te_gen H)). Qed.
Next Obligation. intros v w; exact (ee_base (te_gen_add v w)). Qed.
Next Obligation. intros r v; exact (ee_base (te_gen_smul_l r v)). Qed.

(** The defining relation, in the vocabulary of the algebra. *)
Lemma ext_alt (v : carrier (cmon_setoid V)) :
  rig_mul ExtRing (tt_gen v) (tt_gen v) ≈ rig_zero ExtRing.
Proof. exact (ee_alt v). Qed.

Definition ext_insert : AltLinear V ExtAlg :=
  {| alt_lin := ext_insert_lin; alt_sq := ext_alt |}.

(** ANTISYMMETRY IS DERIVED, not assumed: expanding
    (v + w)∧(v + w) ≈ 0 and cancelling the two square terms leaves
    v∧w + w∧v ≈ 0.  The converse — recovering v∧v ≈ 0 from antisymmetry —
    is not proved and is not claimed; see the header for what is and is
    not established about the two forms. *)
Lemma ext_anticomm (v w : carrier (cmon_setoid V)) :
  rig_mul ExtRing (tt_gen v) (tt_gen w)
    ≈ ring_neg ExtRing (rig_mul ExtRing (tt_gen w) (tt_gen v)).
Proof.
  apply (ab_neg_unique (ring_ab ExtRing)); simpl.
  assert (Hsum : @equiv _ (is_setoid (rig_setoid ExtRing))
                   (tt_gen (cmon_plus V v w))
                   (rig_add ExtRing (tt_gen v) (tt_gen w)))
    by exact (ee_base (te_gen_add v w)).
  pose proof (ee_alt (cmon_plus V v w)) as H.
  change (@equiv _ (is_setoid (rig_setoid ExtRing))
            (rig_mul ExtRing (tt_gen (cmon_plus V v w))
                             (tt_gen (cmon_plus V v w)))
            (rig_zero ExtRing)) in H.
  rewrite Hsum in H.
  rewrite rig_distr_r, !rig_distr_l in H.
  rewrite (ext_alt v), (ext_alt w) in H.
  rewrite rig_add_zero_l, rig_add_zero_r in H.
  exact H.
Qed.

(** The projection T(V) → Λ(V) is the identity on terms; only the
    equivalence relation coarsens. *)
Program Definition ext_proj : TensorAlg ~{AAlg K}~> ExtAlg :=
  (({| rig_map := {| morphism := fun t : TTerm => t |} |}
     : TensorRing ~{Rng}~> ExtRing); _).
Next Obligation. intros s t H; exact (ee_base H). Qed.
Next Obligation. simpl; exact (et_refl TZ). Qed.
Next Obligation. intros s t; simpl; exact (et_refl _). Qed.
Next Obligation. simpl; exact (et_refl TO). Qed.
Next Obligation. intros s t; simpl; exact (et_refl _). Qed.
Next Obligation. intro a; simpl; exact (et_refl _). Qed.

Example ext_proj_computes (t : TTerm) : rig_map (`1 ext_proj) t = t := eq_refl.

(** ** Evaluation out of Λ(V)

    The same fold, on the same terms; only the respectfulness argument
    changes, and it is SEVEN cases rather than twenty — one per constructor
    of [et_eq].  The base case is [teval_respects] verbatim, and the new
    case is exactly the hypothesis that the given map is alternating. *)

Section ExtEvaluation.

Context (A : AAlgObject K).
Context (f : AltLinear V A).

Notation AR := (aalg_ring A).

Lemma exteval_respects (s t : TTerm) :
  et_eq s t → teval A (alt_lin f) s ≈ teval A (alt_lin f) t.
Proof.
  intro He.
  induction He as
    [ s t Hst
    | v
    | s s' t t' _ IHs _ IHt
    | s s' _ IHs
    | s s' t t' _ IHs _ IHt
    | s t _ IHst
    | s t w _ IHst _ IHtw ]; simpl.
  - exact (teval_respects A (alt_lin f) s t Hst).
  - rewrite (alt_sq f v); symmetry; apply (rig_map_zero (aalg_unit A)).
  - exact (rig_add_respects AR _ _ IHs _ _ IHt).
  - exact (ring_neg_respects AR _ _ IHs).
  - exact (rig_mul_respects AR _ _ IHs _ _ IHt).
  - exact (symmetry IHst).
  - exact (transitivity IHst IHtw).
Qed.

Program Definition ext_extend_ring : ExtRing ~{Rng}~> AR := {|
  rig_map := {| morphism := teval A (alt_lin f) |}
|}.
Next Obligation. intros s t He; exact (exteval_respects s t He). Qed.
Next Obligation. simpl; exact (rig_map_zero (aalg_unit A)). Qed.
Next Obligation. intros s t; simpl; reflexivity. Qed.
Next Obligation. simpl; exact (rig_map_one (aalg_unit A)). Qed.
Next Obligation. intros s t; simpl; reflexivity. Qed.

Lemma ext_extend_triangle :
  aalg_unit A ≈ ext_extend_ring ∘ aalg_unit ExtAlg.
Proof. intro a; simpl; reflexivity. Qed.

Definition ext_extend : ExtAlg ~{AAlg K}~> A :=
  (ext_extend_ring; ext_extend_triangle).

Example ext_extend_gen (v : carrier (cmon_setoid V)) :
  rig_map (`1 ext_extend) (tt_gen v) = alin_map (alt_lin f) v := eq_refl.

Example ext_extend_scal (a : carrier (rig_setoid (`1 K))) :
  rig_map (`1 ext_extend) (tt_scal a) = rig_map (aalg_unit A) a := eq_refl.

(* Uniqueness is [tensor_extend_unique] read at the coarser relation: the
   induction is on the TERM, not on the relation, so nothing about the
   quotient enters. *)
Lemma ext_extend_unique (g : ExtRing ~{Rng}~> AR)
  (Hscal : ∀ a, rig_map g (tt_scal a) ≈ rig_map (aalg_unit A) a)
  (Hgen : ∀ v, rig_map g (tt_gen v) ≈ alin_map (alt_lin f) v) (t : TTerm) :
  rig_map g t ≈ teval A (alt_lin f) t.
Proof.
  induction t as [ a | v | s IHs t IHt | s IHs | s IHs t IHt ]; simpl.
  - exact (Hscal a).
  - exact (Hgen v).
  - rewrite (rig_map_add g s t); exact (rig_add_respects AR _ _ IHs _ _ IHt).
  - rewrite (RigHom_neg ExtRing AR g s).
    exact (ring_neg_respects AR _ _ IHs).
  - rewrite (rig_map_mul g s t); exact (rig_mul_respects AR _ _ IHs _ _ IHt).
Qed.

End ExtEvaluation.

Lemma ext_alg_hom_scal (A : AAlgObject K) (g : ExtAlg ~{AAlg K}~> A)
  (a : carrier (rig_setoid (`1 K))) :
  rig_map (`1 g) (tt_scal a) ≈ rig_map (aalg_unit A) a.
Proof. symmetry; exact (`2 g a). Qed.

(** ** Mac Lane §III.1 Exercise 1 for Λ(V), in universal-arrow form

    Λ(V) represents the functor of alternating maps out of V, with the
    insertion as the universal element. *)

Definition ext_universal_element : AUniversalElement (AltFunctor V) ExtAlg.
Proof.
  unshelve econstructor.
  - exact ext_insert.
  - intros A f.
    unshelve econstructor.
    + exact (ext_extend A f).
    + intro v; simpl; reflexivity.
    + intros g Hg t; simpl.
      symmetry.
      apply (ext_extend_unique A f (`1 g)).
      * intro a; exact (ext_alg_hom_scal A g a).
      * intro v; exact (Hg v).
Defined.

Example ext_universal_elem_is_insert :
  @aue_elem _ (AltFunctor V) ExtAlg ext_universal_element = ext_insert
  := eq_refl.

Definition ext_universal_element_bundled : UniversalElement (AltFunctor V) :=
  UniversalElement_of_AUniversalElement ext_universal_element.

Definition ext_representation
  : @Curried_Hom (AAlg K) ExtAlg ≅[[AAlg K, Sets]] AltFunctor V :=
  ue_representation (AltFunctor V) ExtAlg ext_universal_element.

Definition ext_representable : Representable (AltFunctor V) :=
  Representable_of_UniversalElement ext_universal_element_bundled.

Definition ext_auniversal_arrow
  : AUniversalArrow SetsOne (AltFunctor V) ExtAlg :=
  AUniversalArrow_of_AUniversalElement (AltFunctor V) ExtAlg
    ext_universal_element.

End Algebras.

Arguments TTerm {K} V.
Arguments tt_scal {K V} a.
Arguments tt_gen {K V} v.
Arguments tt_add {K V} s t.
Arguments tt_neg {K V} s.
Arguments tt_mul {K V} s t.
Arguments tt_eq {K V} s t.
Arguments tt_refl {K V} s.
Arguments te_gen_zero {K} V.
Arguments TensorRing {K} V.
Arguments TensorAlg {K} V.
Arguments tensor_scal {K} V.
Arguments tensor_insert {K} V.
Arguments teval {K V} A f t.
Arguments tensor_extend {K V} A f.
Arguments tensor_extend_unique {K V} A f g Hscal Hgen t.
Arguments tensor_alg_hom_scal {K V} A g a.
Arguments et_eq {K V} s t.
Arguments et_refl {K V} s.
Arguments ExtRing {K} V.
Arguments ExtAlg {K} V.
Arguments ext_scal {K} V.
Arguments ext_insert {K} V.
Arguments ext_alt {K V} v.
Arguments ext_anticomm {K V} v w.
Arguments ext_proj {K} V.
Arguments ext_extend {K V} A f.
Arguments ext_universal_element {K} V.
Arguments ext_representation {K} V.
Arguments ext_representable {K} V.
Arguments ext_auniversal_arrow {K} V.

(** The universal property applied at its own object: the extension of
    each insertion along itself is the identity.  Each is the
    corresponding uniqueness lemma applied at the identity morphism, with
    both of its hypotheses met by reflexivity of the term relation. *)

Lemma tensor_extend_self {K : CRng} (V : RModObject (`1 K))
  (t : TTerm V) :
  rig_map (`1 (tensor_extend (TensorAlg V) (tensor_insert V))) t ≈ t.
Proof.
  symmetry.
  apply (tensor_extend_unique (TensorAlg V) (tensor_insert V)
           (@id Rng (TensorRing V))).
  - intro a; exact (tt_refl _).
  - intro v; exact (tt_refl _).
Qed.

Lemma ext_extend_self {K : CRng} (V : RModObject (`1 K)) (t : TTerm V) :
  rig_map (`1 (@ext_extend K V (@ExtAlg K V) (@ext_insert K V))) t ≈ t.
Proof.
  symmetry.
  apply (@ext_extend_unique K V (@ExtAlg K V) (@ext_insert K V)
           (@id Rng (@ExtRing K V))).
  - intro a; exact (et_refl _).
  - intro v; exact (et_refl _).
Qed.

(** * Mac Lane §III.1 Exercise 1: the tensor algebra as a universal arrow,
      and §IV.2 Exercise 1's left adjoint *)

Section TensorUniversal.

Context (K : CRng).

(** The universal mapping property, in the shape [universal_arrow_from_UMP]
    consumes: the insertion, read as a morphism of K-modules into the
    underlying module of T(V), factors every module map into the underlying
    module of an algebra. *)
Lemma tensor_universal (V : RMod (`1 K)) (A : AAlg K)
  (h : V ~{RMod (`1 K)}~> fobj[AAlg_Forget_Mod K] A) :
  ∃! g : TensorAlg V ~{AAlg K}~> A,
    h ≈ fmap[AAlg_Forget_Mod K] g ∘ module_hom_of_aalg_linear (tensor_insert V).
Proof.
  unshelve eexists.
  - exact (tensor_extend A (aalg_linear_of_module_hom h)).
  - intro v; simpl; reflexivity.
  - intros g Hg t; simpl.
    symmetry.
    apply (tensor_extend_unique A (aalg_linear_of_module_hom h) (`1 g)).
    + intro a; exact (tensor_alg_hom_scal A g a).
    + intro v; symmetry; exact (Hg v).
Qed.

Definition tensor_universal_arrow (V : RMod (`1 K))
  : UniversalArrow V (AAlg_Forget_Mod K) :=
  universal_arrow_from_UMP V (AAlg_Forget_Mod K) (TensorAlg V)
    (module_hom_of_aalg_linear (tensor_insert V)) (tensor_universal V).

(* The same content in the direct encoding, where the universal object is
   named rather than projected out of a comma category. *)
Program Definition tensor_auniversal_arrow (V : RMod (`1 K))
  : AUniversalArrow V (AAlg_Forget_Mod K) (TensorAlg V) := {|
  universal_arrow := module_hom_of_aalg_linear (tensor_insert V)
|}.
Next Obligation.
  intros V A h.
  unshelve eexists.
  - exact (tensor_extend A (aalg_linear_of_module_hom h)).
  - intro v; simpl; reflexivity.
  - intros g Hg t; simpl.
    symmetry.
    apply (tensor_extend_unique A (aalg_linear_of_module_hom h) (`1 g)).
    + intro a; exact (tensor_alg_hom_scal A g a).
    + intro v; exact (Hg v).
Qed.

(** Mac Lane §IV.2 Exercise 1, in the part this issue delivers: the tensor
    algebra is the left adjoint of the functor that forgets an associative
    K-algebra down to its underlying K-module.  Both come out of the
    generic machinery with no further proof. *)
Definition TensorFunctor : RMod (`1 K) ⟶ AAlg K :=
  LeftAdjointFunctorFromUniversalArrows (AAlg_Forget_Mod K)
    tensor_universal_arrow.

Definition tensor_adjunction : TensorFunctor ⊣ AAlg_Forget_Mod K :=
  AdjunctionFromUniversalArrows (AAlg_Forget_Mod K) tensor_universal_arrow.

(** The free functor's object part IS the term algebra, and the universal
    arrow IS the insertion: [universal_arrow_from_UMP] stores the supplied
    morphism as the second projection of the comma object it builds, so no
    proof is involved. *)
Example TensorFunctor_obj (V : RMod (`1 K)) :
  fobj[TensorFunctor] V = TensorAlg V := eq_refl.

Example tensor_arrow_is_insert (V : RMod (`1 K)) :
  @arrow _ _ V (AAlg_Forget_Mod K) (tensor_universal_arrow V)
    = module_hom_of_aalg_linear (tensor_insert V) := eq_refl.

(** The unit of the adjunction is the generator insertion, on the nose:
    [unit] is DERIVED in Theory/Adjunction.v as the transpose of the
    identity, so what it computes to has to be checked. *)
Definition tensor_unit (V : RMod (`1 K))
  : V ~{RMod (`1 K)}~> fobj[AAlg_Forget_Mod K] (fobj[TensorFunctor] V) :=
  @Category.Theory.Adjunction.unit _ _ _ _ tensor_adjunction V.

Example tensor_unit_is_gen (V : RMod (`1 K)) (v : carrier (cmon_setoid V)) :
  cmon_map (rm_hom (tensor_unit V)) v = tt_gen v := eq_refl.

End TensorUniversal.

(** * Non-degeneracy

    Nothing below is obtained by induction on [tt_eq] or [et_eq]: an
    induction on a quotienting relation cannot produce a negative
    statement.  Every separation is obtained by mapping OUT of the term
    algebra into a concrete algebra where the two candidates have visibly
    different values, which is the only route a presentation by generators
    and relations offers — the same route Instance/Rng/Polynomial.v takes
    for [poly_x_not_constant] and Instance/Mod/Tensor.v for its own
    negative results. *)

(** ** The tensor algebra is genuinely non-commutative

    The witness module is the underlying ℤ-module of
    Instance/Rng/Algebras/Associative.v's upper-triangular matrix algebra,
    and the witness linear map is [alin_id], the identity.  So the
    extension sends a generator [tt_gen x] to x itself, and two generators
    whose matrices do not commute give two products of generators that
    cannot be identified in T(V).  This is the fact that made [AAlg]
    necessary: over [KAlg] this T(V) does not exist. *)

Definition UT2_Mod : RModObject (`1 Int_CRng) := AAlg_RMod UT2_AAlg.

Definition tensor_to_UT2
  : @TensorAlg Int_CRng UT2_Mod ~{AAlg Int_CRng}~> UT2_AAlg :=
  tensor_extend UT2_AAlg (alin_id UT2_AAlg).

(* The extension computes on generators and on products of them. *)
Example tensor_to_UT2_gen (x : ut2) :
  rig_map (`1 tensor_to_UT2) (@tt_gen Int_CRng UT2_Mod x) = x := eq_refl.

Example tensor_to_UT2_e11_e12 :
  rig_map (`1 tensor_to_UT2) (tt_mul (@tt_gen Int_CRng UT2_Mod ut2_e11) (@tt_gen Int_CRng UT2_Mod ut2_e12))
    = ut2_e12 := eq_refl.

Example tensor_to_UT2_e12_e11 :
  rig_map (`1 tensor_to_UT2) (tt_mul (@tt_gen Int_CRng UT2_Mod ut2_e12) (@tt_gen Int_CRng UT2_Mod ut2_e11))
    = ut2_zero := eq_refl.

Theorem tensor_not_commutative :
  tt_eq (tt_mul (@tt_gen Int_CRng UT2_Mod ut2_e11) (@tt_gen Int_CRng UT2_Mod ut2_e12))
        (tt_mul (@tt_gen Int_CRng UT2_Mod ut2_e12) (@tt_gen Int_CRng UT2_Mod ut2_e11)) → False.
Proof.
  intro H.
  apply UT2_not_commutative.
  exact (proper_morphism (rig_map (`1 tensor_to_UT2)) _ _ H).
Qed.

(* A generator is not a scalar: the module used is not the zero module,
   which is the degeneracy the header names. *)
Theorem tensor_gen_not_scalar (r : Z) :
  tt_eq (@tt_gen Int_CRng UT2_Mod ut2_e12) (@tt_scal Int_CRng UT2_Mod r) → False.
Proof.
  intro H.
  pose proof (proper_morphism (rig_map (`1 tensor_to_UT2)) _ _ H) as H2.
  unfold ut2_eqT, ut2_e12, ut2_scal in H2.
  inversion H2.
Qed.

(* ...and the base ring is not the trivial ring: 1 ≉ 0 already in T(V). *)
Theorem tensor_nontrivial :
  tt_eq (@tt_scal Int_CRng UT2_Mod 1%Z) (@tt_scal Int_CRng UT2_Mod 0%Z)
    → False.
Proof.
  intro H.
  pose proof (proper_morphism (rig_map (`1 tensor_to_UT2)) _ _ H) as H2.
  unfold ut2_eqT, ut2_scal in H2.
  inversion H2.
Qed.

(** ** A four-dimensional algebra, to separate v∧w from w∧v

    The classical description of the exterior algebra of a rank-two free
    module over ℤ, written out by hand: the quadruple (s, a, b, p) stands
    for s + a·e₁ + b·e₂ + p·e₁∧e₂, and the product is the one the
    relations e₁∧e₁ = e₂∧e₂ = 0 and e₁∧e₂ = −e₂∧e₁ dictate.  It is written
    out rather than obtained from [ExtAlg] because its purpose is to be a
    TARGET: separations are proved by mapping OUT of a term algebra into
    something whose elements can be told apart by computation, and
    [ExtAlg] of anything has no normal form, so nothing could be told
    apart inside it.  NO isomorphism between [Lam2] and any [ExtAlg] is
    proved or claimed; all that is used below is that [Lam2] is an object
    of [AAlg Int_CRng] — the scalars are central because ℤ is
    commutative — and that a suitable alternating map lands in it. *)

Definition lam2 : Type := (Z * Z * Z * Z)%type.

Definition lam2_eqT (x y : lam2) : Type := x = y.

Lemma lam2_eqT_Equivalence : Equivalence lam2_eqT.
Proof.
  constructor; unfold lam2_eqT.
  - intro x; reflexivity.
  - intros x y H; now symmetry.
  - intros x y z H1 H2; now transitivity y.
Qed.

Definition lam2_setoid_object : SetoidObject := {|
  carrier := lam2;
  is_setoid := {| equiv := lam2_eqT; setoid_equiv := lam2_eqT_Equivalence |}
|}.

Definition lam2_zero : lam2 := (0, 0, 0, 0)%Z.
Definition lam2_one : lam2 := (1, 0, 0, 0)%Z.

Definition lam2_add (x y : lam2) : lam2 :=
  match x, y with
  | (s, a, b, p), (s', a', b', p') =>
      ((s + s')%Z, (a + a')%Z, (b + b')%Z, (p + p')%Z)
  end.

Definition lam2_neg (x : lam2) : lam2 :=
  match x with (s, a, b, p) => ((- s)%Z, (- a)%Z, (- b)%Z, (- p)%Z) end.

Definition lam2_mul (x y : lam2) : lam2 :=
  match x, y with
  | (s, a, b, p), (s', a', b', p') =>
      ((s * s')%Z, (s * a' + a * s')%Z, (s * b' + b * s')%Z,
       (s * p' + a * b' - b * a' + p * s')%Z)
  end.

Definition lam2_scal (r : Z) : lam2 := (r, 0, 0, 0)%Z.

Lemma lam2_eq4 (s a b p s' a' b' p' : Z) :
  s = s' → a = a' → b = b' → p = p' →
  ((s, a, b, p) : lam2) = (s', a', b', p').
Proof. intros H1 H2 H3 H4; now subst. Qed.

Ltac lam2_crunch :=
  cbv beta iota delta
    [lam2_eqT lam2_add lam2_neg lam2_mul lam2_zero lam2_one lam2_scal];
  apply lam2_eq4; ring.

Ltac lam2_1 := intros [ [ [ ? ? ] ? ] ? ]; lam2_crunch.
Ltac lam2_2 := intros [ [ [ ? ? ] ? ] ? ] [ [ [ ? ? ] ? ] ? ]; lam2_crunch.
Ltac lam2_3 := intros [ [ [ ? ? ] ? ] ? ] [ [ [ ? ? ] ? ] ? ] [ [ [ ? ? ] ? ] ? ]; lam2_crunch.

Lemma lam2_add_respects : Proper (lam2_eqT ==> lam2_eqT ==> lam2_eqT) lam2_add.
Proof. intros x y Hxy z w Hzw; unfold lam2_eqT in *; now subst. Qed.

Lemma lam2_mul_respects : Proper (lam2_eqT ==> lam2_eqT ==> lam2_eqT) lam2_mul.
Proof. intros x y Hxy z w Hzw; unfold lam2_eqT in *; now subst. Qed.

Lemma lam2_neg_respects : Proper (lam2_eqT ==> lam2_eqT) lam2_neg.
Proof. intros x y Hxy; unfold lam2_eqT in *; now subst. Qed.

Program Definition Lam2_Rig : RigObject := {|
  rig_setoid := lam2_setoid_object;
  rig_zero := lam2_zero;
  rig_add := lam2_add;
  rig_one := lam2_one;
  rig_mul := lam2_mul;
  rig_add_respects := lam2_add_respects;
  rig_mul_respects := lam2_mul_respects
|}.
Next Obligation. lam2_3. Qed.
Next Obligation. lam2_2. Qed.
Next Obligation. lam2_1. Qed.
Next Obligation. lam2_3. Qed.
Next Obligation. lam2_1. Qed.
Next Obligation. lam2_1. Qed.
Next Obligation. lam2_3. Qed.
Next Obligation. lam2_3. Qed.
Next Obligation. lam2_1. Qed.
Next Obligation. lam2_1. Qed.

Program Definition Lam2 : RingObject := {|
  ring_rig := Lam2_Rig;
  ring_neg := lam2_neg;
  ring_neg_respects := lam2_neg_respects
|}.
Next Obligation. lam2_1. Qed.

Definition lam2_scal_proper
  : Proper (@equiv _ (is_setoid Z_setoid_object)
              ==> @equiv _ (is_setoid lam2_setoid_object)) lam2_scal :=
  fun r s H => f_equal (fun z : Z => ((z, 0, 0, 0) : lam2)%Z) H.

Definition lam2_scal_morphism
  : SetoidMorphism (is_setoid Z_setoid_object) (is_setoid lam2_setoid_object) :=
  {| morphism := lam2_scal; proper_morphism := lam2_scal_proper |}.

Lemma lam2_scal_add (a b : Z) :
  lam2_scal (a + b)%Z = lam2_add (lam2_scal a) (lam2_scal b).
Proof. unfold lam2_scal, lam2_add; apply lam2_eq4; ring. Qed.

Lemma lam2_scal_mul (a b : Z) :
  lam2_scal (a * b)%Z = lam2_mul (lam2_scal a) (lam2_scal b).
Proof. unfold lam2_scal, lam2_mul; apply lam2_eq4; ring. Qed.

Program Definition lam2_scalar : Int_Ring ~{Rng}~> Lam2 := {|
  rig_map := lam2_scal_morphism
|}.
Next Obligation. reflexivity. Qed.
Next Obligation. intros a b; exact (lam2_scal_add a b). Qed.
Next Obligation. reflexivity. Qed.
Next Obligation. intros a b; exact (lam2_scal_mul a b). Qed.

Lemma lam2_scalar_central : ∀ (k : Z) (a : lam2),
  rig_mul Lam2 (rig_map lam2_scalar k) a
    ≈ rig_mul Lam2 a (rig_map lam2_scalar k).
Proof. intros k [ [ [ s x ] y ] p ]; lam2_crunch. Qed.

Definition Lam2_AAlg : AAlgObject Int_CRng :=
  Build_AAlgObject Int_CRng Lam2 lam2_scalar lam2_scalar_central.

(* The two generators, and the products that separate. *)
Definition lam2_e1 : lam2 := (0, 1, 0, 0)%Z.
Definition lam2_e2 : lam2 := (0, 0, 1, 0)%Z.

Example lam2_e1_e2 : rig_mul Lam2 lam2_e1 lam2_e2 = (0, 0, 0, 1)%Z := eq_refl.
Example lam2_e2_e1 : rig_mul Lam2 lam2_e2 lam2_e1 = (0, 0, 0, -1)%Z := eq_refl.
Example lam2_e1_e1 : rig_mul Lam2 lam2_e1 lam2_e1 = lam2_zero := eq_refl.

(** ** Λ(V) does not collapse

    The witness module is the underlying ℤ-module of [Lam2], and the
    witness alternating map is the projection onto the degree-one part —
    linear because the module structure is componentwise, and alternating
    because the square of a degree-one element is (ab − ba) in the top
    slot, which is zero. *)

Definition Lam2_Mod : RModObject (`1 Int_CRng) := AAlg_RMod Lam2_AAlg.

Definition lam2_deg1 (x : lam2) : lam2 :=
  match x with (_, a, b, _) => (0, a, b, 0)%Z end.

Definition lam2_deg1_proper
  : Proper (@equiv _ (is_setoid lam2_setoid_object)
              ==> @equiv _ (is_setoid lam2_setoid_object)) lam2_deg1 :=
  fun x y H => f_equal lam2_deg1 H.

Program Definition lam2_deg1_lin : AAlgLinear Lam2_Mod Lam2_AAlg := {|
  alin_map := {| morphism := lam2_deg1; proper_morphism := lam2_deg1_proper |}
|}.
Next Obligation.
  intros [ [ [ s a ] b ] p ] [ [ [ s' a' ] b' ] p' ].
  cbv beta iota delta [lam2_eqT lam2_add lam2_deg1]; apply lam2_eq4; ring.
Qed.
Next Obligation.
  intros r [ [ [ s a ] b ] p ].
  cbv beta iota delta [lam2_eqT lam2_mul lam2_scal lam2_deg1]; simpl.
  apply lam2_eq4; ring.
Qed.

Program Definition lam2_deg1_alt : AltLinear Lam2_Mod Lam2_AAlg := {|
  alt_lin := lam2_deg1_lin
|}.
Next Obligation.
  intros [ [ [ s a ] b ] p ].
  cbv beta iota delta [lam2_eqT lam2_mul lam2_zero lam2_deg1]; simpl.
  apply lam2_eq4; ring.
Qed.

Definition ext_to_Lam2
  : @ExtAlg Int_CRng Lam2_Mod ~{AAlg Int_CRng}~> Lam2_AAlg :=
  ext_extend Lam2_AAlg lam2_deg1_alt.

Example ext_to_Lam2_gen (x : lam2) :
  rig_map (`1 ext_to_Lam2) (@tt_gen Int_CRng Lam2_Mod x) = lam2_deg1 x := eq_refl.

Example ext_to_Lam2_e1_e2 :
  rig_map (`1 ext_to_Lam2) (tt_mul (@tt_gen Int_CRng Lam2_Mod lam2_e1) (@tt_gen Int_CRng Lam2_Mod lam2_e2))
    = (0, 0, 0, 1)%Z := eq_refl.

Example ext_to_Lam2_e2_e1 :
  rig_map (`1 ext_to_Lam2) (tt_mul (@tt_gen Int_CRng Lam2_Mod lam2_e2) (@tt_gen Int_CRng Lam2_Mod lam2_e1))
    = (0, 0, 0, -1)%Z := eq_refl.

(* Λ(V) is not the trivial algebra. *)
Theorem ext_nontrivial :
  et_eq (@tt_scal Int_CRng Lam2_Mod 1%Z) (@tt_scal Int_CRng Lam2_Mod 0%Z)
    → False.
Proof.
  intro H.
  pose proof (proper_morphism (rig_map (`1 ext_to_Lam2)) _ _ H) as H2.
  unfold lam2_eqT, lam2_scal in H2.
  inversion H2.
Qed.

(* A generator of Λ(V) is not a scalar — so the alternating relation does
   not force the generators into the base ring, and in particular
   v ∧ v ≈ 0 does not force v ≈ 0. *)
Theorem ext_gen_not_scalar (r : Z) :
  et_eq (@tt_gen Int_CRng Lam2_Mod lam2_e1) (@tt_scal Int_CRng Lam2_Mod r) → False.
Proof.
  intro H.
  pose proof (proper_morphism (rig_map (`1 ext_to_Lam2)) _ _ H) as H2.
  unfold lam2_eqT, lam2_deg1, lam2_e1, lam2_scal in H2.
  inversion H2.
Qed.

(* ANTISYMMETRY IS NOT VACUOUS: the two orders of a product of distinct
   generators are provably different elements of this Λ(V).  Together with
   [ext_anticomm] — which says the second is the negative of the first —
   this exhibits a Λ in which the anticommutation law has content, rather
   than one in which both sides happen to be zero. *)
Theorem ext_anticomm_nontrivial :
  et_eq (tt_mul (@tt_gen Int_CRng Lam2_Mod lam2_e1) (@tt_gen Int_CRng Lam2_Mod lam2_e2))
        (tt_mul (@tt_gen Int_CRng Lam2_Mod lam2_e2) (@tt_gen Int_CRng Lam2_Mod lam2_e1)) → False.
Proof.
  intro H.
  pose proof (proper_morphism (rig_map (`1 ext_to_Lam2)) _ _ H) as H2.
  unfold lam2_eqT in H2.
  inversion H2.
Qed.

(* ...and the generators themselves are distinct, so the pair above is a
   genuine pair. *)
Theorem ext_gens_distinct :
  et_eq (@tt_gen Int_CRng Lam2_Mod lam2_e1) (@tt_gen Int_CRng Lam2_Mod lam2_e2) → False.
Proof.
  intro H.
  pose proof (proper_morphism (rig_map (`1 ext_to_Lam2)) _ _ H) as H2.
  unfold lam2_eqT, lam2_deg1, lam2_e1, lam2_e2 in H2.
  inversion H2.
Qed.

(* The square of a generator IS zero in Λ(V) — and the same equation is
   REFUTABLE in T(V) over the very same module.  That is what makes the
   results above results about the exterior algebra rather than facts that
   were already true upstairs: the quotient does something.  The separating
   target is the upper-triangular matrix algebra, reached by the linear map
   that reads off the e₁-coefficient; the image of e₁ is then the
   idempotent E₁₁, whose square is itself. *)

Example ext_gen_square_zero :
  et_eq (tt_mul (@tt_gen Int_CRng Lam2_Mod lam2_e1)
                (@tt_gen Int_CRng Lam2_Mod lam2_e1))
        (@tt_scal Int_CRng Lam2_Mod 0%Z) := @ext_alt Int_CRng Lam2_Mod lam2_e1.

Definition lam2_coeff1 (x : lam2) : ut2 :=
  match x with (_, a, _, _) => (a, 0, 0)%Z end.

Definition lam2_coeff1_proper
  : Proper (@equiv _ (is_setoid lam2_setoid_object)
              ==> @equiv _ (is_setoid ut2_setoid_object)) lam2_coeff1 :=
  fun x y H => f_equal lam2_coeff1 H.

Program Definition lam2_coeff1_lin : AAlgLinear Lam2_Mod UT2_AAlg := {|
  alin_map := {| morphism := lam2_coeff1;
                 proper_morphism := lam2_coeff1_proper |}
|}.
Next Obligation.
  intros [ [ [ s a ] b ] p ] [ [ [ s' a' ] b' ] p' ].
  cbv beta iota delta [ut2_eqT lam2_add ut2_add lam2_coeff1];
    apply ut2_eq3; ring.
Qed.
Next Obligation.
  intros r [ [ [ s a ] b ] p ].
  cbv beta iota delta
    [ut2_eqT lam2_mul lam2_scal ut2_mul ut2_scal lam2_coeff1]; simpl.
  apply ut2_eq3; ring.
Qed.

Definition tensor_lam2_to_UT2
  : @TensorAlg Int_CRng Lam2_Mod ~{AAlg Int_CRng}~> UT2_AAlg :=
  tensor_extend UT2_AAlg lam2_coeff1_lin.

Example tensor_lam2_to_UT2_e1 :
  rig_map (`1 tensor_lam2_to_UT2) (@tt_gen Int_CRng Lam2_Mod lam2_e1)
    = ut2_e11 := eq_refl.

Theorem tensor_gen_square_not_zero :
  tt_eq (tt_mul (@tt_gen Int_CRng Lam2_Mod lam2_e1)
                (@tt_gen Int_CRng Lam2_Mod lam2_e1))
        (@tt_scal Int_CRng Lam2_Mod 0%Z) → False.
Proof.
  intro H.
  pose proof (proper_morphism (rig_map (`1 tensor_lam2_to_UT2)) _ _ H) as H2.
  unfold ut2_eqT, lam2_coeff1, lam2_e1, ut2_scal in H2.
  inversion H2.
Qed.
