Require Import Category.Lib.
Require Import Category.Theory.Category.
Require Import Category.Theory.Functor.
Require Import Category.Theory.Morphisms.
Require Import Category.Structure.Complete.
Require Import Category.Adjunction.SAFT.
Require Import Category.Instance.Sets.

Generalizable All Variables.

(** * SAFT's covering datum is refutable at the identity of [Sets] *)

(* nLab:      https://ncatlab.org/nlab/show/adjoint+functor+theorem
   Wikipedia: https://en.wikipedia.org/wiki/Cantor%27s_theorem

   Adjunction/SAFT.v states the special adjoint functor theorem over five
   premises: completeness [comp], cone-level preservation [cont], a
   cogenerating family [G], a subobject index [WP], and the covering datum

     SubobjectCover U comp G WP :=
       ∀ d c (h : d ~> U c), { i & { s : d ~> U (sub_dom i) &
         { t : sub_dom i ~> c & fmap[U] t ∘ s ≈ h } } }

   where [i] ranges over the index of the ONE object [cogen_prod comp G],
   the product of the cogenerating family.  This file proves that the datum
   is EMPTY at [U := Id] on [Sets], whatever [comp], [G] and [WP] are:
   [SubobjectCover_Id_Sets_absurd].

   THE ARGUMENT.  Adjunction/SAFT.v's [SubobjectCover_Id_retract] is the
   datum at [d := c] and [h := id]: every object [c] is a retract
   [t ∘ s ≈ id] of the domain [m] of one indexed mono into
   [Q := cogen_prod comp G].  Take [c] to be the setoid of [Prop]-valued
   predicates on the carrier of [Q], compared pointwise by [iff].  The
   mono is injective (Instance/Sets.v's [injectivity_is_monic]), so
   Cantor's diagonal [Dg a := ∀ y, mono y ≈ a → ¬ t y a] and the point
   [mono (s Dg)] give [Dg] at that point exactly when not.  [Prop] is used
   so that membership needs no decision procedure; a [bool]-valued
   diagonal would have to decide whether a point is in the image of the
   mono.

   WHY IT MATTERS.  Classically [Sets] is complete, well-powered and
   cogenerated by a two-element set, and [Id] preserves limits: the
   hypotheses of the special adjoint functor theorem hold at [Id[Sets]],
   and so does its conclusion.  That is a classical meta-argument; in
   tree, completeness and preservation are inhabited (Instance/Sets/
   Complete.v's [Sets_Complete], Adjunction/GAFT/Sets.v's
   [Sets_Id_PreservesImageLimit]), well-poweredness only under
   [Untruncate] (Instance/Sets/WellPowered.v's
   [Sets_WellPowered_untruncate]), and no [Cogenerator] is built at [Sets]
   anywhere.  Adjunction/GAFT/Sets.v runs [GAFT] at this very functor
   with every premise supplied in tree.  [SAFT]'s covering datum is not
   the consequence of the classical hypotheses, because [cogen_prod] does
   not depend on [d]: the classical proof works in the comma category,
   whose cogenerating set nLab gives as "the set of all objects of the
   form d→Rc_α", and whose initial object is "the intersection = pullback
   of all subobjects of ∏_s k_s" -- a product over arrows out of [d].  So
   no well-poweredness result discharges [cover]: Adjunction/SAFT/
   WellPowered.v's [WellPowered_SubobjectIndex] supplies [WP], and the
   datum refuted here is what remains.

   UNIVERSES, measured with [Set Printing Universes. About …] (stdlib
   bounds left out).  The lemma's universes are DECLARED in its binder:

     SubobjectCover_Id_Sets_absurd@{r g w u c h cobj} :
       ∀ (comp : Complete@{r g h cobj})
         (G : Cogenerator@{g cobj h} Sets@{h cobj})
         (WP : ∀ x : obj[Sets@{h cobj}], SubobjectIndex@{w cobj h} x),
       ¬ SubobjectCover@{c w g u r cobj cobj h} Id[Sets@{h cobj}] comp G WP
       (* Set < h, h < u, h < cobj, g <= r, w <= c, h <= r, h <= c,
          cobj <= c *)

   [SubobjectCover]'s fourth slot [u] is [cogen_prod]'s product universe,
   [DiscreteCat_Functor]'s, and the only bound on it is [h < u]: nothing
   relates it to the object universe [cobj].  [SAFT]'s readback (Adjunction/
   SAFT.v) at [C = D = Sets@{h cobj}] asks for [Complete@{h h h cobj}],
   [Cogenerator@{h cobj h}], [SubobjectIndex@{u3 cobj h}] with [u3 <= h]
   and [SubobjectCover@{u2 u3 h u h cobj cobj h}] with [h < u]; the lemma
   at [r = g = h], [w = u3], [c = u2] is that instance, and every
   constraint in its block except [Set < h] follows from SAFT's together
   with [h < cobj], which [Sets@{h cobj}] carries itself.  So the
   refutation covers exactly the instances [SAFT] asks for at
   [Sets@{h cobj}] with [Set < h]; [Set < h] comes from the [Prop]-valued
   predicates.
   [SubobjectCover_Id_Sets_absurd_at_SAFT] is the positive control, the
   lemma applied at exactly that instance with [cobj < u] declared rigid;
   in a scratch file the same application with [u < cobj] declared rigid
   is accepted as well.  The binder is load-bearing: left unannotated,
   minimization set the fourth slot to [cobj], and the application at
   [cobj < u] was refused, the unifier asking for [cogen_prod]'s instance
   at [cobj] where the cover has it at [u].

   MEASUREMENTS.  Two constants ([.glob] heads), no [Program] obligation,
   each "Closed under the global context" by its fully qualified name.
   The lemma is [Qed], a refutation carrying no data; the control is a
   transparent application of it.  The file is a satellite so that
   Adjunction/SAFT.v, which is stated over an arbitrary category, does not
   import Instance/Sets.v.

   NOT DELIVERED.  No refutation at [Sets@{Set _}] (the [Set < h] above),
   and none at any functor but [Id].  No re-shaped [SAFT]: its statement,
   [SAFT_solution_set] and Adjunction/Representability/Sets.v's
   [saft_representable] are unchanged, and a covering datum over a
   [d]-dependent product -- the classical one -- is left for a separate
   issue. *)

Lemma SubobjectCover_Id_Sets_absurd@{r g w u c h cobj |
    Set < h, h < cobj, h < u +}
  (comp : @Complete@{r g h cobj} Sets@{h cobj})
  (G : Cogenerator@{g cobj h} Sets@{h cobj})
  (WP : ∀ x : Sets@{h cobj}, SubobjectIndex@{w cobj h} x) :
  SubobjectCover@{c w g u r cobj cobj h} (@Id Sets@{h cobj}) comp G WP →
  False.
Proof.
  intros cover.
  set (Q := cogen_prod comp G).
  (* The Prop-valued predicates on the carrier of [Q], compared pointwise
     by logical equivalence. *)
  unshelve epose (PQ := {| carrier := carrier Q → Prop;
                           is_setoid :=
                             {| equiv := fun A B : carrier Q → Prop =>
                                           ∀ a, iff (A a) (B a) |} |}
                  : obj[Sets]).
  { constructor.
    - intros A a; exact (conj (fun h => h) (fun h => h)).
    - intros A B H a; exact (conj (proj2 (H a)) (proj1 (H a))).
    - intros A B C0 H1 H2 a;
        exact (conj (fun h => proj1 (H2 a) (proj1 (H1 a) h))
                    (fun h => proj2 (H1 a) (proj2 (H2 a) h))). }
  destruct (SubobjectCover_Id_retract comp G WP cover PQ) as [i [s [t e]]].
  set (m := sub_dom (WP Q) i) in *.
  set (mono := sub_mono (WP Q) i).
  pose proof (snd (injectivity_is_monic mono) (sub_monic (WP Q) i)) as inj.
  simpl in e.
  (* Cantor's diagonal: the points of [Q] that do not satisfy the predicate
     their preimage names. *)
  pose (Dg := fun a : carrier Q => ∀ y : carrier m, mono y ≈ a → ~ (t y a)).
  pose (a := mono (s Dg)).
  assert (notD : ~ Dg a).
  { intros H.
    apply (H (s Dg) (reflexivity _)).
    exact (proj2 (e Dg a) H). }
  apply notD.
  intros y Hy Hty.
  apply notD.
  pose proof (inj y (s Dg) Hy) as Hys.
  apply (proj1 (e Dg a)).
  exact (proj1 (proper_morphism t y (s Dg) Hys a) Hty).
Qed.

(* Positive control: the lemma applied at the instance [SAFT] itself
   consumes (SAFT.v's readback, at [C = D = Sets@{h cobj}]), with the
   [cogen_prod] slot [u] held strictly above the object universe [cobj].
   Left unannotated, the lemma had that slot minimized to [cobj], and this
   application was refused. *)
Definition SubobjectCover_Id_Sets_absurd_at_SAFT@{cobj h u u2 u3 |
    Set < h, h < cobj, cobj < u, u3 <= h +}
  (comp : @Complete@{h h h cobj} Sets@{h cobj})
  (G : Cogenerator@{h cobj h} Sets@{h cobj})
  (WP : ∀ x : Sets@{h cobj}, SubobjectIndex@{u3 cobj h} x)
  (cover : SubobjectCover@{u2 u3 h u h cobj cobj h}
             (@Id Sets@{h cobj}) comp G WP) : False :=
  SubobjectCover_Id_Sets_absurd comp G WP cover.
